### ISSUE TITLE
Empty app crashes

### ISSUE THREAD

**Issue by stigi** [Simbul/baker#1]
Hey,

I like the idea of baker & will keep an I on it.
There is an issue when opening opening the newly checked out project & running it straight away.

fix: https://gist.github.com/661151

**Comment by Simbul** [comment]
Thanks for pointing this out, we will look into the issue and into your solution :)

**Comment by folletto** [comment]
I've just tested and pushed the fix into the codebase.
Thank you! You're Baker's first contributor! :D
