### ISSUE TITLE
Shelf customization: interesting examples

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1002]
Here's an issue to keep track of interesting customizations of the original shelf.

**The Briefing**
- info button which displays HTML content
- no refresh button

![photo 1](https://f.cloud.github.com/assets/1521015/768098/afd17adc-e896-11e2-9138-c61b246add78.PNG)

**BCN Cocina**
- pagination for issues
- display of covers with staples
- additional info for issues (free / paid)
- download indicator on the cover
- nice opening of an issue
- no refresh button

![photo 4](https://f.cloud.github.com/assets/1521015/768107/3c229688-e897-11e2-9849-68c8c1c98337.PNG)

![photo 3](https://f.cloud.github.com/assets/1521015/768124/c577e00a-e897-11e2-8817-c05b4825bd91.PNG)

![photo 2](https://f.cloud.github.com/assets/1521015/768126/cb2f5208-e897-11e2-938d-266ebf24d580.PNG)

**Comment by fturner19** [comment]
Very elegant styling of the shelf. Will you be sharing your code edits with the community!

**Comment by benoitchantre** [comment]
I'm not the author/developer of these apps.
@freney, the developer of _The Briefing_ has already written a complete [blog post](http://freney.org/2013/07/03/modifying-the-baker-framework/), maybe there will be a pull request.
@fturner19, if you have other nice examples of customization, feel free to post them here.

**Comment by MaverickWar** [comment]
I also would love to see some code to make similar customizations, i have seen the code for the info and refresh edit but i seem to mess my build up every time i make any of these changes, does anyone have this working in a full piece of code i can copy and paste, there isn't much info on what to replace in the instructions.

Thanks

**Comment by benoitchantre** [comment]
@MaverickWar, did you see the pull request #1004? It will be part of the master sooner or later.

**Comment by MaverickWar** [comment]
I didn't see that no, pleased to see that going in though, is there any chance of getting a tutorial on how you created the designs on those 2 projects, they look absolutely stunning. I think it would be very beneficial to all.

**Comment by benoitchantre** [comment]
@MaverickWar, as said before, I'm not the author/developer of these apps.
You can contact the developer of BCN Cocina to see if he is open to share the code concerning that customization.

**Comment by MaverickWar** [comment]
Sorry i must have missed that, is the developer of BCN Cocina a member on this forum?

**Comment by benoitchantre** [comment]
Yes, here is his [profile](https://github.com/belgo)

**Comment by nin9creative** [comment]
I'm pretty sure that the BCN Cocina is/was using the old Bakershelf fork that I did a long time back (prior to Baker creating their shelf view / newsstand integration).

The book cover image (with the side staple look) and the progress indicator on the book cover were things we did in that fork.  You can take a look here.  It's way out of date of anything current in the Baker main repo though.  You might be able to reverse engineer some of the stuff if you wanted to implement it in the current code.

https://github.com/nin9creative/baker/tree/bakershelf-newsstandkit

**Comment by MaverickWar** [comment]
thanks for that andrew but his version has a shelf also doesnt it? so why did you guys move from this design style?

**Comment by nin9creative** [comment]
Umm, yes that fork is a newsstand enabled shelf.  However it was a little "hackish" because at that time the Baker viewer code wasn't really designed to be used aside from a single book publication view.

The Baker guys did some major refactoring and then introduced their own shelf.  There are a few publications that used the fork - however at this point I wouldn't use it, as its pretty out of date....

However the graphics are there for the book cover mask...

Andrew

**Comment by folletto** [comment]
I'm closing this since it was a discussion and it's more than three months old now. :)
