### ISSUE TITLE
Test accounts from other countries can't connect to iTunes store

### ISSUE THREAD

**Issue by nicholasmartin** [Simbul/baker#1006]
I have setup a server that handles subscriptions and purchases in rails based on the demo server setup provided by Baker.

I'm curious if others have tested their purchases/subscriptions with iTunes test accounts that are attached to different stores compared to the device/location.

If I test my purchases/subscriptions with a test user from the same store that Baker initially opens in, then everything works fine. As an example, my iPad is bound to the Danish store and with a danish test user this works out fine. The iOS simulator starts up in Indonesia (that's where I'm currently located) and if I use an Indonesian test user it all works fine.

However, when I create a test user that isn't from the correct initial store I get an error. The flow is like this:

1) Launch Baker on my iPad (it shows up in Danish currency)
2) Try to buy with an US test user
3) Get the "only valid in the US store message"
4) Tries to switch stores
5) Fails and I get the notification "Could not connect to iTunes store" on my iPad
6) The Xcode log shows Payment transaction failure: Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo=0xeb1eb20 {NSLocalizedDescription=Cannot connect to iTunes Store}
7) I hit refresh in Baker (on my iPad still)
8) The currencies now change to $ in my shelf (although the subscription still shows in DKK)
9) I click buy/subscribe and it works

Not sure (but probably likely) if it's my code or something else and just wanted to hear if anyone else have tried with different stores while testing (this all happens in the sandbox mode)?

**Comment by folletto** [comment]
I'm not sure it's a Baker question. What did they answer you on Apple Development Forums (or Stackoverflow)?

**Comment by nicholasmartin** [comment]
I actually wanted to ask in here first because if others have successfully tested with different store countries, then it's most likely something I've done wrong :)

I have posted here in case you want to follow along:
https://devforums.apple.com/thread/195842

**Comment by freney** [comment]
From memory I got the same flow as you, but I figured that was ok since you'll have the same experience in the iTunes store too. Change to a different country from your account, try and buy something, it'll give you an error and switch store for you automatically. Then you'll be able to purchase.

So I'd say it's expected behaviour.

**Comment by nicholasmartin** [comment]
Thing is, in my app, the store switch doesn't seem to happen. I have to hit the refresh button before the shelf is reloaded with the correct currency.

**Comment by freney** [comment]
It does switch, you just don't see it.

The prices are loaded when the refresh method is called, and a failed transaction won't trigger that. But the fact that if you refresh you see the new currency means that the store has switched regions, and you've now asked for a price refresh.

**Comment by nicholasmartin** [comment]
Okay so this will work as expected in a live production app? Just want to be sure, as it doesn't feel right when testing it out in sandbox. Thanks for your feedback, much appreciated!
