### ISSUE TITLE
"Lublu" Woman's Weekly finally in the App Store!

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#1008]
Latvian Woman's Weekly "Lublu" (in russian) finally up and running in the AppStore! :-)
Even version 1.1 :-)

https://itunes.apple.com/us/app/zurnal-lublu!/id651648556?ls=1&mt=8
(any feedback will be greatly appreciated)

Davide, Marco, Alessandro - thank you guys for the great framework and **greatest support** via the Github's forum. 

I would like to donate some money to support your work.
Please share the necessary credentials.

Thank you again!

**Comment by folletto** [comment]
Congratulations! :)
And thank you very much for the kind words. We are always trying our best in the little time we have, so your thanks are really the highest reward for us. :)

If you want to donate, you can use the website: http://bakerframework.com/donate :)

**Comment by divlv** [comment]
Done. 
Thank you again, and waiting for the framework updates ;-)
