### ISSUE TITLE
Delete transition with page number

### ISSUE THREAD

**Issue by JoseTejera** [Simbul/baker#101]
Hello, i'm actually making a magazine with Baker Framework and i'd like to delete the transition that shows the page number. Thanks!

**Comment by folletto** [comment]
What do you mean by deleting the transition? :)

**Comment by JoseTejera** [comment]
I mean hide it. I just want to show the pages not the page number after the page shows up.

**Comment by folletto** [comment]
We'd love to show the pages too. ;)
Unfortunately, that's very hard. See Issue #27. :)

**Comment by JoseTejera** [comment]
Its just a transition. Why It can't be disabled?

**Comment by folletto** [comment]
Maybe it's that I just don't understand what you want to do. Could you explain yourself a little better?

Is it any of these?
1. Remove just the number and the loader indicator (A: just change the color of the label in RootViewController.m, line 38)
2. Remove the swipe transition, making pages just appear one after the other (A: needs coding)
3. Remove the fade-in transition, making the pages just appear (A: needs coding)
4. Show the next page immediately, without any delay (A: read the whole Issue #27)

**Comment by JoseTejera** [comment]
Its number 4

**Comment by folletto** [comment]
Yeah, then it's #27, that's a very hard problem. :)
