### ISSUE TITLE
Hi, what can I publish with Baker Newsstand?

### ISSUE THREAD

**Issue by axxe16** [Simbul/baker#1011]
Hello,
I'm developing a collection of fables interactive with Baker but I have a doubt. If public in newstand mode Baker, my app will be accepted? My contents are not magazines but books (I would not be required to publish with iBooks Author iBooks Store). And if I publish catalogs also in this case a risk that the application is not published?
Thanks in advance for the answer.

**Comment by folletto** [comment]
Apple acceptation policies aren't very clear, but the requirement for Newsstand is quite clear about its periodicity: it must be clear it's either monthly, bi-monthly, weekly, daily or so.

**Comment by axxe16** [comment]
Thank you. So basically I need to specify the interval at which I will publish the content, but there are no indications on the kind of publishable content.
In fact, even I have found many indications about. 

I guess it is not possible to publish the application kiosk outside newsstand. Features would be a really important because it would give a more chances for publishing different kind of content.

Anyway thank you very much again for your fast reply

**Comment by folletto** [comment]
Baker have a Standalone mode, but it requires at this time to have all the issues pre-packaged. In other terms, it can't download because it uses the download system provided by Newsstand, but in general term it could be possible. ;)

**Comment by axxe16** [comment]
Ok will be my feature request ;)

**Comment by folletto** [comment]
Yep. That feature is tracked in #644. :)
