### ISSUE TITLE
Default Magazine Cover Image?

### ISSUE THREAD

**Issue by nicholasmartin** [Simbul/baker#1014]
Hey guys,

When Baker is first installed it shows the Baker logo icon and once an issue has been downloaded it will change to that issue which is cool.

I was looking for a place to add my default magazine cover image to Baker and not entirely sure where to place it. I did find the Baker/Supporting Files/Icons folder but these should not be resized I guess as the newsstand app also requires icon sizes (tray etc).

So where would I place the default cover image that will be used when no issue has been downloaded?

**Comment by nfeiglin** [comment]
You set the default Newsstand cover image in iTunes Connect.
Nathan

**Comment by folletto** [comment]
You have basically to replace all the assets inside Baker framework. For the icon you can see the folder `Baker/icon` with the various sizes used across various devices. Replace them with yours. :)

Also check `BakerShelf/img` with other background and toolbar assets. :)

**Comment by nicholasmartin** [comment]
iTunes Connect only covers for the default image in iTunes store, not on the device itself.

Davide, thanks for your reply, was wondering about the icon sizes and didn't want to change them. So it's cool to use the magazine aspect size on these icons? I could just try instead of asking here, but maybe someone else would be wondering the same :)

**Comment by nicholasmartin** [comment]
Okay was a silly question really :) Find the sizes here:
http://developer.apple.com/library/ios/documentation/userexperience/conceptual/mobilehig/IconsImages/IconsImages.html#//apple_ref/doc/uid/TP40006556-CH14-SW12

And just change the icons in the /Icons folder to your own newsstand icons that follow the ratio guidelines given by apple.
