### ISSUE TITLE
Baker notify Backend API if Sandbox or Production Environment

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#1017]
Hey.  Is there a way to add support to a future release to notify Baker Backend API's of the state of the Baker instance running and calling the backend services?

Specifically it would be useful to know if the application is being run from a production iOS device vs a debug build / simulator.

The reason I ask is that with MagRocket I would like to enable a feature that would allow users to view "pending" publications in debug versions of their apps and not have those show up if their application is also in production.  This would be beneficial for folks that are managing a release of new issues and inapp purchase approvals for reviewers etc...

Andrew

**Comment by tekdope** [comment]
:+1:

**Comment by Simbul** [comment]
This has been now implemented. I've updated the wiki to reflect the new parameter: https://github.com/Simbul/baker/wiki/Baker-Server-API

**Comment by nin9creative** [comment]
Looked at the wiki, can this variable also be added to the GET requests like the app_id and user_id?  The wiki is not clear on that bit.

**Comment by Simbul** [comment]
It works exactly like the other two. You'll get it in all requests.

**Comment by nin9creative** [comment]
I figured as much - thanks!

Andrew
