### ISSUE TITLE
How do I troubleshoot 'Could not open open issue' error

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1018]
I'm getting an error once I've downloaded my magazine.

When I tap the Read button I get the error: -

![img_0042](https://f.cloud.github.com/assets/4885291/798905/638070a6-ed6a-11e2-9278-0ecc0114e0e2.jpg)

On the console, the output I'm getting is: -

2013-07-15 17:14:07.671 Baker[17139:707] [ERROR] Book Slapshot-Mag-August could not be initialized

I've read through the message board on here and notice I've noticed that people have their book.json outside of the hpub, on the webserver.  Do I need to do this?

Also, just took a look at the book.json file and noticed this: -

"url": "book://tomcallaghan-slapshotmagazineissue1",

Thats not where the hpub is, its a bit of a random url, so does the url not being correct also cause errors?

If none of the above, are there any suggestions on how best to go about troubleshooting this error?

**Comment by folletto** [comment]
On the server you just need:
- `shelf.json`
- the hpub (zip) files of your publications, issue by issue

Did you check the URL specificed by `shelf.json` opens correctly?

**Comment by fturner19** [comment]
WOW... I've just encountered this same error message! I haven't done anything different with this magazine files and  I check the shelf.json file and everything checks out, but I still get this same error. hhmmmm!
![ios simulator screen shot jul 15 2013 2 13 01 pm](https://f.cloud.github.com/assets/280993/799692/11e45112-ed7a-11e2-97c2-ebda15fe3d8f.png)
![ios simulator screen shot jul 15 2013 2 13 26 pm](https://f.cloud.github.com/assets/280993/799693/1c589356-ed7a-11e2-840e-8a3059c0e449.png)

**Comment by folletto** [comment]
Guys, start with [Problems & Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back. ;)

**Comment by fturner19** [comment]
Ok kool

On Mon, Jul 15, 2013 at 2:30 PM, Davide Casali notifications@github.comwrote:

> Guys, start with Problems & Debugginghttps://github.com/Simbul/baker/wiki/Problems-and-Debuggingand report back. ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/1018#issuecomment-20992567
> .

## 

All good things are difficult to achieve; and bad things are very easy to
get.

**Comment by fturner19** [comment]
I fixed it....I had an extra ( " ) attached "creator"..

```
{
    "hpub": 1,
    "title": "ISIS Magazine",
    "author": [
        "ISIS Magazine"
    ],
    " "creator": [
        "2013"
    ],
```

All I had to do was remove the extra quotation mark and it resolved the issue.
@callaght - Make sure to recheck your shelf.json file for errors.
![ios simulator screen shot jul 15 2013 4 56 23 pm](https://f.cloud.github.com/assets/280993/800747/a33a2dba-ed90-11e2-82d8-0cf382f987bf.png)

**Comment by folletto** [comment]
Excellent! :D
