### ISSUE TITLE
shelf.json question

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1027]
I am using in5 to generate my InDesign CC hpub magazine for Baker in Newsstand mode.

Its generated a book.json file for me.

Do I rename this file to shelf.json and does it sit in the *.hpub compressed file or as a file in its own right on a webserver somewhere?

Also, I've noticed this: -

"url": "book://tomcallaghan-slapshotmagazineissue1",

But, this isn't any url I have, do I need to change this to the location of my *.hpub?

**Comment by folletto** [comment]
Hello @callaght :)

To answer your questions:
1. `book.json` and `shelf.json` are two different files. One defines the book (inside the HPub file), the other the shelf (on the server). Please read the Baker wiki here and specifically the Newsstand tutorial to understand how it works. :)
2. The `book://` URL should point to your HPub file. It's a proper, fully formed URL. Read [The book:// protocol](http://intenseminimalism.com/2013/a-tale-of-the-digital-ebook-in-the-tablet-era/) paragraph for some background. :)

**Comment by callaght** [comment]
Thanks folletto, I'm going to start reading the wiki and and newsstand tutorial thoroughly this time! :-)

One question on point 2.  My hpub is located on an Amazon S3 web server so the url is: -

https://s3-us-east-2.amazonaws.com/and/so/on

how do I change the above to have the book:// protocol prefix?

**Comment by folletto** [comment]
Don't worry, it's all on the wiki. That part is described in the [Book protocol page](https://github.com/Simbul/baker/wiki/Book-protocol):

> We are able to download a book: the protocol used is the standard HTTP, so you can easily replace book:// with http:// and download the book from that specific location.

So, take your "http://" URL and change it to "book://". Or, point the URL to a server of yours (so YOUR name and not Amazon's is referenced and then put a redirect from your server to Amazon's. :)
However, we don't actively use that URL in Baker, but it might be used and it's _your_ unique identifier for the book, like an ISBN, so it could point anywhere as long as it's yours and unique. Up to you. :)

**Comment by callaght** [comment]
Thanks for clarifying folletto

**Comment by folletto** [comment]
You're welcome. :)
