### ISSUE TITLE
Background image instead of Background color

### ISSUE THREAD

**Issue by creatov** [Simbul/baker#103]
Is it possible to use an image(.png) or a texture in the loader in stead of the SCROLLVIEW_BGCOLOR? I understand where the black and white (or whatever color) is defined (RootViewController.m)

Hope someone can help me out!

**Comment by Simbul** [comment]
We'll implement this as soon as we implement the Manifest as well.
It will of course be possible to specify the image to use as background in the manifest.

**Comment by yumyo** [comment]
Great one!
