### ISSUE TITLE
Has anyone embedded video with baker?

### ISSUE THREAD

**Issue by Appmantx** [Simbul/baker#1033]
Has anyone embedded video with baker? I tried with In5 and does not work. Has anyone been able to get video to work?

**Comment by folletto** [comment]
Hi @Appmantx. I'm sorry to interrupt given that you're trying to solve an issue, however there's already your thread here #1024 from you on the same topic, so I'm closing this one. :)

**Comment by justinputney** [comment]
If you're exporting from in5, it may be worth updating to version 1.5.4 or higher.

It looks like mediaelementjs and the Baker container do not play well together. As of 1.5.4, the in5 code detects the Baker container by checking the userAgent for "BakerFramework". If detected, in5 bypasses the mediaelementjs initialization and uses the native audio/video elements.
