### ISSUE TITLE
Baker HTML browser

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#1035]
I have a few links in my baker magazine but when I tap on them they overlay the current page and because I have no navigation controls I can't go back... how do I solve this? I wish to keep the user in the app [ i.e. not just boot safari]. 

I'm assuming i'm not the only person to every ask for this so any links / advice would be super appreciated.

Cheers

**Comment by freney** [comment]
You need to add `?referrer=Baker` to your links. [See the wiki for more info.](https://github.com/Simbul/baker/wiki/Managing-links-and-urls)

**Comment by ghost** [comment]
Awesome. Worked a treat :-)
