### ISSUE TITLE
ePub 3.0

### ISSUE THREAD

**Issue by freney** [Simbul/baker#1036]
Hi Baker Devs,

I'm playing around with allowing Baker to read ePub 3.0 files passed to the shelf, in addition to hpubs, as apart from indexing files they're now pretty similar (HTML5/CSS in a zip file).

My guess to the history of this is that hpub was defined before the ePub 3.0 standard came about (what we laughingly refer to as the "standard", that is!). ePub 2 was a pain in the neck; ePub 3 is too, but it's a bit more flexible. My question is whether it's a policy decision on the part of Baker to not support ePub, or if it just grew about over time.

If it's just "it happened that way, but we're not opposed to allowing ePub" then I'll try and tidy my code up and share it via a pull request; if not I'll go and post it somewhere else as an option for others should they want to.

(For reference, if the zip file doesn't have a book.json file I'm looking for ePub structure, parsing the OPF document, and creating a book.json file and a basic index.html, then passing back to the standard Baker parsing.)

**Comment by nin9creative** [comment]
Can't speak for the Baker guys but it's something that I'm interested in!

Andrew

**Comment by freney** [comment]
Thought so!

ePub 3 is actually quite a lot more restrictive than a 'HTML5 microsite' hpub, but that means that pretty much anything you can do in, say, iBooks, should work packaged ever so slightly differently for Baker. (Getting an ePub doc to conform to the specs is _such_ a pain in the neck!)

I'm doing this anyway to package our magazine for both Baker and iBooks/Kindle, so when I get it in a bit better shape I'll share it somehow.

**Comment by folletto** [comment]
Here you'll find the reason why we didn't use ePub 3.0. Check the paragraph **"ePub’s failure"**:
https://medium.com/on-publishing/a9a0865e1611

This is why we won't actively support ePub, in any version. That said however Baker is a reader, by itself, so if someone has a well done solution to support other formats that we could plug-in to Baker, we'll consider that as long as the code is good. ;)

**Comment by freney** [comment]
OK, I see why you went the way you did as a matter of policy.

Although can I play devil's advocate and push back just a bit on "This is why we won't actively support ePub, in any version"? I feel like that's the wrong way around. The ePub spec is more restrictive than Hpub, but is almost a subset of what is supported by an Hpub reader. So there's no way you could do _everything_ in a Baker magazine across all ePub readers, but the reverse is actually true: anything that displays properly in an ereader should look just as good or better in Baker (provided the indexing is done properly, etc.).

Anyway, I've got my answer for now, so I'll close out this issue. I'll work on my code and come back with it, and you can see what you think.

Cheers,

Sam.

**Comment by folletto** [comment]
Ah but I agree. :) 
That sentence was a bit ambiguous: with that "we" I meant the core team, since we don't believe in the standard, we won't support the library necessary to support ePub. But if someone else wants to try, it's fine. :)

**Comment by freney** [comment]
Gotcha. Cool.
