### ISSUE TITLE
It is fundamentally wrong? 

### ISSUE THREAD

**Issue by xappli** [Simbul/baker#1038]
Hello,

CONFIGURE BAKER STANDALONE is also done, 
Although Problems and Debugging was also briefly done from the top, only the logo of Baker is displayed as usual. 

Scarlett is put into a books folder, Run is pushed and it will be OK? 

xcode 4.6.2
Baker Ebook Framework 4.1

**Comment by folletto** [comment]
Hello, could you detail a little more what you are trying to do and what's the problem?

**Comment by xappli** [comment]
Thank you. 
It solved. 
Change the Bundle ID was wrong.

**Comment by folletto** [comment]
Good. :)
