### ISSUE TITLE
Latest Master - Subscription button missing 

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1039]
I've just noticed - There is no subscription button when executing the latest Master Baker.  Is there a new configuration option I need to set?

![screen shot 2013-07-22 at 17 52 46](https://f.cloud.github.com/assets/4885291/836373/cec13196-f2ee-11e2-9fd8-c5731c38c5eb.png)

**Comment by folletto** [comment]
Nop, nothing changed on that side.

**Comment by callaght** [comment]
My constants.h has this: -

```
#define AUTO_RENEWABLE_SUBSCRIPTION_PRODUCT_IDS [NSArray arrayWithObjects: \
@"com.suncatsoftware.slapshotmag.6months", \
@"com.suncatsoftware.slapshotmag.autorenew3months", \
nil]
```

and my Localizable.strings has this: -

```
"com.suncatsoftware.slapshotmag.6months" = "6 Month Subscription";
"com.suncatsoftware.slapshotmag.autorenew3months" = "3 Month Subscription (1st Month FREE)";
```

Does that look correct?

**Comment by folletto** [comment]
As usual, go through [Problems & Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) first and report back. ;)

**Comment by callaght** [comment]
Found the reason!

If I leave the following unchanged in constants.h: -

 #define FREE_SUBSCRIPTION_PRODUCT_ID @"" 

No subscription button appears.  If I put something in it does.

I notice in the notes that you must include a free subscription - what if I want my magazine paid only, is this not possible?

I have a 3 Months with 30 days FREE trial, but this is an Auto-Renewable Subscription.

**Comment by folletto** [comment]
I'm closing this issue since you opened the #1041 on the same subject. :)
