### ISSUE TITLE
Free subscription question

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1041]
Does an auto-renewable subscription with a 30 days free trial count as a free subscription for FREE_SUBSCRIPTION_PRODUCT_ID in constants.h?

**Comment by nfeiglin** [comment]
No, the free trial is set in iTunes Connect when you create your paid auto
renewable subscription and is part of that paid subscription.

Nathan

**Comment by callaght** [comment]
If I create a new subscription which is free then from my understanding: - 

A user would simply take the free subscription and get all of the issues for free, effectively by-passing the the need to pay for an issue or paying for a 3 month paid subscription.

Is that right?

**Comment by nfeiglin** [comment]
@callaght I believe so though I do think this could have something to do with how your server is configured.

**Comment by callaght** [comment]
Baker Master will not show the subscriptions button unless FREE_SUBSCRIPTION_PRODUCT_ID has a value.  So this means I must offer a free subscription.

I think the gap in my understanding is: why have options to purchase subscriptions and purchase issues when a user can subscribe for free - no need to ever pay, just always subscribe for free?

**Comment by folletto** [comment]
This means more likely it's a bug. Thanks for the report, we'll check. :)

**Comment by Simbul** [comment]
That was indeed a bug, but it has been fixed in the latest `master`. Have another go at it ;)
