### ISSUE TITLE
Flicker when page reloads

### ISSUE THREAD

**Issue by albertora** [Simbul/baker#1042]
Hi, 
I'm using the three-cards rendering mode, for an ebook with some hml5 interactions. I need reload the page when it get the focus, and I use location.reload(), but this sometimes makes a flicker when the page receive the event. 
Is there any way to solve this?

**Comment by folletto** [comment]
If you reload the page... that's your flicker. Try re-initializing manually what needs to be initialized instead of doing a full page refresh. :)

**Comment by albertora** [comment]
You're right :) Thank you so much!
