### ISSUE TITLE
How do you change the baker shelf title?

### ISSUE THREAD

**Issue by Appmantx** [Simbul/baker#1043]
How do you change the baker shelf title?
![rename baker self](https://f.cloud.github.com/assets/2564468/841598/9cde762e-f399-11e2-8186-6ab85ac83c54.jpg)

**Comment by folletto** [comment]
Everything is inside [Localizable.strings](https://github.com/Simbul/baker/blob/master/Baker/en.lproj/Localizable.strings) :)

**Comment by Appmantx** [comment]
Thanks
