### ISSUE TITLE
Cannot connect to iTunes Store error

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1045]
Just using the lastest Master and if I follow the purchasing sequence I get the 'Cannot connect to iTunes Store' error dialog error appear.

If I tap Buy: -
![screen shot 2013-07-24 at 07 46 58](https://f.cloud.github.com/assets/4885291/846974/252096e6-f42d-11e2-9b31-bd06aefcaa85.png)

Then tap Buy at the Confirm Your In-App Purchase dialog: -
![screen shot 2013-07-24 at 07 34 54](https://f.cloud.github.com/assets/4885291/846975/2cd442ca-f42d-11e2-8255-f3060643d2fd.png)

Then put my password in and tap OK: -
![screen shot 2013-07-24 at 07 47 25](https://f.cloud.github.com/assets/4885291/846976/39b1bfe0-f42d-11e2-833b-1fc4a1758f7d.png)

The Cannot connect to iTunes Store error dialog appears: -
![screen shot 2013-07-24 at 07 47 39](https://f.cloud.github.com/assets/4885291/846978/4c36a1a8-f42d-11e2-98d4-e33dc82cdb72.png)

Then I tap Cancel.  Next, the You've already purchased... dialog appears: -
![screen shot 2013-07-24 at 07 47 52](https://f.cloud.github.com/assets/4885291/846980/63aafcb2-f42d-11e2-8c74-0166fdcecd31.png)

I then tap OK and purchase is successful.

If at the 'Cannot connect to iTunes Store' error dialog I tap Retry then I go round in circles entering my password and then getting the 'Cannot connect to iTunes Store' error dialog.

**Comment by folletto** [comment]
As usual, the first I have to ask you to go through [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back :)

**Comment by Simbul** [comment]
I'm seeing that a lot when testing on the simulator, but then on devices it's fine. Have you tried it on a real device as well?

**Comment by callaght** [comment]
Yep, I've been testing it on my Simulator since discovering iPad 1 is no longer supported.

I've got an iPad Mini now but due to the Developer Portal being down I can't provision it as a development device :-(

I've no idea how long the Apple Dev Portal is going to be down (1 week so far) - So, I've just bitten the bullet and submitted it for review with Apple and go with Simbul's suggestion that it'll be ok in real life, on real devices.

Thanks for your help!
