### ISSUE TITLE
the application does not launch my book in the "book" folder

### ISSUE THREAD

**Issue by nicolastilly** [Simbul/baker#1047]
Hello everyone, I followed the tutorial for standalone app and it works correctly. But my application does not launch my files in the "book" folder. I joined my html files and book.json in the folder but it does not work. The application does not run my files in the "book" folder.
There instead this screen:

![capture decran du simulateur ios 25 juil 2013 13 12 30](https://f.cloud.github.com/assets/1997136/855206/6ecd5e20-f51b-11e2-8363-d0a52ba0be3c.png)

Thank you for your help

**Comment by folletto** [comment]
As usual: please read [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back. :)

That said, from what you say it seems you put the files themselves in the "book" folder, where instead you should put your book _folder_ inside the "books" folder. Is it right?

**Comment by nicolastilly** [comment]
I'm really confused ... I did not understand the difference. In fact I placed my "book" folder in the "books" folder and then everything works!

I'm sorry for this post and thank you for your answer.

**Comment by folletto** [comment]
That's good to hear! :)
You're welcome. :)
