### ISSUE TITLE
Free subs, Subscription pingback, and the in-app purchase shared secret

### ISSUE THREAD

**Issue by blowback** [Simbul/baker#1048]
HI all,

I'm offering a free sub, and I want to use the subscription pingback. I've pointed the relevant #define in Baker to the purchase_confirmation.php POST handler that's in the Baker API example code.

My post handler is getting called with app_id, user_id, type, and a big ol' receipt_data - but it's failing to decode the latter because it can't open my shared_secret.txt. It can't open it, because I never created it, because my free-sub InAppPurchase doesn't give me the option of downloading a shared secret.

In which case, what am I meant to send in the password field to the itunes server?

I realise this isn't strictly necessary for a free publication, but I'd quite the APNS info.

**Comment by blowback** [comment]
To answer my own question, it seems the empty string "" is acceptable in this case; my app's failure to proceed was due to curl not being installed on the server.

**Comment by folletto** [comment]
Thanks for coming back with the solution, it might be helpful to others. :)
