### ISSUE TITLE
Memory issue with ipad 1 and image gallery

### ISSUE THREAD

**Issue by nickiscoding** [Simbul/baker#1049]
Hi, 
I'm trying to solve a memory issue (that makes the app crash) on iPad 1. 

I'm using the last baker framework, and the Laker compendium to make a gallery on a page. 

I'm using 10 images ( jpeg 1024 x 768 pixel) total about 5 MB. 

When you're on the page that contains the gallery changing the orientation of the devices makes the app crash. ( not enough memory crash)

I tryed anso to build a simple page gallery using Jquery Touchswipe  without Laker, 
but the problem still remain. 

Any suggestion to solve this issue ? 

On ipad 2 and more recent there are no issues...

thanks

**Comment by jukialla** [comment]
It's an iPad 1 problem. On my ipad1 I can usually only run one app at a time. Load a baker app with another app running will cause the baker app to crash, even if the bakercapp is just a basic baker shell app. Baker apps work fine on iPad 1 if it is the only app running. I guess that is why ipad1 stopped at IOS 5.1.

**Comment by nickiscoding** [comment]
Thanks, 
I'll go for an artenative way to show the images. I'd like to keep the magazine also for iPad 1 at the moment. 

best regards
