### ISSUE TITLE
Shouldn't a newsstand app appear in the newsstand folder?

### ISSUE THREAD

**Issue by blowback** [Simbul/baker#1051]
Probably a really stoopid question, but whilst testing on an iPad with Baker in newsstand mode, I noticed that it appears in the home screen like a regular app, and not in the nasty wooden bookshelf folder thingy for the chosen few Newsstanderati.

Is that right? Or do you only go in that folder once you've been approved?

**Comment by Simbul** [comment]
It should always go in the Newsstand folder. Make sure it's not a Standalone version that you compiled in the past: apps in the simulator tend to hang around ;)

**Comment by blowback** [comment]
Ok thanks, I've ballsed something up then. This is on a device not the simulator, but it has had an earlier standalone variant on there.

**Comment by blowback** [comment]
So what I did here was fail to heed the advice:

"Download and unzip the latest version from the website.".

Having first developed my app as standalone, I then tried to convert it back to Newsstand mode, and missed a bunch of settings in the plist file. Happily it is working nicely now, but I'd advise anyone else doing this to start from the vanilla Baker zip file and reapply your customisations ;)
