### ISSUE TITLE
Index bar issues

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#1052]
Hi I am having issues with my index bar. 

I am using in5 to export the magazine from indesign but when I test in baker, the navigation / index bar is way to high and takes up about 80% of the screen vertically. 

As of the latest in5 update, the values for width and height have been removed from the Json file so I added the height one back in and this seemed to work however now if I swipe vertically the index bar literally vanishes of the screen. This is driving me nuts!!

Finally the mag is for iPad and iPhone and ideally I would like to scale the navigation down a bit for the iPhone. Is this possible? If so how

Thanks in advance

**Comment by folletto** [comment]
Most of the issues you're raising are about In5, you should ping them. It's mostly a consequence of the `index.html` they are auto-generating and as such... you have to edit it, or create a new index from scratch.

We can't do much about it.

**Comment by ghost** [comment]
Ok fair enough. I don't mind creating one from scratch using the thumbnails in5 outputs.

Can you please direst me to a super simple index file that just swipes left and right and is the correct size  and doesn't vanish when swiped vertically?

**Comment by folletto** [comment]
For the swiping you don't need anything: just make the page wider. :)

However I can't point you to a specific source other than the demo book, sorry.

**Comment by fturner19** [comment]
@lukeallen1986 - I had this same issue with my index file as well using In5. What you need to do is edit your book.json file and edit the width and height. A good height would be 200px and lower, I use 200 myself.
So it would work like this...If your magazine have 10 pages you would multiply 10x200=2000. So your width would be 2000.

"-baker-index-width": 2000,
"-baker-index-height": 200,

Hope that helps you out.

**Comment by justinputney** [comment]
This should be fixed with an update to in5. Please contact Ajar Productions at our support email if it's still not working for you.

**Comment by ghost** [comment]
@justinputney yeah I have solved the thumbnail issues but given up on the scaling iPhone problem as I simply can't work it out. 

I saw your post - https://github.com/Simbul/baker/issues/1025#issuecomment-23752339 that tried to address it. 

My design does seem to scale everything down nicely and nearly fits but just misses by what looks like 30-50px as it appears to fill both height and width. I would love it to just fill device width and have spaces top and bottom, but unfortunately no can do.

**Comment by justinputney** [comment]
@lukeallen1986 what about creating margins around the edges of your InDesign pages before exporting?

**Comment by ghost** [comment]
Unfortunately that will greatly effect the look of the iPad design and each page on the iPhone version will still have  30-50px horizontal scroll which is almost the most annoying bit, so although its a good idea it won't work for me

**Comment by justinputney** [comment]
It's possible that a CSS media query or an adjustment to the viewport metatag could do the trick...

Do you have this posted on the web somewhere where I can take a look?

**Comment by ghost** [comment]
Yes. Here is the link to the hpub - http://bit.ly/19qQoSq

Oh btw I also had a related question on your in5 answer exchange - http://ajarproductions.com/pages/products/in5/answers/777/ipad-and-iphone-scaling-issues

**Comment by justinputney** [comment]
Thanks @lukeallen1986. The bit.ly link seems to point to a missing file, but I'm looking into the file you posted on the Answer Exchange. It's odd behavior indeed!

**Comment by justinputney** [comment]
Hi @lukeallen1986. Thanks for your patience on this issue. I've found a fix.

It appears in this particular case that given the page width and the width of an iPhone in portrait mode, the scale needed for the width of the page is smaller than the default setting allowed for the device. This can be fixed by adding a _minimum-scale_ value to the viewport tag:

`<meta name="viewport" content="width=1536.00,minimum-scale=.2">`

This extra code will automatically be added in a future version of in5 (1.6.2 or higher) when _Scale to Device Width_ or _Scale to Page Width_ are selected as the _Viewport Zoom_ option.

**Comment by ghost** [comment]
Hey @justinputney that worked perfectly! thanks so much for following that up...
