### ISSUE TITLE
Magazine cover shows on the IOS but not on Ipad

### ISSUE THREAD

**Issue by Appmantx** [Simbul/baker#1056]
Magazine cover shows on the IOS simulator  but not on Ipad
![nopic](https://f.cloud.github.com/assets/2564468/868326/9e63634e-f793-11e2-8b41-e9ebe54f4dcc.PNG)

**Comment by folletto** [comment]
As usual, follow [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back, so we have more data to work on to help you. :)

That said, it might be a formatting problem of the image. Did you try with other images? Or the demo `shelf.json` we provide?

**Comment by Appmantx** [comment]
Thanks for the quick response,It's the last thing before submitting ( driving me nuts!) LOL   I copied the pic and Icon files and just layed my Images over them. I am not sure where to find the (demo Shelf.json)  file. I tested it on that jsonlint site and the app works perfect on the IOS simulator.

**Comment by Appmantx** [comment]
The background Image is fine, once you download the app and go back It's on the shelf. It you don't see it when you first load it on the Ipad... I hope that helps..Thank You

**Comment by folletto** [comment]
The demo one I'm referring is the one in Baker initially, `http://bakerframework.com/demo/shelf.json`, however just try with a random image (even taken from the shelf above. :)

It might be just an export issue with the images (the simulator supports some more variations).

**Comment by Appmantx** [comment]
Something is messed up, I put the demo/shelf.json in my app and it's still pulling old ( images) I do a clean build everytime.. in Xcode...What do you sugguest?

**Comment by Appmantx** [comment]
DuHHHHH....I been working on the so Long. I missed it.. I had another json file up one level that it was pulling from. Of course it had an old URl for the cover. That's why it was not showing on the Ipad!  Thanks for your help!

**Comment by folletto** [comment]
I'm glad to hear it's solved. :D
