### ISSUE TITLE
Important Metrics to Track for Baker Applications?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#1058]
I was just curious what types of Analytics and event tracking would be useful for those publishing apps.

I know the basics would be nice, events such as...  Some of these would probably be more accurate by using the iTunes Connect reports (for In App Purchases) however it may be useful to aggregate in a single view for reporting purposes.

*Opening an Issue
*Downloading an Issue
*Archiving an Issue
*Refreshing the Shelf
*Making a Single Issue In App Purchase
*Making a Subscription Purchase (Paid or Free)
*etc...

Just curious what people think.

**Comment by fturner19** [comment]
@nin9creative - This is exactly what i've been thinking and trying to implement with countly. With this type of information from your apps and games you can make really big decisions by having all the right information at your finger tips in a flash, because Countly presents this information instantly. I'm playing around with the code now...And thanks for pointing me in the right direction. :+1:

**Comment by nin9creative** [comment]
Not sure if you saw I posted a bit in the other thread.

https://github.com/Simbul/baker/issues/1037

**Comment by folletto** [comment]
This is an excellent thread @nin9creative! :)

I'll just cross reference the issue where we track the feature. #332 ;)

**Comment by nin9creative** [comment]
@fturner19 What's great about using a self hosted solution such as Count.ly is that if you are a developer working on different magazines for different clients - you can sell the analytics as part as a value added option to your service.

Countly has the ability to create users that have read only and or admin access to specific applications that Countly is tracking.  You could provide the login information to your client contact, and they could see in real time the use of their magazine and gather metrics around it.  Pretty powerful.

**Comment by benoitchantre** [comment]
Some events related to pages would be useful to know where the reading time is spend in an issue. For example: time spend on the page, how often the page was displayed, ...

For a website, we can track also some interaction inside a page with appropriate trackers. Can it work inside an app?

**Comment by fturner19** [comment]
@nin9creative - True indeed! I've already set up a couple logins for clients that i'm currently working with. What I like about Countly is it's seamless integration with Baker. Just add a few lines of code and you're off to the races. Being able to add custom Events and get instant results is what gets me excited. The Baker community should be adding countly to their builds to track their apps stats. And thanks again Andrew for pointing me in the right direction.

**Comment by fturner19** [comment]
@nin9creative - Looks like The Countly Team added your installation video to their support section and pushed it out to all self-hosted versions. Take a look at it:
![screen-shot-2013-08-04-at-9 01 40-pm](https://f.cloud.github.com/assets/280993/907868/ecf98802-fd6b-11e2-9ede-2980f0c60e03.png)

**Comment by nin9creative** [comment]
Ha :)  Cool.

**Comment by folletto** [comment]
Ok, a first implementation is now on master, let's keep the discussion consolidated on the feature tracking issue, here: #332.

**Comment by nin9creative** [comment]
Awesome!

Andrew
