### ISSUE TITLE
zoom current webview

### ISSUE THREAD

**Issue by MartinPrz** [Simbul/baker#1059]
Hello,

How can i zoom and pinch current webview ?

**Comment by folletto** [comment]
We strongly advise against it, because your publication should just work at the right size. :)

However, if you really need it, please read the wiki here on GitHub.
In the HPub page you see the "zoomable" property:
https://github.com/Simbul/baker/wiki/hpub-specification

**Comment by MartinPrz** [comment]
I am very grateful, cheers.
