### ISSUE TITLE
Index bar size and position from HTML

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#106]
The index bar should be sized and positioned according to the size of the index.html 

The following rules apply:
- The UIWebView for the index bar will never be bigger than the current viewport.
- The bottom left corner acts as a fixed snapping point.

Supposing index.html has a size of 2000x150px, the bar will snap to bottom, be 150px tall and be 768px (portrait) or 1024px (landscape) wide.
Supposing index.html has a size of 150x2000px, the bar will snap to the left side, be 150px wide and be 768px (landscape) or 1024px (portrait) tall.
Supposing index.html has a size of 150x150px, the bar will appear as a 150x150px square, snapped to the bottom left corner.

**Comment by Simbul** [comment]
This will be implemented incrementally:
1. Get index bar height from index.html
2. Get height and width from index.html

**Comment by k8fisher** [comment]
REF: The UIWebView for the index bar will never be bigger than the current viewport.Can I ask about this comment. Is it a problem having an index bar wider than the viewport. E.g. Is scrolling through an index object larger than the viewport not possible?

**Comment by k8fisher** [comment]
Im attempting to call the table of contents from an object which sits on the page at the moment as a double tap gesture isnt obvious enough for readers "apparantly" :/  only problem when I show the hidden toc and attempt to scroll through it (its longer than the viewport) the ipad gets confused between my trying to scroll from the tables of contents and scrolling to a new page. Any thoughts v welcome.

**Comment by Simbul** [comment]
The idea behind the index bar is that we'll usually show a UIWebView as large as the viewport. The UIWebView can contain an HTML page larger than the viewport (in fact, this is what happens in the [example book](https://github.com/Simbul/baker/tree/master/book)). When the HTML page is larger than the UIWebView, the view will take care of the scrolling.
This is the same concept of a browser window: the window itself is never taller than the screen, but it can display taller pages by allowing you to scroll them.

As for the other issue, I'm not sure I understand it completely. The implementation we have on the master branch at the moment is working fine, so what difference is there in your application that could make it behave differently?
