### ISSUE TITLE
how -baker-vertical-pagination  calculate the page step? 

### ISSUE THREAD

**Issue by nickiscoding** [Simbul/baker#1060]
Hi, 
i'm wondering how the option -baker-vertical-pagination  calculate the page step, 
it just move from the pixel amount of the vertical device resolution? 

thanks

**Comment by folletto** [comment]
Wonder no more! :D 
You can directly see it on the source code, line _921_ of `BakerViewController.m`, [here](https://github.com/Simbul/baker/blob/master/BakerView/BakerViewController.m#L921).

```
((UIScrollView *)[[webView subviews] objectAtIndex:0]).pagingEnabled = [book.bakerVerticalPagination boolValue];
```

In other terms: we don't do anything. It's all managed by Apple's libraries, specifically, the `UIScrollView` inside `UIWebView`. :)

**Comment by nickiscoding** [comment]
Thanks! I solved that.
