### ISSUE TITLE
linking directly to app review

### ISSUE THREAD

**Issue by Appmantx** [Simbul/baker#1065]
I realize this is no a baker question but Does any one know how to directly link to app review page? I have tried some old code but it does not work. Can someone point me in the right direction? Thank You

**Comment by folletto** [comment]
What do you mean by app review page? :)

**Comment by Appmantx** [comment]
I took a snap shot, I know it can be done because the are doing on another platform 
![app review page](https://f.cloud.github.com/assets/2564468/906374/b40384aa-fc97-11e2-88f9-2bd9f0ba797e.jpg)

**Comment by folletto** [comment]
Ahh the iTunes App Page. :)
("app review" is a **very** different thing! :D)

Just open the page from iTunes (the one you screenshotted above) and right click on the title, you will get a "Copy Link" option. :)

**Comment by Appmantx** [comment]
Thanks, but that just takes me the the app, not directly to the review 
page.

Davide Casali wrote:

**Comment by folletto** [comment]
Sorry then, I didn't even know it was possible to link directly to that _tab_ in the _app page_.

**Comment by folletto** [comment]
That said I found quite a few topics on google and stackoverflow, I'd advise to ask there since it's more an Apple question than a Baker question

**Comment by Appmantx** [comment]
Yea been there, old code doesn't work thanks
