### ISSUE TITLE
Subscription unlock all the issues

### ISSUE THREAD

**Issue by Regolo-Design** [Simbul/baker#1066]
Hi, 
i'm testing my app in development mode. When i make a subscription all the issues become available for download, but i prefer that only the last issue and the next one will be downlodable when the subscribing period start.

any help?

**Comment by nin9creative** [comment]
What server backend are you using?

If you are using MagRocket 1.0 in development mode it unlocks all the issues.  You can take a look at the logic in the API
and change if you want a different behavior.

When it's in Production (not development/sandbox) it will only unlock the current issue within the month that it's released
going forward for however long the subscription term is valid.  So it'd unlock the current plus future until the subscription
expires or is not renewed.
