### ISSUE TITLE
Info button crash the app in standalone mode

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1069]
It seems there's a bug with the info button and the standalone mode.

Here's what I did
- download the latest code from the master
- configure standalone mode
- add the book _Baker Framework Tutorial_ (to be able to display the shelf)
- proper cleanup
- click on the info button

The result is a crash of the app.

No issue with the newsstand mode.

Here's the log.

> 2013-08-06 11:28:47.455 Baker[14648:c07] ====== Baker Standalone Mode enabled 2013-08-06 11:49:08.035 Baker[17617:c07] ====== Baker Standalone Mode enabled ======
> 2013-08-06 11:49:08.042 Baker[17617:c07] [BakerBook] 'book.json' parsed successfully. Book 'A Study in Scarlet' created with id 'a-study-in-scarlet-1cbeef1e2f24e3'.
> 2013-08-06 11:49:08.043 Baker[17617:c07] [BakerBook] 'book.json' parsed successfully. Book 'Baker Framework Tutorial' created with id 'baker-framework-tutorial-afd254e18ae4f642'.
> 2013-08-06 11:49:09.937 Baker[17617:c07] -[ShelfViewController handleInfoButtonPressed:]: unrecognized selector sent to instance 0xa47f090
> 2013-08-06 11:49:09.938 Baker[17617:c07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ShelfViewController handleInfoButtonPressed:]: unrecognized selector sent to instance 0xa47f090'
> **\* First throw call stack:
> (0x189b012 0x16c0e7e 0x19264bd 0x188abbc 0x188a94e 0x16d4705 0x3092c0 0x545a64 0x16d4705 0x3092c0 0x309258 0x3ca021 0x3ca57f 0x3c96e8 0x338cef 0x338f02 0x13f3e 0x316d4a 0x308698 0x2f1cdf9 0x2f1cad0 0x1810bf5 0x1810962 0x1841bb6 0x1840f44 0x1840e1b 0x2f1b7e3 0x2f1b668 0x305ffc 0x2e72 0x2da5)
> libc++abi.dylib: terminate called throwing an exception
> (lldb)

**Comment by folletto** [comment]
Thanks for the report, we'll check. :)

**Comment by folletto** [comment]
Thanks for the bug report, it was a simple fix: the code was placed under the part of code that gets automatically disabled when you turn off Newsstand. Now should work. :)

**Comment by benoitchantre** [comment]
I cannot reproduce it :)
Good work, thank you!
