### ISSUE TITLE
Best way to rename the app and to keep it in sync with git?

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1070]
The easiest way to rename the app is to change the project name in Xcode.

The inconvenient is that it becomes more complicated to update the app if you use git, because Xcode renames a lot of files.

To rename the app and keep it in sync with the repo, you can either
- rename the target
- change the value of `Bundle name` and `Bundle display name` from the Info panel

What is the best option?

**Comment by benoitchantre** [comment]
Any advice is welcome.

**Comment by Simbul** [comment]
I tend to change the value of Product Name (`productReference`). That still causes a larger diff than I'd like, but at least all the changes are confined to `project.pbxproj`.

**Comment by benoitchantre** [comment]
You mean you rename the content of this field and then you update `.gitignore` with the new name?
![capture decran 2013-09-10 a 09 22 25](https://f.cloud.github.com/assets/1521015/1112792/d3f408b0-19e9-11e3-8531-98cb4b2c046f.png)

**Comment by Simbul** [comment]
This is the field I usually change (I'm on Xcode 5 beta now):
![screen shot 2013-09-10 at 10 33 05](https://f.cloud.github.com/assets/147104/1113402/144cfff4-19fc-11e3-9671-050cc076a866.png)

I don't think you can gitignore `project.pbxproj` as it contains a lot of other stuff as well, but if you have a branch of the baker repo where you've committed your product name you should be able to pull in 99% of changes from `master` without getting into conflicts.

**Comment by benoitchantre** [comment]
Thanks @Simbul. With your method, 5 lines are changed in `project.pbxproj`. Looks good.
