### ISSUE TITLE
Anyone else experiencing Sandbox issues?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#1072]
My test setup for Baker all of a sudden went to the "Updating Price" spinning icon on all Paid In App Purchases.  Was working a few days ago - not sure if it's a problem on my end or iTunes Connect / Sandbox.

Anyone else seeing anything weird?

Andrew

**Comment by fturner19** [comment]
@nin9creative - I added a price to 5 issues that was currently FREE, but was getting the "Updating Price" spinning icon as well. I thought I did something wrong so I just commented out the code and set them all to FREE again and everything worked. So it sounds like a bug to me if you're getting the same results with paid issues.

**Comment by nicholasmartin** [comment]
Wasn't there a scheduled maintenance for iTunes Connect today? Don't remember the details of it though.

**Comment by nin9creative** [comment]
I must have missed the info or something...  Seems to be working fine now and I didn't change anything :)
