### ISSUE TITLE
Problems with hover

### ISSUE THREAD

**Issue by rokayattila** [Simbul/baker#1075]
Hi!

i am a beginer in html codeing. Did you ever had problem with hovers in Baker? I try to add the following code to my css. It works in Opera, Chrome, so on. But it does not works on iPad simulator... Do you have any idea how to solve this problem?

My code:

```
    }
    .slidebutton {
    position:absolute;
    width: 50px;
    height: 50px;
    top: 0%;
    background-color: white;
    transition: width 2s;
    left:718px;
    -webkit-transition: width 2s; /* Safari */
    float:right;
     }
    .slidebutton:hover {
     position:absolute;
    width: 150px;
    height: 50px;
    top: 0%;
    background-color: white;
   left:618px;
    clear:both;
    display: block;
    }
```

**Comment by folletto** [comment]
I'm not sure what you're trying to achieve because `:hover` does not exist on touch devices: there's nothing hovering. What kind of behaviour you are trying to achieve?

**Comment by rokayattila** [comment]
I try to add a button which become bigger after touching it. I need the same effect like the hover generate in desktop browser. Sorry for my language I am not native english speaker......

**Comment by folletto** [comment]
Well if it gets bigger if you touch it it's a touch/click action, not a hover action, and you'll have to manage it with JavaScript. :)

**Comment by rokayattila** [comment]
I tried to do it with the following code:

$(".slidebutton").hover(function(){
    $(this).addClass('active');
},function(){
    $(this).removeClass('active');
});

css:

.slidebutton:hover, .slidebutton.active {

But it did not work.

**Comment by folletto** [comment]
Because, again, there's **no** hover on touchscreens. That javascript triggers a class on hover. :)

That's not much a Baker issue. Check around the web and stackoverflow, you'll find plenty of descriptions on the topic like:
- http://www.nczonline.net/blog/2012/07/05/ios-has-a-hover-problem/
- http://stackoverflow.com/questions/7136188/adding-a-hover-effect-in-mobile-safari-when-the-user-taps

**Comment by rokayattila** [comment]
Thank you really much!
