### ISSUE TITLE
three-cards custom

### ISSUE THREAD

**Issue by bobwol** [Simbul/baker#1085]
Hi Baker team and community!

I would like to customize a version of Baker running a book using three-cards rendering mode, but loading next and prev pages like -2 | 0 | +2

Actual three-cards loads like this: -1 | 0 | +1 (if current page is 5 then load next page 6 and prev page 4)

My need would load like this: -2 | 0 | +2 (if current page is 5 then load next page 7 and prev page 3). And if I swipe to next page, it will show the page 7 and load the next page 9 retaining page 5 as prev page. and so on...

book.json will remain with all sequence of files like:

"contents": [
        "001.html",
        "002.html",
        "003.html",
        "004.html",
        "005.html",
        "006.html",
        "007.html",
        "008.html",
                ...

Could you give me some ideas / guide to change this in BakerViewController ?

Current using Baker 4.1 version.

**Comment by erhnby** [comment]
Did you solve this problem ?

**Comment by bobwol** [comment]
Not yet my friend! Working hard on it but still without a good solution.
