### ISSUE TITLE
Google Analytics Problem

### ISSUE THREAD

**Issue by aspek** [Simbul/baker#1090]
Hi Baker,
I'm try to use google analytics.I follow the installation from wiki's page. But X-code said  
![screen shot 2556-08-21 at 4 56 30 pm](https://f.cloud.github.com/assets/2587452/1000627/1a22a34e-0a51-11e3-8435-a0c84ba07cbe.png)

Have anyone can solved this?

**Comment by folletto** [comment]
Hello!

I think I need more details about what you did. That log is surely very strange to me, mostly the "i386" architecture part. What instructions were you following exactly and could you please detail step-by-step what we should do to reproduce the error from a clean setup of Baker downloaded from the website?

**Comment by aspek** [comment]
Hi @folletto ,
I use baker latest version from Github. Just downloaded on yesterday.
I follow the installation from wiki's page : https://github.com/Simbul/baker/wiki/How-to-setup-google-analytics-or-similar And download google SDK form: https://developers.google.com/analytics/devguides/collection/ios/resources 

And I put this to baker project.
- GAI.h
- GAITracker.h
- GAITrackedViewController.h
- GAITransaction.h
- GAITransactionItem.h
- libGoogleAnalytics.a

![screen shot 2556-08-21 at 6 51 05 pm](https://f.cloud.github.com/assets/2587452/1000810/0a887dd0-0a58-11e3-9f69-6489142ff7af.png)

Add Frame work 
- CoreData.framework
- SystemConfiguration.framework

initialize the library from Step 2 in wiki' page using by  Google Analytics.
Add Fire event from Step 3 in wiki' page.

I following Step 1-3. And just Build (Command +B) .And  X-Code said like that.

**Comment by folletto** [comment]
Try with the library linked from the wiki page (click on Google Analytics for iOS): 
https://developers.google.com/analytics/devguides/collection/ios/v2/

If I read the page you linked correctly, that's Google Analytics v3, beta, for XCode 5. So I guess you would need XCode 5 to run it, currently in beta for iOS7.

**Comment by aspek** [comment]
Look like google analytics SDK can download only in last version. In Header "Before you Begin" if click link Google Analytics for Mobile Apps iOS SDK v2 . It's same link https://developers.google.com/analytics/devguides/collection/ios/resources
So I search v2 on google.com but can not find it.

**Comment by folletto** [comment]
Ahhh! Bad Google!

Check if this solution solves it:
http://stackoverflow.com/questions/9835348/problems-adding-google-analytics-to-ios-app

**Comment by aspek** [comment]
Thanks!! great working. But I think this link to be better https://developers.google.com/analytics/devguides/collection/ios/v3/  
Be careful 
When download google analytics SDK the path file will show like this
![screen shot 2556-08-22 at 10 44 42 am](https://f.cloud.github.com/assets/2587452/1006332/74440354-0add-11e3-88fa-be0b9a4b5dae.png)
If not carefully like me when add SDK you will add "libGoogleAnalytics_debug.a". So remove  "libGoogleAnalytics_debug.a" from Link Binary With Libraries. And add "libGoogleAnalyticsServices.a" in there.

**Comment by folletto** [comment]
Excellent! Thanks for reporting back! :)
I also updated the wiki. :)
