### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#1091]
Hello My app was approved and you can find it on Appstore. I offer free issues in download (between 128 and 386Mo) ->
https://itunes.apple.com/us/app/factice-magazine/id634867246?l=fr&ls=1&mt=8

For a big part of my readers , they can't read the magazines. After downloading the issue, when they want to read it, the app crash and they come back on the desktop.

I don't know in which level is the problem ?
supposition 1 : Upgrade in 4.1
supposition 1 : maybe 128/386Mo are to much and I must have issues less than 100Mo

Thank you for your help

**Comment by folletto** [comment]
We should have fixed the issue in #1046, it will be in the next version of Baker.
However, yes, such huge issuer can be a problem, even more on less powerful devices such as the iPad 1.

**Comment by kodjoe** [comment]
Mister Folletto hope you're okay

ok for your answer, this bug isn't fixed on the 4.1 ?
it will be in another one ;) ?

**Comment by folletto** [comment]
The fix is on the version currently in development, will be likely in the future version 4.2. :)

You might try to use the master version of Baker you can download here from GitHub, but be careful to test it thoroughly since it's an in-development version and might have bugs.

**Comment by kodjoe** [comment]
perfect thanks Folletto, if I want to update my version from 4.0 to the 4.1 there is a tuto or something like that ?

**Comment by folletto** [comment]
No tutorial for upgrade, sorry. The process is similar to making a new app: just take the new version and follow the tutorial for a new install. :)

**Comment by kodjoe** [comment]
oki perfect man, thanks for your help ;D & have a nice day ;)
