### ISSUE TITLE
Javascript error related to pagination

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1095]
The web inspector reveals a javascript error in iOS Simulator.

```
TypeError: 'undefined' is not an object (evaluating 'document.getElementsByName('paged')[0].getAttribute')
```

You can observe it in _A Study in Scarlet_.
This error happens even there's not script in this page.

~~It is probably because the meta "paged" introduced in Baker 4.1 is not a valid attribute.~~

This error is only shown when the page is in iOS Simulator, not in a web browser.

Update: you need the new web inspector to see it. Fix in pull request #1098

**Comment by benoitchantre** [comment]
Pull request merged

**Comment by Simbul** [comment]
Thanks for the pul request!

**Comment by benoitchantre** [comment]
You're welcome. Thanks for this framework.
