### ISSUE TITLE
twitter timeline widget

### ISSUE THREAD

**Issue by rogerdcarvalho** [Simbul/baker#1099]
Has anyone tried to implement the twitter timeline widget in baker? When I use the standard html output that I get from twitter, which is:

```
a class="twitter-timeline" href="https://twitter.com/search?q=<my query>" data-widget-id="<my id>">Tweets about "<my query>"</a

script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script

```

It doesn't load within baker. If I open the HTML in safari directly, it does work. Any ideas?

**Comment by folletto** [comment]
Hi! I see nobody was able to help you here, I'm sorry. Did you manage to find a solution yourself? :)

**Comment by anjimi** [comment]
Hi, I'm having the same problem, @rogerdcarvalho did you manage to find a solution to the twitter timeline widget in baker?

**Comment by anjimi** [comment]
Solution found and posted here: https://github.com/bakerframework/baker/issues/83

**Comment by folletto** [comment]
Cool! :)
