### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by tablazines** [Simbul/baker#110]
Hey all, I've been lurking around Baker and these forums for a while now. It wasn't until I saw "Her World" magazine that I decided to really go ahead and user Baker for a publication.

My questions is will Baker be able to handle subscriptions?

**Comment by folletto** [comment]
It does, there are already a few working on that and at least a released app. However it's not yet in our codebase, we have a lower priority on that, and they coded / are coding their own solutions. :)

That said however, as a workaround you could use downloadable books. It's a bit annoying, mind you, but that wouldn't require any additional coding.

See issue #20 for this. :)
