### ISSUE TITLE
Is there a way to skip the book title/shelf flashing on first launch?

### ISSUE THREAD

**Issue by ayarmanqu** [Simbul/baker#1100]
Hi,

Excuse me if this has been explained before, but I can't find the info in the archives.

I am updating my book to the latest version of Baker (4.1) and I see that Shelf support has been added. I have followed the instructions to disable the shelf since I don't need newsstand support.

The problem I am experiencing is this:
At the beginning of my book I have an intro movie that shows right after the loading screen. It used to appear seamlessly with the older version of Baker.

But now, between the loading screen and my movie, I get a white screen with a black bar with the book title, then there is zoom effect from the upper left corner that fills the screen, and then my intro movie appears. It looks pretty bad.

Is there a way to skip that initial loading (which I assume is the shelf) completely?

Thank you,

Jorge

**Comment by folletto** [comment]
There isn't currently any way to do that, I'm sorry. You have to modify Baker yourself.

**Comment by ayarmanqu** [comment]
Thank you for letting me know, Davide.
Please consider it for a future version.

Jorge

**Comment by folletto** [comment]
We will. I marked this issue as a feature request. :)

**Comment by folletto** [comment]
Check the latest master as above, it should have fixed the issue. :)
It's a byproduct of our work on iOS7. ;)

**Comment by ayarmanqu** [comment]
Thank you, Folleto!
It's much better. I no longer see the "zoom" flash effect :)

The title menu and dock do still appear for a little bit, then they hide. I think it would be better if they don't appear and it goes straight to the first page of the book (or at least make it an option, if to show the dock at first launch).

Jorge

**Comment by folletto** [comment]
That's something we do in order to provide the user a hint that they can access that part of the page. However we'll see, if there's a chance we might make it possible to disable. :)

**Comment by ayarmanqu** [comment]
Sorry, I know I'm being picky ;) and I figured it was on purpose.
But if you could make it a book.json option, it would be great :)

**Comment by benoitchantre** [comment]
It would be great to have an option to disable this behavior. In the case you use a launch image, this makes a strange animation with 3 steps : startup image -> index view show briefly -> page

**Comment by codypallo** [comment]
Is there a way to change the animated title text to white?
