### ISSUE TITLE
iOS7: vertical position of the page after pull down

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1109]
When you pull down a page, there's a gap which is equal to the height of the status bar + title bar.
Same behavior when you change page with a diagonal movement: the new page is not positioned at the top of the view.

If you check the option to hide the status bar during application launch, the page is positioned at the top of the view as expected.

Tested with the latest code from the iOS7 branch.

![capture decran 2013-09-06 a 09 20 35](https://f.cloud.github.com/assets/1521015/1094307/c9529ac4-16c5-11e3-8d9e-d1e609612ed0.png)

**Comment by folletto** [comment]
Yeah. That's one of the most painful things we're trying to fix. :/

**Comment by benoitchantre** [comment]
Both issues are related to the status bar when it's hidden or shown.

**Comment by benoitchantre** [comment]
I cannot reproduce this issue, thanks for the fix.
I have noticed that the page cannot be moved in a diagonal movement. It moves either vertically or horizontally, but not both at the same time. That's better.
