### ISSUE TITLE
iOS7: vertical position of the title bar with status bar hidden

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1110]
When you check the option to hide the status bar during application launch, the bar containing the title of the book is positioned as if there was a status bar.

It should be positioned at the top.

Tested with the latest code from the iOS7 branch.

![capture decran 2013-09-06 a 09 45 02](https://f.cloud.github.com/assets/1521015/1094399/2025d688-16c9-11e3-8321-ed064bfbca8c.png)

**Comment by folletto** [comment]
I think it's the very same bug as #1109.
That said, I don't think we'll support the situation when the user manually disable the status bar: the status bar should be there. We'll see however if the solution for #1109 fixes automatically this as well. :)

**Comment by benoitchantre** [comment]
Thanks. I tried to disable the status bar, because it's displayed on the book.
I think it's better when the status bar is hidden when you are reading, that's more immersive.

In iOS6, the status bar is hidden when you are reading.

Is it something that you are changing or a behavior that is not yet implemented?

Update: the second screenshot reveals an issue when the status bar is displayed: there's a collision between the content of the status bar and the content of the book.
If you decide to keep the status bar, there should be a semi-transparent layer between the page and the status bar.

![capture decran 2013-09-06 a 10 09 01](https://f.cloud.github.com/assets/1521015/1094472/a214420e-16cb-11e3-9881-ddcfa1819e3c.png)

![capture decran 2013-09-06 a 10 33 30](https://f.cloud.github.com/assets/1521015/1094611/0c68b01a-16cf-11e3-9acf-4a12eb17ac02.png)

**Comment by johanneseckert** [comment]
I also believe that the status bar shouldn't be there when simply reading to continue to offer a full screen experience. and I don't think apple intended to have the status bar showing all the time.
@benoitchantre the setting »hide during application launch« only applies for the time the launch image is shown, it does not affect when or how a status bar is shown when the app is running (to your original command). so your first immage should still show the status bar and the navigation bar should be topattached (which it is when you open the navigation bar yourself)

**Comment by benoitchantre** [comment]
@frischmilch thanks for the clarification about the status bar setting.
That's interesting to see that people working at Adobe follow this project ;-)

**Comment by folletto** [comment]
@frischmilch Yes, that's the objective. Baker does that in the current stable version, but we are finding problems in animating it under iOS7. :/

Apple changed a lot on the management of the status bar, and it seems they are "trying" to keep it visible all the time (the new settings are mostly around doing that). I'm curious to see if they will update iBook for iOS7, or not.

**Comment by johanneseckert** [comment]
@folletto you can see apple hiding the status bar in certain modes in Photos.app. if you tap on an image to go to _slideshow_ mode, the status bar disappears and no UI is visible. or more interestingly the landscape view of your photo activities hides the status bar to allow a full screen grid but still has some minimial UI (label and gradient at the bottom). the latter is a great immersive experience and I would expect apple do the same in iBooks later.

![img_0209](https://f.cloud.github.com/assets/545926/1110302/a01f72ee-1990-11e3-9af3-88845e22e6f8.PNG)

**Comment by folletto** [comment]
I'd love to see the code for that, as said we're encountering quite a few problems trying to do the animation transition smooth. :/

**Comment by johanneseckert** [comment]
maybe a difference there is that they are not sliding out but simply fading out, so maybe no boundaries are effected? (don't know enough about xcode animations to judge that).
that said I see that baker is moving the scrollview up or down 20pt when the status bar opens. I believe, in iOS7 the main view basically just stays where it is and always spans the full screen and UI appears ontop of it (but I am sure you already know that). I worked on some apps for iOS7 before and the status bar thingy caused a lot of headaches …

**Comment by benoitchantre** [comment]
I have found that on the macrumors forum.

> If you are getting a persistent black status bar, its a bug related to having Guided Access enabled in Settings-> Accessibility. Turn off guided access, reboot phone, and it should be fine.

And this [snippet](https://gist.github.com/marlonSci5/6006700) on Github.
