### ISSUE TITLE
iOS7: vertical position of the menu bar of the modal view

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1111]
There's a collision between the menu bar of the modal view and the status bar.
The status bar should be hidden or the menu bar moved down.

Tested with the latest code from the iOS7 branch.

![capture decran 2013-09-06 a 10 23 19](https://f.cloud.github.com/assets/1521015/1094564/9da36220-16cd-11e3-807c-f172936558c0.png)

**Comment by folletto** [comment]
Thanks :)

**Comment by benoitchantre** [comment]
I return you my thanks. You're doing a great job.

**Comment by benoitchantre** [comment]
I cannot reproduce the issue, thanks @Simbul.

**Comment by benoitchantre** [comment]
One question though: why are the buttons/icons blue in the modal view when they are red in the shelf?

**Comment by folletto** [comment]
That's a good question. :D

**Comment by benoitchantre** [comment]
That's probably the default color (same color in mobile Safari), but it should be coherent with the color used in the shelf.

**Comment by Simbul** [comment]
Yes that's a good point. Can you open a separate issue about that please? :)

**Comment by benoitchantre** [comment]
It's here: #1137

**Comment by folletto** [comment]
Thanks. :)
