### ISSUE TITLE
Play/Pause embed youtube video problem 

### ISSUE THREAD

**Issue by albertora** [Simbul/baker#1113]
I have some embed youtube video's in baker. The first time when I touch play button, the video start but the second time when I want pause it, the video stops but immediately returns to play. 
I don't know if it's a baker problem but I test this on my ipad with safari and works fine. 

Any idea?

**Comment by folletto** [comment]
Videos always have problems due to the way they auto-detect the browser they are working in. Did you read the other threads on the topic? There might be a solution in there.

There are a few (just search for "youtube" in the search field above). :)

**Comment by albertora** [comment]
Yes, I've been searching in all issues without any solution. 
Keep searching :) Thanks!

**Comment by albertora** [comment]
Ok finally it works! I've removed the UserAgent in AppDelegate.m and solved problem.

**Comment by folletto** [comment]
Great! And thank you for reporting back how you solved it. :)
