### ISSUE TITLE
url not handled: improvements

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1115]
The `urlnothandled` event could be removed if the error was handled directly in Baker. A JavaScript alert could be triggered directly from Baker with a proper error message extracted from `Localizable.strings`.

If you find it too radical to remove this event, it would be great to add a message extracted from `Localizable.strings` to the event object. That way the JavaScript alert would receive the message in the appropriate language.

What do you think @folletto?

**Comment by folletto** [comment]
That handles has been created specifically to handle application calls inside the page via JavaScript, so it's not doable to handle it directly in Baker. See thread #862 for the whole discussion. :)

However, let's always go back to the reasons: is there a specific need that moving the handler inside Baker would solve? :)

**Comment by benoitchantre** [comment]
If it could be inside Baker, it would give a solid error handling for all publications without extra attention. It's something easy to forget if your page doesn't need JavaScript.

I thought it could be done like the js snippet to detect the `meta` paged, but I have a basic understanding of Objective-C and I'm maybe wrong.

What's missing is an error message in the event data. That would be better for localization and maintainability.

**Comment by folletto** [comment]
My question would be why are you even writing a third party protocol URL if you aren't going to pay attention to it? If that's an issue, don't use the protocol. If you use it and you don't like the error, manage it. :)

No? :)

**Comment by benoitchantre** [comment]
I agree, but some publisers use solutions like _in5_ or a cms to build pubications. These users a
less aware of what happens behind the scene.

What do you think about the idea to add the error message in the event object?
Maybe I can implement it.

**Comment by folletto** [comment]
Well... I think that In5 should provide the JavaScript code to do that then. That's the idea. :)

With an error message you will interrupt the experience of the event managed in JS. Imagine you're writing some code to gracefully handle a missing protocol, where if it doesn't work it reverts back to a standard URL and opens a different overlay. With the error message it means that the user first get the error and then it's not-so-gracefully managed opening the overlay.

**Comment by benoitchantre** [comment]
I think my explanation was not clear. My idea was to add a message to the event data, for example in `event.message`. The message would come from the `Localizable.strings`. You can use it or not when you listen to the `urlnothandled` event, the same way can use or not `event.url`. Everything would be managed by JS at the end, but with more data to play with to build the error displayed to the end user. It would be easier to display the error in the case of a multilingual app.

**Comment by folletto** [comment]
Oh, ok. Now I understand. :)
Wouldn't be simpler then to just tell the HTML which language is the app running with, and let the HTML handle that as well? In that way you won't have to jump between HTML and Obj-C to change a simple string. :)

**Comment by benoitchantre** [comment]
I think you are right. I thought it could help for a multilingual app.
In the case you have a multilingual app which relies on localized folders, you can simply duplicate the script and hardcode the error message in the proper language.
If you use JavaScript templates, the error messages can be handled that like any content.
Thanks for your comments @folletto
