### ISSUE TITLE
Image Map %

### ISSUE THREAD

**Issue by JamesMowatt** [Simbul/baker#1117]
Hi Guys,

I am just wondering if Baker can read an image map for hotspots as a percentage or if their is a way to set them for all of the iPad resolutions?

I load an image on a webpage and need to add hotspots.

Thanks

**Comment by folletto** [comment]
Baker content is just HTML: if what you ask is possible in HTML – and more specifically Mobile Safari, it's 99.99% likely it will work in Baker. :)
So, check online for that, and if the answer is positive, then you can. :)

**Comment by JamesMowatt** [comment]
I had checked online however I wondered what baker was using to load HTML as most browsers require fixed co-ordinates for a hotspot, however Safari accepts a percentage. Quite convenient =)
