### ISSUE TITLE
iOS7: strange animation for status bar 

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1118]
The status bar is displayed with the index when you open the book. This is the normal and expected behavior.

When you open the index manually (double tap), the navigation bar is displayed but not the status bar. When you close the index, the status bar appears. It disappears once move the view (horizontally or vertically).

The status bar should appear when you open the index view and disappear when you hide the index view.

Tested with the [latest commit](https://github.com/Simbul/baker/commit/f7b8860d4fecaf290143ca09702b46aca1fc39db) in the iOS7 branch.

**Comment by folletto** [comment]
Yep, it's a bug. Still working on that. :)

**Comment by benoitchantre** [comment]
Ok, thanks.

**Comment by benoitchantre** [comment]
I cannot reproduce it (54ed334eb7246950db47f0bae672514bba67e24e)
Thanks @Xm4s
