### ISSUE TITLE
Magmagoo magazine - issue app store

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#112]
http://itunes.apple.com/us/app/magmagoo-magazine/id451749704?l=es&ls=1&mt=8

http://magmagoo.com/

thaks to all people who let us made this version. (we are spanish whit a terrible english, sorry)

**Comment by Virtualsweden** [comment]
Ho, did you make this from Baker, it looks like the Adobe solution?

**Comment by mutador** [comment]
the ipad version yes, is adobe digital publishing
the iphone/ipod version is baker/laker

**Comment by folletto** [comment]
Hello! Thanks for the tip! :)

May I ask why did you choose Adobe Digital edition instead of doing everything with Baker? :)

**Comment by mutador** [comment]
try to explain whit the help of google translator

baker is a great solution But it's not valid for profesional digital publishing.
the user experince is not right. it need to load the entire magazine at once.

adobe at the moment is the best solution in my opinion but it is too expensive and other bad thigs about big companys...

I've been looking at other solutions like pugpig and honestly I'll sacrifice speed and versatility in front of a full load of the magazine as soon as some improvements in the framework pugpig.

Could you explain more in detail my reasons.

another thing is that I very much hope that you succeed on a full charge at some point, it is essential, if you had with an html templates system you could have a very competitive solution compared to adobe Aquafadas,etc

clear that perhaps your goals are different.

so if it is that I am very grateful for the work they have done and share it, i hope you try the baker efforts to improve and evolve for a full load experience.

i would like to talk about this things and colaborate, but my english is very poor and i only a designer and user experience skills.

regards

**Comment by folletto** [comment]
Thanks for the feedback and the confirmation of the fields where we need to improve. :)

That said, I may suggest you to try our current master version: while not fully ready, many speed improvement are already there and will be soon released in the 3.0. :)

**Comment by tablazines** [comment]
Currently I use a solution by Alligator Magazines for my publishing solution but i'm about to publish another publication and after seeing "Her World" decided to go with Baker.

I don't need templates as I can create my own layouts... my main concern for a professional magazine is...
1. Newsstand integration
2. Reader app which allows loading of multiple issues (though someone has a working model of this done in Laker)
3. A way to get rid the loading screen between pages.

If these issues could be solved... Baker would probably be the premiere publishing platform for a lot of us indie magazine publisher.

**Comment by mutador** [comment]
same as tablazines.....

**Comment by folletto** [comment]
Well, 1 and 2 are in the timeline, and 3 should probably arrive with Baker 3.0. It's not really a way to get rid of the loading (because that's CPU and RAM dependent) but it's a nice workaround. :)

Also, a few developer started developing 2, but until now there is still no completed code that we could merge to the main branch of Baker. :)

**Comment by tablazines** [comment]
So is there an ETA on 3.0? My magazine should be finished this week but I'm wondering on whether I should wait for 3.0

**Comment by folletto** [comment]
Well, we wanted to release it a couple of weeks ago but we hit a few bugs, so now we are working on them. We are targeting now an early september release, due to additional holiday delays.

What I could suggest is however to give a try to the trunk version, and check back before submitting the store for news. :)

**Comment by tablazines** [comment]
Ok. Thanks

**Comment by tablazines** [comment]
Last question... Where can I get the trunk version...  Lol

**Comment by folletto** [comment]
No trouble. :)
Click on "Source" on the top menu of this page, then use git (there are lots of manuals) or just download the latest version (big Download button on the right of the Source page). :)

**Comment by tablazines** [comment]
Thanx

**Comment by Virtualsweden** [comment]
Am I blind or ?  
Can only find 
2.0
1.1
1.0

**Comment by folletto** [comment]
It's not very clear, yeah, but since 3.0 isn't still released there's no 3.0 package. You should "Download Source", either zip or tar.gz. :)

**Comment by mutador** [comment]
hi
any date for 3.0? or the new especifictions?

thanks

**Comment by folletto** [comment]
Nope, sorry. We are still working optimization, unfortunately we're still not there.

You can check the milestone 3.0 to see how it's going. :)
