### ISSUE TITLE
iOS7 Icon Problems

### ISSUE THREAD

**Issue by drking0211** [Simbul/baker#1124]
Just got this message back from Apple Dev Center on submission of app for newsstand.

Must be an iOS7 issue.

Missing recommended icon file - The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format.

The app is now under review so not a biggie but worth fixing for sure.

Guess we will have to add these icons to the icon folder and reference them in the info.plist.

Regards

David

**Comment by folletto** [comment]
Yep. It's a simple change, but we will add the defaults. :)

**Comment by benoitchantre** [comment]
Xcode5 has a new feature: the asset catalog. It was added to simplify management of images that are used by the app. It would be great to use it. It is compatible with targets for iOS6.
What do you think @folletto?

**Comment by folletto** [comment]
We have yet to look into it, no time, sorry. :/

**Comment by benoitchantre** [comment]
I understand, that's not the priority.

**Comment by ghost** [comment]
@drking0211, did your newsstand app get approved without these icons, or did you manage to add them? I got the same message, except there was no mention of the 120x120 icon.

**Comment by jbavington** [comment]
@FunkeXMix , yes you'll need to include the 120x120 icon size as well.  I haven't yet tested this but Validating your binary Archive in Xcode before submission to upload might flag any iOS7 issues.

**Comment by ghost** [comment]
I can confirm that validation in the newest, non beta version of Xcode 4.6.3 does not flag these issues during validation. iOS7 Icon sizes are only sent as a 'recommendation' by email once you upload the binary, there is no mention of it being required. I took some comfort in that since I do not know how to add more icons to Baker, I just replace the four given ones, but we need 6 icons to play with if we are going to include iOS7 icons for iPad. @jbavington, how did you find out it is required now?

**Comment by folletto** [comment]
You fell just in the transition to iOS7. Right now iOS7 is mandatory for submission, given tomorrow's release. So yes: you must provide iOS7 icons now. :)

Xcode 5 will also be the only mandated platform as well.

**Comment by ghost** [comment]
Uhum..'wohoo'

**Comment by jbavington** [comment]
@FunkeXMix:
1.  Create the new icons (name them icon_76.png, icon_120.png, etc.) and place in the same Finder folder as the other icons (Baker/icon)
2.  Load your project in Xcode
3.  In the Project Navigator (that shows your files/folders in the left column), drag your new icons into the Baker/icon folder in your project.  Select copy to destination.
4.  Click the blue shaded Project Name at the top of your list of files.  In the centre section of your window, click the TARGETS name, probably "Baker".  Click the "Info" tab.
5.  Locate the section that says "Icon files".  Click the + sign beside Item 2 and then enter the new name of your icon "icon_76.png".  Repeat this for the 3 new icons.

You should be good!

**Comment by chris-82** [comment]
I just have trouble with the icon stuff as well. I'll now try what @jbavington wrote....
![screenshot](https://f.cloud.github.com/assets/4965875/1158811/9ce85d3a-1fbb-11e3-951f-d3ea0f1b5aab.png)

**Comment by chris-82** [comment]
I just used this new "assets catalog" (xcassets) container where you can just drag&drop the adequate images to a predefined form. Everything "seems" to be fine now - I was just able to upload the app :+1: 

![bildschirmfoto 2013-09-17 um 19 16 54](https://f.cloud.github.com/assets/4965875/1158870/02f49b9c-1fbd-11e3-9803-5ccea88fc36e.png)

**Comment by ghost** [comment]
@jbavington, thank you so very much! That made me understand xcode logic a whole lot more. Having to put the file in the folder directory, then dragging this to the project navigator, and adding references to info section was not exactly user friendly in regards to UI. Maybe the assets catalog is their solution to that. I'll test it next time.

**Comment by jbavington** [comment]
@FunkeXMix, glad it worked out!  Yes, a very unintuitive method for sure.  @chris-82, I'll also check out Xcode 5 and the Asset Catalog.  Would be awesome if it means less hair pulling!

**Comment by im21** [comment]
Hi Guys. Can you please let me know if you are using code from the Master Branch or IOS7 branch. I am currently working with Master Branch v4.1.1 and would like to know if I will be able to submit it for approval this week. Many thanks.

**Comment by chris-82** [comment]
@im21: I'm using the iOS 7 branch (https://github.com/Simbul/baker/tree/ios7)

**Comment by chris-82** [comment]
...my App Update using the iOS 7 branch just got approved by Apple :+1:

**Comment by folletto** [comment]
Considering it's still incomplete, that's good news :D

**Comment by jbavington** [comment]
Sometimes the Great Fruit in the Sky shines brightly upon you.....

**Comment by im21** [comment]
OK that great news @chris-82 can you please send the url of your app on store. Well so i guess if i submit the one of Master branch it will be rejected as it doesn't comply to IOS7 guidelines right?

**Comment by drking0211** [comment]
Just a quick update on this issue.

Our app got accepted with those pesky missing icons.

But better that it is corrected for the future from hereon in.

Regards

dk

**Comment by chris-82** [comment]
@im21 here is the link: http://goo.gl/VPKyX4 . But it's available in Germany only. There is a english version of the app which is available in the UK, Ireland and Australia: http://goo.gl/LS3PCW .

If you won't use the iOS 7 branch it will be rejected by Apple certainly; but furthermore it has some ugly bugs on iOS 7.

**Comment by im21** [comment]
Thanks @chris-82, i guess i should rework on the app now using the iOS7 branch. I see that the app offer only free subscriptions you didn't have any issue with Apple reviewers about that?  #1089

**Comment by chris-82** [comment]
@im21, I never had any problems with Apple's reviewers team since starting the App about 1 1/2 years ago (about 6-7 App Updates per version in this time).

**Comment by im21** [comment]
@chris-82  that's great. crossing fingers that I don't get any issue about that also. Thanks once again and specially to @folletto @Simbul for their awesome work and support for this app.

**Comment by folletto** [comment]
@chris-82 It's OT but: may I ask why you're limiting the english version to these countries?

**Comment by chris-82** [comment]
@folletto I would like to have the magazine completely open by myself. But it's a licencing matter...at the moment the publisher of the magazine wants to have the iPad App only in the countries the printed magazine is beeing published.

**Comment by folletto** [comment]
Ok, so it's the client. I never understood companies that prefer not making money, but ok. Thanks for the reply. :)

**Comment by folletto** [comment]
Could you please have a look at the latest commit in `master`? We switched to the Asset Catalog as suggested. :)

**Comment by benoitchantre** [comment]
@folletto it works for me.

**Comment by folletto** [comment]
Thanks! :D

**Comment by dkamdar** [comment]
Anyone got this while trying to submit on the App Store?

I checked the "newsstand-app-icon.imageset" in the "BakerAssets.xcassets" folder and I have the files there. Is there a link broken or missing?

![screen shot 2013-11-15 at 3 01 12 am](https://f.cloud.github.com/assets/1485304/1548522/2d11cb2e-4dcc-11e3-83f9-e98b62a32a12.png)

**Comment by yujulio** [comment]
Are you using the lastest version of Baker?

2013/11/15 dkamdar notifications@github.com

**Comment by drking0211** [comment]
I had a similar problem.

Try downloading the latest version of Baker. And ensure you have all the correct images in situ.

That should fix it.

dk

**Comment by dkamdar** [comment]
@yujulio @drking0211 - I had to moved newsstand-app-icon.png outside of Assets Catalog folder to the main folder and it worked fine. I made some modifications to Baker code so did not wanna try with the latest one as I was not code versioning the changes :(

![screen shot 2013-11-18 at 4 25 34 pm](https://f.cloud.github.com/assets/1485304/1562085/1de2f2f6-5040-11e3-8529-c393f0e6e0c2.png)

**Comment by rlarrett** [comment]
I am having the same problem in validation my app. I get the error message that newsstand-app-icon cannot be found (see attached), yet it is present in the bundle. I tried placing it outside the main folder per @drking0211 but this does not help. If I delete the string newsstand-app-icon from the info.plist the app validates perfectly, then is rejected by iTunes Connect. I am using the 4.2 version of Baker, which I believe is the latest. It is most vexing. Any suggestions?
![error](https://f.cloud.github.com/assets/367918/1847419/0286ca10-764b-11e3-8435-183e6a690dbb.jpg)

**Comment by RibenZ0rd** [comment]
i'm having the same issue over n over, and putting the icons in the main folder doesn't work.

**Comment by RolandMarianna** [comment]
@RiberZ0rd
Try to change the deployment target from 7.0 to 6.0. I hope that will help.

**Comment by RibenZ0rd** [comment]
@RolandMarianna 
Thanks for the reply, but that can't be done or it will fail on the submit, but i've found the solution alright, you have to copy via finder the 2 png icon files and the json from the folder newsstand icons to the folder info, and then copy via xcode the same files to the folder baker (don't forget to check option to duplicate the files). Hope that helps someone out.

**Comment by drewmantoo** [comment]
Has there been a solution to this?? I'm going crazy... haha

**Comment by Simbul** [comment]
@drewmantoo please use the new Baker issue tracker for questions: https://github.com/BakerFramework/baker/issues

This one is not in use anymore: it's only open as a reference :wink:
