### ISSUE TITLE
Point out selected page in index

### ISSUE THREAD

**Issue by tonyrh** [Simbul/baker#1126]
Hello,

I'd like to put some visual indication of the selected page in the index. Maybe a different border color or something like that. Do you think this is possible using js only or do I need to modify obj code?

Thanks,
Antonio

**Comment by tonyrh** [comment]
Oh sorry, I just saw there is a feature request for this here: #350

**Comment by folletto** [comment]
Yup, that's right. As mentioned there, you might workaround that with localStorage, here some more details #719.
I'll close this one. :)
