### ISSUE TITLE
One Issue updating price endlessly

### ISSUE THREAD

**Issue by JamesMowatt** [Simbul/baker#1129]
Hi Guys,

Just released my first (of two) newsstand apps.

In the simulator it updates price no problem, in the live version one issue sits and updates price constantly.

Any ideas?

Thanks

James

**Comment by nin9creative** [comment]
Tom just went through a similar thing with his Slapshot app.

It resolved itself after about a day and suddenly started working.  It seems to me that it's an iTunes connect
replication/propagation issue once an app goes live.

Andrew

**Comment by JamesMowatt** [comment]
I find it odd that I have never had the issue before. Guess i will wait a few days and see what happens. Surely by the time an IAP is approved it should be available.

**Comment by nin9creative** [comment]
Not saying I totally understand why, but it just happened with Tom.

Andrew

**Comment by JamesMowatt** [comment]
Somewhere in Apple's great wisdom lol

**Comment by JamesMowatt** [comment]
As an extension of this problem, it has started working now. However when I tap download on anything it just spins on connecting?

**Comment by Simbul** [comment]
It sounds like you're talking about #1133 now. Do you think we can close this issue and continue the discussion on the other one?

**Comment by JamesMowatt** [comment]
This was a different issue to #1133 however was resolved, apple IAPs once approved take up to 48hrs to release, like apps.

**Comment by folletto** [comment]
Good to know. Thanks for the feedback, will surely be useful to others. :)
