### ISSUE TITLE
Should we keep the StoreKit Framework for the standalone mode?

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1132]
I have noticed that the StoreKit Framework is linked by default when we download Baker.

Should we keep it when we use the standalone mode?
The tutorial doesn't mention it, but I think it should be removed.

If you already use Xcode 5, you can see under the Capabilities panel that In-App Purchase is activated. At the moment Baker support In-App Purchase only in Newsstand mode.

**Comment by folletto** [comment]
I'm not sure... it works well so far. What would be the reason to remove it?

**Comment by benoitchantre** [comment]
To avoid to load something useless, but in the case it's a system library, it doesn't overload the app. Am I right?
In this case, we can keep it without worrying about it.

**Comment by folletto** [comment]
Well I don't know frankly. But if there's evidence of some kind of optimization that could be done (maybe with weak linking? not sure) we could look into it. But I would do it only if there's a drawback in not doing it, otherwise a person can just simply manually remove it. :)

**Comment by benoitchantre** [comment]
Ok, no problem. Thanks
