### ISSUE TITLE
iOS 7 Update guide

### ISSUE THREAD

**Issue by Regolo-Design** [Simbul/baker#1134]
Hi, 
any tips for update an iOS 6 app to iOS 7? I need to modify the new branch for iOS7 or can update the only baker files on iOS 6 version?

Thank you

**Comment by folletto** [comment]
We still haven't released a iOS7 compatible version of Baker. Once it will be released you can take that and configure it to your needs. :)

**Comment by fobetor** [comment]
I have tested the ios7 version you leaved around here, and it works in ios7, BUT... the final release will work in ios 5-6 and 7 or its going to work just in ios7 as this prerelease do?
I'm testing them in my ipad with ios7, but the version 7 does not work in previos ios versions... just to know if we will have to just develop for ios 7 from now on....
Thanks

**Comment by folletto** [comment]
The next version should work with iOS6 and 7, as actually should already be doing if you're testing the `ios7` branch. What problems does the `ios7` have for you on iOS6?

Also: could you please open a separate issue? This is closed and refers to another question. :)

**Comment by fobetor** [comment]
No problem with ios6-7 testing. Escuse me for the response in this same issue.
