### ISSUE TITLE
How to add icons (other then default ones)?

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#1135]
Hi,

I am using Magrocket. What I want to do is use the default Baker CFBundlePrimayIcon icons since they are required. But the UINewsstandIcon should have a magazine shape instead of square. I have tried to add my own files with other names then the default square icons like below. But Baker is ignoring my newsstand icon and always prioritizing the square ones. What do I need to do to let it use my custom newsstand icon? Furthermore, later on I tried to add default icons by dragging and dropping in the targets - summary section. Now icons that I have in the icons folder no longer show in the project navigator and adding files with the .plist does not seem to add them there either. Anyone know how to fix these two things? Thank you.

`````` <key>CFBundleIcons</key>
    <dict>
        <key>CFBundlePrimaryIcon</key>
        <dict>
            <key>CFBundleIconFiles</key>
            <array>
                <string>ios-icon-ipad</string>
            </array>
            <key>UIPrerenderedIcon</key>
            <false/>
        </dict>
        <key>UINewsstandIcon</key>
        <dict>
            <key>CFBundleIconFiles</key>
            <array>
                <string>newsstandicon.png</string>
            </array><key>UINewsstandBindingEdge</key>
            <string>UINewsstandBindingEdgeLeft</string>
            <key>UINewsstandBindingType</key>
            <string>UINewsstandBindingTypeMagazine</string>
        </dict>
    </dict>```
``````

**Comment by folletto** [comment]
First of all, I'd start to replace all the Baker-provided icons as given. ;)

For everything else, you should really ask on Stackoverflow or Apple forums, since it's not directly a Baker issue. I'll leave this open for a few days tho just in case someone can chime in quickly to give you some pointer. :)

**Comment by ghost** [comment]
I put in all the details in a new fresh version of Baker and used the info from my old one to adapt it. And used the @2x named icons for Newsstand. That worked. Thank you.

I changed the title of this thread to something more constructive for everyone having the same question.

Could you or someone tell us how icon names are referenced in Baker, this would be useful so we can add icons ourselves especially important now when iOS7 requires additional sizes. I don't quite understand why the connection to the icons breaks if they are given a different name when the corresponding file is in the icon folder. I thought it would work adding additional icons since the WWDC2011 Newsstand video made it look easy. Baker does not seem to accept any other file names the default ones it seems. Why is that?
