### ISSUE TITLE
Background color when swiping past the first or the last page

### ISSUE THREAD

**Issue by rogerdcarvalho** [Simbul/baker#1139]
Hi,

When you swipe past the first or the last page, a different background color is used then the one you define in the book.json. It may be swiping out of the UIView or something? Is there a way for me to change that color?

This is Baker 4.1 btw, running on iOS 6.1.3 on iPad

**Comment by folletto** [comment]
Uhm I can't reproduce it on Baker 4.1 and iOS 6.1.3. What color is appearing below? Could you are step-by-steps instructions from the 4.1 download to reproduce it? Did you test the current master?

**Comment by rogerdcarvalho** [comment]
Realize I wasn't using the latest master... Will test and report back! Thanks!

**Comment by rogerdcarvalho** [comment]
Got it fixed, was due to the wrong color code in the book.json after all. Thanks!

**Comment by folletto** [comment]
Wonderful! Thanks for taking care of coming back and adding your feedback. :)
