### ISSUE TITLE
Poll: Remove Tapping / Scrolling multiple pages?

### ISSUE THREAD

**Issue by Xm4s** [Simbul/baker#114]
Hi!

We noticed that most publisher that use Baker disable the quick tap / scroll to jump back or forward for more than one page.
Also others publishing platform (Pugpig or Adobe Digital Edition) don't seem to implement this feature.

When we start Baker this feature was fundamental, since we didn't have any other way to quickly jump between pages, but also it introduced a slight delay in the loading of pages (to detect if the user was multitapping).

Now we have added the navigation bar to our framework, which allow the users to select the page they want to jump to, so we were thinking to removing the "multitap" feature to try to improve the loading speed and the overall reading experience.

But of course we would like to hear the community opinion before removing this feature from Baker: do you think it's a good idea or do you like it the way it is now? What will you do?

Thank you all for the support :)

**Comment by jeffehobbs** [comment]
I would say your thinking is sound -- remove the multi tap feature. As Baker pages become more complex, render and display speed is going to be more and more critical, and as you say, the navigation bar is going to improve the overall reading experience.

**Comment by folletto** [comment]
Given that we noticed many authors disable it and basically no other app does that... it's probably a feature that might be removed... even if it was nice to have, getting that tiny speedup in basically all the page might be worth it. :)

**Comment by aldriq** [comment]
Go ahead, I think it makes sense, the navigation bar is far more useful and immediately obvious to the user than the multi-tap access.

**Comment by k8fisher** [comment]
Can I ask how you disable quick tap detection I only ask as Ive tried to setup publications which have image maps within them that dont appear to react to user interation. Could this be linked?

**Comment by folletto** [comment]
Uhm it doesn't seem related to me but... who knows. Let's test. Two things:
1. Can you give us a sample page to test?
2. Does it work in Safari mobile? :)

**Comment by folletto** [comment]
Thanks to you all! :D

Ok, given the received feedback we are going to remove it. :)

**Comment by k8fisher** [comment]
Apologies for not getting back, Ive only just returned from holiday I thought Id put up the question just before leaving to check if anyone had noticed this.

Will this amendment be implemented in the next revision of baker?

**Comment by folletto** [comment]
Yes, exactly. It's already on Master. :)
