### ISSUE TITLE
dynamic shelf

### ISSUE THREAD

**Issue by fmenossi** [Simbul/baker#1143]
hi,
i have a project which a user need to login and load a dynamic shef depending on its category.
is it possible to call a dynamic json based on login?

**Comment by folletto** [comment]
Hi there. :)
I'm sorry but there's nothing like that in Baker, neither login or separate shelf (even if the separate shelf are mostly a server-side thing once you have the login). You have to add these features yourself.

**Comment by fmenossi** [comment]
Hi Folletto, thanks for the rapid reply.
And is it possible to create folders to separe different kind of issues?
Thanks again!

**Comment by folletto** [comment]
Nop, Baker has one shelf only.
