### ISSUE TITLE
iOS7 issue requires guidance

### ISSUE THREAD

**Issue by pattypatpat** [Simbul/baker#1146]
Hi there,

I've used Baker in combination with Magrocket (both amazing) to create a newsstand app with paid issues that was submitted a few weeks back to Apple for the first time and I must have been in the boat that requires the app to be completely compatible with iOS7 so unfortunately the app was rejected due to the following bug (comments copied from Apple's feedback):

"We found that your app exhibited one or more bugs, when reviewed on iPad running iOS 7, on both Wi-Fi and cellular networks, which is not in compliance with the App Store Review Guidelines.

Specifically, after the user purchase the current issue, the contents are not available to download. Please see the attached screenshot for details."

I've attached their screenshot below (first one). 

After receiving this comment, I updated my Xcode to the latest version and began testing with iOS7 on the simulator. In my case, I get the app running but the 'Updating Price' doesn't stop spinning and it tends to get stuck here. Any direction, any pointers would really help, as I'm not sure what to tackle or if there is something missing in either Baker or Magrocket that is specific for iOS7. The app seems to work fine on iOS 5 to 6.1

Thanks in advance!

![screenshot_0 1](https://f.cloud.github.com/assets/4339703/1188964/d2b2af48-23f7-11e3-8832-d70e9be70ed8.png)
![ios simulator screen shot 19 09 2013 4 08 31 pm](https://f.cloud.github.com/assets/4339703/1188966/dee48bc4-23f7-11e3-8f5e-bd5524fc7549.png)

**Comment by pattypatpat** [comment]
Also noticing that on iOS7 simulator, I'm missing the refresh and Subscribe buttons as well as the text of the issue appears to have character limits (this is not happening in the screenshot from Apple though).

**Comment by benoitchantre** [comment]
Please follow the guidelines on the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page. You can also give a look at this issue: #1129 

If your app works in iOS 5, you are not using an up to date version. For info, Baker is not ready for iOS7 at the moment (the iOS7 branch is not merged in the master branch).

**Comment by pattypatpat** [comment]
Thanks for the reference link, I'll have look. As for iOS5 you're right, my above post is incorrect as while the previous baker framework I was using worked, I've since upgraded and it hasn't been (which is fine, we don't want to cater for iOS 5). 

As for iOS7 being part of Baker, how can I go about using this separate addition if it's not in the master branch yet. Sorry if my question isn't really intelligent, non-coder here. Or would you happen to know when it might be merged, so I can factor it into the timeline for my app :)

Thanks so much for the help!

**Comment by benoitchantre** [comment]
You can [download the code directly](https://github.com/Simbul/baker/archive/ios7.zip) from the Github website, but it's better to use git to merge the changes.

**Comment by pattypatpat** [comment]
Thanks, I might give it a try. Presuming I have to fork the repository and then clone it to Github Desktop to be able to merge the IOS7 changes? Thanks for everything so far, the developer world never ceases to amaze and even though I'm new to Github, I love this site!

**Comment by benoitchantre** [comment]
You don't need to fork the repository. You only need to clone the repository on your desktop.

**Comment by pattypatpat** [comment]
Oh already done so. Isn't it safer if I fork it as I really don't want to do any damage to the master baker files? I'm not sure how commits work if I'm working on the real repository off my desktop and not a fork.

Maybe I should stop asking questions, I might be in over my head and may not be worth your time to educate me on things that I should already know if I plan to work on the files in any form. Just help me out with the above question: will the changes I make affect any of the original baker files? That was my reasoning for forking, so I could play around with the code without upsetting anyone else's work.

**Comment by benoitchantre** [comment]
You can't push to the Baker repository directly, you don't have the permission for that. There's no risk to corrupt the remote repository with your commits.

If you want to submit something to the original repository, you need to make a local branch with you changes, then to push this local branch to you fork and finally to make a pull request on Github.

**Comment by pattypatpat** [comment]
Ah good, I would have thought so... (surprisingly) I've seen systems where external contributors have messed up internal structures. Just wanted to be certain. Fantastic, i'll give it a go then! Thanks for the help! I'll leave this open and if I manage to resolve the issue I was having over the next few days, will notify you and close the issue.

**Comment by drking0211** [comment]
A quick update regarding IOS7 and related/unrelated issues.

Our newsstand magazine "Bead me" was accepted by Apple with those missing icons and is now on sale.

I did have an issue with the constant "updating price" on one of the IAPs so, via MagRocket, disabled that particular IAP to investigate.

As reported elsewhere this was a matter of Apple propagating the IAP even though the App itself showed up.

Took 24 hours to fix itself. I then enabled through MagRocket.

Hope that helps someone.

dk

**Comment by nin9creative** [comment]
Yeah, that's been the feedback that I've seen from others.  That there is a delay with the IAP propagation through the App Store.

It would be great if there were a programatic way to know this from the MagRocket backend...  That way if an item was "published"
and was a paid issue - MagRocket could hold off on displaying it to the shelf until it knew that the price info was actually available.

Or it could be handled somehow on the Baker side, not sure...

I just see it as a problem for Magazines that have a more frequent release schedule - dealing with timing for releasing etc...

Andrew

**Comment by ghost** [comment]
@drking0211. Do you mean to say that we should disable the IAP for the issue to be able to fix itself? Or do you think it is okey to have everything enabled and wait? I have waited 4 days already and it's still the same in the xcide 5 simulator. I can add that for me everything works when I test on my iPad with ios7. Therefore I already sent my app for approval since it worked on my iPad. I hope this was a good move since I do not see the simulator being an important factor in the review process. Or what do you think?

**Comment by drking0211** [comment]
I disabled the IAP (within MagRocket) which was not properly propagated as I did not want users to get a bad experience of the APP.

You need to check IAPs on an actual physical device using a test account.  You can set this up within the itunesconnect dev centre.

As for the review process, it seems it takes around a week for approval and then IAPs take another 1-2 days to work as expected.

Hope that helps.

**Comment by pattypatpat** [comment]
Hi @drking0211, thanks for the comments - I'm just getting back to fixing the issue I am having and attempting what has worked for you. I'm a bit unclear on your process as this is my first submission and the app only has one magazine issue to begin with. From my understanding, I should have the magazine issue as 'Pending' on Magrocket when I submit the app and then wait 1-2 days after it's approved and then switch it to 'Published'? This prevents me from testing purchases and downloads so maybe I'm not following your procedure correctly. Are you able to help suggest how I go about this? Thanks for your help!

**Comment by pattypatpat** [comment]
I should mention that after merging the iOS7 branch with the master branch and using that, I have resolved the missing shelf navigation bar issues and the magazine appears and does display the price when testing on iPad (not on simulator where it shows the spinning Updating Price), however after clicking 'Buy' and accepting the pop-up alerts confirming purchase, the magazine still displays the Buy button. This only happens on iOS7 :(, iOS6.1/6 is working fine.

Debuggers shows the following on simulator: 2013-10-02 09:12:45.320 Baker[3142:a0b] ====== Baker Newsstand Mode enabled ======
2013-10-02 09:12:45.422 Baker[3142:a0b] [AppDelegate] Push Notification - Device Token, review: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo=0xb3a89b0 {NSLocalizedDescription=remote notifications are not supported in the simulator}
2013-10-02 09:12:45.658 Baker[3142:a0b] [BakerShelf] Newsstand - Added Edition-34 2013-08-26 23:06:17 +0000
2013-10-02 09:12:48.546 Baker[3142:a0b] App Store request failure: Error Domain=SSErrorDomain Code=2 "Cannot connect to iTunes Store" UserInfo=0xc2925b0 {NSLocalizedDescription=Cannot connect to iTunes Store}
2013-10-02 09:12:48.621 Baker[3142:a0b] App Store request failure: Error Domain=SSErrorDomain Code=2 "Cannot connect to iTunes Store" UserInfo=0xb3bc820 {NSLocalizedDescription=Cannot connect to iTunes Store}

**Comment by ghost** [comment]
Try turning off issue security under publications in Magrocket.

**Comment by pattypatpat** [comment]
Changing issues security didn't resolve it but both developer mode on 'true' and the new iOS7 branch fixed the purchasing issue and made the app work smoothly. Submitted today checking everything again, fingers crossed! Thank you all for the amazing help :+1:

**Comment by MrKistic** [comment]
According to Apple's release notes for for Xcode 5.0:

StoreKit (In-App purchases) will not work in the Simulator. 13962338

You can read it here:

https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/index.html#//apple_ref/doc/uid/TP40001051

Basically you can only test IAP on a real device for iOS 7, not within the simulator. If you try, you get the "Cannot connect to iTunes Store" errors and the always "Updating Price..." status.
