### ISSUE TITLE
Validation of book.json: is it too strict?

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#1147]
In `book.json`, a page of an issue can be either an url or an object.

When you choose to use an object, there's an error during the validation of `book.json` in the case you add an additional key/value.

``` json
{
    "url": "Front-Article.html",
    "title": "The Wonders of Hpub",
    "author": "The community"
}
```

_Pass the validation made by Baker._

``` json
{
    "url": "Front-Article.html",
    "title": "The Wonders of Hpub",
    "author": "The community",
    "chapter": "Introduction"
}
```

_Doesn't pass the validation made by Baker._

```
2013-09-24 16:12:20.288 Baker[7876:c07] [BakerBook] ERROR: param 'chapter' should not be a String. Check it in 'book.json'.
2013-09-24 16:12:20.288 Baker[7876:c07] [BakerBook] ERROR: param 'contents' is not validating. Check it in 'book.json'.
```

Why is it so strict?
The HPub spec doesn't mention that we cannot add key/value to describe a page.

**Comment by folletto** [comment]
That's correct. That's a part of the standard not supported by Baker.

**Comment by benoitchantre** [comment]
Ok, thanks for the info.

**Comment by benoitchantre** [comment]
Should we keep this issue open?

**Comment by folletto** [comment]
Probably not. ;)
