### ISSUE TITLE
problem click sound

### ISSUE THREAD

**Issue by kekko73** [Simbul/baker#1151]
Hello to all,
I am finishing a catalog for a client of mine, I have set the button sound, tried it with my Ipad (ios7) everything works perfectly, I did install everything on iPad (iOS6) the customer clicks sound do not work.
What might be the problem?
Thank all!

**Comment by folletto** [comment]
Unfortunately it's hard to tell with this little information, at least for me... you can hope that someone got the same issue. :/

Maybe it could help if you report here the code you used to generate the sound, so maybe someone could verify that.

Also, might be worth trying in Mobile Safari on both iOS6 and iOS7 and see what happens there. Did you try?
