### ISSUE TITLE
ERROR: Cannot find 'book.json'

### ISSUE THREAD

**Issue by rossellap** [Simbul/baker#1159]
I am having this error:
ERROR: Cannot find 'book.json'

My book.json validated in JSONLint.
The book.json is in the root of books.
What's the matter?
![schermata 2013-10-01 alle 11 36 22 am](https://f.cloud.github.com/assets/3698630/1244162/a8150984-2a7d-11e3-926d-90d62440b637.png)

**Comment by benoitchantre** [comment]
You must have a folder inside books/ to contain the book.

**Comment by rossellap** [comment]
Thank you, benoitchantre. That was the problem and it works now.
I got confused because I am working with Friar and Baker at the same time.
