### ISSUE TITLE
How was the navigation done in "HerWorld" and "Female" magazines?

### ISSUE THREAD

**Issue by tablazines** [Simbul/baker#116]
I thought the navigation used in those two publications were pretty awesome. Is there any where I can find out how that was done?

**Comment by Xm4s** [comment]
If you want to know specifically how that was done you may try to contact the publisher.

However you can setup a navigation bar like the one on those magazine in the latest version of Baker: simply put an index.html file with your navigation bar and Baker will handle the rest :)

More in this feature can be found here: https://github.com/Simbul/baker/issues/17

**Comment by tablazines** [comment]
Thank tou...
