### ISSUE TITLE
Is it possible to force new download of existing downloaded issue?

### ISSUE THREAD

**Issue by DaveAtDog** [Simbul/baker#1160]
Hi,

Is it possible to force new download of existing downloaded issue? For example: I already have an issue downloaded into my app and our client updates that issue and wants all it's readers to have the latest version.

I've tried sending a notification to download an already existing issue but it says it's already downloaded — even though the content is new.

Maybe I could add another flag to the APS payload in the notification signifying that there's an updated .hpub file to download and just overwrite what's there?

**Comment by folletto** [comment]
It's not possible at the moment, you will have to code that feature yourself. You can have a look at the conversation on the issue that is tracking it, #638. :)
