### ISSUE TITLE
ETA for an iOS 7 version of the Baker app.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1161]
Hello my name is Travis. I am using the Baker app publish a magazine (no duh), I got it working great with iOS 6, but when iOS 7 came up and i put the app into Xcode 5 it got all messed up. So, anyways does anybody know an ETA for a Baker app iOS 7 version?

**Comment by folletto** [comment]
I'm sorry but we aren't able to provide ETAs. Have a look at the 4.2 milestone here, by that you should be able to keep track of the progress. :)
