### ISSUE TITLE
can't download hpub from server

### ISSUE THREAD

**Issue by kremisi** [Simbul/baker#1164]
Hi,
following your tutorial:

Upload each Hpub to your web server (just the Hpub). Test and make sure that you can download them from a browser. (e.g. http://example.com/publication/issue1.hpub).

That is impossible to me. I'm using a simple Linux hosting service on Aruba. I tried to modify some htaccess and permissions but nothing. There is a lack of personal knowledge in this domain... What are the provider are you using that allow easily to download hpub files?

Thanks in advance.

**Comment by folletto** [comment]
Does Aruba allow download of these files at all? Might be worth asking their technical support.

**Comment by kremisi** [comment]
Ok, this is the solution for me: I have to store the file on a Linux server not a Windows one. In this way I can download correctly the .hpub and .json extension.

**Comment by folletto** [comment]
Woah. It seems a very specific Aruba issue. Well discovered! :)

Thanks for coming back with the solution, I'm sure others will find that useful. :)
