### ISSUE TITLE
Google Analytics: some help please

### ISSUE THREAD

**Issue by fobetor** [Simbul/baker#1168]
Hello,
 I've implemented the google analytics lybraries with GA 3.01, in Baker for ios7... I've done everything you mentiones in your wiki, BUT...(perhaps a stupid queston)... 

Why I dont see my events in GA Real Time panel? I should?
and:
Why Baker only report in my log some of the events present in BakerAnalyticsEvents.m you have programmed?
I have used my new tracking code etc....
Perhaps I'm missing something
Thank you

**Comment by folletto** [comment]
Hello there! :)

I think that evern the "Real Time" panel isn't realtime. I didn't use that for long, but during the tests I did when I implemented the code, there was a delay between the action and the Real Time display, sometimes even minutes.

About the logs... we don't log events. The logging there exists regardless of the events. :)
If you want to check that just uncomment the `NSLog` call on line 98 in `BakerAnalyticsEvents.m`. :)

**Comment by fobetor** [comment]
Thank you... I'll wait to see if Analytics records the events later again.
The logs I refer to are the ones you say: NSLog(@"[BakerAnalyticsEvent] Received event %@", [notification name]); // Uncomment this to debug

I just  see the @"BakerViewPage" event, and two more. The page event only when clicked in the index thumbnails, not when I go frompage to page.... I dont know if this is what it should be ...

**Comment by folletto** [comment]
Is it the same issue as this one: #1144?

**Comment by fobetor** [comment]
Yes.. it seems similar, but I havent gone into the code itself... 
Thanks

**Comment by folletto** [comment]
Ok, then I'll close this one. Feel free to reply there if you have anything else to add on the issue. :)

**Comment by fobetor** [comment]
OK, thank you, I'll try to dig in the code.

**Comment by jhmac** [comment]
I can see the active users in real time but not any other information in GA. Is that typical for real time or have I done something wrong?
Sorry, I can see location as well. It is about 120 miles off target though.

**Comment by fobetor** [comment]
Its typical, at least for me in real time. Only users and Screen
To see other information you must look some time later in the other statistics

Enviado desde mi iPad

**Comment by jhmac** [comment]
Thanks for the feed back. I am seeing more info this morning.
