### ISSUE TITLE
Can you use image maps in a document?

### ISSUE THREAD

**Issue by tablazines** [Simbul/baker#117]
My magazine is exported from Quark as an image file. Some of the text contains links that need to be clicked on. Can I use image maps in Baker for links...?

**Comment by Xm4s** [comment]
Sure! Since image maps are supported in Safari mobile they should work well within Baker too :)

**Comment by tablazines** [comment]
Ok.. I thought my image maps might somehow interfere with the sliding of the pages.

**Comment by tablazines** [comment]
thanx
