### ISSUE TITLE
Subscription issue with migrating to Baker for iOS 7

### ISSUE THREAD

**Issue by JosephMacReady** [Simbul/baker#1170]
My subscription settings all worked (and still do) fine with the old app, 

```
com.valkalinic.enactmentmag.subscriptions.free
```

is approved in iTunes Connect and set in the old Baker project.
Now I'm trying to get it all to the Baker for iOS 7, so I set 

```
#define FREE_SUBSCRIPTION_PRODUCT_ID @"com.valkalinic.enactmentmag.subscriptions.free"
```

in Constants.h.
The subscription options are properly shown but when selected, the _Subscription failure_ message is displayed and the simulator output states "_Trying to buy unavailable product com.valkalinic.enactmentmag.subscriptions.free_".

What am I missing?

**Comment by nicholasmartin** [comment]
Not sure if you are using Xcode 5 and iOS7 but in that case, you cannot test purchases or subscriptions in the Simulator. Currently it has to be tested on an actual device. Normally though you would just receive an error code 2 "cannot connect to iTunes store" so this could be something else. Either way, try it out on a device if you can to see if it makes a difference.

**Comment by JosephMacReady** [comment]
Thank you, @lifestylenetworker !

Yes, using latest Xcode and iOS on the device, ran on it and the message "_Subscription failure, cannot connect to iTunes Store_" is displayed while the output says "_Payment transaction failure: 
Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo=0x1567d460 {NSLocalizedDescription=Cannot connect to iTunes Store}_"

Any ideas?

**Comment by nicholasmartin** [comment]
What backend are you using? As it's a free subscription, maybe that isn't implemented yet? Try setting up a paid subscription and see if that works? Really just using the elimination method here :)

**Comment by JosephMacReady** [comment]
@lifestylenetworker  I'm not sure what you mean, don't use any backend service, manage it by hand, just host and then update the JSON list. 
Then free subs would't work for anyone using iOS 7 Baker, right?
Tried setting up new free and paid subscriptions but the same error occurs, although it does fetch the right prices from iTunes Connect.

What is happening here? :D

**Comment by nicholasmartin** [comment]
Hmm yeah sounds like you should be good to go.

Try following the steps here to do a proper Xcode cleanup:
https://github.com/Simbul/baker/wiki/Problems-and-Debugging

**Comment by JosephMacReady** [comment]
@lifestylenetworker Thanks! Cleaned it all up, no change, downloaded fresh a Baker release from the site and plugged in the subscription, still; 

```
013-10-09 12:15:58.274 Baker[4830:60b] Action sheet: com.valkalinic.enactmentmag.subscriptions.free
2013-10-09 12:15:58.277 Baker[4830:60b] ############ UPDATED TRANSACTIONS (
    <SKPaymentTransaction: 0x17d3ca20>
)
2013-10-09 12:15:59.483 Baker[4830:60b] ############ UPDATED TRANSACTIONS (
    <SKPaymentTransaction: 0x17d3ca20>
)
2013-10-09 12:15:59.484 Baker[4830:60b] Payment transaction failure: Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo=0x17e8f010 {NSLocalizedDescription=Cannot connect to iTunes Store}
```

Other ideas?

**Comment by folletto** [comment]
Ok, one thing I can point out is that your first message was _"Trying to buy unavailable product"_ while in the last two is now _"Cannot connect to iTunes Store"_. So, it's definitely something in the iTunes Connect configuration.

Are you testing with a sandbox + sandbox user?

**Comment by JosephMacReady** [comment]
That's it, can't believe I'd miss it, so we still need it for testing new versions even when the app is live, got it! Just sign in with a test account.
Thanks so much @folletto and @lifestylenetworker :)
I was over at the _Tutorial for Newsstand with In App Purchase_ Baker Wiki page and the Apple doc _Testing a Store_ is down, I can't find the new link to the same article but the closest I did is the same subject in the Mac library; https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/StoreKitGuide/DevelopingwithStoreKit/DevelopingwithStoreKit.html

**Comment by folletto** [comment]
Thanks. :)
And good to know you solved it! Excellent. :)
