### ISSUE TITLE
Has anyone added ability to adjust font size within an HPUB?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#1174]
I know that this is something that would need to be implemented within the actual HPUB itself, vs a Baker feature...

However I was curious if anyone had done anything like this?  User option for font size for the publication.

Andrew

**Comment by Simbul** [comment]
The support is in there already since we added support for iOS 7. The app uses the system-wide accessibility parameters.
As for the book, there's a javascript callback (and a JS endpoint) to propagate the value of the accessibility parameter (look for `contentsizechange` in the codebase, unfortunately we've had no time to document that yet).

**Comment by benoitchantre** [comment]
You should be able to set the value of `font-size` to `-apple-system-body`, `-apple-system-headline1`, ... directly in your stylesheet. I haven't yet tested that.

**Comment by Simbul** [comment]
@benoitchantre nice find! I've tested it with the following code, and it works.

``` html
<div style="font:-apple-system-body">body</div>
<div style="font:-apple-system-caption1">caption1</div>
<div style="font:-apple-system-caption2">caption2</div>
<div style="font:-apple-system-footnote">footnote</div>
<div style="font:-apple-system-headline">headline</div>
<div style="font:-apple-system-short-body">short-body</div>
<div style="font:-apple-system-short-caption1">short-caption1</div>
<div style="font:-apple-system-short-footnote">short-footnote</div>
<div style="font:-apple-system-short-headline">short-headline</div>
<div style="font:-apple-system-short-subheadline">short-subheadline</div>
```

This is where I found out most about it: http://mir.aculo.us/2013/09/16/how-to-create-a-web-app-that-looks-like-a-ios7-native-app-part-1/

**Comment by benoitchantre** [comment]
I have found that info in the video session 600 (WWDC 2013), but the post from Thomas Fuchs you linked is a good resource too.

**Comment by Simbul** [comment]
Documentation added on the wiki: https://github.com/Simbul/baker/wiki/Dynamic-type-fonts-support
