### ISSUE TITLE
"Trying to buy unavailable product" on iOS7

### ISSUE THREAD

**Issue by n0vecento** [Simbul/baker#1176]
I updated my newsstand app to iOS7 and applied it to the store.
The app was rejected because it fails to subscribe user in iOS7 devices, while it works  on iOS6 devices (I tested it on iOS7 iPad, iOS7 iPad Simulator and iOS6 iPad Simulator).
These are my settings:
My in-app purchase datas:
![schermata 2013-10-15 alle 11 05 56](https://f.cloud.github.com/assets/2522020/1332390/bc6c8450-3579-11e3-9a47-37f73ec1476e.png)
Constants.h:
![schermata 2013-10-15 alle 11 06 09](https://f.cloud.github.com/assets/2522020/1332397/e1069c06-3579-11e3-9df4-166454fce188.png)
and the error:
![schermata 2013-10-15 alle 11 06 36](https://f.cloud.github.com/assets/2522020/1332400/eebe253a-3579-11e3-9aa1-0ddd4c4da44d.png)

If there's been a variation on how newsstand/in-app purchase works in iOS7, I couldn't find any information on Apple documentation.

Thanks

**Comment by folletto** [comment]
What's the reason for the rejection? 

Because the error from what you pasted could simply be due to iTunes Connect Sandbox configuration (are you using a sandbox user?) and have nothing to do with the rejection reason.

**Comment by n0vecento** [comment]
The reason is: "It was not possible to purchase the Free Subscription. Please see the attached screenshot/s for more information."
(If I test it in iOS6, the sandbox respond correctly)

**Comment by folletto** [comment]
And what was the screenshot? One of the above?

**Comment by n0vecento** [comment]
This is the screenshot they attached:
![screenshot_0](https://f.cloud.github.com/assets/2522020/1332628/24d0d640-357f-11e3-9e11-662cdb9ee385.png)
This is the screenshot if I try to subscribe on iOS7:
![schermata 2013-10-15 alle 11 48 42](https://f.cloud.github.com/assets/2522020/1332635/4077767e-357f-11e3-9ba1-b5887e767c0b.png)
And this if I try it on iOS 6:
![schermata 2013-10-15 alle 11 50 01](https://f.cloud.github.com/assets/2522020/1332636/5132dfd0-357f-11e3-9207-e9f0cacfbd46.png)

and this is the log on iOS6:
![schermata 2013-10-15 alle 11 52 18](https://f.cloud.github.com/assets/2522020/1332646/966335c8-357f-11e3-93e1-2b3a9bb8c847.png)

**Comment by folletto** [comment]
Uhm. Does that mean you aren't getting the "Confirm Subscription" message in iOS7?

**Comment by n0vecento** [comment]
Yes, it responds that BabylonIT is not an avalaible product.

**Comment by n0vecento** [comment]
Don't know if it can help, I inserted some NSLog in PurchasesManager.m to try to understand where the problem is.

This is the iOS7 log

```
 ====== Baker Newsstand Mode enabled ======
1  Luca: (void)retrievePricesFor: -> productIDs : {(
    BabylonIT
)}
2  (void)retrievePricesFor: -> [productRequest start]
3  (void)retrievePricesFor: -> productIDs : {(
)}
4  Action sheet: BabylonIT
5  (SKProduct *)productFor: -> [self.products objectForKey:productID] : (null)
6  (BOOL)purchase: -> productID : BabylonIT
7  (BOOL)purchase: -> product : (null)
8  Trying to buy unavailable product BabylonIT
```

This is, instead, the iOS6 log:

```
 ====== Baker Newsstand Mode enabled ======
1  (void)retrievePricesFor: -> productIDs : {(
    BabylonIT
)}
2  (void)retrievePricesFor: -> [productRequest start]
3  (void)retrievePricesFor: -> productIDs : {(
)}
4  (void)productRequest: enter in the function
5  (void)productsRequest: -> request : SKProductsRequest: 0x9da0f70
6  (void)productsRequest: -> response : SKProductsResponse: 0x9dbbb50
7  Received 1 products from App Store
8  - BabylonIT
9  Action sheet: BabylonIT
10 (SKProduct *)productFor: -> [self.products objectForKey:productID] : SKProduct: 0x9dafd90
11 (BOOL)purchase: -> productID : BabylonIT
12 (BOOL)purchase: -> product : SKProduct: 0x9dafd90
13 Received 1 transactions from App Store
14 - purchasing: BabylonIT
```

It seems that the (void)productRequest in iOS7 doesn't start, even if it is started in line 2 of iOS7 log.

**Comment by n0vecento** [comment]
Well, don't ask why, but I rebooted my iPad and now it works.
On the iOS7 iPad simulator it doesn't work, but I read that it's normal since it's now no more possible to test In-App Purchase on iOS7 simulators.
I'll submit again the app, hoping that Apple operators reboots their iPad too.

(However this is a really strange behavior)

Thanks for your time.

**Comment by folletto** [comment]
That's a VERY good news. :)

Thanks a lot for taking the time to come back and report how you solved it. :)

**Comment by n0vecento** [comment]
It was a so stupid solution that I couldn't lose the opportunity to share it :)
