### ISSUE TITLE
New Baker app available in AppStore

### ISSUE THREAD

**Issue by rogerdcarvalho** [Simbul/baker#1177]
Thank you guys so much for all your contributions, it's amazing to see what is possible using the frameworks you've created. 

There is one small thing though. When you buy a subscription on one device and then install the app on another device, the subscription menu says 'not subscribed'. When you try to resubscribe, iOS says you are already subscribed, but Baker still sees it as 'not subscribed'. Is this a known issue? Should I raise a separate issue for this?

Regards,

Roger

**Comment by folletto** [comment]
That's great! :D

—

Regarding your question: in the drop down menu isn't there a "Restore purchases"? That should trigger the subscription renewal on the second device. :)
If there isn't... open a new issue with the information you get by following [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging).

**Comment by rogerdcarvalho** [comment]
No, but that's because all the issues currently available are free. I suppose when I release the first paid issue, the option to restore purchases should appear?

**Comment by folletto** [comment]
Likely. ;)
