### ISSUE TITLE
iframe-Support (for supporting googleMaps)

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#118]
Hey everybody!

If an iFrame is placed within a page, the app exists and Safari opens.
Would be cool to implement GoogleMaps etc (which is a piece of cake with iframes ;) ).

Thanks
florian

**Comment by folletto** [comment]
That's totally a requirement. We need to check it out. If you have anything that could help, please link it to us here. ;)

**Comment by ffranke** [comment]
Romain gave a hint in the Laker-Comments:

About iFrames, this is due to the way Baker handles load request in the web view. 

The hack is to make some changes in the following method in the RootViewController:

```
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType
```

You could, for example, change the last else condition into:

```
} else {
  // ****** Handle: *
  return YES;
  //[[UIApplication sharedApplication] openURL:[request URL]];
}
```

that should do the trick.

This is just a start, it would need a little more investigation. Hope it'll help nevertheless.

Best regards,
Romain

**Comment by folletto** [comment]
It might break something else, but we'll check, thanks! :D
(also tell Romain to come here if he has some more tips to share :D)

**Comment by Xm4s** [comment]
As I answer to Romain on the Laker website commenting [[UIApplication sharedApplication] openURL:[request URL]] will cause all the external link (if any) clicked on the page to be opened in the current UIWebView.
Of course if there aren't any link that point outside your Baker book this should really do the trick nicely.
The best solution I can think of is to recognize and handle an iframe request separately and load it in the UIWebView, while send all the other ones to Safari Mobile… but of course it’s easier said than done :)

**Comment by folletto** [comment]
So, the idea could be that to open a link in Mobile Safari you have to add a parameter to the URL, like:

http://example.org/page.html?referrer=baker

Any other link instead will be opened inside Baker itself. So if you type:

http://example.org/page.html

The page will be opened _INSIDE_ Baker, as a page.

**Comment by Virtualsweden** [comment]
Would it be possible to use offline maps with
http://plebeosaur.us/you-are-here-with-safari-on-iphone/

If you have your own svg or jpg-map and you have the extent coordinates of the image and the gps would follow the map. Or download Google offline maps?

**Comment by folletto** [comment]
Well, we are using the same engine as Safari Mobile, so everything you can do there should be possible in Baker too. :)

**Comment by jpantuso** [comment]
The approach of adding a parameter to the URL sounds good. It would add a lot of flexibility. And it is simple enough for any non-developer authors to make use of. 

It also sets a precedent for how to do other custom things with URLs inside Baker in future.

**Comment by folletto** [comment]
Excellent, thanks for the feedback! :D
We'll go ahead with that then. :)

**Comment by Xm4s** [comment]
Ok, with the commit bd24c19270cbe53923c7585fde24fda355a188f1 external url are loaded inside Baker, so there should be no more problems with iFrames. To go on Safari Mobile just add to the url the param referrer=Baker.

Test on this feature are kindly appreciated :)
Thanks

**Comment by danielbenjamins** [comment]
I'm testing this at the moment and iframes are working fine: GREAT! However when I'm making a link in the iframe (to display other content in the iframe) Baker is quickly displaying the black loading screen + title) and then quickly fades out again. Safari desktop is displaying this without delay or loading, it's working awesome.

Does this has anything to do with "referrer=Baker" like @Xm4s mentioned? If so, where do I place this parameter?
Right now I placed it like this:
`<a href="iframe-001-01b.html?referrer=Baker">`

I tried switching off the Three-Card loading method, but that doesn't do the trick.

**Comment by folletto** [comment]
It might be a bug, because I think Xm4s already worked on a similar problem while addressing this issue.

Adding the ?referrer=Baker will take you _outside_ the book to Safari, so I suppose it's not what are you looking for. :)

**Comment by danielbenjamins** [comment]
Ha, no that's not what I'm looking for :)
Alright, so let's wait if @Xm4s can figure this out!

**Comment by Xm4s** [comment]
Ok, with the commit 46825733e540b07bb70c590a3757636ebb2dd9ff I should have fixed the problem.

Thank you for pointing it out, please let me know if now all work correctly :)

**Comment by danielbenjamins** [comment]
Yeah, it's working great, thanks! :)

**Comment by Xm4s** [comment]
Thank you for the support :)
