### ISSUE TITLE
Baker app not working in Xcode 5.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1180]
The baker app runs in Xcode 5 but it has a lot of bugs in it. Any ideas on how to fix it? Will Baker come out with an iOS 7 baker app.  am not an Xcode wizard, i only know enough to navigate around.

**Comment by folletto** [comment]
The current version of Baker isn't iOS7 compatible, the future version 4.2 will be. Just follow us ([twitter](https://twitter.com/BakerFramework) or [newsletter](http://bakerframework.com/)) to get the launch announcement. It should happen in the next few weeks. :)

In the meantime you might want to try the `master` version downloadable form GitHub. Even if it's not final yet, so it might contain bugs.
