### ISSUE TITLE
Subscriptions / IAP

### ISSUE THREAD

**Issue by OvenBaker** [Simbul/baker#1186]
Hi Guys

I'm having a lot of difficulty in getting a free subscription to work reliably in our magazine. It seems that depending on iOS version and simulator / device, I get completely different results. I can't seem to find much guidance via the Baker wiki on what I should be seeing, and which failures I can safely ignore vs which might indicate a problem.

At present, I'm getting:
#### iOS 7 / Simulator:

```
App Store request failure: Error Domain=SSErrorDomain Code=2 "Cannot connect to iTunes Store"
```
#### iOS 6.1 / Simulator

```
Received 1 products from App Store
cirquefreesubscription
Action sheet: cirquefreesubscription
Received 1 transactions from App Store
purchasing: cirquefreesubscription
Received 1 transactions from App Store
purchased: cirquefreesubscription
```
#### iOS 6.1 / iPad 2:

```
Received 0 products from App Store
Invalid product identifier: cirquefreesubscription
Trying to buy unavailable product cirquefreesubscription
```

I'm working off Baker 4.2 (commit 8537c3223f). I've checked that my bundle identifier matches the one provided in iTunes connect (by logging it from code even). The subscription is clear for sale and linked to the version for review. Being able to subscribe via the simulator is encouraging, but I don't understand why I can't do it from real device. I've tried whilst logged in to the device both as a regular iTunes user, an iTunes Connect test user and whilst logged out. I've regenerated my deployment profiles.

At this point, I've submitted to the App Store as is - I'm just concerned that I'm going to have problems during review. Is there any guidance on what should be working, or where I may be going wrong?

**Comment by RibenZ0rd** [comment]
I had similar experience with several simulators, the best way is definitly test it on a device with iOS7 and other with 6.1 (because those will be your major targets from now on). Cheers

**Comment by folletto** [comment]
From iOS7 isn't possible to test purchases from the simulator. 
Please check Apple documentation and... use a device. :)
