### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by RibenZ0rd** [Simbul/baker#1187]
Hi there, i have been working on a newsstand app with baker and now that everything is ready i tried to submit to the app store but after making the archive file the validation fails, it gives me these 2 errors.
![captura de ecr 2013-10-26 s 18 49 24](https://f.cloud.github.com/assets/5594792/1414076/d6bc3732-3e67-11e3-8095-aac84bdd746c.png)

I know it's a path issue but i honestly don't know how to fix it, i have seen that the files are described in the magazine-info.plist but i don't know how to "point" a path to them. Any help will be much apreciated. Thanks in advance.

**Comment by folletto** [comment]
Thanks for the report. :)

That's the Apple side of things, please refer to Apple's documentation and Apple's developer forums. StackOverflow can be also an excellent resource. :)

—

I'll keep this issue open as a reference to be checked for our next release, might be something we could ease. :)

**Comment by RibenZ0rd** [comment]
After trying to fix all the "errors" it finally passed submition BUT after submited i received a invalid binary at itunes connect and this email from apple.

"Dear developer,

We have discovered one or more issues with your recent delivery for "myappmag". To process your delivery, the following issues must be corrected:

Newsstand Icon - One or more of the Newsstand icons referenced by CFBundleIcons.UINewsstandIcon was not valid. The icon must be a .png file, at least 72 DPI, and it must have an aspect ratio between 1:2 and 2:1. Also, the artwork must be flat with no rounded corners.

Once these issues have been corrected, go to the Version Details page and click "Ready to Upload Binary." Continue through the submission process until the app status is "Waiting for Upload." You can then deliver the corrected binary.

Regards,

The App Store team"

**Comment by RibenZ0rd** [comment]
This was a fresh download of baker framework here from github (the newest update), i didn't modify any core files just the references needed to show my magazines and splash + icon files  (drag n drop).

**Comment by folletto** [comment]
Yes, but the icon is still _your_ icon, not Baker's. :)

**Comment by OvenBaker** [comment]
I had the exact same issue with a recent GitHub Baker version. I'm guessing it's a combination of iOS 7 requiring new icon sizes and the move to the assets file format. I had to add the required icons to the Baker project manually (I placed mine under Baker/Supporting Files/icon), and then added the filenames in the project configuration (Info tab -> Icon files iOS 5 -> Icon files). Needed two entries, one for the normal iPad icon and another for the newer 76 pixel version. Note that the entry there does not have a file extension and that you only put the entry for the "smaller" file version, iOS automatically checks if there is an identically named file with @2x appended (e.g. ios-icon-76@2x.png). Seemed to solve the problem, although I'm sure there's a slicker way of doing it.

**Comment by Xm4s** [comment]
With the commit 514a0cea88e867759cf72d1f780aed49a9e441b1 we've added sample assets for the newsstand application icon in the Asset Catalog and updated the plist icon files value. This should avoid problems during the validation process.

Of course they are only **samples**, you'll have to replace them with your custom icons :)

Thanks to everyone for the information provided regardinf this issue
