### ISSUE TITLE
Possible to do one column instead of 2 on iPad?

### ISSUE THREAD

**Issue by andrewvmail** [Simbul/baker#1189]
I would like to have a one column design is it possible to create a one column design for the baker shelf like the iPhone?
Thanks!
![cursor_and_ios_simulator_-_ipad_retina___ios_7 0 3__11b508_](https://f.cloud.github.com/assets/2431354/1426505/cab15ba4-406d-11e3-9eb9-e7cc93325dc5.jpg)

**Comment by folletto** [comment]
Hello there. :)

Baker doesn't provide that functionality out of the box unfortunately, but since it's an open framework you can do that change yourself.

The class you can start by looking is `UICollectionView` in the variable `gridView` and also have a look at `IssueViewController.m`.

**Comment by andrewvmail** [comment]
Thanks got it.
If someone needs an answer to this you can play around with the spacing 
and removed the divide by 2 in the first return of getIssuecellsize and changed minus 10 to minus 350. Pretty easy. 

```
(UI)getIssueContentMeasures
{
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        UI iPad = {
            .cellPadding   = 30,
            .thumbWidth    = 135,
            .thumbHeight   = 180,
            .contentOffset = 225
        };
        return iPad;
    } else {
        UI iPhone = {
            .cellPadding   = 22,
            .thumbWidth    = 87,
            .thumbHeight   = 116,
            .contentOffset = 128
        };
        return iPhone;
    }
}

+ (int)getIssueCellHeight
{
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        return 240;
    } else {
        return 190;
    }
}
+ (CGSize)getIssueCellSize
{
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
        return CGSizeMake((screenRect.size.width - 350), [IssueViewController getIssueCellHeight]);
    } else {
        return CGSizeMake(screenRect.size.width - 10, [IssueViewController getIssueCellHeight]);
    }
}

@end\
```

in `issueviewcontroller.m` at the very bottom changed the offset to 225 
![banners_and_alerts_and_ios_simulator_-_ipad_retina___ios_7 0 3__11b508_](https://f.cloud.github.com/assets/2431354/1443754/b0cc5aa6-41f1-11e3-8883-07a1edb34210.jpg)

**Comment by folletto** [comment]
Thanks for coming back with the feedback and the solution! That's great! :)

**Comment by AlmondFace** [comment]
im looking to make 3 columns, any ideas? ( i can work to move the track etc all below the cover art...), basically like this: 
![analog](https://cloud.githubusercontent.com/assets/9403556/4859986/9c95abe4-60f1-11e4-86bd-b122308ada94.jpg)
