### ISSUE TITLE
In-App Browser: external links open browser within app

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#119]
Hey there,

when clicking on an external link, it would be cool to display the page not in safari but in an overlay. So you won't be kicked out of the app.

florian

**Comment by tablazines** [comment]
I don't know... I hate apps that open their own browser because a lot of times it doesn't display the content correctly. I always find myself looking for the "open in Safari" button.

**Comment by yumyo** [comment]
I definitely agree with ffranke, a full screen inApp browser will be a great option

**Comment by ffranke** [comment]
Does anybody did it?

**Comment by steiny2k** [comment]
Hi there. Fixed it and sent you a pull request. I implemented and tested it together with ffranke (I'm this "programmer"-guy he's referring to some times :P).

See: https://github.com/Simbul/baker/pull/324

**Comment by Simbul** [comment]
I believe this has been implemented with pull request #325, so I'm closing the issue.
