### ISSUE TITLE
Downloading newsstand content in the background

### ISSUE THREAD

**Issue by tinytimmytim** [Simbul/baker#1190]
I have used Parse for sending push notifications, and it is working well when the app is running. However there is no background download when the app is not running. Do we need to modify the code in Baker to support background download?

**Comment by Xm4s** [comment]
Background download support was restored for iOS 7 with the commit 5e4d6abc90366bafe3d75514557f1cb22980999e and it shouldn't require any change in the Baker code.

However, iOS 7 background downloads may have some problems starting up when the app is not running, specifically some user have reported that **if an app is killed by the user a push notification won't restart it** (see my last comment in https://github.com/Simbul/baker/issues/999 for more details).

Also be aware that some users reported problems while using Parse to send push notification (https://github.com/Simbul/baker/issues/1063) : while this may not be related to your problem with background downloads it may be worth to take a look :)

Try to find if your problem falls in one of these two category and, in case it doesn't send us the steps to reproduce the bug. Please include : 
- the iOS version tested
- the notification payload sent
- the state of the app at each step (running, background, closed)

**Comment by tinytimmytim** [comment]
my colleague resolved the issue by downloading the latest version of Baker (branch master). Thank you for your help!
