### ISSUE TITLE
Magazine loads from the wrong page

### ISSUE THREAD

**Issue by michaeldemi** [Simbul/baker#1192]
Hello fellow bakers, I'm a total newbie and I'm sure both of these errors are self inflicted. any help would be much appreciated I'm using the 4.2 framework. 

I converted a 32 page magazine to 32 html files and created the index.html file as per instructions . When I load the magazine it automatically opens on page 10 and mistakenly thinks it's page 1. 

you can download the files here:
insurancelawyermag.com/ipad/shelf.json
insurancelawyermag.com/ipad/IL091013.hpub

I'm also experiencing a problem with the index.html file if I double tap and press on any thumbnail it will load in the index bar with the page that it is linked to.

**Comment by folletto** [comment]
The reason of the behaviour you describe is that Baker stores the last page you visited automatically to simplify the reading experience for the users. 
So if you want to see a magazine from the beginning you have to remove and reinstall the application entirely. :)

In general, for any problem, go first through the steps in [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging). You would have solved the issue. ;)

**Comment by michaeldemi** [comment]
I tried this before, my steps for cleaning and reinstalling were:
1. Going to product menu in xcode and selecting clean
2. Going to iOS Simulator main menue and selecting Reset Contents and Settings.

I'm afraid this issue persists.

**Comment by folletto** [comment]
Maybe it doesn't solve your issue, but if you read Problems and Debugging you see many other steps. Please follow through these first. :)

**Comment by michaeldemi** [comment]
Yes my apologies, lack of attention to detail on my part.
