### ISSUE TITLE
ios7 webview shifts up behind the status bar work fine in 6.x

### ISSUE THREAD

**Issue by dkamdar** [Simbul/baker#1193]
Hi,

On 6.1, the magazine displays correctly. However when I test it on 7.0 simulator, it shifts by (what looks like is the status bar height). 

Please see the screenshots here - 
iOS6.1 - 
![ios6 1](https://f.cloud.github.com/assets/1485304/1444326/0301783e-4205-11e3-8bd6-89b5e7b9ce74.png)

iOS7.0 - 
![ios7](https://f.cloud.github.com/assets/1485304/1444327/07df03da-4205-11e3-8502-0759323d43c4.png)

Notice the extra white space above as the webview has shifted up.

I am using the setting "UIViewControllerBasedStatusBarAppearance" in info.plist to NO. I also tried using YES (default) but the WebView goes behind the tranluscent status bar.

I tried to dig in BakerViewController.m and tried to change the frame if version is 7.0 or above for scrollView in viewDidLoad. However its does not take the new Y co-ordinate.

Heres what I am trying to do 
    if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {
        self.scrollView = [[[UIScrollView alloc] initWithFrame:CGRectMake(0, 20, pageWidth, pageHeight)] autorelease];

Can someone point me to where I should be tweaking this to make it work correctly on iOS7?

Thanks,
Dev.

**Comment by dkamdar** [comment]
Please close this. I was way off. Was working with version 4.1 ... downloaded 4.2 and it works perfectly ok.

**Comment by folletto** [comment]
Good to hear. :)
