### ISSUE TITLE
Instituting Three-Cards Rendering

### ISSUE THREAD

**Issue by BenjaminRPerry** [Simbul/baker#1195]
I've just set up my first magazine issue by exporting an interactive InDesign file to HTML5 using In5 and then uploading it into the Baker Framework.  

After some initial hiccups, everything is set up and the issue is able to be viewed. However, the page loads are extremely slow and some of the text boxes don't render completely.  Plus the interactivity is so jenky and slow most people would just ditch trying.

I'm hoping that instituting the Three-Cards rendering will help with these issues (page loading and hopefully getting the text to look right) but I'm unsure how to implement it.  

So far, I think I'm understanding that you put a new line in the book.json file on the server, but I'm unsure how to format it in code.  (I'm obviously new to this.) 

Let's say I have my issue call as:

[
  {
    "name": "a-study-in-scarlet",
    "title": "A Study in Scarlet",
    "info": "The original masterpiece by Sir A. Conan Doyle",
    "date": "1887-10-21 22:50:36",
    "cover": "http://example.com/a-study-in-scarlet/a-study-in-scarlet.png",
    "url": "http://example.com/a-study-in-scarlet/a-study-in-scarlet.hpub",
    "product_id": "com.example.Baker.issues.january2013"
  }
]

Would I add the command within the curly brackets or outside?  Or should I be placing it outside the brackets completely, like so:

[
  {
    "name": "a-study-in-scarlet",
    "title": "A Study in Scarlet",
    "info": "The original masterpiece by Sir A. Conan Doyle",
    "date": "1887-10-21 22:50:36",
    "cover": "http://example.com/a-study-in-scarlet/a-study-in-scarlet.png",
    "url": "http://example.com/a-study-in-scarlet/a-study-in-scarlet.hpub",
    "product_id": "com.example.Baker.issues.january2013"
  }
]

"-baker-rendering": "three-cards"

Any help would be greatly appreciated.  Can't wait to get the pages to load faster and smoother!

**Comment by folletto** [comment]
That's actually not a setting of `shelf.json` but of `book.json`. Have a look on the wiki the [HPub 1.0 specification](https://github.com/Simbul/baker/wiki/hpub-specification) and the [Baker extensions to it](https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters). :)

However, the problem you're having seems about the weight of the page... and unfortunately three-cards will do just the opposite, since it will consume 3x the memory you're consuming now. But it's still worth giving it a try, it's always difficult to tell what's the root cause of a rendering problem.

**Comment by BenjaminRPerry** [comment]
@folletto Thanks for the tips. I found the line in book.json and changed my layout font for quicker loading.  It's almost seamless now,  which is a worthwhile trade for now having custom fonts you can't even see.

I'm all set to load my app now, but the Application Uploader is telling me that the files for the App-Icon referenced in the Newsstand bundle in the info pane cannot be found in the project.  

I saw that someone else had this issue but I didn't see a posted answer/solution.  Have you had experience with this issue before?

I've tried loading the images in separately and putting their .png names in the info list, but it doesn't seem to help.  I've also loaded them into a different baker native asset icon folder that previously had nothing in it, but still the loader says they can't be found.

I also took the exact dimensions of the baker placeholder images.  
Any idea what I'm doing wrong here?

**Comment by folletto** [comment]
Yep, that's correct: just add the icons as Apple is telling you. Check Apple's documentation, and issue #1187. ;)

But... are you sure you're using the latest version, Baker 4.2, just released?

**Comment by BenjaminRPerry** [comment]
I've been working with the Baker Framework downloaded from the website Oct 30 I believe.  Maybe 29.  

While screwing around trying to get the files to be found, I changed the file name in the newsstand bundle to the .png file names.  I changed it back to "App-Icon" I believe, trying to recreate what was in the original framework.  Should these images be stored in the asset folder along with the other images?  I've been placing them there as well as within the templates in Xcode. 

Everything else seems to work perfectly except for the icon files listed in the info list under newsstand icon.  I checked out the other thread and the apple site but seem to be doing this all already.  (Although obviously not if it isn't working.)

Just to clarify, under the newsstand image bundle the line should read:
image 0        String       "App-icon"(Or whatever the name of the array is)

**Comment by BenjaminRPerry** [comment]
Okay, so nothing I was doing with placing the images inside the asset folders was working.  

So, I added them in the supporting documents folder and referenced their file names.  It worked like a charm and the app uploaded.  

Do you know if there will be issues I'm not anticipating down the road because of this?  I wouldn't think so, but it'd be nice to know for sure.  

Thanks so much for the awesome framework.  Literally took a matter of two or three days to get my mag up and sent to apple for review.  You guys work miracles.

**Comment by folletto** [comment]
Down the road? It's Apple's approval process, it's difficult to tell. :)

Thanks to you, for us it's great to see authors publish great stuff using our work. :)
