### ISSUE TITLE
Google Analytics - track which issue is opened

### ISSUE THREAD

**Issue by pmfadil** [Simbul/baker#1199]
Hello,

I have just implemented Google Analytics tracking within my app successfully. I would now like to be able to know which issues are being opened. I have been trying various methods in the BakerIssueOpen event but without success. 

Has anyone managed to find a simple way to do this?

**Comment by DaveAtDog** [comment]
I implemented tracking issue opening like this.

```
else if ([[notification name] isEqualToString:@"BakerIssueOpen"])
    {
        IssueViewController *issueViewController = [notification object];

        NSString *label = [NSString stringWithFormat:@"Baker Issue Open - %@", issueViewController.issue.ID];

        [tracker send:[[GAIDictionaryBuilder createEventWithCategory:@"ui_action"
                                                              action:@"open"
                                                               label:label
                                                               value:nil] build]];

        NSLog(@"[BakerAnalyticsEvent] label = %@", label);

    }
```

The receiveEvent method receives an object which in the case of "BakerIssueOpen" is the issueViewController. From there you can access the issue and ID.

**Comment by pmfadil** [comment]
Works like a charm! Thanks a lot @DaveAtDog !
