### ISSUE TITLE
Wink Toolkit

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#120]
Recently I found out about the Wink Toolkit. This is a JavaScript-toolkit with a lot of cool effects which work great on an iPad.
At the moment I'm trying to implement some of these effects in my books, but I'm having some difficulties.

The problem is that "jquery-1.5.min.js" (used in the Laker Compendium) has to be disabled to make the Wink-effects work. After disabling "jquery-1.5.min.js" you can no longer swipe to the next page...

Is there any change to make these scripts work together?

More info about Wink: http://www.winktoolkit.org/

**Comment by folletto** [comment]
I think you should ask Florian about this, Laker (and so, JavaScript) is his part. It's strange however that you can't swipe, since it's Baker doing that. Does it work if you tap on the side? :)

**Comment by danielbenjamins** [comment]
Ah, I see I mixed up some files. Let's try again :)

Some Wink-effects use specific JS-files like DND.js (Drag N' Drop: http://www.winktoolkit.org/documentation/module/712/)
Some of these JS-files won't work in combination with "jquery-1.5.min.js" so I had to disable this script.

I used Laker which doesn't support 'tapping' (yet?) so I thought disabling "jquery-1.5.min.js" killed the swiping-option, but that's not true I see now. I just tested it with Baker and indeed I can tap to switch pages, but can't swipe.

It seems that DND.js is killing the swipe-option in both Laker and Baker.

If someone wants to see my files to make things clear, just let me know.

**Comment by folletto** [comment]
Uh that's a wonderful analysis, thanks! :)

I might guess that DND.js intercepts ALL the touch events on the page, factually removing them from the app and making Baker unable to move. That's a very drastic choice by Wink, I wonder what they do in the codebase. :)

**Comment by danielbenjamins** [comment]
There's a topic (about 2 months old) on their discussion-platform where someone notices a bug:
http://www.winktoolkit.org/discussion/topic/puzzle-bug

There's also a solution for that particular bug on that page, but I don't know much about JS.
Also, I don't know if these modifications are already implemented in their latest version (I guess not), but if they are, then it's still killing the touch events :)

**Comment by folletto** [comment]
After checking it out for a bit I guess it's something we don't have any control on, it's completely eaten by the page and we can't intercept it. You might contact the author of Wink or check another way to do dnd... :|
