### ISSUE TITLE
Iphone 5 Launch Image Problem

### ISSUE THREAD

**Issue by drking0211** [Simbul/baker#1201]
Binary got rejected on submission this afternoon.

Anyone seen this one before?

> iPhone 5 Optimization Requirement - Your binary is not optimized for iPhone 5. New iPhone apps and app updates submitted targeting iOS 6 and above must support the 4-inch display on iPhone 5 and must include a launch image with the -568h size modifier immediately following the <basename> portion of the launch image's filename. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the iOS Human Interface Guidelines and iOS App Programming Guide.

Looks as though we need to add yet another image to the launchimage folder and reference that in the relevant contents.json.

Anyone got any scoop on this and/or rectification?

Such a good and timely idea to separate that image asset folder.

Regards

dk

**Comment by drking0211** [comment]
Just an update on this.

Have spent a while looking into the bug and it seems to be a fairly common problem i.e. selecting a target below IOS 7 and having the app supporting both Ipad and iPhone.

We have three major magazines out there now using the fabulous Baker framework and the split for Iphone users is around 40 per cent - so we don't want to alienate those people.  But at the same time if we set the target to IOS 7 we could be losing 25 per cent of the potential readership.

So we need to find a solution.

Been fiddling with the contents.json file and have the Default-568h@2x.png referenced and installed but getting this in the new Xcode 5 interface.

See below.

Ho hum ....

![screen shot 2013-11-04 at 20 28 51](https://f.cloud.github.com/assets/2156396/1468266/f29c6038-458f-11e3-99e9-61f45c5b2b00.png)

**Comment by folletto** [comment]
You just have to add the iPhone Portrait for iOS 6. Check the Asset Catalog documentation:
https://developer.apple.com/library/ios/recipes/xcode_help-image_catalog-1.0/Recipe.html#//apple_ref/doc/uid/TP40013303-CH1-SW1

For a quick reference, here's how to add it:

![add-asset-types-xcassets](https://f.cloud.github.com/assets/4389/1468552/d1c6e8ba-4594-11e3-8b10-2c2df46e7144.gif)

**Comment by drking0211** [comment]
Cool David.  I was over complicating this new asset folder topology.

Tnx for your quick response.

Regards

dk

**Comment by folletto** [comment]
Great. :)

**Comment by benjamincano** [comment]
@folletto I did as you specified above, I am using the latest build however I keep getting the same error even after doing your recommendation.

iPhone 5 Optimization Requirement - Your binary is not optimized for iPhone 5. New iPhone apps and app updates submitted targeting iOS 6 and above must support the 4-inch display on iPhone 5 and must include a launch image with the -568h size modifier immediately following the <basename> portion of the launch image's filename. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the iOS Human Interface Guidelines and iOS App Programming Guide.

**Comment by folletto** [comment]
Hello @musuko! That's strange... however Baker moved to a new tracker, this one is closed. So if you still have problems try to open a new issue there, detailing what you did exactly and where the error appears. :)

This is the new tracker: https://github.com/BakerFramework/baker/issues

**Comment by zlc000190** [comment]
@folletto  I got the same issue as musuko   .but  i'm not using  bakerframework. Can you give a help.
