### ISSUE TITLE
Changing Info in Shelf View

### ISSUE THREAD

**Issue by BenjaminRPerry** [Simbul/baker#1202]
Hello,

I found this tutorial on changing the info panel in the shelf view:
http://freney.org/2013/07/03/modifying-the-baker-framework/

But, I'm having a difficult time understanding its purpose.  The shelf view already has an info panel that is populated with a Baker image.  Is it possible to just find the location of the Baker placeholder and replace it with my own image?

If so... where would that be?

All help appreciated.

**Comment by folletto** [comment]
@freney contributed that and it was released with Baker 4.2 (see pull request #1004), so there's no need anymore for that. :)

Just replace the HTML, you can find it in `BakerShelf/info`. :)
