### ISSUE TITLE
Video not playing in iOS 5 beta

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#121]
I implemented a video in the current master, it is displayed correctly, but I can't touch the "play-Button". It just won't play.

The weird thing is, sometimes it is working, sometimes not. Is there some kind of layer, preventing input?

thanks!
florian

**Comment by folletto** [comment]
There's no layer above it, but it might be related to the current acceleration between pages. :)
We'll check. :)

**Comment by ffranke** [comment]
it's really weird, that it works 1 in ten times. First I assumed it's a memory problem or something like that...

**Comment by ffranke** [comment]
Any news about the videos...?

**Comment by folletto** [comment]
Not yet sorry, I'm the only one here these days, the other in the team are on hols. :)

**Comment by ffranke** [comment]
posted in the apple dev forums, because the bug is also in mobile safari:

https://devforums.apple.com/thread/118951?tstart=0

(login required)

**Comment by folletto** [comment]
Cool! :)

**Comment by folletto** [comment]
I'd say that we have to wait for the final version of iOS 5 to see if this issue is still there, since it's a WebKit issue. :)

**Comment by ffranke** [comment]
yeah that sounds like a good thing to do!

**Comment by folletto** [comment]
Hi ffranke, were you able to check if this bug is still there? :)

**Comment by ffranke** [comment]
I got the GM installed on my iPad 2. Looks good.
Btw: Did I send you the link to the magazine I did with the three-cards-version?
If no: http://itunes.apple.com/app/id460041187?mt=8

cheers

**Comment by folletto** [comment]
Excellent! I'll close this issue then. :)

Nope, you didn't! Looks awesome, I'll check it out better asap. :D
