### ISSUE TITLE
Rejected Binary (Issue 1): No In App Purchase API

### ISSUE THREAD

**Issue by d4rkl0rd3r3b05** [Simbul/baker#1215]
![screen shot 2013-11-18 at 11 03 07 am](https://f.cloud.github.com/assets/4295977/1560678/f72f8b7e-5012-11e3-9c5e-e275c2edb1e4.png)
![img_0606](https://f.cloud.github.com/assets/4295977/1560681/0394d8e2-5013-11e3-88f8-6dbc76bf3a09.PNG)
![img_0607](https://f.cloud.github.com/assets/4295977/1560680/0394959e-5013-11e3-8daa-7d4227c76265.PNG)

Hey Guys,

I submitted a Binary and got it rejected for the following reason.
#1:

We found that while you have submitted In App Purchase products for your app, the In App Purchase functionality is not present in your binary.

If you would like to utilize In App Purchase in your app, you will need to upload a new binary that incorporates the In App Purchase API to enable users to make a purchase

Once you revise and resubmit your binary, you will also need to resubmit your In App Purchases for review since they are in the state Developer Action Required. For each IAP product submitted, please be sure to edit the detail information or cancel the request to change the detail information for the In App Purchases using iTunes Connect.

For more information on how to implement In App Purchase in your application, please refer to the In App Purchase Programming Guide.

I have tested the APP Binary in Xcode using a test account in the Sandbox and it successfully purchases. 

Also, I have studied the case https://github.com/Simbul/baker/issues/989. But, unlike that we have been using the same download server for our ANDROID APP to make downloads.

Any ideas appreciated.

Here is a screenshot of my IAP setup in iTunes:

**Comment by nin9creative** [comment]
Did any IAP's get submitted as part of the binary?

**Comment by d4rkl0rd3r3b05** [comment]
Yes, we did submit 100(books and magazines) IAP's as part of the binary. And none of the IAP's has been reported as violation of the guidelines by the reviewer.

**Comment by nin9creative** [comment]
And you have some sort of server side backend setup with Baker to handle the purchases using the Baker API?

**Comment by d4rkl0rd3r3b05** [comment]
Thanks for your reply. But, now the review team finally seems to found In-App purchase in the uploaded binary after we asked for their clarification in the issue.

However, now they are reporting a different issue.

Reasons

Abandoned Batch
Thank you for your response.
Your app requires customers to register or login prior to purchasing or downloading a book, which is not in compliance with the App Store Review Guidelines.
It would be appropriate to provide users with a way to register at any time, if they wish to later extend access to additional iOS devices.

We tried to get a detail clarification on this issue from the Review Team, but they replied with the same thing again and again. 

Any help in the issue is much appreciated.

**Comment by nin9creative** [comment]
Knowing nothing about how your app works from what you've posted - it's difficult to say.  Is there a requirement for logging in or registering before someone can purchase or download a magazine/book?

**Comment by fturner19** [comment]
What they're explaining to you is that a customer shouldn't have to register to purchase a book or magazine. Remove the registration and see if the app gets approved!

**Comment by nin9creative** [comment]
Yeah, what @fturner19 said ;)

**Comment by d4rkl0rd3r3b05** [comment]
Yes, the app does require user to register/login before making a purchase/download. The application flow is thought in a such a way that it facilitate us to provide user with the restoration and device syncing using his app account.

**Comment by fturner19** [comment]
One of fundamental rules of getting your app approved is making sure your app is in compliance with Apples rules. The restore feature is all that's needed.

**Comment by nin9creative** [comment]
They are telling you that you can't require a user to register or login before making a purchase or downloading a book (in essence, using your application)...  It must be optional, but not required.

**Comment by fturner19** [comment]
Download the magazine "Slapshot" from the newsstand, he used a login feature within his app made with Baker. And that will give you and idea of what Apple approves regarding login within apps.

**Comment by d4rkl0rd3r3b05** [comment]
We did go through the app guidelines(multiple times). But  we are not still able to locate any guideline related to user login/registration.

Its very difficult for us to change the app flow because the same is happening on the Android platform.

But, can you explain why is it a problem if the app requires user to register or login before making a purchase...

Thanks.

**Comment by nin9creative** [comment]
It's a gray area.  I know there isn't anything specifically in the Newsstand Review Guidelines around it - however I've seen multiple rejections and difficulties around registration/login functionality.  As @fturner19 mentioned.  Check out "Slapshot" magazine.  You'll see there is the option to setup an account, but it is not required to use the application.

**Comment by d4rkl0rd3r3b05** [comment]
Guys, the app we are creating is not a newsstand application. Its somewhat similar to KOBO.

Regards.

**Comment by nin9creative** [comment]
Ok, regardless...  Not sure what input I have - they are telling you specifically why the app is being rejected.

**Comment by fturner19** [comment]
I think you're missing the point...You can't FORCE users to sign-up to purchase your books or magazines, it's has to be an option,but not a requirement. Exactly what @nin9creative just typed!

**Comment by folletto** [comment]
Apple has **always**\* rejected applications that don't work without registration. In other terms: the application _must_ work without any registration, but the registration can exist to provide additional features.

_\* There might be exceptions for pure client-server tools, such as remote desktop apps, enterprise secure clients and similar._
