### ISSUE TITLE
BAKER'S FUTURE: SAY HELLO TO THE NEW PROJECT LEAD

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#1216]
Baker started with a very simple [idea](http://intenseminimalism.com/2013/the-history-of-baker-framework/): making high-quality digital publishing open to everyone. Today the project reached its **third year** of life with some impressive numbers:
- 10 releases – one every 4 months
- 310 forks
- 16+ contributors
- 941 commits
- 14,901 lines of code
- 60+ new publications
- 1,200+ discussions
- 20,000+ downloads
- 200,000+ people reached

While the team has released many other open source projects in the past, Baker has been the first one to really pick up steam, as proven by the community: we had great discussions, lots of contributions and we even got to the point of having people outside of the core team independently answering questions.

Now, however, Baker needs to shift gears in order to keep being the awesome and simple platform so many people enjoyed: it must start integrating the framework with an open backend. We managed to do this up until now with an open, clear and simple API, but it’s obvious what the next step is, to make it even simpler for developers: we need to provide a ready-made platform that doesn’t require to waste any time implementing the backend.

That’s why we choose to give the project lead to [Andrew Krowczyk](https://twitter.com/nin9creative), one of the most active contributors, the author of our biggest fork (which influenced Baker’s own shelf implementation) and more importantly the author of [MagRocket](http://www.magrocket.com/), the best open source publishing backend for Baker Framework.

While there are other excellent platforms out there that complement Baker, Andrew’s commitment to keeping an open API, while at the same time developing an integrated solution, felt to us like the best choice going forward. And best of all, he’s a great contributor to Baker’s community and its culture.

To show our commitment to Andrew’s work, we are staying onboard as Advisors for the project.

This is Baker’s new home on GitHub, please give a warm welcome to Andrew and start posting there your feature requests and issues:
[https://github.com/BakerFramework/baker](https://github.com/BakerFramework/baker)

Read here Andrew's announcement:
[https://github.com/bakerframework/baker/issues/1](https://github.com/bakerframework/baker/issues/1)

Goodbye and thanks for all the fish,
_Davide, Alessandro, Marco_

**Comment by nonuts** [comment]
a big THANK YOU to you guys for tremendous work! You guys not only have delivered and maintained an excellent framework, I was also always very impressed by your fast responses to the community. all the best for your future endeavors ! :)

**Comment by MrKistic** [comment]
Wow. That sounds like a big change in direction. I'll be very interested to see how things go from here.

**Comment by benoitchantre** [comment]
@folletto, @Simbul, @Xm4s thanks for this amazing project and your excellent support. It was a pleasure to discuss with you about new features and to contribute modestly to move the project forward. I whish you all the best and I welcome @nin9creative to take the lead of this great project.

**Comment by MaverickWar** [comment]
Wow what a dramatic shake up, Congrats Andrew, looking forward to seeing new and great things to top up and already amazing framework.

Shame to see @Simbul, @folletto and @Xm4s leave though, Was it a time factor?

Well done Andrew though!

**Comment by MaverickWar** [comment]
Good that you will still be around as advisors though

**Comment by folletto** [comment]
@nonuts Thanks to you. These are the kind of words that helped us running these years. I'm sure they will help Andrews as well. :)

@MrKistic In a sense, we choose Andrew among many because he was the one that without any input was building what we would have built. So it's not much a change of direction, but letting the project go ahead in its growth. :)

@benoitchantre Don't be modest: you were one that made this community alive and supported the project with both suggestions and code. Thanks to you. :)

@MaverickWar Time was definitely a huge factor in our choice, but we probably wouldn't have made this decision at this moment if there wasn't a person so greatly aligned with the vision as Andrew is. Consider also that at this moment in time, just after iOS7 release, we are maximizing the time available for him to get into the project from a moment where the past release is done and the next release needs to be planned without any potential disruption from Apple for about 12 months. So, that's ideal. :)

Thanks everyone. :)

**Comment by tekdope** [comment]
A big thank you to the historic team for their dedication and cutting edge help. Without you TekDope wouldn't the success it is now. So big kudos to you guys.

Andrew, congrats! We've been in touch together for Baker related project and i would be more than happy to help you bringing live the vision we had.

Thanks to all of you.

**Comment by MrKistic** [comment]
Makes sense @folletto. A massive thanks to you, @Simbul & @Xm4s for all your work so far and all the best for the future :)

**Comment by anjimi** [comment]
Big thanks for all your work on such a remarkable product! I don't know how I would have got started with our publication without it/you. As others have mentioned the fantastic support here has been as invaluable as the Baker product itself. Congratulations Andrew!

**Comment by folletto** [comment]
@tekdope Thanks! That's great to hear already active support with Andrew. :)

@anjimi Thanks for the kind words. :)

**Comment by nicholasmartin** [comment]
The Baker team ROCKS! What you guys have done is open the door for independent publishers and others that want to support independent publishers. I'm still amazed that this is in fact an open source project and I think you guys have all done an INCREDIBLE job! 

Super excited on Andrews behalf and can't wait to see Baker shift gears!

**Comment by dkamdar** [comment]
Thats awesome news ... We are using both Baker and Magrocket to publish for one of our clients and the support and experience from both the teams has been fantastic! Hope the platform evolves to greater heights. Its an awesome combination! :)

**Comment by folletto** [comment]
@lifestylenetworker Thanks. It makes us really happy to read that. :)

@dkamdar That's the plan! Please give Andrew full support on that, and I'm sure that Baker and Baker's community will grow to even greater heights :)

**Comment by nin9creative** [comment]
@dkamdar That's the plan :)

**Comment by mtamony** [comment]
What the heck happened? This project seems to have died.

**Comment by Barney2324** [comment]
It seems to have slowed down to a tiny little crawl. The app ui is in need a of a complefe refresh. There are a tonne of features people are waiting for... Including free issue/coupon support and lots more. They did a survey and since then, the only advances are with the android team. I seriously hope these guys are working on a major release because its a bit of a disappointment at the moment.

**Comment by akeilox** [comment]
+1 for the coupon support. It was discussed in numerous occasions to incorporate login functionality to enable download of issues and it will be great if a simple implementation of this can be shared; even mentioning which section/code of the default back-end needs to be edited to accomodate this function that can be wired to info.html login form - would be adequate for most to get started.

**Comment by Simbul** [comment]
Hey guys,

As you know the project has moved on to a new home so there's no point in discussing it on this issue board: it's not monitored anymore :wink: 

Here's the link to the current project: https://github.com/bakerframework/baker. You'll find more responsive ears down there :smiley:
