### ISSUE TITLE
The Tech Chronicles is available in Newsstand

### ISSUE THREAD

**Issue by wwarder** [Simbul/baker#1217]
Hello, guys!

Just want to say thank you for your great work. The first issue of The Tech Chronicles is now available and there was no problem with a iTunes moderation. Baker is really outstanding framework and I'm sure it will get even better with a new project lead.

A couple words about The Tech Chronicles. It's a free magazine that serving up a selection of hand-picked articles and blog posts from all around the Web. I'm trying to focus on unique and inspiring opinions evaluating what is happening around us. 

https://itunes.apple.com/en/app/the-tech-chronicles/id599325388?mt=8

**Comment by folletto** [comment]
Hello there! 

The Baker project **moved**, this issue tracker isn't used anymore. You might want to re-post on the new board here: https://github.com/BakerFramework/baker/issues

Thanks! :D

_(That's a really awesome magazine, btw! :D)_
