### ISSUE TITLE
Specifically, the current issue is not available after subscription purchase. BAKER

### ISSUE THREAD

**Issue by diegofelipeer** [Simbul/baker#1218]
Hi guys

I downloaded Baker Framework 4.2 for IOS 7 but the app was rejected. The reason is "Specifically, the current issue is not available after subscription purchase". I don't know why this is happening. Anyone can help me?? Issue#1146 has no the solution. :(

**Comment by nin9creative** [comment]
What are you using for a backend server framework?

Andrew

**Comment by diegofelipeer** [comment]
I added the issues and in-app purchases directly to the iTunes Connect account. Should I use one backend server as Magrocket? Sorry, first time with Baker Framework. And thanks for answer BTW

**Comment by tekdope** [comment]
I invite you to re-read the wiki, it should answer to most of your questions. :)

There are two ways to use baker: 
- Standalone publication
- Newsstand publication

Seems that you want to use Newsstand to distribute free or paid issues.
The newsstand mode requires a backend server, there are some listed on baker website.
Your app won't work without the appropriate backend in place.

Hope this helps

**Comment by folletto** [comment]
Hello there! 

The Baker project **moved**, this issue tracker isn't used anymore. You might want to re-post on the new board here: https://github.com/BakerFramework/baker/issues

Thanks! :D

_(In the meantime, try the hints above :D)_
