### ISSUE TITLE
Pages are still able to be swiped up and down.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1219]
The baker 4.2 the app its great but when you are reading a magazine you can swipe left and right (normal) but you can still go up and down, now nothing happens when this is done, but is a bit disconcerting. Any way to fix it? or maybe another update will come ?

**Comment by nin9creative** [comment]
Can you please log the issue on the new github repo for the project?

http://github.com/bakerframework/baker/issues

**Comment by airterjun** [comment]
Hi  nin9creative,

I need some help for -baker-vertical-pagination. :)

So, I just newbie and I try building some APPS using baker framework 4.2, and in book.json I set -baker-vertical-pagination to TRUE and the page doing good and working like what I want, but there is one think make me not happy with that, so I try to add some navigation panel ( menu to jump to others page ) on top and social sharing button on bottom of page at the HTML file and I set the position to fixed on CSS, now when I try to clicked on each menu the page not goes to the right page, example : if I clicked on top navigation or click on each link navigation then the page goes to the previous page or goes to up, also when I try to click on social button on bottom the page will scroll to the next page or goes to down not goes to right url.

Can you help me with this??

Sorry about my bad English.

Thanks :)

**Comment by Simbul** [comment]
Hi,

Baker has moved to a different repo.
This tracker is open for consultation only: you should post your request in the new issue tracker here:
https://github.com/bakerframework/baker/issues

Thanks
