### ISSUE TITLE
Baker Cloud Console without Newsstand??

### ISSUE THREAD

**Issue by viDU85** [Simbul/baker#1220]
Hello, I want to use baker + Baker Cloud Console without the Newsstand, but if I disable the boolean "Application presents content in Newsstand" I can't download free Issues. Do you know how to fix it? 
thanks in advance.

**Comment by folletto** [comment]
Hello there. :)

I think you have followed an old link. Baker's project is now at a different page and this issue board is still open just for reference. 

You can ask your question here:
https://github.com/BakerFramework/baker/issues
