### ISSUE TITLE
Rejected: Subscription, latest issue remains locked. How?!

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#1222]
Hello there!

I'm so close to giving up... :-(
My application (new version) was rejected several times by Apple.
The last time, I have edited all the settings just like my other (1st) approved application.
But the Apple says:

**After the auto-renewable subscription is purchased, the latest issue remains locked and must be purchased with non-consumable.**

I'm wondering **HOW** could it be?!!
Where I am doing wrong?

Also they said: **Application State is Rejected, a new binary will be required**.
So, it means that (maybe) something is wrong within the application itself (configs, etc.), not the iTunes settings...

_However, in the iTunes, I still have my Auto-Renewable subscription and Non-Consumable purchase (new issue) in the "Waiting for Review" status.
But I think this is not a problem - I could test and "see" this issue in my test environment._

Please, help me.
I cannot submit my application during the whole month! :-(

**Comment by folletto** [comment]
Hello there. :)

Thanks for getting in touch. 
However, this board isn't active anymore and is kept open as an historical archive. Baker moved to a different space, you can find the new project home here:
https://github.com/BakerFramework/baker/issues
