### ISSUE TITLE
Downloading Book Error

### ISSUE THREAD

**Issue by InquirerMegamobileInc** [Simbul/baker#1223]
I am begginer to making books in Baker, I try to create a book in a webserver but theres an error in zipping the file, 

this is the the shelf.json

[{"name":"Lasallian","title":"Lasallian","info":"The Lasallian","date":"2013-12-16 10:10:10","cover":"http://apps.txtchum.com/cms/icon/102.png","keyword":"lasalle, magazine, digital","url":"http://apps.txtchum.com/cms/hpub/ios-Lasallian-Lasallian.hpub"}]

but when i try the book in a standalone app, the book Lasallian is ok. but when in newsstand app it have an error. 

![untitled](https://f.cloud.github.com/assets/4569043/1876801/3a99e7a0-7918-11e3-86eb-88582d955129.jpg)

**Comment by folletto** [comment]
Hello there! :)

I'm sorry but this issue tracker is the old one and isn't in use anymore. :)
Please post on the new one: https://github.com/BakerFramework/baker/issues
