### ISSUE TITLE
Scrolling pages shows file names while it is loading.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1224]
I am using an application called Hype, if you don't know what this is it makes dynamic html5 pages. I then can make an html5 folder with my page that i made and add it to my magazine. The problem is that when i use these hype pages during the loading time of the page you see in grey the file name. EX. page004.html. This is ugly and only occurs with hype made pages. Do you know of a way to fix it? Also the hype file comes with an html page and a folder with more files needed for that page.

**Comment by folletto** [comment]
Hello!

Baker has moved home! :)
This tracker is open for consultation only, you should do your request in the new issue tracker here:
https://github.com/BakerFramework/baker/issues

All the best! :)

**Comment by codegeek511** [comment]
Thank you.
