### ISSUE TITLE
Tap area position 

### ISSUE THREAD

**Issue by airterjun** [Simbul/baker#1226]
Hi there,

Can anybody help me to setup the upTapArea position Y move 40px down and downTapArea position Y move 40px up??? I'm not familiar with object-C code.

Thanks All :)

**Comment by Simbul** [comment]
Hi,

Baker has moved to a different repo.
This tracker is open for consultation only: you should post your request in the new issue tracker here:
https://github.com/bakerframework/baker/issues

Thanks
