### ISSUE TITLE
iPhone 5 Optimization Requirement

### ISSUE THREAD

**Issue by benjamincano** [Simbul/baker#1227]
I downloaded the latest version to replace an old newsstand and I got the "iPhone 5 Optimization Requirement" error I tried the fix mentioned here but I still got the error, I was wondering if anyone also experienced this?

iPhone 5 Optimization Requirement - Your binary is not optimized for iPhone 5. New iPhone apps and app updates submitted targeting iOS 6 and above must support the 4-inch display on iPhone 5 and must include a launch image with the -568h size modifier immediately following the portion of the launch image's filename. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the iOS Human Interface Guidelines and iOS App Programming Guide.

**Comment by folletto** [comment]
Hello there. This issue tracker is closed and kept available just for reference :)

Please post your issue adding more details about **what you did** and where the error appears on the active board, here:
https://github.com/BakerFramework/baker/issues

**Comment by benjamincano** [comment]
Sorry, got it :)
