### ISSUE TITLE
Different content for portrait / landscape orientation.

### ISSUE THREAD

**Issue by pr3drag** [Simbul/baker#1228]
Hi, I'm trying to set up a publication with Baker for iPad. I'm facing an issue: The content I'm preparing has different html pages for portrait and landscape orientations. That means I have pages like 1.html, 1-landscape.html, 2.html, 2-landscape.html and so on...

Is there a way to make it load the right content depending on the device orientation?

Thanks

**Comment by folletto** [comment]
Hello there!

This issue tracker is available just for historical reasons, to participate and ask questions please refer to the new project home, here:
https://github.com/BakerFramework/baker/issues

Thanks! :)
