### ISSUE TITLE
Subscription Button Showing Product ID Instead of Display Name

### ISSUE THREAD

**Issue by ausiuming** [Simbul/baker#1229]
![device](https://f.cloud.github.com/assets/6687702/2177115/803444f6-95f9-11e3-9132-883b81a19e19.jpg)
![itune_connect](https://f.cloud.github.com/assets/6687702/2177116/8045bbe6-95f9-11e3-8b99-891cd1aac4de.jpg)
![xcode](https://f.cloud.github.com/assets/6687702/2177117/80481c60-95f9-11e3-96be-3068329a9097.jpg)

Dear Baker Support,

I have followed the tutorials to setup a Newstand app. It works in the testing device and can purchase in Sandbox Environment. But the Product ID is shown in the subscription button instead of the Display Name. The app is in Traditional Chinese, could this a problem related to localization settings? Screens of the testing device, iTune Connect and Xcode attached.

Daniel

**Comment by fturner19** [comment]
This is the original Baker Framework repository by Davide Casali, Marco Colombo and Alessandro Morandi. Note that this repo is not maintained anymore.

The new official fork can be found at https://github.com/bakerframework/baker/.
