### ISSUE TITLE
Javascript Load from Laker doesn't work in index.html

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#123]
It seems that the js-loading is too slow including a file via js (I use that a lot in Laker). Therefore the height of the index.html isn't calculated properly (in my cases it were 1 px in height or so...). Is there a way to check the height AFTER the index.html is loaded? 

Or maybe we could define the height in the JSON-File? (But that automatic-height-thing would be extremly cool! ;)

thanks!
florian

**Comment by folletto** [comment]
Couldn't you just specify the height of the page in CSS? :)

**Comment by ffranke** [comment]
that's a clever idea, folletto! ;D

**Comment by folletto** [comment]
May I mark this as closed? :)

**Comment by ffranke** [comment]
yeah
