### ISSUE TITLE
I don't know how to locate my PURCHASE_CONFIRMATION_URL, PURCHASES_URL and POST_APNS_TOKEN_URL

### ISSUE THREAD

**Issue by tomibady** [Simbul/baker#1230]
Please kindly assist me with these, I'm almost done with it, just these stuff. Thanks for the support.

**Comment by folletto** [comment]
Hello there. :)

Thanks for posting but... this tracker is not active anymore and it's open just for historical reasons. Please post on the new tracker, here:
https://github.com/BakerFramework/baker/issues

Thanks! :)
