### ISSUE TITLE
Can't Download hpub

### ISSUE THREAD

**Issue by JosephCastro** [Simbul/baker#1231]
Hi.

I configured the application (following the tutorial), then I run it in the simulator and download the issue, but when I try it in the iPad (iPad 4, iOS 7.0.4), I can't download the issue.

I get this error: 

```
  Connection error when trying to download <url in debug enviroment> : Cannot connect to iTunes Store
```

Can you help me ?

**Comment by folletto** [comment]
Hello there!

Unfortunately this board has moved and isn't used anymore and is kept available for historical reasons. Please post on the active board here, adding all the details about your Baker configuration:
https://github.com/BakerFramework/baker/issues

Thanks! :)

**Comment by JosephCastro** [comment]
thanks!
