### ISSUE TITLE
transactionReceipt is deprecated? How to fix.

### ISSUE THREAD

**Issue by jervenstar** [Simbul/baker#1233]
I am almost ready to publish my binary. I do have 11 Issues - i wonder if those are fixable? I do not understand how those problems happened. Any advice would be helpful.

![screenshot 2014-03-27 15 54 40](https://cloud.githubusercontent.com/assets/4260237/2544618/3525893c-b603-11e3-81d0-36ef5afe050b.png)

**Comment by folletto** [comment]
Hello. This issue tracker isn't used anymore and is here just as a public archive. Please post on the active Baker issue tracker here:
https://github.com/BakerFramework/baker/issues

Thanks. :D
