### ISSUE TITLE
How to Make a notification

### ISSUE THREAD

**Issue by kukusumaa** [Simbul/baker#1236]
Hi, im new in baker and ios app.
Could somebody tell me step by step how to make a notification with Baker on ios app?
I need it so much.
thank you

**Comment by Krustin** [comment]
try this https://developer.apple.com/notifications/ and google for tutorials
You can find nice tutorials for pushnotifications
http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

**Comment by Simbul** [comment]
Hi @ayukusuma. This is not the current tracker for the Baker project anymore. The right place is https://github.com/bakerframework/baker/issues (where you already posted, as far as I can see) :wink:
