### ISSUE TITLE
App Binary Rejected, reasons: Abandoned Batch

### ISSUE THREAD

**Issue by abe2014** [Simbul/baker#1238]
Hello I have recently submitted an App to Apple but got rejected.

Reasons

Abandoned Batch
We found that while you have submitted In App Purchase products for your app, the In App Purchase functionality is not present in your binary. 

If you would like to utilize In App Purchase in your app, you will need to upload a new binary that incorporates the In App Purchase API to enable users to make a purchase

Once you revise and resubmit your binary, you will also need to resubmit your In App Purchases for review since they are in the state Developer Action Required. For each IAP product submitted, please be sure to edit the detail information or cancel the request to change the detail information for the In App Purchases using iTunes Connect.

I am not sure where to start trouble shooting so maybe someone here could give me some advice.
I felt that the rejected reason is too vague and I couldn't pin point what exactly they are rejecting me for.

Here are some information that might help:
1. I have created, tested(sandbox), and included the In App Products in the app binary upon submission.
2. The app is developed using Unity3D and Prime31 Plugin
3. I am able to retrieve purchased receipts.
4. I also included directions to help navigate in the shop menu.

Regards.

**Comment by folletto** [comment]
Hello there!

This issue board is closed, and available just as an archive, you can write on the new board here:
https://github.com/BakerFramework/baker/issues
