### ISSUE TITLE
iPhone subscriptions will not work.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1239]
So we have setup or app on the iPad and it works fine. We just got an iPhone version on the market but when you try to subscribe the issues are still saying buy, and not download. I personally subscribed and i was sent and email saying i was subscribed. What did we do wrong?

**Comment by folletto** [comment]
Hello there,

Thanks for getting in touch. :)

Please note that this issue tracker is not in use anymore, and kept visible for historic reasons only. 

You can post your question on the new board, here:
https://github.com/BakerFramework/baker/issues

**Comment by codegeek511** [comment]
Oops, thanks
