### ISSUE TITLE
Backgroundcolor loading-page

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#124]
I've seen some issues/questions about the background color of the loading-page, but not a real solution so far.
Is it possible to change the background color to something else other then blackColor and whiteColor?
If so, which color-system can be used (HEX, RGB, etc.)

**Comment by folletto** [comment]
Sure. :)

It's a UIColor: http://developer.apple.com/library/ios/#documentation/uikit/reference/UIColor_Class/Reference/Reference.html

However once book.json will be in place it's going to be very simple and more flexible. :)

**Comment by danielbenjamins** [comment]
Thanks! For now I'll change the UIColor in 'RootViewController.m'.

For my app I changed this rule:
#define SCROLLVIEW_BGCOLOR colorWithRed:0.592 green:0.109 blue:0.121 alpha:1.0f

If you know the RGB-values it's very easy to use your 'own' color, but you have to do some calculations to use this.
Just divide every R/G/B value by 255.

Example:
My RGB-values were: Red 151, Green 28, Blue 31 (dark red).
151 / 255 = 0.592
28 / 255 = 0.109
31 / 255 = 0.121

For those who want to change the color of the spinner/loading-icon, change this rule (also in 'RootViewController.m'):

UIActivityIndicatorView *spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
- UIActivityIndicatorViewStyleGrey = grey spinner (Baker default)
- UIActivityIndicatorViewStyleWhite = white spinner

**Comment by folletto** [comment]
Ok! :)
On our side, this will be solved once the book.json is in place, so I'll close this issue. :)

Thanks! :)
|D
