### ISSUE TITLE
NewsstandKit outside Newsstand

### ISSUE THREAD

**Issue by presende** [Simbul/baker#1240]
Hello,

I'm building an application using Baker. Cause of the user strategy i wanted it to be placed outside newsstand, but I still need the whole functionality of downloading and unziping magazines.

Is there a way to do that? Do I really need to clean all NewsstandKit Framework use?

Thanks!

**Comment by Simbul** [comment]
Hi. The Baker project has moved on from this repo. Please post your question on https://github.com/bakerframework/baker/issues :smile: 

Thanks

**Comment by presende** [comment]
Thanks!
