### ISSUE TITLE
Weird parsing error in xcode project.

### ISSUE THREAD

**Issue by Minimorro** [Simbul/baker#1242]
Hello. Recently I've been trying to use the Baker framework to publish an online magazine, I followed the standalone tutorial step by step, but when I hit build project I get this weird error: "Unknown type name "UIBackgroundFetchResult", and I have no idea how to solve it. Could you help me correct this? Thanks in advance.

**Comment by folletto** [comment]
Hello there!

Thanks for writing us, but unfortunately this issue tracker is not in use anymore and kept live for archive reasons only. I advise you to ask for help on the new board here:
https://github.com/BakerFramework/baker/issues

_(I'd also suggest when you write there to add more details: what are you using, test with a new blank setup, describe the steps to reproduce it and so on)._
