### ISSUE TITLE
Issues not showing on newsstand

### ISSUE THREAD

**Issue by Str4f3r** [Simbul/baker#1243]
Hey there, recently we made a magazine and used baker framework. Followed all the steps on the tutorial and add a free and paid subscription to itunes connect. Changed shelf.json and uploaded to server both 2 magazines (free and paid). Well now we have a problem i can only get one magazine on my newsstand.  If on shelf i have one free magazine then that's the magazine that we will see on newsstand. Passed hours looking at this thing, and  even after adding subscriptions to iTunes (6months and 1year) i still can't get that info on my simulator or iPad. Is it possible this can be a server problem? Anyone else had same issue already? would appreciate some help thanks.

**Comment by Simbul** [comment]
Hi. The project has moved to https://github.com/bakerframework/baker/.
If you post in that project's issue board you may find someone who can help you :smiley:
