### ISSUE TITLE
Termintated due to memory error

### ISSUE THREAD

**Issue by philahern** [Simbul/baker#1244]
I have a hpub with some of the pages having up to 4 image galleries displayed. Each page with galleries has a jquery based carousel to display. This causes Baker to crash saying "Terminated due to memory error" I have tried several different js based carousels and all of them cause the memory crash. Am I doing something wrong? Are there too many image galleries on the page perhaps? Any help would be greatly appreciated.

**Comment by folletto** [comment]
Hello!

Thanks for getting in touch. :)
This issue board is now closed, and let available just as an archive.

Please repost on the active board, adding details about the hardware you're using, Baker version, what library are you using, what HTML and the weight of the images. Post here:
https://github.com/BakerFramework/baker/issues
