### ISSUE TITLE
Copy and paste in the magazine

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1245]
Hi, my boss noticed that you can copy the text and paste it into another application (naturally because we use html to display the content) we were wondering if there was a way to turn this off? Or is there a third party plugin or extension that you know of?

**Comment by Simbul** [comment]
Hi. The project has moved, so you're much better off posting in the new issue board you can find here: https://github.com/bakerframework/baker/issues :)

**Comment by codegeek511** [comment]
Thank you.
