### ISSUE TITLE
Display only downloaded magazine on baker shelf

### ISSUE THREAD

**Issue by rahafiz** [Simbul/baker#1246]
Hello Guys,

I would like to ask, how can i display only downloaded magazine on the baker shelf. Let say, i create 2 viewController and name it viewController A and viewController B. On viewController A it display all the available magazine from server including the magazine before user download and magazine that already been downloaded. On viewController B, it's only display the magazine that i already downloaded on the viewController A. Is it possible this thing to be done on baker framework. I am really appreciate you guys answer. Thank you.

**Comment by Simbul** [comment]
Hello.
Baker's development is not happening in this repo anymore: things have moved over to a fork, so you're probably better off posting in the new issue tracker: https://github.com/bakerframework/baker/issues

Thanks!

**Comment by rahafiz** [comment]
Ok thanks for the info. :)
