### ISSUE TITLE
Error on AppleStore

### ISSUE THREAD

**Issue by lhap** [Simbul/baker#1247]
Reasons
2.23: Apps must follow the iOS Data Storage Guidelines or they will be rejected
2.23

We found that your app does not follow the iOS Data Storage Guidelines, which is required per the App Store Review Guidelines
.

In particular, we found that on launch and/or content download, your app stores 59.1MB. To check how much data your app is storing:
- Install and launch your app
- Go to Settings > iCloud > Storage & Backup > Manage Storage 
- If necessary, tap "Show all apps" 
- Check your app's storage

The iOS Data Storage Guidelines indicate that only content that the user creates using your app, e.g., documents, new files, edits, etc., should be backed up by iCloud. 

Temporary files used by your app should only be stored in the /tmp directory; please remember to delete the files stored in this location when the user exits the app.

Data that can be recreated but must persist for proper functioning of your app - or because customers expect it to be available for offline use - should be marked with the "do not back up" attribute. For NSURL objects, add the NSURLIsExcludedFromBackupKey attribute to prevent the corresponding file from being backed up. For CFURLRef objects, use the corresponding kCFURLIsExcludedFromBackupKey attribute. 

Well, I did what it was, even more so I could not upload, I saw a tutorial ( https://github.com/Simbul/baker/issues/233 ). And also not solved, can you help me?

**Comment by Simbul** [comment]
Hi,
this repo is not maintained anymore: you should check out the official Baker fork at https://github.com/bakerframework/baker/issues ;)
