### ISSUE TITLE
Working with big pdf's

### ISSUE THREAD

**Issue by serkanerkan** [Simbul/baker#1248]
I have 300 mb high quality pdf's. Download process is so slow. i reduced pdf sizes but still slow. Is there a way to fix it? im waiting 10-12 minutes with 50 mb hpub file.

**Comment by folletto** [comment]
Hello!

Thanks for writing, but unfortunately this board is not in use anymore and kept open for historical reasons only. Please refer to the new Baker issue board here: https://github.com/bakerframework/baker/issues
