### ISSUE TITLE
Auto renewable subscription fail in ITC

### ISSUE THREAD

**Issue by serkanerkan** [Simbul/baker#1249]
Hello,

i know here are so many documents subscription plans. But i have a different problem.. 

Our mag is publishing for one year. ITC says "you must a subscription plan."  What can i do? I have set the one year subscription plan, and price tier 3. but they have set the status "developer action needed"

i dont know what will i do.  My another question is. ITC wants a screenshot, in autorenewable subscription plan. But our new mag did not publish yet. What can i upload there?

**Comment by Simbul** [comment]
Hi,

This issue board is not maintained anymore, as the project has moved. Have a look here: https://github.com/bakerframework/baker/issues :wink:
