### ISSUE TITLE
Reload page

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#125]
Is it possible to reload the current page with a link or button? At the moment nothing happens when I'm trying to link the current page I'm on. It's similar like <a href="https://github.com/Simbul/baker/issues/64">this issue</a>, but I'm not using anchors.

Example:

I implemented a little JS-game in one of my pages and I'd like the possibility a user can reload the page to play again.

On page 058.html I'd like to use this code: "a href="058.html"" to reload the page, but that's not working :)

**Comment by folletto** [comment]
Uhm that's strange indeed, we need to sort it out.

In the meantime, does the javascript alternative work?
javascript:location.reload(true)?

**Comment by danielbenjamins** [comment]
Just tried and it works in Safari (desktop) but not in Baker.

**Comment by folletto** [comment]
Argh. Ok, thanks. :)

**Comment by danielbenjamins** [comment]
In Laker I used to use a hack/workaround/trick which worked fine. In Baker this trick only works just once.

056.html - add a button/link on this page which points to 057.html
057.html - add this meta-tag to this document: "meta http-equiv="refresh" content="0;url=056.html""

Maybe this helps :)

**Comment by danielbenjamins** [comment]
Another suggestion: shake to reload?

I'm definitely not a coder, but maybe this would be easy to integrate so we can switch it on or off in XCode?

Just Googled a bit:
- http://www.iphonedevsdk.com/forum/iphone-sdk-development/4381-iphone-shaking-code.html
- http://stackoverflow.com/questions/150446/how-do-i-detect-when-someone-shakes-an-iphone

Also a very cool and interactive feature :)

**Comment by danielbenjamins** [comment]
A little update:

The trick/hack I mentioned above is now working after a minor change.
Just make sure the refresh-page isn't right next after the actual page.

Example:
Content on 056.html & meta-tag (refresh) on 057.html: doesn't work.
Content on 056.html & meta-tag (refresh) on 099.html: does work

Still not the most neat solution, but it works for now...

**Comment by folletto** [comment]
Ok, I hope however to avoid that workaround soon hehehe :)

I can also guess why that happens, since we have some caching in place, that might be it. :)

**Comment by danielbenjamins** [comment]
Yeah, it's really ugly but it works for now... :)

**Comment by danielbenjamins** [comment]
Any news on this yet? I'm working on an app which has an HTML5 drawing object (color book) included and I'd like to insert a button which reloads the page so you can make a new drawing :)

**Comment by folletto** [comment]
Nope, sorry. Xmas is working on this and is taking care of the caching issue first. :)

**Comment by Xm4s** [comment]
With the commit bd24c19270cbe53923c7585fde24fda355a188f1, since I review the handling of loading request, I fix this up too. Now a click on the link page_01.html on the page_01 should correctly reload the page :)
