### ISSUE TITLE
Baker 4.3 padding on Cells

### ISSUE THREAD

**Issue by AlmondFace** [Simbul/baker#1250]
Hi,

I was previously working with 4.2 of Baker and had managed to customise the collection view controller on iPhone and iPad but adding some methods such as

-(CGFloat)cellLineSpacing;
-(CGFloat)cellItemSpacing;
-(UIEdgeInsets)cellEdgeInsets;

. Ive just switched over to the new version 4.3 and have to work this out again as the layout method has changed for the grid.

I can see this in viewDidLoad accounts for the first 2 methods above:
        self.layout.minimumInteritemSpacing = 0;
        self.layout.minimumLineSpacing      = 0;

But im trying to work out how to add a padding of 40 on the sides of the cells (cellEdgeInsets).

On the image below, the left image is what i currently have with the new version of Baker, on the right is the layout I achieved on my previous baker project and that which i am trying to workout in the new version.

Any help on how to do this would be amazing,

thanks

![layout](https://cloud.githubusercontent.com/assets/9403556/4945999/6b4c4a12-660e-11e4-9e7c-9e3283a8d400.jpg)

**Comment by folletto** [comment]
Hello there,

This board is closed and kept available for historical reasons only, since the project moved to a better location with a new team. You can post any request you have here: https://github.com/bakerframework/baker/issues

Cheers!
