### ISSUE TITLE
Attempting to badge the application icon but haven't received permission from the user to badge the application

### ISSUE THREAD

**Issue by thegirlinorange** [Simbul/baker#1251]
Hi,

I'm getting this error - "Attempting to badge the application icon but haven't received permission from the user to badge the application". I'm using the latest version of Baker and XCode.
Does anyone know how to sort this out?

Many thanks!

**Comment by folletto** [comment]
Hello there! 

Thanks for contacting us but... this board isn't in use anymore and it's kept running just for historical reasons. You can write to the active BakerFramework board here:
https://github.com/bakerframework/baker/issues

Thanks! :)
