### ISSUE TITLE
Baker Standalone App and In-App Purchase

### ISSUE THREAD

**Issue by LuxViz** [Simbul/baker#1252]
QUESTION
Has anyone created a standalone Baker app and also implemented in-app purchases? Would you be willing to provide some paid Skype consulting to help us understand how in-app purchases work with standalone apps?

BACKGROUND
We have an approved standalone iPad app called Bali's Finest Villas which was designed to "promote indulgent luxury travel" to Bali by showcasing some of the most exclusive villas here. This app has been developed using the Baker Framework with HTML5 and Javascript, but also with some additional functional components in Objective C.

We're almost finished with some major revisions to the content organization, functionality, and layout for the app. The next release will support all iOS devices, and we will also publish an Android version that will also support both tablets and phones.

Our initial plan has been to release a free SD (standard-definition) version, and then start charging for an HD standalone version of the app. We intended to release new "issues" of the app about every 3 months with a new selection of 10 luxury villas. 

We're now reconsidering that strategy and are wondering about keeping one version of the app, and making the SD version of the Premiere Issue free, but then the HD and SD versions of all other issues would be offered as in-app purchases.

However, we would really like help in understanding any architectural changes we need to make to our existing app, as well as receiving knowledgable consulting about the wisdom of this new strategy.

Is there anyone with experience with a standalone Baker app that supports in-app purchases who might be willing to help us out with some paid Skype consulting?

Thanks,
Rick

LuxViz
https://itunes.apple.com/us/artist/luxviz/id796339928#

Bali's Finest Villas - SD Version (for iPads with normal displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-sd-english/id879332125?ls=1&mt=8

Bali's Finest Villas - HD Version (for iPads with the retina displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-hd-english/id880005823?ls=1&mt=8

![01 cover](https://cloud.githubusercontent.com/assets/9841038/5103382/5c8e56f6-7012-11e4-9fe7-8066608a1c51.jpg)
![02 villa sungai](https://cloud.githubusercontent.com/assets/9841038/5103378/5ab62958-7012-11e4-82cc-189847ca917f.jpg)
![03 sanctuary bali](https://cloud.githubusercontent.com/assets/9841038/5103379/5afd7538-7012-11e4-854f-558f01f671ba.jpg)
![04 sound of the sea](https://cloud.githubusercontent.com/assets/9841038/5103380/5b43f7ba-7012-11e4-8676-bd5ae93e2412.jpg)
![05 bali article](https://cloud.githubusercontent.com/assets/9841038/5103381/5bb0928a-7012-11e4-95e4-d5132dafabfc.jpg)

**Comment by folletto** [comment]
Hi there!

Thanks for getting in touch. Unfortunately this issue board is available for historical reasons only, and it's not in use anymore. Please post on the active one here: https://github.com/bakerframework/baker/issues ;)

Cheers!

**Comment by LuxViz** [comment]
Hi Davide.

Thanks for the clarification! I will repost on the active board....

Rick

---

PT LuxViz - social media for luxury lifestyles
Jalan Raya Canggu 103
Canggu, Bali Indonesia 80362

+62 (0)878 610 33533
http://www.luxviz.com

**Comment by LuxViz** [comment]
Hi Guys,

I’ve written to numerous email addresses of the Baker “team” members before, and yet never received a response… so I hope someone reads and responds to this email. 

INTRODUCTION
My name is Rick Carmichael, and after working for Apple in Cupertino for about 10 years, I took a layoff package, worked freelance as a web designer and photographer for a while in Santa Cruz, CA, and then in 2007 I "ran away" to Bali to form LuxViz. My company develops mobile apps, provides very skilled architectural photography, 360˚ interactive panorama tours, and creates a variety of social media to be used in promoting indulgent luxury travel. In the 7 years I've been living in Bali, I've shot - and professionally edited - about 120,000 photos, mostly of Bali's finest villas.

We're still a VERY small firm with clients in the luxury travel and lifestyle market. Our first app was Bali's Finest Villas, which we plan to republish as new (standalone) editions every 3 months. Each issue of Bali's Finest Villas features 10 of the most gorgeous and luxurious villas in Bali, along with close to 500 stunning architectural photos, dozens of 360˚panorama tours, hundreds of pages of villa content, and numerous articles about the people and the culture of The World's Best Island.

In the one year since we started working with Baker, we have published a total of 26 standalone apps: 13 iOS apps and 13 Android apps. Again, these are all standalone apps, and NOT magazines or books. 

The next app we’re working on now is called Bali’s Boutique Villas and it will feature the more “mid-range” villas in Bali. BBV will also be a quarterly publication, with each issue featuring 20 villas, along with information about the people and culture of Bali.

iOS STANDALONE APPS DEVELOPED USING BAKER
Here is a list of the iOS apps we’ve created in the last one-year period.

Bali's Finest Villas - SD Version (for iPads with normal displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-sd-english/id879332125?ls=1&mt=8 https://itunes.apple.com/us/app/balis-finest-villas-1-sd-english/id879332125?ls=1&mt=8

Bali's Finest Villas - HD Version (for iPads with the retina displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-hd-english/id880005823?ls=1&mt=8 https://itunes.apple.com/us/app/balis-finest-villas-1-hd-english/id880005823?ls=1&mt=8

The View at THE edge
https://itunes.apple.com/us/app/the-view-at-the-edge/id888174007?ls=1&mt=8 https://itunes.apple.com/us/app/the-view-at-the-edge/id888174007?ls=1&mt=8

Villa Sungai
https://itunes.apple.com/us/app/villa-sungai/id888575675?ls=1&mt=8 https://itunes.apple.com/us/app/villa-sungai/id888575675?ls=1&mt=8

Jagaditha
https://itunes.apple.com/us/app/jagaditha/id888597640?ls=1&mt=8 https://itunes.apple.com/us/app/jagaditha/id888597640?ls=1&mt=8

The Sanctuary Bali
https://itunes.apple.com/us/app/the-sanctuary-bali/id888637329?ls=1&mt=8 https://itunes.apple.com/us/app/the-sanctuary-bali/id888637329?ls=1&mt=8

Villa Arika
https://itunes.apple.com/us/app/villa-arika/id888654168?ls=1&mt=8 https://itunes.apple.com/us/app/villa-arika/id888654168?ls=1&mt=8

Villa Sound of the Sea
https://itunes.apple.com/us/app/villa-sound-of-the-sea/id888979485?ls=1&mt=8 https://itunes.apple.com/us/app/villa-sound-of-the-sea/id888979485?ls=1&mt=8

Jeeva Saba
https://itunes.apple.com/us/app/jeeva-saba/id888993802?ls=1&mt=8 https://itunes.apple.com/us/app/jeeva-saba/id888993802?ls=1&mt=8

Villa Shambala
https://itunes.apple.com/us/app/villa-shambala/id889006817?ls=1&mt=8 https://itunes.apple.com/us/app/villa-shambala/id889006817?ls=1&mt=8

Villa Taman Ahimsa
https://itunes.apple.com/us/app/villa-taman-ahimsa/id889015098?ls=1&mt=8 https://itunes.apple.com/us/app/villa-taman-ahimsa/id889015098?ls=1&mt=8

Villa Ombak Laut
https://itunes.apple.com/us/app/villa-ombak-laut/id889019237?ls=1&mt=8 https://itunes.apple.com/us/app/villa-ombak-laut/id889019237?ls=1&mt=8

Qunci Villas - Lombok
https://itunes.apple.com/us/app/qunci-villas-lombok/id899099183?ls=1&mt=8 https://itunes.apple.com/us/app/qunci-villas-lombok/id899099183?ls=1&mt=8

For the Qunci Villas app, we used Baker again to develop a visually stunning and totally engaging app for this stunning hotel property in Lombok Indonesia. The app is a collection of about 13 linked, 360˚ panorama tours for showing off that property. And... the opening screen in the app is an aerial 360˚ of the property shot out over the ocean from a remote-controlled, drone octocopter.

ANDROID STANDALONE APPS DEVELOPED USING BAKER
And then here is a list of the Android apps we’ve created in the last one-year period - actually within the last 2 months.

Bali's Finest Villas - SD Version (standard-definition for normal displays)
https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillasSD1 https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillasSD1

Bali's Finest Villas - HD Version (high-definition for retina displays)
https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillas1HD https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillas1HD

The View at THE edge
https://play.google.com/store/apps/details?id=com.luxviz.theView https://play.google.com/store/apps/details?id=com.luxviz.theView

Villa Sungai
https://play.google.com/store/apps/details?id=com.luxviz.villaSungai https://play.google.com/store/apps/details?id=com.luxviz.villaSungai

Jagaditha
https://play.google.com/store/apps/details?id=com.luxviz.jagaditha https://play.google.com/store/apps/details?id=com.luxviz.jagaditha

The Sanctuary Bali
https://play.google.com/store/apps/details?id=com.luxviz.sanctuaryBali https://play.google.com/store/apps/details?id=com.luxviz.sanctuaryBali

Villa Arika
https://play.google.com/store/apps/details?id=com.luxviz.villaArika https://play.google.com/store/apps/details?id=com.luxviz.villaArika

Villa Sound of the Sea
https://play.google.com/store/apps/details?id=com.luxviz.soundOfTheSea https://play.google.com/store/apps/details?id=com.luxviz.soundOfTheSea

Jeeva Saba
https://play.google.com/store/apps/details?id=com.luxviz.jeevaSaba https://play.google.com/store/apps/details?id=com.luxviz.jeevaSaba

Villa Shambala
https://play.google.com/store/apps/details?id=com.luxviz.villaShambala https://play.google.com/store/apps/details?id=com.luxviz.villaShambala

Villa Taman Ahimsa
https://play.google.com/store/apps/details?id=com.luxviz.tamanAhimsa https://play.google.com/store/apps/details?id=com.luxviz.tamanAhimsa

Villa Ombak Laut
https://play.google.com/store/apps/details?id=com.luxviz.ombakLaut https://play.google.com/store/apps/details?id=com.luxviz.ombakLaut

STANDALONE APP DEVELOPMENT MARKET?
We initially used the Adobe DPS system for developing Bali’s Finest Villas. However, once we completed the prototype and began looking at the implementation issues, we realized that our business model simply would not support paying the hefty download fees they were wanting to charge developers. So, we had to look for other development platforms. Which is how we came to find out about Baker.

We initially were using Baker to design a Newsstand app, but because our content is totally focused on promoting bookings in some of Bali's finest luxury villas, Apple wouldn't approve as a Newsstand app. So... we basically flipped the switch in Xcode from Newsstand to Standalone, rebuilt and resubmitted the app, and now we're up to THIRTEEN apps approved on the iTunes App Store and the same 13 also published using the beta versions of Baker for Android on the Google Play store. All 26 are standalone apps.

I think you guys might be missing out on an enormous chunk of the app development market because your verbiage and examples seem to be totally focused on digital (newsstand) publications.

The top headline on your website states: "Baker is a HTML5 based digital publication framework for publishing interactive books & magazines on iPad & iPhone using simply open web standards."

(To be fair, you DO mention both Newsstand and Standalone under Item 3 - Publish. But, the majority of your examples and verbiage on the site are geared towards magazine-like apps.)

Just my 2 cent's worth! 

GETTING LISTED AS A BAKER DEVELOPER?
We'd love to be included in your list of developers on your website.

We're using a combination of the following tools in producing our apps:

HTML 5
CSS
JQuery/Javascript
Objective C
Xcode
Java
Android Studio
and, of course, the Baker Framework!

My programmer has done a VERY SIGNIFICANT amount of custom coding to get our Android apps functioning as closely as possible to the iOS Baker apps. We would be happy to provide source code to you guys if you’re interested in seeing what we did.

Thank you from the bottom of my heart for allowing me to carve out a brand new service niche for my small company in Bali!

Best wishes,
Rick

---

PT LuxViz - social media for luxury lifestyles
Jalan Raya Canggu 103
Canggu, Bali Indonesia 80362

+62 (0)878 610 33533
http://www.luxviz.com

**Comment by folletto** [comment]
That's amazing! :D

However this issue board isn't used anymore, you'd be better off posting on https://github.com/bakerframework/baker/issues :)

**Comment by LuxViz** [comment]
Hi Davide,

Is your reply a response to my lengthy email about Bali’s Finest Villas and our other apps? (Your suggestion to post on the GitHub board has me confused.)

I’ve been wanting to provide the feedback more to the Baker team, and I was think the board is a more “general” public venue???

Thanks,
Rick

---

PT LuxViz - social media for luxury lifestyles
Jalan Raya Canggu 103
Canggu, Bali Indonesia 80362

+62 (0)878 610 33533
http://www.luxviz.com

**Comment by folletto** [comment]
Yes, the "awesome" is about the work you did.  :) 

The suggestion to post on the other board it's because this board isn't used anymore, but THAT board is instead the right place. :)

**Comment by LuxViz** [comment]
got it - will post there - and thanks for your part in the awesome framework!

---

PT LuxViz - social media for luxury lifestyles
Jalan Raya Canggu 103
Canggu, Bali Indonesia 80362

+62 (0)878 610 33533
http://www.luxviz.com

**Comment by folletto** [comment]
It's truly my pleasure :)
