### ISSUE TITLE
Issues with HTML images on Baker framework on iPad

### ISSUE THREAD

**Issue by omegah3** [Simbul/baker#1257]
All the HTML images on a Newsstand Magazine app i made in Baker Framework are showing up very dark on iOS devices, but when viewed on the regular browser they show up normal.

What might be the issue, please help.

**Comment by folletto** [comment]
Hello!

This issue board is closed, kept available for historical reasons only. 

If you have a question please ask on the active issue board:
https://github.com/bakerframework/baker/issues

Thanks!
