### ISSUE TITLE
Scrolling model: Vertical (view article content) Horizontal (change article)

### ISSUE THREAD

**Issue by proecorp** [Simbul/baker#1258]
Hello, I need help setting up the navigation in the magazine. I would like the navigation in the article content to be vertical and to change article to be landscape/horizontal. Is it possible? Is there any example how to do it that anybody can show me?

**Comment by folletto** [comment]
Hello!

I'm sorry but this issue board isn't active anymore, we're keeping it alive for historical reasons only.

Please check the active issue board here:
https://github.com/bakerframework/baker/issues
