### ISSUE TITLE
Side panel links do not react on iPad

### ISSUE THREAD

**Issue by anitannesh** [Simbul/baker#1259]
Hi all,

The e-book I have designed has side panels to display extra information (see screenshot). 
These panels have links (the icons on the top) to navigate through them, but they do not seem to work on the iPad. When I test them on a browser they work just fine. Any idea what could be happening here?

Thank in advance.

Cheers,

Ana
![img_0557](https://cloud.githubusercontent.com/assets/13909865/9419648/63db5a8c-4855-11e5-947c-b18587183449.PNG)

**Comment by folletto** [comment]
Hello! 

Thanks for getting in touch. However, this is the old issue board that we are keeping live for historical purposes. You should ask your question on the currently active board, here:
https://github.com/bakerframework/baker/issues

**Comment by anitannesh** [comment]
Thank you, I already opened it there.
