### ISSUE TITLE
Migrating from InDesign to Baker Framework

### ISSUE THREAD

**Issue by everton-schumacker-clansoft** [Simbul/baker#1261]
Hi!

First of all, I would like to thank anyone that took the time to read this post, specially those that took the time to help me with any possible answer! 

I am from Brazil and new in the publishing business. I am facing a very complicated situation in my internship and I couldn't find any good solution to efficiently solve it. I already researched extensively all forums about InDesign, but none of the answers seem to be viable to me. 

We published an interactive eBook using InDesign 2014 and Adobe's DPS system, but Adobe changed its licensing policies in 2015, which made impossible to small companies to update and release new apps . The problem is that we would like to divide this whole book into 5 more apps, because it is a complete and extensive book (so we would like to make smaller apps, each one of them covering one chapter of the book). The thing is: we don't want to redo all the content in HTML5, so we are looking for a way of converting InDesign folio into hPub efficiently. In5 does a really good work in this case, but the problem is that it apparently can only convert a single INDD file. Since we have a huge amount of files is this book, it would be very difficult to merge everything into a single file.

I would like to know if any of you guys could please take the time to answer any of this questions, since any of then would solve my situation:
1. Is there any other INDD to HTML5 converter that can converte the whole folio?
2. Is there any way to converte the whole folio into hpub using in5? If not, is there any tool that automatically merges the whole folio into a single .indd file to be used with in5?
3. Is there any way of merging multiple hPubs into a single hPub?
4. Is there any way to build a single app that joins multiple HPUBs into a single interactive eBook?

Again, thank you very much for your attention, help and support!

PS: Sorry for my bad English. As I said, I'm from Brazil and it have been a long time since I wrote a message as long as this one. lol

**Comment by folletto** [comment]
Hello!

I'm sorry but this board is not used anymore (it's just kept alive for historical reasons).

You can check the new board and ask a question there:
https://github.com/bakerframework/baker/issues

**Comment by everton-schumacker-clansoft** [comment]
Thanks
