### ISSUE TITLE
free subsciptions

### ISSUE THREAD

**Issue by petesavva** [Simbul/baker#1262]
May i ask a potentially dumb question?
The Free Subscription model is only implemented to work with apple's requirements correct?
Given that the free mags are still downloaded within the app, the subscribe button does not really accomplish anything.
Am I correct in this assumption?
Thank you for a great product.

**Comment by folletto** [comment]
Hello!

This repository is not in use anymore, please check https://github.com/bakerframework/baker/issues

(P.S.: no question is dumb).
