### ISSUE TITLE
Memory issues with 360.

### ISSUE THREAD

**Issue by Virtualsweden** [Simbul/baker#127]
Hi, I am trying to add 360 images that are HTML5.

When adding one image it works fine, but when adding 2 or more it crashes. Could there be a memory issue?

**Comment by folletto** [comment]
It's very strange, a crash isn't usually related to a memory issue. How are you adding these? Are you using Baker 2.0?

**Comment by Virtualsweden** [comment]
Hi, I am using Baker 2.0 and are adding 2 html pages with 1 panorama each in them.

It works fine i iOS simulator

 I have a testflight setup and if you want you can download the app from there.

It shows the first 360 ok, but when swiping to page 2 it crashes.

**Comment by folletto** [comment]
Uhm but are you using any JS? To debug it we need the simplest page possible that triggers the bug. Seeing the app would be nice, but won't give much informations.

Did you try running Instruments or GDB to try track down the error? Or, what does the stack trace give in the logs?

**Comment by folletto** [comment]
From what you sent us, it seems you are using Pano2VR, that uses HTML5, Canvas and WebGL.

WebGL is a very young technology and I think it might create quite a few issues in our current Baker implementation, but I don't know why exactly why it crashes. It gives me absolutely no error, it just crashes. And yes, it might be some problem in the canvas or WebGL implementation, because it happens without giving me any memory warning (only occasionally).

Btw on my iOS5 beta crashes immediately, even the first page.

**Comment by Virtualsweden** [comment]
Hi,

 Thanks for taking the time to investigate these things.

 I have tried different frameworks and all have the same issue.

 It looks as if krpano crashes more seldom and almost never if
 you stay away from the fullscreen button.

 Will talk to Klaus who has developed the Krpano script.

 If I find anything I will get back to you :-)

 Thanks again.

 //Jonas Carlson

**Comment by folletto** [comment]
Thank you very much. :)

**Comment by kruegerson** [comment]
Hi,
It seems to be a memory issue - Klaus / krpano wrote on this page
http://krpano.com/iphone/#details
"The Mobile Safari has only very limited memory and a very buggy memory handling. Every time when the memory gets too low it simply crashes."

**Comment by Virtualsweden** [comment]
Hi,

I finally found that out, reducing imagesize helped a lot.
:-)
//Jonas

30 aug 2011 kl. 23:43 skrev kruegerson reply@reply.github.com:

**Comment by Virtualsweden** [comment]
It actually didnt help all the way. Is there a way to free memory when loading a new page in UIWebView?

Is something like this possible?
http://blog.techno-barje.fr/post/2010/10/04/UIWebView-secrets-part2-leaks-on-release

I am not really a programmer so, I have little knowledge about how this works.

**Comment by folletto** [comment]
Unfortunately it all depends on how Apple implements the UIWebView and the bugs solved there, we have no control over it. That article is almost one year old and so it should be done a more recent benchmark, maybe on the final iOS5 release that will be out in a couple of days.

We can't do much there, unless someone is going to develop a JavaScript library targeted to Mobile Safari / UIWebView specifically.
