### ISSUE TITLE
Multiple HPUB

### ISSUE THREAD

**Issue by leo70623** [Simbul/baker#130]
Hi, I just found this amazing framework for developing e-book, I've tried and looked for ways to add multiple HPUB on my shelf. Is there any other ways that could support local multiple HPUB?

**Comment by folletto** [comment]
Hi leo! :)

Multiple HPub support is coming. Progress, feedbacks and comments are tracked on the Issue #20, right here, and it's currently scheduled to be released in Baker 4.0. :)
