### ISSUE TITLE
Multitap navigation removal cleanup

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#131]
Given the results of the poll of Issue #114, we are going to remove multitap to browser multiple pages at once.
See there for the whole discussion. :)

**Comment by Xm4s** [comment]
To be completely clear:

• Now there's a delay of 0.5 sec between the change of a page and its loading. The delay is necessary to check if the user is tapping more than one time.

• The delay of 0.5 sec is also the time necessary for the scrollview animation to be complete. Starting the loading of a page before the animation is completed cause severe slowdowns.

Removing the delay may be a way to improve page loading speed, but up to know loading pages to quick is really heavy on the device. Further testing is needed.
