### ISSUE TITLE
Topic/Label called 'Design'

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#133]
Maybe it's a nice addition to this community to add a section with it's own label called 'Design' (or something like that). In that section we can discuss and share CSS/HTML snippets, JS files, tips/tricks, etc. which work in the Baker Framework.

For example: I can explain how to add Google Analytics to an app to give you insight of your readers location.

What are your thoughts about this?

**Comment by folletto** [comment]
Uhm, it's a good point. 
I wonder if we could maybe use the wiki for that? What do you think?

**Comment by danielbenjamins** [comment]
Yeah sure, if there'd be a place to share stuff, it'd be great!

**Comment by folletto** [comment]
Ok, check the Wiki section on top. You should be already able to edit and add pages... ;)

**Comment by Simbul** [comment]
Since the discussion is no longer active, I'm closing it. Please reopen if necessary.
