### ISSUE TITLE
Multilanguage magazine: is it possible?

### ISSUE THREAD

**Issue by albertoMartinsen** [Simbul/baker#134]
Hi,

I'm new to Baker and to the AppStore. I'm about to release my first little ebook for children inside the AppStore using Baker+Hype (http://www.tumultco.com/hype/). I'm not a programmer, just a designer, so I found both a perfect combination for me (within Hype I design the book, and later use Baker as the envelope to build the app). The only thing I'm wondering right now is about languages: I'm spanish living in Norway, and my girlfriend is from Barcelona, so we would like to have the book translated to 4 languages: Spanish, English, Catalan, and Norwegian. I'm not sure how to make it easier for me and for the customers: Should I make one app for each language? Should I put flags in the first page to choose the language and then have 4 books inside one app? Or is there a workaround for Baker to detect the language of the iPhone or iPad and show the appropriate language itself?

Sorry if it's not the right place to answer, but I didn't find other support forum.

Thanks in advance ;)

**Comment by danielbenjamins** [comment]
Maybe you could place different .hpub-files on a server, so your reader can download the book after choosing their own language? Check the README file for using .hpub files, it's really simple!

**Comment by folletto** [comment]
It should be easy just using the multilingual feature of iOS apps, but even if we know it was done in one of the previous versions of Baker, I didn't test with the latest one.

Check however a resource like this one:
http://stackoverflow.com/questions/5748600/making-multi-language-ios-app

**Comment by albertoMartinsen** [comment]
Thank you for your answers. Folleto, I'm checking your link, but I'm not programmer and it seems really difficult for me to understand what I should do :(. The perfect solution for me could be to have 3 books inside one app, each one in its own folder, and opening the correct one depending on the device language, but as far as I know, it is no possible, isn't it?

**Comment by folletto** [comment]
Well, multi-language support isn't much different from what you describe, but right now I didn't dig into it so I can't tell you if it's easily possible and how.

**Comment by albertoMartinsen** [comment]
http://developer.apple.com/library/ios/#documentation/MacOSX/Conceptual/BPInternational/Articles/LocalizingInterfaces.html#//apple_ref/doc/uid/20002138-BBCBFFDF

Here they talk about .nib and .lproj files, but I don't find any of them in Baker, and inside Xcode 4, in the main project info tab, I can see "Localizations", and several languages, and all say "0 files localized". I add Spanish, but I don't know how to add localized files :(.

**Comment by folletto** [comment]
It might be as easy as adding the two localization folders and put inside each one the "book/" folder:
http://www.raywenderlich.com/2876/how-to-localize-an-iphone-app-tutorial

But I can't confirm right now, I need some time to test it. :)

**Comment by albertoMartinsen** [comment]
I tried to do the following steps:
-Within Xcode, create a "Localizable.strings" file and save it inside "Resources" folder, with the default content.
-Click to show the "Utilities" right panel, and add spanish language.
-Within Finder, I create a folder called "book" inside "es.lproj" folder, and copy there all the spanish related files, leaving the english version in the main book folder (if not, Xcode says "No such file or directory" error).
-Then, I launch iPad simulator and change the language within it.
-And then, I clean and run the scheme, but only the main english version loads :(. I tried also restoring iPad simulator, to be sure it loads a fresh copy of the app.

Maybe I'm doing something wrong or I'm missing some step or do I need to put "Localizable.strings" elsewhere...

Thanks for your help

**Comment by folletto** [comment]
Yeah, sorry, but I can't help more than this right now. We'll track this as a feature and we'll add it in a future version. :|

**Comment by albertoMartinsen** [comment]
Ok ok, I understand. Many thanks for your help anyway!

**Comment by folletto** [comment]
However we asked for support on Twitter, if we have news we'll write here. Also, we'll write here when we are able to get on that part of the project, so you'll be updated either way. :)

**Comment by nelsonliu3830** [comment]
My be it can be done by a Javascript.

**Comment by webschnecke** [comment]
have anyone new ideas about languages?

I have tested the localization with xcode but I get an error about MULTIPLE FOLDER "book" -> one inside de.lproj and in en.lproj

**Comment by morands** [comment]
This is just an idea but you could take a look to https://github.com/nin9creative/baker. That provides a shelf for magazines, you can use the shelf to put different books in different languages... Sure it wouldn't be perfect because the user has to decide which to download and then download it but better than anything :)

**Comment by folletto** [comment]
@morands It's still in development, and it will be merged into Baker when it's ready. :)

**Comment by morands** [comment]
@folletto Oh cool! Sorry :)

**Comment by ShaunStilwell** [comment]
Any one managed to implement multi languages yet? 

Any ideas about pointing the user to a specific folder ie: en.lpro or fr.lpro?

eg: Cover page would have a language select option and the user would select their language and be directed to that specific version of the book.

**Comment by folletto** [comment]
With that approach, you can have a cover page that then downloads the book in the right language. :)

**Comment by ShaunStilwell** [comment]
Issue it needs to be a stand alone app and not integrated with the newsstand. I have looked at the https://github.com/nin9creative/baker, bakershelf-newsstandkit branch which works as you have suggested but still in integrated with the newsstand.

There has been an app approved that works as I would like it http://itunes.apple.com/app/the-canny-outlaw/id538273615, just not sure how they achieved it.

**Comment by folletto** [comment]
I'll expand: 
1. Take the current version of Baker
2. Create one book per language, using the `hpub` format and zip it accordingly (see the wiki at the top for more info)
3. Create a "book" made with just one page, that page will have two `book://` links pointing at the two languages `hpub` files you previously uploaded on your server.

Done. :)

**Comment by ShaunStilwell** [comment]
Right so I have the books in the correct languages, so I all I need to is create a new book ie: splash screen with the book:// links pointing to the correct versions. This will be submitted to the App Store? 

If that works you're a legend!

**Comment by folletto** [comment]
Yes. That's it. :)

**Comment by Simbul** [comment]
@shaunstylz out of curiosity, why do your app need to be standalone, as opposed to an app with Newsstand support?

**Comment by ShaunStilwell** [comment]
It's a request from a client. They prefer to have a standalone app.

**Comment by Simbul** [comment]
Then I guess my question would be, why do they prefer a standalone app? :D

Anyway, coming back to the issue, have you had any chance to implement @folletto's suggestion?

**Comment by ShaunStilwell** [comment]
The client perceives the standalone app as having more value. 

I have manage to implement solution, waiting for the client to make sure all the content is ok and then I will resubmitted to the app store. 

Just wanted to say, thanks for an awesome framework and the support is fantastic!

**Comment by Simbul** [comment]
Brilliant!

I'll keep the issue open so you can come back and let us know how it went. Good luck with the submission!

**Comment by benoitchantre** [comment]
To add a new localization of the app, you can simply select the project in Xcode and to click on the add button under "localization" (see screenshot). Then you need to translate strings in this file and it will work.

I don't know why it keeps the new file inside en.lproj, I'm new to Xcode.

![Capture d e cran 2013-01-02 a 16 16 29](https://f.cloud.github.com/assets/1521015/38475/f8c0294a-54ef-11e2-88cc-fc92ea73c2b4.png)

**Comment by benoitchantre** [comment]
Here's a tutorial from Apple : https://developer.apple.com/library/ios/#referencelibrary/GettingStarted/RoadMapiOS/chapters/InternationalizeYourApp/InternationalizeYourApp/InternationalizeYourApp.html

**Comment by benoitchantre** [comment]
The master repo has been updated, you can now <a href="https://github.com/Simbul/baker/wiki/Add-a-new-localization">localize the app in your language</a>.

**Comment by Simbul** [comment]
On that note, I edited the page to reflect the fact that we don't support language-specific localisations in the main repo. It is essentially a matter of not having something in the main repo that gets out of date very easily. More on this in #664.

Thanks again for the contribution, @benoitchantre. I'm closing this discussion as it seems like the issue has been solved with your pull request.

**Comment by bdgeyter** [comment]
For a Newsstand app I am building, I've supported multilanguage magazines by adding the following to the `Constants.h` file:

```
#define NEWSSTAND_MANIFEST_URL NSLocalizedString(@"NEWSSTAND_MANIFEST_URL",nil)
```

In each `localizable.strings` file I then define:

```
@"NEWSSTAND_MANIFEST_URL  = "@"http://example.com/en/shelf.json";
```

with a separate folder (/en by default) on my server for each language the magazine supports. Basically, I set up different shelf.json and .hpub files for each language in those folders.

I'm wondering if this is a clean way of doing it? I'm mainly fearing this approach will crash and burn when I implement MagRocket into my server.

**Comment by tekdope** [comment]
@bdgeyter Hi any feedback on this and using MagRocket ?

**Comment by folletto** [comment]
I guess you should ask on MagRocket's github, for us this thread is two years old and closed — also with the clever solution just above. ;)

**Comment by nin9creative** [comment]
Not sure what the question is here - however if you are talking about the description, title and whatnot....  MagRocket stores all strings using UTF8 encoding, so it should work with multiple languages.  For instance, I know of one guy that has already published a Russian version of a magazine and used MagRocket on the backend just fine.

Andrew

**Comment by tekdope** [comment]
That was the purpose of my question, if defining the shelf path int he localizable.strings was actually working without any troubles in MagRocket :)
I don't see any reasons why it wouldn't but just curious to know:)

**Comment by bdgeyter** [comment]
I haven't tried this myself yet with MagRocket. 

@nin9creative, I guess the question is more whether it would easily support multiple languages (i.e. multiple .hpub, one for each language). 

Maybe not a bad idea to move this to MagRocket's Github ;)

**Comment by nin9creative** [comment]
Ah, at this point no...  It could be done though, don't see why not.  It'd be a feature of the Backend server to allow the definition of 
multiple language .hpubs for each Issue - then serve those up based on some sort of indicator from the Baker calls as to which language
was needed.
