### ISSUE TITLE
Show JavaScript nav with double tap?

### ISSUE THREAD

**Issue by rludgero** [Simbul/baker#135]
After a month of testing and reading all the posts, I've been locked in the menu that I created, the problem is that done in js and I can not make the double-tap event is associated with my menu show because ios not accept the dblclick jquery event.

I would like my menu will be displayed as status bar top, double tap but I'm just starting to objectify c still have not found the solution.

I've seen can be done it with  index.html, but is not valid for my menu.

Any idea?

Sorry for my bad english,

Thank you very much in advance.

**Comment by folletto** [comment]
Uhm I think I need to understand better what you need: why isn't index.html valid for your menu? :)
What are you trying to do? :)

**Comment by rludgero** [comment]
hi folleto, thanks for answer, 

I created a menu bar like a carrousel placed in all .html pages of my magazine, but i want display it when i make a double tap event.

In my css the #id  dysplay: none, and jquery after .dblclick show slidetoogle, its posible indicate a class or id for open and close with double tap in objective c?

**Comment by folletto** [comment]
Sure. You just have to attach to the matching event and send a specific javascript command to the UIWebView. However, you should be able to catch it in JavaScript before the double-tap reaches ObjC. :)

It's not clear to me why index.html wouldn't work, however. :)

**Comment by rludgero** [comment]
Perhaps because the index.html I'm not calling it correctly, I stand as an anchor, not if it's alright, can you help me?

**Comment by folletto** [comment]
But what version of Baker are you using? Index.html is just in the latest working branch. :)

**Comment by rludgero** [comment]
yes, now i used the 2.0, but I do not get to make it work.

**Comment by folletto** [comment]
Ok: index.html exists only on the current development master that is going to be released in september. You can  get it from the download button clicking on the toolbar above on Source and then "Download". :)

**Comment by rludgero** [comment]
ok, i will try this, thanks a lot.

**Comment by rludgero** [comment]
This work perfectly now, thank you very very much folleto!

**Comment by folletto** [comment]
You're welcome. If you find any bug, just write them here in the appropriate Issue or by opening a new one. :)
