### ISSUE TITLE
Is it possible to add background audio for the whole app?

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#136]
Is it possible to add background audio which keeps playing continually, even when swiping pages?
Especially for a children book this would be great.

**Comment by folletto** [comment]
We didn't test, but it _might_ work if you add it in the index.html. Please however: add a pause button. :D

**Comment by danielbenjamins** [comment]
Just tried it and it works. Only autoplay (HTML5) doesn't work.

**Comment by folletto** [comment]
Excellent! :)

Autoplay is a little buggy on WebKit side. Does turning OFF the MEDIA_PLAYBACK_REQUIRES_USER_ACTION flag helps maybe?

**Comment by folletto** [comment]
...may I ask also if you can paste on a https://gist.github.com/ the code and link it here, so others can find and use it? :)

**Comment by danielbenjamins** [comment]
I already turned that flag off (#define MEDIA_PLAYBACK_REQUIRES_USER_ACTION NO), so that won't help :)
Autoplay (video) works in another page which is in the book. Is the index.html being loaded when opening the app, or is it idle until opening the table of contents?

I just added the code: https://gist.github.com/1200126

**Comment by folletto** [comment]
Uhm let me check. ;)

**Comment by folletto** [comment]
Ok, it seems that it's loaded at the beginning, but we'll check in detail. ;)

**Comment by danielbenjamins** [comment]
Any news on this yet? :)

**Comment by Simbul** [comment]
We still need to check this in detail. However, as a tentative answer I'd say that the index view is indeed loaded when starting up the app. The only problem is, the MEDIA_PLAYBACK_REQUIRES_USER_ACTION flag is not applied to that view (only to the main view) and the default behavior is _not_ to autoplay media.

If you are in a hurry and willing to meddle with ObjC code, you could try adding

```
webView.mediaPlaybackRequiresUserAction = NO;
```

at line 85 in IndexViewController.m in the current master branch.

As soon as I have some time on my hands, however, I'll make sure the flag (which is now a configuration in the manifest) is applied to the index view as well.

**Comment by danielbenjamins** [comment]
I just added the code at line 85 and it was working right away. Thanks!

**Comment by armenjo** [comment]
can't find the code at https://gist.github.com/1200126
?
