### ISSUE TITLE
<title> problem in PageTitleLabel.m

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#137]
Hello,

I'm trying to migrate to the latest version of Baker and I downloaded the latest version of the "master" branch.

Everything works fine until I modify the default book and I include mine. After, Xcode displays error "PageTitleLabel.m" and SIGABRT signal.

NSRange matchRange = [[titleRegex firstMatchInString: FileContent options: 0 range: NSMakeRange (0, [FileContent length])] rangeAtIndex: 1];

Any suggestion? ;)

Thanks!

**Comment by folletto** [comment]
Could you paste here the full line of the title tag, or maybe the full head tag? It should be related with something in the title. :)

**Comment by frantovar** [comment]
Sorry, text editor of github compile the HTML code... even using the label

I upload the first html file of my book:

http://dl.dropbox.com/u/487370/001_01_portada.html

**Comment by folletto** [comment]
To paste code you can use the sister website of Github, Gist: https://gist.github.com/ :)

Ok, that looks fine... mumble. Could you paste (here or on Gist) the full stacktrace? :)

**Comment by Simbul** [comment]
Weird. I'll have to look into the code when I got some spare time.
Do all the pages have the same title tag?

**Comment by frantovar** [comment]
The title is the same. Do not be like this? 

I think there is problem with the paths. I will re-localize the project to match and then I comment.

Thanks!

**Comment by frantovar** [comment]
Hi, 

I think that the problem is in the .html files format, Json seems that fail with the .html files in ASCII format, changing for UTF8 this files and Work fine ;)

**Comment by folletto** [comment]
A-ha! That's an excellent discovery! :D

**Comment by folletto** [comment]
I think I can close this, right? :)

**Comment by frantovar** [comment]
Yes, sorry ;)
