### ISSUE TITLE
Does anyone have example code for adding video

### ISSUE THREAD

**Issue by Prufrock1** [Simbul/baker#140]
I've been trying to implement video content to individual pages- but am having no sucess. I've tried youtube videos, HTML5 vids and quick time but to no avail. Has anyone successfully added a video? If so, can you share your method. Thanks!

**Comment by folletto** [comment]
There are plenty of books on the store that are using videos. As far as I know, a HTML5 video tag does the job. What problem are you having?

**Comment by Prufrock1** [comment]
```
    <video preload="metadata"> 
        <source src="assets/dizzy.mp4" type="video/mp4" />
        <source src="assets/dizzy.webm" type="video/webm" />
        <source src="assets/dizzy.ogv" type="video/ogv" />
    </video>
```

I was also using the javascript from this example to activate the play button:
https://github.com/remy/html5demos/blob/master/demos/video.html

But I still cannot get the video to play- tapping on it or pressing the play button does not work

**Comment by folletto** [comment]
Does it work on Safari Mobile? :)

**Comment by Prufrock1** [comment]
I checked my initial code in Safari Mobile and it wasn't working.
But then ended up getting the video to work with following code:
     <video id="bubbles" width="700" height="560" controls="controls" src="assets/bubbles.m4v" poster="assets/bubbles.jpg"></video> 

Figured it out with this demo:
http://www.robwalshonline.com/demos/html5_video_demo/html5_video.html

just wanted to share.

**Comment by folletto** [comment]
Excellent. :)

As a general rule of thumb, I'd suggest to test on Safari / Safari Mobile in order to see if it's a problem with the engine itself. Since we embed directly the engine, it's usually a nice way to isolate specific problems (and maybe even use their debugger :D). :)

**Comment by k8fisher** [comment]
Just wondering Im having problems with m4v files in the framework. Ive added a poster to the video but cant seem to get the poster to show / when the video ends the poster isnt re-shown, the video stays on black.

Im using the standard format of code and things seem okay in safari but in the simulator theres no poster image and the video area is black at the end of the video. Shouldnt it return to the poster image?

Code example:

```
<video poster='images/twelve.jpg' color="#ffffff" bgcolor="#ffffff" controls="">
    <source border='#ffffff' bgcolor='#ffffff' color='#ffffff' width='100%' height='100%' src='media/Sonoma.m4v' />
</video>
```

**Comment by folletto** [comment]
Well, I suppose it should if it works in Mobile Safari, but it's quite probably an issue with UIWebView, so you might be able to open a bug on Apple's website or on the developer forum. :)
