### ISSUE TITLE
Babylon App

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#141]
Hi Guys,

thanks a lot for the baker framework. 

I'm studing that for my university project and I found the documentation ( thanks to laker,too) clear , so I downloaded the baker framework and the Xcode for trying it.

I see the "Showcase" for see the possibly result and I found the Babylon book/App , it's very nice.

I see some features that I don't know how to enable in baker :
- multi issue ( but i read the read on about the download of multi issue in hpub format)
- the managing/selection of this multi issue in the "application bar" 
- the progress bar of dowloading the number
- the summary on the left of the display

I try to do some search on Internet without any result.

Can you please help me?

Thanks  a lot
Goodbye

**Comment by folletto** [comment]
Except the book download, that you can get by linking from a book another book using the book:// protocol, everything else is planned for us (you can see around this issue tracker). Babylon did an independent work to support these features before we implemented it. ;)

**Comment by airtek** [comment]
Davide,

Thansk a lot, I have seen the issue tracker before, but later I will 
check better.

Thanks a lot

Goodbye

Il 12/09/11 21.29, Davide Casali ha scritto:

> Except the book download, that you can get by linking from a book another book using the book:// protocol, everything else is planned for us (you can see around this issue tracker). Babylon did an independent work to support these features before we implemented it. ;)

**Comment by folletto** [comment]
Ok, cheers! :)
