### ISSUE TITLE
Coloring book

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#142]
Just found out about an awesome way to make a 'color book' with HTML5: http://www.williammalone.com/articles/create-html5-canvas-javascript-drawing-app. In a desktop browser it's working great, but it doesn't work on the iPad... Any suggestions for an alternative which can be used inside Baker?

**Comment by folletto** [comment]
iPad, you mean iOS 4.x or 5? :)

**Comment by danielbenjamins** [comment]
I tried it on my iPad with iOS 5.0, latest beta.

**Comment by robotloveskitten** [comment]
It's not going to work because he's capturing mouse events. If you were to convert these to touch events, it might work.

**Comment by danielbenjamins** [comment]
Just found something after a quick Google search: http://vetruvet.blogspot.com/2010/12/converting-single-touch-events-to-mouse.html. I'm going to try this later.

**Comment by danamajid** [comment]
@eaglejohn did you manage to do this?

**Comment by danielbenjamins** [comment]
No afraid not... I contacted the author of the script and he pointed me in this direction:

"You will have to call the init function to add the event listeners. The following article shows how to point touch events to mouse events": http://ross.posterous.com/2008/08/19/iphone-touch-events-in-javascript

To be honest I don't have a clue since I don't know anything about JS.

**Comment by danamajid** [comment]
I gave it a try, and it seems to work fine.
This is what needs to be done:

*\* html5-canvas-drawing-app.js**
    // add this somewhere after line 66
    // author: http://ross.posterous.com/2008/08/19/iphone-touch-events-in-javascript

```
function touchHandler(event) {
    var touches = event.changedTouches,
        first = touches[0],
        type = "";
         switch(event.type)
    {
        case "touchstart": type = "mousedown"; break;
        case "touchmove":  type="mousemove"; break;        
        case "touchend":   type="mouseup"; break;
        default: return;
    }

//  initMouseEvent(type, canBubble, cancelable, view, clickCount, 
//  screenX, screenY, clientX, clientY, ctrlKey, 
//  altKey, shiftKey, metaKey, button, relatedTarget);

var simulatedEvent = document.createEvent("MouseEvent");
simulatedEvent.initMouseEvent(type, true, true, window, 1, 
                          first.screenX, first.screenY, 
                          first.clientX, first.clientY, false, 
                          false, false, false, 0/*left*/, null);

                          first.target.dispatchEvent(simulatedEvent);
event.preventDefault();
}
```

// inside the prepareCanvas() function add the event listeners

```
    document.addEventListener("touchstart", touchHandler, true);
    document.addEventListener("touchmove", touchHandler, true);
    document.addEventListener("touchend", touchHandler, true);
    document.addEventListener("touchcancel", touchHandler, true); 
```

That's pretty much it. Good luck!

**Comment by Simbul** [comment]
Let us know if you manage to get a working implementation of this. Looks like a good candidate for a tutorial page on the wiki ;)

**Comment by danielbenjamins** [comment]
Time is a bit short at the moment, but I'll sure give it a try. Thanks @dandoen!

**Comment by danielbenjamins** [comment]
Just tried the code of @dandoen and it works right on, great!
You can download the modified script from my Dropbox: http://dl.dropbox.com/u/17869072/html5-canvas-drawing-app.zip

Next challenge: make the drawing canvas larger for the iPad screen :)

Edit: just tried to make the canvas larger, but it really slows down the drawing and very angular lines.

**Comment by folletto** [comment]
Awesome! :D

**Comment by folletto** [comment]
Did you find anything? :)

**Comment by danielbenjamins** [comment]
No, didn't look into it yet. Hope I'll find some time soon! :)

Sent from my iPad

On Nov 14, 2011, at 2:21 PM, Davide Casali
reply@reply.github.com
wrote:

**Comment by marciosm** [comment]
you have to redesign the entire canvas. I did it but it's not an exactly formula as it depends a lot of the quantity of colors you want to work and the size of the picture. I'm still working on it, but this is the way. Does not only resize the canvas, but every element inside it.

**Comment by folletto** [comment]
Was anyone able to do this in the end? :)

**Comment by marciosm** [comment]
I did it on my book that will be sent to Apple this month. :)

**Comment by folletto** [comment]
Great! :D

**Comment by marciosm** [comment]
The book is now on iTunes and has two coloring pages exactly as we were talking about above. Regards ;)

**Comment by bahmet** [comment]
@marciosm i found paint bucket tool here  http://www.williammalone.com/articles/html5-canvas-javascript-paint-bucket-tool/
but this is a separate js. do you have any idea how to add paint bucket to the tools of this js http://www.williammalone.com/articles/create-html5-canvas-javascript-drawing-app/ 
thanks :)

**Comment by marciosm** [comment]
Nope. Yet ;)
I will take a look on it soon.
Regards

Marcio Morais
(11) 9778-9873

**Comment by bahmet** [comment]
hi,
anyone wants to use this script for color book, @Simbul solved internal linking problem with the script as describe here https://github.com/Simbul/baker/issues/334
Kudos to @Simbul ;)
