### ISSUE TITLE
Image as background in book.json

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#143]
Is it already possible to use an image as a background in book.json?
I just tried it using CSS ("background": "url(bg.png)"), but this doesn't work.

**Comment by folletto** [comment]
Nope. We are still implementing book.json. :)
When Issue #102 is complete, then you'll be able to use it. :)

**Comment by danielbenjamins** [comment]
Alright, so at the moment it's only possible to change #000000 into another color? I tried it and this is working, I'm using the latest master.

**Comment by folletto** [comment]
Yes, we are working on it right now, so something already landed. :)
