### ISSUE TITLE
turn off page turning?

### ISSUE THREAD

**Issue by jhill3d** [Simbul/baker#145]
I would like the navigation of my book to take place within my html documents via buttons and other user actions. Can I easily turn off all page turning? I know it seems odd but my book is more of an interactive book that requires kids to do something to get to the next page(s). Thanks.

**Comment by folletto** [comment]
It's a good request, I don't have a simple answer, but maybe some of the others has :)

**Comment by danielbenjamins** [comment]
That's something I'd really like to know. At the moment I'm building an app for someone who says that tapping left and right isn't stable and with 'normal' use of the app I experiencing the same some time.

Edit to be more clear: swiping seems to be more stable than tapping.

**Comment by folletto** [comment]
What do you mean by "isn't stable"? :)

**Comment by danielbenjamins** [comment]
Sometimes you have to tap about 10 times before the page flips, sometimes only once. It's very different each time. Swiping seems to be more stable if you look at it that way :)

**Comment by Simbul** [comment]
To turn off the 4 tappable edges it should be enough to change line [198](https://github.com/Simbul/baker/blob/8fc8d53f956bec2977c13652606ad1620c039a62/Classes/RootViewController.m#L198) in `RootViewController.m` to:

```
int tappableAreaSize = 0;
```

**Comment by jhill3d** [comment]
Would this also disable turning the pages?

**Comment by Simbul** [comment]
Nope, this only disables the tappable areas (top, right, bottom, left).
With this simple change it will still be possible to swipe to turn the pages. Double-tap to open the index will still work as well.
And of course it will still be possible to implement a link-based navigation.
