### ISSUE TITLE
Disable overlay while performing a mousedown/taphold

### ISSUE THREAD

**Issue by lord-of-shred** [Simbul/baker#146]
Hi alltogether,

First, great work, I dug into Baker/Laker one week ago and it made my life much easier.

But I got a question on an issue I discovered while working on a demo app.

When I perform a tap/click/mousedown/taphold the element/div I tap on get's highlighted with an overlay:

[URL=http://imageshack.us/photo/my-images/809/holdingdown.jpg/][IMG]http://img809.imageshack.us/img809/3076/holdingdown.jpg[/IMG][/URL]

Uploaded with [URL=http://imageshack.us]ImageShack.us[/URL]

Is it possible to disable that or drag the opacity down to 0? It's really ugly for something like a 360° plugin I developed for the app.

Thanks in advance and chapeau to your work.

Greeting, Leo

**Comment by lord-of-shred** [comment]
Sorry I goofed on the link, I hope that will work:
http://picfront.de/d/8me2

**Comment by folletto** [comment]
From your description it seems something you have to manage on the HTML side, regardless of Baker. Check this answer here: http://stackoverflow.com/questions/826782/css-rule-to-disable-text-selection-highlighting :)

**Comment by lord-of-shred** [comment]
Thanks for the fast reply.

The solutions discussed in the stackoverflow thread didn't solve it....or not on the simulator...I'll get back to you, when I got the chance to try it on the real devic...which will take some days...

Thank you till then. :-)

**Comment by danielbenjamins** [comment]
This CSS rule works for me:

outline: none;

**Comment by lord-of-shred** [comment]
Problem solved, after all, folletto, you were right!
I had a faulty CSS import in my main styles .css with a typo in the:

body {
    margin: auto;
    -webkit-tap-highlight-color: transparent
}

part.

After removing it, it works like a charm on the simulator and the ipad.

Thank you very much for your input and keep up the good work!

Best wishes, Leo

**Comment by folletto** [comment]
Awesome. :)
