### ISSUE TITLE
Target iPhone platform

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#15]
_As an author I want to publish on the iPhone_

This feature allows Baker's author to build well-designed books on the iPhone screen size as well. While it seems counter-intuitive to be able to build design books on the iPhone small screen, it's still well within Baker's aim: to allow authors to build great designed books... even if it's on a small screen. ;)

**Comment by svdgraaf** [comment]
One of my commits in the rotation pull request should enable this, now it's just a matter of creating another build, see here: https://github.com/svdgraaf/baker/commit/7752a48489cff0c6dd5cca5af60f86e4c1265b28

**Comment by folletto** [comment]
That's true! :)

After your branch is complete and merged, we should look into it. :)

**Comment by Xm4s** [comment]
Ok, from commit 410da40c42c32a9caf8f2fc130f60dc8361281e0 it's possible to publish on iPhone devices :)

Two small notice on the matter:
1. The default configuration in the Project Settings is iPad by default, one should change the setting as needed (for targeting only the iPhone or iPhone/iPad); see the README file for details.
2. The iPhone Baker Icon (57x57) is still missing inside the project, we'll be adding it as soon as possible :P

**Comment by folletto** [comment]
Icons added. Some more safety testing would be advised. ;)

**Comment by Xm4s** [comment]
Icons tested ;D
All works well, I'm closing this up.
