### ISSUE TITLE
Baker errors after upgrading to Xcode 4.2 developers preview and iOS5

### ISSUE THREAD

**Issue by albertoMartinsen** [Simbul/baker#150]
Hi,

I just enrolled the iOS developer program to publish my first app made with Baker. I did it because iOS5 is very close and would like to see if my app will be compatible. With Xcode 4.1, the first time I started a project, it told me to upgrade a couple of things, and after it, I had no errors. Now, I did the same with Xcode 4.2 and a clean .xcodeproj but after upgrading that couple of things, I keep having some issues (although it seems to work OK). The issues are inside Downloader.m:

This code:     `[self connection:connection didFailWithError:statusError];`
Has this two errors: 
-   ('_' may not respond to '_') Instance method '-connection didFailWithError:' not found (return type defaults to 'id')
-   (Semantic issue) 'Downloader' may not respond to '-connection didFailWithError:'

Can anybody help me? Should I downgrade to Xcode 4.1 and iOS4.3 and wait until you upgrade it?

Thank you very much in advance

**Comment by folletto** [comment]
We are developing in parallel on different iOS and Xcode versions, and we are still waiting a bit to finalize the iOS 5 part. However these problems shouldn't be "errors" but "warnings", no? It should still compile and run, or am I wrong? :)

**Comment by albertoMartinsen** [comment]
Don't know. I'm new and not a programmer :(. Xcode call them "issues", and yes, they compile and run, but I was just worried because maybe those "issues" are more dangerous than I think, or maybe Apple doesn't approve apps with "issues" :?

**Comment by folletto** [comment]
Yeah, these shouldn't be blocking problems, they are going to be solved, but it still works. :)

**Comment by albertoMartinsen** [comment]
Great to know ;). Thanks for your fast and kind support!! And congratulations for such an amazing framework!

**Comment by folletto** [comment]
Thanks to you, it's awesome to have people that take time to come here and collaborate with the community. :)

**Comment by exalted** [comment]
Although iOS 5 SDK along with the Xcode 4.2 is official now, I still got the "error: instance method '-connection:didFailWithError:' not found (return type defaults to 'id') [-Werror,3]". Any ideas please?

**Comment by folletto** [comment]
Yes, 3.0 is not out yet with iOS5 support. :)

However I'm able to compile and run it, ignoring the warning, without problems. Are you using Baker 2.0?

**Comment by exalted** [comment]
@folletto thanks for quick reply, I actually don't use Baker at all, yet this issue is valid anyway...

**Comment by folletto** [comment]
Did you try if Baker 3.0 just released has the same problem? :)

**Comment by exalted** [comment]
@folletto thanks again, but as I mentioned earlier I don't use Baker at all, it's just that I'm having the same issue you had; that's why I asked here. Excuse me for the confusion/trouble that may have caused to you. Cheers.

**Comment by folletto** [comment]
No problem. :)
For us it was as simple as updating the project to the latest version of Xcode. :)
