### ISSUE TITLE
Saving values to a "global variable" - Is that possible?

### ISSUE THREAD

**Issue by lord-of-shred** [Simbul/baker#151]
Hi,

It's me again. I got an idea for some kind of "playing book" to get more familiar with that whole HTML5, JS and Baker thing (I come mostly from a technical 3D (dynamics, rigging, procedural stuff, etc. ) and Flash AS3 background so please ignore if my questions seem stupidly put ;-) ).
My idea would be to build a small book with some pages, and on each there is a little game where you can collect points. Is it possible to save the points values into a variable to acess it from another page?

Thank you very much for shareing your knowledge with all of us!

Best wishes, Leo

**Comment by folletto** [comment]
So far, we didn't implement anything like that, because the pages at this point are isolated and work independently. 

What kind of data would you like to store? :)

**Comment by lord-of-shred** [comment]
Hi folletto,

I'll give you an example of what I got in mind:

You got a text on the first page and a small puzzle game with an easy diffuculty. When you finished it (eg based on the time it took you to do so) calculates a score. This score should be saved to a variable (int, string, whatever).
 When you get to the next page, you got again a text and a puzzle but now the puzzle difficulty adepts to your previous result, and so on.

I recon you could do this on one page and change it's text and game, but I like the character of swiping through a book...

Or another example, you have a startpage where you choose a character...and as you progress through the story/book you always are with the character you have chosen. So it would be nice to store that information what character you got somewhere.
I thought about using a file that gets written on the first page and read afterwards by every page on loadup with a js...but I don't know if you got the rights/possibilities to do so on the ipad.

**Comment by NathanFrund** [comment]
You might be able to use localStorage() for this.

**Comment by lord-of-shred** [comment]
Ah alright, I just read 2 articles about that. I'll test it when I get back to the ipad/Mac next week. Thank you for now.

**Comment by Simbul** [comment]
Btw, it'd be lovely if you could write a followup post and let everyone know where your inquiries have led you, when you're through ;)

**Comment by lord-of-shred** [comment]
^^ Yeah, sure I'll share some code if I can get it to work on wednesday when I get back to a Mac. :-)

**Comment by robotloveskitten** [comment]
You can use localStorage and sessionStorage in Baker. I have tested these out and they work fine. Any demo ripped from the web should work. localStorage should work great for games. 

The only caveat I would mention is that if you're doing anything on page load, things might get funky, because Baker preloads pages as you're navigating around.

**Comment by lord-of-shred** [comment]
Alright, I just got the chance to test it. Works very nice for that purpose.
Best way to utilise it for me was to include "jstorage.js" ( http://plugins.jquery.com/project/jStorage ) since Baker is already using jquery...and it sets up a nice setter/getter system. I setup a little demo to check it out, I will share with all of you:

http://pastebin.com/RPYjhJFH

I hope I could help someone with that piece of code.

Thanks for your support also.

Greetings, Leo

**Comment by folletto** [comment]
Awesome! :D

Thanks for sharing! :)
