### ISSUE TITLE
How to swipe vertically??

### ISSUE THREAD

**Issue by dboptimize** [Simbul/baker#152]
How to swipe each page vertically such as up and down each page like horizontally,,,??

(Not scroll on each page)

**Comment by folletto** [comment]
I think you should do that in JavaScript, there's no built-in support for pagination, just scrolling.

**Comment by Xm4s** [comment]
You could try to enable pagination on the webView.

in the loadSlot:(int)slot withPage:(int)page method, try adding ...
  ((UIScrollView *)[[webView subviews] objectAtIndex:0]).pagingEnabled = YES;
near the end, just before [scrollView addSubview:webView];

I didn't test it too well, so I don't know if there something else to fix or adjust ... but seems to work just fine :)
Let us know if this can help.

**Comment by aliababua** [comment]
Hey Xm4s! It's working fine! Great, great, great! 
Your code:
((UIScrollView *)[[webView subviews] objectAtIndex:0]).pagingEnabled = YES;

added before:
[self loadWebView:webView withPage:page];

Thanx a lot!

**Comment by folletto** [comment]
I think it might be worth adding a flag to out book.json then ;)
