### ISSUE TITLE
View a page on the ipad, when i click add to home screen we make download a magazine (like a asidemag) How to make?

### ISSUE THREAD

**Issue by danineves** [Simbul/baker#153]
It's a Javascript code? I see the source page, but i can´t find the code to make that

**Comment by folletto** [comment]
It's possible only if you do everything with HTML5, it's not Baker. Baker is made to allow you to publish on the App Store. :)

This link, found with a quick search, should help you: http://matt.might.net/articles/how-to-native-iphone-ipad-apps-in-javascript/ :)
