### ISSUE TITLE
Thumbs up

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#154]
Just a big thumbs up for the improvements in the latest (image as background, better page scrolling, reloading page, etc.)!!!

**Comment by folletto** [comment]
Thank you! :D
3.0 is near, now :D

**Comment by killer1loop** [comment]
Thank you for the great job guys, we are giving a spin at the latest commit too. Brilliant

**Comment by folletto** [comment]
Thank you all again! :)

Btw, if you want to have a look, now we are almost there for the release. It's a matter of days... maybe hours. ;)

**Comment by Simbul** [comment]
3.0 is out! Let's open new issues if someone needs more thumbs :D
