### ISSUE TITLE
How top publish the app to the store. 

### ISSUE THREAD

**Issue by roliveros** [Simbul/baker#155]
We need instructions step by step using Xcode 4.X on how to summit the app to app store.... Please......

**Comment by folletto** [comment]
You find them in the Apple documentation on the Developer page. It's quite detailed. :)

Also googling you can find interesting resources, like this video from Apple:
https://deimos.apple.com/WebObjects/Core.woa/BrowsePrivately/adc.apple.com.1579102445.01579102451.1580085281?i=2050284209

**Comment by roliveros** [comment]
Sr. Thanks for your help... But I am been trying all that for the pass two weeks... And I can not do....

**Comment by roliveros** [comment]
Can you help me to do it? Can web Skype and guide me to do so?

**Comment by folletto** [comment]
Did you try following that video? :)

**Comment by roliveros** [comment]
Yes Sr... I did....

**Comment by folletto** [comment]
Then I can't help much more, try finding a developer to support you. :)

**Comment by roliveros** [comment]
Hey Thanks.... that is not helpful. Miami don't have a developer that you can find for that.....
