### ISSUE TITLE
Please I need help to add to app Store.

### ISSUE THREAD

**Issue by roliveros** [Simbul/baker#156]
Can some one add a step by step how to.... add to app store? including the step for certification etc.... Thanks

**Comment by folletto** [comment]
Please, don't open other issues, you have already an open discussion. :)

As I said on the other topic, you should ask on Apple Development Forums, not here. It's their stuff. :)

**Comment by roliveros** [comment]
Look Follettooooooo. I am looking for a solution. if you have anything so say positive go away.....

**Comment by folletto** [comment]
Look Roliverooooos, I'm one of the founders, I'm not going away. ;)

The right place to ask for that, as I told you, is on the Apple Developer Forum: https://devforums.apple.com/community/ios

See ya. :)
