### ISSUE TITLE
Index View Problem

### ISSUE THREAD

**Issue by venkatmarri** [Simbul/baker#158]
Hello,
I am using new baker framework from the branch. 
I have problem with Index View, When I tap on the page its loading in Index View Itself.
For instance, If I am on Cover Page - and by mistake or, purposely I tap on the Cover page link in Navigation (Index) bar on bottom, desired page loading in the Navigation bar... and its been hidden until you delete from the device.
How to solve this Issue. Quick response much appreciated.

thanks
Venkat.

PS. I check original branch also, its been same.

**Comment by folletto** [comment]
Could you detail a step-by-step sequence on how to reproduce the problem? :)

**Comment by venkatmarri** [comment]
Sure...
1. I have downloaded new baker frame work from the branch.
2. I didn't changed anything in the Xcode project, only thing I used my own .html pages.
3. I changed the Navigation bar (index.html) with the content of my magazine.
    It worked fine on my device and simulator.
4. By mistake ones I clicked on Cover Page in Navigation bar at bottom. (I am already viewing Cover page).
5. Then The Navigation bar shows the actual cover page with in the bar.
6. I checked original project which i downloaded from the branch. It's also behaving in same way, loading pages in index view. ( I think, its because of opening links within the App instead of using the browser )
Hope I am clear? 
PS : I am new to Xcode, so, i don't know much to explain in detail. Sorry.

**Comment by folletto** [comment]
Just to exclude some possibilities: does it do the same with our demo book?
If not, could you give us your index, maybe anonymized? :)

**Comment by venkatmarri** [comment]
Its same with your demo book also.

**Comment by Xm4s** [comment]
Fixed with commit 3c85f4ef8daf5ab87924a2089405429d10fa8a52
Now all should work correctly :)
