### ISSUE TITLE
Chapter Jumping

### ISSUE THREAD

**Issue by PRDGS** [Simbul/baker#16]
Hi,
I tried to apply your platform to a catalog.
I have two main issues: 
- the possibility of use it in landscape mode - already being discussed in another thread...
- "chapter jumping"

I would like the catalog to be read as any normal book, but wanted to have direct links in main page to certain chapters. So in 1.html I had a link to 5.html, which worked, but when swipping back to the previous page, it goes back to 1.html (instead of 4.html)... I know this might be the intentional flow in some apps, but in an ebook, shouldn't it keep the page sequence, even after jumps?

Thanks!

**Comment by folletto** [comment]
The internal linking isn't supported yet in the released version of the Framework, but we have it already ready inside the GitHub repository, so you can either download that or wait for us to release the next zip package. ;)

**Comment by snive** [comment]
aha I've made my own internal link modification now
I should read these Issues better...
