### ISSUE TITLE
How can I make It only Portrait or Landscape

### ISSUE THREAD

**Issue by blumedia** [Simbul/baker#163]
How can i do that: make It only Portrait or Landscape only.....?

**Comment by folletto** [comment]
What are you using? Baker 2.0 or the current master? :)

**Comment by blumedia** [comment]
I am using Baker 2.0

**Comment by folletto** [comment]
Then just open RootViewController.m and change line 83 to the orientation you need:
https://github.com/Simbul/baker/blob/2.0/Classes/RootViewController.m#L83

:)

**Comment by blumedia** [comment]
Super... Thanks...

**Comment by folletto** [comment]
You're welcome! :)

**Comment by blumedia** [comment]
Do you have by any chance like different templates books... "no examples" by real HTML5 working templates like Forgotten Colours that is zoo good template it.....?

**Comment by folletto** [comment]
You can have a look at Laker Compendium for Baker, that does exactly that: http://www.lakercompendium.com/ :)

**Comment by blumedia** [comment]
Ohh yea I did that.... it is real good but you know what i am looking for?.... You can may be open a section were who used and make super nice jobs they can share for those who not are good or are new to this. :)

Thanks for all.

**Comment by folletto** [comment]
Well, if they want to share what they did they can already, and for everything else we have the Showcase section on the website:
http://bakerframework.com/books

Unfortunately it's hard to find someone that wants to contribute back with tutorials, examples and support. :)

**Comment by blumedia** [comment]
for sure... I think so... you are very right... Thanks for all your support. Super Job

**Comment by blumedia** [comment]
What is the current master?

**Comment by folletto** [comment]
The current work in progress that will be released as 3.0, you can test it clicking on Source above and then clicking on Download. :)

**Comment by blumedia** [comment]
Ohhh super.... and what are the changes?
