### ISSUE TITLE
Black "fade" after clicking content in iframe

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#165]
Regarding @Xm4s' comment on commit 46825733e540b07bb70c590a3757636ebb2dd9ff

"Now the webView fade in only the first time"

Is it possible to remove this as well? I'm experiencing this:
- Open book, don't click any content in iframe and swap page: no black fade
- Open book, click content in iframe and swap page: black fade

**Comment by folletto** [comment]
What do you mean by "black fade"? You mean fading from the black background?

**Comment by danielbenjamins** [comment]
Yeah I guess. There's a quick fade from black to white.

**Comment by Xm4s** [comment]
Hi!

Could you please explain how to reproduce the bug?
I'll need to know ...

• which rendering mode are you using? (screenshots or three-cards)
• where is located the page you are loading in the iframe? (it's an external page or included in a book subfolder)

Also I don't understand "click content in iframe and swap page", do you mean that you have a link in the iframe that points to another page in the book folder?

Thank you for your help, you're a great tester ;D

**Comment by danielbenjamins** [comment]
I'm using three-cards. The page which is being loaded inside the iframe is an HTML-page in a subfolder.

_I'll try to be more clear about the "click content in iframe and swap page":_
Your guess is right, on the page which is loaded in the iframe, there is a link which points to another page. This is a simple way to create a slideshow/click-trough without JS. The only issue right now is that, when you used this slideshow and you swipe to the next page in the book, a black fade/reload shows up.

My source code is available for testing (mail me).

**Comment by mutador** [comment]
this happens if you use a complex js

for some reason this version is very sensitive to complex js and css, appearing this bug and white flash betwenn changes pages.

I have a stable css page for general and do not touch it, if the new  page its complex i created a new css fot it.

even if the CSS does not give errors may be things you do not like the compiler or safari ?

**Comment by folletto** [comment]
If you are using three-cards, you're using more memory: that's why it's easier to see the slowness of UIWEbView.

**Comment by danielbenjamins** [comment]
Just switched from three-cards to screenshots and the fade is gone.
But isn't it strange that, when you use three-cards, the fade only appears after clicking in an iframe and not when you just swipe pages? I guess iframes are using too much memory?

**Comment by folletto** [comment]
Well, that's a possibility: the fade can be two things. One, is us doing actually the fade, the other is UIWebView that "flashes" content. I can't rule out one or the other, but with three cards that's surely a an increased probability. :)

**Comment by folletto** [comment]
Hi! Did you try again in the latest Baker 3.0? :)

**Comment by danielbenjamins** [comment]
No not yet, but I will try soon!
