### ISSUE TITLE
How can I use the download module?

### ISSUE THREAD

**Issue by dboptimize** [Simbul/baker#166]
I want to use the download module in Baker source.

I found a source file related with it (Downloader.m).

If there are no Book or .html, how can the Baker access the source page?

Please help me,,,

**Comment by folletto** [comment]
You should always have a default book, so Baker shows something to the user.

To use the download feature,  you have to use the book:// protocol, check it here:
https://github.com/Simbul/baker/wiki/Book-protocol

:)

**Comment by dboptimize** [comment]
Thank you so much~~

**Comment by folletto** [comment]
You're welcome. :)

Btw, keep an eye on Issue #20, when that one is closed it means we added native support for multiple books. :)
