### ISSUE TITLE
Hide toolbar Google Maps (not a Baker issue)

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#167]
This question hasn't anything to do with Baker itself, it's about Mobile Safari.

I added a map from Google Maps, but Mobile Safari adds automatically a toolbar with options like navigation and calling a phone number: http://imageshack.us/photo/my-images/651/mapssafarimobile.jpg

Does anyone know how to hide this toolbar?

Since you can't call with an iPad and when reading a Baker-book you don't need navigation as well :)

**Comment by folletto** [comment]
It looks like the advertisments/sponsored toolbar that Google adds automatically.

You might be able to turn it off with some of the options specified here:
http://code.google.com/apis/maps/documentation/javascript/reference.html#MapOptions

Or, try asking that question here:
http://groups.google.com/group/google-maps-js-api-v3?lnk=srg&hl=en
