### ISSUE TITLE
Urban Airship

### ISSUE THREAD

**Issue by venkatmarri** [Simbul/baker#168]
Hello!
I am trying to add urban airship to my existing app for push notification service,
How can I add that, I am reading the Documents available in Urban Airship, but it looks too complicated for me,
Is there any other way to add notification service.? which baker can support.

thanks

**Comment by folletto** [comment]
Baker should use the Newsstand features, but we have yet to implement any kind of integration. I'm afraid that you have to find a developer to add that feature yourself. :|

**Comment by venkatmarri** [comment]
OK. Thank you.
Will wait for it.

**Comment by folletto** [comment]
If you want to track our progress, you can keep an eye on Issue #100 ;)
