### ISSUE TITLE
Baker for Android?

### ISSUE THREAD

**Issue by inventionarts** [Simbul/baker#169]
I've tried out the latest 3.x version of Baker and it has advanced dramatically.

For a client project, would be great to use Baker, but there's also a requirement to support Android, particularly the Nook Color and forthcoming Kindle Fire. I found this: https://github.com/mbharadwaj/BakerAndroid but wondered if it has been used, and also would appear not to include the latest functionality. 

So just asking if anyone has put together Android support. Thank you.

**Comment by folletto** [comment]
Unfortunately we don't have time to work on an Android port as well, but we welcome anyone that is willing to collaborate with  us to provide that framework as well.

That port was made at the time of Baker 1.0, and has never been updated afaik.

If anybody is aware of an Android port, of of anyone willing to collaborate with us to do that, we'll be more than welcome! :)

**Comment by inventionarts** [comment]
Unfortunately, I don't have the skills to undertake this effort. I do think the release of Kindle Fire will make this meaningful. Will see if. Can figure out some way to move the effort. Thanks again.

**Comment by folletto** [comment]
Yep, precisely. ;)
