### ISSUE TITLE
Customizable intermediate scrollView

### ISSUE THREAD

**Issue by antonsukhonosenko** [Simbul/baker#170]
I'm a designer and newbie IOS developer and I am trying to use Laker framework to make a children book for iPad.
I tried to add a feature myself, but failed and now I request any help.
The feature I needed, is to show custom image inside of intermediate scrollView instead of just plain 'Loading...' text. 

What I already did before posting here:
I am not afraid of digging Objective C code, so I started with trying to put following simple code

``` objectivec
UIImageView *tempImageView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"28.jpg"]];
[scrollView addSubview:tempImageView];
[tempImageView release];
```

into RootViewController::initPageNumbersForPages() inside loop for pages - where, as it seems to me, contents of intermediate scrollView are initialized (I did it like this: https://gist.github.com/1290752).
Obvioulsly I added my image to project resources before running the app.

Problem is, this works and image is shown, but only once - only on a scrollView which is shown while _first_ html page is loading. 
If I add any more html pages, all other intermediate scrollViews except first are shown without any image.
At the same time, UILabel which shows 'Loading...' text is shown correctly on every intermediate scrollView, and if I remove that UILabel, it is removed from every scrollView shown.

So, can you please tell what is possible to do to show images on intermediate scrollView consistently?
Sorry if I am asking in a wrong place, if I do. I will move my question anywhere you need it to be.

(Another option suggested by Florian, author of Laker framework, is to handle this feature the other, more flexible way: get image to show on intermediate scrollView before page from the HTML code of that page - just like page title is taken now. While I find this solution much better indeed if feasible, I also understand it is much more time-consuming).

**Comment by folletto** [comment]
Hi Anton, it's a feature that is going to be out of the box in the upcoming Baker 3.0, and currently you can test it from the master repository here on GitHub.

Baker 3.0 implement the Hpub format 1.0 fully, so you'll be able to use the book.json syntax to specify these things. Check the two wiki pages here:
https://github.com/Simbul/baker/wiki/hpub-specification
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

**Comment by antonsukhonosenko** [comment]
Thanks Davide, that helped me a lot!
And, as I understand, no per-page -baker-background-image-\* parameter planned?

**Comment by folletto** [comment]
I asked another user to create it to give proper credit, but I guess I have to create it... created: Issue #175.

So, yes, it's planned in 3.1. :)

**Comment by antonsukhonosenko** [comment]
Thanks, great!
