### ISSUE TITLE
Release 3.0 documentation

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#172]
1. Website
   - Homepage copy
   - Homepage screenshots
   - Changelog page
2. Tutorials:
   - Basic (site)
   - book.json (site)
   - How to package for downloads and book:// (wiki)
   - How to manage links (wiki)
3. Zip
   - Baker 3.0
   - Demo book
4. PR
   - Email
   - Tweet

**Comment by Virtualsweden** [comment]
Now this is a good sign :-)

**Comment by folletto** [comment]
;)

**Comment by folletto** [comment]
Going live... :)

**Comment by folletto** [comment]
...and done. :)

We are just missing a wiki page about how to package for downloads, but it's something we can prepare in the following days. :)

**Comment by Virtualsweden** [comment]
Woooo, well done !! :-)
