### ISSUE TITLE
Data storage format

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#173]
Hi guys,

I'm studying better the baker framework and I have a question.
Using some implementations of baker (like babylon ipad app) I see that the application save the issues begore downloaded.
Which kind of storage are these using?Web SQL Database ?

Thanks a lot

Goodbye

**Comment by folletto** [comment]
Baker uses just plain and standard HTML files. :)

**Comment by airtek** [comment]
How you can storage this data? In the file system?

Using a IOS Api?

Il 17/10/11 16.58, Davide Casali ha scritto:

> Baker uses just plain and standard HTML files. :)

## 

Pierpaolo Gulla

---

Email: airteknology@gmail.com
Cell: 3920091596
Skype: airteknology
Fax: 0698380501

**Comment by folletto** [comment]
If you test the hands-on tutorial you should understand better how it works, try it: http://bakerframework.com/tutorials/20/basic :)

**Comment by airtek** [comment]
Hi Davide.

thanks for your replies

Yes I have read the doc before.

I'm speaking about the application that download the hpub files from 
internet: later when the user reopen the app , will be the files that 
was downloaded.

I'm trying to understand which way/tecnology/api is used to memorize 
this big files.

Thanks a lot

Bye

Il 17/10/11 17.06, Davide Casali ha scritto:

> If you test the hands-on tutorial you should understand better how it works, try it: http://bakerframework.com/tutorials/20/basic :)

## 

Pierpaolo Gulla

---

Email: airteknology@gmail.com
Cell: 3920091596
Skype: airteknology
Fax: 0698380501

**Comment by folletto** [comment]
As before, it's just a file, exactly the ones you read in the Tutorial. :)

The only difference is that the downloaded ones are inside a single zip (renamed .hpub) in order to be downloaded. I suppose we need to clarify that part a bit more. :)
