### ISSUE TITLE
Insert PDF in webpages

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#174]
Hi guys,

trying to develop my little app with baker, I have a simple problem :
My magazine normal is a pdf , how I can insert it into a webpage? Is is possible to embed a single pdf ( maked of 1 page) in every html page ?
Thanks
Bye

**Comment by folletto** [comment]
If it's a PDF, Baker isn't your answer. You have to build a HTML5 publication to use Baker. :)

**Comment by airtek** [comment]
Oh yes.
I'm tryng to use svg in the html to render vectorial images.
I'm tryng some ways for do it,when ì found a solution i'll post here.
Do you have any experience or idea about this?
Thanks
goodbye

2011/10/17, Davide Casali
reply@reply.github.com:

> If it's a PDF, Baker isn't your answer. You have to build a HTML5
> publication to use Baker. :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Simbul/baker/issues/174#issuecomment-2431145

## 

Inviato dal mio dispositivo mobile
