### ISSUE TITLE
Per-page pre-built screenshots

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#175]
As an author I want to specify a cached screenshot for each page.

**Comment by folletto** [comment]
This is already partially implemented in 3.0 thanks to @Xm4s, check this commit: 7956e89bac366987468d3a98f4b0f885749c4ab5

**Comment by folletto** [comment]
We added a new flag to manage the folder containing the screenshots, `-baker-page-screenshots`, here more details:
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

**Comment by Xm4s** [comment]
Closed with commit ff0ed7aeff6a71e22c3fbe074de1066c4053852c
