### ISSUE TITLE
Open links in Safari?

### ISSUE THREAD

**Issue by viDU85** [Simbul/baker#176]
Hello,

When I touch in an external link (I´m use target="_blank" in my html file) the link is opened into my book. I want open the link in Safari. How Can I change this?

Thanks.

**Comment by folletto** [comment]
Hi!

What version of Baker are you using? :)

**Comment by andrewogi** [comment]
Hi! Try to use this, http://www.yourlink.com?referrer=Baker in a link tag

**Comment by viDU85** [comment]
Hi folletto,

I downloaded the latest version today. With the previous version I don't have any problem with the externals links.

Thanks for your help!

**Comment by viDU85** [comment]
Hi andrewogi, 

Your suggestion works, but when I return to my app the screen goes white. I´m use the "three-cards" rendering type.

**Comment by danielbenjamins** [comment]
Other question: is it possible to link to an app in the App Store without opening Safari?

**Comment by folletto** [comment]
This answer should be what you're looking for: http://stackoverflow.com/questions/1453711/reliably-opening-app-store-links-from-a-uiwebview :)

**Comment by andrewogi** [comment]
or u can simply use itms:// protocol instead of http://

upd: just tested, it can be achieved by link directly pointing to your app in App Store.
http://itunes.apple.com/ru/app/ibooks/id364709193?mt=8

with itms:// method iTunes will open for sec and then redirect you to App Store, it is good. Updated method perforable more.

**Comment by danielbenjamins** [comment]
Thanks for the info. I found out that it's the iPad Simulator who broke it, the link I created was ok :)

**Comment by folletto** [comment]
Nice. :)
