### ISSUE TITLE
Using SVG Images

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#177]
Hi Guys,

anybody have tried to use the svg image format?

I try without any good result.

I try with this sintax:

<object data="gfx/5.svg" width="1000" height="760" type="image/svg+xml" /> 

Or

<embed src="gfx/5.svg" type="image/svg+xml" width="1000px" height="760px"/>

Hi have done many research on the web and the same page viewed with safari are very good!!

The application starts but the page are blank and any images are rendered.

Thanks for the help
Goodbye

**Comment by airtek** [comment]
pasting of code isn't working right,I retry.

The first try was this:

```
  <object data="gfx/butterfly.svg" width="1000" height="760" type="image/svg+xml" /> 
```

The second was this 

```
<embed src="gfx/test-1.2-tiny.svg" type="image/svg+xml" width="1000px" height="760px"/>
```

Thanks goodbye

**Comment by folletto** [comment]
I did some tests, trying the two syntaxes you added on iOS 5:
1. The first one, renders, but CUTS anything on the page after that.
2. The second one, renders correctly.

**Comment by airtek** [comment]
Hi Davide, 

which kind of SVG you use for your tries?

**Comment by folletto** [comment]
I tried this one: http://cl.ly/2W280H3K3Z2d0K261D01

**Comment by airtek** [comment]
Yes this is rendering good.

I make some test and share the code.
Goodbye
