### ISSUE TITLE
using xhtml files

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#179]
Hi guys,

with baker is it possible to use file with xhtml extension?

I have tried byt baker don't find any page when I launch the application in the simulator!

Thanks a lot
Bye

**Comment by Simbul** [comment]
It is indeed possible, just tested with an example from [this page](http://www.javascriptkit.com/howto/xhtml_intro4.shtml).

If you're using 3.0, make sure you specify the name of your XHTML file in [book.json](http://bakerframework.com/tutorials/30/manifest).

**Comment by airtek** [comment]
Hi Simbul, 

I wa using the baker 2.0 now with 3.0 it's more simple to use xhtml

Thanks a lot

Goodbye

**Comment by Simbul** [comment]
Ah yes, 2.0 required HTML files, as Baker was reading them directly from the filesystem.
Glad to hear the issue is solved.
