### ISSUE TITLE
External URLs should be opened in the system's browser

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#18]
_As a user I want to be able to open external links in my browser_

**Comment by Xm4s** [comment]
Done in the commit https://github.com/Simbul/baker/commit/1b4e509c295a5e53747880c47fafd1a2b5f325d6

A test with the actual device is welcome before closing this issue :)

**Comment by jeffehobbs** [comment]
Works great for me. It would be really useful to keep this flexible to all the user to launch out to the other iOS custom URL schemes, but this is a tremendous first step. Thanks so much!

**Comment by folletto** [comment]
I think that already does that! We filter out just file:// :D

**Comment by jeffehobbs** [comment]
Yep, just tested with Twitter's "tweetie:" custom URL scheme and it worked just as you'd hope. Cool!

**Comment by Xm4s** [comment]
Ok, I'm closing this up.
Thanks for the help Jeff :D
