### ISSUE TITLE
Baker 3.0 and Newsstand

### ISSUE THREAD

**Issue by mehlwurm** [Simbul/baker#180]
Hi,
i will try to make a small magazine about gaming. I was using Baker 2.0 and it works fine in the simulator. But i will have my app in the newsstand, is there a way to use Baker for it? What did i need to bring the app to the newsstand? I hear about a notifiaction server. Is there a framework or something what i can use or did i write my own server with the service. And how is it with the Newsstand Kit, is this integrate in Baker? Can i also create a Newsstand App Icon?

I will really happy if somebody can help me.

thx
mehli

**Comment by folletto** [comment]
Hi!

The Newsstand integration is a feature already requested, we are going to look into it for the next 3.1 release. Follow the Issue #100 for updates and feedback. :)

If you're able to developer that feature yourself and help us to do that, that would be awesome too. ;)

**Comment by mehlwurm** [comment]
Thanks, im an developer - so i look for the Newsstand Kit and try something. But maybe u have a date for the 3.1 release?

**Comment by folletto** [comment]
Nope, we just released the 3.0, and it's hard to tell when that is going to be released. :)

However, if you start working, just keep us updated using the issue above. :)
