### ISSUE TITLE
OhmyGod magazine whit baker ready to download

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#181]
http://itunes.apple.com/us/app/ohmygod00/id472971950?l=es&ls=1&mt=8

OhmyGOD is a brand new magazine about gay life-style, culture and interests. Plunge into a wide range of contents, including: art, photography, fashion, and people around the world. OhmyGOD tablet version is born to become a reference magazine for modern gay men.

---

thanks a lot baker team

**Comment by k8fisher** [comment]
Cool, look forward to checking out your magazine to see how it works. Great news!

**Comment by lozich** [comment]
wow! I'll download it NOW! 

Looks like nice!

**Comment by folletto** [comment]
Very nice! :)

It might be able to make it to the showcase. :)
We'll close this issue, keeping open issue #186 until we do the check. :)
