### ISSUE TITLE
iOS4 working problem: spinner.color

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#182]
in RootViewController.m's initPageDetails

```
spinner.color = foregroundColor;
```

which is only available for iOS5 or above SDK.

**Comment by MrSpukhaus** [comment]
It is a real show stopper. As long as this is in the sample book, people < iOS5 might not get it to run on the iPad without removing it. So, below iOS5 devices I would call it "a bug".

**Comment by zenz** [comment]
it's a bug if the Readme told that it's working with iOS4.

but the solution is quite simple, just add a condition like:

```
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 5.0) { 
        spinner.color = foregroundColor;
    }
```

This can make Baker3 working with iOS4 just without the spinner.

**Comment by folletto** [comment]
We'll check. :)

**Comment by hyoungielpark** [comment]
Hello zenz.. 

Interesting, but I think it won't work becuz  the code is still in there.. :D
Why don't you erase the line ?

**Comment by airtek** [comment]
I have tried 

inserting the condition

if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 5.0) { 
        spinner.color = foregroundColor;
    }
but I have the same error...

**Comment by airtek** [comment]
I only comment the line and now I can compile...
