### ISSUE TITLE
Prepare graphic assets for 4.0

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#183]
Issue to track the graphic assets for shelf: background images mainly.

WAS:

> Change demo book to HTML5 download shelf
> 
> Instead of the current Study in Scarlet book:
> 1. Prepare a HTML5 shelf to be the new default book.
> 2. The shelf will have links to demo books.
> 3. You can download the books.

**Comment by davidex** [comment]
I found this CSS3 shelf, it can be a good starting point - of course coupled with an automatic thumbnail generation: http://www.steveworkman.com/bookshelf/

**Comment by Simbul** [comment]
We will probably go for something simpler, at least as a first implementation. Thanks for pointing that out though.

**Comment by zenz** [comment]
My Opinion, the shelf function is very important, but should always make the book reading function in the first position.
I mean the shelf should not be a page of a book which will disturb the reading.

How about display the shelf use some gesture like pinch-in? just like double tap to bring up the navigation bar(index view).
then, you can do anything in the popup view or window.

**Comment by folletto** [comment]
I think you're talking about Issue #20. :)
This Issue refers to a demo page to show how downloaded books work. :)

**Comment by folletto** [comment]
The new assets for `shelf` are in, but we have to update them on iPhone since for now it's iPad only. This is now closely related to issue #519.

**Comment by tekdope** [comment]
Let me know if you need a designer to get some work done. I would be very happy to help.

**Comment by Simbul** [comment]
Hi @nin9creative,
that's an issue we noticed as well, but we haven't had time to address it yet.

The `UIImage` that contains the cover is 135x180px. If you use the same exact size for the png, the result is not that bad. This does not make full use of the retina display though, which is why we want to fix it (doubling the size of the png actually makes it worse).

If you manage to code a solution before we come round to it, a pull request would be much appreciated ;)

**Comment by folletto** [comment]
Hi @nin9creative I don't want to look too annoying but... could you open a separate issue for that? This was to track the in-app assets (background, icons, etc). :)

–

On the other side, I think the problem is somewhere in the code that takes the image at "base resolution" and scales it regardless if it's retina or not. It looks like the image is first read and resized at a "standard" resolution and then scaled up for retina, where the first scaling obliterates any advantage of using a higher-resolution image. That's however my guess... it might be something in the grid component  we are using, or some code that's missing, I don't know.

**Comment by folletto** [comment]
The assets are now done. :)
