### ISSUE TITLE
Using matchmedia to test the orientation of the ipad

### ISSUE THREAD

**Issue by k8fisher** [Simbul/baker#184]
Hi
Im trying to create a publication which makes use of matchMedia to switch between portrait and landscape versions of pages. Im using matchMedia and listeners, along the lines of...

var mql = window.matchMedia("(orientation: portrait)");  
mql.addListener(handleOrientationChange);  
handleOrientationChange(mql); 

function handleOrientationChange(mql) {  
   if (mql.matches) {  
      top.location.href="portraitVersion.html;"
    } else {  
      top.location.href="landscapeVersion.html;" 
         }  
   }  

I dont see any change in page layout when running this on an ipad, is there any reason why matchMedia isnt firing when the ipad is rotated? I need to use javascript rather than css to as the pages (jpgs) need to have imagemaps assigned to them.

Any thoughts on detecting orientation change and switching page very much welcome. Unfortunately I _have_ to change web page rather than use css to stretch the jpg to fit the orientation :/

Kate

**Comment by folletto** [comment]
I don't know matchMedia so I can't really tell, however... if you are going to the extent of creating two pages, why don't you put BOTH the image maps on the page and use CSS to show / hide them? This will result in only one page with both and probably will spare you also time to manage only one page. :)

**Comment by k8fisher** [comment]
Hi, 
yeah that was my first thought but having two layers 768x1024 and 1024x1488 in one html page causes the body of the page to stay at 1024x1488 (so when the portrit version of the page is showing youve scroll bars and white space where the larger layer is sitting "hidden". Not sure if thats a ipad only situation or universally true but it pushed me to look at creating two seperate pages.

What method dyou use to check orientation / a change in the orientation?

**Comment by folletto** [comment]
Check the latest demo book: the CSS there should be correctly working for portrait and landscape.

However, it's strange, because items with display: none; shouldn't count for the page size. Did you try that or were you using some other CSS? :)

**Comment by k8fisher** [comment]
aah i set visibility:hidden and set the height of the layer to 0px I will definitely try display:none; and will check out the demo book. Thank you for your super speedy response.
Kate

**Comment by k8fisher** [comment]
Heck! thank you that worked perfectly.

**Comment by folletto** [comment]
Wonderful :)

The difference is that visibility keeps the item on the page, just hides it, while display removes it from the page entirely. :)
