### ISSUE TITLE
Has anyone got an App Store app using 3.0?

### ISSUE THREAD

**Issue by dixiepnum** [Simbul/baker#186]
Would like to see an example on my ipad of a 3.0 product...

Thanks!

**Comment by mutador** [comment]
http://www.omgod.es/app/

http://itunes.apple.com/us/app/ohmygod00/id472971950?l=es&ls=1&mt=8

**Comment by rhoulay** [comment]
OhmyGod magazine has problem on my iPad 1, it's crash aways...

**Comment by mutador** [comment]
blameto  the baker ... Joking, I think it's a memory problem, I've downloaded again and I do well, but my iphone1 is 64gb  , the magazine that we are following up we had to make with the system " three cards " that could not stand the i weight to crash all the time, I guess it's a problem of how to manage memory the ipad and what I read in other post baker people know this but it should be easy to fix ....

I hope the system will solve all three cards.

a question? spoils you forever in the same place? closes the app ? remains hookup?

**Comment by folletto** [comment]
Could you please give us more details on the crashes in Issue #199? Thanks! :)

**Comment by rhoulay** [comment]
It's just crash.

OhmyGod run well when I first download it. 
When it's crash first time, it will no longer running. Every time open magazine, it will show at laster page, and  scrolling to other page will crash, use indexView will crash too...

Close app, and reset iPad same.
