### ISSUE TITLE
Itouch 1 - iOS 4.2/iOS4.3 problems to deploy

### ISSUE THREAD

**Issue by marciosm** [Simbul/baker#187]
Hi there. I was using Laker framework to create an ebook, deploy, etc. Since I upgraded my xcode to 4.2 with iOS 5 support, and changed the framework to Baker 3.0 , I have not been able to deploy my app to my itouch. I'm a newbie developer and I do not know what is happening. Using an Ipad 2 with iOS 5, it works fine. Both devices are registered as developer devices with authorization and so on. Anybody has the same problem? Even tests the XCode say that are not configured to run. Do I have to change something about architecture, arm7, arm6 processors, etc? Or is it more simple than that? Thanks a lot :)
PS: I already solved the problem of spinners running on iOS 4.3 simulators with the IF sentence as explained on another issue. Tks.

**Comment by folletto** [comment]
Well, Baker 3.0 is built for iOS5, so that might be a problem. ;)

That said however, it's difficult to tell without any information from you about the error you're getting, the log file or at least something to try to pinpoint the problem. :)

Could you add more details? :)

**Comment by marciosm** [comment]
You can see the logs at www.marciomorais.com.br/baker/logs.zip . The build is done alright. The problem is that the app is not installed on device. I took so long to reply because I was restoring the device to beginning and installing everything again. It's fine with Apple, but I guess that the problem is with Xcode 4.2 as I can't install any other project there. I was reading about the correct name of project (no spaces, no underlines) and to include i386 with armv6 and armv7 ... I tried it all. The Xcode just do not publish the project on my itouch with iOS 4.2.1. And as it it's 2o generation I think that I will need to buy another one more recent. I'm really upset and angry because the iOS Simulator 4.2 and 4.3 works fine on XCode. I appreciate any help, but I really don't know if it will be possible for you to recreate this kind of problem as it's appears to be a matter of old device... Well thanks a lot for any efforts. Best, Marcio

**Comment by marciosm** [comment]
PS: the provisioning profiles are allright as well. itouchtest and ios team provisioning. The console has a message about not be able to use the usb connection:
Tue Oct 25 06:52:19 ComputerMarcio lockdownd[16] <Error>: 2ffea000 handle_connection: Could not receive USB message #8 from MDCrashReportTool. Killing connection

Tue Oct 25 06:52:19 ComputerMarcio com.apple.mobile.lockdown[16] <Notice>: Could not receive size of message

Tue Oct 25 07:17:28 ComputerMarcio lockdownd[16] <Error>: 2ff68000 handle_connection: Could not receive USB message #6 from MDCrashReportTool. Killing connection

Tue Oct 25 07:17:28 ComputerMarcio com.apple.mobile.lockdown[16] <Notice>: Could not receive size of message

Tue Oct 25 07:17:28 ComputerMarcio com.apple.mobile.lockdown[16] <Notice>: Could not receive size of message

Tue Oct 25 07:17:28 ComputerMarcio lockdownd[16] <Error>: 2ff68000 handle_connection: Could not receive USB message #8 from MDCrashReportTool. Killing connection

**Comment by folletto** [comment]
Ach, that sounds like a very tricky problem. :(
Did you try another iPod Touch device? Maybe a friend's one?

I'm afraid I can't help much on that...

**Comment by marciosm** [comment]
Hi. Thanks for your help. I still can not be able to run the project on my itouch, but it worked fine on any other device with iOS5 that I tried. I will just let it go the idea of 4.3 and below devices for now. If I discover what is happening with my old device I will post it, ok? All the best. Marcio :)

**Comment by joshbaltzell** [comment]
It's possible these settings were your issue. I had to manually add the "armv6" setting to make it work on an old iPod touch. But it runs so poorly that I think I am going to avoid it altogether. 

http://stackoverflow.com/questions/4198676/warning-iphone-apps-should-include-an-armv6-architecture-even-with-build-config
