### ISSUE TITLE
Which SDK?

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#189]
Which SDK should I choose to make my (very simple) app compatible with an iPhone 3 (which supports iOS 4.2.1 max)?
In other words: which 'oldest' SDK does Baker support?

**Comment by Xm4s** [comment]
The latest version on Baker here on GitHub should compile with both 4.3 and 5.0 SDK and run fine on all the iOS Device >= 4.0 (at least the 4.3 ones, testing on older device is really appreciated :P)

As you may be aware there were a little problem on the spinners, but it should have been solved yesterday. Check out the latest version of the repo and give it a go :)
