### ISSUE TITLE
Zoom the HTML content

### ISSUE THREAD

**Issue by segundoseis** [Simbul/baker#19]
As a user I would love to zoom the content with a double tap.
Similar to how Safari works.

**Comment by folletto** [comment]
Could you specify the reason? The zooming is something we removed on purpose in order to give precise control to the book creators on how it looks like. :)

**Comment by segundoseis** [comment]
I understand ..
Just what I was thinking to make the journal more accessible.
I understand that I could change in the css the fontsize in the html itself .. but it would be very inconvenient to have to change it on every page.
Perhaps with a native configuration option we can keep a trademark for the application to load a new css with font size changes or a new accessible design.

**Comment by folletto** [comment]
You can, and I think you can also set a cookie to handle the size on multiple pages. But we need to try it out. :)

**Comment by segundoseis** [comment]
I'll look :-)

**Comment by segundoseis** [comment]
It seems that no written cookies in the app.  :-(
Any ideas?

**Comment by folletto** [comment]
I think that the ability to save data is important for this kind of app. Maybe is it possible to use the HTML5 database?

Otherwise I suppose we need to implement some kind of storage...

**Comment by bru** [comment]
It seems like this discussion could be split into two: 
. how to build / allow for accessible CSS(s) in baker 

. how to manage settings

**Comment by nikos** [comment]
I can understand the restriction to use a fixed width for the pages, but on the other hand there are special use-cases where it might make sense, two use-cases regarding zooming-in coming to my mind are:
- The content producers have an image map (for example ecatalog) which is hard to locate for detailed objects and therefore zooming helps to select the element
- A user would like to see details of high-quality photos in an magazine

Would it be possible to allow on a per div or img element base whether the user is allowed to zoom-in or not (default) ?

**Comment by folletto** [comment]
I think that's doable in HTML, exactly what happens in websites today, no? :)

**Comment by yu12** [comment]
I'd like to have the zooming feature since it allows readers to control their own preference.

**Comment by andreacampi** [comment]
FWIW, I just tried using HTML5 storage within a Baker book and it worked flawlessly :)

**Comment by folletto** [comment]
Excellent. :D

Do you mean localStorage, right? :)

**Comment by andreacampi** [comment]
Yeah, that's the one :)

**Comment by folletto** [comment]
We landed a constant in master branch to turn zoom on.
It's still NOT recommended, but it's there. Also it require a change in the HTML head element of each page.

As an author, you can. Please, use it only if you are absolutely sure. ;)
