### ISSUE TITLE
Issue when compiling in iOS 4.3 with Baker 3.0

### ISSUE THREAD

**Issue by TonyRen9825** [Simbul/baker#190]
Both iPhone and iPad. 

When processing RootViewController.m, it prompts: 
        spinner.color = foregroundColor;                    Thread 1: Program received signal: "SIGABRT"

Things work well in iOS 5.0.

**Comment by Simbul** [comment]
This was discussed and solved in issue #182. Closing for now, please feel free to repoen if the fix doesn't work for you.
