### ISSUE TITLE
Error with compiling Baker 3.0

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#193]
Hi guys,

I'm trying new baker, when I compile I have this 2 errors:

/Users/pierpaologulla/Downloads/baker-framework-3.0/Classes/RootViewController.m:246: error: request for member 'color' in something not a structure or union

file://localhost/Users/pierpaologulla/Downloads/baker-framework-3.0/Classes/RootViewController.m: error: Semantic Issue: Property 'color' not found on object of type 'UIActivityIndicatorView *'

What do you think?

Thanks a lot

Bye

**Comment by Simbul** [comment]
This is likely to be the same error pointed out in #182.

**Comment by airtek** [comment]
Thanks a lot
I try and report

2011/10/28 Alessandro Morandi <
reply@reply.github.com>
