### ISSUE TITLE
Newsstand & Publishing

### ISSUE THREAD

**Issue by b19rok** [Simbul/baker#194]
Hi guys,

We're int the final stages of building a baker magazine publication. The whole thing functions really well within the Newsstand using the simple guidelines provided by Apple. The only issue we have is getting each issue to cache locally (for multiple issues) and add support for in-app purchases. I know the local storage was covered a while back but we're looking at implementing a really basic setup based on the WWDC lecture on offline storage that will store the files locally and check for updates. We won't be adding the ability to select/delete local issues just yet. How far off is 4.0?

**Comment by folletto** [comment]
We just released the 3.0... the 4.0 might be quite far off at this point, if of course no other developers come in.

For simplicity purposes, I think that your request is Issue #20, right? :)
If that's the case, I can rename this one to be the one to check for in-app purchases - as that's missing. :)

**Comment by b19rok** [comment]
Thanks for the quick reply :)

Yeah that thread looks like it's been dead for a while though... I think we'll push a head and try to implement this system using Apple's offline storage guidelines for web apps. I'll post any successful code here. I just have 2 Quick questions:
1. Can we link to a local file using: local:// or something similar
2. Is it possible to wrap 'baker' using Phonegap? I know it sounds silly but we already have in-app purchases working thanks to the clever "InAppPurchaseManager" by ascorbic.

**Comment by folletto** [comment]
Unfortunately at this time I personally don't have an answer to these two questions. I guess that's "no" to both (because you are trying to access the private Document folder and because Baker is an app and not a library at this time), but it's just a guess, you might want to dig deeper. :)

**Comment by folletto** [comment]
Ok, from a quick test local:// is really file://, and however it's the same of just specifying a relative path, since file:// will require an absolute path and that will be quite hard on the sandboxed iOS environment.
