### ISSUE TITLE
Device Orientation

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#195]
Hi guys,

with baker we can "block" the orientation of an App. But there is the possibility to check the real orientation of the device, and if is different from the "default" of baker show a message to the user , something like "Wrong orientation, turn right the device"

Thanks a lot

Goodbye

**Comment by folletto** [comment]
Uhm I don't get the need of this: if the book supports only one alignment it will show up in that way: the user will simply turn the device. :)

No? Am I missing something? :)

**Comment by sangshuduo** [comment]
sometimes, user may use portrait mode with one column but use landscape mode with two columns to read, I saw some magazine app does. It's nice to have in Baker if possible.

**Comment by folletto** [comment]
Sure, just use the CSS media queries to re-compose your pages. :)

**Comment by airtek** [comment]
any ideas for implementing it?

**Comment by folletto** [comment]
Yes, look up for any tutorial on CSS `media queries`. :)

**Comment by airtek** [comment]
I'm speaking about the possibility to check the device orientation with
Javascript or similar...

**Comment by folletto** [comment]
I'm sorry, but I was thinking that you were referring to the same thing as the above where you wanted to just display a message. That's something done by `media-queries`.

For the orientation in JavaScript you can, as everything, check the HTML5 documentation, specifically `window.orientation` and `window.onorientationchange`. You'll find plenty of information on the web. :)

**Comment by airtek** [comment]
Thanks Davide,

I'll update the thread with information that I found

Goodbye

2012/9/11 Davide Casali notifications@github.com
