### ISSUE TITLE
Update Laker from Baker 2.0 to Baker 3.0?

### ISSUE THREAD

**Issue by Paul-B** [Simbul/baker#196]
I want to upgrade my book that I created with Laker 1.1, based on Baker 2.0 to Baker 3.0.
Of course I do not want to avoid loosing my work so I am now going to experiment with dropping the Baker 3.0 files into my Laker 1.0 directory.
Can somebody point me out what files NOT to copy over? I will start by leaving my .xcodeproj file intact but I can imagine there are more that I should not touch.
Any upgrade advice much appreciated.

**Comment by folletto** [comment]
You should do the reverse: copy your Laker book/ folder inside Baker 3.0 book/ folder, and update what's necessary. You shouldn't touch anything from Baker 3.0 :)

Notice that some things are different, for example Baker 3.0 now uses "index.html" to render the menu. :)

**Comment by Paul-B** [comment]
Smart move :) Thank you!
Move complete. No errors. I get a the loading screen, but after that only black. Looking for what is wrong...
-Update: Baker to Laker or Laker to Baker, both are unsuccessful. If I can't crack it I think I have no choice but to give up and wait for an update to Laker. No problem, I can live with the great result that it already gives and enjoy any future update.
If I somehow get it working I'll post that here.

**Comment by folletto** [comment]
I did some tests. :)

Converting Laker 1.1 to Baker 3.0 is quite straightforward:
1. Download Laker 1.1 and Baker 3.0, unzip them
2. Take the book/ folder from Laker 1.1 and put it in Baker 3.0
3. Rename "navigation.htm" to "index.html"
4. Copy the whole content of "toc.html" inside "index.html" **replacing** line 57 (div id includeTOC...)
5. **Add book.json** following the Hpub specifications
6. For the index to work correctly, add to book.json -baker-index-height = 200

That's it. It could probably be cleaned up a bit more, but in this way it should work. :)

**Comment by k8fisher** [comment]
Is it possible to clarify points 5 and 6. 
Add book.json following the Hpub specifications
For the index to work correctly, add to book.json -baker-index-height = 200

Also is there anyway to make the table of contents show with a single click rather a double click? Im running Xcode 4 with ios 4 SDK at the moment.

**Comment by folletto** [comment]
Uhm the latest Xcode release is 4.2. We support that one. :)

**Comment by k8fisher** [comment]
Once Ive updated to ios5 is it possible to set up the table of contents to show with a single click rather a double click? 

Apologies I changed my question between you reading my question and responding.

Kate

**Comment by folletto** [comment]
Points 5 and 6 are how publications in Baker 3 are handled: Hpub. Read the specification from the wiki or the tutorial:
Tutorial: http://bakerframework.com/tutorials/30/manifest
Wiki: https://github.com/Simbul/baker/wiki/hpub-specification

For the single click, it's not possible, because:
1. Every publication out there uses double-tap
2. Single tap is used to trigger buttons and links

So we're not going to implement it, but feel free to implement it yourself. :)

**Comment by nin9creative** [comment]
This went pretty well for me, however I did it before I saw this post :)

**Comment by nin9creative** [comment]
Has anyone noticed any "stuttering" type effects when swiping side to side or scrolling up and down with Baker 3 and Laker 1.1?  

I can't really put a finger on why it's doing it.  I'm on an iPad2 and it just seems to not be very smooth.  It hangs for a few seconds every once and a while etc.  Curious to see if anyone else had noticed such behavior?

**Comment by barrytallis** [comment]
I'm trying to find out what the differences between Baker 3.0 and Laker 1.1 (which contains baker 2.0).  Whats the pros/cons of one versus the other.  Can I assume that Baker 3.0 has incorporated some of the features/suggestions of Laker?  BTW - great frameworks and I'm working on an interactive fitness book with this framework.  Just need to be 100% confident of the framework to start with.

**Comment by folletto** [comment]
Baker 3.0 incorporates all the changes from Laker and more.
Now, from Laker the only parts you need are the ones inside book/, that needs to be adapted (as you can read above) to work with Baker 3.0. :)

Cheers! :)

**Comment by barrytallis** [comment]
Thank you for your prompt and helpful response.  Moving foward with Baker 3.0 then.

**Comment by Paul-B** [comment]
I finished conversion from Laker 1.1 to Baker 3.0.2 as guided by Folletto (tnx!!) and can confirm that it is totally worth the effort of your trouble. The main advantage to me is the fact that it loads quicker and that there now is an option to allow the pages of the previous and the next dossiers to pre-load. This greatly increases the feel of speed.
For the future my most anticipated feature will be in-app purchases, I hope that will arrive soon.

**Comment by xiripi** [comment]
I Already make all as Folleto said but i can run the project on iso. Anyone can send me the book conversion for baker 3 to vhangelo@gmail.com. thanks

**Comment by folletto** [comment]
Laker has been updated to version 1.2 with full Baker 3.0 support by the awesome @ffranke. :)

More info here: http://www.lakercompendium.com/2011/12/27/laker-1-2-and-a-few-notes/
