### ISSUE TITLE
Download: idleTimerDisabled = YES

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#197]
Normally those eBooks are large, but even it's small,  if the download time exceed the idle time, download will fail. So I would like to suggest disabling the Idle time while downloading books.
After download finished, just enable the Idle time again.

**Comment by folletto** [comment]
Uhm I never encountered the idle time in my tests (and there's no such a thing in our code, afaik), what does it happen?

**Comment by zenz** [comment]
Perhaps I didn't explain it very well.
Think about some magazine is about 20M, and your wireless connection speed is only 56kbps...
Normally you won't touch the iPad to make it keep away from idle. if you forget to do it. and the iPad reached it's idle time, then the iPad will turn off the screen, turn off wifi......
Then the download process will be terminated. you have to download it again.

Is this clear?
So I suggested that before download process start, we use some code to avoid the iPad auto idle like this
[UIApplication sharedApplication].idleTimerDisabled = YES;

then when download finished, we can enable the idle again.

**Comment by folletto** [comment]
Yup, as I said we downloaded even bigger Hpubs but we never encountered that problem. Now it's clear, we'll check it out, thanks. :)
