### ISSUE TITLE
Orientation of pages

### ISSUE THREAD

**Issue by svdgraaf** [Simbul/baker#2]
I need orientation of pages for a project. We discussed the best way to do this was to start supporting the media query, and let UIWebView figure out which version to load after a rotation.

I'll start working on this.

**Comment by svdgraaf** [comment]
oh, and if anyone else has any specific concerns or ideas to add, please let me know

**Comment by folletto** [comment]
Great Sander, this topic is your house then for the discussions on that feature. ;)

**Comment by svdgraaf** [comment]
pull request is available:
https://github.com/Simbul/baker/pull/6

**Comment by Xm4s** [comment]
Duplicated issue, discussion continue on https://github.com/Simbul/baker/issues#issue/6
