### ISSUE TITLE
can't use chinese character in html file

### ISSUE THREAD

**Issue by sufei** [Simbul/baker#202]
When I generate ebook, if there is Chinese character in my html file, the app will "terminate called after throwing an instance of 'NSException'", what shall I do to generate a Chinese book?   

Thanks very much !

**Comment by folletto** [comment]
Could you please provide an example Hpub book to test? :)

**Comment by sufei** [comment]
Sure!

 I download the sample from http://bakerframework.com/, compile and run correctly. Then I added  "你好" in the first sentence of part1-01.html, then the app can't run.  

  In the Hyphenator.js, I can't find the supported language, is the reason for it?

 Thank you very much!

**Comment by zenz** [comment]
It must be your problem.
We are just released a Chinese book using baker3 framework.
There's a lot of Chinese characters.
http://itunes.apple.com/cn/app/id476520123?mt=8

Please check your program.

**Comment by folletto** [comment]
I just did the test above: I took the sample book, added `你好` and it works, even if it doesn't display the characters correctly.
To display the characters correctly I had to add `<meta charset="UTF-8">`, and with that works as well.

What are you using to edit? Are you using Xcode? Or another editor? It might be a problem of encoding when saving the file itself.
