### ISSUE TITLE
Portrait or landscape only?

### ISSUE THREAD

**Issue by mikadonguyen** [Simbul/baker#203]
I wanna config Baker with only Portrait version
I use lock Landscape or Portrait in Xcode 4.2 but when Baker run on ipad, landscape still active

Can you help me config it use only Portrait version?

Thanks

**Comment by zenz** [comment]
modify book.json

"orientation": "portrait",

**Comment by mikadonguyen** [comment]
thank so much @zenz
do you use Laker Magazine (core Baker), so I wanna use only portrait version but I dont find book.json
can you help me!

**Comment by zenz** [comment]
Normally it's included in baker's source code? in the book directory.

**Comment by mikadonguyen** [comment]
oh I found it  (for Laker source)
file "RootViewController.m" and edit here 
#define AVAILABLE_ORIENTATION @"Portrait"

**Comment by folletto** [comment]
@Mika are you using Laker? Laker uses an old version of Baker (2.0) that's why you couldn't find book.json. :)

**Comment by mika** [comment]
I'm not involved here (you got the wrong Mika ;)), pinging @MikaDo0211 therefore.

**Comment by folletto** [comment]
Wow! I didn't know that using @ references created also notifications! Sorry! :)

**Comment by mika** [comment]
@folletto - hehe, no problem :)

**Comment by mikadonguyen** [comment]
@mika i dont know, config in Baker @zenz help me, and i found file config for Laker , and I shared it :D
