### ISSUE TITLE
screenshots mode too slow on iPad1

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#204]
I found that the screenshots mode runs too slow on iPad1, but it's ok for iPad2.
So I make a fall back to three-cards mode if the hardware is iPad1 like this:

```
// ****** RENDERING
renderingType = [[[properties get:@"-baker-rendering", nil] retain] autorelease];
BOOL isIPad2 = (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad &&
                [UIImagePickerController isSourceTypeAvailable: UIImagePickerControllerSourceTypeCamera]);
if(!isIPad2){
    renderingType = @"three-cards";
}
```

**Comment by mutador** [comment]
If this is so, it would be good to include in the default option
book.json

something like

  "-baker-rendering-ipad1": "three-cards",
  "-baker-rendering-ipad2": "three-cards",

more flexible than change the framework xcode

**Comment by folletto** [comment]
That's strange. In none of our tests resulted in three-cards being lighter than screenshots. Could you give us an example?

**Comment by zenz** [comment]
Because my book is based on Laker's design, so may be you can use Laker's book for a test? 
Let me explain the situation what I met.
When selected "three-cards", although it will shows a black screen with page title, but we all understand it's loading, so we don't mind it.
But when selected "screenshots", on iPad1, it will brings a grey screen without anything for about 1 second to load the screen shots. I think that's not so good for the reader.

**Comment by mutador** [comment]
my experience
lakers doesn´t work fine whit baker now, i´ts a problem of the scripts, the include of the html is the most bad. i decided no use because this....you can try to delete the js and tell us your new experience abut it ( can my english be more bad, i say yes....)

**Comment by folletto** [comment]
As explained in the Laker topic, I did a quick conversion to adapt Laker and it worked for me, but indeed, it was built for Baker 2.0, not 3.0.

@zenz: just to be completely sure: did you clean up everything, deleted the app and all before doing the test? Because in theory screenshots should work the other way: you should see the screenshot for about 1 second before the HTML is loaded... Could you check? :)

**Comment by zenz** [comment]
dear folletto, I did remove the app first then make clean and make run again. but the same situation.
perhaps it's the laker's problem, but on my iPad2, it worked quite well. so I cannot agree that's the problem laker brings to me.

**Comment by folletto** [comment]
...on the other side, I can't reproduce it, so we're stuck. :P

**Comment by zenz** [comment]
This is not very important. I just write down my solution when I hit this situation, if you cannot re-produce it, then just ignore it right now.

**Comment by zenz** [comment]
I cannot re-produce this with the new version, so close it.
