### ISSUE TITLE
Magazine Grid  layouts  for the iPad  by http://asidemag.com/

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#205]
http://asidemag.com/grid/

Runs very well whit baker

**Comment by folletto** [comment]
Thanks! That's good to know. :)

I think everything specially designed for iPad and iPhone should work marvels with Baker, however there might be slight differences and it's great to get this feedback. :D

**Comment by nin9creative** [comment]
Is there a bunch of different layouts?  Or just one grid layout?

**Comment by barrytallis** [comment]
Its a css grid framework designed around magazine layouts.  There are no templates for you to use, but it is very easy to create nice layouts by calling the different grid classes.  Check out their examples.  I'm using it in my Baker HTML5 books.

**Comment by folletto** [comment]
I'm cleaning up the issue tracker. So I'll close this old discussion. :)
