### ISSUE TITLE
How to use the -baker-page-screenshots extension parameter?

### ISSUE THREAD

**Issue by palianah** [Simbul/baker#206]
Hello,

i read in the Wiki using the "-baker-page-screenshots" parameter you can show screenshots for each page before showing the Page.
But how do you use it actually? I tried this Parameter on the book.json file like the other Parameters, but it didn't work.

i tried like "book/screenshots/" or "book/screenshots" or.. "screenshots/" and "screenshots" (screenshots is my folder to the images) 

I named the images like it's explained on the Wiki. 

Do you have to make the rendering-mode to screenshot/screenshots?

Please help me, 

if this is possible actually or it's a feature for the future Version :) ( I am using the 3.02 Version)

**Comment by folletto** [comment]
All the page on the Wiki refer to the MASTER from GitHub, not the released version (3.0 currently).

That parameter was implemented in Issue #175, and will be released with Baker 3.1. :)

**Comment by palianah** [comment]
ok thanks for the fast answer! :)

**Comment by nruffilo** [comment]
Any idea when 3.1 will be available?  Is this available in the current source?

**Comment by folletto** [comment]
Yes, it's available in the current master, in development, source. No release date yet for 3.1, we are trying to clean up a bit more the source before release. :)
