### ISSUE TITLE
Jplayer continues playing after moving to next page

### ISSUE THREAD

**Issue by lostinjapan** [Simbul/baker#207]
I am using jplayer and have three cards turned on in the latest release of Baker. 

When I play the audio and then move to the next page, the audio does not stop. I heard it is issue #122.

Is there some javascript or event listener I can use so that when the user goes to the next page, the audio is stopped?

Thanks in advance!

**Comment by folletto** [comment]
At this time there isn't a call for that, the only thing I might suggest you is to use the screenshot mode right now.

**Comment by lostinjapan** [comment]
I noticed something very odd. We have jplayer on the first 3 pages of our book with the same code, but the audio on page 1 and page 3 stop when you swipe to another page. It is only page 2 (between pages 1 and 3) that continues. 

I have no idea why that page responds differently, but here is my book order:

pg4(no jplayer)  -  pg3(jplayer)  -  pg2(jplayer)  -  pg1(jplayer) - cover(no jplayer)

This is a "backwards" Japanese book, so that is why the order is reversed from what you would expect. 

My code for jplayer is the code in laker 2.0.

**Comment by folletto** [comment]
That's not odd: three-pages works that way: pre-loads page +1 and page -1 from the page you're looking, so when the page with the video is two steps behind... is shut down. :)

Couldn't you use the screenshots mode? :)

**Comment by lostinjapan** [comment]
Really? I believe you. I can't quite get my head wrapped around it, though.

If I start on pg1 (with jplayer) and press play and then swipe left or right, the audio stops. 
Same with pg3

If I load pg2(identical to pg1 and pg3) and start jplayer and then swipe left or right, jplayer continues.

Thank you for the reply :) I will try screenshot mode when I get back to the office tomorrow.

**Comment by folletto** [comment]
Uhm ok, no then there's something I don't get either. I should see a demo book, if you're able to produce one without your content inside but that has the same behaviour. However, first, try screenshots. :)

**Comment by folletto** [comment]
Did you solve this? :)

**Comment by folletto** [comment]
So... did you solve it with screenshots mode? :)

In other terms, we implemented custom events in Issue #225, have a look, it's another way that allows you to solve this issue since you should be able to control players off-screen. :)
