### ISSUE TITLE
Distribution options

### ISSUE THREAD

**Issue by djempty** [Simbul/baker#208]
Hi,

If I don't want to publish my app through the App Store but instead want to distribute it through my company's internal app store, is this possible? If yes, what are the procedures for this?

Thanks

**Comment by folletto** [comment]
Yes, it's possible.
You should refer to Apple documentation regardin Ad-Hoc distribution. :)

It should be on Apple SDK documentation, but you should be able to google around for it too. For example: 
http://diaryofacodemonkey.ruprect.com/2011/03/18/ad-hoc-app-distribution-with-xcode-4/

**Comment by djempty** [comment]
Hey... thanks a lot. That's very helpful!

**Comment by folletto** [comment]
You're welcome :)
