### ISSUE TITLE
Navigation interrupted after using a link

### ISSUE THREAD

**Issue by marciosm** [Simbul/baker#209]
Hi. I created an ebook with baker 3 with 2 different languages using just an initial cover with links to different pages of my book folder. The english cover is 001.html . The english pages are from 01 to 18. The spanish cover is 200.html and the spanish pages are from 201 to 218. When I am on 001.html (english cover) and click on the link to spanish cover (200.html) the page is loaded fine. But when I use the finger to go to the next page (201.html), the system shows 01.html ....
Am I doing something wrong? Can't we use links to jump to another next page? 
There's is another issue that I noticed: when I am on page 210.html for example and want to use the hidden menu (double click) to go to first cover (001.html) there is an effect that is visually like passing through all the past pages (200, 18, 17, 16, 15, 14, 13... until show the 001.html). Can this effect be avoided or am I doing something very very wrong?
tks a lot :)

**Comment by marciosm** [comment]
I just realized that I was doing a big mistake on json file, not writing the covers between the pages. That's the reason that when I was flipping from 200.html (spanish cover) to 201.html the framework did not understand it and returned to 01.html. There was no 200.html on json file. Sorry. :D

**Comment by folletto** [comment]
Oh, nice! That's a self-solving issue, wonderful :D

Keep us informed on your release. :)
