### ISSUE TITLE
Embedded Google Maps bounce out to Maps app automatically

### ISSUE THREAD

**Issue by jeffehobbs** [Simbul/baker#21]
If the user embeds a google map in their HPub, when they reach that page, the ebook will open the Maps app automatically.

**Comment by folletto** [comment]
Before proceeding, a question: are we sure that embedding a Google Map inside a book is something we want to do? :)
Because that means that the "book" works only online, and I think it would create a quite bad experience for a user.

That said, I think it's still interesting to see why it happens - I think it's something related to the managing of the URL schemes.

**Comment by jeffehobbs** [comment]
Really good point about the "online only" nature of embedded maps (I envisioned the maps as part of a travelogue). I imagine the bounce out is due the outlying nature of the way iOS handles links to the maps.google.com domain.

**Comment by PeterSchoppert** [comment]
I've embedded Google Maps using iframes and it works without bouncing me out ... I could see an argument for including Maps iframes, as long as failure to load a map is not a critical downside to the reader... Or if we could replace it with a static graphic while offline...

**Comment by folletto** [comment]
Did you use the ZIP from the website or the current development HEAD from github?

**Comment by PeterSchoppert** [comment]
Still on the ZIP...am I getting ahead of myself?

**Comment by folletto** [comment]
Ok, I think that the problem with maps appears only on the head version due to some changes in the way we intercept events to allow linking and other interesting stuffs. :)

**Comment by snive** [comment]
I've used this exampel to have a small googlemap on a page - http://code.google.com/intl/sv-SE/apis/maps/documentation/javascript/v2/examples/map-simple.html

**Comment by folletto** [comment]
The problems should be solved in the current master and in the 1.1. ;)
