### ISSUE TITLE
Baker app in ipad simulator appear in Newstand not like an app

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#210]
Hi,

I have finish my first ipad app with baker and I'm experiencing a weird problem when I try it in the simulator it is compiled in the newstand app and not like app. 
Is this a default behaviour?
How can I compile it to an app like the versions before?

Thanks for your help

**Comment by folletto** [comment]
That tells me you are using the latest unreleased master and not the 3.0 release :D

That's going to be the default, but you can turn off that behaviour, more informations here: https://github.com/Simbul/baker/wiki/Newsstand-support
