### ISSUE TITLE
View with Storyboard or XIB ???

### ISSUE THREAD

**Issue by webschnecke** [Simbul/baker#211]
Hi,

it is possible to use a xib or storybord file? I want to show a UiButton for spezial infos, but I dont want to create a spezial html-site. I want to show another view controller ;-)

So, I have to crate a view with a scrollview class but how I have to connect them all?

How can I do this?

**Comment by folletto** [comment]
I'm really sorry, but it's probably better if you ask this question on http://stackoverflow.com/questions/tagged/iphone or another generic iOS SDK development forum, we can't really help in implementing specific requests, otherwise we won't be able to develop Baker.

I'm sorry.

**Comment by webschnecke** [comment]
I have it ;-)

I modified the RootView: add a UIButton with an image and linked to a View, works fine for me. ;-)
