### ISSUE TITLE
Can I have more than one index.html file?

### ISSUE THREAD

**Issue by marciosm** [Simbul/baker#213]
I wanted that part of my book called a different index.html file. I was looking on XCode code that refers to that and did not find a way. Anybody more here wanted such crazy thing?
Maybe knowing on which page I clicked twice I could do something with javascript? Just guessing... :)

**Comment by trikanna** [comment]
Hi, can you find a solution? I need something similar. Regards.

**Comment by marciosm** [comment]
Not yet, but I am studying a way to use html5 local storage to keep the information about the page that I am reading in that moment and pass that data to index.html and change the toc file. Did it make any sense? :D

**Comment by trikanna** [comment]
Sure. I am trying to build a bridge between js and the rest of the framework.

**Comment by marciosm** [comment]
I have to try this on my book tonight when I return from work, but if you wanna try first, be my guest:

On every page book you have to define the language using local storage inside a script tag (here I can not copy & paste):

localStorage.lang="toc.html";

or, in my case, for spanish language in some pages:

localStorage.lang="tocspa.html";

then, go to index.html and write inside a script tag:

```
        document.write("<div id=\"includeTOC\" csi:src=\"inc/"+localStorage.lang+"\"></div>");
```

this script will identify the var language that is now stored inside each page of your book. 
As I said, I tested here on my work just using safari browser, but not yet on Baker XCode project. Hope it works :)
If so, I will let you know.

**Comment by trikanna** [comment]
I will try in a couple of hours. At work right now.

**Comment by marciosm** [comment]
I tried here on xcode project. Strange... sometimes it works. Sometimes not. I will try tomorrow to use meta no cache because I think that maybe the page is being cached (index.html)... When I run the localStorage command alone, it works. But it's not working between the main page and index.html. I think I gonna sleep and tomorrow try again... sorry :(

**Comment by trikanna** [comment]
Right now upgrading to xcode 4.2.1 (maybe 4.2.2 dont remember). And man, dont worry, in fact tks a lot for the idea. btw I am from Uruguay

**Comment by marciosm** [comment]
I´m from Brazil :) 
Let´s try until it works, :D

**Comment by trikanna** [comment]
hey marcio I have an BookIndex.html (where User can choose between 2 issues), and by javascript simply set a localStorage.variableName value. Then on the index.html just do a simple setInterval to check the localStorage.variableName... maybe with some conditional to clearInterval... tested on iOS simulator and works fine.

example:

set_edition : function(id){
    edition = id;
    localStorage.issue = edition;  
}

setInterval(function(){
    chapters.hide().eq(Number(localStorage.issue)).show();
    var el = chapters.hide().eq(Number(localStorage.issue)).show().find('li').size();
    $('body').width(200 + (160 \* el));
    $('p.output').html('menu para la versi&oacute;n -> ' + localStorage.issue );  
}, 1000);

**Comment by trikanna** [comment]
Just to be clear. I don`t have 2 index.html files, just 1... with 2 &lt;ol&gt;, each one with his own navigation thumbnails.

or maybe you could have 2 divs, each for one language. and hide/show by javascript (or even jquery, maybe zepto).

Regards

**Comment by marciosm** [comment]
Hi trikanna. I tried both ways but the reference of localstorage is being lost somehow. Sometimes the variable is undefined, even when I force the value. And when it works it's just for the first value, keeping it for the rest of the navigation, not changing when I use a function on my language buttons. I even tried to clear the values of localstorage everytime a page is loaded in portuguese (as example) and force the value to portuguese. Even so, it keeps english or spanish language as a value. Don't know what is happening. I thought that maybe tree cards was loading the contents of the other pages in memory and changing somehow the value of localstorage, but I did what you told me, to keep the function on first page only. It did not worked also. :( 
I tested on ipad and iphone and the value of localstorage sometimes is lost (undefined) and sometimes is eternal, keeping the first value for the rest of the navigation. Tried also sessionstorage and did not worked. Could you send me the 2 pages you developed so I can test in my computer? Just the code, not the contents, so you will not be worry about that. :)
My email is marciosmorais@gmail.com . Tks a lot. If you want, I can send you mine. All the best, Marcio

**Comment by marciosm** [comment]
just to close this issue, it's possible to have more than one index file using javascript and localstorage html5 function. But it's necessary to have the first page as a language selector to pass throught the selected value to the other pages and to toc files. thank you so much to trikanna/santiago for his valuable help. ;)
