### ISSUE TITLE
replace the download code with ASIHTTPRequest ?

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#214]
As I can see that ASIHTTPRequest has many advanced features, especially have break point recovery mode for download, this is very useful.

Consider?

**Comment by folletto** [comment]
You mean http://allseeing-i.com/ASIHTTPRequest/ ?
It seems nice. We'll consider it. :)

**Comment by folletto** [comment]
@zenz as you can see we can't yet look into it. Did you already implement this somewhere or are you able to contribute this code? Or, in other terms, what are the advantages that we could get out of it? :)

**Comment by zenz** [comment]
Sorry that I didn't make it. but will try it in next week if I have piece of free time.

**Comment by Simbul** [comment]
Issue download has been delegated to Newsstand Kit for a while now. Closing this issue as it does no longer apply.
