### ISSUE TITLE
NAVIGATION ON/OFF

### ISSUE THREAD

**Issue by mikadonguyen** [Simbul/baker#215]
I wanna make a ebook without nagavition,

can you help me, turn off it?

Tks

**Comment by k8fisher** [comment]
Im not an objective c person but Id guess removing everything from index.html and resetting all css linked to the table of contents would be the approach Id take (display:none) on all the components. Obviously one of the objective c wizards can probably think of a neater approach.

**Comment by mikadonguyen** [comment]
i deleted all div, but when i tap on ipad, navigation still show ???

**Comment by zenz** [comment]
just delete the index.html, it should work

**Comment by mikadonguyen** [comment]
ok i will try
