### ISSUE TITLE
Page "curl" animation instead of "slide"

### ISSUE THREAD

**Issue by a-v-ebrahimi** [Simbul/baker#216]
Is there an option for page curl, instead of slide?

Thank you.

**Comment by folletto** [comment]
It's not there and unfortunately it's a bit difficult to implement with the current architecture. But we'll keep this issue open to track it and see if it's possible - or of someone implements it.

Thanks :)

**Comment by jcampbell05** [comment]
I would implement this as I have found a tutorial for it but I am having difficulty understanding the code, which bit would I need to change. I understand that the scroll view is used to swap the webviews in and out

**Comment by a-v-ebrahimi** [comment]
What is your source for page curl, maybe I can help migrating it into Baker

**Comment by jcampbell05** [comment]
http://www.techotopia.com/index.php/An_Example_iOS_5_iPhone_UIPageViewController_Application - Heres is the tutorial I've been following

**Comment by folletto** [comment]
Reviewing this, we feel it's a bit outside the scope of the framework, so we are closing the issue. If someone wants to implement this however we could give it a try and see if we can merge it into master.

**Comment by Jacky1212** [comment]
Hi,

I am going to give it a try to implement it, but before that, @folletto, can you give me some hints why it is difficult to implement under the current architecture?

**Comment by folletto** [comment]
Hello @Jacky1212,

The reason it's difficult is because the gesture is fully managed right now by a `UIScrollView` and implementing curl requires a complete rewrite of that part.

That said, there's already someone else that is trying to do it, check issue #529 and maybe contact the author. :)
