### ISSUE TITLE
Newsstand basic support?

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#217]
Someone has created a free subscription to the Newstand? How? Baker needs to be implemented in xcode?

http://developer.apple.com/search/index.php?q=newsstand
http://developer.apple.com/library/ios/#documentation/StoreKit/Reference/NewsstandKit_Framework/_index.html
http://developer.apple.com/library/ios/#technotes/tn2280/_index.html

**Comment by folletto** [comment]
This is a duplicate of the request on Issue #100, I'll close this one. :)
