### ISSUE TITLE
automatically taking snap-shots produced crash

### ISSUE THREAD

**Issue by palianah** [Simbul/baker#218]
when i start the Applikation first time on the iPad1/iPad2 (both ios5 with Baker 3.0.2 using screenshot as rendering-mode), i can see on the log file that the screenshots where taken from each Page. 
But when you hava a lot of pages like me, you receive this log-message after a few pages: "received Memory warning" and than the application just crashes. 
But when you go the second time through the app, you don't get any Memory warnings and no crashes. So i think the reason of the crash is the automatically taking snap-shots. It saves to a repository like "var/mobile/Applications/application identifier/Documents/baker-snapshots/snap-portrait-x.jpg", where you can't access with your iPad (accept via ftp)

So my question is: Is there a method to disable taking automatically snap-shots on the iPad? On the Simulator it's fine, but on the iPad it crashes. 
Thanks!

**Comment by palianah** [comment]
I noticed, that the screenshots are taken only in the rendering-mode "screenshot" and "screenshots". 
I think you could limit this out only for taking the snap-shots on "screenshots" mode, because you use them only there.

**Comment by mutador** [comment]
i have this errors when i rotate ipad

---

  int retVal = UIApplicationMain(argc, argv, @"UIApplication", @"BakerAppDelegate");

--Thread 1: Program received signal: "SIGABRT".

---

```
    // Portrait
    view.image = backgroundImagePortrait;
} else {
    view.image = NULL;
}
```

}

Thread 1: program recceived signal: " EXC_BAD_ACCESS".

**Comment by palianah** [comment]
no more issues for me with the three-cards mode, so i will close the issue.

**Comment by mutador** [comment]
but be carefull whit the screenshot mode, it give you the same error whit a big book whit a lot images....
