### ISSUE TITLE
Best Fixed footer implementation?

### ISSUE THREAD

**Issue by Dreeke** [Simbul/baker#219]
Is anyone successfully implementing a fixed footer in their pages? I am running into all kinds inconsistent behavior. Sometimes it displays  properly. Sometimes it doesn't.

I am using the following code in the css for the footer.
# footer {

```
padding-top: 1.2em;
height:5%;
width: 100%;
position: fixed; bottom: 0px; left: 0px;
background: white;
```

}

**Comment by mutador** [comment]
you try includes? see laker

**Comment by folletto** [comment]
Is this complete? Any solution you found working that might be useful to someone else? :)

**Comment by mutador** [comment]
see this for a footer
https://github.com/Simbul/baker/issues/261
