### ISSUE TITLE
White background flash makes it difficult to use any other background other than white

### ISSUE THREAD

**Issue by jeffehobbs** [Simbul/baker#22]
It would be useful to be able to easily select the "background flash" color (and associated page number) when switching pages -- for a photography book, the user might want to select a different color or perhaps black, but white seems hard coded somewhere. Perhaps the flash color could be based on the next page's background color, but I also imagine that would be complicated to implement.

**Comment by folletto** [comment]
Yes, using the next page colour is probably the best solution, but as you've guessed it's also quite hard to get. :)

Consider also that I'd like to have the next and previous page pre-loaded, today it isn't possible due to memory limits of the iPad, but maybe in the future it's going to be possible (next year?).

If we can think of a simple - and efficient - way to do that it would be great. :)

**Comment by segundoseis** [comment]
Could it be creating an initial configuration document? I imagine an XML node for each page, you could set the background color and the color of the number as attributes.
Optionally you could use XML to control some other application parameters.

**Comment by jeffehobbs** [comment]
That XML file might be a good place to put optional index metadata (thumbnails, chapter/page titles, etc.) as well.

**Comment by folletto** [comment]
Indeed.

But I think that:
1. The standard should be universal, not device or implementation dependent (like a "background color for the next page on the iPad"
2. We should aim for a incredibly simple 1.0 version for the HPub standard.

So I'd try to avoid overloading the meta file with configuration bits. :)

What do you think?

**Comment by segundoseis** [comment]
I think it's good to have a configuration file with default values and then the player could to read it, depending on their capabilities use it or not.

It comes to my head the mp3 metadata, initially was not used by many players and then has been implemented at all.

I understand what he says @ jeffehobbs, if you put a black background in the html you will see that it is not very aesthetically change pages.

**Comment by svdgraaf** [comment]
The background color issue is simple to fix I think. We can just add a simple 'background' color to the meta file, have it be a hex color, and we can then read it and use that color.

**Comment by jeffehobbs** [comment]
As to what @folleto is saying above, I strongly agree on both points, and especially that the hPub standard should be as simple as possible (but not more so!). 

Having said that, a _completely optional_ preferences.xml document in the spec specifying some advanced features like background color(s) or content index would not be a bad thing. This product is going to be judged next to more advanced commercial offerings by Adobe etc. and should stack up competitively whenever possible.

**Comment by folletto** [comment]
Yes, I agree on that. We'll probably go on with this discussion then when we choose a way to handle metadata in HPub. ;)

**Comment by segundoseis** [comment]
for a background color I recommend to use this class of Jonas Schnelli
https://github.com/jonasschnelli/UIColor-i7HexColor

is very simple to use and supports hexadecimal color with transparency.
I used it as a test in Baker changing the white background color and page numbers colors, and it was very simple to implement.
:)

label.textColor = [UIColor colorWithHexString:@"ff0000"]; // red color
//or

label.textColor = [UIColor colorWithHexString:@"f00"]; // red color
//or

label.textColor = [UIColor colorWithHexString:@"ff000055"]; // red color with some alpha

**Comment by folletto** [comment]
That's a great idea. :) Thanks for the tip.

**Comment by folletto** [comment]
It seems we forgot to answer properly to this issue. :)

So, the code to do this is in the 2.0 release of Baker, you can edit it in the header of RootViewController.m:

// LOADER STYLE
// Configure this to change the color of the loader
#define SCROLLVIEW_BGCOLOR whiteColor
#define PAGE_NUMBERS_COLOR blackColor
#define PAGE_NUMBERS_ALPHA 0.2

**Comment by jeffehobbs** [comment]
Very cool! Thanks for following up, I am amazed and impressed at the progress Baker is making.
