### ISSUE TITLE
How to download new magazine edition

### ISSUE THREAD

**Issue by dudisitchy** [Simbul/baker#220]
Hi, I'm new on Baker...
How could I put 3 books on my server in order to baker donwload them from a menu with these 3 books?
Is it possible ? The magazine that I have to create will update every month and people would be able to download each one what they want.

Thanks a lot !!

**Comment by folletto** [comment]
I think that this page on the wiki should be able to answer your questions:
https://github.com/Simbul/baker/wiki/Book-protocol

However, it's something that works inside a Baker book: you have to add the links there :)

For the full multi-issue support, check for Issue #20 to be completed. :)

**Comment by dudisitchy** [comment]
Thanks for you answer...
Ok... I got it... but how could I make this inside book get dinamically the new edition ?? I can't work with php and mysql, am I right ??

**Comment by folletto** [comment]
Well, as I said that's related to Issue #20 for us, but if you want you should be able to create a JavaScript library to check the server and report any update. :)

**Comment by dudisitchy** [comment]
Hi folletto, thanks again for your reply... I downloaded the github file on issue #20 but I don't understand how to do what I need... could you give me a quick explanation ? Thank you !!!

**Comment by folletto** [comment]
There's no file: read the discussion ;)

**Comment by dudisitchy** [comment]
Ok... now I have the new baker... I was working with older. Sorry...
But, my question is the same. I edited on Book Index.html the link and write "book://www.myserver.com/books/firstedition". On my server I created this folder and put the book folder there. But there is no download on iPad Simulator... only opens the default page... How I have to proceed ?

**Comment by Simbul** [comment]
Sorry for getting back so late. I assume you've managed to solve the issue on your own by now.
In case you haven't: I believe the issue is that you should have a .hpub _file_, not a _folder_, on your server.
See the _Downloadable Books_ section in the [readme](https://github.com/Simbul/baker/blob/master/README.md).
