### ISSUE TITLE
How to add iAds Banner into Baker 3.0 ?

### ISSUE THREAD

**Issue by xx-Hitachi-xx** [Simbul/baker#224]
I read the followings:

https://github.com/Simbul/baker/issues/93

http://bees4honey.com/blog/tutorial/how-to-add-iad-banner-in-iphoneipad-app/

http://www.google.com/search?q=how+to+add+iad+to+my+app

http://www.raywenderlich.com/1371/how-to-integrate-iad-into-your-iphone-app

http://stackoverflow.com/questions/6532404/how-to-add-iads-without-xib-files

They don't work with Baker 3.0

I added the " iAD.framework " into the Frameworks folder and joined the Apple iADs Network.

Please tell me how to modify the existing files inside the Baker 3.0 to show the iAds banner. Thanks

**Comment by folletto** [comment]
Unfortunately I never did that.
And it seems that nobody else tried as well. 

Did you find a solution in the meantime? :)
