### ISSUE TITLE
Custom events fired by Baker

### ISSUE THREAD

**Issue by al3d** [Simbul/baker#225]
I've seen a few people mention animations and videos playing early/closing late when in three-card mode. Would it be possible in future versions for Baker to fire off events when certain things happen?

e.g. in three-card mode, baker fires `bakerloaded` or `bakerunloaded` events in javascript that can be captured by javascript:

``` javascript
document.addEventListener('bakerloaded', function(e) {
    // webview has finished rendering, start animations
});
document.addEventListener('bakerunloaded', function(e) {
    // stop playing sounds
});
```

They do something similar in Phonegap, and while I recognize the different approaches of both platforms, it would be handy to have functionality like this added to Baker.

Thanks

**Comment by folletto** [comment]
Sorry for the late answer. We agree on the suggestion, and we'll think of some kind of solution for this along the lines you suggested. :)

Thanks! :D

**Comment by mutador** [comment]
but in three cards is not when "bakerloaded" is when "bakershowpage" the pages after and before is load when don´t show, yo need the animation star when the page is show or when the user stop in the page

**Comment by folletto** [comment]
We mean exactly that, but I agree, the naming of the original example is ambiguous. :)

**Comment by al3d** [comment]
Ideally Baker would fire several events at different times, suited for different needs :-)

**Comment by folletto** [comment]
We are implementing the following two, so we should be as standards compliant as possible:

```
window.focus
window.blur
```

**Comment by Xm4s** [comment]
As the commit says now when the current page appear the event "focus" is dispatched on window and when it disappear the "blur" one is dispatched.

I'm closing this issue now, if problems arise feel free to open a bug issue on the board :)

**Comment by folletto** [comment]
As an example of implementation:

```
window.addEventListener("focus", function() { ... }, true);
window.addEventListener("blur", function() { ... }, true);
```

Where inside the two functions you can handle the focus and blur of the page. :)

**Comment by mutador** [comment]
GREAT- works fine ( ipad 1 - threcards mode)
