### ISSUE TITLE
Baker Children's book approved at App Store

### ISSUE THREAD

**Issue by ayarmanqu** [Simbul/baker#227]
Just to share that my Children's book was approved today (it only took a week, as opposed to the iBook version of my book that is waiting for approval for 2 months and counting).

I used Baker version 3 and lots of Javascripting for animation and other effects.
I was able to customize the index menu, so it worked as a "dock" for my book and used local.storage variables to be able to communicate between pages (to play/stop music).
I also used a custom Splash and a video intro, so it looked more like a "real app" rather than a static book.

Many thanks to the Baker team, as this framework made the work very easy!
I am now trying to create an Android version (especially now that the Kindle Fire and Nook Tablet are out) and I am using Phonegap, but the process is not as elegant and easy as it is with Baker.

If you want to check out the book, it is available here: http://itunes.apple.com/us/app/pookie-tushka-find-little/id483240724
(If it is incorrect to post links in here, please delete the posting and receive my apologies).

Thanks again!

Jorge
www.pers.com

**Comment by macpablodesigns** [comment]
Since you wrote it with Baker, why not check out Friar http://friar.szuhanchang.com/

**Comment by ayarmanqu** [comment]
Woooow! Thank you SO much!
I've been searching the web for this type of tool, but I couldn't find anything!
This is awesome! 
Jorge

**Comment by folletto** [comment]
Does someone know the author of Friar? We just discovered it and we'd like to contact him to ask if he wants to support the Baker Android port, officially. :)

~

@ayarmanqu that looks awesome. :) We'll check. :)
Could you provide us a voucher so we can see if we can add it to the showcase? :) Cheers!

**Comment by ayarmanqu** [comment]
Thanks!
It seems the App is crashing on some iPad 1s :/ I am assuming it is because of the video intro.
I may need to do a version check and disabled video on iPad1.

**Comment by barrytallis** [comment]
@folletto - szuhanchang@gmail.com.  Han Chang  - http://www.szuhanchang.com/projects.php

**Comment by folletto** [comment]
@barrytallis thanks. :)

**Comment by inventionarts** [comment]
I was able to using the Friar framework to bring up a test book on the Kindle Fire. Would indeed be great if it was brought up to speed with Baker 3.0. Happy to contribute through testing and commentary, at least. Android development using Eclipse, compared to iOS dev, is another world of complexity and gotchas. Simplifying the process with a cleaner development path is something Baker for Android would really help out with.

**Comment by inventionarts** [comment]
Jorge, wonderful work on Pookie and Tooshka! Such a rich collection of imagery, music, and activities. Really demonstrating what's possible with Baker and hybrid app development.

**Comment by ayarmanqu** [comment]
Thank you :)

I really tried to push the format and add as much content as possible.
Tons of thanks to the Baker folks :)

**Comment by ayarmanqu** [comment]
FYI, I could not get the book to work on iPad 1. No matter what I tried it always crashes. It seems the book uses too much memory :(

Oh well ...

**Comment by teamstar** [comment]
I am having the same problem... When i flip the pages, it will be alright for awhile then it'll just white out followed by black out then it'll shyly close itself...

**Comment by ManelSoria** [comment]
Well done, congratulations !!
Ja l'he descarregat :)

**Comment by marciosm** [comment]
Great book, with great pictures ! Congratulations !
If it's not asking too much, when you wrote "I was able to customize the index menu, so it worked as a "dock" for my book and used local.storage variables to be able to communicate between pages (to play/stop music" - can you share the code? I'm trying to stop a music when going to another page and it will be very helpful. Tks a lot and congrats again :D

**Comment by ayarmanqu** [comment]
Thank you, glad you liked the book :) (if you can, please give me a good rating ;)

Well my code is very messy, but basically this is what I did:
- I used a localStorage variable and gave it a value of 1 or 0 depending if the sound was playing or not.
- On each page I added a play/stop button that could change the localStorage variable to 1 or 0.
- On the index.html, I placed the background music and added a timer that would check the value of the localStorage variable every second. If the value changed to 0, then I would stop the sound.

So, you could add code to each page that changes the value to 0 as soon as the new page is loaded, so that the sound would stop.

My code is this:

```
var playingbg = false;
var sndbg = new Audio("audio/BackgroundMusic.m4a");         

function playMusicbg() {     
    localStorage.dataToStore = 0;  
    if (playingbg)
    {
    playingbg = false;  
    sndbg.pause();
    sndbg.currentTime=0; 
    sndbg.removeEventListener('ended', bgEnded);    
    document.getElementById("note").src ="images/note.png"; 
    clearInterval(ourInterval);
    } else { 
    playingbg = true;
    document.getElementById("note").src ="images/note-off.png"; 
    sndbg.play();
    sndbg.addEventListener('ended', bgEnded);   
    var ourInterval = setInterval(check, 1000);
    }
 }

function bgEnded() {   
document.getElementById("note").src ="images/note.png"; 
sndbg.removeEventListener('ended', bgEnded);    
playingbg = false;
clearInterval(ourInterval);
localStorage.dataToStore = 0;
}

function check(){
    if (localStorage.dataToStore >0) {
    playingbg = false;
    sndbg.pause();
    sndbg.currentTime=0; 
    sndbg.removeEventListener('ended', bgEnded);    
    document.getElementById("note").src ="images/note.png"; 
    clearInterval(ourInterval);

    }
}
```

Jorge

**Comment by folletto** [comment]
Jorge, let me tell this: you are a genius. :)
That's an incredible workaround. Kudos. :)

**Comment by ayarmanqu** [comment]
Hehehehe :)
Thank you :) :) :)
