### ISSUE TITLE
book://local can not go back to bundle book from Safari?

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#228]
"book://local can not go back to bundle book from outside?"
as title.

Please check.

**Comment by folletto** [comment]
We'll check. Thanks :)

**Comment by zenz** [comment]
I just make a dirty hack with my own by modifying the downloadBook function like this:

```
- (void)downloadBook:(NSNotification *)notification {

    if (notification != nil) {
        URLDownload = [[NSString stringWithString:(NSString *)[notification object]] retain];
    }   
    NSLog(@"• Download file %@", URLDownload);
    if ([URLDownload isEqualToString:@"http://local"])
    {
        // ****** Handle: book://
        NSLog(@"    Page is a link with scheme book://local --> download new book");

        feedbackAlert = [[UIAlertView alloc] initWithTitle:@"" 
                                                   message:[NSString stringWithFormat:CLOSE_BOOK_MESSAGE]
                                                  delegate:self
                                         cancelButtonTitle:ALERT_FEEDBACK_CANCEL
                                         otherButtonTitles:CLOSE_BOOK_CONFIRM, nil];
        [feedbackAlert show];
        [feedbackAlert release];
    } else {

        feedbackAlert = [[UIAlertView alloc] initWithTitle:@"" 
                                                   message:OPEN_BOOK_MESSAGE
                                                  delegate:self 
                                         cancelButtonTitle:ALERT_FEEDBACK_CANCEL 
                                         otherButtonTitles:OPEN_BOOK_CONFIRM, nil];
        [feedbackAlert show];
        [feedbackAlert release];
    }
}
```

Waiting for the official hack.

**Comment by Xm4s** [comment]
Hi!

I'm sorry but I can't reproduce your bug, in all my test clicking a link to book://local in a downloaded book revert correctly to the bundle book.

I think I understand what is happening, but just to be sure can you detail the necessary step to reproduce the bug? Also could you please explain what did you mean with the word "outside"? :)

**Comment by zenz** [comment]
Hi! Xm4s,
Outside means using safari to handle the book://local, on my clone copy, it doesn't work.

**Comment by folletto** [comment]
I don't understand the solution your code above is providing. Why `http://local`?
Could you explain the steps you are following in detail, where it fails, and what should it do instead?

**Comment by zenz** [comment]
Hi, Folletto,

What I do:
1. clone the newest baker code from github
2. set target's URL scheme to book(baker's source didn't set this).
3. compile and run on simulator.
4. open simulator's safari, in the address bar, enter book://local
Then I found that baker cannot handle it well(it will try to download that book but not switch back to bundle book).
It's the same result while running on real device.

about "http://local" is just a lazy work. because when the "book://local" comes to downloadBook, it's already translated to "http://local".

**Comment by folletto** [comment]
Uhm ok, I see the problem. :)

It's this:
`2. set target's URL scheme to book(baker's source didn't set this).`

Because this will break any other Baker book out there: you'll app will try to open every book linked anywhere.

It's ok if you want to build a general reader for Hpub books, but it's not if it's your own book, you'll just create a bad experience for book users... and you'll book will be removed with no way to come back. :)

**Comment by zenz** [comment]
Yes, if use a URL scheme like "book", it will be a problem, but if we change it to some special name, like "xyze", I think this can avoid the mass.

**Comment by folletto** [comment]
Yes, please avoid using book if you're not creating a generic reading app. ;)

That said: `book://local` is meant to work only from inside a book, since there's no "local" in an external book. If you want to revert to the default book from an external link, I think you should build a specific protocol and call yourself, different from "local". :)

**Comment by zenz** [comment]
That's the reason why I ask xm4s in other issue"Is that book://local designed only for internal open bundle book?"

If it's the design's reason, it's not a bug. but in my opinion, the handling should be there, just left for the user to make the decision(use it or not).

May be this issue can be closed and go for next one.  the issue #229 is still exist. no matter it's internal or external.

**Comment by folletto** [comment]
The protocol `book://`should be a standard, generic protocol. 

`book://local`, instead, is a way to tell Baker to workaround a specific limitation that we hope to remove in a future version. So yes, it's only an internal thing. :)
