### ISSUE TITLE
Screenshot mode rendering pages with video poorly

### ISSUE THREAD

**Issue by joshbaltzell** [Simbul/baker#231]
I tried screenshot mode today and it is working really well for me. My only issue is that on my test iPad2 the pages that have video render like the screenshot below for a moment before the HTML renders.

What's really strange is that this does not happen on iPad 1.

![GitHub Logo](http://img35.imageshack.us/img35/1628/img0062t.png)

**Comment by zenz** [comment]
I think this should be html codes problem? I use video on my app too. it seems running well. and I found if I use poster param with video element, it will create cache images on tmp folder and left there by uiwebkit.

**Comment by folletto** [comment]
Did you solve this @joshbaltzell? :)

**Comment by joshbaltzell** [comment]
Yes, sorry. I think it was confusion about the documentation. I was trying to specify my own screenshots in 3.0, but that feature was in 3.1.

**Comment by folletto** [comment]
Great! Thanks :D
