### ISSUE TITLE
So.. here's another problem of book handling

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#232]
Follow this steps:
1. make a link in any page(except page1) of the bundle book. like this &lt;a href="book://zenz.ourcafe.mobi/files/testbook.hpub"&gt;Download this testbook&lt;/a&gt;
2. run baker and go to that page
3. click the link.
   Then it will open the textbook.
4. completely close(kill) baker.
5. run baker again.
   You will found that baker will hang up.

textbook actually is a 1page book. 
This problem is related to book://local problem

**Comment by Xm4s** [comment]
Ok, I've ...
1. make a link on page 5 to book://localhost/mytestbook.hpub; mytestbook is a Baker book with only one page (so the hpub contains only page-01.html and book.json) and that page has a link to book://local.
2. install Baker on my iPad (iPad 2 with iOS 5.0.1)
3. run Baker and go to page 5
4. click on book://mytestbook.hpub link: mytestbook.hpub got downloaded and opened, its first (and only) page is shown.
5. close and then kill Baker
6. reopen Baker: **mytestbook is opened and its page is shown (no hang up)**.
7. click on book://local link: **Baker bundled book is opened and its first page is shown (no hung up)**.

I think I've done all correctly but still I can see the application crash, so ...
- are you sure you are using a pristine clone of Baker, with no change whatsoever in the code?
- after reading this report, have you got any further suggestion for me to reproduce the bug?

**Comment by zenz** [comment]
Hi, Xm4s.

Thank you for your work!

While I do the test. I use the fresh clone of backer on that day.

So, I will try it again on monday. because no coding machine in weekend.

**Comment by zenz** [comment]
Well, this problem also fixed with issue #229
