### ISSUE TITLE
JPG/PNG images sometimes gets blank

### ISSUE THREAD

**Issue by sergeant-s** [Simbul/baker#234]
HI, I'll be grateful if you give me a help.

I'm suffering from a problem since baker2.0. 
When browsing a book on a device(iPad), sometimes JPG/PNG images on pages gets blank.(disappears.) Instead of images, I get "baker-background"-colored rectangles. Weirdly, not all images get blank, but a few random ones do.

I presume this has something to do with memory issues, because
a. it does not occur on simulators.
b.it does not happen immediately after launching the app, but it happens only after quite a bit of browsing.

I checked Outputs, and found

"ImageIO: JPEGNot a JPEG file: starts with 0xff0xd9"
then
"memory warning. Level=1"

when occurrence.

I have had this issue since baker2.0. Now I use baker3.0+Laker with thrree-cards rendering without any JavaScripts, and still suffer from it. 

Please forgive me if this is already a well-know issue.

**Comment by zenz** [comment]
you really should check your html coding and your files path also your files format. I am also using baker3 + laker framework(but all Jquery relative js scripts updated to newest version). every thing fine.

**Comment by sergeant-s** [comment]
Thank you for your quick reply, zenz.
I really appreciate your suggestions, and I'll try updating Jquery scripts.

However, I'm afraid, it's not about path or file formats.
All images appear fine at first, but after a lot of browsing and lots of page jumping, a few of these images will gone.

Thank you very much anyway, your success in Baker3.0+Laker encourages me greatly.

**Comment by sergeant-s** [comment]
I found it's a memory issue and happens only on iPad1, and basically unsolvable.
It only happens when a user change pages back&forth for about 50 times, so I regard it not a great problem.
Thanks.
