### ISSUE TITLE
Swipe Code

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#235]
Hi!

Presently, I see lots of swipe down navigation. I was wondering if anyone disabled the swipe on the chapter page and created individual pages for chapter content?

This would be while still keeping a book navigator somewhere on the page that's launched with a double tap.

**Comment by folletto** [comment]
Do you mean having each page exactly of the right vertical size, so there's no scroll down?

**Comment by ghost** [comment]
Yes!

**Comment by ghost** [comment]
To clarify, there are still chapters and chapter navigation would use the framework. Only individual pages of the chapter content would be accessed via LR swipes.  Double tap still brings up Chapter nav.

I think I see that an override has to be done... send event in the interceptor window...

**Comment by folletto** [comment]
Uhm I don't get however why do you have to change anything, just put each page after the other and make the navigation point only to the first pages of each chapter, like Forgotten Colours do, no? :)

Maybe, adding the `-baker-vertical-bounce: false` flag: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters :)

**Comment by ghost** [comment]
Now that you caused me to look at Forgotten Colors again, I got it! Thanks!!! 

Cheers! Stay tuned, content alignment next!  Having someone post Forgotten Colors (sans photos) would be very nice...LOL

**Comment by folletto** [comment]
;)
