### ISSUE TITLE
PHP form to create book.json file

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#236]
Would anyone have any interest in one? It's scheduled to be done in a week. I'll put it up somewhere or it can be here.  It just constrains things a bit and gets you out of manual entry...

/jws

**Comment by folletto** [comment]
That would be great, I'd say. :)

Please keep us updated. :)

**Comment by ghost** [comment]
A little distracted on other priorites, my JQ dev is working on it. A couple of weeks, I expect.

**Comment by Simbul** [comment]
Hey @JackWS, did you manage to complete that PHP script? It's totally fine if you decided it was not a priority, just want to make sure it's properly linked in case you managed to complete it ;)
