### ISSUE TITLE
How about use JSONKit to replace the TouchJSON?

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#237]
JSONKit is more fast and more tiny than TouchJSON.

I have replace TouchJSON with JSONKit in my own copy, and it seems running well.

**Comment by folletto** [comment]
May I ask what's the concrete advantage? Smaller executable or cleaner code? :)

If you think it's an improvement we should make, just prepare a branch on GitHub and push it to the main branch ;)

**Comment by zenz** [comment]
Personally, I think JSONKit is design with more clean structure, and more easy for use.
Like original

<pre>
ret = [NSDictionary dictionaryWithJSONString:fileJSON error:&e];
</pre>

And now

<pre>
ret = [fileJSON objectFromJSONString];
</pre>


The reason why I didn't prepare a branch on github..... because I don't know how to....shame....

**Comment by folletto** [comment]
Are you willing to try? In that way your work will be clearly attributed to you and it will be incredibly easier for us to test it: http://help.github.com/send-pull-requests/ :)

**Comment by zenz** [comment]
Thank you for the HOWTO, I've just try to set it up and send a pull request. I don't know if I did it right.

**Comment by folletto** [comment]
You did! Thanks, we'll check! :D
