### ISSUE TITLE
Double tap to zoom?

### ISSUE THREAD

**Issue by ramvi** [Simbul/baker#238]
How would I go about making double tap zoom like in Safari? It's not possible to fit to content as I'm you rendering jpgs, but it should be possible to just set zoom to 2x at location of double tap?

**Comment by zenz** [comment]
double tap was used for showing the index(navigator)

**Comment by ramvi** [comment]
Thanks for the quick answer. Yes, I know. In my magazine I want to change this. Shouldn't be too hard; or am I wrong?

**Comment by zenz** [comment]
It's not hard. but it's a private need.

**Comment by folletto** [comment]
I don't know if it fits your needs, but you can enable the "zoomable" property of Hpub, out of the box: https://github.com/Simbul/baker/wiki/hpub-specification ;)

**Comment by molorago** [comment]
how you fix this problem?

**Comment by folletto** [comment]
Just look at the comment above yours. :)
