### ISSUE TITLE
Screenshots update for retina display

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#239]
consider the user will use some retina display devices like iphone4 & iphone4s, the capture of screenshots should be modify like following.

<pre>
- (void)takeScreenshotFromView:(UIWebView *)webView forPage:(int)pageNumber andOrientation:(NSString *)interfaceOrientation {
    .....
         // UIGraphicsBeginImageContextWithOptions(webView.frame.size, NO, 1.0); 
        UIGraphicsBeginImageContextWithOptions(webView.frame.size, NO, [UIScreen mainScreen].scale);
    .....
}
</pre>

or else baker will just capture the low density screenshots, it's ugly.
Also we should change the handling for pre-made screenshots.

**Comment by folletto** [comment]
That's nice! :)

Thanks :D

(still no luck at figuring out push? no worries than, we'll add your name in the commit) :D

**Comment by folletto** [comment]
What do you mean by the handling for pre-made screenshot? :)

**Comment by zenz** [comment]
about the pre-made screenshot, I mean this:

<pre>
NSString *screenshotFolder = [properties get:@"-baker-page-screenshots", nil];
</pre>


In current state, the book designer can put some captured screenshots in the defined folder. so that the reading can be very smooth from the most beginning(no need to render and capture in run time). but for the reason like this topic, one folder definition is not enough while the user are using retina device. so we should figure out a solution.

**Comment by folletto** [comment]
Good point. But if you upload screenshots at retina resolution, doesn't that solve the problem? What's the solution then?

**Comment by zenz** [comment]
because right now the iPad and iPhone have different display scale. so we cannot use just one resolution to solve all the problem. or else the pre-made screenshots cannot fit for the user's device. and after html rendering the display will be different. we don't want that.
so, I personally use two folders to handle it. still use one property define. but have a device detection to confirm which folder should be use.like

in book.json, I have

<pre>
"-baker-page-screenshots":"pre-made"
</pre>


and then I have two folder for different device

<pre>
pre-made-ipad
pre-made-iphone
</pre>


normally the retina pictures from iphone4 can display well on normal iPhone display. because they have the same scale. but I never tested on real devices.

**Comment by folletto** [comment]
That's clear now. I suppose we could use the `@2` standard naming that Apple is using for retina as well. :)

**Comment by zenz** [comment]
please be aware that it's not only normal display and retina display's different, it's also iPad and iPhone's display scale's different. if we want to make a universal app, we must handle it well.

**Comment by folletto** [comment]
Yes, certainly. :)

That feature is actually a temporary add-on, we really hope to be a stop-gap while the WebView gets less buggy, but of course, it might be worth the effort to support these variations. :)

**Comment by folletto** [comment]
Done! Thanks :D

**Comment by zenz** [comment]
Thank you all who bring us such a good project.
