### ISSUE TITLE
Scroll down bug

### ISSUE THREAD

**Issue by Xm4s** [Simbul/baker#24]
Scrolling down while near/at the end of a page by tapping the bottom of the screen cause the webview to "jump up" in a strange manner.

Details:

iOS Version
- 4.2

What steps will reproduce the problem?
1. Open a book with Baker 
2. Scroll down by tapping the bottom of the iPad
3. Keep scrolling down till ou reach the end of the page, then scroll again

What is the expected result?
- The page scroll till the end and stop there.

What happens instead?
- The page indeed scroll till the end, but near/at the end it keeps "jumping up" before setting down.

**Comment by folletto** [comment]
Yup, same issue here. Confirmed. :)

**Comment by Xm4s** [comment]
I've looked into the problem, actually the "jump" animation it's the uiscrollview inside the uiwebview that's bouncing after scrolling too much over the end of the page.

I'm already working on this, I'll have a fix ready as soon as possible.

**Comment by Xm4s** [comment]
I've just commited a fix for this problem (commit https://github.com/Simbul/baker/commit/c5e1400f86a68ec90af9bccf4e7fecb7d7790246)

Unfortunately I can't try it on iOS 4.2 right now, so, before closing this up, I think a test is required :)

**Comment by segundoseis** [comment]
hi @Xm4s!
tested in ipad with 4.2
works OK with portrait mode, but the jumping is not fix with the landscape mode. 
I supose that  the problem are in this line with the 1024:
currentPageMaxScroll = size.height - 1024;

if I change the 1024 for 768 works in landscape but not in portrait mode ;-)

Did you use the @svdgraaf last version?
https://github.com/svdgraaf/baker/commit/bf0409a2f461c0cb664b3b631a84ff739dc0f988

**Comment by Xm4s** [comment]
Thank you for point this out segundoseis, I really haven't though of that :)
I guess that hard coding 1024 was a bit gross :P I'll have it fixed as soon as possible.

About svdgraaf code, that's still being revised, so up to now I've worked on the main branch of the framework. As soon as its ready for a merge we'll add the rotation on the main branch too.

**Comment by segundoseis** [comment]
OK :)
I've tested your changes to the master in @svdgraaf version, that I think should be included in the master. ;-) works very fine!

**Comment by folletto** [comment]
svdgraaf's branch needs surely to be included in the master, but I still have the problems I've cited in the other issue. We can't stop working on all the other features until it gets merged unfortunately.

**Comment by Xm4s** [comment]
I've made a little improvement to the fix, now handling the scroll limit with different device orientations (when available) should be much easier :)

Since the bug is fixed I'm closing this up, thanks for the help.
