### ISSUE TITLE
double-tap navigation not working

### ISSUE THREAD

**Issue by nruffilo** [Simbul/baker#240]
I have the latest baker (as of 12/3) and am testing on iPad iOS 5 simulator.  I have an index.html file in my /book directory and when double-tapping on a basic page (all it has is an H1 element on it) nothing happens (except the iPad status bar displays).

Am I doing something wrong?  Do i need to define something special in the book.json?  The rest of the book works perfectly fine.

**Comment by folletto** [comment]
Maybe it's a matter of sizing: did you try specifying the size of the index in book.json? :)
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

`-baker-index-height`. :)

**Comment by nruffilo** [comment]
Thanks!

On Tue, Dec 13, 2011 at 5:49 PM, Davide Casali <
reply@reply.github.com

**Comment by folletto** [comment]
You're welcome! :)

**Comment by molorago** [comment]
Hi... i have the same problem, what size you place in the height????
