### ISSUE TITLE
Discussion: Adobe Edge and Tumult Hype and Baker/UIWebView

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#242]
No Issue but I tried dropping in an Adobe Edge Example...

I went out and had coffee while it played. Horrible performance.  Definitely not due to the framework.  I tried Getting Jumpy by MediaRain. 

Resolution of all of the pngs were decent and perhaps that was the issue; however, it was just so darned slow.

Would be curious if anyone has tried using Edge to create HTML 5 pages or if folks are using something different. I'm going to keep looking for an HTML5 producer - perhaps something that will create pages using strictly Jquery...

**Comment by ghost** [comment]
On the other hand...I just tried Hype for Mac.  WOW!!! Performance is EXCELLENT!!!  I took their Woo Grit Example, exported to HTML5, dumped into the framework and boom! Nice CSS transitions, image moves, buttons, graphics, all with decent fidelity.  Nice!

**Comment by folletto** [comment]
That's _VERY_ good to know. :)

I suppose that Edge performance still needs some finetuning, and it might even be something about the performance of UIWebView vs Mobile Safari.

Did you test the same thing in Mobile Safari as well, just to have an additional perfomance check?:)

**Comment by ghost** [comment]
LOL, nope. Why in the heck would I do that? I do mobile!  LOL...

**Comment by folletto** [comment]
Just because while it's the same engine that powers Baker, it has some differences that might impact acceleration, so, if you test in Mobile Safari and it runs smoothly, it means that it's just the acceleration is missing from UIWebView and we need to wait Apple. Instead, if it doesn't run smoothly in Mobile Safari as well, it might be probably worth waiting for Adobe update instead of Apple. Just that. :)

**Comment by ghost** [comment]
http://labs.adobe.com/technologies/edge/resources/gettingjumpy3/wordAnimation3.html

http://tumultco.com/hype/gallery/WooGrit2/WooGrit2.html

Not quite the same but here's what I tested. The edge is loaded with about
40 small graphics files plus repeats of the same I think.

I looked at the beginning of the edge part - which was very slow. Don't
know why but I think the transforms were a problem.

**Comment by folletto** [comment]
I'm cleaning up the issue tracker. I'll close this old discussion. :)
