### ISSUE TITLE
Screenshots doubts

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#243]
Hi. First of all i wanna congratulate the programmers of baker. Nice work guys!!! I try to make a magazine and i have a doubt for the mode rendering screenshots - Its the "-baker-page-screenshots" already implemented in 3.0.2? I try "-baker-page-screenshots":"book/images/screenshots" with the files screenshot-portrait-1 and so on....didnt work, always display loading.

Anyone can clarify me?

Thanks

**Comment by Xm4s** [comment]
Path to the screenshots folder should be relative to the book, try **"-baker-page-screenshots": "images/screenshots"** :)
