### ISSUE TITLE
Using external content and testing for internet access

### ISSUE THREAD

**Issue by joshbaltzell** [Simbul/baker#245]
I'd like to redirect my users to a signup form that renders either within Baker or directly in Safari, but I'd like to gracefully handle situations where they do not have internet access. Is there a way for me to test and show one page if they have internet access and one if they don't? Maybe a JS trick?

**Comment by folletto** [comment]
Yup, you should be able to load a page (the one that will be displayed if online) and then modify it when it finds a connection. :)

**Comment by mutador** [comment]
yes , but how?

**Comment by folletto** [comment]
The outline of what the script should do is:
1. You try to connect to the server using JS and XMLHTTPRequest
2. If it can't connect, then you are offline.
3. If it can connect, you download the HTML/JSON/XML/anything and update the localstorage data store.
4. You then display the latest content from either the book or the localstorage data store.

Done. :)

**Comment by folletto** [comment]
Did anyone write successfully this javascript code in the end? :)

**Comment by davidrsim** [comment]
If you're using jQuery this is easy:

$.ajax({ url: "http://servicetoconnectto.com/",
                       datatype: "xml",
                       success: function(xml){
                       //actions on successful connect go here... update localstorage?
                        },
                       error: function(jqXHR, exception) {
                       //Display a message or do nothing - we're unable to connect for whatever reason. Probably offline but server could be down. 
                       }
                        });

**Comment by rahuxx** [comment]
can we load installed app?

**Comment by folletto** [comment]
Could you please clarify? :)
