### ISSUE TITLE
Highlight text when touched

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#246]
Is it possible (with JS and/or CSS) to highlight text when it's begin touched?
Maybe something like the CSS elements "hover" or "active" which can be used on regular websites?

**Comment by folletto** [comment]
Sure, there are lots of informations on the web on the possible touch events on Mobile Safari. :)

For example: 
http://code.google.com/p/jquery-ui-for-ipad-and-iphone/

**Comment by danielbenjamins** [comment]
Thanks Davide, that's a nice project you're referring to. (Also this one: https://github.com/furf/jquery-ui-touch-punch).

I've done some searching myself and found (http://developer.apple.com/library/IOs/#documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html) a CSS selector called '-webkit-tap-highlight-color'. Hopefully this will work with normal text as it works with buttons/links in their example.

**Comment by folletto** [comment]
So, as a summary for future readers before closing this issue:
- `-webkit-tap-highlight-color` changes the color of the [interactive tapped element](http://css-infos.net/property/-webkit-tap-highlight-color).
- `::selection` pseudo-class instead allows changing the [color of the selected highlight](https://developer.mozilla.org/En/CSS/%3A%3Aselection). However mind that this is not in the CSS3 specification, and so it's just supported by the browsers by themselves.
