### ISSUE TITLE
Professional magazines made in Baker discussion

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#248]
Hello we are trying to push through a publishing project to produce monthly magazine subscriptions and download payment newsstand numbers.

if anyone has the same interests, this is a post to discuss the needs and experiences of the baker edition

http://omgod.es/app

**Comment by mutador** [comment]
My first comment is the comment and support for newsstand, which is necessary and essential for the viability of professional projects.

https://github.com/Simbul/baker/issues/100#issuecomment-3223583

There are several requirements related to the inclusion of advertising such as eg
include a form of floating windows open baker himself with urls possib online and have a close button, without leaving the baker, but can easily return to baker

**Comment by zenz** [comment]
my be you can check github to find a branch of baker named bakershelf.

**Comment by mpena2099** [comment]
See "bakershelf" on issue #20 (direct link to bakershelf: https://github.com/nin9creative/baker)

We need help! :)

**Comment by mutador** [comment]
You work for a viewer with direct downloads.
I believe(  and be wrong) than the correct way  for magazines professionals and clients  is only newsstand ,they  are going to demand their systems newsstand and subscriptions and payments  through apple system.
even your  viewer must be inside the newsstand , that is where people now search for magazines only in newsstand.

is my opinion

We can help with design issues and beta testers only, we are not developers...

**Comment by mpena2099** [comment]
@mutador, we will start with direct downloads BUT the future versions will also use In App Purchase (THAT is what your're looking for, not Newsstand). Newsstand is just the new and right place to put magazines.

I guess any help, not only with code, but also with design and test, will be welcome. :)

**Comment by mutador** [comment]
hi  mpena2009, 
but you are to put a magazine in newsstand? they have their own especifications , your work whit direct downloads probably does´nt be for nothing whit newsstand, but i comment how i see the aplication whit direct downloads....

**Comment by mpena2099** [comment]
Yes, we will put the "shelf" in Newsstand.

**Comment by mutador** [comment]
ok i hope this, i comment in this https://github.com/Simbul/baker/issues/20 how i see the project now

**Comment by folletto** [comment]
Please, always try to break down functionalities in small chunks. Today, we have already the whole path for Magazines laid down, in order:
1. Shelf: Issue #20
2. Newsstand full support: Issue #100

If you need more features after these, break them down into specific issues, so people can vote and contribute to them, and we as the Baker team can prioritize and version them. :)

**Comment by mutador** [comment]
idea: fullsceeen window whit close buttom in links

when you have a link inside baker, you will need close it and reload the baker page. a new reference for the links be good.

a fullscreen popup 1024x768 whit a buttom for close it and reload the original page in baker.

this is necesary for microsites of product in publicity

**Comment by mutador** [comment]
idea: a rss system integrate in xcode baker, not in html5 , similar "http://flipboard.com/"

**Comment by mpena2099** [comment]
@mutador, I think it is out of scope of a book/magazine... or not? :)

**Comment by mutador** [comment]
Well, it is always well received by advertisers, which has a page that is updated real-time content, you tell them in the magazine may have an ad that changes by the day they go crazy.

This would be so and it's one thing I miss much at fault: iframes with content that is updated online if you are connected and it will show the latest version loaded, and xml or rss. but always have content, e.g. whit the date of the update

anoter great idea is this: http://vimeo.com/27296518

**Comment by folletto** [comment]
Well you can do exactly the same thing that they did in Baker. :)

However, that's a publication feature, not a Baker feature. You don't need to add features to Baker to do that, you just have to include a simple JavaScript on the page. It could probably even be a Google Ad if you really want to. :)
It's quite simple. :)

**Comment by mutador** [comment]
thanks @folleto 
but I say, it´s need implementation in baker, because you need is a page to save the update via xml and display it with the date in baker upadate,  if the user updates it and if not,  showing the latest updated content and keep in a final update. if you just use javascript in the html does not work (or if someone may hideout in iphone javascript content please share it), i am not sure to explained well

this is a thing have adobedigitalpublishing and a lot of similar solutions for magazines

**Comment by folletto** [comment]
Uhm I might be missing something, but:
1. If it's a small variation, you can just show a default ad, and if the user is connected you download the latest update ad. You also might be able to store the update using things like localstorage: https://developer.mozilla.org/en/DOM/Storage
2. If it's a big variation, you just ping the server and if there's an update you download the latest Hpub package.

Both of them are already possible today.

We might think to provide a more reliable solution than localstorage, but I didn't test the localstorage permanence itself, so it might be already enough. :)

**Comment by folletto** [comment]
About your message above for the browser inside Baker, there's already an open issue for that: Issue #119. ;)

**Comment by mutador** [comment]
but i only talk in a part of one page, not a full hpub, i am gona make a sreenshoot

<img src="http://www.mutador.com/baker/iframe.jpg" >

**Comment by folletto** [comment]
Yes, that's what I meant by "small", point 1. :)

**Comment by mutador** [comment]
Thanks for your references, but we have tried this , your point 1 and in practice does not work well with apps and pages in html and manifest files only, we found that at times for visualizing changes need to delete the preferences and manually Cache sometimes even delete and reinstall the app. So this makes it unfeasible to do so and still think that the solution passes through xcode integration.

we have interview whit xcode developer in madrid but nobody seems to know how to do what we ask, integration with newsstand, xml and rss....etc ...... we are searching for a xcode developer in madrid  to customice baker , newsstand integration etc...

**Comment by folletto** [comment]
Uhm it's really strange, because well... it works on the web and Baker just uses WebKit. If you have the source code of the javascript library you wrote I might be able to give you some pointers about that. That's because with JS you should have all the tools to check serverside the updates and pull them down plus storing them with localstorage. If that doesn't work, well, I think that we are facing a bigger problem than that, because it means that the UIWebView is less capable than Safari Mobile.

It might be that localstorage isn't working well but... I'd have expected the opposite: losing the updated data, not its persistence. Or problems from the security sandbox, like this one:
http://forrst.com/posts/Security_err_dom_exception_18_and_how_to_avoid-1Ge

Could you send us the JS you tried to use? Or is it too sensitive/private to have another pair of eyes looking at that?

**Comment by mutador** [comment]
we try whit this kind of code
http://www.thecssninja.com/javascript/how-to-create-offline-webapps-on-the-iphone

and this

http://html5demos.com/offlineapp

and we can´t

**Comment by folletto** [comment]
A-ha! No, that's not it. :)
That's a completely different solution, and it's required only if you want to build a completely standalone app (not with Baker) from the web that could be added _as HTML_ on the iPhone/iPad.

It's way simpler. :)
See my answer on Issue #245. :)

**Comment by PabloFonseca** [comment]
I just got in this discussion today, and i think that it would be very helpfull if we could delivery new magazine editions through baker. It would add great value to this solution. 
From what i've read baker needs to implement the shelf system from issue #20, then it should be able to dowload new issues through book:// protocol, but i think it needs to implement some kind of security to avoid download and acccess to hpub contents through any brownser, maibe a password on the hpub zipped file or a way to uniqulely identify the client, so we can perform authentication and/or delivery of new editions in our servers.
And finally a push notification system. 
I think any other feature regarding dynamic content, layouts, animations, etc. Should be done via jscript, css and some others brownsers technologies.

**Comment by killer1loop** [comment]
I want to check the opportunity of forming a team to work on the following:
- Add multiple issue functionality with Apple Newsstand support of .zip edition files
- Add in-app purchases to support paid single editions and subscription
- Add an issue picker functionality to browse for issues, purchase them and manage subscriptions
- Add background downloads functionality through push notifications

Not baker related points:
- Add a WordPress team working on building a plugin to manage entitlements and create .zip packages to be sent over to the App
- Add an external entitlements web service to manage purchased content through non-Apple systems
- Form a web designers' team to develop custom made responsive wordpress themes as a starting point for publishers

We have some good work made on Wordpress to share with the team, sketches and workflows to use a starting point.

The whole thing could be discussed in London in a short time if someone wants to take part. We can also share opinions on starting a Kickstarter on that.

I would be glad to collect ideas and propositions. Everything can be open-sourced.

**Comment by folletto** [comment]
Regarding the first and partially third and fourth point, check the branch `shelf` here on github. We have already started that and the work is in progress as you can see on the Issue #20. :)

**Comment by krisix** [comment]
I've done some work on implementing multiple issues functionality. You can check my code here https://github.com/krisix/baker-s.

There is some work to be done - like in-app purchase, background downloads and support for Newsstand.

**Comment by folletto** [comment]
I think the main issue right now is that a lot of people are working on these features but without any coordination, either here or elsewhere, to come up with a single solution we could merge in the main tree. @killer1loop proposal is interesting because he wants to form a team to work on these features, solving that. :)

**Comment by nin9creative** [comment]
Stefano,

We've made a chunk of progress on this in my nin9creative branch of baker.  We do need some work to get it up to the latest compatibility (we broke it when we had to change baker to be launched from the shelf - however now I think there is a version that we can use from their master shelf branch)

I'd be interested in chatting about this.  I have been trying to make progress but it has been hard with limited time and resources.  

Andrew

**Comment by folletto** [comment]
@nin9creative you're correct: we split Baker from being a single app to `BakerViewController` to make it modular during our work in Issue #59. :)

Please if you discuss keep the conversation going here (and on Issue #20) as well. ;)

**Comment by tstegart** [comment]
I also suggest we separate the newsstand work into paid and free, with a stripped down version for people who release free magazines and a full version for people who release paid magazines. A lot of the requirements to accept payments just confuse me, and I know a lot of people just want to get their free magazine into the right place in the App Store, ie Newsstand.

**Comment by folletto** [comment]
The basic version is exactly where we are headed with the currenet branch `SHELF`, have a look. ;)

**Comment by tstegart** [comment]
That's a pleasant surprise. Is this written down anywhere? I'm a little confused for what the goals are for the next version. Is it support for free magazines in Newsstand out of the box? Maybe we need an update thread. As a non-coder, I find it hard to tell if the shelf version is ready for me to start testing or if there are large parts of the functionality still missing. Can you give a quick update on what is done and what still needs to be done?

**Comment by folletto** [comment]
Yes: check the milestones at the top of this page on GitHub to check the progress for the next release.
The branch is currently in development, so I can't really highlight what's in and what's out, but the milestone 4.0 should be a good approximation: basically, we are addressing Issue #20. :)

It's ready for testing, but it's not yet in beta: not all the features to have a workable shelf are implemented (however, we are following some of the choices made by @nin9creative and @mpena2099). :)

Follow Issue #20 for updates. :)

**Comment by tstegart** [comment]
Thanks @folletto I'll keep an eye on that issue from now on.

**Comment by krisix** [comment]
@nin9creative We have the same problem - we have to release a magazine for client. We have started work in the february/march and after few months we have realized that there have been done many changes in master branch :)

But we don't have newsstand support :(

**Comment by nin9creative** [comment]
I'm going to try to update the bakershelf branch this weekend with the newer Baker changes...  Hopefully I'll be able to get it up to date with the main Baker master.

Andrew﻿

**Comment by folletto** [comment]
Great news Andrew! :)

**Comment by folletto** [comment]
This was a good but definitely old discussion with Baker 4 out by now. I'm closing it. :)
