### ISSUE TITLE
Loading screen disable

### ISSUE THREAD

**Issue by alpertayfun** [Simbul/baker#25]
Hi,

How can i disable loading screen ? Because , I'm long waiting for the page load. ( Page content : Video , Image , JS , JSon... )

Greetings,
AT

**Comment by folletto** [comment]
There's not set up way to do that as of today. You have to code that part yourself. However, if your page takes a long time, I'd advise to not remove the loader, or to replace it with something similar to tell the user that the page is still loading.

**Comment by folletto** [comment]
This isn't a bug or feature req, closing.

**Comment by alpertayfun** [comment]
All right. Thank you for your helping :)
