### ISSUE TITLE
How to compatible version of iphone and ipad size

### ISSUE THREAD

**Issue by strong6619** [Simbul/baker#250]
How to solve the iphone and ipad compatibility problem, when I run the iphone  screen become too big

**Comment by folletto** [comment]
What do you mean?

Are you using a specific CSS selector for iPhone?

**Comment by strong6619** [comment]
why your app could work in both iPhone and iPad? 

my app only can work in iPhone or iPad，i want to work in both of them.

please

**Comment by folletto** [comment]
Yes:
1. Enable the app to be Universal (Device: Universal) from the project settings, as you would do to change from iPhone to iPad
2. Write the CSS rules to apply to different screen sizes as you would do on browsers using media-queries.

If you need more help, just google these two things separately, you'll find plenty of info and tutorials. :)

It's as simple as this. :)
