### ISSUE TITLE
Potential parsing flaw in JSON when edited

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#251]
I had a feedback on another platform by a friend, Renato Gabriele.

Ho fatto un paio di prove ma sono su un altro Mac... ma ho intercettato il problema: che un editor alteri il file nel save (con ascii non "validi" o che falsano il parse del json file) o che tu metta un valore errato (tipo errore di digitazione di true/false tipo tura/falsa) ottieni esattamente lo stesso errore che avevo verificato ieri sera.
Ti confesso che non mi ci ero proprio messo visto l'orario, ma sono 25 anni che vedo succedere cose strane con gli editor ;-) Non a caso, tutti i dev, ne adottano qualcuno no ?

He wasn't able to nail down exactly and provide a file to test, however he found that altering a file with an invalid JSON gives the same error as the one he got by editing it with Xcode and saving. There might be some encoding issue somewhere or something similar:

```
"2011-12-22 12:27:50.416 Baker[5401:b303] Error loading JSON: {JKAtIndexKey = 325; JKLineNumberKey = 13; NSLocalizedDescription = "Unexpected token, wanted '{', '}', '[', ']', ',', ':', 'true', 'false', 'null', '\"STRING\"', 'NUMBER'.";
}"
```

Suggestion from him is to add a JSON parser validator.

**Comment by zenz** [comment]
oops, but normally guarantee the json file to be valid is the provider's job?

**Comment by folletto** [comment]
Yes. But a little help would do no harm. We'll check. :)

**Comment by zenz** [comment]
maybe some unicode problem?
may be he can change some JKParseOptions?

**Comment by folletto** [comment]
Yes. We need to test. :)

**Comment by folletto** [comment]
Issue #226 might be related to this one.

**Comment by Simbul** [comment]
Closing this as it has gone stale.
