### ISSUE TITLE
Images don't Appear after Testing on Device

### ISSUE THREAD

**Issue by digijake** [Simbul/baker#252]
Running the pub in the simulator I see all of the images but not the video (as forewarned) but after archiving and testing the app on my iPad I cannot see some of the images.  Any ideas of what could be happening?

**Comment by zenz** [comment]
take good care of case sensitive. on the simulator, there's no problem, but on the real device. it does matter.

**Comment by Simbul** [comment]
Hi @digijake, is the issue still bugging you?

**Comment by folletto** [comment]
I'm cleaning up the issue tracker, so I'm closing this issue. If the problem re-surfaces, please re-open this issue without any trouble. :)

**Comment by digijake** [comment]
No the issue was fixed...case sensitive

**Comment by folletto** [comment]
Great, thanks! :D
