### ISSUE TITLE
Unload between pages.

### ISSUE THREAD

**Issue by Virtualsweden** [Simbul/baker#254]
Is it possible to unload content between pages to release memory?

**Comment by folletto** [comment]
That's what happen already. :)

**Comment by Virtualsweden** [comment]
OK, what settings do I use for releasing pages?

**Comment by folletto** [comment]
It's automatic, there's no setting. :)

The only thing you can configure is the rendering mode, where "screenshots" is more optimized: https://github.com/Simbul/baker/wiki/Baker-rendering-modes :)

**Comment by Virtualsweden** [comment]
Excellent, now it works perfect :-)
