### ISSUE TITLE
Change UI back ground color...

### ISSUE THREAD

**Issue by teamstar** [Simbul/baker#256]
I need to change the background color to some thing like #e5c889. Do i need to tweak at BakerAppDelegate.m at line localWindow.backgroundColor = [UIColor brownColor];?

**Comment by mutador** [comment]
in the - json file - you have this property for your book, background color, even a background image

  {
    "-baker-background": "#000000",
    "-baker-vertical-bounce": true,
    "-baker-index-height": 150,
    "-baker-index-bounce": true,
    "-baker-media-autoplay": true,
    "-baker-background-image-portrait": "assets/background-portrait.png",
    "-baker-background-image-landscape": "assets/background-landscape.png",
    "-baker-page-numbers-color": "#FFFFFF",
    "-baker-page-numbers-alpha": 0.5,
    "-baker-vertical-pagination": false,
    "-baker-rendering": "three-cards"
  }

**Comment by folletto** [comment]
Did you solve this problem @teamstar? :)

**Comment by teamstar** [comment]
I  did and it says in the console area during'run' that my book has 0 pages... lol.. i dunno if am going to heaven or hell...

**Comment by teamstar** [comment]
I can't seem to solve the v.3 of frame baker so i went back to v2... without the need for .json. Although i am feeling the itch to figure out what went wrong. Another thing. I am truly a newbie in Xcode... is there a guide/tutorial i can follow to add in-App purchase in Baker?

**Comment by folletto** [comment]
About the book, I should have a look at your book/ folder to tell you what was going on.

About the tutorial, I'm not aware of any, sorry.
