### ISSUE TITLE
Images taking a few seconds to render

### ISSUE THREAD

**Issue by joshbaltzell** [Simbul/baker#257]
I have a Baker 3.1 project that uses screenshot mode. When most pages load they show the screenshot, then render the HTMl without the first image, and then show the image a second later. To illustrate this I made a quick video:

http://www.youtube.com/watch?v=JP9Wtf30UYM&feature=youtube_gdata_player

Here is the HTML in question just in case you are curious about how I am loading the image:

```
<!DOCTYPE html>
<html>
   <head>
      <title>Leadership</title>
      <meta name="viewport" content="width=768; initial-scale=1.0;"/>

      <!-- Included CSS Files -->
      <link rel="stylesheet" href="stylesheets/foundation.css">
      <link rel="stylesheet" href="stylesheets/app.css">
      <link rel="stylesheet" href="stylesheets/iPadMenu.css">

    <!--[if lt IE 9]>
        <link rel="stylesheet" href="stylesheets/ie.css">
    <![endif]-->


      <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="twelve columns">
               <div id="navBar" class="container">
                  <ul id="topnav">
                     <li>
                        <a href="#" class="products">Jump</a>
                        <div class="sub">
                           <ul>
                              <li><h2><a href="Book Cover.html">Cover</a></h2></li>
                           </ul>
                           <ul>
                              <li><h2><a href="Tour-01.html">Tour</a></h2></li>
                              <li><a href="Tour-01.html">Believe in Brotherhood</a></li>
                              <li><a href="Tour-02.html">Believe in Giving Back</a></li>
                              <li><a href="Tour-03.html" class="selected">Believe in Leadership</a></li>
                              <li><a href="Tour-04.html">Believe in Family</a></li>
                              <li><a href="Tour-05.html">Believe in You</a></li>
                           </ul>
                           <ul>
                              <li><h2><a href="About-01.html">About</a></h2></li>
                              <li><a href="About-01.html">Who Are Freemasons?</a></li>
                              <li><a href="About-02.html">Famous Freemasons</a></li>
                              <li><a href="About-03.html">Become a Freemason</a></li>
                              <li><a href="About-04.html">History of Shriners</a></li>
                              <li><a href="About-05.html">Famous Shriners</a></li>
                              <li><a href="About-06.html">Become a Shriner</a></li>
                              <li><a href="About-07.html">Shriners Hospitals For Children</a></li>
                              <li><a href="Contact.html">Contact Us</a></li>
                           </ul>
                           <ul>
                              <li><h2><a href="NextStep.html">Take the Next Step</a></h2></li>
                           </ul>
                        </div>
                     </li>
                  </ul>
               </div>
               <img src="images/Leadership.jpg" />
            </div>
         </div>
         <div class="row">
            <div class="nine columns centered">
               <h1>Shriners Believe in Leadership</h1>
               <p>You may be surprised to know that Shriners count among their ranks presidents, senators, local business leaders, professional golfers, country music stars, astronauts and actors. But, we think it's just as important to be a leader in your personal life, to be a role model, to be a sounding board, and to simply be a friend.</p>
               <p>As a Shriner, you will become part of a powerful network of mentors who can help you grow as a man, a father and a husband. You will develop relationships that benefit your business and help you reach your career goals. And you will find that you've become a mentor yourself, passing the lessons of leadership along to the next generation.</p>

               <p><a href="Tour-04.html" class="large blue button radius">See why Shriners believe in family.</a></p>
            </div>
         </div>
      </div>
      <!-- Included JS Files -->
      <script src="javascripts/foundation.js"></script>
      <script src="javascripts/app.js"></script>
      <script src="javascripts/iPadMenu.js"></script>
      <script src="javascripts/jquery.min.js"></script>

   </body>
</html>
```

Any ideas?

**Comment by zenz** [comment]
iPad1 ? which iOS version? I did ever meet the same situation before with my iPad1(issue #204). when updating to iOS5.01, the problem never show again.

**Comment by folletto** [comment]
Wow that's not slow, that's incredibly slow.
However I really have no idea about the origin of that bug. It seems related to something within UIWebView, so it's a bit outside our possibilities I think.

However, let's see...
What size is that image?

_(btw thanks for the AMAZING bug report, that's one of the best I've ever seen)_

**Comment by joshbaltzell** [comment]
The image is 719k. That would seem really large to me for standard web design, but not for loading it locally.

I did create it at 1024 wide even though I am currently only rendering in portrait. I will make them all 768 and compress a little to see if it helps.

**Comment by joshbaltzell** [comment]
@zenz: That is in the simulator. But you did make me notice that my simulator is running iOS 5.0. When I run it it says this in the toolbar:

"iOS Simulator - iPad / iOS 5.0 (9A334)"

I don't think my software is out of date is it?

**Comment by joshbaltzell** [comment]
Image resizing made no difference. I am using an animated gif in the upper left. I wonder if that is creating some weird situation in UIWebView. I am testing now.

**Comment by joshbaltzell** [comment]
The animated GIF was not the problem either. I replaced it with a static GIF and I still have the same problem.

**Comment by folletto** [comment]
@joshbaltzell Thanks, you're doing a great debugging work. :)

But did it do the same on the device as well? :)

**Comment by joshbaltzell** [comment]
@folletto I made sure to uninstall the app on my test iPad and iPad2 (both running 5.0.1) and everything looks like it is working just fine on the physical devices. I have seen this happen on a live iPad before though, I guess it is possible that I was seeing that before 5.0.1 came out, but I am fairly certain it was more recent than that.

I looked at the 5.0.1 release notes and there is nothing browser related. Hmm...

Now I am worried that people running 4.3 or 5.0 are going to have issues with my app. Do you think it is just a simulator problem?

**Comment by folletto** [comment]
I never found that out, but it might well be: the UIWebView in the Simulator is similar but not the same of the one shipping on the actual device, they perform differently and sometimes they have slight differences popping up.

I never encountered that problem myself, so I can't tell, but that would be my guess, yes.

**Comment by Simbul** [comment]
Hi @joshbaltzell, looks like the discussion is quite old now. Have you managed to find out whether anyone on 4.3/5.0 has had problems with your app?

**Comment by folletto** [comment]
I'm cleaning up the issue tracker, so I'm closing this issue. If the problem re-surfaces, please re-open this without any trouble. :)

**Comment by joshbaltzell** [comment]
I had this issue come up again in 5.1 on the iPad itself. It looks to be a height bug of some sort. If I put enough content to make it to the bottom of the screen the issue goes away. I added a div named "takeUpSpaceToFixHeightBug", gave it some height and the problem went away.
