### ISSUE TITLE
@font-face support broken after iOS 4.2 update

### ISSUE THREAD

**Issue by davidex** [Simbul/baker#26]
I'm quite sure it could be an OS-related problem, so not related with Baker, but anyway: I'm working on a project where I include a font with @font-face and after updating to 4.2 (both SDK and iPad) the @font-face support seems gone.

Anyone experiencing the same problem?

**Comment by Xm4s** [comment]
Hi,
I've made a little experiment with @font-face and I was able to embed a truetype font in my .html page within Baker successfully.

Unfortunately I couldn't made a test on an actual iPad device, however both iOS 4.2 simulator and my iPhone with iOS 4.2 showed no problem with embedded fonts.

So, maybe you should check out your @font-face element and/or your font files.
As a reference try this site: http://www.fontsquirrel.com/fontface/generator, I think it can provide all the help you need to embed your fonts :)

I'm leaving this up till a test on an actual device is done, just to be 100% sure.

**Comment by botic** [comment]
Works fine on my iPad and in the Simulator, so I don't see a problem with iOS 4.2 or Baker.

**Comment by davidex** [comment]
ok, thanks for the feedback guys.
I cleaned up provisioning profiles and recompiled, everything's fine now.
