### ISSUE TITLE
simple footer - iframe whit js

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#261]
you can put the js in a external js , and only use the name of the div, its simple but works fine for a footer in all pages or a html include in diferents pages, if someone have others ideas?

http://magmagoo.com/baker/iframeipad_safari.html

view the code in this page

**Comment by folletto** [comment]
Hi @mutador, I'm cleaning up a bit the issue tracker so I'll close this old message since nobody answered. 

I'd say: if the technique works, go for it. ;)
