### ISSUE TITLE
Tiled Screenshots

### ISSUE THREAD

**Issue by Xm4s** [Simbul/baker#262]
Hi!

Since rendering too many screenshots at the same time could be quite hard for the iPad, I've just implemented a class to render them with tiles.

I've tested the class outside Baker with 5000 screen sized pictured images and the iPad seems to perform rather well (for starting it doesn't crash for lack of memory :D )

The updated project is on the branch "[tiled-screenshots](https://github.com/Simbul/baker/tree/tiled-screenshots)".
I'd like your help to do some tests with Baker, to see if this can be used on the master branch.

Thank you very much :)

**Comment by zenz** [comment]
Oops, the effect is so... magical. :)

**Comment by mutador** [comment]
hi i tested it and whit my book whit some script crash, with this kind of code @-webkit-keyframes  for animations in pages crash.
i don´t like the effect,  and with this actualization i have the old problems of the black/white flashing is some pages.( i hate, i was a lot of days whit this trouble and i don´t like in my live again)

but in mode three-cards this actualization is better, more faster....

thanks

i am working now whit this kind of animations in the book, and with the new baker the time of rendering intercept whit the time of the animations, but this is only my problem....
http://addyosmani.com/blog/css3transitions-jquery/
http://jsfiddle.net/addyosmani/BFeMN/show/

have you tried to load all the pages  before release it as pugpig, but also pugpig fails with large magazines, when begins load videos , a lar content, scripts etc...

This is the great problem of baker.  apple may have to settle with his ipad apple-safari and memory management and rendering of html.

**Comment by mutador** [comment]
http://kindmags.com/  (aquafadas-quark solution)
this is another solution, they show you a prerendering screenshoots but not a full quality.
is possible make screenshoots prerendering of all the book like pugpig but in 50% of quality, when you are looking trhoug the book, you´ll see all the pages in a blur efect (50%of quality) and when you stopped in one, they make the full loading.

threecards is the best solution for big magazines whit a lot of video and scripts, dont crash, but a prerendering in small size of the all pages can be an idea

**Comment by Simbul** [comment]
Closing this, as we decided not to go through with it in the end.
