### ISSUE TITLE
Libraries for Baker (tested in Baker + iPad)

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#263]
interactivities compilation tested and work well in baker + ipad

circle slider -http://www.baijs.nl/tinycircleslider/

drag and drop - http://www.gotproject.com/blog/post2.html

music player -http://jplayer.org/latest/developer-guide/

scroll in page - http://cubiq.org/iscroll

code animations whit keyframes - http://addyosmani.com/blog/css3transitions-jquery/   ( you can use this for make fade in and animation pages whit a diferent and predefined animation js, very recomended see and understand how it works)

**Comment by folletto** [comment]
Uh? What's the problem here? :)

**Comment by mutador** [comment]
NO any problem for this time, a boy ask me for interactions i use in  http://www.omgod.es/app and i decided share it if they are of use to people

**Comment by folletto** [comment]
Ok then. :)

I'd suggest then to just edit the text above to include a small introduction of the content of this topic. ;)

**Comment by ghost** [comment]
Mutador! Excellent work!  love the circleslider. might use it for selecting stylesheets in what we're doing.

I might have to dl your mag just to see examples (nothing else though! LOL).

**Comment by folletto** [comment]
I created a wiki page from the libraries suggested here:
https://github.com/Simbul/baker/wiki/Libraries-for-baker
