### ISSUE TITLE
App rejected due to iOS Data Storage Guidelines

### ISSUE THREAD

**Issue by nurtext** [Simbul/baker#266]
My baker-based app just got rejected due to the iOS Data Storage Guidelines:

2.23 Apps must follow the iOS Data Storage Guidelines or they will be rejected
https://developer.apple.com/icloud/documentation/data-storage/

Any ideas how to solve this? I even wasn't using pre-rendered screenshots or anything else not included in Baker.

:-(

**Comment by nurtext** [comment]
It seems the baker snapshots that gets created dynamically (if not provided within the book) cause the trouble. They are stored within the Documents path and that's clearly against the guidelines. I've written a small fix that uses the Caches path instead and will pull it into the repo.

**Comment by nurtext** [comment]
Damn forget about it… seems I used an outdated version of baker…

**Comment by folletto** [comment]
I like so much self-solving problems. :)

@nurtext, if you have any other problem we are here. ;)

**Comment by nurtext** [comment]
@folletto As much as I like them :)

Anyway… have been able to test the source from my pull request?

**Comment by folletto** [comment]
We are going to do our weekling progress meeting next monday, we had to skip this week for personal problem, mostly translatable in "impact from coming back from holiday". We'll check it on monday evening. :)

**Comment by nurtext** [comment]
Great, didn't even know you're doing progress meetings on a regular basis :)
