### ISSUE TITLE
Playing Audio in iOS 4.3

### ISSUE THREAD

**Issue by nruffilo** [Simbul/baker#267]
I'm having an issue with audio.  I have an activity where 4 sound files play in succession.  In iOS 5, and latest safari, things play wonderfully, but in 4.3(.2) things aren't working.  I'm not sure if this can be solved in baker or not.  

Below are the MANY solutions I have tried.  It should be noted that playing ONE sound file on a page is not a problem.  I have Voice Over audio playing on page-load for most of my pages and that works fine.

If you can think of a way to get this working, let me know.  All of the below methods work perfectly in 5.0 and latest desktop safari, just not in iOS 4.3 simulator/device:

1) Have a hidden div, set innerHTML = an <audio> tag with the appropriate src file
1a) onended -> clear div innerHTML, load next audio file
1b) setTimeout, delay 2 seconds between each file (which is 1 second long) then load next sound
2) Hidden div, set innerHTML = 4 audio tags
2a) onended -> .play() next audio file
2b) setTimeout -> .play() next audio file
3) replaced <audio> with <embed>
4) replaced <audio> with <object>

The behavior is best described as "wonky" in Baker.  Sometimes only 1 sound will play, others two will play, rarely 3.  Sometimes the first will repeat 4 times (while the debug displays that 4 different sounds should have played)

Below is the debug output of when I set the innerHTML to 4 audio tags, then use a set-timeout (1.5 seconds between each, 1 second sound) to play the items one at a time:

2012-01-05 14:42:18.342 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/B.m4a
2012-01-05 14:42:19.860 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/A.m4a
2012-01-05 14:42:19.863 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/B.m4a
2012-01-05 14:42:21.357 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/D.m4a
2012-01-05 14:42:21.361 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/B.m4a
2012-01-05 14:42:22.866 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/C2.m4a
2012-01-05 14:42:22.870 YFEB[16749:b903] setting movie path: file:///Users/druffilo/Library/Application%20Support/iPhone%20Simulator/4.3.2/Applications/B17831DA-83BB-49FC-BEEC-669282EC063A/YFEB.app/book/media/notes/B.m4a

Note that its playing more than 4.  Again, this works perfectly in iOS5 and desktop safari.  

Any help would be appreciated.

**Comment by nruffilo** [comment]
To add: I've changed the delay to 5 seconds between each sound and they STILL do not work.  I have the controls visible (for debugging) and the audio is done playing, and when the 2nd one goes to play it just says: "loading" then the 3rd one actually plays (visually) but 50% or so of the time it will play the first note instead of third, even though the 3rd control is playing...  Tried adding a ".pause()" before the play of the next audio - didn't work.  Again, having them all loaded, or overwriting the previous both had the same effect.  I've even tried changing the src of the one audio element.

As a small addition - there seems to be HUGE lag for the first audio in the book to load.  After that, all audio plays fine, but the first sound file played has a 1-5 second lag.  Any ideas on that as well?

**Comment by nruffilo** [comment]
Seems try #7 was a winner.  

1) Created a new audio element
2) Used setTimeout to call a "setAudio" function with 2 seconds delay for each audio element i wanted to play
3) the setAudio had the following code:
document.getElementById("snd").pause();
    $("#snd").attr("src","media/notes/"+srcFile+".m4a");
    document.getElementById("snd").play();

That seemed to work fine in 4.3 and 5.0.  Still worth noting that first audio played has massive delay.

**Comment by nruffilo** [comment]
Nope - resetting the SRC is more accurate, but still not perfect.  I'm getting some ghosting (playing of previously loaded src) every now and again.  So I'd say this is still an issue.

**Comment by folletto** [comment]
I can give you three pointers:
1. Did you try on Mobile Safari - without Baker. Does it do the same?
2. It seems a Mobile problem more than a Baker problem, did you try asking on StackOverflow?
3. It seems that you are controlling everything via JavaScript. Then... why are you creating DOM elements? Why don't you just:

```
var a = new Audio("file.m4a");
a.play();
```

That's all, I hope it helps... :)

**Comment by nruffilo** [comment]
I have exactly the same issues using new Audio...  I'll try StackOverflow....

**Comment by nruffilo** [comment]
To add to this, sometimes it crashes (in simulator) with the following:

 #import int main(int argc, char *argv[]) { NSAutoreleasePool \* pool = [[NSAutoreleasePool alloc] init]; int retVal = UIApplicationMain(argc, argv, @"UIApplication", @"BakerAppDelegate"); [pool release]; return retVal; } --- Thread 1: Program received signal: "EXC_BAD_ACCESS".

**Comment by nruffilo** [comment]
I found a solution that has yet to fail...

I created a global audio control: var a=new Audio();.  Whenever I wanted to play a sound I did: a.pause(); a.src='newfile.m4a'; a.play();

**Comment by folletto** [comment]
That's fascinating! :o

**Comment by Simbul** [comment]
Hi @nruffilo, I hope the solution in your lates post is the one that finally did it. Would you say that we can consider this issue closed then?

**Comment by nruffilo** [comment]
Yups it can be closed
