### ISSUE TITLE
Its possible to hide URL when download book?

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#268]
Hi, when i download a book always show the url, is possible to hide this and only appear "Do you want to download the book? Cancel / Open book"

thanks

**Comment by folletto** [comment]
Sure, but you have to manually edit Baker. Open RootViewController.m, find the function `downloadBook` (around line 1373) and replace this:

```
message:[OPEN_BOOK_MESSAGE stringByAppendingFormat:@"%@?", URLDownload]
```

To probably something like:

```
message:@"Do you want to download the book?"
```

However, be careful with that, because the user will not have anymore any indication of what's being downloaded. :)
