### ISSUE TITLE
Adding in App Puchase into baker

### ISSUE THREAD

**Issue by teamstar** [Simbul/baker#269]
Is there anyway to insert in-App purchase into Baker framework?

---

_UPDATE FROM THE BAKER TEAM_: please take notice that x24dotbiz, who has commented below with a solution, has been **reported as a scammer** - read the whole thread for more info.

**Comment by teamstar** [comment]
@folletto: How do i pass the book to you to see what went wrong?

**Comment by folletto** [comment]
Send to the Baker email address: info@bakerframework.com :)

**Comment by teamstar** [comment]
Can you keep me in the loop once you have a solution? I would really appreciate it.

**Comment by Simbul** [comment]
I think it would be interesting for everybody to hear more about this solution. Keep us posted! :)

**Comment by teamstar** [comment]
So how mate? Did they charge expensive for the In-App inclusion in the baker framework?

**Comment by nin9creative** [comment]
So what did they do?  Modify your code to have a shelf and in app purchase?  Would be interested in seeing how they restructured baker to be launched from the self...

**Comment by nin9creative** [comment]
I guess my question is what did they exactly do? Is there now a shelf view with the ability to download and purchase new titles?

Andrew

**Comment by nin9creative** [comment]
Does it work on the iPad?

**Comment by nin9creative** [comment]
Can you email me?  I have a few questions.  Thanks!2

**Comment by nin9creative** [comment]
Won't anything other an App Store In App purchasing get denied by Apple?  Regarding your comment about PayPal, Credit Card or over The App Store?

**Comment by nin9creative** [comment]
Don't anyone fall for @x24dotbiz solution above.  I was curious as he sent screenshots of an in app solution that seemed to look really good.  HOWEVER after I paid him to send the same code to me (as I had a pressing need for a solution) he sent me the exact same bit of code that can be found on this website http://www.brightsolutions.de/blog/implementierung-eines-inapp-stores-auf-dem-iphone-1-2 

Which is not the same as what he sent in the screenshot below. 

http://dl.dropbox.com/u/14238775/Baker/inapppurchase.jpeg

Apparently people cannot be trusted.  Please avoid dealing with this scammer.  Hopefully I can get my money back through PayPal.

**Comment by folletto** [comment]
That's depressing. Thanks for the report @nin9creative.

**Comment by nin9creative** [comment]
Yeah, I feel like quite the fool. Got scammed out of $350 for this "solution"....

And what was sent was such a basic bit of In App purchase code that is not at all what he sent screenshots of....

**Comment by Simbul** [comment]
I'm sad to hear that, @nin9creative. I've edited the first post in the discussion to warn off people reading this thread for the first time.

Good luck with Paypal!

**Comment by tekdope** [comment]
Hi Guys, any news on in-app purchase integration?

**Comment by folletto** [comment]
Any update will be posted here, so... no, no news. If you check the Milestones above, you'll see that right now we are working on everything else to have Newsstand in place first, release it, and then we could start looking at it. ;)

**Comment by tekdope** [comment]
@folletto Thanks for the head up :)

**Comment by Simbul** [comment]
Closing this as In-App Purchases are now in the `master` branch.
