### ISSUE TITLE
Google Map Inline Issue

### ISSUE THREAD

**Issue by Bitography** [Simbul/baker#270]
Howdy folks. Your framework is excellent. Great xcode! Thank you very much. Been testing it for a couple of months and this is my first Issue using an iPhone 3g iOS 4.2 [I haven't tested it with anything else but the desktop, which works naturally]

The Google Maps inline code (direct from maps) works initially perfectly in the page as it does on the desktop-- but then always crashes the app (after a  level 2 memory warning) at ~30 seconds into running the app, weather I am on that page or not -- and weather there are many pages in my book or just the one and weather there are many images or not and a fast wifi connection or not. None of that seems to matter. I am not loading any other external javascript and simply using the code provided by google maps 'embed link' button. Yes, offline maps are a very important component to my current project and I'd love to use Baker! Help?

**Comment by Simbul** [comment]
Sorry for not getting to your issue sooner. Have you managed to find a solution?

Alternatively, you could send us the code so we can try and replicate the issue.

**Comment by folletto** [comment]
I'm closing this issue since there is no answer. Feel free to reopen it if you'd like to continue. :)

**Comment by Bitography** [comment]
Yes, I appreciated the reply and I am still working on this issue-- and No I haven't found a solution yet, but I am trying a few more things before I resort to sending you the code (thanks for offering). I'll be back in a few days.

**Comment by folletto** [comment]
Mind that the solution might not exist: from the message above it seems you are using an iPhone 3G with an old OS version, that means that there might not be enough RAM to allow it to run, and unfortunately we won't be able to test it on that hardware.

Comment and re-open this issue when you are ready. :)

**Comment by Bitography** [comment]
Yes, ok. Thank you again for the prompt replies. It's the newest OS for that particular phone, which there are still many users of, so my aim was to get maps to work-- although if it won't, I will have to resort to some workaround and iOS detection in the code for older phones. Perhaps my struggle should be focused on phone/iOS detection instead of getting maps to work inline on these older phones! I think you will agree but I'd like to keep trying for a little longer :)

**Comment by folletto** [comment]
I agree... but I can also see that sometimes you really want to make it work, so I understand your effort as well. That's great. :)

Keep us updated. :)
