### ISSUE TITLE
App icon dont apear when newsstand flag is off

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#271]
Hi. After i hade some troble submit na app with newsstand on i try to put newsstand off and apple receive the app. But after i run on ipad there is no icon? I have the basics that came on baker 3.1 - ios-icon-ipad72 / ios-icon-iphone57 and ios-icon-iphone114.

**Comment by zenz** [comment]
You can select App icons on Targets->Summary page.
Or, you can follow apples' suggestion to use:
Icon72.png
Icon.png
Icon@2x.png
for default icons.

**Comment by Simbul** [comment]
Hi @xiripi, did @zenz's suggestion solve your issue in the end?
