### ISSUE TITLE
create the first App!

### ISSUE THREAD

**Issue by nerena88** [Simbul/baker#272]
HI guy!
Sorry but I have a stupid question!
I have already create an app by quark/apple (and ind/apple), and I'm capable write in html/css and i would try Baker!

This is my stupid question:

After that i have create the folder (inside ther are: the xcodprog, the folder book, ect...)
How can i change "the folder" to ".ipa" (usually when i create the app on quark or ind, I export and i have an only file that i send to apple, and apple give me a ".ipa")
But in this case i have a folder!

Please can somebody explain how i do?

**Comment by folletto** [comment]
You have to start with some Xcode tutorial: the process of creating an app with Baker is the same of creating an app with Xcode, Apple's standard tool. Check their documentation, tutorial and guidelines.

On Baker's side, you can read this tutorial: http://bakerframework.com/tutorials/30/basic :)

**Comment by nerena88** [comment]
yes, I have see my "app" on xcode simulator, I followed the guide by your link!

but when I'm on the xcode I need to export the file to create my app?

**Comment by folletto** [comment]
It's the last part of that tutorial: "Publish on the Apple Store". :)

**Comment by nerena88** [comment]
OK, but I upload the folder?

**Comment by folletto** [comment]
Uhm probably I'm not understanding where you're stuck. From the tutorial page:
1. You have to prepare the application from the [iTunes Connect website](https://itunesconnect.apple.com/).
2. You have to create the compiled application for Release, following the instruction from the [iOS Provisioning Portal under Distribution](http://developer.apple.com/ios/manage/distribution/index.action).
3. You have to upload the compiled application.

Did you already do part 1 and 2 of that part of the tutorial, following all the Apple instructions to prepare the application for publishing? Where are you stuck?

**Comment by nerena88** [comment]
I'm stuck in the "3"!!
I go on "application loader" but I upload the "folder" (because the other thimes I upload Only one file ".ipa")

**Comment by folletto** [comment]
Ok...

Let's see... I think you're missing some steps from the Apple tutorial: once Xcode built for Releaase, you have an ipa ready to be uploaded, the tutorial should have told you that.

That said... there's an alternative way to do that. Try following this other tutorial, where you Build and Archive and you use Organized to upload to iTunes Connect:
http://www.weston-fl.com/blog/?p=2442

More info on that method on the official documentation here:
http://developer.apple.com/library/mac/#documentation/ToolsLanguages/Conceptual/Xcode4UserGuide/DistApps/DistApps.html

**Comment by nerena88** [comment]
yesssssssssss!
Great!
For this reason i seid "is a stupid question", I have lost something! ;D

The other times, I have use Xcode only for see on simulator because ind or quark export for me the necessary file!

Ok I try following the guide!

Thank you very much! ;D

**Comment by folletto** [comment]
You're welcome.

If this tutorial works, please come back and tell us, so we can see if we can update our tutorial as well. :)

**Comment by nerena88** [comment]
sure!
thanks again for your time!

When I finished the app,I give you the link, so you tell me what do you think ;D

**Comment by Simbul** [comment]
Hi @nerena88, any progress with that? :)
