### ISSUE TITLE
Confused with the previews

### ISSUE THREAD

**Issue by ManelSoria** [Simbul/baker#273]
I'm beginning to experiment with Baker. I have little experience with html and I programmed a small app for iphone.

My problem: I'm confused with the previews that baker generates and stores. Sometimes that don't change when I change the html files. Then, for a couple of seconds, I still can see the old screen while the new is rendered. The problem persists even after many reloads, even quitting or (I think) deletting the app.

Am I doing somthing wrong? Is a point in the code where I can force the code to discard all the old previews ? 

Another question: there is a "-baker-page-screenshots" property that seems I could use to pre-render all the pages. How can I do so and save the images ?

Thanks for the very good job !!

**Comment by Xm4s** [comment]
Hi urquinaona!

Preview images, or page screenshots as we usually call them, are taken by Baker as soon as a page is loaded for the first and then stored for future usage.

If you change a page its screenshot, if already taken by baker, doesn't change. To update the screenshots you have to delete them and have Baker regenerate them anew.
Deleting the app of course remove all the screenshots :)

If you want you can provide all the screenshots for your book manually, you just have to take them, include their folder in your book and then specify the folder path in the "-baker-page-screenshots".

To take the screenshots for you Baker book you can use ... well, Baker :)
Follow [this guide](https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book) on our wiki, you'll find all the info you need to accomplish the task.
