### ISSUE TITLE
How can I support iPhone and iPad simultaneously?

### ISSUE THREAD

**Issue by shinji310** [Simbul/baker#274]
It seems like the Baker Framework provides pretty nice features supporting iPhone and iPad.  However, I could not find any info about supporting iPhone and iPad simultaneously.  I am not trying to really optimize everything to each of the device.  Also, I rather not to have two apps to suppor them.

It would be nice if someone could point out a general instruction to implement such an app.  Anyone?

**Comment by folletto** [comment]
Sure, have a look here and tell us if it works:
https://github.com/Simbul/baker/wiki/Publish-on-ipad-and-iphone

**Comment by shinji310** [comment]
Thank you for a quick response.  I thought I went through the wiki.  Sorry but somehow I missed the page.  I will review the instruction carefully.

**Comment by folletto** [comment]
Ah I'm sorry! I meant that I added it when you asked the question, that's why you didn't see it. It wasn't there, it is now thanks to your feedback. :)

**Comment by shinji310** [comment]
Wow.  That is cool.  I appreciate your support very much.

**Comment by Virtualsweden** [comment]
But I am kind of missing the function that PugPig has that scales down pages to the iPhone.

**Comment by folletto** [comment]
I don't think we are going to implement it, sorry. I believe that to provide a good experience you have to support the reader at your best and downscaling isn't really a great solution for the reader.

But of course, feel free to add that feature yourself if you want to. :)

**Comment by airtek** [comment]
In your opinion there is problem with ipad3 with the resolution of 2880 px ? It's the same like iphone 4s and iphone 4 ( retina display).

How you manage this in the content ? I think that the CSS media query are only a part of the solution, for the main structure , but for the content, like the images?

**Comment by folletto** [comment]
Well, you can do all with the `media-queries`, just select the right image via CSS and display it. Also, most of the time you don't even need to do that if you just resize the image properly: since the image is already there and you don't have bandwidth constraint, it will just work.

Otherwise there are other techniques like JavaScript replacement. All of these and a lot of tutorials should be available if you search around the keyword "responsive design". :)

**Comment by airtek** [comment]
Latest question:

During the application design I'm thinking about the possibility of offering a single app for ipad and iphone.

With baker is possible to enable the orientation change only with ipad and not with iphone?

**Comment by folletto** [comment]
You have to write that custom code by yourself, it's not in there by default. However, you can just add padding on the iPhone when it's turned. ;)
