### ISSUE TITLE
[HPub] howto define a multi-level content structure

### ISSUE THREAD

**Issue by Chralu** [Simbul/baker#275]
Hi,

First of all, thanks for sharing that very handy project.

Now, let's expose my issue :)

I have to create a publication with chapters, each chapter containing multiple pages.

The right/left scroll must navigate between chapters title pages, and the status bar must
navigate between the chapter's pages (like the "Our choice" iPad application).

As you defined a HPub standard, it would be a shame that I do not follow it.

So, here is the question : is there a standardized way to define a multi-level content structure in "book.json" file ?

Thanks,

**Comment by folletto** [comment]
A single Hpub works as a single book, with just horizontal swiping and vertical scrolling. There aren't multiple levels. :)

Baker uses a different model from Our Choice, where the "status bar" is really the content itself. the page itself. You can simulate quite easily in JavaScript however: just add another scroller on the "chapter" page and zoom in on touch. :)
