### ISSUE TITLE
Swipe and double tap in pure HTML (Safari)

### ISSUE THREAD

**Issue by lithos77** [Simbul/baker#276]
When I try Laker on iPad or iPhone (iOS 5.0) Safari, the swipe between pages does not work (both in three cards both in screenshot rendering mode) as well as the double tap to bring up the TOC. The Laker and Baker versions of the framework are the latest.
Apart from this problem, congratulations for the project, wonderful!

**Comment by folletto** [comment]
It's really hard to tell what's happening. Does your page intercept touch events? What's displaying? What's in the logs? :)

**Comment by lithos77** [comment]
Ciao Davide,
Swipes and double taps work normally after building the app with Xcode and viewing it in simulator: logs are all correct. The problem occurs only in Safari on iPhone or iPad, where other javascript plugins and jquery code function as expected. 
I would use laker/baker as a web app also.

**Comment by folletto** [comment]
Ahh! Sorry, I misread it.

It doesn't work in Safari because these are only your pages. The way you do that is by building an index page that works well as the starting page and each other page is linked to that, so you can read it. :)

**Comment by lithos77** [comment]
As you can see at http://www.futuraweb.eu/book/ viewing it in mobile safari swipes and taps do not function. Debug console say no errors.. Thanks.

**Comment by folletto** [comment]
Yes: it's HTML, there's no swiping on HTML pages. :)

But as you can see you can build an index page with media-queries and click to the specific page, allowing your book to be readable on the web with minimal effort.

Or, you might want to add some kind of javascript library helping the user to navigate between pages. Up to you. :)

**Comment by lithos77** [comment]
You're right. When I've been finished I'll show you the result. Thanks.

**Comment by Simbul** [comment]
Hey @lithos77, any news on that yet? :)

**Comment by mutador** [comment]
i have this problem in some pages, when tap dont go the next/previos page and doble tap go to next, next page...two pages...
iuse ipad 1, threecards and ios 5

you can test it in my new book, you´ll know how you get?....

**Comment by folletto** [comment]
Hi @lithos77 I'm closing this issue since there are no new developments, but if you come back please feel free to reopen it and go ahead with the discussion. :)
