### ISSUE TITLE
error in xcode with baker 3.0

### ISSUE THREAD

**Issue by wijeweera** [Simbul/baker#277]
Greetings.
Took time using baker, I have now upgraded the operating system, the corresponding xcode and I have updated the version of baker, now I have some problems not solved.

Baker If I use 2.0, I get the following error:

Instance method '-connection: didFailWithError:' not found (return type defaults to 'id')

If I use the latest version of the baker, the application runs, but the simulator screen appears totally black.

Someone could help me?

Thank you very much.

**Comment by Simbul** [comment]
This could be really due many different reasons.
As a first step, I can suggest thoroughly cleaning the build: remove the Baker app from the simulator (use the home button to go back to the home screen and remove the app as you would remove any app on the iPad) and clean the Product in Xcode (cmd+shift+K).

**Comment by Simbul** [comment]
Hi @wijeweera, did you manage to solve your issue?

**Comment by wijeweera** [comment]
yes everything works fine. thank you very much.
