### ISSUE TITLE
How to stop a sound/music when changing the page

### ISSUE THREAD

**Issue by marciosm** [Simbul/baker#278]
Hi. I tried to find another issue where could be an answer for my doubt. I have a music background started by a button. I wanted that it stops when my reader change the page. Is that possible? Tks a lot. All the best.

**Comment by folletto** [comment]
Did you try using screenshot mode? :)
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

**Comment by marciosm** [comment]
Tried now and works. Tks. But I lost the tree cards function that I love so much... snif snif
If I do not find any other way, this will be the solution. Tks a lot!!!

**Comment by folletto** [comment]
For information, why did you like it? :)

However, the implementation of Issue #225 will solve your problem when it's ready. :)
