### ISSUE TITLE
Problems to share a test version

### ISSUE THREAD

**Issue by ManelSoria** [Simbul/baker#279]
Hi,

This is not only related with Baker as I'm having the same problem with other apps but I would appreciate your kind help. 

I can run apps on my devices from Xcode, but I can't share a test version. Well, I share it but iTunes can't transfer it to the devices of the testers.

It seems I can't sign the apps, but I have the certificates in my Keychain access.

In Xcode/Organizer/Archives, i choose "Share", then ".ipa" and my identity, the same as in the valid certificate as I can see it in Keychain Access

app.ipa file is generated with no warinings, and then:

$ codesign -dvvv app.ipa
app.ipa: code object is not signed at all

Any idea ? Should I delete and try to generate again the certificates ?

Thanks !

**Comment by folletto** [comment]
Are you using the right Distribution certificate? I don't think you can use the Developer certificate. However it's probably better if you ask feedback on Apple Dev forums or in the Xcode part of Stackoverflow. :)

**Comment by ManelSoria** [comment]
Will ask .. I have asked in Apple Dev but maybe my question is too easy or my Eglish too bad :)

The only certificate I have is the "iPhone Developer". Should I have/use another ?

Thanks for tour quick answer and your nice software !

**Comment by folletto** [comment]
Have a look at TestFlight then, you might find it VERY useful, and it has also tutorials to help you:
http://testflightapp.com
