### ISSUE TITLE
interactive Maps / Elements  vs. pagescrolling/tapping

### ISSUE THREAD

**Issue by vanderbreye** [Simbul/baker#28]
Baker is GREAT WORK, thanks you!
But i wonder how the implementing of maps or interactive swipe / drag guestures could be improved? As far as i can see in the emulator, an embedded map i.e, is always fixed 

All swipes / scrolls / taps are directly given to the page-move-mechanism.. is there a way to fix that, or am I missing something?

**Comment by folletto** [comment]
It might be related to the way we intercept the events...

Do you have an example page to provide with an embedded map that have those problems?

**Comment by vanderbreye** [comment]
just embed a classic google-map (via iframe)  or a mapstraction.com-map (via div) in the 1.0 release - 

<iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/?ie=UTF8&amp;t=h&amp;ll=37.09024,-95.712891&amp;spn=33.435463,56.25&amp;z=4&amp;output=embed"></iframe>


mmh - maybe its just a problem of the emulator? i can access some of the controls, but not the map-moving/zooming/pinching-features. is it possible to get some objects over the interception-layer?

**Comment by folletto** [comment]
I think it's something we are trying to figure out, since there are a lot of overlapping events. Any help is welcome. ;)

**Comment by snive** [comment]
I've managed to add a scroll to a special DIV using the iScroll at http://cubiq.org/iscroll
And by not preventDefault on touchmove you can still use the swipenavigation outside the div.
But I still have'nt solved the problem to have a fixed header or footer div

**Comment by folletto** [comment]
Wow nice workaround! :)

Even if I think it's not something that would work on Google Maps, right?

**Comment by snive** [comment]
I'll try to test Google Maps with this and post my result in the future

**Comment by snive** [comment]
google maps javascript include works nice, but the user need to be online

**Comment by folletto** [comment]
Hehheheh yes, I think that it's unavoidable. :)
Thanks for the feedback. :)

**Comment by snive** [comment]
;)
