### ISSUE TITLE
Apple to announce tools, platform to "digitally destroy" textbook publishing

### ISSUE THREAD

**Issue by mpena2099** [Simbul/baker#280]
................................
Apple to announce tools, platform to "digitally destroy" textbook publishing

Apple is slated to announce the fruits of its labor on improving the use of technology in education at its special media event on Thursday, January 19. While speculation has so far centered on digital textbooks, sources close to the matter have confirmed to Ars that Apple will announce tools to help create interactive e-books—the "GarageBand for e-books," so to speak—and expand its current platform to distribute them to iPhone and iPad users.

(...)

More in http://arstechnica.com/apple/news/2012/01/apple-to-announce-tools-platform-to-digitally-destroy-textbook-publishing.ars
................................

Any idea what's coming? Will help or kill our job here? :)

**Comment by folletto** [comment]
If they do something like that, it will be along the lines of what we did with this project, and it will be great. We released this because of our vision for the iPad to be a great digital book platform, and if Apple does that for everyone, with the skills and resources they can execute with, it would be great. :)

As for your question, I really don't like to add hypothesis to rumors. ;)

**Comment by Simbul** [comment]
Yeah, we'll know soon enough anyway ;)

**Comment by zenz** [comment]
I think apple is just want to release a tool to create iBook epub or something more advanced for iBook?

No matter how, it's a good thing.

**Comment by mutador** [comment]
http://www.apple.com/education/itunes-u/

**Comment by folletto** [comment]
iBooks 2:
http://t.co/rpFKxeTJ

iBooks Author:
http://t.co/diou3p0M

They look wonderful. :)

**Comment by mutador** [comment]
but now? it´s only for education, what happend whit magazines?
i testetd, and it´s not viable for magazines,long life baker...but whit newsstand integration, pleased...

**Comment by zenz** [comment]
newsstand is not only an icon in the newsstand folder, it should combine with in app purchasing & background downloading. there's a lot of works to do.

**Comment by folletto** [comment]
Hey don't deviate every discussion about that! :D
Spend time finding developers if you need it. :D :D :D

**Comment by mutador** [comment]
we try, but spain is not the place, we talk whit @mpena2099  and friend , and we waiting for ....

**Comment by mpena2099** [comment]
Yes @zenz, lot of work to do! @mutador... we are working on it. :)

iBooks Author??? Downloading! ;)

**Comment by jameskatt** [comment]
I'd love to see a tool to de-construct the iBook Author file so that the components can be re-purposed by placing them in Baker.

**Comment by zenz** [comment]
the ibook which created by iBook Author is just a zip file, you can easily analyze it.
Apple defined this minetype as application/x-ibooks+zip

**Comment by aroop** [comment]
ibook create by iBook Author is in a format which is apple specific. Its not epub 2 standard or epub 3 standard

**Comment by millr88** [comment]
Watch your rights with using iBooks creator. Apple owns the content, and you can't resell your work anywhere else according to the shady EULA.

http://www.informationweek.com/news/software/productivity_apps/232500227

**Comment by folletto** [comment]
Not exactly, even if it's still weird: http://daringfireball.net/linked/2012/01/19/unprecedented

**Comment by mpena2099** [comment]
For us the question is: it's time to change Baker to this new format, try to use ePub3 or HPub is enough?

**Comment by folletto** [comment]
- EPub3 is a new standard (october 2011) with no real backing as of today and with a very specific focus "The design center of EPUB is dynamic layout", so it means: no precise pagination, layout or else. You have no control and it's their will: http://idpf.org/epub/30/spec/#sec-access-layout.
- iBook 2 uses a set of proprietary over EPub3, making it a format that's not anymore EPub3... exactly to compensate the lacking parts of the EPUb3 standard above. What puzzles me is why they didn't use HTML, but that's another question.
- HTML5 is a universal web standard that supports both flowing and not flowing text, precise pagination, has the widest and most developed market existing today and developer tools, plus the engine is already ready and updated out of the box by Apple. _HPub is just a zip of this._

There's no question. :)

**Comment by mpena2099** [comment]
OK @folletto, OK. I agree, there is no question. :D

**Comment by jameskatt** [comment]
I would love to see a version of Baker that can turn the iBook 2 format into an app!  Then we could have a very easy to use tool to design eBooks.

**Comment by zenz** [comment]
come on @jameskatt, so why don't just use iBook2 to read the book in your case?

**Comment by mutador** [comment]
but you have used the ebook author? is oriented to chapters and sections, has no sailing magazine, is only vertical and horizontal in a case in another ...

text content is the same in horizontal and vertical ...

it´s invalid for magazines.

another question is the format epub3, etc...

**Comment by ayarmanqu** [comment]
iBooks Author is very nice, but it lacks a lot of simple features.

For example, it seems it is impossible to place an image that will make a sound when touched.
The only thing you could do is either attach a movie file with sound (in which case you get a play button on top of the image) or you have to create javascript widget with Dashcode (but widgets open up in full screen and don't work within the book interface).

So, for textbooks it is an awesome tool, but not for other type of interactive books.

**Comment by mutador** [comment]
but dont forget is version 1.1
they will update whit new interactions and better expecifications soon....

**Comment by ayarmanqu** [comment]
Hopefully! I was looking forward to using it to create a new book, but it is too limited right now.
