### ISSUE TITLE
Pages blinking on Ipad & -baker-page-turn-* parameter

### ISSUE THREAD

**Issue by dudisitchy** [Simbul/baker#281]
Hi there,

I am facing a problem with pages blinking after I build to my Ipad. On simulator it didn't happen.
On Ipad, the first time that the page is loading stay normal, but if I return to this page again, the page blink once.

Could someone help me ?

Thanks a lot !!

**Comment by zenz** [comment]
try #262 to see if it's workable for you.

**Comment by dudisitchy** [comment]
Hi zenz, I download that project and replaced the book for my book folder. The problem remains the same.
On my book, I have a lot of images that size 768x1024.
Do you have another tip for me ?
Thanks !!

**Comment by zenz** [comment]
download? you should checkout the tiled-screenshots branch to see if it's work or not.

**Comment by dudisitchy** [comment]
Ok... sorry for my bad...
But where is this "tiled-screenshots" ? I didn't find it on baker project !!

Thanks a lot for your support !!

**Comment by zenz** [comment]
first, you should use "git clone https://github.com/Simbul/baker.git" to get the baker source.
then use Xcode to open it. and goto organizer,goto repositories, select baker->remotes, click the arrow of origin, you will see that tiled-screenshots branch. 
When you need the branch, just click "Track Branch", if you want to jump to that branch after pull the branch source, you should select "Automatically switch to this branch", then click create.
That's all, hope you can fix your problem with this branch.

**Comment by folletto** [comment]
There's an easier way:
1. Click on "Code" in the top menu
2. Click on the "Current Branch" dropdown menu
3. Click on the branch you want, in this case "tiled-screenshots"
4. Click on "Zip" to download the last commit of that branch only

This is faster for testing, but of course if you want to play around with the code and the branches @Zenz suggestion is better. :)

**Comment by dudisitchy** [comment]
Hi folletto !!
I download that zip and replaced the book folder with my book folder.
Built and tested on Ipad and the pages blink once after load.

https://github.com/Simbul/baker.git --- link is not working.

Thank you again for the support !!

**Comment by zenz** [comment]
All right, you can use the following link to download the tiled-screenshots branch source.
https://github.com/Simbul/baker/zipball/tiled-screenshots

**Comment by dudisitchy** [comment]
Hi man,

I made the changes as are on repositories. Included the files TiledImageView.h TiledImageView.m and changes on another files. But the problem is the same... some pages blink... I am using ipad with ios 4.3. This blink is killing my work...

Do you have another idea ? I am trying to put my pages as background, but don't solve the problem too.

Thanks a lot !!

**Comment by zenz** [comment]
search this line in RootViewController.m:
[webView performSelector:@selector(setHidden:) withObject:NO afterDelay:0.1];
try to increase the afterDelay from 0.1 to a bigger number like 0.2 or 0.3.

I don't know if it's work or not, it's just increase the hidden time to avoid drawing while screenshot loading.
Your iPad is generation 1 or 2? if it's iPad1, the cpu speed is the problem.

**Comment by dudisitchy** [comment]
Hi man !!! I put 0.5 and it solved my problem !!!!
Thank you a lot for your quickly support !!!

**Comment by dudisitchy** [comment]
## Change of topic: Disable tap left or right to change page

Zenz, could you help me with one more thing ??
There is a way to disable the tap left or right to change page ? I want that the page only change with finger slide...
Thanks !!

**Comment by zenz** [comment]
Hi, @dudisitchy, you should really read the codes to use baker. it will help you a lot.

in RootViewController.m, find this instant method

<pre>
#pragma mark - GESTURES
- (void)userDidTap:(UITouch *)touch {
    
    CGPoint tapPoint = [touch locationInView:self.view];
    NSLog(@"• User tap at [%f, %f]", tapPoint.x, tapPoint.y);
    
    // Swipe or scroll the page.
    if (!currentPageIsLocked) {
        if (CGRectContainsPoint(upTapArea, tapPoint)) {
            NSLog(@"    Tap UP /\\!");
            [self goUpInPage:@"1004" animating:YES];    
        } else if (CGRectContainsPoint(downTapArea, tapPoint)) {
            NSLog(@"    Tap DOWN \\/");
            [self goDownInPage:@"1004" animating:YES];  
        } else if (CGRectContainsPoint(leftTapArea, tapPoint) || CGRectContainsPoint(rightTapArea, tapPoint)) {
            int page = 0;
            if (CGRectContainsPoint(leftTapArea, tapPoint)) {
                NSLog(@"    Tap LEFT &gt;&gt;&gt;");
                page = currentPageNumber - 1;
            } else if (CGRectContainsPoint(rightTapArea, tapPoint)) {
                NSLog(@"    Tap RIGHT &lt;&lt;&lt;");
                page = currentPageNumber + 1;
            }
            [self changePage:page];
        } else if ((touch.tapCount%2) == 0) {
            [self toggleStatusBar];
        }
    }

}
</pre>


the page = currentPageNumber +1 or -1 is what you need, just remark that line, it will disable the tap side function you want.

**Comment by mutador** [comment]
about this
"I don't know if it's work or not, it's just increase the hidden time to avoid drawing while screenshot loading.
Your iPad is generation 1 or 2? if it's iPad1, the cpu speed is the problem."

there are a implementationin xcode  to define if the user is ipad 1 or two , automatic and  use one specifications or others, it´s posible?

---

Pages blinking on Ipad

i only use three cards for no blinking efecct, but "pugpig solution" don´t have this problem ( have others...) then i think its not only a problem ipad1 cpu ....

**Comment by Simbul** [comment]
To chime in on @zenz's suggestion, if you don't care about left and right tap you can remove the `else` clause starting on line 1301 entirely.

You can go from:

```
  ...
  [self goDownInPage:@"1004" animating:YES];
} else if (CGRectContainsPoint(leftTapArea, tapPoint) || CGRectContainsPoint(rightTapArea, tapPoint)) {
  int page = 0;
  if (CGRectContainsPoint(leftTapArea, tapPoint)) {
    NSLog(@"    Tap LEFT >>>");
    page = currentPageNumber - 1;
  } else if (CGRectContainsPoint(rightTapArea, tapPoint)) {
    NSLog(@"    Tap RIGHT <<<");
    page = currentPageNumber + 1;
  }
  [self changePage:page];
} else if ((touch.tapCount%2) == 0) {
  ...
```

to

```
  ...
  [self goDownInPage:@"1004" animating:YES];
} else if ((touch.tapCount%2) == 0) {
  ...
```

Please let us know if this worked, so we can close the issue :)

**Comment by dudisitchy** [comment]
Hey man... I solved this with the reply of zenz !!
Sorry for not reply that the solution was fine !!!
Thanks for all of your help !!

**Comment by folletto** [comment]
Since this was a too popular request, with the latest commit (f770bb9575aa66bc1ba71ce9786d5418800afd5c) we added a way to disable page turns with both tap, swipe or both.

In `book.json` now you can use also:

```
-baker-page-turn-tap
-baker-page-turn-swipe
```

We also updated the wiki page.
