### ISSUE TITLE
Trying to disable double tap event for IndexView?

### ISSUE THREAD

**Issue by coxmi** [Simbul/baker#283]
Hello,

I'm trying to create my own custom html/jquery navigation menu (at the top of the page), which is initiated with a double tap.
I've created the script to do it, but when i load it up in baker (both the simulator and on the ipad), the Index view takes over the double tap gesture, rather than being on the webpage itself.

is there any way to disable the indexview appearing on double tap, i've searched through the files but to no avail.

Any help would be much appreciated,
Thank you!

**Comment by ghost** [comment]
This will helps you. Find in RootViewController the function toggleStatusBar and comment the lines i put you in this code

```- (void)toggleStatusBar {
    NSLog(@"• Toggle status bar visibility");

```
UIApplication *sharedApplication = [UIApplication sharedApplication];
BOOL hidden = sharedApplication.statusBarHidden;
[sharedApplication setStatusBarHidden:!hidden withAnimation:UIStatusBarAnimationSlide];


//if(![indexViewController isDisabled]) {
    //[indexViewController setIndexViewHidden:!hidden withAnimation:YES];
//}
```

}

```
```

**Comment by coxmi** [comment]
Just trying that on the simulator, but it doesn't seem to work.

I've also tried altering the tapCount value on line 1311 of RootViewController.m to 10 instead of two, so it only appears after ten taps rather than two. In this case, all but the quickest taps do not get through to the HTML page and script.
I presume after one tap, Baker listens out for more afterward, which is taking the focus of the taps on the page?

**Comment by ghost** [comment]
It runs for me, is quite simple, I dont understand what happens with this code and your project, but it works

**Comment by coxmi** [comment]
I've just tried again on the iPad and commenting those lines of code does stop the Index from appearing, but it still doesn't allow me to double tap the webpage, which seems odd.

A two finger tap works (essentially being a very quick double tap), but it would be nice to get the double tap working...

**Comment by Simbul** [comment]
You can try commenting out lines 73 to 77 in `InterceptorWindow.m`. This should get rid of the code handling the double tap (which explicitly prevents the gesture event from being propagated to the views and ultimately to the html page).

```
if (touch.tapCount > 1) {
  // Touch is not the first of multiple subsequent touches
  // if (touch.phase == UITouchPhaseEnded && !isScrolling) {
  //    NSLog(@"Multi Tap");
  //    [self performSelector:@selector(forwardTap:) withObject:touch];
  // }
  // shouldCallParent = NO;

} else ...
```

I haven't tested this since I had no time to implement a double tap handler in the html page. Give it a spin and let us know if it works! :)

**Comment by folletto** [comment]
Did that fix work? :)

**Comment by Simbul** [comment]
I'm closing the issue, given that there have been no further comments. @michaeland feel free to reopen if you drop by.

**Comment by coxmi** [comment]
it worked, yes!
apologies for the late reply.

**Comment by bahmet** [comment]
hi @Simbul 
did you change InterceptorWindow.m since i can not find that lines of code. i am using ver 3.2.2 fyi...
thanks

**Comment by folletto** [comment]
@bahmet that comment refers to 10 months ago, it was about Baker 3.1, there was a huge rework in 3.2 and 4.0. Overall we still advise to not disable double tap. :)
