### ISSUE TITLE
Problem sliding to next pages...

### ISSUE THREAD

**Issue by kingu** [Simbul/baker#285]
Hi, 
im making a recipe book with baker, at first everythings it´s going ok, some little problems, but a little investigation can solve it, heheh.
but im facing a strange problem ( i think)..
i have a book where ther its a index and 4 diferent sections; i gave to each section an html range, for example, first section have the part1-01.html  to part1-03.html, section two part2-01.html to part2-02.html ... 
i have an index (book index.htm file) that point to the first page in every section and its working fine.. but when i navigate swiping through pages when comes to an html file at the final of every section, the net page to load it isn´t the next html .. its Tail.html!
For exemple, i came to the last page in the first section, part1-03.html ... when i slide to the left the next page to load its tail.html.. no part2-01.html...
any idea where´s the issue?

ps. sorry for may bad bad english  :-)

**Comment by Simbul** [comment]
What's the order of the pages in book.json?

**Comment by kingu** [comment]
ups..ok! thanks!! that WAS the problem!! solved!  ;-)
