### ISSUE TITLE
error testing app on my iPad

### ISSUE THREAD

**Issue by moushik** [Simbul/baker#286]
Hi everybody, 

when I hit the run button for testing on my device, I get this error message: "Code Sign error: The identity 'iPhone Developer' doesn't match any valid certificate/private key pair in the default keychain"

Any suggestions?

Thanks!

**Comment by mutador** [comment]
yes , you need a certificated ID and developer certificates by apple? you know about this?

**Comment by moushik** [comment]
...I knew I was missing something...

thanks, mutador
