### ISSUE TITLE
Disable tap to swipe

### ISSUE THREAD

**Issue by morands** [Simbul/baker#287]
Hi everyone, 
I'd like to disable the function that when I tap on the left or right part of a page it changes page, I'd like to keep only the swipe. How can I do it? 

Thanks in advance, 
Ed

**Comment by zenz** [comment]
It was replied with #281, but I like to reply you again as a separate topic.

in RootViewController.m, find this instant method

<pre>
#pragma mark - GESTURES
- (void)userDidTap:(UITouch *)touch {
    
    CGPoint tapPoint = [touch locationInView:self.view];
    NSLog(@"• User tap at [%f, %f]", tapPoint.x, tapPoint.y);
    
    // Swipe or scroll the page.
    if (!currentPageIsLocked) {
        if (CGRectContainsPoint(upTapArea, tapPoint)) {
            NSLog(@"    Tap UP /\\!");
            [self goUpInPage:@"1004" animating:YES];    
        } else if (CGRectContainsPoint(downTapArea, tapPoint)) {
            NSLog(@"    Tap DOWN \\/");
            [self goDownInPage:@"1004" animating:YES];  
        } else if (CGRectContainsPoint(leftTapArea, tapPoint) || CGRectContainsPoint(rightTapArea, tapPoint)) {
            int page = 0;
            if (CGRectContainsPoint(leftTapArea, tapPoint)) {
                NSLog(@"    Tap LEFT &gt;&gt;&gt;");
                page = currentPageNumber - 1;
            } else if (CGRectContainsPoint(rightTapArea, tapPoint)) {
                NSLog(@"    Tap RIGHT &lt;&lt;&lt;");
                page = currentPageNumber + 1;
            }
            [self changePage:page];
        } else if ((touch.tapCount%2) == 0) {
            [self toggleStatusBar];
        }
    }

}
</pre>


the page = currentPageNumber +1 or -1 is what you need, just remark that line, it will disable the tap side function you want.

**Comment by morands** [comment]
GEAT!! Exactly what I was looking for, sorry for issue #281 but I haven't saw that. Thank you so much, @zenz

**Comment by folletto** [comment]
As I said before, I'd advise you to avoid that if you aren't absolutely sure because users will expect that behaviour. Think twice before disabling it, it might translate to a very bad user experience. :)

**Comment by morands** [comment]
Thanks, but I have a bigger problem than that: if I keep active the tap to swipe function when the user tap on the "full screen" or "play" button of a YouTube video also changes page and that would seriously mean a bad user experience ;)

**Comment by zenz** [comment]
@morands , you can put your action elements far from the screen border to avoid that happen.

**Comment by morands** [comment]
@zenz yes I could but this way videos would be smaller and I prefer to have those with 768px width... I can't move the play/full screen buttons in the video player, isn't it?

**Comment by zenz** [comment]
@morands, maybe you can use javascript to make the video full screen while user hit play button? then your video can placed in any position.just an idea.

**Comment by morands** [comment]
@zenz this can be an idea, I'll try to do this later :)

**Comment by folletto** [comment]
Since this was a too popular request, with the latest commit (f770bb9575aa66bc1ba71ce9786d5418800afd5c) we added a way to disable page turns with both tap, swipe or both.

In `book.json` now you can use also:

```
-baker-page-turn-tap
-baker-page-turn-swipe
```

We also updated the wiki page.
