### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by DaveLEWIS** [Simbul/baker#288]
Hi, Baker is ACE, thank you for your hard work.

There is a feature that would help me in a project to produce a periodical Magazine.

Is it possible to have a Subscription based magazine through Baker, or is it something that you are planning on developing for baker. If not, can anyone point me in the direction of creating this myself?

Thank you so much.

Best Wishes

DaveLEWIS

**Comment by Simbul** [comment]
Hello. Have a look at issue #100 (on Newsstand integration) and #269 (on In App Purchase), they may provide the answer to your question.
