### ISSUE TITLE
In App Purchase

### ISSUE THREAD

**Issue by sabgottfriedx** [Simbul/baker#289]
Hello Everyone,

I am wondering whether you have plans or currently develop a solution for In App Purchase - a kind of Kiosk function. maybe there is already a solution out there to develop such thing in combination with the Baker Framework? We would like to be able to develop a project for a publisher who has a number of books that we would like to build with Baker. Such an environment would be ideal to manage multiple publications. 

Would be awesome to get some hints. 
Thanks a lot, 
Sabine

**Comment by Simbul** [comment]
The subject has already been discussed somewhat extensively in issue #269. Have a look and see if you can find something useful in there ;)
