### ISSUE TITLE
Persistent Navigation on books

### ISSUE THREAD

**Issue by paulhontz** [Simbul/baker#29]
It would be great if the Baker Framework had a persistant navigation option. At the very least an option to tap and bring up an index.

This would be outside the UIWebView and wouldn't have to be redrawn each screen. From a UX point of view, this would also help with the perception of it loading faster.

Probably the best example I've found would be Wired's Magazine app. Being able to have a consistant point of reference helps users from "getting lost". The small scrollbar at the bottom simply isn't enough. The thumbnails are a great addition too.

**Comment by folletto** [comment]
Yup, as you've seen there's already the issue #17 open about that. ;)
