### ISSUE TITLE
Enable landscape view only for videos

### ISSUE THREAD

**Issue by morands** [Simbul/baker#291]
Hi guys, 
in my publications there are some YouTube videos that I'd like to enable for landscape mode, but videos are the only part of the app that I want in landscape: I tried to modify the orientation options on both the Xcode project and on the book.json file but I can't reach my goal. Anyone has an idea?

Thanks in advance, 
Ed

**Comment by zenz** [comment]
Then make your books in landscape mode? it's really not a good idea to ask the user rotate the iPad just for watching the video.

**Comment by morands** [comment]
@zenz I'm considering to leave only portrait also for videos, 'cause I'm working on a magazine and I can't make both versions every month.

**Comment by Simbul** [comment]
I'd have to test this, but I'm pretty sure the video can be viewed in portrait mode even though the Baker app is only landscape, when the user selects _fullscreen_.

**Comment by folletto** [comment]
@morands so, you mean that by building the book as portrait only, then playing a video and then turning the iPad, the video doesn't turn?

**Comment by Simbul** [comment]
Hi @morands any news on this issue?

**Comment by morands** [comment]
Hey @Simbul! I have been pretty busy with school and another project recently... I should take a look to Baker for the end of this week (at least I hope). I'll keep you updated :)

**Comment by Simbul** [comment]
Cool, we'll be waiting :)

**Comment by morands** [comment]
Hi @Simbul and @folletto sorry for the wait but I finally made some tests with the "initial" Baker (without my changes). I tried many configurations and basically we can reassume as:

1) Info.plist: all orientations enabled + book.json: only portrait = videos always in portrait
2) Info.plist: all orientations enabled + book.json: both = videos in landscape and also contents

So I can see fullscreen videos in portrait only if I enable also the "normal content" to portrait. 
Any idea about how could I solve it?

**Comment by folletto** [comment]
It seems that the code we use to handle the screen rotation influences the video as well.

It seems there's something to detect the video entering and exiting full screen, but it's on [javascript side](http://stackoverflow.com/questions/9094913/how-can-we-figure-out-when-a-html5-video-player-enters-the-full-screen-mode-on-i). I should try to see if there's an equivalent on Objective-C side. It might be possible, but unfortunately it requires some research and rework.

**Comment by folletto** [comment]
I asked the question on Stackoverflow, to double check: http://stackoverflow.com/questions/9473688/detect-when-a-html5-video-runs-full-screen-from-objective-c

**Comment by folletto** [comment]
I'm afraid that question didn't have any answer and as such is probably either impossible today or too complex to achieve. Sorry. :(

**Comment by morands** [comment]
Don't worry ;)
