### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#292]
Does baker framework support push notifications?
How can i setup this?

regards

**Comment by zenz** [comment]
APNS was not support in baker right now, but you can make it by yourself. easyapns is a good selection.

**Comment by xiripi** [comment]
this easyapns send to all people who install app?

**Comment by zenz** [comment]
No, Please visit www.easyapns.com for details.

**Comment by folletto** [comment]
That's a very nice resource zenz. Are you using that? :)

**Comment by zenz** [comment]
Yes, I'm using it on my app. it's quite easy for use.

**Comment by folletto** [comment]
And, if I'm not too bold, do you think you could write a couple of lines, here or somewhere else, on how do implement that for Baker? :P

**Comment by zenz** [comment]
Firstly, follow this link to add some code to BakerAppDelegate.m
http://www.easyapns.com/apple-delegate

and then in
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
  you should handle the different msg pushed to app. my solution is to register a notification to handle it in RootViewController.m so that all important things can be handle together. then we can just postNotificationName here in BakerAppDelegate.m

Is this clear?

**Comment by nin9creative** [comment]
Cool.  I used Urban Airship for another app I did a while back.  The only problem is that you are locked into paying them if you are sending a lot of push notifications.  Will need to investigate setting this up.

**Comment by folletto** [comment]
Awesome @zenz! 
Yes, it looks quite simple. No gotchas. :)

Thanks. :)

@nin9creative The problem with Push notifications is exactly the server side of things. I don't want to rely on a pay system, and I can't find a well packaged and reliable opensource server solution to interface build. The one pointed out above seems the nearest thing to it. It's rough, but it might work. :)

**Comment by zenz** [comment]
By the way, there is a plugin for wordpress, so if you use wordpress. then you can also give it a try(I didn't test that).

**Comment by bahmet** [comment]
@nin9creative 
as for the urbanairship solution, they provide one million free messages per month. which is enough for me at the moment.
can you pls advice how did you handle baker side .
thanks

**Comment by xiripi** [comment]
Hi Zens. Im trying to implement easyapns, when you said: 

"`(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo` you should handle the different msg pushed to app. my solution is to register a notification to handle it in RootViewController.m so that all important things can be handle together. then we can just postNotificationName here in BakerAppDelegate.m"

i have difficult to to implement the handle in rootviewcontroller.m can you help me?

**Comment by bahmet** [comment]
hi @xiripi did you manage to setup the server side and the app side.
today i tried on this, could not get the push notification service screen ( the one that asks permission when you run the application). also i could not find my device in the sql side.
i would appreciate if you can share with me.
thanks...

**Comment by xiripi** [comment]
Did you see the debug window? I got a registration error and cannot see my device registered neither push notification enable service.

**Comment by zenz** [comment]
When you coding well and configuring the server side correctly, you should see you machine listed in the SQL database.
And you need to switch the state form production to sandbox to reveive test APNS messages.

**Comment by xiripi** [comment]
Hi zens. I have configured the server side well but i get error register the device on debug. What you mean with: switch the state form production to sandbox?Can you me more explicit.

**Comment by bahmet** [comment]
hi,
i have been working with the easyapns, what i have completed so far is:,
- i have managed the server side and got the "No APNS Task Provided..." screen
- i have managed the application side and got the screen that asks to use push messages,
- i found my device registered to the "apns_devices" table
- i changed the state from production to sandbox in  "apns_devices" table
- i ran the "http://dijitalyayincim.com/apn/samples.php" and found that messages queued under "apns_messages" table
- i ran " http://dijitalyayincim.com/apn/apns.php?task=fetch" to send the message,
  result no message received and message status changed to failed in "apns_messages" table.
  i will check with my isp whether i have conenction to 'ssl://gateway.sandbox.push.apple.com:2195' or not. 
  if you have any thoughts pls let me know.
  @xiripi pls let me know where you at in the setup. i will try to help....

**Comment by bahmet** [comment]
my hosting company adviced me that they do not allow port 2195 and 2196 for security reason....

**Comment by xiripi** [comment]
Hi bahmet im stand at the same point as you are. I cant receive message in my device, all setup is correct: device-> register, message-> Enter , change to sandbox and not received. Im used the server on my local pc and is the same. Your provider block that port for is server but the link to ssl://gateway.sandbox.push.apple.com:2195 dont have nothing to do with it.

Keep trying...

**Comment by bahmet** [comment]
do you have firewall or router that may block traffic.
i will also try it in my local pc at home...

**Comment by zenz** [comment]
If you want to test APNS in local machine,you may try pushmebaby, it's also in github.

**Comment by bahmet** [comment]
Ok, godaddy also confirmed that shared hosting are not allowed to open specific ports. The best option is to get virtual dedicated server

**Comment by xiripi** [comment]
Did you try your on your local computer? 

Zens: can you help us? the ports need to be open?

**Comment by bahmet** [comment]
Unfortunately not. That is a shared pc with my daughter

**Comment by zenz** [comment]
First of all, you don't need to open a port(actually I don't know why you guys talking about open a port). 
Please post your logs here. Thus can help to analyst what's wrong.

**Comment by zenz** [comment]
And I need to notice you that, you must apply a uniq app profile for this app you want to use APNS, also you need to configure it within apples profile manage page. And APNS only can be tested on real machine.

**Comment by bahmet** [comment]
@zenz i created a uniqe app profile only for this apns testing. 
btw my log file is empty. 
thanks

**Comment by bahmet** [comment]
i created my pem files following this method just fyi.
http://blog.serverdensity.com/2009/07/10/how-to-build-an-apple-push-notification-provider-server-tutorial/

**Comment by bahmet** [comment]
here is my log file for your reference. thanks

Failed to connect to APNS: 110 Connection timed out.

```
1) APNS::processQueue -> File: samples.php (line 63)
2) APNS::_fetchMessages -> File: class_apns.php (line 1087)
3) APNS::_iterateMessages -> File: class_apns.php (line 381)
4) APNS::_connectSSLSocket -> File: class_apns.php (line 431)
5) APNS::_triggerError -> File: class_apns.php (line 456)
```

A connected socket to APNS wasn't available.

```
1) APNS::processQueue -> File: samples.php (line 63)
2) APNS::_fetchMessages -> File: class_apns.php (line 1087)
3) APNS::_iterateMessages -> File: class_apns.php (line 381)
4) APNS::_pushMessage -> File: class_apns.php (line 433)
5) APNS::_triggerError -> File: class_apns.php (line 500)
```

Failed to connect to APNS: 110 Connection timed out.

```
1) APNS::processQueue -> File: samples.php (line 63)
2) APNS::_fetchMessages -> File: class_apns.php (line 1087)
3) APNS::_iterateMessages -> File: class_apns.php (line 381)
4) APNS::_connectSSLSocket -> File: class_apns.php (line 431)
5) APNS::_triggerError -> File: class_apns.php (line 456)
```

A connected socket to APNS wasn't available.

```
1) APNS::processQueue -> File: samples.php (line 63)
2) APNS::_fetchMessages -> File: class_apns.php (line 1087)
3) APNS::_iterateMessages -> File: class_apns.php (line 381)
4) APNS::_pushMessage -> File: class_apns.php (line 433)
5) APNS::_triggerError -> File: class_apns.php (line 500)
```

**Comment by xiripi** [comment]
I create a profile unique too. I don't have nothing in my log file.

**Comment by bahmet** [comment]
@xiripi did you remove the passphrase when you export your certificates. 
you can follow here. http://blog.serverdensity.com/2009/07/10/how-to-build-an-apple-push-notification-provider-server-tutorial/
 after i remove passphrase my log file is not empty anymore. now my problem is the connection issue and when i google about apns i found lots of comments complaining about shared hostings. all advice VPS.

**Comment by xiripi** [comment]
Finnaly got it working!
@bahmet - thanks for the link. After a generate the perm certificate my iPad start to receive push notifications. I got only one problem. I run the application on another iPad, fallow all the steps-> sandbox change and i didn't receive nothing on this last. The developer is restarted to one iPad?

thanks

**Comment by bahmet** [comment]
Hi @xiripi congratulations. I guess you made it work on your pc environment not the shared hosting. For using easyapns with multiple applications you can refer to https://github.com/vincentsaluzzo/EasyAPNS-Panel/issues/1

**Comment by Simbul** [comment]
Push notifications support has been implemented and a tutorial has been written in https://github.com/Simbul/baker/wiki/Push-notifications-tutorial

**Comment by nonuts** [comment]
Got parse working quite easily, but a friend pointed me to http://helios.io as an alternative, since it's open-source and could be used via heroku, too.
