### ISSUE TITLE
cant change html pages

### ISSUE THREAD

**Issue by sabgottfriedx** [Simbul/baker#293]
Hi All,

I am just starting up with Baker and also have to get back on track with css and html. So sorry if my question might be beginner level....

I have downloaded the baker framework and the book you have provided. 
Now I wanted to build my own book from there with just two pages - a cover and one article. 
So I deleted all pages apart from cover, index and part1-01 and changed the book.json file accordingly. 
I have cleaned all target etc.
Now when I start the app with simulator something weird happens. 
I see neither cover nor first page. And when I double click a couple times the page appears somewhere in the middle of the screen and is weirdly resized as if it was included in the nav bar. 

I have tried a couple of changes all afternoon and nothing really worked. So I would really appreciate a hint. 

Thanks a lot.

**Comment by zenz** [comment]
just read the wiki or read me doc etc. then check your books carefully to see if it fits the rules very well . nothing else.

**Comment by sabgottfriedx** [comment]
hey zenz, i did all of this. any ideas suggestion where to look first? ughh drives me crazy ;)

**Comment by zenz** [comment]
http://bakerframework.com/tutorials/basic

**Comment by sabgottfriedx** [comment]
yes i read all this and checked it all and cant see where the problem might be. 
i try to do something totally rudimentary - just a book with a cover. [here my example](https://www.wetransfer.com/dl/fcnT24d5/e154c649cb6acfaade628c750c0bb8fa56518543da6cb0214c2e64cb2c6f843e81a73c4a2398de0)  - would be so awesome if you could have a quick look over it and tell me where I am getting wrong - I just cant see anything on simulator, just blank screen

**Comment by mutador** [comment]
but you try whit more pages and the index.html?

**Comment by sabgottfriedx** [comment]
Hey guys, thanks a lot for your help. I found the problem - i knew it was something stupid - just had a comma before the final ] in the json file and never looked at the output in xcode where it tells you what goes wrong ... now I see what I am doing. thanks for your help anyways. xxx sab

**Comment by Simbul** [comment]
Glad to hear it's solved. Unfortunately JSON parsing errors are not very clear at the moment, so it's totally understandable to be tripped by them ;)
