### ISSUE TITLE
baker screenshots folder

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#294]
i can't find it the screenshots generated by baker. Can someone give me the correct path?

**Comment by Xm4s** [comment]
Hi!

[Here](https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book) you can find the wiki page that explain everything you need to knwo abour pre taken screenshots.

To answer your question Baker screenshot generated by iOS simulator are in the folder **/Users/_username_/Library/Application Support/iPhone Simulator/_simulator version_/Applications/_application identifier_/Library/Private Documents/baker-screenshots/**, where ...

**_username_** is your username on your Mac :)
**_simulator_version_** is the version of the simulator where you've installed Baker (usually **5.0** or **4.3.2**)
**_application identifier_** is a string of chars generated by Xcode (es: **5000955B-BD09-496E-93E2-9D5CACCD2D65**)

**Comment by belgo** [comment]
I follow all the steps to generate the "screenshots", but does not create the folder "Private Documents". What is wrong?
