### ISSUE TITLE
five cards mode

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#296]
an idea... load all the pages in a screenshoot  50% resolution and make two before and to after whit good resolution, a five card mode? 

is a stupid thing? 

i dream whit a full load magazine and a newsstand integration, of course....it´s a joke...

**Comment by folletto** [comment]
Given we are having problem with even simple screenshots, it's probably way too heavy. :/

**Comment by mutador** [comment]
i see my new magazine in ipad 2 with three cards mode and " casi me hecho a llorar"  thanks a lot for baker, it´s the project i am most love in time....
it´s lovelly in ipad2, soft transition clean and quikly.......
I never come back adobe i promise ....
and only for the ears of @folleto and for close this post
newstand integration ....jajajajajajaj, kiss

**Comment by folletto** [comment]
;)
