### ISSUE TITLE
Wiki Documentation -baker-index-width 

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#298]
This is the current documentation on the page "Book.json Baker extension parameters"

-baker-index-width (number, default: null) - since 3.2:
Width (in pixels) for the index bar. When null, the height is automatically set to the height of the index.html page. Note that the index bar will always snap to the left side of the viewport.

Is this a typo? The words height should be replaced by width, so it should read:

-baker-index-width (number, default: null) - since 3.2:
Width (in pixels) for the index bar. When null, the width is automatically set to the width of the index.html page. Note that the index bar will always snap to the left side of the viewport.

Let me know if this is correct and I will change it on the wiki. 
Tom

**Comment by folletto** [comment]
You're correct. It's a typo. :)

**Comment by tstegart** [comment]
Ok, fixed.

**Comment by folletto** [comment]
Thanks. :)
