### ISSUE TITLE
Prevent Page from drag-scrolling?

### ISSUE THREAD

**Issue by vanderbreye** [Simbul/baker#30]
Hey!
Is there a way to pass a drag-move ( which currently scrolls the page up/down/left/right ) directly to the tap events?
This would be great to implement for a more "magazine-like" view  - but i simple can't figure out how to suppress this -  or better: redirect the move to the tap-functions..

**Comment by folletto** [comment]
What exactly do you mean for "magazine-like" view? :)

However those events are handler by the native components we are using, UIWebView a UIScrollBar, so you need to intercept them before they gets "absorbed" by them. :P

**Comment by vanderbreye** [comment]
Mmh. I still could not figure out how to do that.
As far as i can see, there is no proper way to intercept if the user has scrolled up or down  without passing it through to the webview?!

I want to make a simple scroll by one whole pageview each time there is a swipe Up/Down - just instead of these Tappings - like seen in some iPad-Magazines.
Am currently using the latest commit.

Also we are currently testing a new 3-cards-view - which allows propper preloading.
hoping to finish it the next 2 weeks.

**Comment by folletto** [comment]
Unfortunately that's one of the problem we are already trying to solve with the InterceptorWindow, even if for other needs. :)

~

Note: Baker before release was already 3-cards-view, but we had to drop it because it was too slow on the current hardware. Maybe it behaves better if your pages are smaller, but be aware of it! :)
Or maybe... did you find a way to optimize it? :)

**Comment by vanderbreye** [comment]
indeed, there may be a chance to cut down the BIG Webview an optimize loadings, but we still have to test a lot, stay tuned.
if someone could even think of a soloution for the scrolling-to-tap-function-interception (beside pulling it in the html), this would be great.
keep up the great work!

Update: Here is the solution for the UP/down/swipe in JS, wich you have to put in the body of one or more html-book-file(s): (some smaller problems are still remaining: clicking a link triggers the scroll, too...)

<pre>
<script>
/**
* Parts taken from: 
* @author Dave Dunkin
 * @copyright public domain
 */
function addSwipeListener(el, listener)
{
 var startX;
 var dy;
 var direction;
 
 function cancelTouch()
 {
  el.removeEventListener('touchmove', onTouchMove);
  el.removeEventListener('touchend', onTouchEnd);
  startX = null;
  startY = null;
  direction = null;
 }
 
 function onTouchMove(e)
 {
  if (e.touches.length > 1)
  {
   cancelTouch();
  }
  else
  {
   //dx = e.touches[0].pageX - startX;
   dy = e.touches[0].pageY - startY;
   if (Math.abs(dy)>0) {e.preventDefault();}
   
   if (direction == null)
   {
    direction = dy;
   // e.preventDefault();
   }
   else if ((direction < 0 && dy > 0) || (direction > 0 && dy < 0) || Math.abs(dx) < 50)
   {
     cancelTouch();
   }
  }
 }

 function onTouchEnd(e)
 {
  cancelTouch();
  if (Math.abs(dy) > 50)
  {
   listener({ target: el, direction: dy > 0 ? 'down' : 'up' });
  }
 }
 
 function onTouchStart(e)
 {
   
  if (e.touches.length == 1)
  {
   startX = e.touches[0].pageX;
   startY = e.touches[0].pageY;
   el.addEventListener('touchmove', onTouchMove, false);
   el.addEventListener('touchend', onTouchEnd, false);
  }
 }
 
 el.addEventListener('touchstart', onTouchStart, false);
}


/* Make sure Jquery is installed, else use document.scrollTo(...)
addSwipeListener(document, function(e) { //alert(e.direction); 
if (e.direction=='up'){
$("body").animate({scrollTop: $("body").scrollTop()+ window.innerHeight}, 200);
}

if (e.direction=='down'){
$("body").animate({scrollTop: $("body").scrollTop() - window.innerHeight}, 200);
}

});
    </script>
</pre>

**Comment by folletto** [comment]
I think I could close this as solved, ping me if I'm wrong. ;)
