### ISSUE TITLE
book.json - cover parameter - where is it used?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#300]
Where is the cover file used in Baker that is specified in the book.json file? The example given in the documentation is:

"cover": "assets/study-in-scarlet.png",

But there is no "assets" folder in Baker that I can find. Is it supposed to be the "images" folder? What benefit do we get from specifying a cover image? Don't we do that by placing an image in Book Cover.html? Is the image specified in book.json used somewhere else? Do we need it when we implement a shelf to download books?
Tom

**Comment by folletto** [comment]
`assets/` is an example. You can place it wherever you want in the Hpub folder. It's not a requirement right now, but if you don't have that by the time we implement the shelf, we will use a default image on the shelf instead of your cover. ;)

**Comment by tstegart** [comment]
Thanks. I suspected it might be used on the shelf but I wasn't sure.

**Comment by tstegart** [comment]
One last thing, when it is used on the shelf, does it need to be PNG? Can it be JPG? Also, does it have an orientation requirement and size? For example, portrait, 768 x 1024?

**Comment by folletto** [comment]
It's hard to tell right now. Try to put in a good sized image that looks like a book cover with the same proportions of the iPad. The Hpub standard doesn't put any limit, except, yes, PNG. :)

**Comment by anjimi** [comment]
Apple developer guidelines table says for Default Newsstand cover images: At least 512 pixels on the longest edge / At least 1024 pixels on the longest edge (for high-resolution iPhone 4/iPad displays). So I'm guessing we would need one cover image per issue at least 1024 pixels long and it should then be scaled appropriately in Newsstand and on the Baker shelf?
