### ISSUE TITLE
Book Content Security

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#301]
I'm not sure if this has been brought up at all yet.  I had a quick question regarding book folder security and content protection.

Right now (not that I advocate doing this) one can do the following...

1)  Download a Baker based book from the App Store on their iPad.
2)  Sync the download with their Mac
3)  Find the application backup folder on the Mac
4)  Find the application .ipa for the Baker based application
5)  Rename the .ipa file to .zip file
6)  Unzip the contents of the .zip file
7)  Find the Payload folder and open it
8)  Right Click on the Application Name in the Payload folder and select "Show Package Contents"
9)  Bam!  There is the whole "book" folder with all of the Assets / HTML / CSS / Javascript

Has anyone thought about this?

Andrew

**Comment by zenz** [comment]
Even if you encrypt the books, you have to decrypt it to book folder so that UIWebView can read it. So, actually you don't need so many step to get the books content. just use iExplorer to explore the application folder to get the decrypt content is so easy.

**Comment by nin9creative** [comment]
I was just asking if anyone had thought about it as a potential issue...  I'm sure that some folks will invest a lot of time in creating content and features that they might not want easily "borrowed"...

**Comment by zenz** [comment]
May be we can learn from this?
http://aptogo.co.uk/2010/07/protecting-resources/

**Comment by mutador** [comment]
please, delete this post ....don´t make the work of the thiefs easy, jajajaj

**Comment by folletto** [comment]
I'd just advise to don't replicate the paranoia that the music and movie labels have. A simple system will always trump any piracy, and no system will ever trump piracy completely,ever. It's a balance between the two.

Anything can be copied. It's just a matter of effort. They could copy your magazine 1:1 without ever looking at the code and you'll have the same problem as having the code stolen.

So: create good content, market it well and find the right price, and you won't have to worry. :)

**Comment by nin9creative** [comment]
I wouldn't go so far as to say that anyone is replicating the paranoia that exists in the music industry...  However Baker as a framework has great promise as a platform on iOS for publications.  Given some of the efforts on the Newsstand front, could provide a great option for organizations wanting a less costly solution than the Adobe and other solutions now available. I would also guess that one of the considerations would be deploying content that could not be easily replicated or borrowed...

I think that it is a completely valid point to make.  If nobody cares then nobody cares.

**Comment by folletto** [comment]
Well, you know, I could easily copy any website in the world... right? j/k ;)

More seriously: did you try doing the same on an Adobe publication? :)

**Comment by nin9creative** [comment]
This is different though.  The Adobe stuff mostly gets flattened out as images.  There isn't HTML, Javascript and CSS easily available.  Apparently I'm making an issue out of nothing.  I just thought I'd bring it up.  Feel free to ignore.

**Comment by folletto** [comment]
It's a discussion worth raising, it's just also as important giving it the proper size and context. :)

So did you try? What's the output? XML? :)

**Comment by mutador** [comment]
adobe export all like images , and interactions are in a xml ( i think), but export a screenshoots of indesing , of this i am sure....even some solutions based in indesing open photoshop for make this...

i am not afraid of have a opened book, for me is right, when i am dead i don´t want nothing of my desings whit me....even for some people y send my book for testing.

**Comment by folletto** [comment]
Ok, as expected. Everything is in clear, but since it's a proprietary "precomposed" format nobody will do much with it. :)

As for Baker, it's surely possible to implement some kind of cryptography, but I'm not sure if it's worth the time, since somewhere in the distributed app the decoding key needs to exist, and as such... anyone will still be able to steal it.

Otherwise, you could take the Adobe approach as well: limit the interactivity of your publication and flatten out everything by taking full-page screenshots. The downside of this is the same as Adobe: limited interactivity and increased app size.

I can't think of many other solutions...

**Comment by nin9creative** [comment]
I guess in the grand scheme of things there are tradeoffs to be made...  I'd rather have a working shelf and in app purchase stuff going than worrying about people stealing my layouts :)

**Comment by Simbul** [comment]
For what it's worth, I think it's a positive tradeoff. A proper DRM implementation would take a considerable effort, be arguably more cumbersome for the user and the result would be breakable anyway - as it has always been the case in the music/movie/game industry.

To me, it looks like the really successful initiatives to limit piracy have been the ones concentrating on making the purchase/consumption as easy or easier than the alternative: iTunes, Netflix, Steam and so on.
Or, if you haven't got the same degree of control they have on the process, you can always concentrate on creating a great product.

All in all I think you raised a good point, but I don't believe some sort of DRM would help more than what I've written above ;)

**Comment by nin9creative** [comment]
Cool.  Thanks for the the input @Simbul
