### ISSUE TITLE
Autoplaying more than one video

### ISSUE THREAD

**Issue by joshbaltzell** [Simbul/baker#302]
I'm trying to autoplay two videos when a page in Baker loads. Both are used as interface elements, so the goal is to have them playing with no controls showing.

The problem is that I can only get one at a time to autoplay. When I add an autoplay to the video just the last one plays. When I test I can get either of the videos to play, but not both.

Here is my HTML:

```
<video preload class="introVideo" autoplay loop="loop">
    <source src="video/Intro.mov">
</video>
<img src="images/misc/Logo_UnderVideo.png" />
<div align="center">
    <video preload class="hospitalsVideo" autoplay loop="loop">
        <source src="video/22Hospitals.mov">
    </video>
    <img src="images/misc/OnePatient.jpg" />
    <p>
        <a href="About-05.html" class="blue button radius">Find out what makes us different</a>
    </p>
</div>
```

**Comment by Xm4s** [comment]
I'm sorry but on iOS is impossible to play multiple media element at the same time.

Taken from developer.apple.com:

**Multiple Simultaneous Audio or Video Streams**
Currently, all devices running iOS are limited to playback of a single audio or video stream at any time. Playing more than one video—side by side, partly overlapping, or completely overlaid—is not currently supported on iOS devices. Playing multiple simultaneous audio streams is also not supported. You can change the audio or video source dynamically, however. See “Replacing a Media Source Sequentially” for details.

[source](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW10)
