### ISSUE TITLE
open external link?

### ISSUE THREAD

**Issue by kingu** [Simbul/baker#305]
Hi, i´m making mi first free recipe book with baker, and i want to put in te last page a link to a paypal donation button, but i dont know how to open a web link outside the baker app.. if i put a link the web page open full screen inside the app .
Can i open an external link from baker apps? (beside this paypal button, i want to put an email link for example)
thanks!

**Comment by Simbul** [comment]
Have you had a look at the wiki page explaining how to [manage links and urls](https://github.com/Simbul/baker/wiki/Managing-links-and-urls)?

**Comment by kingu** [comment]
Thanks!
 i didn´t look at the wiki page  before, only look here, in issues.. sorry for inconveniences :-)
