### ISSUE TITLE
(Ask) How To Set Picture Size On Building Web For E-Book 

### ISSUE THREAD

**Issue by chowsoft** [Simbul/baker#306]
hello, i'm newbie here, i have a stupid question and wondering if someone can help me to solve my problem.

If i use dreamweaver to build a html page for my e-book that i want to create using baker, how much width and height 
i should to make in adobe photoshop to make sure that it is full screen on iphone or ipad.

it's hard for me to explain what i mean, but i hope i can explain below :

for example :
1. Layout in dreamweaver when create a page html, should be unlimited length for example 1500pixel
   if i want to create a first page of my book on that. and i like to give a picture background, how to make sure
   it's exactly full on iphone or ipad? should i make it on CENTER in size 480 pixel length  ?

really i don't know and this is my problem, because i don't know how to test if i already design it to make it see
on iphone/ipad

IS this answer right ?

We just make it FULL SCREEN when create using Dreamweaver , the baker frame script project x code  will automatically make the FRAME will full screen follow the ipad/iphone size. is it right?

**Comment by folletto** [comment]
You should refer to the device screen size and create an HTML page and/or image that fits it perfectly.

Sizes:
- iPhone: 480 × 320 px
- iPad:  1024 × 768 px

(note also that on iPhones with Retina display you can use more advanced CSS techniques to achieve pixel perfection). :)
