### ISSUE TITLE
Text layer

### ISSUE THREAD

**Issue by draculaus** [Simbul/baker#307]
Hi together!

Is it possible to use something like a text layer and pull this layer over a background picture.  I will have a picture and on the bottom of this should be a "arrow" or something like that. So if you pull this "arrow" to the top you will pull also a text from the bottom over the picture. 
Well I hope you understand what I mean ;). 

with best regards

**Comment by zenz** [comment]
I couldn't understand. sorry.

**Comment by draculaus** [comment]
Is it possible to take a button over a image and if I press the button it will open a popup  with a text inside over the image.

**Comment by mutador** [comment]
jqerymobile

**Comment by folletto** [comment]
Sure. That requires some kind of JavaScript. You can find plenty of code examples around the web, from the most basic to the more advanced ones. For example:
- http://flowplayer.org/tools/overlay/index.html
- http://answers.oreilly.com/topic/1823-adding-a-page-overlay-in-javascript/
- http://stackoverflow.com/questions/873184/javascript-image-overlay-over-a-specified-div

Of course, if you need to do something really custom, then you should probably learn a bit more about javascript/css itself and code it by yourself. :)
