### ISSUE TITLE
NEW MAGAZINE FOR MAGMAGOO EDITORIAL

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#309]
http://itunes.apple.com/us/app/ohmygod-es-02/id499892763?l=es&ls=1&mt=8

<img alt="Captura de pantalla del iPad 1" class="portrait" src="http://a4.mzstatic.com/us/r30/Purple/ee/68/e1/mzl.tfpiyhhw.480x480-75.jpg">

two month of hard work, always thanks baker team

**Comment by CopperF0x** [comment]
Wow, very very impressive!   

Despite the huge amount of content/multimedia, this mag has the fastest page flipping of any Baker mag I've yet seen, how did you pull off this feat?   There's no rendering delay like the other mags.   Was this done with the 3-page rendering option?  (I noticed that only if you skip ahead pages very quickly will you see the loading screen, at normal page-flipping speed, it's unnoticeable).  

Out of curiosity, which HTML editor did you use to produce this?   

Amazing job!

**Comment by wijeweera** [comment]
Me encanta!!

**Comment by mutador** [comment]
i use the last version of baker whit three cards mode , dreamweaver how editor , but i typing the code manually...thanks

**Comment by folletto** [comment]
Thanks @mutador for the notification, you are doing one of the best Baker magazines out there. :)
I'm so happy for its development and I hope to be able to provide you a few more features soon. ;)

I'll however close this issue since almost one month has passed. :)
