### ISSUE TITLE
stopping the swipe/horizontal scroll actions

### ISSUE THREAD

**Issue by ajmi-dev** [Simbul/baker#310]
Baker is wonderful :)

I was wondering if there is a way to stop the swipe/horizontal scroll actions? Im trying to build an interactive book for kids where they need to to click on an icon or img to advance to the next chapter. 

Thanks!

**Comment by Bobramyl** [comment]
If that's the only thing you want, then you probably could remove scroll view entirely in rootViewController.m:141-150. Some additional modifications may be required but that's what I would do.

**Comment by ajmi-dev** [comment]
thank you for your reply, but your suggested solution didnt work! any other way to do it?

**Comment by folletto** [comment]
It's not very simple unfortunately, you have to remove a bit of code from very different parts of the source. I think you want to remove also the scroll when you tap, am I right?

For the tap, you have to comment out the relevant code inside `- (void)userDidTap:(UITouch *)touch` (`[self changePage:page]`).
For the scroll, you have to add `scrollView.scrollEnabled = NO` in `initBookProperties` and set it in `lockPage` and `scrollViewDidEndScrollingAnimation`.

Or...

**Comment by folletto** [comment]
...you can check the latest commit (f770bb9575aa66bc1ba71ce9786d5418800afd5c), done right now on master, that adds:

```
-baker-page-turn-tap
-baker-page-turn-swipe
```

As properties that you can use in `book.json`.

**Comment by ajmi-dev** [comment]
works just as I wanted .. thank you very much :)
