### ISSUE TITLE
looking for a god hosting for my app

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#313]
someone  knows a good hosting for hpub system?

**Comment by nin9creative** [comment]
Are you talking about hosting the files to be downloaded?  The .zip files for the issues?  Or just in general for web hosting.  I currently have servers with WiredTree, MediaTemple.  Have used HostGator and Bluehost as well which were ok.

**Comment by mutador** [comment]
The .zip files for the issues

your hpub project is finishead?

**Comment by mutador** [comment]
the hosting is for .zip files, could you recommend me one?
