### ISSUE TITLE
Test on my iPad

### ISSUE THREAD

**Issue by l00per** [Simbul/baker#314]
Hi there,

how can I test the compiled app on my iPad?

Thank you!

**Comment by Virtualsweden** [comment]
One simple way is to sign up on testflightapp.com and test your app.

**Comment by folletto** [comment]
Or, it might also be that you are asking about the Developer Account, so I suggest you to register as an iOS developer and check out Apple's documentation on how to do that. :)

https://developer.apple.com/devcenter/ios/index.action

**Comment by l00per** [comment]
Thank you!
