### ISSUE TITLE
In App Web Browser?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#315]
Has anyone solved the problem of embedding an in app web browser into a Baker based book?  For instance if I were making a magazine with a link to a companies online shopping site...  I would want to pop that link open into a browser window hosted by the baker app and not open it in safari.  

The other solutions available (Adobe DPS, Mag+, etc...) all seem to have a concept of an internal vs external hyperlink.

**Comment by mutador** [comment]
i´m not sure about but see my solution for 
http://itunes.apple.com/us/app/ohmygod-es-02/id499892763?l=es&ls=1&mt=8
in tail.html (the last page) butom suscipcion

i put a page load external page online but whit a close buttom, if the user dont have online conection have a mensage....

**Comment by folletto** [comment]
This is issue #119. :)

We received contrasting opinion on its usefulness right now, so it's quite low in priority. It shouldn't be a difficult contribution however, if someone wants to try to do that. :)

**Comment by nurtext** [comment]
Since we now have in-app sending of emails I would like to have in-app browsing of webpages as well. Unfortunatly I'm not a coding pro in Obj-C/Cocoa Touch, so it would be nice if anyone could do the job… +1 for this feature request :)

**Comment by folletto** [comment]
Yes, but as above, please feedback on issue #119 ;)
