### ISSUE TITLE
Pagination like ibooks and other book apps?

### ISSUE THREAD

**Issue by mgcist** [Simbul/baker#316]
Is it possible to paginate pages like ibooks and other book apps?

Thanks for your time.

**Comment by Virtualsweden** [comment]
You can use the

```
"-baker-vertical-pagination": true
```

In the json file.

**Comment by mgcist** [comment]
Thanks for your reply but what I I want to achieve is horizontal pagination as in ibooks, stanza and other book apps. I want to disable vertical scrolling and page each page like in a paper book. 

Does anyone know if it's possible?
Thanks

**Comment by folletto** [comment]
Sure: just create one html for each page, with height as the height of the screen and disable the bounce: `-baker-vertical-bounce`. :)

Is this what you asked for? :)

**Comment by mgcist** [comment]
Thanks for your reply but even though I can achieve my purpose with this option it's a little unoperational since I have to redesing all my htmls and I would like something, if it's possible, more automatic. Is it possible?

**Comment by folletto** [comment]
Baker doesn't do that, since its main purpose is to give you design control on each page and that requires the simplicity of the concept 1 page = 1 html.

However I guess that you could build a script to do that, after a certain number of words it will split it and create multiple HTML pages. :)

**Comment by mgcist** [comment]
Thanks for the hint. I'm already looking into that. Best regards.
