### ISSUE TITLE
jplayer issue

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#318]
hi all,
i created my app using laker templates. one of my html page has 4 pictures and when you click these pictures each of them plays different mp3, which is 2-3 seconds long. this works on chrome, ie and safari but when i create the app and download to ipad one of the sound does not work, remaining 3 works bot not all at the same page load. at each page load 2 of them works.  i even tried to uplaod html to web and tried to open with web browsers it works. i did the same on ipad and safari opened it and all sounds worked. 
so do you have any idea to fix this problem
thanks

**Comment by bahmet** [comment]
hi all,
today i tried different thing. replaced  all mp3's with wav files. at first all 4 wav's  worked well then same thing happened. did not play all at the same page load. you can check the pages here http://dijitalyayincim.com/book/index_3.html 
thanks in advance for your help

**Comment by bahmet** [comment]
why not all my sounds do not work at the same page load

**Comment by bahmet** [comment]
i think i self solved my problem after 1326890 attempts :))
i changed  "-baker-media-autoplay": true, to  "-baker-media-autoplay": false
now all my sounds work. i hope it continues to work.....

**Comment by bahmet** [comment]
closed

**Comment by folletto** [comment]
Awesome @bahmet. Huge thanks for having reported back how to fix it and having closed the bug as well. That's an impressive community mindset. Kudos. :)
