### ISSUE TITLE
Navigation index.html

### ISSUE THREAD

**Issue by sophiegc** [Simbul/baker#319]
Hello, 

I am working with your framework to create a Yoga Sutra publication. This is my final school project !

I have a small problem with my navigation bar. The index.html contains links to the different pages in the book, but whenever i click on one, the index.html itself turns into the page.

Can anyone help me with the double-tap navigation links !

Thank you (:

**Comment by Simbul** [comment]
You can start by having a look at the Wiki: https://github.com/Simbul/baker/wiki/Managing-links-and-urls (although that's not specifically about the index bar).

If you still can't fix it, could you post the code for one of the links that are not working?

**Comment by folletto** [comment]
Hi @sophiegc did you solve that issue?

**Comment by sophiegc** [comment]
Yes i did, don't ask me how, but eveything is working pretty good now!
I basically created a new file and started over.

Thank you for the support (:

**Comment by bahmet** [comment]
@sophiegc hi, which file you created exactly. i have the same problem here. 
thanks

**Comment by folletto** [comment]
@bahmet Could you please answer the questions I asked on your issue thread? ;)

**Comment by bahmet** [comment]
ok, i found my error, forgotten ] in book.json file
