### ISSUE TITLE
Internal referencing 

### ISSUE THREAD

**Issue by franz49** [Simbul/baker#32]
Hej everybody, 

we are currently working on an eBook and are using the Baker framework. I know this is isn't the right place for questions and support, but nevertheless there seems no other location to do so. 

The specific question I have, is concerning the internal links. As HPub is using *.html files within the book folder I'm kind of keen to use some 'a href=""' referencing to jump from one page to another. Naturally this only works partially and I indeed see the right content but still be one the page I'm coming from. 

Is there a clever solution to allow internal referencing?

Kind regards, Franz

**Comment by folletto** [comment]
There's another location to ask for support: email. :)
See at the bottom of the website: info AT bakerframework DOT com

~

The solution you are looking for is already in our master GitHub branch, it's just not released yet on the website's zip file. :)
Download the current master from here: https://github.com/Simbul/baker (top-right corner, "Downloads") until we release the next official framework. :)

**Comment by franz49** [comment]
Cool. Thanks a lot. But anyway it would be great to have a kind of forum to prevent that my clones send you a eMail each time they're wondering about internal referencing... :-)

**Comment by folletto** [comment]
I agree, but for now the load is high but not so high and the questions are mostly bugs or feature request. :)

We'll surely think of a better way of communicating if this project gets more success. ;)
