### ISSUE TITLE
Jerky swipe

### ISSUE THREAD

**Issue by yumyo** [Simbul/baker#322]
I ran my test with the "white-flash-fix" branch. In my book.json I set "-vertical-bounce: false" and noticed a jerky animation swiping between pages. 
Any idea? 
The problem mitigates if I enable "vertical-bounce" for both modes. At a closer look I noticed that it seems related to the javascript code execution in my heavier pages. But I'm not sure. There's a way to set a delay between the screenshot fade-out and page rendering? Or... may be the problem comes from elsewhere?

**Comment by Xm4s** [comment]
Sorry, but I wasn't able to reproduce the problem by setting "-baker-vertical-bounce: false" in our test book, so maybe the problem did comes from elsewhere :)

Have you tryed to turn off the javascript on your pages and see if the problem remains ?
Also what do you mean when you say _enable "vertical-bounce" for both modes_ ?

**Comment by folletto** [comment]
Hi @yumyo is there any development about this issue?
