### ISSUE TITLE
Memory Issue in iPad 1

### ISSUE THREAD

**Issue by nruffilo** [Simbul/baker#323]
We have  fairly large book (40+ pages, total of 150 MB for the project, mainly due to 100 megs of audio that is on an activity we have).

But, it works wonderfully on iPad 2.  For iPad 1, it fails.  After running on device in debug mode, I have the following:

The app ALMOST opens, then fails (crashes).  Any thoughts on how to fix this?  No one page is more than 2-3 megs at a time.

Feb 22 12:59:19 Test-iPad1 YFEB[136] <Warning>: • Show page details for the book pages
Feb 22 12:59:19 Test-iPad1 YFEB[136] <Warning>:     Unlock page changing
Feb 22 12:59:21 Test-iPad1 SpringBoard[28] <Warning>: Received memory warning. Level=1
Feb 22 12:59:22 Test-iPad1 configd[25] <Notice>: jetsam: kernel memory event (91), free: 456, active: 3532, inactive: 1859, purgeable: 0, wired: 12264
Feb 22 12:59:22 Test-iPad1 SpringBoard[28] <Warning>: Received memory warning. Level=2
Feb 22 12:59:23 Test-iPad1 configd[25] <Notice>: jetsam: kernel termination snapshot being created
Feb 22 12:59:23 Test-iPad1 com.apple.launchd[1](UIKitApplication:com.YFEB[0xf1b0][136]) <Notice>: (UIKitApplication:com.YFEB[0xf1b0]) Bug: launchd_core_logic.c:3795 (24506):0
Feb 22 12:59:23 Test-iPad1 com.apple.debugserver-50[135] <Warning>: 1 [0087/1503]: error: ::read ( 4, 0x2ffcf9f0, 1024 ) => -1 err = Bad file descriptor (0x00000009)
Feb 22 12:59:23 Test-iPad1 com.apple.launchd[1](UIKitApplication:com.YFEB[0xf1b0][136]) <Notice>: (UIKitApplication:com.YFEB[0xf1b0]) Bug: launchd_core_logic.c:3794 (24506):3
Feb 22 12:59:23 Test-iPad1 com.apple.launchd[1](UIKitApplication:com.YFEB[0xf1b0][136]) <Notice>: (UIKitApplication:com.aerbook.YFEB[0xf1b0]) Bug: launchd_core_logic.c:3202 (24506):10
Feb 22 12:59:23 Test-iPad1 com.apple.launchd[1](UIKitApplication:com.YFEB[0xf1b0][136]) <Notice>: (UIKitApplication:com.YFEB[0xf1b0]) Working around 5020256. Assuming the job crashed.

**Comment by folletto** [comment]
Could you check if it's something about the screenshots by turning on three-cards instead?
If it's about screenshots, then it's probably the same as Issue #258. :)

**Comment by nruffilo** [comment]
I set my first page to be a static HTML page (our table of contents) and it worked OK - but i couldn't turn the page.  Our pages make pretty strong use of javascript and CSS transitions (although, they do work in just safari if I load them that way).

Because the triggers for animation are on page-load three-card is NOT an option for us.  But, I did try with three-card and it worked fine...

We were using pre-generated screenshots...

Please, is there anything we can do?  Shouldn't screenshot be a smaller footprint?  Our total screenshots folder is less than 10 megs

**Comment by folletto** [comment]
Screenshots are small as files, compressed. In memory they expand to be as big as they need to be, about 19Mb each.

So, now you have 2 choices:
1. You use screenshots and wait until Issue #258 is fixed.
2. You use three-cards and change the animations from `onload` to `window.addEventListener("focus", function() { ... }, true);`, as per Feature #225. :)

**Comment by nruffilo** [comment]
Last update on #258 was 2 months ago - has there been any movement on it?  I want to use pre-generated landscape screenshots, can I take the latest branch and have that work?  

-Nick

**Comment by folletto** [comment]
Yes, it's planned for 3.2, @Xmas is working on it right now. It's quite the last thing standing before 3.2 release. :)

I don't think that the current codebase will help with the problem. It's mostly a memory issue there.
