### ISSUE TITLE
My new book "HoneyComb and the Little Mouse" with my own characters on Apple Store!

### ISSUE THREAD

**Issue by marciosm** [Simbul/baker#326]
It's a dream coming true, as it's a project of 17 years ago. And with 3 languages in the same book: english, spanish & portuguese :D.
Thank you very much, Baker team for your help and support. It's really a dream.
If you want to take a look at the book, please visit http://lnkd.in/9wRz7H  !

**Comment by zenz** [comment]
Congratulation!

**Comment by webschnecke** [comment]
Cool,

are all languages in your book/ folder?
01.hmtl, 02.hmtl,03.hmtl = english
04.hmtl, 05.hmtl,06.hmtl = spanish
07.hmtl, 08.hmtl,08.hmtl = portuguese

Or do you use the Xcode Lacalization folder? 
en.lproj/book
sp.lproj/book
po.lproj/book

greetz

**Comment by marciosm** [comment]
I separated by file names, exactly as you wrote (from 1 to 10, english - from 20 to 30.html, portuguese and so on) not using the Xcode way :)
The "jump" is to have a language page on every end o session/ language

Marcio Morais
(11) 9778-9873

**Comment by webschnecke** [comment]
The Jump is...

What do you mean?

**Comment by marciosm** [comment]
Sorry. Here in Brazil we call a hint or a trick as a "cat's jump - o pulo do gato" . It's a way to say that the only way that I found to make it work fine was that, so the user does not have the sensation that I created the book as a sequence of languages. The language page, by the way, has limited movements to the sides, not allowing flipping to left or right. Just clicks. Regards :)

**Comment by marciosm** [comment]
Tks for all your reviews! Regards, Marcio.
