### ISSUE TITLE
Save data on database

### ISSUE THREAD

**Issue by dudisitchy** [Simbul/baker#328]
Hi there,

There is a way to send information from my magazine to some database ?
I would like to save the moment (date time) that the application was opened or some page was opened in a database outside the app (like php/mysql work).

Could some one have any idea ?

Thanks a lot !!!

**Comment by Ferprosa** [comment]
You can add to your app Google analytics in order see the behavior or you can add code in javascript that make a post to a PHP file hosted in a server.

**Comment by dudisitchy** [comment]
Thanks for your answer Ferprosa.
Do you know how javascript can post to a php file hosted in a server (the code)?

**Comment by Ferprosa** [comment]
Not in detail but, i've made a form that send the data to a PHP file in my server. That php insert a record into a Mysql table.
May be, executing a post once the page is complety load (Plase see Jquery tutorial).

**Comment by dudisitchy** [comment]
Ok man...
I was thinking that would be a simple code to make this communication.
I will see the Jquery.
Thank you !!!

**Comment by folletto** [comment]
I close this issue since it seems that a solution is on its way. Please re-open it if you want to continue the discussion, if you want to provide a solution yourself or ask anything else related to this. :)
