### ISSUE TITLE
HTML5 Audio Tag Autoplay

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#33]
It seems that Apple has not implemented this feature in their HTML5 webkit implementation for the iPad.  Is this something you are planning on supporting in a different way in a future release of Baker?  The reason I'm asking is that I was creating a travelogue photo book and wanted to have autoplay audio commentary on the pages.

**Comment by folletto** [comment]
Our plan is to use the current WebKit engine, so for now I don't think we are going to re-implement it. However, are you sure you can't do that even today with a little of javascript attached to the ready event of the page?

**Comment by vanderbreye** [comment]
yes, JS will work, you can trigger the play/pause event of the html5 player easily.
btw., autoplay for video works fine in webkit..

**Comment by nin9creative** [comment]
I did find some Javascript stuff online after I posted this comment...  However in some of the comments on a couple blog posts people mentioned that the autoplay workaround using Javascript was broken in iOS 4+.

I haven't been able to get anything to work.  Maybe I'm a moron though.  I've dorked around and can't get JS to trigger the play event.

@vanderbreye - do you have any example that you know works?

Thanks guys!
Andrew

**Comment by vanderbreye** [comment]
sure. it is only video, but i assume, this would work on audio as well..

<pre>
<script>
$(document).ready(function() {

function playPause() {
  var myVideo = document.getElementsByTagName('video')[0];
  if (myVideo.paused)
    myVideo.play();
  else
    myVideo.pause();
}

   playPause()
 });
</script>
</pre>


for video, this is clearly running on IOS 4+.

**Comment by Xm4s** [comment]
UIWebView has an attributes "mediaPlaybackRequiresUserAction" from iOS 4.0+, default YES
Reference: http://developer.apple.com/library/ios/#documentation/uikit/reference/UIWebView_Class/Reference/Reference.html

**Comment by nin9creative** [comment]
Thanks Xm4s...  After changing that default setting in the actual Baker Framework code, I'm able to use the autoplay feature of the HTML5 audio tag and it works great.  Thanks for posting that!

Andrew

**Comment by ghost** [comment]
Hey, i'm new  here, sorry if i'm not already at the same speed of all of you.

I've developed a simple page with audio inside. It's html5, mp3, and with standard html5 works.

The problem, or better the feature needed, is that the reader can't change page without stopping the audio / video.

I understand this can bring the discussion far from the direction of this thread, but I'm working to find a solution to have audio / video without iframes even changing the pages. Is someone working on this matter ?

**Comment by folletto** [comment]
If you need a background audio I think you can just add that in Objective-C and control it maybe through javascript calls. Unfortunately there's nothing "native" in HTML that persists through different pages.

**Comment by ghost** [comment]
Yes, this is what I was thinking about. Could be an extension of HTML: [a href=url target=_player]with or without text[/a] Loading the page the app should show a play button at the bottom of the screen, for example. This is the idea. I'll try even if I'm a newbie in C.

**Comment by folletto** [comment]
I think we can mark this as closed, tho. :)
