### ISSUE TITLE
Embedded interactive quiz in Baker?

### ISSUE THREAD

**Issue by chuckbrandt** [Simbul/baker#331]
Hello,
     Let me start by saying I am a native iOS developer not a web or javascript developer, so this is probably a dumb question. 

Imagine a book created in Baker that is a lot like a textbook.   At the end of each chapter there are a series of questions that test you on the content in that chapter.   Would it be possible to fill in a form with the questions and have your answers graded?   This would have to be done in javascript would it not?   And could this all happen locally, without a webservice - off-line?

Also is there a version of baker or something similar that works on Android?

Thank you,

Chuck Brandt

**Comment by folletto** [comment]
Hello. :)
1. Baker books are completely packaged and standalone, but you can make them interact with the web by using iframes and javascript.
2. You can absolutely do that (actually I saw something in our showcase that does that). You just have to create a javascript library that handles it all and you're done. :)
3. For Android, one contributor built Friar framework, here: http://www.friarframework.com/

**Comment by ghost** [comment]
@chuckbrandt you can always put in your own native code. 

I'm not quite sure how to do the intercept code from webkit to go back to native; however, I would assume that you put something in - perhaps a CGFrame overlay.

**Comment by folletto** [comment]
Doing that is quite simple actually: http://stackoverflow.com/questions/9473582/ios-javascript-bridge/9473941#9473941 :)

However it's usually more complex than doing the same in HTML, if you don't want high speed and fancy effects. :)

Does this reply to you @chuckbrandt? :)

**Comment by chuckbrandt** [comment]
Thank you this is all very helpful.   We are going to try a small sample and see how it goes.  Chuck
