### ISSUE TITLE
.net top 10 ways to create Digital magazines

### ISSUE THREAD

**Issue by charge-valtech** [Simbul/baker#333]
Not sure if anyone's seen this... good to see Baker mentioned!

http://www.netmagazine.com/features/top-10-ways-create-digital-magazines

**Comment by Simbul** [comment]
And Laker as well! So we have 2 spots out of 10, not bad ;)

**Comment by folletto** [comment]
WOW! Thanks for the link :)
Do you have a twitter handle? I'd love to credit you in our tweet about it. :)

**Comment by charge-valtech** [comment]
Sure! @henrycharge 

Thanks

**Comment by folletto** [comment]
Done!
Thanks again :)
https://twitter.com/bakerframework/status/175552084907802624
