### ISSUE TITLE
internal links in a page

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#334]
hi all,
i have some internal and external links in my page. external links worked after i followed this instructions  https://github.com/Simbul/baker/wiki/Managing-links-and-urls (thanks to folletto) however i could not manage internal ones. the link points to a page in my book, this works in index.html (means when i browse thru index.html it goes to the selected page ). 
can someone help me to solve this, can someone give me an example on how to use <a href="new-page.html#anchor">Link to new page</a> which is described in https://github.com/Simbul/baker/wiki/Managing-links-and-urls
thanks in advance :)

**Comment by folletto** [comment]
Could you post an code example of what you are writing to see first the starting point? :)

**Comment by bahmet** [comment]
i wan to do basically the following. this works on web on computer, works on safari, does not work on safari on ipad, does not work in the app
you can check here http://dijitalyayincim.com/book/boyama.html
 thanks...

`<a href="boyama2.html"><img src="images/esek_boyama.png" width="150" height="150">Esek</a>`

**Comment by folletto** [comment]
If it doesn't work on Safari, it won't work ever in Baker, I'm sorry.

The link however looks fine, as long as you have a page called "boyama2.html" in the same folder and in `book.json` it should work fine.

**Comment by bahmet** [comment]
thanks @folletto ,
this is exactly the point that i can not solve. same link works on index.html but does not work on other page. i have  "boyama2.html" in the same folder and in `book.json`.
weird ha?? :)

**Comment by folletto** [comment]
Is there maybe some javascript on the other page that might impact it?

**Comment by folletto** [comment]
@bahmet did you check the question above?

Also: could you send us the file, so we can check it?

**Comment by bahmet** [comment]
@folletto hi,
yes there is a javascript which i used after i see this thread  https://github.com/Simbul/baker/issues/142 . when i do not use the script, links work internal and external.
also you can check it here http://dijitalyayincim.com/book/boyama.html
do you want the html file or the book folder?
thanks

**Comment by folletto** [comment]
Yeah, the javascript might impact the ability to open pages.

The book folder if it's possible, just the index.html otherwise. :)

**Comment by bahmet** [comment]
hi , you can find the book folder here http://dl.dropbox.com/u/51424384/book.rar
thanks

**Comment by folletto** [comment]
Ok, received. We'll check. :)

**Comment by Simbul** [comment]
Hi @bahmet, I have downloaded the archive right now but I can't seem to unzip it, as it is asking for a password. Any hint? ;)

**Update**: my bad, you sent that already.

**Comment by bahmet** [comment]
Hi
It is github
Thanks

**Comment by Simbul** [comment]
Right, I've had a look at the code. Take this with a grain of salt, but I've been able to get the links working by commenting out the `event.preventDefault();` line in the `touchHandler` function in `html5-canvas-drawing-app.js` (it's line 99 in my copy of the file).

So after the edit you should have something like:

```
...
simulatedEvent.initMouseEvent(type, true, true, window, 1, 
                          first.screenX, first.screenY, 
                          first.clientX, first.clientY, false, 
                          false, false, false, 0/*left*/, null);

                          first.target.dispatchEvent(simulatedEvent);
// event.preventDefault();
}
...
```

(I'm showing a bunch of lines for context).

Caveats: I have not been able to test this on the device, only on the simulator. Also, it's possible that removing that line will cause issues somewhere else. I couldn't find any, but I did not test it thoroughly.

**Comment by bahmet** [comment]
@simbul thanks for your efforts. i did what you suggested. links work now. 
however since the colorbook pages act like normal pages, you can not draw or color the image. left and right edge navigation works, so when you click that parts, page changes. also page is not locked anymore, so every touch of you moves the page.
i guess, if i lock the colorbook pages and only navigate with the links at the bottom it will work. do you have any idea how to do that ;)
thanks again

**Comment by Simbul** [comment]
Yup, I confirmed the behaviour you talk about on the actual device (weirdly enough, it was fine on the simulator).

I think I may have another fix for you: go back to the previous code (e.g. uncomment `event.preventDefault();`) and then change the code starting at line 104 in `html5-canvas-drawing-app.js` to:

```
function prepareCanvas()
{
  // Create the canvas (Neccessary for IE because it doesn't know what a canvas element is)
  var canvasDiv = document.getElementById('canvasDiv');

  canvasDiv.addEventListener("touchstart", touchHandler, true);
  canvasDiv.addEventListener("touchmove", touchHandler, true);
  canvasDiv.addEventListener("touchend", touchHandler, true);
  canvasDiv.addEventListener("touchcancel", touchHandler, true);
```

What the edit does is to add the touch event listeners to the div where the drawing happens instead of the whole page. This means links won't be affected but drawing will work as expected.

I've tested it on my iPad and it seems to be working. Let me know if it solves the issue for you as well :)

**Comment by bahmet** [comment]
hey @Simbul thank you very much, yes, this solved my problem... you are great....
thanks :))

**Comment by Simbul** [comment]
Brilliant!

**Comment by bahmet** [comment]
hi all,
now i have another weird link problem. 
i have a page which has 286 different links to the anchors in the same page,
i followed https://github.com/Simbul/baker/wiki/Managing-links-and-urls to create links, however it does not work.
links go to a place in the same page but not the anchor that i wanted
i tried `<a href="Sayfa-02.html#BAKARA-1"><k1>1: Elif, lâm, mim.</k1></a>`not worked
i tried `<a href="#BAKARA-1"><k1>1: Elif, lâm, mim.</k1></a>` also not worked.
her comes the weird part.... this all works on safari, firefox, and chrome. but does not work on simulator and the device..
i am using Baker's latest release downloaded from github
the html file is here for your reference http://dl.dropbox.com/u/51424384/book/Sayfa-02.html 
i would appreciate if you can advice
thanks

**Comment by bahmet** [comment]
@Simbul @folletto 
guys how can i reopen this issue? thanks...

**Comment by folletto** [comment]
Please, open a new issue, since it's a different problem. ;)
