### ISSUE TITLE
Page cache

### ISSUE THREAD

**Issue by dudisitchy** [Simbul/baker#336]
Hi there...
I am facing some problems with app after build. When I build the app and update it on ipad, the pages open first the last page build and then the correct.
Is there a solution for this ? Maybe disable the cache ? How to do this ?

Thanks a lot !!!

**Comment by folletto** [comment]
I guess you are using the app in Screenshot mode. :)

Try doing a _Proper cleanup_: https://github.com/Simbul/baker/wiki/Proper-cleanup

And try again. ;)

**Comment by dudisitchy** [comment]
Thanks folletto...
If I make the proper cleanup and upload the updated app for customers download, the "cache" will not happen anymore?

**Comment by folletto** [comment]
Well the page shouldn't change once it's done, right? :)
So the customer will have the final version, and that will be the right one. :)

If you have dynamic pages instead, and you don't want the user to get the default view first, then you should switch to `-baker-rendering: three-cards` view: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters :)
