### ISSUE TITLE
Modal WebView: doesn't trigger rotation of Book

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#337]
After merging the Pull Request #325.

BUG: Unfortunately, we found a bug: when you are in modal view, and rotate the iPad, and then close the modal, then the navigation is broken until you rotate the iPad again. It's probably because the modal view doesn't call our rotate function.

Steps to reproduce:
1. Open Baker
2. Open an external view into the modal WebView
3. Rotate
4. Close the modal WebView
5. Try to swipe

**Comment by steiny2k** [comment]
whow. that looks pretty ugly :( sorry for causing this.

I was quickly looking into this, but it seems to be a bit more complex than just calling the appropriate orientation-methods from `RootViewController.m`. I'll dig a bit deeper soon. Keep us updated when you find something on this. Thx.

**Comment by folletto** [comment]
Yup, let's use this thread to sync. :)

**Comment by steiny2k** [comment]
please have a look on pull request #343
