### ISSUE TITLE
Modal WebView: statusbar shows up

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#338]
After merging the Pull Request #325.

BUG: Unfortunately, we found a bug: if you double tap the status bar appears on top, cutting the toolbar. Instead, if it's open before opening the modal view and then you double tap, the modal window will leave a gap at the top.

Steps to reproduce:
1. Open Baker
2. Open an external view into the modal WebView
3. Double tap
4. See the status bar cutting the toolbar

Or:
1. Open Baker
2. Double tap
3. Open the modal WebView
4. Double tap
5. See the gap where the status bar was

**Comment by steiny2k** [comment]
see pull request #343

**Comment by Xm4s** [comment]
Fixed with pull request #343
