### ISSUE TITLE
Display of downloaded book not working on the iOS Simulator and partly working on iPad

### ISSUE THREAD

**Issue by MacBoy** [Simbul/baker#34]
In the iOS Simulator, I downloaded and ran the latest Baker files (as of January 04, 2010).

In preparation for the testing of the download-and-display-a-new-book, I did the following:
1. Copied the files of the built-in book to a new folder
2. Modified Chapter 1 of the new book to make it obvious it was the new book
3. Zipped-up all the files within the folder (but not the folder itself)
4. Renamed the zip file to book10.hpub
5. Moved the book10.hpub zip file to /Library/Webserver/Documents
6. Turn on the web server of the Mac computer
   System Preferences --> Sharing --> Web Sharing --> Enabled
7. The local Web Server will be referenced via the 127.0.0.1 address by links within the HTML pages of the book
8. Then I compiled and ran the latest Baker sources within the iOS Simulator
9. Within the simulator, I went to Chapter 3 of the built-in book
10.  In Chapter 3, scroll down to the link named "A medical student ..."   
11. A tap on that link downloads the new book (book10.hpub) from your computer's web server (neuro.local)
12. The new book is successfully unzipped and the old files are replaced by the new files. This was verified by checking for my custom modification to the book files. ( Home/Library/Application Support/iPhone Simulator/4.2/Applications/###/Documents/book )
13.  !!! However !!!  The book files are not being displayed in the iOS Simulator for the Baker app. The displayed text is "Mac OS X 2AATTRSA)) com.apple.quarantineq/000;4d22bf7c;Safari;com.apple.Safari
14.  !!! Debugger Console log !!!  shows that the file being fetched has the wrong file name:
    Goto Page: book/._Chapter 01.html
    [+] Loading: book/._Chapter 01.html

Conclusion:  Instead of loading ._filename.html,  it should be loading  filename.html (without the ._ characters)

Its great accomplishment in registering a new URL type (book://) and downloading a zipped book and expanding it.  Now just have to properly display the new book.  

Almost there!

:-)

**Comment by MacBoy** [comment]
Just for completeness, I tried it on the actual iPad -- it works !!!

:-)

For those following along, do the above steps 1-11

Wonder why it does not do it properly on the iOS Simulator?

I changed the title of the issue to show that its a problem with the iOS Simulator and that it partly works on the iPad.

**Comment by MacBoy** [comment]
When the book download occurs, the old book is deleted and the new book replaces everything.  However, it seems the old pages are not completely deleted, they remain as ghosts.

If the book originally had 12 pages, and the new book has 12 pages, then the total page count is 24.

However, only the new 12 pages are displayed correctly. The old ghost pages, now renumbered to 13-24, are showing the error message of:

"Mac OS X 2 TEXTATTR com.apple.TextEncodingUTF-8;134217984"

I am not a skilled iOS developer, thusly, I try to be a good tester.  I'll look at the code to see if I can find the bug.

**Comment by Xm4s** [comment]
Hi MacBoy,

For what I can see the problem lies in the "._" files: those files are resource forks that are probably created by Mac OS X during the .zip creation. Since their extension is .html the framework recognized them as valid pages and showed them in the correct order.

I've released some fixes tonight, one of which is a new method for retrieving the html files from the book folder that ignore resource forks. With this the problem of the "ghost files" should be solved :)

Thank you for the help, I'll wait for your feedback on the fix before closing this up.

**Comment by MacBoy** [comment]
Hello Xm4s,

It is fixed, thank you for the very quick response!

I've noticed that you have changed the link on Chapter 3 to be 127.0.0.1 instead of neuro.local -- that is a good idea, I will edit my instructions accordingly.

Thank you!

**Comment by Xm4s** [comment]
Oh, yes... neuro.local is the name of my local server, I've written out of habit while I was doing some tests :P Yes, 127.0.0.1 is much better.

Ok, bug fixed, i'm closing this up :)
