### ISSUE TITLE
Toggle bar and show like app

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#340]
Hi,

I'm trying to show my toggle bar like the case of "Forgotten Colours" but i don't know how to make it. Can anyone tell me how to make it?

Also I want to show my book like a app, out from newsstand.

Sorry about my english and thanks

**Comment by folletto** [comment]
What do you mean by "like the case of Forgotten Colours"? What behaviour are you referring to? :)

To remove it from Newsstand just have a read on the wiki: https://github.com/Simbul/baker/wiki/Newsstand-support

**Comment by ghost** [comment]
I mean the first case of showcases at baker web:

http://bakerframework.com/books

You can download the free version to see it

**Comment by folletto** [comment]
Yes, what about it? What do you want to replicate? :)

As far as I know, they did a custom development in house based on Baker. So, if you can't point out anything specific, it's better if you contact them directly and ask them if their App codebase is for sale. The link is on the same page you linked, they are Play Creatividad. :)

**Comment by ghost** [comment]
I just want to make a link (image for example) where i can show the toggle bar as wel as double tab. Is that posibble?

**Comment by folletto** [comment]
I think it needs to be all custom development unfortunately.

**Comment by ghost** [comment]
What do you think if i do this with JavaScript into the html page? Is it possible?

**Comment by folletto** [comment]
Sure you can. :)
Almost everything that's doable in a website, can be done in Baker... since it's HTML. :)

**Comment by ghost** [comment]
Thanks :)
