### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by trikanna** [Simbul/baker#341]
I was wondering about the idea of **create a series of themes for the framework**. I've made some projects with Baker and always I started from the ground, but in some cases the projects have some common elements.

Tks. Santiago Camelo

**Comment by folletto** [comment]
I think they will be very well received. As of today, the only official one with a good tutorial is Laker and it's the only choice to start with. We are receiving lots of private contacts of people asking for more resources, but as you can imagine there isn't much time for us to do that. :)

**Comment by trikanna** [comment]
ok, I'm in.

**Comment by ffranke** [comment]
A theming engine would indeed be great.. ;)

**Comment by trikanna** [comment]
i'm just thinking the best approach

**Comment by folletto** [comment]
Is there any update on this idea? Any progress?
