### ISSUE TITLE
360 degree photo

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#344]
hi,
has anyone used http://jquery.vostrel.cz/reel jquery-reel plugin in their projects. what is the performance issue? do you use any other 360degree photo plugin ?
thanks

**Comment by mikadonguyen** [comment]
http://itunes.apple.com/us/app/360-party/id508029609?mt=8 This is my app use 360 with Baker :D Cheer

**Comment by jayohTM** [comment]
i used: http://gardengnomesoftware.com/pano2vr.php with the html5 output.

**Comment by trashoid** [comment]
Hi, i try desesperatly to use jquery reel in baker.
It doesn't work.

I taste more version, always the same issue. The touch event of baker take first, and the page slide...

Could you help me please ?
