### ISSUE TITLE
Application failed codesign verification

### ISSUE THREAD

**Issue by abcd19886** [Simbul/baker#348]
warning: Application failed codesign verification.  The signature was invalid, contains disallowed entitlements, or it was not signed with an iPhone Distribution Certificate. (-19011)
Executable=/Users/linkzhengke/Library/Developer/Xcode/DerivedData/icaocao-clnsuzbltrnznxenvydlibouwylk/ArchiveIntermediates/Baker/InstallationBuildProductsLocation/Applications/icaocao.app/icaocao
codesign_wrapper-0.7.10: using Apple CA for profile evaluation
Illegal entitlement key/value pair: CFBundleInfoDictionaryVersion, 6.0
Illegal entitlement key/value pair: CFBundleExecutable, icaocao
Illegal entitlement key/value pair: CFBundleVersion, 1.0
Illegal entitlement key/value pair: CFBundlePackageType, BNDL
Illegal entitlement key/value pair: CFBundleSignature, ????
Illegal entitlement key/value pair: CFBundleIdentifier, com.deegold.icaocao
Illegal entitlement key/value pair: CFBundleDevelopmentRegion, zh_CN
AssertMacros: filter_entitlements(entitlements_whitelist, entitlements_requested, allowable_entitlements),  file: /SourceCache/codesign_wrapper_Sim/Security-1245/codesign_wrapper/codesign_wrapper.c, line: 918
- (null)

what shoud i  do?

**Comment by folletto** [comment]
To start, try explaining what you were doing and how you got that error ;)

**Comment by abcd19886** [comment]
i ues the xcode upload app.

**Comment by folletto** [comment]
Then you should refer to Apple documentation and forums, we can't help unfortunately on submission issues that are on the Apple side: https://developer.apple.com/devforums/

From the message above it seems that you aren't using the correct publishing certificates.
