### ISSUE TITLE
How to create IPA file of Baker Project

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#349]
Hi,

I'm very proud of me. I finished my book. But now i trying to export my project to testflightapp.com creating a IPA file. I try to execute the option "Product--->Build for--->Archiving" for create it but this option is desactivated. 

Help me please!

Thanks and sorry about my poor English

**Comment by folletto** [comment]
I'm afraid you'll have to ask either TestFlight support or Apple Developer support. We can't give support on Apple related issues here. :/

**Comment by folletto** [comment]
Have a try here:
- https://developer.apple.com/devforums/
- http://support.testflightapp.com/login?to=%2F

**Comment by carlostruji85** [comment]
Hola como solucionaste ese problema, estoy en el mismo dilema

**Comment by ghost** [comment]
Hola Carlos, 

Para compilar cualquier programa creado con Xcode tienes que darte de alta como desarrollador de Apple. No hay otra forma.

**Comment by carlostruji85** [comment]
Hola, ya estoy inscrito, pero mi problema es que estoy enredado con la cuenta y los certificados, si me podrías asesorar o contar tu experiencia te lo agradecería en el alma.

**Comment by ghost** [comment]
No soy muy experto en el tema. De hecho tuve que hablar con un amigo de un amigo para saberlo hacer. Por lo que pude quedarme con la copla. Primero tuve que crear los certificados para certificarme como desarrollador de Apple. Posteriormente si quieres probar la aplicacion en algun dispositivo tienes que darlo de alta en la parte de Devices. Por último para cada aplicación tienes que crear un APP ID y de ahí bajarte el provisioning (el de desarrollo y el de distribución para poderlo enviar a la applestore) Te hablo de memoria pero mas o menos son estos pasos. Te aconsejo que mires bien la documentación. Suerte :)

**Comment by carlostruji85** [comment]
Muchas gracias por tu tiempo, mas o menos esos son los pasos que e hecho pero cuando exporto la App desde el Xcode me dice que hay un error en el ceritificado y por consiguiente no puedo subirla al store

**Comment by ghost** [comment]
Eso es porque después de instalar el certificado en el proyecto tienes que buscar una opcion que se llama "Build Sign" y tienes que seleccionar el certificado que te has bajado.

**Comment by mutador** [comment]
hola
la verdad es un poco rollo, y casi imposible de contar aqui
existen dos certificados de desarrollo y de distribución que hay que poner en el xcode ademas del bundle, para subir la aplicacion es necesario usar las de ddistribución...
si eres de madrid puedes pasarte por mi estudio y ves como lo hacemos nosotros, sino puedo hacer escritorio remoto contigo y decirte como lo hacemos nosotros....
@ Woskis lo explica muy bien
revisa que tu ID este bien asociado a los dos certificados, que estos esten asociados a tu device y que esten en distribucion cuando vayas a subir la aplicación

pero ya te digo que es sencillo y lioso a la vez....
a veces los cerificados estan mal asociados arriba en el manage aplications ID, a veces mal bajados....

**Comment by carlostruji85** [comment]
Hola agradeceria enormemente tu ayuda, no me encuentro en Madrid estoy en Bucaramanga Colombia, vos me dirás cuando tienes un tiempo y me puedes colaborar.

gracias

**Comment by carlostruji85** [comment]
Mi Skype es carlostruji85 gracias

**Comment by carlostruji85** [comment]
warning: Application failed codesign verification.  The signature was invalid, contains disallowed entitlements, or it was not signed with an iPhone Distribution Certificate. (-19011)

**Comment by mutador** [comment]
te he aadido ya a skype, a ver si podemos ayudarte

El 26/03/2012, a las 20:47, carlostruji85 escribi:

> carlostruji85

Hola

Un Saludo :-)

Manuel Otero | Director creativo
T. 91 50 60 376  609 94 48 78
Email: manuel@mutador.com
Estacion de trabajo: El Cisne 
Direccin: C/Esperanza n12 Bajo Derecha 28012 Madrid 
Web  Portfolio: www.mutador.com

---------------------------------------------------------------------------- Noticia legal----------------------------------------------------------------------------

Este mensaje electrnico contiene informacin de mutador.com, que es privada y confidencial, siendo para el uso exclusivo de la persona(s) o entidades arriba mencionadas.Si usted no es el destinatario sealado, le informamos que cualquier divulgacin, copia, distribucin o uso de los contenidos est prohibida.
