### ISSUE TITLE
Font Replacement

### ISSUE THREAD

**Issue by transmitter** [Simbul/baker#35]
Hello
My first post so I apologize for missing any etiquette. Doing a quick search of issues I see no one has posted regarding font replacement. I'm putting a book together which would ideally use Cufon font replacement for headlines and body copy. The issue is Cufon uses a domain confirmation as a way of protecting fonts from abuse. When creating a font file for use with Cufon one must upload the otf or ttf file to the system and define domains that are approved to use it. How would this domain auth work once the hpub is uploaded to the app store? Should I use another replacement technique?

**Comment by folletto** [comment]
Before diving into it, there's some reason why you can't use the standard CSS3 font-face directive?
http://www.css3.info/preview/web-fonts-with-font-face/

**Comment by transmitter** [comment]
Ahh thanks for that. I was thinking old-needs. I use cufon for its X-browser compatibility which is not a requirement for this. Thanks!

**Comment by folletto** [comment]
No worries! Have fun! ;)

**Comment by transmitter** [comment]
Now - sadly - Using both embedded and inline declarations for my @font-face rules and trying multiple url references for the .otf files, The xcode simulator doesn't show the replaced fonts. browser testing shows that they are displaying as intended. If you have any ideas that would be hugely helpful.

**Comment by folletto** [comment]
...and what happens on the device? :)

However without the code you're using it's hard to guess what your problem could be. :)

**Comment by transmitter** [comment]
folletto: sorry for disappearing and thank you for your help. I had a syntax error preventing font replacement from activating properly. I need to look a little closer before posting. - cheers.
