### ISSUE TITLE
My new application The Town Musicians of Bremen

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#353]
hi all,
i am very proud to tell you that my first ipad application is published today on app store. i would like to thank all the baker project guys here, especially @folletto for his patience to my never ending questions.
application is in Turkish, short story of The Town Musicians of Bremen (German Die Bremer Stadtmusikanten) with animations and sounds + color book.
it is free, get your copy and review, feel free to ask if you have any questions. Comments are also welcome...
thank you baker guys....
http://itunes.apple.com/ee/app/bremen-m-z-kac-lar-interaktif/id507130003?mt=8

**Comment by tstegart** [comment]
Congratulations! I hope it does well.

**Comment by folletto** [comment]
Congratulations. :)
And thanks to you. :)

**Comment by mikadonguyen** [comment]
Congratulations :D
