### ISSUE TITLE
DUDAS EN ESPAÑOL

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#354]
Hemos abandonado el projecto baker, por lo que no podemos seguir dando respuestas sobre el.

**Comment by aguebel** [comment]
Quería saber si tenías alguna novedad con el tema de newsstand y suscripciones. Tenemos un cliente al que le hicimos una publicación con Baker que quedó muy bien, el tema es que ahora nos pide poder subirla al kiosko o hacer que los usuarios puedas suscribirse mensual o anualmente, hay algo hecho open source o a valores razonables que no involucren el DPS de Adobe? gracias.

**Comment by mutador** [comment]
es el tema del millón...de baker no hay nada por el momento.(hay gente que esta trabajando en ello pero nada aún)
http://urbanairship.com/   - esto puede ayudarte algo.
http://urbanairship.com/products/subscriptions/

y da la sensación como si yo hubiese hecho algo de baker y no es el caso...solo lo utilizo y hablo español...

**Comment by aguebel** [comment]
Perdón, pensé que estabas en el equipo que está haciendo Baker, gracias por la info.

**Comment by mbayona** [comment]
Hola Mutador! El problema es que eres muy amable.  En verdad gracias por tus comentarios y experiencia con esta herramienta formidable...

**Comment by ghost** [comment]
Hay un fork de una versión de Baker que soporta varios hpub en una aplicación. Con activar la opción  de newstand en el book.json y tal vez algún tipo de identificación por usuario se pueda hacer.

https://github.com/orangesparkleball/baker/tree/multiple-hpubs

**Comment by belgo** [comment]
Hola, 
Soy Serge de BCNBase, Barcelona.
He trabajado mucho (18 Apps) con el DPS de Adobe (*), pero los costos me han espantado y ahora las estoy desarrollando en HTML5 y con Baker.
Quisiera saber si hay alguna manera de que las dos páginas, vertical y horizontal, sean diferentes, es decir que al girar el iPad (iPhone) se accedan a 2 html distintos... ¿será posible?
Cordialmente

—Serge

(*) Puedes ver mis Apps aqui: http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewArtistSeeAll?dkId=11&ids=427866506&softwareType=iPad

**Comment by mutador** [comment]
buena pregunta pero nunca lo he pensado, en principio no, por xcode coge solo una pagina html de cada vez ya que tiene que renderizarla
si lo que necesitas es mostar un contenido u otro, con las hojas de estilo puedes literalmente tener dos paginas en una. con overflow=hidden; 

http://asidemag.com/grid/

este es un buen layout para comenzar, optimiza bien las imagenes para que valgan para ambos sentidos

**Comment by belgo** [comment]
Debe existir algún código que redireccione una página a otra cuando gire el iPad, pero ...¿donde? ...that the question!!
Si se te ocurre algo, te agradecería tu info y, de todas formas, si encuentro algo te lo comento.

Gracias.

—Serge

**Comment by mutador** [comment]
pero no te va a ser muy practico, por que el funcionamiento de baker es renderizar cada pagina, si al girar cambias de pagina aparecera un delay, y va a ser muy molesto, si es solo puntual con javascript lo vas apoder hacer seguro,.

cual es tu necesidad concreta? a la hora de que al girar sea una pagina distinta?

podrias investigar con iframes colocados los dos en posicion 0,0 y que al girar enseñe uno u otro con visible=false;

**Comment by belgo** [comment]
He podido hacer que cambie de página al rotar el device aplicando un redireccionamiento en el body (a partir de un comando "onresize") y efectivamente cambia la url interna. Funciona muy bien y por ahora no genera conflico con el "book.json", pero... hay otro problema... 
Necesito que el iPad pueda detectar si se encuentra en posición portrait o landscape y en función de esta posición cargar una página u otra. Ej. portrait cargue "portrait.html" y landscape -> "landcape.html".
Es muy importante que detecte la orientación inicial del iPad y que pueda cargar la página inicial correcta. Si no lo hace me carga la pagina inicial (a partir de book,json), no importa la orientación. Si esta página es vertical  y la orientación del iPad en posición horizontal ...toda la App me queda ...al reves!

(Sé que se puede hacer algo con css, pero me reordena los elementos de una misma página, no me redirecciona a otra diferente)

—Serge

**Comment by mutador** [comment]
te pille..... tu problema es que no sabes hacer la pagina para ambas orientaciones en una sola....
si es muy sencillo, con las propiedades visible=flase; según la orientación, tienes todo en una sola...a ver si te lo explico bien

*********\* esto en el css*************

```
/* iPad [portrait] */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation:portrait) { 

.landscape { display: none; }
.portrait { display: block; }

img.landscape { display: none; }
img.portrait { display: block; }

 #landscape { display: none; }
 #portrait { display: block; }
}

/* iPad [landscape] */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation:landscape) {



      .portrait {  display: none ;}
        #portrait {display: none; }

  #landscape {display: block; }

   img.portrait {  display: none ;}
    img.landscape { display: block; }
   .portrait {  display: none ;}
   .landscape { display: block; }




}
```

**************************_y en el html enseñas o oculatas las imagenes o los divs segun la orientación**_************

*img src="images/oviedo_int.jpg" class="portrait"  *
*div class="portrait ">  este contenido solo se muestra en portrait, aqui puedes poner todo lo que quieras </div *
- el asterisco remplazalo por <   >  

si quieres a lo bruto creas un div que contenga toda la pagina en portrait y otro en landscape, solo en un html
y si colocas un jpg le aplicas lo mismo, prueba ha hacer una pagina con 2 imagenes , una en vertical y otra horizontal, aplicale los estilos y veras como es mas comodo,  http://asidemag.com/grid/, este layout fluido es muy bueno, miralo y veras como es muy sencillo hacer una pagina para las dos orientaciones

y perdona por ser pesado en que solo hagas 1, si no es por nada especial que se me escape....es mejor

**Comment by belgo** [comment]
Gracias, funciona muy bien y me soluciona muy buena parte de mis problemas.

Claro que sigo necesitando encontrar una solución basada en 2 html diferentes porque somos varios los que vamos a trabajar en un proyecto literario que va incluir una versión horizontal para un idioma y otra vertical para otro (estas versiones se van a desarrollar por separada en estudios diferentes y en continentes diferentes...)
La única solución que se me ocurre por ahora es insertar una de las páginas en un <iframe> y asi poder utilizar tu método sin enredarme demasiado la vida!

De todas formas mil gracias por tu colaboración y cuenta conmigo para lo que necesites!

—Serge

**Comment by belgo** [comment]
Falta un pedazo de texto...

La única solución que se me ocurre por ahora es insertar una de las páginas en un < IFRAME > y asi poder utilizar tu método sin enredarme demasiado la vida!

Voila!

**Comment by rokanne** [comment]
Hola, gracias x abrir este hilo, quería preguntar una duda a ver si entre todos lo aclaramos porque he leido mil comentarios pero no me queda nada claro.

Quiero hacer que el index.html en vez de mostrarse con el double tap se muestre clikando un botón,para esto ya se ha comentado en otro hilo cómo deshabilitar el tap de la pantalla,pero no cómo hacer la llamada desde el botón.

Además en el index.html tengo varios contenidos a mostrar dependiendo de la página en la que esté a través de una variable localstorage ,con un setitem le doy un valor u otro.

El tema es que no he podido hacer que se comuniquen entre las páginas y el index.html, es decir, pongo un intervalo en el index para que cada 1seg me compruebe el valor de esa variable,pero no lo actualiza.

Aquí entiendo que han logrado hacerlo con una variable para controlar el play de la música a través de la aplicación..pero lo he probado y no he logrado hacerlo echar a andar:
https://github.com/Simbul/baker/issues/227#issuecomment-3520768
También hay un usuario que ha hecho bookmarks pero con Web SQL Database y comentan que mejor no usarlo xk..
-" which is officially deprecated by the W3C."
sos
gracias!!

**Comment by mutador** [comment]
lo siento, las dudas que yo te puedo resolver son mas ligeras, programación avanzada, nada, tendras que hacerla en ingles en el foro.
el tema del playmusic, que yo lo he intentado...y mi conclusión es que hay que programarlo desde xcode para que sea una UIWebWiew siempre presente, si la haces por programación xcode puedes hacer que cogiendola de un xml , se escuche aunque se cierre la aplicación....nosotros vamos ha intentar hacer una , asi que si damos con una solución te imformo...pero ya te digo que vamos a tirara por el metodo que te comento

**Comment by rokanne** [comment]
ok,muchas gracias!!...si ..habrá que implementar algo en objectivec...lo que vaya logrando lo voy publicando.

**Comment by rokanne** [comment]
yuju!!conseguí hacer que se comuniquen las paginas con el index a través de una variable localstorage ,lo comento por si os ayuda en algo que es una tontería pero como se te cruze..a ver..pongo un setinterval en un js y le llamo desde el index.html,de esa forma me chekeará cada seg el valor de la variable:
en menu.js

```
var ourInterval = setInterval(check, 1000);
function check(){
//alert(localStorage.tipomenu);
switch(localStorage.tipomenu)
{
case '1':
document.getElementById("nav1").style.display='block';
document.getElementById("nav2").style.display='none';
break;
case '2':
document.getElementById("nav2").style.display='block';
document.getElementById("nav1").style.display='none';
break;}}
```

Desde `index.html:script src="js/menu.js">` y dos  `div class="navigation" id="nav1"` y otro
  `div class="navigation" id="nav2"`  con distintos contenidos.
Desde las paginas donde quiero que se cambie esa variable en el evento de carga de la página le meto 1 y en otra pues que sea =2 x ejemplo:

```
 window.addEventListener("focus", function() {
                              localStorage.removeItem('tipomenu');
                              localStorage.tipomenu=1;
                              }, true);
```

de esa forma puedo tener varios div en el index.html y dependiendo que páginas e cargue le meto un div u otro , así consigo tener varios menús dentro del index y controlar su aparición.
Hay que darle unas vueltas all código pero esa es la idea.
Con el tema del player las variables funcionan de la misma forma.
Ahora lo que no he conseguido aún es el menú tipo dock...alguna idea???
Gracias a todos!!

**Comment by belgo** [comment]
Hola,
Estoy teniendo problema con algo que para ti debe ser muy simple pero que a mi me desborda...
He seguido todas instrucciones para generar los snapshots (https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book) pero no se genera el folder "Private Docs" en "iPhone Simulator"...
Hay algo que hago mal, pero ....¿Que será?

Gracias

**Comment by mutador** [comment]
ni idea @belgo , voy a cerrar este hilo por que he dejado de trabajar con baker, en el nuestro estudio hemos desarollado nuestro propio framework de trabajo -papereasy- y al no usar baker ya no estaré al dia de su evolución e implementaciones.baker es un gran proyecto y le estamos muy agradecidos, pero tenemos una necesidad de adptarlo a revistas digitales y evolucionarlo a un ritmo mayor.

**Comment by molorago** [comment]
hola buenos dias!!!
Estoy haciendo una revista en baker y uno de los requisitos que me piden es que al girar la pantalla no muestre una sola pagina sino que ya carguen 2 paginas, si puedes ayudarme te lo agradeceria muchismo

**Comment by erolando** [comment]
alguien tiene problema de que muestre una imagen como tipo "cache" al hacer scroll¿

**Comment by thejoepeach** [comment]
Morolago encontre una forma de hacer usando JS para leer dos paginas y mostrarlas aunque es algo artesanal pero mola, si quieres aun saber como hacerlo te puedo apoyar....
