### ISSUE TITLE
Baker file size - does the book folder matter?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#356]
I know a lot of people are working with magazines that have large images sizes and want to stay below the limit Apple sets for over-the-air downloads, so I thought I'd ask this file size question: Does xCode only pull in the files that Baker actually uses when it builds the app? Do I need to worry about leaving things in the book folder that I don't actually use, like the Baker example files, or do only the images I use in my magazine get put into the final build release? I want to know if I should delete the things I don't use in the Baker folder.

**Comment by folletto** [comment]
Yes, you should delete them, since Xcode can't check which files are in use and which aren't. :)

**Comment by tstegart** [comment]
Thanks!

**Comment by tstegart** [comment]
Sorry, one more question related this topic. When we use @font face to import fonts in our CSS like in Laker, does web view actually use all those fonts? Or can we delete some of the ones used for IE? Do you know which one we actually need?

**Comment by folletto** [comment]
What do you mean by "all those fonts"? Font-face loads only the fonts you tell it to load, and there should be one. Are you generating the code with some tool?

In general, Baker is Safari Mobile: you need to load only the typeface that works with Safari Mobile. :)

**Comment by tstegart** [comment]
Ah, ok. I used the tool suggested in Laker, the font-face generator from Font Squirrel. It gives you CSS that ends up like this example:

src: url('../fonts/oswald/oswald-webfont.eot');
    src: url('../fonts/oswald/oswald-webfont.eot?#iefix') format('eot'), url('../fonts/oswald/oswald-webfont.woff') format('woff'), url('../fonts/oswald/oswald-webfont.ttf') format('truetype'), url('../fonts/oswald/oswald-webfont.svg#webfont1Pz3m7lF') format('svg');

I think I can delete some of those because Laker is made to work on the web as well and I don't need that inside Baker.

**Comment by folletto** [comment]
The TTF should be enough, but check it. :)

**Comment by tstegart** [comment]
It is enough, thanks. I can confirm thats the only one you need.
