### ISSUE TITLE
Screenshots and large books

### ISSUE THREAD

**Issue by pixelrevision** [Simbul/baker#358]
The way the backing screenshots are managed can cause issues when creating a larger book.  We are currently working on a book with 80+ pages.  Because the screenshots are all added in up front and kept in memory during usage when you hit somewhere just over page 60 the app will run out of memory (this is on ipad 3 which has really large images).

This can also cause another issue of then not being able run the app after that without a full clean.  If there are 60+ images saved on disk the screenshots will be loaded until the app runs out of memory again not even giving the chance to look at the magazine.

The solution on our end is to switch to three-cards for the time being, just thought you guys should know.

**Comment by folletto** [comment]
What version of Baker are you using? I'm asking because we released yesterday version 3.2 that had a fix for that problem. :)

**Comment by pixelrevision** [comment]
Oh awesome.  Will grab the latest.
