### ISSUE TITLE
Application usage report

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#359]
hi all,
is there any way to get a report for:
-how many times the app clicked
-which pages user spent more time,
-which multimedia elements (video or audio) viewed
- which hyperlinks(in the app) clicked 
  -etc.....

do you use any tool, how did you manage to get the reports.
thanks

**Comment by folletto** [comment]
I think you should have a look at Issue #332 regarding Analytics. :)
It's not there yet. :)

**Comment by bahmet** [comment]
sorry after i post this i saw that issue
thanks...
