### ISSUE TITLE
mailto: links crash the app

### ISSUE THREAD

**Issue by andreacampi** [Simbul/baker#36]
See https://github.com/Simbul/baker/commit/61e471a8e2e3605291587e81d6f528e78d171e02#commitcomment-233772

**Comment by Xm4s** [comment]
Thanks for finding this bug :)
Fixed with the commit https://github.com/Simbul/baker/commit/b8a6d2e3a28d12e4842c214489400cfced893125
I'll wait for a positive feedback on the fix before closing this up.

**Comment by andreacampi** [comment]
Doesn't crash anymore, thanks :)

**Comment by Xm4s** [comment]
Thank you for discovering and pointing out the bug :D
