### ISSUE TITLE
Numbering in Screenshots - can they be set to start anywhere?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#361]
I just noticed the numbers that baker displays in the loading screenshots start from one. Can I custom number them somehow? For instance, have no number on the first three pages and then have numbers on the next 6 (starting at 1) and then no numbers on the last three pages. 

This isn't a feature request, just wondering if it can be done, otherwise I will take out the numbers.

**Comment by folletto** [comment]
It's not a feature available out of the box, but I can point out that the code generating it is within the function `- (void)initPageDetails` and as such you might perform some editing there and achieve your need. :)

Another way would be to pre-generate the screenshots and use these. :)

**Comment by tstegart** [comment]
Thanks. Can they be deleted if we don't want them? I can see where to change the color in book.json (which I could just change to match the background color if I want them invisible), but where can I delete them?

**Comment by folletto** [comment]
Yes, the way to do that right now is by using the alpha setting. :)

You can play with the code in that same function if you want to do extra things. :)

**Comment by tstegart** [comment]
Thanks!

**Comment by tstegart** [comment]
Sorry to reopen this, but is there a way to not show the page number but still show the page title? When I make the numbers invisible by changing their color to the background color the titles also disappear. I can't find a place to change just the numbers color.

**Comment by folletto** [comment]
Not out of the box, you need to do some work in the function I told you about above :)

**Comment by tstegart** [comment]
Ok, thanks :)

**Comment by thejtate** [comment]
@folletto Thanks for the Alpha feature, very handy! 

This might sound like a dumb question, but where is the <code>\- (void)initPageDetails</code> function at? I was digging around in ui/PageTitleLabel.h and .m and didn't see it. Figure that just loads the title itself but not the page numbers. 

Edit: Just discovered I can do a search using cmd+shift+O. Nice little feature.

**Comment by folletto** [comment]
Unfortunately this is a old thread and refers to an obsolete version of Baker. I'm sorry.

**Comment by thejtate** [comment]
Still pretty new to Obj-C, but where is the new location the page numbers are printed out?

**Comment by Simbul** [comment]
Most of that is done in the `buildPageDetails` function, inside `BakerViewController.m`.

**Comment by thejtate** [comment]
@Simbul Thanks for the heads up. Seriously appreciate all the work you guys have done with Baker.
