### ISSUE TITLE
Webkit bug in safari - will it affect Baker?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#362]
I noticed this blog post about how webkit scales down JPEG images if they are too large.
http://duncandavidson.com/blog/2012/03/webkit_retina_bug

Since Baker uses webkit, I assume a full screen retina image will also be affected. Do you agree?

**Comment by folletto** [comment]
Yes. We are completely dependant on Apple, since it's the same browser engine. :)

**Comment by tstegart** [comment]
Thanks for the quick response guys! As a note, I've read a few other blogs and most people seem to think this will get fixed soon. For now, can I just break up my images and put them back together again using CSS? Its sounds like that should work as the bug is with individual image sizes.

**Comment by folletto** [comment]
Yes, from what I've seen that should work. If you can, also PNG have an higher limit. :)

**Comment by folletto** [comment]
It seems there's already a workaround: http://duncandavidson.com/blog/2012/03/photography_on_retina :)

_After reverse engineering the limits and then later being pointed to the documentation about the limits, a birdie dropped a hint into my inbox telling me to try using a progressive JPEG file. Within just a few minutes, several people also chimed in noticing that the large iPad hero image is a progressive JPEG. I’ve not used progressive JPEGs in years, but following the lead of the birdie and the crowd, I gave it a shot. Lo and behold, it’s indeed the ticket to large JPEG joy on the iPad Retina display._

**Comment by tstegart** [comment]
Awesome. Thanks.
T
