### ISSUE TITLE
Double Click Status Bar is not showing

### ISSUE THREAD

**Issue by altecdell** [Simbul/baker#363]
I am trying the fresh untouch sample files. 
After I double click, i can only see a tiny bit of status bar , as shown in this screenshot.
http://vvcap.net/db/038TAEobXhqZDiJDOSjL.png
Everything else is working perfectly...
Anyone know whats the problem?
I remember seeing it.. but i cant see it now..
I didnt touch book.json
thanks!!

**Comment by folletto** [comment]
You should be able to find an answer in the wiki from the menu on top. :)
https://github.com/Simbul/baker/wiki/Adding-an-Index-Bar-to-your-publication

**Comment by altecdell** [comment]
Indeed, i missed the wiki...
Appreciate your reply! 
Found the solution!

**Comment by folletto** [comment]
Great ;)
