### ISSUE TITLE
How to load new pages for orientation changes

### ISSUE THREAD

**Issue by mbayona** [Simbul/baker#366]
I have the situation when a different page (different dimensions for images) needs to be accessed with orientation changes.  I would like to take advantage of the wider length while in landscape mode.  I know that this is probably accomplished with CSS, but I guess I need a bit of guidance.  I guess I have two main questions:  
1.  The way it works now: when the iPad changes orientation to landscape, the page appears left justified, with some blank space to the right.  At the bare minimum I'd like to have this page be centered...
2.  Better yet, I'd like to load a page with with larger image that will take the whole width now available.

Thanks for any help.

**Comment by manyakabi** [comment]
Hi, wondering this question me too.

And I want to add something; we want to show double html5 pages (left, right) on horizontal orientation mode. However, it should show one page (left page) on portrait orientation. Can we make this, or is there any chance to do this with Baker Framework?

**Comment by folletto** [comment]
@mbayona you are right, you should be able to do that just by using CSS and media queries. This is one of the best sources and more advanced ones that you could find: http://www.alistapart.com/articles/responsive-web-design/

@manyakabi unfortunately that's not possible with Baker. A page in Baker is a page, exactly like on a book or on the web.

**Comment by anjimi** [comment]
@manyakabi the 'double page spread' effect could be achieved if you make your pages so you have left and right page in one html file and use css media queries to make both 'sides' of the page fit on horizontal orientation and scroll across left-to-right on portrait orientation.

**Comment by manyakabi** [comment]
Oh that's information is great!
Thank you @anjimi. I'm going to develop with Baker Framework.
