### ISSUE TITLE
Problem occurs when swipe pages

### ISSUE THREAD

**Issue by sengkit** [Simbul/baker#367]
Hi,

Great job everyone to make Baker better and better and I am excited to get my first ebook developed with Baker 3.2 completed very soon. However my ebook isn't perfect because I had encountered a problem which I need your help to solve it. I realised that when I try to do the left-swipe between pages, the swipe is stucked and you will see a vertical gap between the pages, which looks like the screenshot i attached below:

http://www.flickr.com/photos/seng_kit/6882821856/

No problem with the right swipe, it works perfectly, only the left. FYI, the rendering mode i am using is "three-cards", and some of my pages do have photo slideshow and videos. 

Hope someone can help, thanks very much.

**Comment by bahmet** [comment]
hi ,
i think it is the rendering issue. i have the same on one of the pages of my application. that page has 6 slide shows with approx.30 images.
can someone share their experience when choosing the right rendering mode...
thanks

**Comment by sengkit** [comment]
Hi Bahmet, I also suspect the rendering issue, but somehow both rendering method didn't solve my problem. so how do you solve your case?

**Comment by bahmet** [comment]
@sengkit  
İ resized my images :(

**Comment by sengkit** [comment]
@bahmet  oh my... u mean the dimension or the file sizes? does it affect the picture quality? :(

**Comment by bahmet** [comment]
@sengkit 
hi , i resize the dimensions and also resized the slideshow specifications to not to affect picture quality.

**Comment by sengkit** [comment]
Thanks @bahmet for the reply. I wish there is ways to solve this issue without altering the layout design. I guess we need avoid too much slideshow idea until we have solution to overcome this.

**Comment by sengkit** [comment]
Hi @folletto @Xm4s, any idea? :(

**Comment by Xm4s** [comment]
Hi Sengkit!

Well, without seeing the actual pages its kinda hard to tell what the problem may be :)
I suspect that the slideshow is somehow altering the page width ... but it's really just a guess. 

My advice it's to:

• try to remove the slideshow completely and check to see if the problems on swipe is solved. 
• try to implement the slideshow with different js libraries, to see if the problems are related to a specific implementation.
• try to add to the slideshow one image at a time, to see if and when the problem arise.

One last thing: if you could provide us a sample book with five sample pages, two of them with the "swipe-to-gap" problem, we could try to track the problem down.

**Comment by sengkit** [comment]
Hi @Xm4s thanks for your advice. I tried your steps to check which part of my code cause the problem, and i realised that it's not the problem of slideshow at all, just a very small little css mistake which cause the big problem, what a shame. The book looks perfect now! Hope I can share with you guys once it's up at Apps store very soon. ^^

**Comment by sengkit** [comment]
and thanks to @bahmet too, this time is not the rendering issue. The "three-cards" rendering mode just work perfectly for my heavy slideshow, so I didn't alter any sizes or specs this time. just a very small CSS mistakes which cause the big issue, what a joke. ><"

**Comment by Xm4s** [comment]
I'm glad you solved the problem, hope to see your book on the app store anytime soon :)
