### ISSUE TITLE
add search capability to ebook

### ISSUE THREAD

**Issue by jnan** [Simbul/baker#369]
hi 

i use baker framework for my html book but i want to add search  to the book  but because it is html book i have no idea how to do that.

if there are a source  benefit for me  can you provide it to me

**Comment by Bobramyl** [comment]
Am currently working on full-book search, will post code as soon as it's finished (proly week or so). I do recommend you to create NSArray with all strings as contents of pages (create scanner and process all files), then search them using any search function you want (substring is useful here). If you have page numbers with occurances, you can highlight words you want by using javascript. Profit. Or wait :)

**Comment by folletto** [comment]
Hi :)
That feature is tracked by Issue #61, so please follow that one to be updated. :)

@Bobramyl that's great, we'll wait for your pull request ;)
