### ISSUE TITLE
How do we update Baker?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#371]
How do we update Baker if we're in the middle of making our app? Do we just drag the new files into the Baker folder? What if we've modified the files in Xcode, is there any way to keep our changes?

**Comment by bahmet** [comment]
if you are modifying the book folder, just download the new version and copy book folder to new version.
if you are modifying the baker files, download the new version, read the changelog in the code page whether any impact to your modification or not. then replace your modified files with the downloaded ones.....

**Comment by tstegart** [comment]
Ah, ok, thanks.
