### ISSUE TITLE
Is there any reason why I can't pick a launch image in Xcode?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#373]
I can't seem to specify a launch image in Xcode for Baker, the options are grayed out. I used to be able to control click on the missing image icon and choose a default image, but that is grayed out too. Do you think this is a Baker problem or an Xcode problem? I can still specify launch images for earlier versions on my App that use Baker, just not the current version. I can't specify launch images for the retina display or app icons either, everything is grayed out. 

I can't find anything online about this yet, but I'll keep looking. Let me know if you guys have the same problem.

**Comment by tstegart** [comment]
This is an Xcode bug, so I've closed the issue. You have to control-click on the very tiny outside part of the missing icon image, outside the dotted line. Clicking inside the dotted line does nothing. Very silly.

**Comment by kaolin** [comment]
Brilliant! Thanks for this solution =)

**Comment by torsod** [comment]
Wow, spent three hours on that...

**Comment by jcsahnwaldt** [comment]
Thanks! I was getting frustrated.
