### ISSUE TITLE
New magazine "Universo Relógio" available in apple store, based on baker framework

### ISSUE THREAD

**Issue by Oliveirakun** [Simbul/baker#374]
Hi Friends!!
   I would like to announce the release of "Universo Relógio" magazine, available in apple store. Universo Relógio is a Brazilian magazine for "watch lovers" or simply for people who like watches and want to know the news about releases and reviews of watches available in the market. Our magazine is based on baker framework with some changes to support the shelf and full newsstand integration. We also would like to congratulate the baker team for this awesome work!
  If you wanna know, this is the link to our magazine page in apple store:

  http://itunes.apple.com/br/app/universo-relogio/id505818117?mt=8

  It's totally free!

Best Regards,
Francis

**Comment by tstegart** [comment]
Congratulations! Maybe you can talk to the Baker guys about how you implemented newsstand. Its on the list.

**Comment by Oliveirakun** [comment]
Thank you! I'm little busy now, but I intend to contribute to the project as soon as possible, helping the Baker guys with newsstand integration or other functionality.

**Comment by mbayona** [comment]
Francis,

Great job!  It would really be great if you could share those changes to support the shelf and newsstand integration.  Your magazine looks very nice!

Regards,

Miguel

**Comment by sabgottfriedx** [comment]
Hi Francis, 

I just reviewed your magazine and it looks very good and work super well. Congrats!

I d have a question - I found that the swiping performance on oyur mag also seems much smoother than on any other publication made with baker that I downloaded and tested. Did you make any changes to the usual settings and what type of caching mode did you use. All the others have super long loading times and that spinning wheel when I swipe to a new page. One that is working better is a bit jumpy. But with your mag thats not at all the case. 

Would be awesome to hear back from you. 

Sabine

**Comment by Oliveirakun** [comment]
Hi Sabine,

   Thank's for your comment, I really get happy to hear the feedback from our users or other developers,
even more when it's positive ;). We didn't make any change regarding the swiping, and we used the three-cards mode for cache. Maybe the magazines you've downloaded are using an old version of baker, that's I think...

Best Regards,
Francis

**Comment by folletto** [comment]
@Versioncrowd  Yes, I can confirm that Baker did quite big progress from one version to another, and not every publication worked on that - well, not even our own, I have to admit. :)
We should probably start tagging the page with the specific Baker version, we'll look into that. :)

Huge compliments again to @Oliveirakun :)

**Comment by moushik** [comment]
Francis,

great publication! I hope you could share with us the newsstand integration!

bye

**Comment by folletto** [comment]
We (finally) had time to update the show case, and you've been added. :)
http://bakerframework.com/books

:)

**Comment by Oliveirakun** [comment]
@folletto, thank you very much for add my magazine to baker show case!
