### ISSUE TITLE
Navigation - Index.html (request)

### ISSUE THREAD

**Issue by mbayona** [Simbul/baker#376]
I am sure it is possible to achieve the following:  After double tapping the screen, I'd like the main index to appear at the bottom of the page (as it does) but with the current page highlighted (the current image maybe framed) or some other way to give the user a good idea of where he/she is coming from...This is possibly already there.  I know it would require tinkering with the js.  Any ideas about how to accomplish this?

**Comment by tstegart** [comment]
I don't think this is possible just yet with just javascript. Maybe someone can correct me if I'm wrong. See https://github.com/Simbul/baker/issues/350

**Comment by folletto** [comment]
Yes, correct. That's the issue we are using to track this feature. Follow that one please ;)
