### ISSUE TITLE
Contents loads in Index View---

### ISSUE THREAD

**Issue by mbayona** [Simbul/baker#377]
I just followed a very similar issue.  It seems this has been dealt with before, but after following the comments and viewing the code (I have the latest Baker, with the "fixes"in place), it still DOES NOT WORK!...please help!

**Comment by Simbul** [comment]
I guess you are referring to issue #335.

Can you add some more details? (I know you added some to the other issue, but it would help to have more and to have them in this issue).

Some useful details to start with:
Do you have the latest released version (3.2) or the latest development version (master branch)?
Is it happening an all the links or just some of them? Is it happening when you click two links at the same time? That was the trigger with issue #335.

**Comment by Simbul** [comment]
Hello @mbayona, I'm closing the issue as there are no new developments for it.
Please feel free to reopen if you have more details.
