### ISSUE TITLE
Play music continously

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#378]
hi,
i know its a silly question but i am totally lost.
i would like to include a music file in my app which starts from the cover page and fade outs on the 4th page. i used jplayer in my previous app to play sound on demand ( on click).
i really appreciate if you can describe me how to do that.....
thanks

**Comment by mutador** [comment]
i try this.... but i can do...i try to put a player in the index.html  but not works fine....
i think a videoplayer or playlist of music always selectec in the top of baker when you make double tap it will be god.
and another implementations in the top will be apreciated like, go to cover a suscriber page, etc...

sorry i am not the solution for you

**Comment by folletto** [comment]
Did you find a solution for this? Should we add this as a feature request? :)

**Comment by mutador** [comment]
hi folleto, we are developed our baker, called paper easy. You have a great work, but don´t have time for make all the things that i say..
we changes a lot of things, developed from 0. a predict system of navigation, don´t screen shots, only threcars mode...etc
one of them is a player music always present in the uiweb - we are developed a doble tap whit a navbar whit funcionalitys, in top, menu,player music, suscriptions,credits....
we try developer whit divs in the same index.html

i have a lot ideas for publicity, and make something special for comercial magaznes..i see baker for special books, kids, etc...

in a couple of weeks, we have a papereasy 1.1 for show

**Comment by mutador** [comment]
the solution is don´t unload the index.html when is hidden, and so you can put a lot of things in the ondex.html whit tabs...a playlist , suscription forms, diferent ways to see the index..etc 

i expalin well?

but, if you have a index.html always visible  the transitions betwen pages is  little slow...

**Comment by bahmet** [comment]
hi,
@folletto that would be great feature in Baker.
thanks

**Comment by mutador** [comment]
http://itunes.apple.com/us/app/ohmygod-es-02/id499892763?l=es&ls=1&mt=8
see the solution in this aplication
is not baker, but is a inspiration for baker developers if they want
