### ISSUE TITLE
Transfer on iPad

### ISSUE THREAD

**Issue by fxzone** [Simbul/baker#379]
Hello! 
How I can transfer my publication on my iPad outside of the library(iBooks) (as another application).

Thank you!

**Comment by folletto** [comment]
Could you try to describe a little better what are you trying to do? :)

**Comment by fxzone** [comment]
Hello! Sorry to have taken time to answer you.
What I would like to make is to have an icon outside of the library (ibooks) as an application.
Is it possible?

Thank you!

**Comment by folletto** [comment]
That's exactly what Baker does if you build a book with it. :)
Check the showcase: http://bakerframework.com/books :)

**Comment by fxzone** [comment]
Thank you! For the information.
I do not for the moment want to sell my book on iTunes.
I want to install it on my iPad only for a use in kiosk mode in an aluminum case.
I am going to make some tests.
Thank you! For your indications.
