### ISSUE TITLE
Request: Change position of index view

### ISSUE THREAD

**Issue by nurtext** [Simbul/baker#384]
Is it possible to change the screen position of the index view based on a property set in book.json? For example have the index view not at the bottom of the screen, but at top or even at the left/right side of the screen?

**Comment by steiny2k** [comment]
Well, if I'm reading this right in https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters i think it should at least be possible to have the index view either on the bottom or the left side.

However it will always slide in from below...

**Comment by Simbul** [comment]
It is indeed possible to have the index view on the left side. In that case, it will slide from the left, not from below.

At the moment it is not possible to have the index view on top or on the right side: that would require rewriting a fair amount of code.

**Comment by nurtext** [comment]
Thanks @Simbul. Having a index view on top or on the right side would be cool. Maybe you could the issue into feature request for an upcoming version?

**Comment by lostinjapan** [comment]
@Simbul You said it is possible to have the index view on the left side. How or where should we change the code to allow this?

**Comment by Simbul** [comment]
It should be as easy as creating an `index.html` page that is only as wide as you want the index bar to be and it scrolls vertically.

If you're only supporting one orientation, you can also force the size of the index bar by setting `-baker-index-width` inside `book.json` (see https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters)

**Comment by folletto** [comment]
I'm closing this one since there are no follow-ups. Reopen at need. :)
