### ISSUE TITLE
Opening an internal (non-book page) within a modal window?

### ISSUE THREAD

**Issue by coxmi** [Simbul/baker#385]
Currently, adding "?referrer=Baker" to the end of an internal/local (non-book page) link does not open that page in a modal window as it defaults to overwriting the current page. 

It seems strange to limit the modal window functionality only to external pages, when it can be a very useful interface element for a local operation.

Is there an easy way to implement this, editing the Webview section if else statements in RootViewController.m?

**Comment by folletto** [comment]
If you need something local, you can just open a div over the current page with an iframe in it. Looks simpler to me, and without the overhead of an additional WebView. :)

But if you really think it's better, the best place to start looking is probably within `- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType`. :)

**Comment by coxmi** [comment]
I'm trying to implement this in many places throughout the book, so having it as a referrer query makes the markup simpler and without any additional scripting so it runs a little quicker/slicker than a javascript animation/iframe implementation. I'm thinking it's always better to use a native implementation rather than fudge a false one.

I'll take a look into this and report back if anybody else is interested in this. Thanks for the quick reply (and for baker itself!)

**Comment by coxmi** [comment]
Okay, that was easier than i thought!

in <pre>\- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType</pre>

Find:

<pre>
                if ([[url scheme] isEqualToString:@"file"])
                {
                    // ****** Handle: file://
                    NSLog(@"    Page is a link with scheme file:// --> load internal link");
                    
                    anchorFromURL  = [[url fragment] retain];
                    NSString *file = [[url relativePath] stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
                    
                    int page = [pages indexOfObject:file];
                    if (page == NSNotFound)
                    {
</pre>


within that if statement towards the bottom, delete what's in the last brackets and insert the following:

<pre>                        NSString *params = [url query];
                        NSLog(@"    Opening URL: %@", [url absoluteString]);
                        
                        if (params != nil)
                        {                        
                            NSRegularExpression *referrerExternalRegex = [NSRegularExpression regularExpressionWithPattern:URL_OPEN_EXTERNAL options:NSRegularExpressionCaseInsensitive error:NULL];
                            NSUInteger matches = [referrerExternalRegex numberOfMatchesInString:params options:0 range:NSMakeRange(0, [params length])];
                            
                            NSRegularExpression *referrerModalRegex = [NSRegularExpression regularExpressionWithPattern:URL_OPEN_MODALLY options:NSRegularExpressionCaseInsensitive error:NULL];
                            NSUInteger matchesModal = [referrerModalRegex numberOfMatchesInString:params options:0 range:NSMakeRange(0, [params length])];
                            
                            if (matches > 0) {
                                NSLog(@"    Link contain param \"%@\" --> open link in Safari", URL_OPEN_EXTERNAL);
                                
                                // Generate new URL without
                                // We are regexp-ing three things: the string alone, the string first with other content, the string with other content in any other position
                                NSRegularExpression *replacerRegexp = [NSRegularExpression regularExpressionWithPattern:[[NSString alloc] initWithFormat:@"\\?%@$|(?<=\\?)%@&?|()&?%@", URL_OPEN_EXTERNAL, URL_OPEN_EXTERNAL, URL_OPEN_EXTERNAL] options:NSRegularExpressionCaseInsensitive error:NULL];
                                NSString *oldURL = [url absoluteString];
                                NSLog(@"    replacement pattern: %@", [replacerRegexp pattern]);
                                NSString *newURL = [replacerRegexp stringByReplacingMatchesInString:oldURL options:0 range:NSMakeRange(0, [oldURL length]) withTemplate:@""];
                                
                                NSLog(@"    Opening with updated URL: %@", newURL);
                                [[UIApplication sharedApplication] openURL:[NSURL URLWithString:newURL]];
                                return NO;
                            } else if (matchesModal) {
                                NSLog(@"    Link contain param \"%@\" --> open link modally", URL_OPEN_MODALLY);
                                
                                // Generate new URL without
                                // We are regexp-ing three things: the string alone, the string first with other content, the string with other content in any other position
                                NSRegularExpression *replacerRegexp = [NSRegularExpression regularExpressionWithPattern:[[NSString alloc] initWithFormat:@"\\?%@$|(?<=\\?)%@&?|()&?%@", URL_OPEN_MODALLY, URL_OPEN_MODALLY, URL_OPEN_MODALLY] options:NSRegularExpressionCaseInsensitive error:NULL];
                                NSString *oldURL = [url absoluteString];
                                NSLog(@"    replacement pattern: %@", [replacerRegexp pattern]);
                                NSString *newURL = [replacerRegexp stringByReplacingMatchesInString:oldURL options:0 range:NSMakeRange(0, [oldURL length]) withTemplate:@""];
                                
                                NSLog(@"    Opening with updated URL: %@", newURL);
                                [self loadModalWebView:url];
                                return NO;
                            }
                        }
                        
                        NSLog(@"    Link doesn't contain param \"%@\" --> open link in page", URL_OPEN_EXTERNAL);
                        return YES;
                        </pre>

**Comment by coxmi** [comment]
Not the best way of doing it (by duplicating lines of code), but perhaps with a little rewriting or making it into a function, it might be good to put this in a future release?

**Comment by Simbul** [comment]
Glad to hear you managed to solve your issue!

As for including in a future release, I think this solution covers a very specific case, and it has some drawbacks that we would have to iron out (it makes it less clear from a UX perspective when opening internal vs. external pages, it needs some special handling for Safari).
All in all, I don't think this would be a good trade-off for the official release.

We'll keep the issue marked as Contribution, however, so other users in need of the same functionality can find it and apply your patch.

**Comment by coxmi** [comment]
You're right, that does make sense — I was looking at this from thinking baker is an application framework, rather than a publication framework. For a publication, there does need to be that distinction, but for an application, it's not a necessity.

Thanks for the help, and again, for Baker.
