### ISSUE TITLE
"Corrupt PNG File" error during App Store upload

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#386]
hi all,
i was trying to upload my last application to app store. i constantly receive error mail after i upload to itunesconnect.  saying that "Corrupt PNG File - The PNG icon file ios-icon-ipad.png appears to be corrupt."
after i did some googling i found that this is related to some png compress failure of xcode.
you can find detailed information here..
http://iazapps.wordpress.com/2012/03/16/corrupt-png-file-the-png-icon-file-icon2x-png-appears-to-be-corrupt/

**Comment by folletto** [comment]
An alternative way is to use the [Application Loader](https://itunesconnect.apple.com/docs/UsingApplicationLoader.pdf) that you can download from iTunesConnect :)

We'll keep this thread open for a while, hopefully Apple will fix that soon. ;)

**Comment by bahmet** [comment]
yes you are right ,
but i saw that after i disabled png compress on xcode, my ipa file size decreased.  i guess the problem is xcode png compression.
