### ISSUE TITLE
Index sizing problem

### ISSUE THREAD

**Issue by stemmo** [Simbul/baker#387]
Hi everyone,

I've been using Baker/Laker successfully for a year and have released several apps into the App Store without problem. Just made the transition to Baker 3.2, and I have struck a problem that has been giving me headaches for days.

The problem is that I can't get my index.html functioning as it used to under Laker. Rather than getting an index bar that is horizontally scrollable but vertically fixed at 200px and snapped into position, the container is throwing up what seems to be a full-size html page within the index container. My 41 chapters aren't fitting horizontally (they break at about 24, then you need to scroll down). There is also a lot of empty space under my content.

I've tried all of the solutions/workarounds here, including the height/width settings in book.json, and setting height/width as absolute figures in index.html's viewport settings. Neither works. I've also raked through CSS for possible overrides but can find nothing.

No matter what I've tried, I can't constrain the index container to the size I need (height: 200 width: 16810). Does anyone have any possible solutions or suggestions about where to look for one?

Steve

**Comment by stemmo** [comment]
Issue solved - it was indeed a CSS conflict/override. Just created a new (and separate) CSS for the index bar and all was good. Half expected to find a solution straight after posting here, but glad I have. Sorry to bother you!

Steve

**Comment by folletto** [comment]
No worries! :)
Thanks :D

**Comment by Bonet83** [comment]
I have the same problem with index... And i can´t find a solution. Can you post yor new CSS for index, please?
