### ISSUE TITLE
How to: App rejected due to App Store Review Guidelines 2.21

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#391]
hi ,
my app rejected  due to App Store Review Guidelines 2.21, which basically says books should be published under ibooksstore.
my app has 4 videos, image sliders. what should i do to pass the review. what should i add.
thanks

**Comment by stemmo** [comment]
This has been an issue for a while, even moreso since the release of iBooks Author. There are dozens of apps approved and released into the App Store each day that are nothing more than text books. Yet some (like yours) are rejected and steered towards the iBookstore. In many respects it comes down to individual reviewers at Apple, so you MIGHT have luck just cancelling the binary and starting again. But ideally, you need some kind of interactive content, like a game. quiz or social media connectivity. 

I think we're going to see this more and more with Baker-made apps.

**Comment by bahmet** [comment]
thanks @stemmo 
i applied to app review board. lets wait and see what will happen. also i have the  same app in Turkish waiting for review. if the english one rejected and the Turkish one published that will prove your idea about individual reviewers....

**Comment by Dreeke** [comment]
I have had the same problem with identical apps that differ only in textual content initially having one pass the review and one being rejected.

I got the second one accepted after having added videos and adding an online questionnaire.

**Comment by bahmet** [comment]
@dreeke online questionnaire is a good idea.
which one did you use?

**Comment by Dreeke** [comment]
We already had our own custom solution, so I simply linked to that and adapted the css to cater for mobile devices.

**Comment by bahmet** [comment]
@stemmo Turkish version of my app is approved and published on app store. :)))
http://itunes.apple.com/us/app/turk-ebru-sanat/id518569396?mt=8&ign-mpt=uo%3D2

**Comment by stemmo** [comment]
Nice. Kind of proves what I suggested - that book app approvals come down to individual reviewers. 
Congrats on the release of your app. Unfortunately I can't speak Turkish, but it looks nice.

**Comment by Simbul** [comment]
Congrats on publishing your app!
Unfortunately the Apple Store approval process has always been pretty random. There's not much we can do on that front.

**Comment by ghost** [comment]
I am currently working on a template to integrate Unity3D with the baker framework. I'll be blogging about it in a week or so for anyone interested. It might help jump the hurdle of the app approval process for those looking to add that level of content.

**Comment by folletto** [comment]
@jmkevan That looks impressive, thanks in advance for the contribution. Can't wait to read it. :)

**Comment by folletto** [comment]
@jmkevan Do you have any news? I'm very interested in the integration you were talking about. :D

**Comment by ghost** [comment]
@folletto Thanks for asking! I was a little distracted by finals, but it's almost done. I'll post it on Monday :-)

**Comment by bahmet** [comment]
hi,
apple contacted me and explained that, since they do not have Turkish ibook store they allow turkish version of my app. 
just FYI....

**Comment by bahmet** [comment]
@jmkevan did you make the template for unity 3D
