### ISSUE TITLE
Getting crash reports from ipad1 users

### ISSUE THREAD

**Issue by joshbaltzell** [Simbul/baker#392]
We submitted an app that is very stable on the iPad2s and new iPads that we have tested in so far, but we had two report of stability issues in the app store. I chased one down and it us current o. IOS, but is an iPad1.

Is there anything I have to consider when making a baker app for the original iPad? Memory issues?

The app is Shriners International in the app store.

**Comment by folletto** [comment]
What Baker version are you using, and what rendering mode? :)

**Comment by joshbaltzell** [comment]
3.1 in screen shot mode. my app has a lot of video if that matters.
On Apr 18, 2012 9:25 AM, "Davide Casali" <
reply@reply.github.com>
wrote:

**Comment by joshbaltzell** [comment]
I got my hands on an iPad1. It does indeed crash on load. Here is what I see on the console. Any ideas?

---

Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -I-N-I-T
Apr 19 09:55:07 unknown Shriners[7800] <Warning>:     Device Width: 768.000000
Apr 19 09:55:07 unknown Shriners[7800] <Warning>:     Device Height: 1024.000000
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -S-e-t -s-i-z-e -f-o-r -o-r-i-e-n-t-a-t-i-o-n-: -p-o-r-t-r-a-i-t
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -H-i-d-e -s-t-a-t-u-s -b-a-r 
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: Set IndexView size to 768x1024, with pageY set to 0
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: Reloading index from bundle
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: Path to index view is /var/mobile/Applications/85DC8146-39D7-450E-8012-C58C81F4492E/Shriners.app/book/index.html
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -I-n-i-t -B-o-o-k
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: available orientation: portrait
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: rendering type: screenshots
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -R-e-s-e-t -p-a-g-e -d-e-t-a-i-l-s -a-r-r-a-y -a-n-d -e-m-p-t-y -s-c-r-e-e-n-s-h-o-t -d-i-r-e-c-t-o-r-y
Apr 19 09:55:07 unknown kernel[0] <Debug>: launchd[7800] Builtin profile: container (sandbox)
Apr 19 09:55:07 unknown kernel[0] <Debug>: launchd[7800] Container: /private/var/mobile/Applications/85DC8146-39D7-450E-8012-C58C81F4492E [69](sandbox)
Apr 19 09:55:07 unknown Shriners[7800] <Warning>:     Pages in this book: 42
Apr 19 09:55:07 unknown Shriners[7800] <Warning>:     Starting page: 1
Apr 19 09:55:07 unknown Shriners[7800] <Warning>: • -I-n-i-t -p-a-g-e -d-e-t-a-i-l-s -f-o-r -t-h-e -b-o-o-k -p-a-g-e-s
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -R-e-s-e-t -s-c-r-o-l-l-v-i-e-w -s-u-b-v-i-e-w-s
Apr 19 09:55:08 unknown Shriners[7800] <Warning>:     Prevent page from changing until scrollview reset is finished
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -S-e-t -t-a-p-p-a-b-l-e -a-r-e-a -s-i-z-e
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -S-h-o-w -p-a-g-e -d-e-t-a-i-l-s -f-o-r -t-h-e -b-o-o-k -p-a-g-e-s
Apr 19 09:55:08 unknown Shriners[7800] <Warning>:     Unlock page changing
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -A-d-d -p-a-g-e -t-o -t-h-e -l-o-d-i-n-g -q-u-e-u-e
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -H-a-n-d-l-e -l-o-a-d-i-n-g -o-f -s-l-o-t -0 -w-i-t-h -p-a-g-e -1
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -S-e-t-u-p -n-e-w -p-a-g-e -f-o-r -l-o-a-d-i-n-g
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -S-e-t-u-p -w-e-b-V-i-e-w
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: • -L-o-a-d-i-n-g-: -b-o-o-k-/-C-o-v-e-r-.-h-t-m-l
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: Reloading index from bundle
Apr 19 09:55:08 unknown Shriners[7800] <Warning>: Path to index view is /var/mobile/Applications/85DC8146-39D7-450E-8012-C58C81F4492E/Shriners.app/book/index.html
Apr 19 09:55:11 unknown MobileMail[7790] <Warning>: Received memory warning.
Apr 19 09:55:11 unknown SpringBoard[51] <Warning>: Received memory warning.
Apr 19 09:55:11 unknown UserEventAgent[12] <Notice>: jetsam: kernel termination snapshot being created
Apr 19 09:55:11 unknown UserEventAgent[12] <Warning>: TRACE: <MBConnection: 0x18b1b0> connection interrupted
Apr 19 09:55:11 unknown UserEventAgent[12] <Warning>: DEBUG: <MBConnection: 0x18b1b0> disconnected
Apr 19 09:55:11 unknown UserEventAgent[12] <Warning>: TRACE: Canceling <MBConnection: 0x18b1b0>
Apr 19 09:55:11 unknown UserEventAgent[12] <Warning>: TRACE: <MBConnection: 0x18b1b0> connection invalid
Apr 19 09:55:11 unknown com.apple.launchd[1] <Notice>: (UIKitApplication:com.apple.mobilemail[0x4448]) Exited: Killed: 9
Apr 19 09:55:11 unknown com.apple.launchd[1] <Notice>: (com.apple.backupd) Exited: Killed: 9
Apr 19 09:55:11 unknown com.apple.launchd[1] <Notice>: (UIKitApplication:com.shrinersinternational.Shriners[0x849]) Exited: Killed: 9
Apr 19 09:55:11 unknown SpringBoard[51] <Warning>: Application 'Shriners' exited abnormally with signal 9: Killed: 9
Apr 19 09:55:12 unknown SpringBoard[51] <Warning>: Application 'Mail' exited abnormally with signal 9: Killed: 9
Apr 19 09:55:12 unknown kernel[0] <Debug>: launchd[7802] Builtin profile: MobileMail (sandbox)
Apr 19 09:55:13 unknown ReportCrash[7801] <Error>: libMobileGestalt computeUniqueDeviceID: total time for bb to return imei: 0
Apr 19 09:55:13 unknown ReportCrash[7801] <Notice>: Saved crashreport to /Library/Logs/CrashReporter/LowMemory-2012-04-19-095513.plist using uid: 0 gid: 0, synthetic_euid: 0 egid: 0

**Comment by joshbaltzell** [comment]
Upgrade to the latest build fixed it for me. Sorry guys, I should have just done that before posting anything.

**Comment by Simbul** [comment]
No worries. Glad to know it's ok now ;)
