### ISSUE TITLE
Wow Slide Show

### ISSUE THREAD

**Issue by mbayona** [Simbul/baker#393]
Has anyone tried to use these slide shows with the Baker Framework?  I need to implement some slide shows, and WOW seems to be really nice.  I know I need to try it out and see if it works, but I thought I'd ask...

See:

http://wowslider.com/

Miguel

**Comment by folletto** [comment]
Hi Miguel, I'm sorry that you didn't receive any feedback on this, probably nobody used that yet.

However, checking their documentation they say: "Support for swipe touch events for iPhone / iPad / Android" and as such, it should work without problems in Baker. :)

Let us know if you did any test. :)

**Comment by mbayona** [comment]
Hi Davide,

I have been doing some other work as well and I have not yet try this myself.  I will and will post my findings...thanks for your reply.

M. Bayona
