### ISSUE TITLE
two separate page contents at the same app

### ISSUE THREAD

**Issue by rengen** [Simbul/baker#396]
Hello everyone.
I use Florians framework with Simbul/Baker and my question is this.
Is there a possibility to have 2 content menus? 
For example, When you double tap between pages 1 to 10 have content for these pages and when you double tap from page 10 to 20 to have the second content menu.
Is that possible.

thank you

**Comment by Simbul** [comment]
It is not possible with the current code.

We have a feature, slated for release 4.1, that concerns communicating the current page to the index bar (see issue #350). That solution could be conceivably adapted to your needs.

You could of corse implement it yourself, if you wanted to. Unfortunately it's not planned for the near future.

**Comment by rengen** [comment]
thank you for your answer. I will try with the index bar in order to have different languages in the same app.
