### ISSUE TITLE
Local book vs remote (downloaded from web)

### ISSUE THREAD

**Issue by olowek** [Simbul/baker#399]
Please clarify what should be changed to the settings for an application framework based on the Baker collected the contents of the HTTP server, such as for example: Universo Relogio. I do not understand a little different as far as if locally in the "book" is the content of all of this is understandable to me. The other hand, I would like to test the download release of the web server.

**Comment by folletto** [comment]
From what I understand you are trying to build a Shelf, please check Issue #20: it's in our plan, but it's not there yet. :)

If you want to, you might try to ask directly the author of Universo Relogio, that did an independent development, here: #374.

On the other side, to download directly a book from another book just use the `book://` protocol, on our Wiki: https://github.com/Simbul/baker/wiki/Book-protocol
