### ISSUE TITLE
Best way to see Youtube video on a modal windows

### ISSUE THREAD

**Issue by xiripi** [Simbul/baker#400]
Hi. What's the best way to see youtube videos on a modal windows with close bottom?

thanks

**Comment by zenz** [comment]
you mean full screen for video?

add following in your page which contain video.

<pre>
&lt;script type="text/javascript"&gt;
        var vid;
        
        function init() {
            vid = document.getElementById("myVideo");
            vid.addEventListener("loadedmetadata", addFullscreenButton, false);
        }
        
        function addFullscreenButton(){
            goFullscreen();
        }
        
        function goFullscreen() {
            vid.webkitEnterFullscreen();
        }
 &lt;/script&gt;</pre>


load it in body tag, like &lt;body onload="init();"&gt;

and add id="myVideo" to your video.

That's all.

**Comment by kilop** [comment]
Hi. How to call the video?

**Comment by zenz** [comment]
in this case, just tap on the video, it will bring the video to full screen and than play. that's all.

**Comment by Simbul** [comment]
I am assuming this is solved :)

**Comment by gmli-eu** [comment]
@zenz do you know to re-use that code in order to display 3 videos in fullscreen?

**Comment by folletto** [comment]
Hello!

Baker has moved! You can find the new issue board here:
https://github.com/BakerFramework/baker/issues

Please post there on a new issue to ask for support. :)
