### ISSUE TITLE
iPad to iphone

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#401]
hi ,
i have an application prepared with laker and baker. it works well on ipad, however when on iphone everything goes to wrong place. it looks like it needs resizing. 
is there a simple resizing option to resize for iphone to be used on @media queries  mediacan you guys advice how can i do that.
thanks

**Comment by folletto** [comment]
You should create a different layout and serve it with a different media query when you are on an iPhone screen. That's the best way to do it. :)

**Comment by bahmet** [comment]
Hi
 is there any layout specifications for iphone

**Comment by folletto** [comment]
What do you mean by that? That has a screen size, so you just tailor the page for that. No? :)

**Comment by bahmet** [comment]
Ok i got it and realised how dumb my question was. i will try media query. İts going to be my first time. Cross your fingers
Thanks
