### ISSUE TITLE
Baker Ebook Framework's logo

### ISSUE THREAD

**Issue by Zlyuk** [Simbul/baker#402]
When I making my app I wasn't sure that apple developers team will aprove it. So, i glad to say that I was wrong. Now you can find it there:

http://itunes.apple.com/us/app/zoryana-kazka/id519277179

I just wondering if it possible to put The Baker Ebook Framework's logo to our app's web-site and tell everyone, that these guys are and their job are so great? So, I look for the guidelines how to use your logo?

**Comment by folletto** [comment]
That's awesome! :)

Thanks for asking the use of the logo. You can use the badge image included in the sample book if it fits your needs, or the logo you find on the homepage to promote the framework you used in the book. :)

We should write some guidelines, you're right. :)

**Comment by Zlyuk** [comment]
Done!
http://www.zoryan.com/ipad/ipad.html

**Comment by folletto** [comment]
Awesome! 
Thanks. :)

**Comment by Zlyuk** [comment]
Hello, David!

Is it possible to publish info about my book Zoryana Kazka (which made by baker framework) on your project's web page?

**Comment by folletto** [comment]
Check the bottom of the Showcase page for the link to submit it. ;)
http://bakerframework.com/books
