### ISSUE TITLE
My compressed hpub in OSX error

### ISSUE THREAD

**Issue by rungsikorn** [Simbul/baker#403]
I use OSX 10.7 to compressed hpub to use downloadable book file

and I compressed content at root level but my baker still don't see any page

Do I miss something ?

I just a beginner

thx for advice

sry for bad eng

**Comment by folletto** [comment]
It's quite impossible to help you without any other information unfortunately.

Does it give any error?
What does it happen _exactly_?

**Comment by rungsikorn** [comment]
I try to download a example book from http://www.bakershelf.com/issues/

and Yes ! I change it extension ".zip" to ".hpub" upload to my site it work 

my app can open a new book

but when I compressed with my own It can't see any page of book 

I think it cause from how I compress files 

Could you please explain it by more details ? 

thx

**Comment by folletto** [comment]
Uhm there isn't much more detail than what's there in the tutorial: 
1. take a Hpub prepared folder (with all the files and the `book.json` file)
2. select all the files in your book director
3. right click and compress them

Without more information we can't help much. What does it happen when you click on the `book://` link? What message does it give you? What does the Debug Console say? Could you copy and paste here the Console output?

_Any_ detail is helpful.

**Comment by rungsikorn** [comment]
Oh I fix it !

because I didn't compress the book.json file

Thx very much : D

I know it was too silly problem but Thank you very much

for answer my question 

I 'm newbie for these 

thx for advice

**Comment by folletto** [comment]
You're welcome. :)
