### ISSUE TITLE
Blue Background behind app

### ISSUE THREAD

**Issue by charge-valtech** [Simbul/baker#404]
Hi there,

I've tried searching to see if anybody else has this problem, it's only a minor problem and perhaps it's unfixable...

When you swipe beyond the number of pages in the application, you can see a blue background, so if you swipe right on the last page and left on the first page...  Does anybody else have this problem?

Thanks in advance

Henry

**Comment by bahmet** [comment]
hi
change below line  in your json file ;)
`"-baker-background": "#000000",`

**Comment by charge-valtech** [comment]
Excellent! cheers
