### ISSUE TITLE
Quitting and starting app returns to same page

### ISSUE THREAD

**Issue by alexaffonso** [Simbul/baker#405]
I'm making some apps using Baker framework and I noticed a strange behavior that I don't know how to workaround:

Everytime I press the iPad home button to quit the app (leaving it in background) and then I click the App icon to open it again, it returns to the same page it was left. The same occurs even when I double click the iPad home button, close the app pressing the minus icon and then open it once again.

What am I doing wrong? Is there anything I have to setup that I haven't?

Thanks in advance.

Alex

**Comment by folletto** [comment]
It's a feature of Baker framework: it remembers the last point you were reading. :)

Why do you want to workaround that? :)

**Comment by alexaffonso** [comment]
The app I'm doing isn't actually a book. It's a portfolio and my client wants it to load from start every time it starts. Do you know if its a feature I can disable?

**Comment by folletto** [comment]
It's possible, but you have to do it by hand.
1. Find the function `- (void)initBook:(NSString *)path`
2. Inside there, around line 496, find the line like `NSString *currPageToLoad = [[NSUserDefaults standardUserDefaults] objectForKey:@"lastPageViewed"];`
3. Change it to: `NSString *currPageToLoad = nil;`

It should avoid the initialization of the stored variable on the first run. I didn't check it on running code, it might be slightly different, but it should be around there. :)

Let me know if this works for you. :)

**Comment by andersonchagas** [comment]
NSString *currPageToLoad = nil; works!

But when the app came from background it start from the last page viewed,
To workarround this just add a line in info.plist file:

Application does not run in background | YES

works for me.

**Comment by folletto** [comment]
Excellent! :D

**Comment by alexaffonso** [comment]
Great folletto. Thank you so much. It worked flawlessly. And the typo from andersonchagas worked too, though it's good to leave it in the background if the user doesn't quit it.

Thank you guys!
