### ISSUE TITLE
Modal View Crash If Page Not Fully Loaded

### ISSUE THREAD

**Issue by davidrsim** [Simbul/baker#406]
I've reproduced this on a couple of apps: 

Click on a link which goes to the modal view browser.
Click "back" before the page loads
The app then crashes. 

Anyone else getting this? 

Error is EXC_BAD_ACCESS (code=1, addres=0xf)
main.m line 37
int retVal = UIApplicationMain(argc, argv, @"UIApplication", @"BakerAppDelegate");

**Comment by folletto** [comment]
Thanks for the report, we'll check. :)

**Comment by andersonchagas** [comment]
Same on the simulator. Couldnt test on device yet.

**Comment by andersonchagas** [comment]
Saem behavior on iPad.

**Comment by rodrigors3012** [comment]
the device also get an error

**Comment by rodrigors3012** [comment]
news?

**Comment by rodrigors3012** [comment]
I'm just waiting for the resolution of this issue to launch my book in the apple store. If anyone can solve please advise.

**Comment by Xm4s** [comment]
Hi Rodrigors,

we acknowledge the bug and we've started looking for a solution.
I cannot give you a precise date for the fix, but as soon as we have one we'll push it on :)

**Comment by rodrigors3012** [comment]
I'm also trying to solve, if I can post here.

**Comment by Simbul** [comment]
Merging this thread with issue #422 by @rodrigors3012.

The gist of that issue is: you open a link in the modal view, close it before the content has loaded, and this causes the Baker application to crash.

**Comment by rodrigors3012** [comment]
any solution for this problem?

**Comment by Hamorabi** [comment]
I'm having this issue too. Given users can continue to browse within the model view, it is very likely that they will close the model view before the load is completed, hence, crashing the app frequently.

**Comment by folletto** [comment]
Hi, we are closing the refactoring of part of the code first, then we'll be back to this issue to fix it. I'm sorry for the delay but we really have to close that first refactoring first (you can see the releated issue and branch on github) so we have a better grounding to move forward. :)

**Comment by folletto** [comment]
It seems working now on MASTER, please test so we can close this issue. :)

**Comment by Simbul** [comment]
@davidrsim @rodrigors3012 @Hamorabi, has any of you had any chance to test the fix (i.e. download the current `master` and see if the problem has indeed gone away)?

**Comment by rodrigors3012** [comment]
I tested it, resolved.

**Comment by folletto** [comment]
Thanks! :D
