### ISSUE TITLE
how to demo and unlocked version

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#407]
hi all,
how can i publish demo application and then advice users to buy full version. do you have any examples in your applications. how did you do that.
thanks

**Comment by folletto** [comment]
You have to follow the standard Apple practices and either:
1. Develop In-App purchase
2. Create two applications, a Standard (pay) and a Lite (free) one.

However mind that Apple doesn't allow "demo" applications, the Lite version or the basic with In-App purchase must still be a satisfactory, complete experience, albeit shorter/smaller. :)

**Comment by bahmet** [comment]
but as far as i know In-App purchase is not available with baker, right?
in this case creating 2 applications is the best way. i can add a single page with a link to appstore page of the paid one, do you think apple accept that?
thanks

**Comment by folletto** [comment]
1. Nope, as I said you have to develop In-App purchase if you want to. :)
2. I think that Apple will accept it as long as the Lite application gives a complete experience (as in, the first book of a series, for example). But it's really hard to tell. :)
