### ISSUE TITLE
Padding between pages

### ISSUE THREAD

**Issue by andersonchagas** [Simbul/baker#409]
First of all, congrats for the amazing work..

Im wondering if is possible to make a padding between the pages of a book.
Something like the photos app.
You`ll understand when see that: www.motionbits.net/labs/bakerTest/page-spacing.png

Thanks.

**Comment by folletto** [comment]
Do you mean an invisible padding that's visible only when you're scrolling from one page to the other?

**Comment by andersonchagas** [comment]
Yes, exactly. Is possible?

**Comment by folletto** [comment]
Unfortunately no, it's not possible. I'm sorry.

**Comment by andersonchagas** [comment]
I found a way:

at rootViewController.m I add:

```
#define PADDING  10
```

```
- (void)setPageSize:(NSString *)orientation {
    NSLog(@"• Set size for orientation: %@", orientation);

    pageWidth = screenBounds.size.width + (2 * PADDING);

    pageHeight = screenBounds.size.height;
    if ([orientation isEqualToString:@"landscape"]) {
        pageWidth = screenBounds.size.height + (2 * PADDING);
        pageHeight = screenBounds.size.width;
    }

```

```
#pragma mark - SCROLLVIEW
- (CGRect)frameForPage:(int)page {
    return CGRectMake((pageWidth * (page - 1) )  - PADDING, 0, pageWidth, pageHeight);
}
```

The webview adjust to size of pageWidth, so I add same value as padding for body of pages:
In book.css

```
body{
padding: 0 10px;
}
```

---

It works fine, but when orientation changes, the left margin is visible. Simple drag correct.

Some idea to correct this?

Maybe this could have a flag "baker-page-spacing"?

**Comment by folletto** [comment]
That would be great. If you are able to make it work, we will gladly accept a Pull Request. :)
