### ISSUE TITLE
Lightbox imageviewer

### ISSUE THREAD

**Issue by snive** [Simbul/baker#41]
Hello everyone!
I've just started to playaround with the Baker framework and I love it
Has anyone used any lightbox effekt to show larger images in a baker book?

I think the regular problem will be the position of the image to show because the javascript in the page don't get the scrollHeight right after scrolling in the iPad

I will test some more and post if I found some working lightbox

/jesper

**Comment by folletto** [comment]
Thanks! :)

**Comment by snive** [comment]
Lightbox Imageviewer was easy to do with JQuery overlay effect

**Comment by folletto** [comment]
Excellent. Would you care to write a tutorial? Maybe link it here as well? :)

**Comment by MacBoy** [comment]
Hello snive,

Can you share the code that you used? Perhaps zip-up the "book" folder and let us download it.

Thank you, this is great achievement!  :-)

( If it is easier to share the zip, I've given you my email address in a private message -- please check your Inbox on GitHub )

**Comment by snive** [comment]
I'll try to make a tutorial on a blogg this weekend

**Comment by snive** [comment]
Check out my small tutorial about how to make a lightbox lookalike image shower:
http://blogg.cantalope.se/2011/01/lightbox-baker-ipadboo/

**Comment by folletto** [comment]
Ok, I'll close the issue. :)
