### ISSUE TITLE
better swipe functionality like iBook, possible?

### ISSUE THREAD

**Issue by rahuxx** [Simbul/baker#410]
Sorry if asking something wrong, but as you all know apple is such a company that likes everything to go perfect and same is for those who uses it.

I  have made book in both Baker - HTML 5 and iBook and find iBook has much smoother swipe and pinch functionality. That is why people loves ibooks made in iBook author more then made in other options.
So just want to know if it is possible to have swipe like iBook? like swipe left 2-3 pages at once.
Pinch and zoom embedded videos and images even if they are not active and gets active once we start pinching and zooming things.

I am newbie and just starting to work on both Baker and iBook so if there is something which is not relative to the feature I am asking just forgive me for it

**Comment by folletto** [comment]
Well, it's HTML, so everything you can do on HTML page is possible in Baker too. :)

As for the smoothness, try using the screenshot mode in Baker, it should be smoother. Unfortunately iBooks has an "easy" life since it's mostly just text, while doing the same in HTML is incredibly heavier - and as such, less smooth. :)

**Comment by steveRW** [comment]
Rahuxx is referring to iBooks2 made with iBooks Author.  It's full multimedia including videos, slide shows etc. I would also be interested to know if that level of smooth swiping could be achieved. And also whether the pinching in to thumbnail and pushing out to full screen like they have in iBooks 2 can be achieved with HTML and JavaScript.

**Comment by folletto** [comment]
Well... 
For the scrolling, just to give you and example, the App Store on the iPad is HTML, not native. Most of the people wouldn't be able to tell the difference in scrolling. :)
It's all a matter of effort. :)

About iBook... Books made with iBook Author are enhanced HTML, from a certain perspective it's like a narrowed down version of Baker with some extra hooks. I don't know if the pinch is made in HTML or Obj-C however.
