### ISSUE TITLE
Autogenerate index bar

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#411]
There should be a way to automatically generate the index bar if a custom one is not provided.
Some possible solutions:
- if screenshots are provided, use scaled-down versions of the screenshots to automatically generate an entry for each page
- if screenshots are not provided, use a property of the page (e.g. `title`) to generate a linked list

See http://www.mightymeta.co.uk/app-book-publishing-with-baker-and-pugpig/comment-page-1/#comment-1378 for reference.

**Comment by nin9creative** [comment]
It would be cool if it could generate a view like the Adobe DPS view...

![Index View](http://dl.dropbox.com/u/14238775/Baker/dps_index_view.png)

**Comment by folletto** [comment]
That was our first plan very early on, but we had to scrap it since it's incredibly heavy. Adobe gets around it since well... they basically use screenshots already.

We still haven't dismissed the ability to do it, it's just very challenging.

**Comment by JamesBrocklehurst** [comment]
Could looking at the PugPig source help? They do it by taking snapshots of each page. No idea how this is achieved, but the answers will be in the code...

Not sure I would want the Adobe approach. From a user experience perspective, you don't need to see thumbs of the whole page layout, just something that allows you to quickly recognise the page you want and jump to it.

**Comment by folletto** [comment]
The PugPig source helps but up to a certain point, because they have a very different codebase and structures. They use the screenshot they do to accelerate page rendering to build the index itself. We use the screenshots as well in screenshot mode, so on that side we are already covered.

The big difference is that PugPig then does that by using native controls, while our philosophy is about giving full control and let everything be in HTML5, so our code will have to generate HTML. :)

**Comment by benoitchantre** [comment]
I don't know what is possible or not, difficult or not, but if it's possible to compile a jade template when you build the app in xCode, it could be a solution to generate the index page in html.
The publisher could then enable/disable this function by providing or not the jade template.

**Comment by folletto** [comment]
I think that @benoitchantre hit the spot here. With the way we manage things, auto-generation should be done outside of the Baker framework itself, by the CMS or the publishing engine in general. 

I'm closing this issue. :)
