### ISSUE TITLE
fixed width does not work on iphone

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#413]
hi,
i have another weird problem in my project. i am making a color book for iphone. i am using https://github.com/williammalone/HTML5-Paint-Bucket-Tool . i already resized the canvas to fit my page. 300*300px.
below that canvas i have jplayer scripts to play 5 different audio. that also works fine.
i created a wrapper div. (width.320px)  to put 5 player divs(each width 60 px) in it. now the problem starts. wrapper wraps divs correctly on chrome, safari, however when i copy to baker there is a blank space on the right side of the screen on the simulator and device.
1. i disabled paint bucket script. nothing changed.
2. i deleted one of the player so 4 left in the wrapper, space size decreased but not completely gone.
3. i disabled jplayer. space gone
4. i deleted players (divs) space gone
i am not using @media tag in css. and checked that there is nothing to affect div sizes. 

most probably you have an idea to fix this. i would appreciate if you can help
thanks...

**Comment by folletto** [comment]
Hi! Let's see a couple of points that might help you:
1. Does it work on Mobile Safari?
2. Did you check the CSS used in the page (maybe adding `overflow: hidden`)?
3. Did you set a specific viewport meta size?

**Comment by bahmet** [comment]
@folletto have i told you lately that i love you :)))

"Did you check the CSS used in the page (maybe adding overflow: hidden)?" is the answer
thanks very much
