### ISSUE TITLE
image map hyperlinks to Safari

### ISSUE THREAD

**Issue by pterotype** [Simbul/baker#414]
Hi,

I'm working on a newsstand magazine app using Baker Framework. Due to the high design of the magazine, all of the html files in the app (generated by Baker) have only an <img src> tag to a .png file output from InDesign. I'm created an image map to link to Facebook, Twitter and my web site. All of the links open up a webUI browser within the newsstand app. I really want these links to open up in Safari on the iPad and iPhone.

How do I target the links to open up in the Safari app, rather than within a webUI view?

**Comment by pterotype** [comment]
<--Here is the simple markup:

<--html>
<--head>
    <--title>The Uninvited</title>
    <--meta name="viewport" content="width=768; initial-scale=1.0;"/>
    <l--ink rel="stylesheet" type="text/css" href="css/main.css">
</--head>
<--body>
    <--img src="pageimages/63_backcover.png" usemap="#Links" />
    <--map name="Links" id="Links">
        <--area shape="rect" coords="-1,635,396,673" href="http://www.facebook.com/digitalhorrormag/" alt="Facebook" />
        <--area shape="rect" coords="2,718,394,758" href="http://www.twitter.com/#!/uninvitedmag/" alt="Twitter" />
        <--area shape="rect" coords="2,802,449,843" href="http://www.theuninvitedmagazine.com" alt="Web Site" />
    </--map>
</--body>
</--html>

-->

**Comment by folletto** [comment]
Please have a read of this page on our wiki: https://github.com/Simbul/baker/wiki/Managing-links-and-urls ;)

**Comment by pterotype** [comment]
Aha, I see. Thank you very much! On to my next issue! ;)

**Comment by folletto** [comment]
You're welcome, and let us know how it goes. :)

**Comment by pterotype** [comment]
So far so good! Have an issue with the navigation viewport. Previously, with our Objective C - coded version, we were able to include every page in the magazine in the viewport and have the current page display in the centre of the viewport when invoked. We have not been able to get that working in Baker Framework.

**Comment by folletto** [comment]
It's not possible yet, check issue #350. :)
