### ISSUE TITLE
Unable to generate screenshots files in the "Private Documents" folder

### ISSUE THREAD

**Issue by belgo** [Simbul/baker#415]
I follow all the steps to generate the "screenshots", but does not create the "Private Documents" folder ... What is wrong?

**Comment by folletto** [comment]
So, you mean that you are following the wiki page tutorial (https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book) and you aren't able to go ahead more than step 3?

A few things then:
1. Which Baker version are you using?
2. Are you sure the book has be `-baker-rendering` flag set to `screenshots`?
3. While running the app, are actually the screenshots appearing in the app?
4. Could you describe step-by-step what are you doing?

**Comment by belgo** [comment]
Screenshot, not three cards!!

Thank you!

Do you speak french or spanish?...

**Comment by folletto** [comment]
Nope, sorry :)

**Comment by Simbul** [comment]
I'm assuming this is solved. Feel free to reopen if it isn't ;)
