### ISSUE TITLE
HTML5 audio

### ISSUE THREAD

**Issue by scozz** [Simbul/baker#416]
Hey Guys,

Total newb here with regards to coding and I know this issue has been up before in various versions, but I'm trying to add and an autoplay audio track to my page;

my HTML (which works fine in Safari) is;

audio autoplay=""
  source src="media/audio/children.mp3" type="audio/mp3"
  source src="media/audio/children.wav" type="audio/xwav"
  source src="media/audio/children.m4a" type="audio/m4a"
/audio

I have also added webView.mediaPlaybackRequiresUserAction = NO; in IndexViewController.m (as Xcode won't let me edit the UIWebView.h framework)

The audio does not autoplay in the sim. It displays a controller in the sim (which I do not want) and hangs it the simulator when you try to play the track via the controls???

I have no idea why?

If anyone can suggest where I may be going wrong that would be a huge help.

Thanks in advance,

Corey

**Comment by bahmet** [comment]
Did you try jplayer. You can disable controllers

**Comment by scozz** [comment]
Thanks for your reply. It seems to be working now??? maybe it just needed a bit of a kick.
