### ISSUE TITLE
I need a little help

### ISSUE THREAD

**Issue by vmardesign** [Simbul/baker#417]
hello all, I created a magazine with baker, but when I try it with the simulator I get an error: ocmock / ocmock.h file not found

Anyone know what happens?

Would greatly appreciate your help. Greetings!

**Comment by folletto** [comment]
It should be that you're trying to compile the Test Suite instead of the Application. Check the dropdown in the top-left corner of the Xcode window and make sure you're building the Baker App :)

**Comment by folletto** [comment]
Were you able to solve this? :)

**Comment by vmardesign** [comment]
Hi Folleto, yes i just rename the carpet OCMock y vuala! get out error!

Tnks!

**Comment by Simbul** [comment]
Brilliant!
