### ISSUE TITLE
colorbook for ipad

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#419]
hi all,
my color book application made with Baker. first of the series. Animals. 
http://itunes.apple.com/app/egitici-boyama-kitaplar-serisi/id526663518?mt=8
 all comments are welcome!!
thanks

**Comment by CatherineEng** [comment]
awesome! Lovely accomplishment. The crayon texture is especially nice.

**Comment by bahmet** [comment]
thanks, it is williammalone's scripts modified version.
