### ISSUE TITLE
Book pages cannot be in a sub-directory?

### ISSUE THREAD

**Issue by MacBoy** [Simbul/baker#42]
We have subdirectory of HTML files that are accessed through a top-level page within the book.

The pages (files) within the sub-directory cannot be accessed from a top-level page.

Example:

Book / Chapter1.html
Book / Chapter1_More / Chapter1_More_Stuff.html
Book / Chapter2.html
Book / Chapter3.html

A link within Chapter1.html points to the Chapter1_More_stuff.html via this link "Chapter1_More/Chapter1_More_Stuff.html"

When we tap on that link, nothing happens, no error message is displayed on the iPad and not in the Debugger console.  This happens also on the Simulator.

Are sub-directories allowed to have content that is hyperlinked from the top-level pages?

**Comment by folletto** [comment]
In fact, it's not supported. :)

Why do you need that? :)

**Comment by MacBoy** [comment]
My suggestion is to be as flexible as possible. Directories within the "book" content are useful to group related files. Why are directories not allowed -- is there a technical reason or is it for another reason?

Here is my explanation on how we need and use directories. Otherwise, we would have to develop post-processing scripts, which can lead to silly errors.

We intend on using Baker as a "Product Catalog", not as an eBook or a Magazine.

Our product information is inside a Content Management System that uses "directories" as a way of grouping related information.  An export out of that CMS generates product directories.  Inside each product directory are the files for that particular product.

A table of contents provides an easy to browse product index -- index_01.html  The index file has a list of each product.  The product links point to the overview.html file within each of the product directories.

Each product directory has four pages, with these (same) filenames:
- overview.html
- specifications.html
- features.html
- pictures.html

Thus, our file structure is:

index01.html

product1 / overview.html
product1 / specifications.html
product1 / features.html
product1 / pictures.html

product2 / overview.html
product2 / specifications.html
product2 / features.html
product2 / pictures.html

etc. etc. for the remaining products ...

Please re-consider the ban on directories. The beauty of Baker is that it is open-ended, allowing it to hold content for many different purposes.

Thank you!

**Comment by folletto** [comment]
It's not a ban. It's both a choice and a technical limitation.
For the complete reason, check the hPub topic #13, where the future implementation of the format has the answer to your problem. ;)

The brief answer is: it's going to be possible whent the manifest file is going to be implemented, it's not going to be possible with the automatic ordering because to do that we would be _less_ flexible, disallowing basically the possibility of not including files, an actual requirement to be more flexible and allow some kind of in-page dynamics with javascript. :)
