### ISSUE TITLE
How I can resolve this problem?, What is "Index 63 beyond bounds"?

### ISSUE THREAD

**Issue by belgo** [Simbul/baker#421]
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 63 beyond bounds [0 .. 28]'

Note: this problem aparently only exist with iPad 1 
(Xcode: Version 4.3.2 [4E2002])

**Comment by folletto** [comment]
That's a little too brief for us to understand. :)
Could you please describe step by step what you were doing, what did you change, where it breaks and the full debug log?

Also, please write also the version of Baker that you're using. ;)

**Comment by belgo** [comment]
Its my fault because I use Baker 3.1 and crash.
After downloading Baker 3.2, all work perfectly.   

Thank you... again!!

**Comment by folletto** [comment]
Great then! :)
These are the best problems: the ones that have an easy solution. :D

Keep us updated on your progress. :)

**Comment by belgo** [comment]
Hi, I'm working on 3 projects: 2 books and 1 food magazine.
Initially I work with Adobe DPS and produce 18 Apps (BCNBase in AppStore)
but the DPS result to expensive for my budget.
A few month ago I discover Baker and I develop 3 projects (2 books and 1
food magazine) with him.
I think Baker is a great solution for me.
I'll count you the development of Apps when are ready.

Thanks a lot for your collaboration!

‹Serge Herbiet

```
        BCNBaseDigitalbooks
```

Carrer Napols, 195-2-1, Barcelona, España, 08013, (34) 935323643 (Barcelona,
España), 630867405
http://www.bcnbase.com
skype: sergeherbiet
iChat: belgo 
facebook: http://www.facebook.com/home.php?sk=group_164196520276717&ap=1
