### ISSUE TITLE
Error using referrer = Baker

### ISSUE THREAD

**Issue by rodrigors3012** [Simbul/baker#422]
Making referrer = Baker and go to an external link to youtube and click a video, if I close the window to return to this page for the magazine before the video finishes loading the magazine gives error and closes. The same happens if I access any site and close it before the upload is complete.

Anyone found a solution for this error?

**Comment by Simbul** [comment]
Just to clarify: you open a link in the modal view, close it before the content has loaded, and this causes the Baker application to crash?

**Comment by rodrigors3012** [comment]
exactly

**Comment by Simbul** [comment]
And is it the same issue you're talking about in #406? If that's the case, I'd rather move the whole discussion to that thread.

**Comment by rodrigors3012** [comment]
I agree

**Comment by Simbul** [comment]
Brilliant, I'll close this one then :)
