### ISSUE TITLE
Urban Airship with Baker

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#426]
Hi,
have you ever used urban airship push notification service with baker. can you give me step by step information to setup UA for my application.
thanks....

**Comment by Simbul** [comment]
Urban Airship has already been mentioned in issue #292 - but I'm assuming you know that, given that the last comment in that thread is yours ;)

We have never used UA ourselves, let's see if someone else can help.

**Comment by bahmet** [comment]
thanks @Simbul , yes i followed that issue and other issues on internet. my problem is i am not a coder. so, when the tutorials tell that "link x,y,z... frameworks to your project" that is exactly where i stuck ( this is the beginning.) 
if someone is using any push service and could tell me (as if they tell to a 6 years old (where i am 38)) how to add it to my baker project, i will be very much appreciated. 
i am making colorbook applications with baker, that is the very best part of the framework, that you do not need any programming skills. i just copy my book folder to the framework and it works. i just need push messages to inform user about new issues and maybe some useful tips about growing a baby :))
thanks....

**Comment by bahmet** [comment]
hi,
i finally achieved to send push message with UA. i may even write a tutorial about it :))
thanks for helps..

**Comment by fluidImages** [comment]
bahmet - Can you (or have you already) shared your UA integration?

**Comment by bahmet** [comment]
Hi sean
No i havent. Pls give me couple of days to create a doc. Or you can ask if you stuck any point...
Regards
