### ISSUE TITLE
looking for a hosting  for the .zip files of the issues , to be downloaded? 

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#427]
We are a looking for  a hosting to accommodate the numbers of downloads of the .zip issues of the our new magazine, unlimited downloads or payment for application downloaded 

someone can advise me?
thanks

**Comment by kilop** [comment]
Hello. We have a hosting company (teclahost.com) if we need help you, please contact me. thanks.

**Comment by tstegart** [comment]
We decided to use Amazon S3, and the set-up was pretty easy. I had a Baker book download up and running in about an hour. You can get a free usage tier for a year, and then the cost is relatively low after that. http://aws.amazon.com/s3/pricing/

**Comment by folletto** [comment]
I'm closing this discussion since it's a bit old, with more than 6 months without a comment.
I think that the discussions here are relevant however, if a follow-up is needed: #613 and #639.
