### ISSUE TITLE
Apple Store approval process [guideline 2.21]

### ISSUE THREAD

**Issue by moushik** [Simbul/baker#429]
hi everybody,

just  a quick recap: 

we all know that baker is (a great tool) for publishing interactive books e magazines. 

But if your app is similar to a book, it may be rejected:
http://www.the-digital-reader.com/2011/06/08/apple-now-rejecting-ebook-apps-simply-becuase-theyre-ebook-apps/#.T9XcqfEsmHm 
http://www.cocos2d-iphone.org/forum/topic/12814
http://www.iphonedevsdk.com/forum/business-legal-app-store/69269-app-store-rejected-apple-asking-go-into-ibookstore.html

Infact, Apple states clearly: "Apps that are simply a book should be submitted to the iBookstore".

Note that iBookstore only accepts two kind of files: EPUB and iBooks (created with iBooks Author).
Sorry, no baker apps here.

So, what makes a book act as an app? Music? Galleries? Videos?
You can make all of this with iBooks Author (which, by the way, is another great software).
If I submit my interactive book built with baker,  with audio, video and galleries, chances are that it will be rejected.

Talking about magazines, I'm wondering if the same assumptions may apply to this category.

Does a magazine have to be interactive to wear the "app dress"?

"Universo Relojo" the beautiful app made by Francis (https://github.com/Simbul/baker/issues/374) passed Apple check. But, as you can see, it's "only" a mag, there's no sort of interactivity in it. There are other examples you can find yourself in the App Store: "Flow", "cityproject", to name a few. They are all apps (magazines).

I'm a bit confused: can we build a magazine and pass Apple examination?

Simbul says: "Unfortunately the Apple Store approval process has always been pretty random."
I agree, but I think nobody wants to waste hours of development to be rejected.

What do you think?

**Comment by folletto** [comment]
There's already the discussion #391 on this, please update that one. :)

**Comment by zenz** [comment]
just add some special function that a normal book cannot do is ok.

**Comment by gasparenovara** [comment]
which type of special function you intend?
