### ISSUE TITLE
Codesign operation failed - With Xcode 4,3,2

### ISSUE THREAD

**Issue by kilop** [Simbul/baker#430]
I'm getting this error after generate archive file from project, and trying export it to distribute ad-hoc.

Codesign operation failed
Check that the identity you selected is valid.

Thanks

**Comment by folletto** [comment]
It's a code signing issue, you should probably check your certificates/provisioning profile.

We can't help unfortunately on that side, I can advise you to ask on StackOverflow or on the official Apple Developer forums.
