### ISSUE TITLE
customizing the Index (TOC) behavior

### ISSUE THREAD

**Issue by Maxhodges** [Simbul/baker#431]
We want the table of contents to come in from the top. We understand this is non-standard behavior, but it makes sense for our product (we have an audio player at the page bottom.)

We tweaked the code to make it come in from the top (it was just a couple of minor changes; pasted below), but we still have one outstanding issue. When you first open the app, the menu flies in from the bottom. Each time after than, it slides in and out from the top, which is perfect. We are just stuck trying to figure out how to get it to stop fly in from the bottom when you first open the app. 

I assume that somewhere there may be some kind of init settings which establish the initial position, but I've been unable to find them anywhere. Anyone has some helpful ideas on this?

Cheers!

```
(void)setIndexViewHidden:(BOOL)hidden withAnimation:(BOOL)animation {
  CGRect frame;
  if (hidden) {
    //frame = CGRectMake(0, pageHeight + pageY, pageWidth, indexHeight);
    frame = CGRectMake(0, 0, pageWidth, 0-indexHeight );
  } else {
    //frame = CGRectMake(0, pageHeight + pageY - indexHeight, pageWidth, indexHeight);
    frame = CGRectMake(0, 20, pageWidth, indexHeight);
  }

  if (animation) {
    [UIView beginAnimations:@"slideIndexView" context:nil]; {
      [UIView setAnimationDuration:0.3];

      self.view.frame = frame;
    }
    [UIView commitAnimations];
  } else {
    self.view.frame = frame;
  }
}
```

**Comment by folletto** [comment]
I didn't test this, but:
1. You should probably have a look at the `init` function in `RootViewController` where the Index is initialized. You might try to set the initial frame there.
2. The code you pasted looks coming from a previous version of Baker. Did you upgrade?

**Comment by Maxhodges** [comment]
was not aware. is there a changelog somewhere? we've made mods so not sure if we could move forward. Is there some place I can get a summary of any compelling new features?

Cheers!

**Comment by Simbul** [comment]
For releases (of which the latest is 3.2) we have a changelog in the README: https://github.com/Simbul/baker/#changelog
For more fine-grained information, you can look at the commit messages in the `master` branch: https://github.com/Simbul/baker/commits/master
