### ISSUE TITLE
A questions about book links - can we have two books in our app?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#436]
We're a magazine and we're working on our second issue. I'm trying to avoid having to set up a server with our book files to be downloaded and I want to include both issue 1 and issue 2 in the app at the same time. As our issues are only 50mb, this isn't a huge problem.

Can I include two books in our app at the same time? How do I link between them and get Baker to switch the index views to the proper book? I don't need a "shelf" for people to pick which book they want yet, I just need to be able to link between two books. 
Any help is appreciated.
Tom

**Comment by folletto** [comment]
I don't think it's possible right now, you should probably code that yourself. You should probably by using the book:// protocol, and use it from one issue to link the other and load it locally. :)

**Comment by tstegart** [comment]
Thanks. If we end up hiring someone to do it (I don't know how to code) we'll release it, otherwise you might want to add it to the feature list. It has advantages of saving users time by not having to download a new book and also by not having to be near an internet connection and will save devs money by not having to pay for the extra bandwidth. A magazine could include two or three popular issues in one app and others could be downloaded later, thereby putting much of the download costs onto Apple.
P.S. How many hours work would you estimate it would take to do this?

**Comment by folletto** [comment]
The shelf should already provide that feature, and it's the next feature in line after the code refactoring. :)

I can't estimate much the work, it depends exactly on what you want. It should be in the order of days tho.

**Comment by tstegart** [comment]
Thanks. There isn't a way to trick Baker into thinking it is downloading a book but really it would be unzipping a file from within the book folder itself?

**Comment by folletto** [comment]
Well... that's what you have to discovery I think. :P

**Comment by tstegart** [comment]
I was thinking... can the index view be reloaded to a different file? Its a shortcut to getting what we want, but it will help if we can change the content in the index view to pretend to show different table of contents for each magazine issue.

**Comment by folletto** [comment]
Nope. But I'd advise to open a new issue here, so we keep track of the suggestion and we might implement it in the future. :)
