### ISSUE TITLE
invoke TOC by single click?

### ISSUE THREAD

**Issue by tangentdesign** [Simbul/baker#438]
I'd like to invoke the TOC by single clicking on a button rather than the default behaviour which is double tapping anywhere. Any idea how to do this?

thanks!!

**Comment by Simbul** [comment]
Unfortunately there's no API to do that yet.
If you want to implement the behaviour with Javascript and a button in the page, have a look at the `shouldStartLoadWithRequest` function.

To show/hide the index view you can use the `setIndexViewHidden` method. E.g., to hide the view:

```
        [indexViewController setIndexViewHidden:YES withAnimation:YES];
```

**Comment by tangentdesign** [comment]
thank you.

**Comment by tangentdesign** [comment]
This is over my head :) is it possible to provide the code required for a button that invokes the menu through a single click?

Much appreciated.

**Comment by Simbul** [comment]
That would require writing some HTML, javascript and ObjC code. It's not exceedingly difficult, but I'm afraid we cannot commit to developing a custom solution at this point.

Maybe someone who's had the same issue in the past will be able to send you some code :)

**Comment by fernandomedrano** [comment]
We used custom URL schemes to do this. You create HTML with an href like :"mycustomurlscheme://openindexmenu". Then add some code into BakerViewController.m, right before these lines:

```
            else if (![[url scheme] isEqualToString:@""] && ![[url scheme] isEqualToString:@"http"] && ![[url scheme] isEqualToString:@"https"])
            {
                [[UIApplication sharedApplication] openURL:url];
                return NO;
            }
```

==========start====

else if ([[url scheme] isEqualToString:@"mycustomurlscheme]){

```
                NSLog(@"    Custom URL Scheme is: %@", [url absoluteString]);
                NSLog(@"    Do something here...");
                // grab the action string as the resource specifier string    
                NSLog(@"    The invokeAction string is......%@",[url resourceSpecifier]);
                // test for resource part of the URL to determine action (eg openIndexMenu
                if ([[url resourceSpecifier] isEqualToString:@"//openIndexMenu"]){
                    // if the Index View is not disabled then open it or close it...
                    if ([indexViewController isDisabled] == NO){
                    // toggle the status bar which toggles the menu
                    [self toggleStatusBar];
                    }
```

etc....

You can use something like mycustomurlscheme://sendTweet in your HTML file (for example) and add code like this:

```
                else if ([[url resourceSpecifier] isEqualToString:@"//sendTweet"]){
                    // do something else - log it for now
                    NSLog(@"    The invokeAction string is......%@",[url resourceSpecifier]);
                    if ([TWTweetComposeViewController canSendTweet]){

                        TWTweetComposeViewController *tweetSheet = 
                        [[TWTweetComposeViewController alloc] init];
                        [tweetSheet setInitialText:tweetText];
                        [self presentModalViewController:tweetSheet animated:YES];
                    }
                }
```

To instantiate a TweetComposeViewController.

**Comment by fernandomedrano** [comment]
Oops...the code above is kind of mangled.

I do have a related question. Baker uses [self toggleStatusBar] to open and close the Index Menu. It seems to use BOOL "sharedApplication.statusBarHidden" to determine if the IndexViewController is visible (i.e. test for the visibility of the status bar to determine the visibility of the Index Meny. Why is this necessary?

Is there any other way to test the visibility of the IndexViewController other than the above method?

I tried 

```
                    if (indexViewController.isViewLoaded && indexViewController.view.window) {
                        NSLog(@"    The window is visible");
                        // the Index View is visible -> hide it.
                        [indexViewController setIndexViewHidden:YES withAnimation:YES];
                    }
```

....but I think that .isViewLoaded and .view.window are only available to UIView and not UIWebView so it does not work. 

Any tips? Ideally, I would like set a JS button or an HTML href to toggle the menu without also toggling the status bar.

(Sorry for the beginner question, but I am literally a beginner at all this)..

-f

**Comment by Simbul** [comment]
Hi @fernandomedrano, sorry for the delay.
The `toggleStatusBar` function is a toggle, which means it will close the bar when it is open and open it when it is closed. This of course requires knowing what the current status of the bar is (open or close).

I don't think `isViewLoaded` is going to help you: the index bar is always loaded, it's just hidden outside the viewport.

**Comment by folletto** [comment]
I'm closing this due to the lack of follow-ups. Reopen at need.

**Comment by bmatto** [comment]
Hello -

I am checking to see if there has been anything done in this regard... i.e. single tap to show contextual menu.  

Here's the problem I am faced with -

Baker doesn't offer configurations for augmenting the toolbar which contains the back to contents button or it's interactions.  I would like to be able to add a TOC menu here, and potentially a share button.

My expertise is in JS, and would have no issue whipping something up that would handle the interactions I would like to have happen ... however I need the home button to get back to the shelf.  Is there a JS api in place that allows me that control, and a way to turn off the native toolbar?  What would be your recommendation?  any feedback is much appreciated.

**Comment by folletto** [comment]
Uhm... Why aren't you just using the index for that?

**Comment by bmatto** [comment]
Perhaps I'm misunderstood - 

This is the newsstand context:

The toolbar that is revealed on double tap contains the only way back to the shelf.  Further, without obj-c skillz I'm woefully unable to add custom functionality to the existing toolbar.  What would be ideal would be disabling the double tap to view the toolbar/TOC, and then handle all events on the JS side for a custom navigation solution.

Maybe I'm missing something?

**Comment by folletto** [comment]
What I don't understand is why you want to modify the top toolbar – no, it's not possible unless you develop it yourself – to add a TOC when the `index.html` exists exactly to allow that. Why aren't you just using the index?

**Comment by bmatto** [comment]
Th requirement to add functionality to the toolbar comes from the design side of the equation - I am trying to meet those reqs.

I think my solution will have to be some sort of secondary navigation that is handled in js.  Thank you for your response though. 

Have you guys considered some sort of JS API similar to phone gap? I know there are events that bubble to the js level - but it would be killer to have js methods like goToPage or showToc - this would add a deep level of customization.

**Comment by folletto** [comment]
I'm afraid it's not possible out of the box without manually coding the features, if you need that degree of freedom you should just use PhoneGap, or go back to the "design side" and review the request, because that's a lot of work for something that would be ready if just done slighly differently. I would personally do this second thing. ;)

For the internal API there are specific individual request, see the tracker for that. However the "goToPage" already exists. It's a simple link. ;)
