### ISSUE TITLE
'cropped' page view when changing portrait to landscape orientation

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#440]
Hello, I am working on my first Baker app for iPad (and iPhone) which is a media rich magazine. Baker is awesome, I had no idea where to start until I found Baker :)

One issue I am experiencing with my app when testing on device - iPad 2, doesn't happen in simulator: 

When changing from portrait to landscape orientation I see a cropped portion of the (correctly sized) landscape page, with a portion of the previous/following pages showing. Sometimes it is the center portion of the current page showing with both previous and following pages showing on either side, sometimes it is cropped from the left with a portion of the following page showing, and (rarely) sometimes it is cropped from the right with a portion of the previous page showing. It happens on every page, but only the first time orientation is changed portrait to landscape. If you stay on the same page and flip back to portrait, then back to landscape again it shows proper landscape view without cropping, as if it's cached?

Is this a known issue, any idea how I can prevent it happening?

**Comment by folletto** [comment]
I can suggest first to see this to see if it's a problem of something that's not "clean":
https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue

Then... it looks like an orientation problem. Are you able to color the background of the HTML in a full color (so we can see the edges) and send us the screenshots, if not a slimmed down version of the page that triggers the problem?

**Comment by anjimi** [comment]
Thanks, I have been using clean build each time I run the app, as per the Baker tutorial instructed.

I have some screenshots of the issue, where should I send them?

**Comment by folletto** [comment]
To info AT bakerframework DOT com :)

**Comment by anjimi** [comment]
I have emailed some screenshots. I set the pages to have solid backgrounds in different shades of grey. Usually there are full-page background images on each page. I saved some first without removing the images but they were obviously quite large ;)

I found the size much quicker to correct itself without the images, it is less of an issue without the images! It was actually quite hard to capture the screen shots, the ones I managed to catch are in mid-rotate.

I sent 9 shots in total, 3 each for 3 different pages. So first image for each page shows portrait view, second shows the cropping issue, third shows correct landscape view.

Just so you know, with the background images I'm using one image for both portrait and landscape backgrounds, so it's not having to load a new image on orientation. My background image file sizes average 200-400k each.

**Comment by Xm4s** [comment]
Hi Anjimi!

I've seen the behavior you're talking about.
The only suggestion I can give you is:
• Try reducing the size of the images
• Try takeing the screenshots with the iPad simulator and include them in your book
• Try use three-cards mode.

Unfortunately it's pretty difficult to work on this problem right now, since we are in the middle of a code refactoring.
Probably the fix will come with the refactored version of Baker, stay tuned for updates :)

**Comment by anjimi** [comment]
Thanks Xm4s!

• I had thought to try reducing the image size after seeing how much quicker it was to correct without them.
• I've tried using screenshot mode but was getting a flicker on page change.
• I'm already using three-cards mode.

No problem, I understand. I will play with the image sizes and will keep an eye out for Baker updates....

**Comment by anjimi** [comment]
To follow up on this issue:

I tried reducing the size of my background images, but to make any significant difference to the file size there was too much loss of image quality and it made no apparent difference to the speed of the 'cropping' correction.

I discovered screenshot mode does fix the 'cropping' issue when changing portrait to landscape orientation :)

... _But_ there is another issue with a fade/flicker glitch on page change in screenshot mode - screenshot is loaded first on page change, which then fades to black (which is my background colour) before then loading the page itself. This happens quickly but is noticeable and unacceptable for us - is this a known bug?

I tried screenshot mode with pre-rendered screenshots included and screenshots folder referenced in book.json, but still get the flicker problem on page change.

I have now made all the pre-rendered screenshots solid black (same colour as my background colour) which means the fade/flicker glitch on page change is effectively invisible. It does mean the pages appear to take slightly longer to load, but of course with a solid black image for each screenshot these have very small file-size so at least they load quickly.

This seems to be the best compromise right now.

**Comment by folletto** [comment]
Unfortunately that's a known bug, and it's inside the `UIWebView`... so, it's an Apple's bug. You can try ti open a but in their bugreport system: http://bugreport.apple.com/ and hope that they will fix it.

**Comment by anjimi** [comment]
Hi, is that the fade/flicker glitch you are referring to? I'm not sure of the best way to describe it to apple, how to reference UIWebView, could you offer any advice on describing the problem correctly so I can submit a bug report to apple. Thank you :)

**Comment by folletto** [comment]
Their bug report system is quite standard and tells you in a few lines what's a good format for it. Just open a new issue, specify the OS and version and describe what should happen, what happens and how to reproduce it. The more details you can give it's always the better - like you did here above. :)

**Comment by anjimi** [comment]
Ok, thanks. I was meaning, I don't know how the screenshots mode works - how to describe the process of loading the screenshot, then the page content. Should I describe how the issue occurs relative to baker, or should it be described relative to UIWebView?

**Comment by folletto** [comment]
The screenshot should be irrelevant: being there or not, that "flash" of color will happen. The best idea would be for you to expresse the solution in "abstract" terms, only talking about `UIWebView` and then citing that you found the problem by working in a specific way with Baker. :)

**Comment by anjimi** [comment]
Hi, sorry, I'm confused. I only see the flash of colour when in screenshots mode, so what triggers it - if it's not loading the screenshot and then the content?

**Comment by folletto** [comment]
It's... way complicated if that's the same bug that we are tying to work around since version 1 - which, I'm not sure of course, but the behaviour is exactly the same. You can see another bug report here: #164.

The reason you see that in screenshot mode and not in other modes it's because the "fade" effect is applied there, while it shows itself in a different way in three-cards mode.

That said, go ahead: if Apple has already the bug report in the list, your report will count as one more vote to solve it. If it doesn't, then they will ask more details. And if you explain it - abstract or not - with a reference to Baker or even a link to this very issue, they can track it down. :)

**Comment by Simbul** [comment]
Closing as the discussion grew stale and the solution is most likely out of our hands.
