### ISSUE TITLE
Model view missing "open in Safari" button on iPad

### ISSUE THREAD

**Issue by Hamorabi** [Simbul/baker#441]
The open in Safari button appears on the simulator, but not on the iPad in the model window. I do see the back button though. Besides, the refresh animation is not centered, it is closer to the back button.

**Comment by folletto** [comment]
Did you do any change?
Did you try following this https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue ? :)

**Comment by folletto** [comment]
Hello, were you able to solve the problem?
