### ISSUE TITLE
Cannot open project in xCode - Quit unexpectedly 

### ISSUE THREAD

**Issue by Hamorabi** [Simbul/baker#442]
Process:         Xcode [1429]
Path:            /Developer/Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:      com.apple.Xcode
Version:         3.2.1 (1613)
Build Info:      DevToolsIDE-16130000~2
Code Type:       X86-64 (Native)
Parent Process:  launchd [107]

Date/Time:       2012-06-22 06:28:24.985 -0400
OS Version:      Mac OS X 10.7.4 (11E53)
Report Version:  9

Interval Since Last Report:          53306 sec
Crashes Since Last Report:           1
Per-App Interval Since Last Report:  12 sec
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      6BAD2E69-81DF-4747-9466-1FCD18C6CC84

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
objc[1429]: garbage collection is ON

Dyld Error Message:
  Symbol not found: _dispatch_queue_attr_create
  Referenced from: /Developer/Applications/Xcode.app/Contents/MacOS/../../../../Library/PrivateFrameworks//DevToolsCore.framework/Versions/A/DevToolsCore
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by folletto** [comment]
The problem is:
`Version: 3.2.1 (1613)`

You need the latest Xcode version. :)

**Comment by Hamorabi** [comment]
Thanks Folletto. I had the latest version of xcode, when I was double clicking on the project it was opening with the older version. I opened xcode and then opened the project from xcode and it worked fine.

**Comment by folletto** [comment]
Great! :)
