### ISSUE TITLE
book:// protocol providing access to image files

### ISSUE THREAD

**Issue by JamesBrocklehurst** [Simbul/baker#443]
In terms of making an HTML5 'shelf' that links to different books, some way of providing a thumbnail image for each link would be desirable.

What if Baker made it possible to access images using the book:// protocol within the src="" attribute of an &lt;img&gt; element?

&lt;img src="book://www.myserver.com/mybook.hpub/myimage.jpg" /&gt;

Authors could then place an image of their choice in the root of each .hpub bundle, with a generic title, such as 'cover.jpg' for this purpose.

**Comment by folletto** [comment]
Wouldn't that require however the full download of the book?

**Comment by JamesBrocklehurst** [comment]
Without fully understanding how the protocol works, I guess that the answer to that is implicit within your question: "yes".

Is there a way that individual files could be accessed without needing the whole book?

**Comment by folletto** [comment]
Yes, but it's a bit outside of the scope of Baker intended as a "iOS framework":
1. Make a server that handles `book://` (or `http://`) requests, sees the "hpub" file as zip, unzips/reads it on the server and provides the file.
2. Have the book "open" on the server (without `.hpub` extension) and just access the file through `http://`.

The first one requires a special script on the server (it could be as simple as a PHP script, but I would advise to build some kind of caching to avoid the constant zip opening/reading) while the second it's already doable but requires the book to be both as hpub and as unzipped version on the server. :)

**Comment by JamesBrocklehurst** [comment]
OK, cool, thanks Davide.

May also investigate this http://html2canvas.hertzen.com/index.html in relation to html5 local storage or webSQL to store the thumbs once they are generated. Will share my findings if I get anywhere.
