### ISSUE TITLE
the index from right to left

### ISSUE THREAD

**Issue by tmleeek** [Simbul/baker#444]
Hi , I want the index to be start swiped from right to left , where the code I need to change

**Comment by tmleeek** [comment]
if you just tell me where the code that tell to move the page to right or left , I will do the rest

**Comment by tmleeek** [comment]
I want to know where is the location of doing movement from right to left , the animation I mean . 
also I want to no how did you decide this the prev and that is next , where did you cach the swipe movement and decide where to go , it was easier on tapping to know where is it going , but the movement and the swipe thats really where I get very confused .

**Comment by folletto** [comment]
Are you talking about the index to be swiped (i.e. the overlay), or the pages (i.e. the book itself)?

**Comment by tmleeek** [comment]
the index , and the book pages , lets concetrate on the index , i want the cursor to start from the right and then I swipe it to the right to see the rest of chapters

**Comment by folletto** [comment]
Ok, so:
1. For the index. you should write a javascript yourself that moves the page to the very end the first time it loads.
2. For the pages, you should enable the "manga mode", see the wiki on the flag `-baker-start-at-page` here: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

This should do the trick. :)

**Comment by tmleeek** [comment]
where did I have to write the java script , and did you make one to make it start from the left  by javascript , if so please inform where is the javascript so i will modify it or creat something from it

**Comment by tmleeek** [comment]
I have added this line to book.json in your demo , but its not working : 

```
"-baker-start-at-page: -1",
```

**Comment by tmleeek** [comment]
sorry i modify it like this and work : 

"-baker-start-at-page:" -1,

however , I want  to modify the original code that make the movement so it  start correctly . 

so what i want is when  swipe to right will be go next page , and swipe to left will go to prev page . 

where is the code that i need to modify

**Comment by tmleeek** [comment]
and to be more clear , i am looking just to make the animation opposite just the animation i want just to make the animation the opposite .

**Comment by folletto** [comment]
I think you have to code it yourself unfortunately, it's not available in Baker, I'm sorry.

**Comment by tmleeek** [comment]
i will , just tell me where did you catch the swipe to right and swipe to left . 

where the code that cach this movement .

**Comment by folletto** [comment]
Unfortunately we don't deal with that: it's the _default_ behaviour of the `UIScrollView` component that we are leveraging. You will have to rewrite it all, or subclass it in some way.

By the way, from an interaction perspective I won't advise to keep the movement and reverse the animation, it will be perceived as weird to the final user. ;)

**Comment by tmleeek** [comment]
ok , forget about the  animation  I maent , where did you tell the code to go to next page when swipe to right where is it  , not the animation where did you tell the page to go next page if swipe to right , thats all what I need to know .

**Comment by folletto** [comment]
That's what I told you: it's done by the native Cocoa component `UIScrollView`. It does everything related to the swipe: swipe, animation, all.

**Comment by tmleeek** [comment]
where is that located ?
in which file ?

**Comment by folletto** [comment]
It's native, it's not in the project. It's from Apple iOS. We just use it.

Here you can find it's documentation:
http://developer.apple.com/library/ios/#DOCUMENTATION/UIKit/Reference/UIScrollView_Class/Reference/UIScrollView.html

**Comment by tmleeek** [comment]
so the native code , have not done by your , its have done by coca? I
thought you have write it for that I ask you for you help

I am sorry I took so much of your time .

On Sun, Jun 24, 2012 at 5:26 AM, Davide Casali <
reply@reply.github.com

**Comment by folletto** [comment]
No worries. :)
