### ISSUE TITLE
Screen just goes black

### ISSUE THREAD

**Issue by beansarenotfruit** [Simbul/baker#447]
When I hit run, the iOS simulator as well as my iPad simply go black. I've tried it with both my own book as well as with example books. I'm not getting any errors, so I have no idea what the problem is.

**Comment by folletto** [comment]
Could you add more details please? It's impossible for us to help without further details.

So, first of all: did you try this one?
https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue

**Comment by beansarenotfruit** [comment]
Yes, looked at the exploding issue page, went through the whole series more
than once.

My JSON file is below:

```
{
    "hpub": 1,
    "title": "Men's Dating Monthly",
    "author": ["Justin Carnahan"],
    "date": "2012-07-2",
    "url": "book://justincarnahan.com/books/mdm",
    "cover": "img/cover.png",

    "orientation": "portrait",
    "zoomable": false,
    "-baker-vertical-bounce": true,

    "contents": [
        "page000.html",
        "page001.html",
        "page002.html",
        "page003.html",
        "page004.html",
        "page005.html",
        "page006.html"
        "page007.html"
    ]
}
```

I haven't modified anything else, and even the pre-made books fail. I've
also tried restarting my computer, so I'm very confused.

**Comment by folletto** [comment]
Does that mean that it never worked?
Could you copy here the result of the debug log from Xcode?

The default book should work... however, in the JSON above you are missing a comma at the end of the line of page 6. Always check it with a JSON validator like http://jsonlint.com/

**Comment by beansarenotfruit** [comment]
Can I send you $10 via Paypal for helping me out? Where should I send it?
You solved it with a damn comma.

**Comment by folletto** [comment]
Well... we accept donations, yes, it helps us keep working on it. :)
It's on our website: http://bakerframework.com/donate :)

Thanks. :)

**Comment by beansarenotfruit** [comment]
Any plans on helping us get our apps into the iOS Magazine Store?

**Comment by folletto** [comment]
Uhm I don't understand, what do you mean? :)

**Comment by beansarenotfruit** [comment]
I want to create an iOS Magazine. Obviously, there needs to be a store view
and automatic updates set up. Do you know of a good place for me to learn
how to put my newly created magazine into the iOS magazine app store?

**Comment by beansarenotfruit** [comment]
Sorry, I meant newsstand.

**Comment by folletto** [comment]
A magazine is just an app, with special features. I'm not able to point you to any specific resources unfortunately. You might want to try however to start with the usual Stackoverflow and Apple tutorials. :)

Baker will get the shelf (to allow multi-issue magazines) in version 4.0, but I don't have a release date for that yet. :)
