### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#448]
Hey everybody,

thanks for all the great work. Is there an option on increasing the performance? For example rendering the first 10 Pages when starting the app or something like that?

Thanks!
florian

**Comment by folletto** [comment]
About 50% of our overall time is spent on performance, so... we have already done all that was possible.

There are a few things you can do, change rendering mode to find the best one for you, pre-render the pages (https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters) to have them ready from the start and things like that.

Unfortunately most of the issues are from the `UIWebView` and so most of our performance work comes from finding workarounds to that... :/

**Comment by ffranke** [comment]
Thanks for the quick response. Damn you, webview! ;)

**Comment by folletto** [comment]
Yeah :/

The only thing we can do is open issues on the bug report...

It's also funny to see the same "behaviours" on Chrome for iOS: flash of white and such. :D
