### ISSUE TITLE
Problem with wider Pages

### ISSUE THREAD

**Issue by vascoc** [Simbul/baker#449]
Hi, 

Thanks for the great work!

I'm trying to create a wider page for my book. I'm creating the page artwork in Tumult Hype with the size 3072 x 768 px. 
In the iPad it scrolls horizontally pretty well, but it also creates a white blank space bellow the page 3072 x 768 area. If I swipe vertically it will appear.

Is there a way to prevent this?

Thanks so much for all the help.

**Comment by folletto** [comment]
Hi and thanks for the support! :)

To answer your question, the vertical scrolling is determined by the height of the page itself, so... I guess there might be some margin or something in the page that makes it "higher". I don't know how Tumult Hype structures it, but you might try to put the animation inside a frame with a fixed height and `overflow: hidden`.

There are also a couple of flags you can specify, but while they might help, they aren't the direct solution to that problem:
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

**Comment by vascoc** [comment]
Hi,
Thanks for the quick answer.
I will try you suggestion now and will give some feedback later.
Thanks!

**Comment by Simbul** [comment]
Hi @vascoc, have you managed to solve your issue in the end? :)
