### ISSUE TITLE
That means Multitap page navigation in 1.1?

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#45]
I have not got an iPad. With the simulator can not I find out how it works

Thanks ;)

**Comment by folletto** [comment]
With the 1.0 you could just go on the next/previous page when tapping on the side, now it detects multiple taps and jumps multiple pages accordingly. :)

**Comment by frantovar** [comment]
Ok, thanks, and Full screen swipes?

**Comment by folletto** [comment]
Instead of separating the screen in areas for swipe, touch, etc, now we recognise swipes independently from where you do them. :)

**Comment by frantovar** [comment]
Ok thanks!
