### ISSUE TITLE
page down and page up tap areas

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#452]
I would like to know dimensions of the active areas for page down/up tap functions, and if it's possible to change the dimensions?

I found reference to these functions as `goDownInPage` and `goUpInPage` in this previous issue: https://github.com/Simbul/baker/issues/311

I have disabled page left/right tap in book.json, and I have a page down icon which is positioned bottom right corner, I would like it to be under the baker page up/down tap area but it's just outside it. I'm guessing this is because the top/bottom tap areas are narrower than the width to allow for the left/right tap areas. I would like the top/bottom tap area widths to be the same as full page width.

**Comment by folletto** [comment]
I think that you should start the code rewriting by checking the function `setTappableAreaSize`. :)

**Comment by anjimi** [comment]
Thanks Davide, where would I find this function? 
Sorry, I'm not familiar with Xcode or Objective-C, just learning :)

**Comment by folletto** [comment]
It's in `RootViewController.m` right now.

—

If you are just starting, notice that you can perform a project-wide search and look for it. :)
Some details here:
http://stackoverflow.com/questions/8016276/how-to-search-xcode4-2-project

**Comment by anjimi** [comment]
Great - I'll take a look and thank you for the info and help :)

**Comment by folletto** [comment]
You're welcome. :)

**Comment by anjimi** [comment]
Cool, that was really easy :)

So normally the corners are not active for any tap area.

I have changed from this:

```
- (void)setTappableAreaSize {
NSLog(@"• Set tappable area size");

int tappableAreaSize = screenBounds.size.width/16;
if (screenBounds.size.width < 768) {
    tappableAreaSize = screenBounds.size.width/8;
}

upTapArea    = CGRectMake(tappableAreaSize, 0, pageWidth - (tappableAreaSize * 2), tappableAreaSize);
downTapArea  = CGRectMake(tappableAreaSize, pageHeight - tappableAreaSize, pageWidth - (tappableAreaSize * 2), tappableAreaSize);
leftTapArea  = CGRectMake(0, tappableAreaSize, tappableAreaSize, pageHeight - (tappableAreaSize * 2));
rightTapArea = CGRectMake(pageWidth - tappableAreaSize, tappableAreaSize, tappableAreaSize, pageHeight - (tappableAreaSize * 2));

}
```

to this:

```
- (void)setTappableAreaSize {
NSLog(@"• Set tappable area size");

int tappableAreaSize = screenBounds.size.width/16;
if (screenBounds.size.width < 768) {
    tappableAreaSize = screenBounds.size.width/8;
}

upTapArea    = CGRectMake(0, 0, pageWidth, tappableAreaSize);
downTapArea  = CGRectMake(0, pageHeight - tappableAreaSize, pageWidth, tappableAreaSize);
leftTapArea  = CGRectMake(0, tappableAreaSize, tappableAreaSize, pageHeight - (tappableAreaSize * 2));
rightTapArea = CGRectMake(pageWidth - tappableAreaSize, tappableAreaSize, tappableAreaSize, pageHeight - (tappableAreaSize * 2));

}
```

so my top/bottom tap areas are now full width and my icon in the corner is now tappable :)

I would think a page-down icon in bottom corner could be a common desirable, and seems a waste that corners are normally not active at all, maybe worth changing this as standard in Baker?

(sorry, still trying to figure out commenting ;)

**Comment by folletto** [comment]
We kept the corners "empty" to allow them to be used for other things in the future, namely, the top-right one for "Bookmark". :)

**Comment by anjimi** [comment]
Ah, ok fair enough :)
