### ISSUE TITLE
Long tap toggles index bar

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#453]
When long-tapping (e.g. to select a word in a page) the status bar opens/closes, as if receiving a double-tap.
The status bar should only open/close on a proper double-tap.

**Comment by f3r3nc** [comment]
BakerViewController:1512 (shelf brach)
..  if ((touch.tapCount % 2) == 0) { ..
Is there a reason double tap is identified by modulo 2? Why not simply 
touch.tapCount == 2 ?

**Comment by Xm4s** [comment]
Hi f3r3nc,

The module 2 was my fault: with that condition the status and index bar visibility are toggled every 2 taps, even if you keep tapping continuously. With touch.tapCount == 2 the toggle happens only after the first 2 taps, to make it work again you have to stop tapping and make another double tap.

Sadly I haven't foreseen the toggling bug while long tapping, which is pretty bad :P

With the commit 50fb4d684256a030c1fc46acb66463485da386b7 I've changed the condition and fixed the problem.
Thank you for pointing out the solution :)
