### ISSUE TITLE
Is there any way to change the message related to downloading books?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#456]
I'd like to change the message the user receives when downloading books but I cannot find it in the code. For example, when the user clicks on a link to download a new book it asks "Do you want to download https://annoyingwebaddressthatisreallylong.hpub"

I'd like to make it more user friendly, as in "Would you like to download Issue 2?" and more aesthetically pleasing. It would also be helpful to hide the download links. Not much, I know, but helpful.

I can find the alert message, "Would you like to download " but I can't find where that is used in the code to add on the URL at the end to complete the message. If anyone knows how I would remove the URL, I would appreciate it.

**Comment by folletto** [comment]
The quick answer is: check the function `downloadBook` where the `feedbackAlert` is created. There's a parameter called `message` where the URL is appended to the message.

The long answer, that might help you in the future is: when you found the text message, you cal see that it's assigned to a constant called `OPEN_BOOK_MESSAGE`. To go back where it's used, just perform a search in the whole file for "OPEN_BOOK_MESSAGE" and you are going to find where it's used... that is, where I pointed you above. :)

—

On the other side, I think we can make that part simpler, so I keep this issue open as a reminder to fix that.

The idea is to change the `message` composition from a string append with `stringByAppendingFormat` to a proper string composition using `%@`. We'll check. :)

**Comment by tstegart** [comment]
Thanks! And thanks for the advice on the Open_Book_Message too, I've got it fixed.
