### ISSUE TITLE
flip scrolling model: Vertical (change article) Horizontal (view article content)

### ISSUE THREAD

**Issue by frederickk** [Simbul/baker#457]
I wasn't sure what to title this "feature" request.

I saw this issue, but it's not exactly what I'm looking for
https://github.com/Simbul/baker/issues/316

But what I'm looking for is to alter the model of interaction so that in order to change articles the user would scroll VERTICAL and to read the content scroll HORIZONTAL, ideally with page snapping based on orientation, i.e. portrait = snap every 768px, landscape  = snap every 1024px

[I made a simple graphic, explaining the above, which might be clearer:](https://dl.dropbox.com/u/7038255/baker_scrolling_interaction_mod.png)
blue = how it currently works 
red = how i would like to modify it

Any hints on how to modify the underlying Baker framework would be great! 

Thanks
Ken

**Comment by folletto** [comment]
We checked a bit if it's possible and how it could be done.
Now, in theory it's possible, but it's also quite deep in the code and so it might turn out quite hard to be done.

However, as a pointer...

Baker works basically by a combination of a `UIScrollView` and `UIWebView`. The `UIScrollView` is created within `initWithBookPath` and set as wide as the number of pages multiplied by the width of the iPad and as high as the screen height. In this way, the scroll view handles the horizontal scrolling automatically while the web view handles the vertical scrolling.

To revert this, you should change this whole logic and create HTML pages that scroll horizontally. I have no idea however how deep you need then to re-code Baker to make it work properly, consider that there are things like the rotation and the touch on the sides that needs to be taken care of as well and probably other things.

I hope this helps. :)

**Comment by frederickk** [comment]
thabks for the tip. i'll take a gander at the code but i have a sinking feeling it may be beyond my capabilities, i'll probably be back with more questuons. 

Ken

**Comment by frederickk** [comment]
Ok, after taking some time and poking around I've managed to more or less alter Baker as I mentioned. Thank you Davide for the tips! You can see my forked version of Baker here https://github.com/frederickk/baker

The key changes are within:
https://github.com/frederickk/baker/blob/master/Baker/BakerViewController.m

It's not perfect, as swiping between articles up and down doesn't work (at least not consistently), however, tapping up or tapping down does. 

As for scrolling pages, tapping left and right scrolls "chapters" fine, within the HTML I've attempted to build a snapping mechanism, so that they scroll like pages when swiping... which so far works very roughly http://jsfiddle.net/kenfrederick/4p4zb/

Any hints or tips on where I can improve would be greatly appreciated.

Thanks,
Ken

**Comment by folletto** [comment]
Awesome work, we'll check it out. :)

**Comment by folletto** [comment]
I'm closing this since Baker evolved a bit from there. Still, the work done here could be useful to someone else that might want to do the same. :)

**Comment by frederickk** [comment]
although this issue is officially closed, i have pulled the the 4.1 version and flipped it's scrolling model and made some additional modifications here https://github.com/this-and-that/baker/tree/flipped-app

**Comment by folletto** [comment]
Wonderful! Thanks for the update! :)
Maybe is it worth to edit the `readme` file to describe the changes you made there? :)
