### ISSUE TITLE
The best way to upgrade my application to 1.1

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#46]
Hello,

I have configured my application to locate files by language and other changes I've made.

What do you think is the best way to upgrade to 1.1?

Thanks!

**Comment by Xm4s** [comment]
Well, first I would probably try my book with the latest version of the framework and see how it works, then I would merge the changes I need in the new code one by one.

**Comment by frantovar** [comment]
Think you could replace outside xCode, directly in my project folder files like Baker AppDelegate.m. h, etc ...? or should do it from Xcode?

**Comment by Xm4s** [comment]
I think you should first try the book with the pristine 1.1 version of the framework, then you should implement your changes in the code with Xcode.
