### ISSUE TITLE
Using jquery Reel with Baker

### ISSUE THREAD

**Issue by trashoid** [Simbul/baker#460]
Hi, 

I try desesperatly to use jquery reel (http://jquery.vostrel.cz/reel) in baker.

It doesn't work in baker but works in baker bookshelf (nin9creative).

I don't understand it at all ... I didn't change anything (that's the same page on the two applications)

The touch event of baker take the first position and I can't access the jquery reel event. 

As I wrote before, it's working on baker bookshelf but not in baker "single". It's getting me mad :)

Could you help me please ?

Thanks in advance for any clue.

**Comment by folletto** [comment]
I don't think we can help much, since I don't know how they implemented the shelf. You should probably ask @nin9creative if he can point out what are the differences that might trigger the different behaviour. :)

My guess is that they removed the interceptor window, but I don't know how they compensated the lack of it. :)

**Comment by nin9creative** [comment]
Hey Trashoid, so are you saying that it works when running in the bakershelf version, but it doesn't work when you use the standalone baker version?

**Comment by trashoid** [comment]
Yes it is ... that's why I'm getting crazy :) ... I didn't change anything on the html page ... I just tested it on bakershelf ... that worked.

I thought about no problem to place it on baker standalone (because it's the same core I suppose) and boom ... the swipe is getting the principal interceptor and the script still in background and then no work.

**Comment by nin9creative** [comment]
Yeah, we had to change the code somewhat in the shelf to accomodate launching the Baker core as a "plug in" viewcontoller which included removing the interceptor window from the original Baker project and implementing a different gesture recognizer scheme....

**Comment by folletto** [comment]
But does your current gesture recognition work? The last time I had an update for you you were still trying to sort that out. Is there something still missing?

**Comment by nin9creative** [comment]
On the Bakershelf-NewsstandKit branch yeah that works (default branch for my fork).  There is a lot of stuff implemented, still trawling
through the Newsstandkit stuff though, but there is a lot done already.

You can download the latest code from that branch and run it, it loads some sample issues etc so you can see the behavior.

**Comment by folletto** [comment]
We'll check that, thanks. :)

Unfortunately the changes are too big for us to check it all properly and move everything. On this specific fix we might have to ask some questions for that if you're available, or... if you could port back the new way you developer on the current master it would be awesome. ;)

**Comment by folletto** [comment]
Hi @trashoid did you try the last Baker 3.2.2 version? Does it work? :)

**Comment by trashoid** [comment]
Hi folletto, thank you for your answer. I'll try it and I will let you know.

**Comment by Simbul** [comment]
Hi @trashoid, any news?

**Comment by Simbul** [comment]
I'm closing this as it has gone stale. Feel free to reopen if you need it.

**Comment by benoitchantre** [comment]
I'm trying to use jQuery Reel with Baker v4.0, but without success.

The html works in my desktop browser but not in Baker.

In the iOS simulator, I can see that the plugin has loaded my image sequence when the page is loaded, but it doesn't respond to touch events. The output of Xcode shows "user scroll" even if I blocked the bubbling of touch event.

Here's my code:

``` javascript
window.addEventListener("focus", function() {

    $('#sequence').on("touchstart, touchmove, touchend", function(event) { 
        event.preventDefault();
        event.stopPropagation();

        $('#sequence').reel({
            path: "img/sequence/",
            images: "image_###.jpg",
            frames: 73,
            frame: 1,
            entry: 1
        });

    });

}, false);
```

Any idea?
