### ISSUE TITLE
Links to iTunes App Store

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#461]
This is a followup to the closed issue <a href="https://github.com/Simbul/baker/issues/176">#176</a> on link behaviors in Baker books, where solutions proposed either don't work or are beyond me.

I'm using  Baker 3.2. and trying to make a free sample of a <a href=""http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&uo=4">Baker/Laker book</a> that contains links to the iTunes store to allow purchase of the full version. 

Links to most URLS work fine but links to iTunes don't load at all.

If ?referrer=Baker so that the link loads in a modal view it shows "Loading" indefinitely and returns

<pre>» Loading a modal webview for url http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&uo=4&referrer=Baker
2012-08-02 11:35:54.618 Viols Free[761:15203] [Modal] Loading </pre>

If the link is opened int eh same webview it returns:

<pre>2012-08-02 11:36:54.771 Viols Free[761:15203]     Page is current page and current page IS NOT delaying loading --> handle clicked link: itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4
2012-08-02 11:36:54.772 Viols Free[761:15203]     Opening absolute URL: itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4
2012-08-02 11:36:54.772 Viols Free[761:15203]     Link doesn't contain param "referrer=Safari" --> open link in page
2012-08-02 11:36:54.773 Viols Free[761:15203] • CurrPage failed to load content with error: Error Domain=WebKitErrorDomain Code=101 "The URL can’t be shown" UserInfo=0x7fc54e0 {NSErrorFailingURLKey=itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4, NSErrorFailingURLStringKey=itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4, NSLocalizedDescription=The URL can’t be shown}
2012-08-02 11:36:54.773 Viols Free[761:15203] • CurrPage failed to load content with error: Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo=0x8c8b430 {NSErrorFailingURLKey=itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4, NSErrorFailingURLStringKey=itms-apps://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&ign-mpt=uo%3D4, NSLocalizedDescription=Frame load interrupted}</pre>

@foletto refers to http://stackoverflow.com/questions/1453711/reliably-opening-app-store-links-from-a-uiwebview as providing a solution. However this document seems to be out of date and is intended for people who, unlike me, don't need to be told where to make changes to existing code.

Can it really be true that Apple devices are able to open any URL <strong>except</strong> those directed to their own App Store? Is there a solution that works for the Objective-C-challenged?

Thanks for any help with this!
Ardal

**Comment by folletto** [comment]
That Issue refers to a really older version of Baker, lots of things changed since that, so I guess no answer there can help you. :)

You probably found a bug in the latest version, we need to check. Thanks for the report. :)

**Comment by folletto** [comment]
Maybe, if you can: test `referrer=Safari` as referenced on the wiki: https://github.com/Simbul/baker/wiki/Managing-links-and-urls and let us know what happens. :)

**Comment by ghost** [comment]
Thanks, @folletto. The link opens Safari and produces an error dialog: <pre>Cannot Open Page
Safari cannot open the page because the address is invalid.</pre>

Xcode returns the following:

Page is current page and current page IS NOT delaying loading --> handle clicked link: http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&uo=4&referrer=Safari

Opening absolute URL: http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&uo=4&referrer=Safari

Link contain param "referrer=Safari" --> open link in Safari

replacement pattern: \?referrer=Safari$|(?<=\?)referrer=Safari&?|()&?referrer=Safari

Opening with updated URL: http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8&uo=4

Ardal

**Comment by folletto** [comment]
Interesting. Thanks for the feedback! I think we'll be able to check this next monday and see if there's a simple solution. :)

**Comment by ghost** [comment]
Thanks! Holding my breath ;-)

**Comment by bahmet** [comment]
hi @drardal  did you try  itms://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8 instead of  http://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8 
itms:// approach worked for me in my application http://itunes.apple.com/app/comfort-your-baby/id542189740?ign-mpt=uo%3D5
my link in the application  is  `<a href= itms://itunes.apple.com/us/artist/dijitalyayincim.com/id507130006?uo=4 target=itunes_store>`

**Comment by ghost** [comment]
Thanks @bahmet, I did try that without success.

Incidentally I wonder how your link works since surely there's an ampersand missing before <pre>target=itunes_store</pre> as per http://www.apple.com/itunes/affiliates/resources/documentation/linking-to-the-itunes-music-store.html

In any case even when I pasted your link, with or without the ampersand, into my app it did not work. Without the ampersand, it's interpreted as a local file link. With it, Xcode returns <pre>Error Domain=WebKitErrorDomain Code=101 "The URL can’t be shown"</pre> Details below.

<pre>2012-08-03 10:13:31.661 Viols Free[977:15203]     Page is current page and current page IS NOT delaying loading --> handle clicked link: itms://itunes.apple.com/us/artist/dijitalyayincim.com/id507130006?uo=4&target=itunes_store
2012-08-03 10:13:31.662 Viols Free[977:15203]     Opening absolute URL: itms://itunes.apple.com/us/artist/dijitalyayincim.com/id507130006?uo=4&target=itunes_store
2012-08-03 10:13:31.662 Viols Free[977:15203]     Link doesn't contain param "referrer=Safari" --> open link in page
2012-08-03 10:13:31.663 Viols Free[977:15203] • CurrPage failed to load content with error: Error Domain=WebKitErrorDomain Code=101 "The URL can’t be shown" UserInfo=0xfd231e0 {NSErrorFailingURLKey=itms://itunes.apple.com/us/artist/dijitalyayincim.com/id507130006?uo=4&target=itunes_store, NSErrorFailingURLStringKey=itms://itunes.apple.com/us/artist/dijitalyayincim.com/id507130006?uo=4&target=itunes_store, NSLocalizedDescription=The URL can’t be shown}</pre>

**Comment by bahmet** [comment]
Hi ardal i read your message from my ipad and the link in the error message works fine :)))

**Comment by bahmet** [comment]
Hi ardal
İ used that link in my application under info button. When you press info button ( " i " image actually, placed in the top right corner of the page) it opens a little popup and inside the popup there is appstore icon and when you tap it from ipad or iphone it opens the page in the app store application. İ can not give you the more info about the link since i am not near my computer. 
Pls let me know if i can help more

**Comment by ghost** [comment]
Well yes, you notice the link in the error message has the ampersand in it ;-)

My question is why it works in a browser and in your app, but exactly the same code fails in mine. Which version of Baker did you make your app with?

**Comment by ghost** [comment]
Update: the syntax

<a href="itms://itunes.apple.com/us/app/custos-caldwell-viols/id515392351?mt=8?referrer=Safari">

works on the iPad. It opens iTunes in two successive windows, but at least it opens. It does not work at all on the simulator.

**Comment by folletto** [comment]
I think the reason is simple: `itms` is handled by the Store app, and there's no Store app on the simulator, that's why it can't work. :)

So, may I mark this issue as solved? :)

**Comment by ghost** [comment]
Oh, perhaps that's why two windows open in succession: Safari then the store app. In any case the issue seems to be solved, thanks, Davide. 

Best,
Ardal

Ardal Powell
CEO
518 779 6188
Skype: drardal ~ Twitter: @drardal

Music Word Media Group
www.musicwordmedia.net

**Comment by bahmet** [comment]
Its good to hear that itms worked on your app too .....
