### ISSUE TITLE
Semantic issues

### ISSUE THREAD

**Issue by stemmo** [Simbul/baker#463]
Hi guys,

I've updated to Mountain Lion and xCode 4.4. Since updating, the Baker framework brings up a whole slew of semantic issues. Most stem from JSONkit.m, others are parsing issues from unzip.c. Searching suggests other frameworks (e.g. Phonegap) had the same issues. 

Are there any plans to amend Baker to eliminate these issues popping up every time you run?

Also, has anyone had any trouble submitting apps to the iTunes Store with these parsing/semantic errors in the final package? Or don't they care?

Cheers.

**Comment by upyrus** [comment]
I've found it.

https://github.com/shai-amar/pubnub-api/commit/54b92b2af488fdf7285d21bfea31f506f7c331b6

But "unzip.c issue" did not solved.

**Comment by folletto** [comment]
These are part of some libraries we are using. We can check if there are updates like the one you pointed out in the main branch, it might solve the issue. However as far as I know it shouldn't block from compiling, is that correct?

**Comment by mfpro** [comment]
For unzip.c issue ... hmm?

```
    /* we check the magic */
    if (err==UNZ_OK)
    { if (unzlocal_getLong(&s->z_filefunc, s->filestream,&uMagic) != UNZ_OK)
            err=UNZ_ERRNO;
    else if (uMagic!=0x02014b50)
        err=UNZ_BADZIPFILE; }
```

**Comment by folletto** [comment]
Did you try to suggest the change to the authors of unzip.c, so we can update and use the official release instead of patching it ourselves? :)

**Comment by mfpro** [comment]
Nope, sry.

**Comment by upyrus** [comment]
https://github.com/kajinka13/ZipArchive/commit/74362f1695d56cd855dbae8dfe6789d711b6da87#diff-0

Semantic issues solved! :)

**Comment by folletto** [comment]
That's awesome, thanks for the update! :)
We are in the middle of some big changes, so we won't be able to quickly add this, but it's right up in the priorities. :)

**Comment by cfocoder** [comment]
Hi guys,

Just discovered Baker over the weekend after searching for a solution like this, and I found Baker really promising, especially for version 4.  I run it with Xcode 4.5 and I got 25 warnings:

4 Parse Issues (unzip.c)
6 Format String Issues (JSONKit.m)
12  Semantic Issues (JSONKit.m)
1 Semantic Issue (AQGridViewCell.m)
1 Dependency Analysis Warning

I don't think these will cause a problem when compiling, but I thought I just let you know

Regards
Hector

**Comment by folletto** [comment]
Yes, they don't cause an issue, but thanks for pointing out. We have to check all these libraries for updates.

**Comment by Simbul** [comment]
We have updated our libraries (and removed an additional warning in our code), in commits c97bbea96f86ea96fd3e9b1ac765b96071f97c9e (SSZipArchive), 5a4187388e475c7209d27aa611e14e7da67ce61f (JSONKit) and 3f056d474932c64f5f094fe445da1573316e4012 (`Constants.h`).

This means the only warnings left are the AQGridView ones. Unfortunately we are already using the latest version of the library.
