### ISSUE TITLE
Error while double tap with two finger 

### ISSUE THREAD

**Issue by ahmetomer** [Simbul/baker#464]
Hi all,

 I'm working first Baker app and I have a problem.  When double tab to screen with double finger baker lock the scroll (not always most of the time) and error is;

Ignoring call to [UIPanGestureRecognizer setTranslation:inView:] since gesture recognizer is not active.

Is this a known issue or any idea ?

Thanks

**Comment by folletto** [comment]
We weren't aware of it, we'll check. Thanks. :)

**Comment by Simbul** [comment]
Hello @ahmetomer, I'm sorry but I could not reproduce the issue on my iPad.

Which version of Baker are you running? Is it the `master` branch on https://github.com/Simbul/baker ?

**Comment by folletto** [comment]
Do you have any update @ahmetomer? Otherwise we'll close this issue...
