### ISSUE TITLE
How much newsstand integration has anyone done yet?

### ISSUE THREAD

**Issue by itgiawa** [Simbul/baker#467]
My plan is to build and submit a fully functional newsstand app to Apple before I contribute any code to Baker. I've already implemented NKAssetDownloading of books.

My question is, has anyone implemented subscription registering code yet, even if its ugly and just a work in progress?

Also, has anyone thought about push notifications? 
I'm making a bunch of free apps with free subscriptions  and can't afford to pay UrbanAirship .10 per subscription. 
GoogleApp engine does not support apple push notifications, so I'm looking for alternatives. 

Thanks!

**Comment by Simbul** [comment]
I can't give you solutions, but a couple of pointers you may find interesting.

Newsstand support is an ongoing discussion you can find in issue #100.

Push notifications have been discussed in issue #292 (Urban Airship in #426, but I think you have ruled that out). That's a very long thread, so I'll point out [EasyAPNS](http://www.easyapns.com), which was proposed in that discussion and seemed to work for someone.

**Comment by folletto** [comment]
Hey @itgiawa if you made any progress on these topic we'd love to hear back from you. ;)
