### ISSUE TITLE
multiple slideshows on page

### ISSUE THREAD

**Issue by nicolastilly** [Simbul/baker#468]
Hi all,

I would like to know what is the best way to integrate more slideshows in a page? I work with Laker but it is not possible to integrate several slideshows.

Thank you!

**Comment by folletto** [comment]
What do you mean exactly? Did you try any iPad compatible slideshow library? :)

**Comment by nicolastilly** [comment]
I am looking for a solution to integrate multiple slideshows on a single page (like in Laker). I don't know what iPad library to use (jQuery)? Can you give me links or examples?
Thank you very much!

**Comment by bahmet** [comment]
@Nikkolas ,
pls read these for multiple slideshows in a page ;) ErneX modified imgscroll.js and jquery.touchSwipe-1.2.1.js and explains how to use....
http://www.lakercompendium.com/how-to-use/modules/image-slideshow/#comment-579
https://gist.github.com/1245444

**Comment by nicolastilly** [comment]
@bahmet Thank you ! I read the explanation of Ernex :)

**Comment by bahmet** [comment]
I hope it helped ;))

**Comment by folletto** [comment]
Hello @Nikkolas were you able to solve the issue you were having with the JS library in the end? :)

**Comment by nicolastilly** [comment]
Hello @folletto , I'm still working on the details of @bahmet. For now, I have not completely succeeded in integrating multiple slideshows on a page.
But I hope to succeed quickly! : )

**Comment by bahmet** [comment]
hi @Nikkolas 
pls let me know where you stuck. i can send you my working page for your reference, if you want

**Comment by Simbul** [comment]
Closing as inactive.
