### ISSUE TITLE
Downloaded book has wrong index view size

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#469]
When using book links in Baker 3.2, the downloaded book has the wrong index view size. The content is correct, so the new index.html file is loaded, but it seems to use the same width as the local book and cuts off part of the content (the downloaded book index.html is wider than the local book in my magazine). When I test the downloaded book in Baker by itself it displays correctly, so I know it is the right size, its only when it is downloaded that it is incorrect.

EDIT: If you shut down the app and open it back up again, while you're still in a downloaded book, then the index view is the correct size.

**Comment by folletto** [comment]
Did you also try the latest `MASTER` from GitHub? :)

**Comment by tstegart** [comment]
No, sorry, we were getting a release out the door. I'll try it again with the master and get back to you guys.

**Comment by folletto** [comment]
Hello, were you able to look into this? :)

**Comment by Simbul** [comment]
Closing as inactive.
