### ISSUE TITLE
Index bar doesn't work when I close and restart the app on an Ipad2

### ISSUE THREAD

**Issue by Mky777** [Simbul/baker#470]
Hi

I'm a little confused with this issue. I develope a book with Baker and when I try it in the simulator works fine with the index bar in the lower part (in the vertical and horizontal position) . But when I stop the simulator and its running on the Ipad2 memory when I press two times for the index bar it shows only across the left side in vertical position and because it's designed in horizontal it only appears the first box int the upper-left corner (it doesn't depends on the device orientation). My bar's nav.css width is 4920  pixels. 

Another issue is that xcode 4.4.1 show me 22 errors in the jsongkit.m and unzip.c (semantic, format and parse issues) and I doesn't change a lot from the original script...

Any thoughts to solve the index bar issue?

**Comment by folletto** [comment]
Could you try the current master from GitHub here and see if that fixes the problem for you?

**Comment by folletto** [comment]
Hello @Mky777, were you able to test it? :)

**Comment by Simbul** [comment]
Good to hear it's working! I'm closing the issue as it is now solved.
