### ISSUE TITLE
Fresh Content

### ISSUE THREAD

**Issue by airtek** [Simbul/baker#472]
Hi Guys,

I'm not new about Baker Framework, but now I need to create an ebook of my articles in two ways.

My ebook will be formed from two parts:
- the book / hpub  will contains article . If I need to update this I can use the book protocoll and update the file
- the news part , accessible by a button in the navigation bar will show some news from by blog. About this , for you the best choise is using a simple html page with an iframe pointed to  the news or a json/rss reader (maybe in javascript) ?

Thanks for you attention

goodbye

**Comment by airtek** [comment]
for the second part, reading the wiki, https://github.com/Simbul/baker/wiki/Managing-links-and-urls , I can use a link to the direct page?

**Comment by folletto** [comment]
I think that everything you said is correct. The book contains all, and you can update it with a book:// protocol link.
The news can be made accessible by a link that opens your website. :)

**Comment by airtek** [comment]
perfect.

I dont' know only one things.

How I can insert a control of connection when I user click on the news
button without an active internet connection?

**Comment by folletto** [comment]
You could probably just use some JavaScript and use XMLHTTPRequest to check if a connection is available. It will be better in future versions, but right now that's the way to go. :)

**Comment by airtek** [comment]
It's ok  simple solution is powerfull

2012/8/26 Davide Casali notifications@github.com

**Comment by airtek** [comment]
I'm doing some tryes and I have some doubt:

when I submit the app to appstore , inside there is the first book , for example "book0".

Later some days I need to update this book without resubmit the app to appstore.

Reading the documentation I need to use the book protocol , for download the book , but how I can replace the "book0" with the "newbook" , so when I reopen the app I find only "newbook" ?

**Comment by folletto** [comment]
Right now, you can just resubmit the app to the app store, or write a javascript updater you embed in your book that checks for new versions and if a new one is present it asks the user to download it.

**Comment by airtek** [comment]
which code I can use for rewrite/replace the original book?

For example with phonegap ( I know is a different system / way) i can use
some class for write files on the device

**Comment by folletto** [comment]
About the download of books, you can read from our Wiki (see the link on top) this page:
https://github.com/Simbul/baker/wiki/Managing-links-and-urls

Just make a JS that checks if a new version is available and if it is, it shows the download link to the user.

**Comment by Simbul** [comment]
Just a quick note: if you download a book using `book://` as explained in the wiki link above, the new book will replace the old one - even if you close and reopen the app. Baker will take care of writing the files on the device.

**Comment by airtek** [comment]
thanks guys,

now is more clear

2012/9/11 Alessandro Morandi notifications@github.com
