### ISSUE TITLE
problem with xcode 4.4.1

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#475]
hello!
today i tried to export testing my app on ipad.
i use bakers 3.2 and updated xcode 4.4.1. 
it generates 22 issues:

```
4 in unzip.c
baker-framework-3.2/Classes/lib/minizip/unzip.c:613:9: Add explicit braces to avoid dangling else
18 in JSONKit.m
baker-framework-3.2/Classes/lib/JSONKit/JSONKit.m:745:180: Format specifies type 'unsigned long' but the argument has type 'NSUInteger' (aka 'unsigned int')

/Volumes/grafik/buchklub/bkl_app/yep_will/xcode/version 1.1/baker-framework-3.2/Classes/lib/JSONKit/JSONKit.m:2598:11: Direct access to objective-c's isa is deprecated in favor of object_setClass() and object_getClass()
```

i´m no programmer - can anyone help me, what to do?
all worked very well in xcode 4.3

thanx
h.

**Comment by folletto** [comment]
Ignore them. These should be just warnings and should compile fine. :)

**Comment by hitchio** [comment]
thanx-i´ll try!!

**Comment by folletto** [comment]
Hello! Did it work? :)

**Comment by hitchio** [comment]
hi there!
it worked very well. i had this issues, but i ignored them and uploaded to app-store without problems.
now my app is in "waiting for review" ;-)

**Comment by folletto** [comment]
Excellent! :D
