### ISSUE TITLE
HTML 5 Canvas Tag

### ISSUE THREAD

**Issue by DaveLEWIS1973** [Simbul/baker#476]
Hi, 

I am new to Baker.

For my first project, is it possible to us the HTML 5 Canvas Tag in order to animate characters in a story book using baker Plz ?

Thank you everyone

DaveLEWIS

**Comment by folletto** [comment]
Baker supports everything supported by Safari Mobile: canvas included. :)

**Comment by DaveLEWIS1973** [comment]
Hi Davide,

Thank you, that is what I wanted to hear. 

May I ask, is the Canvas Tag the best option for simple animation in Baker Plz ?

Thank you for your prompt reply. I appreciate it immensely :D

DaveLEWIS

Vizualiser.biz

thevizualiser@gmail.com

**Comment by folletto** [comment]
That's not a Baker specific question: an animation in Baker is an animation in HTML. Just choose the way you prefer to do it. ;)

**Comment by DaveLEWIS1973** [comment]
Hi Davide,

Thank you for your reply. 

Just clarify, are you saying that anything that works in HTML 5, will work in Baker and by extension, Xcode ? 

I appreciate your time.

Best Wishes

DaveLEWIS

**Comment by folletto** [comment]
Xcode needs apps like Baker (or PhoneGap) to use HTML5. Baker loads HTML5 and the engine is WebKit, the same version you have in Mobile Safari.

So yes, anything that works in HTML5 on Mobile Safari will work.

**Comment by DaveLEWIS1973** [comment]
Hi Davide,

Thank you, I'm on my way now :D

DaveLEWIS

Vizualiser.biz

thevizualiser@gmail.com
