### ISSUE TITLE
Baker on Android

### ISSUE THREAD

**Issue by DikkeBalou** [Simbul/baker#477]
Hi,

I discovered your framework two weeks ago when a I was searching a solution to publish magazines.  It was wonderful except it was not so well developed on Android with Friar :-(

So I decided to create an Android application taking most of your functionnalities in Baker with some from the BakerShelf.

It use the HPub format but not all attributes are implemented yet.

If you want to try your book, send me your zip file and I will publish it on my repo.

So let's try it and I'm waiting for your feedback!!

https://play.google.com/store/apps/details?id=com.heymananddroid.android.hmdhpubreader#

Thanks for your help

**Comment by xiripi** [comment]
Hi. I would try to test my application. Can you send em your mail or aplication for aneroid?

thanks

**Comment by DikkeBalou** [comment]
Hi Xiripi,

you have two possibilties to test your HPub file:
- You can send you hpub zip file at claude@heymananddroid.com and I will publish it on my issues list
- Or in the app you can introduce your issues repository by clicking on the refresh button

**Comment by folletto** [comment]
That looks cool! :)

What do you plan to do with it? Are you going to release it or make a paid service to package books? :)

**Comment by DikkeBalou** [comment]
I will share the code once my client will accept my offer for his magazine.

**Comment by folletto** [comment]
Sounds cool. :)

**Comment by chebTS** [comment]
Hi, Your app is awesome. What about code sharing, are you going to share it?

**Comment by DikkeBalou** [comment]
Hi chebTS,

I will not publish the code but I can put your book on the GooglePlay for free with ads if you are a non-profit entity and in the other case for a little subscription.

Are you interrested to be an early adopter?

**Comment by folletto** [comment]
Oh, so you didn't get the approval for sharing? That's unfortunate. :/

**Comment by xiripi** [comment]
The version you have post on googleplay dont open the books. The app is for
review know. I make a magazine for my town. I need a android version.

Cumprimentos,
Vítor Ângelo

**Comment by festaans** [comment]
Its sad to hear that the code wont be open sourced

**Comment by nin9creative** [comment]
You aren't going to share this?  On my Nexus 7 tablet it looks all screwed up (the interface).  Also, are you referencing the Issues list at my bakershelf.com domain?  It popped up asking what list to use and it was pre-populated with that.

It's too bad you aren't going to open source this to get some folks to contribute.  It could be a really cool and compelling draw for the Bakerframework in general to be able to support folks that want to publish on the Play store as well as iTunes App store.

**Comment by folletto** [comment]
Unfortunately if the code can't be opensourced there's no reason to keep this topic open. Let's hope for someone with full opensource support. :)
