### ISSUE TITLE
jquery touch event

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#478]
hi,
i found a jquery memory match game tutorial and resources on the web.  i followed the tutorial and customised it to my need. it works from my computer both with chrome and safari.
however it does not on the simulator and the iphone 3gs device. i copied working book folder to my web folder and again it did not work on safari browser. 
i suspect it is the touch event issue. is there any tool or script to enable touch events without modifying the code. say for example including the script on the header part of the page and it takes care of the rest. or can someone help me to add touchevents to the script
thanks...

**Comment by folletto** [comment]
I don't know in detail, but I guess no since the mouse events (`mousedown`, `mousemove`, `mouseup`) and the touch events (`touchstart`, `touchmove`, `touchend`, `touchcancel`) are different.

See here:
http://ross.posterous.com/2008/08/19/iphone-touch-events-in-javascript/

**Comment by bahmet** [comment]
hi @folletto thanks for the info, 
actually i found hammer.js http://eightmedia.github.com/hammer.js/ which support touch gestures. but sadly my problem seems not related to touchevent issue. 
can you throw another guess, why my script does work on computer and safari but does not work on ios device. 
thanks

**Comment by folletto** [comment]
I can't make any other guess given the information I have. If it works on desktop but not on mobile that's the first thing you should check. What did you do exactly? Hammer.js seems an enabler, not a plugin, so you have to rewrite everything you did with Hammer.js to check if it works.

**Comment by bahmet** [comment]
http://dijitalyayincim.com/dergi/book/1.html when you check this you may understand clearly what i want to do. try on computer and device please.
with hammer. i included jquery.hammer.js plugin and added it to my section as described in https://github.com/eightmedia/hammer.js. i also enabled output to see whether it receives my touch gestures or not. so i found that it receives my touchs. 
thanks

**Comment by folletto** [comment]
Ok, Hammer.js received the touches. Now you have to forward the touches to the same points where your app is now receiving the clicks. ;)

That said it's strange, because the app you have there shouldn't require management of touch notifications. Weird.

**Comment by bahmet** [comment]
hi @folletto ,
i found the problem is related to the sound bound to the flip action.now i am trying to solve it.
thanks for your help...

**Comment by folletto** [comment]
A-ha! When you'll fix it, could you come back and detail the issue and how to solve it? It could be very useful to others too. :)

Thanks! :)

**Comment by bahmet** [comment]
you can try now :)) http://dijitalyayincim.com/dergi/book/index.html 
pls try on ipad or iphone...

**Comment by folletto** [comment]
That's great. :)
Good job. :)
