### ISSUE TITLE
App Rejected: "did not integrate with app content and/or iOS features"

### ISSUE THREAD

**Issue by marwol** [Simbul/baker#479]
App Rejected - what to do?

Today my app built on Baker Framewotk was rejected by Apple. Apple's reasoning was violation of section 10.6. "Specifically, we noticed your app: - did not integrate with app content and / or iOS features"

The app is a collection of 100 fotos with captions (can be turn on/off by a click on the page). It is divided into 10 chapters, each with a cover page with images and text.

I do not understand why it is beeing rejected. There are hundreds, if not thousands, of similar magazine apps in the App Store. Many off the with no interactive content at all.

Any  suggestions on what  to do to get my app approved? The plan was actually to make a whole series of travel apps, but now i am afraid i am wasting my time.

My app will not work as a eBook, so if i cannot make it to the App Store i have to trash it. After hundreds of hours work, that is not what i want.

Any suggestions is appreciated.

/Martin

**Comment by folletto** [comment]
Yes. Unfortunately Apple can be very picky, and moody, about this. Sometimes just re-submitting makes it through.

Let's see if there's something we can say: 
1. Why wouldn't it make sense as an ebook? (this just to see what could be done, I'm not questioning it).
2. Is that an exact quote of the email you received? Isn't there anything else? Usually they refer to specific parts of the agreement that you didn't follow, is there any?

**Comment by marwol** [comment]
Thank you for your reply.

Here is the what Apple wrote to me:

"
_10.6_

_We found the user interface of your app is not of sufficient quality to be appropriate for the App Store. Apps that provide a poor user experience are not in compliance with the App Store Review Guidelines._

_Specifically, we noticed your app:_
- _did not integrate with app content and/or iOS features_

_Please evaluate whether you can make the necessary revisions to improve the user experience of your app._
"

I think Apple's point is that I might as well make a web app or a website. It is true, but it is true for 99% of all magazines in the App Store more of them are basically just PDF's.

I can throw all sorts of interactivity in the app, but then the magazine idea disappears. I really like the way Baker Framework functions, so making it a more regular app would be annoying.

/Martin

**Comment by folletto** [comment]
Uhm that review is quite decisive, and it's not really about the fact it's a magazine, because we saw other rejections for that reason and their feedback was "Publish it in the Book store", here they aren't saying it.

Given: **"the user interface of your app is not of sufficient quality to be appropriate"** it seems more about the app overall quality, not the fact it's a magazine.

Without having seen it however it's hard to tell with more precision, but this would be the clue I get from them.

**Comment by marwol** [comment]
"the user interface of your app is not of sufficient quality to be appropriate" is just a standard quote takes from their guidelines, section 10.6.

Note this:

"Specifically, we noticed your app:

did not integrate with app content and/or iOS features"

I really do not understand what they mean.

I will post some screenshots, so you can se that the UI is not bad.

**Comment by folletto** [comment]
Yes I know it's a quote, I was just saying that the problem highlighted isn't that it's a magazine. If you search around, you see it's different from other cases of rejection, where the text was: _"Apps that are simply a book should be submitted to the iBookstore" (App Store Review Guidelines 2.21)_.

I'm really just guessing, they might well have changed the policy internally. I have no idea.

**Comment by marwol** [comment]
I know people use to get rejected by section 2.21 (i think).

Here is some of the first pages in the rejected app: https://www.dropbox.com/sh/q1sqsf9fzmk3fvj/dzcnSvgTP3?%20m

Its not state of the art, but neither the worst thing i have seen in App Store.

**Comment by davidrsim** [comment]
We've had some success, but always with some interactivity i.e. making calls to an external server. 

However, as we don't charge for our apps, we're almost certainly going to move to HTML5 delivery over the web, rather than an app submission. It works well, even with Apple's outdated web app implementation. 

App store guideline interpretation is too hit and miss, and once we came close to missing a launch deadline because Apple were questioning our right to use content - we provided proof and they took 3 weeks to get round to approving thereafter!

**Comment by krisix** [comment]
I didn't have problems with publishing emgazine based on bakerframework.

It has only text. I've added some shelf support - you can check this here http://itunes.apple.com/pl/app/dobry-znak/id542474380?mt=8

Version 1.2. is on the way - because 1.1 has some bugs.

As soon as I clean up the code I will publish it on GitHub.

**Comment by hitchio** [comment]
i can give you a hint to provide your app with a little game or video support. mostly this works.
i get rejected, if i use too much commercial stuff and too less programming.

**Comment by folletto** [comment]
Hi @marwol  did you solve this issue in the end?

**Comment by marwol** [comment]
I  wrote to Apple to get a more precise reason why the rejected my app.

Yesterday evening a guy from Apple in San Jose called me. I was unable to pick up the phone, so I will call him today.

**Comment by marwol** [comment]
I have been in contact with Apple. They think my app should be submitted to iBooks Store. It needs native iOS functionality to be acceptet in App Store.

I just wonder why my app is rejected, when there are  100 + similar magazines in the App Store already.

I can solve the problem by building in things I feel do not belong in a magazine. I guess a interactive map or a video will do the job.

Suggestions are very welcome.

**Comment by marwol** [comment]
I think I found the real reason for the rejection.

I have done all my testing on af iPad 1, because my iPad 3 was dedicated to iOS 6 testing, which the old production version Xcode could not build to.

Now after updating Xcode, I can see that my magazine behaves completely different on my two devices.

1) iPad 1, iOS 5
2) iPad 3, iOS 6

On 1) everything looks as intended.

On 2) the content looks fine in portrait mode, but not in landscape. The content will not rotate at all. 

If i start the app in portrait the content will not rotate. If i start in landscape, the content will still not rotate, but it is formated for 1024_768 (instead of 768_1024), which means that everything is messed up. For instance the index-file can be seen on the screen.

It is the same project build on two different devices. I do not know if the difference is caused på iOS og the device (ipad 1 vs. ipad 3) og retina vs non-retina.

I hope someone can help me figureing out wat is going on.

**Comment by folletto** [comment]
There might be some issue with iOS 6, but we still have to look into that. They _did_ change the code to manage rotation, so that might be the issue.

**Comment by marwol** [comment]
There is an issue. I have tried with af clean install of Baker Framework and the book example. It behaves the same way: Will not rotate in landscape.

I also have tried to download som Baker build apps from the App Store. Same ting.

**Comment by folletto** [comment]
Thanks for checking. It's definitely an issue of iOS6 then. :/

**Comment by folletto** [comment]
We'll track the orientation problem in Issue #493, so we can keep the rejection and the fix isolated. :)

**Comment by Simbul** [comment]
@marwol I think we can close this issue, as your comment in #493 makes me think you're not experiencing problems with landscape mode anymore.
Have you resubmitted your app? Heard anything new from Apple?
