### ISSUE TITLE
Supported interface orientations  to Landscape (left home button)  , But the UIView is not rotation ,

### ISSUE THREAD

**Issue by magix** [Simbul/baker#48]
I have set the baker-info.plist
Supported interface orientations  to   Landscape (left home button)  , 
But the UIView is not rotation , It always stay in  Portrait (bottom home button) ..
I have try 
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
  // Overriden to allow any orientation.
  return YES;
  }

1.0 version is work ,but 1.1 is not work ....

**Comment by folletto** [comment]
Baker 1.0 didn't support orientation switch, I don't know how it could have worked for you. :)
We are working on the rotation right now, it should be in the next release. See issue #6. :)

**Comment by magix** [comment]
Dose the latest 1.1  is work ?

**Comment by folletto** [comment]
No, the next release is the one coming after the 1.1. :)
