### ISSUE TITLE
Custom events fired on window blur and focus

### ISSUE THREAD

**Issue by timeinline** [Simbul/baker#481]
i use custom events fired on window blur and focus,but when i tap twice,the events also fired,could you tell me why?

**Comment by Simbul** [comment]
My guess would be that a double tap causes the index bar to open and this causes focus to be transferred to the index bar itself. 
I'd have to do some testing to be sure, but it seems to make sense to me.

**Comment by timeinline** [comment]
so how can i fix it？

**Comment by timeinline** [comment]
i fixed it by

var firsttime=true;

window.addEventListener("focus", function() { 

if(firsttime){

alert('this is the first time.');

firsttime=false;

}

}, true);

window.addEventListener("blur", function() {

firsttime=true;

 }, true);
