### ISSUE TITLE
Xcode stuck when loading book

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#482]
Hi @Simbul   I've been following baker, laker and siteless from couple month, and from simbul and andrew(nin9creative), its been a great work, I'm building digital magazine, until... A few hours ago, somethings came up...
My xcode project stuck, i wonder if anywone could help my by testing my book at ://numosh.com/spotsdigital/ its the 1st zip of the book (combining the siteless magazine format that using zip rather than hpub), and thankyou so much if anyone would help me for testing the book only (book://numosh.com/spotsdigital) it would be very helpful... Thank you...

And sorry for my very bad english...
cheers...

**Comment by Simbul** [comment]
I downloaded the book (`4.zip`) and tried it with the latest version on `master`: seems to be working well for me.

What do you mean exactly when you say that Xcode is stuck when loading the book?

**Comment by ghost** [comment]
Hmmm, its when i download the first book using xcode project - baker, and start to open it (after download), it wont start, and the page reffer to xcode again, and suddently 18 threads came up from no where...

**Comment by Simbul** [comment]
Ok, are you using the master branch of Baker or are you using the [fork by nin9creative](https://github.com/nin9creative/baker)?

In case you're using the latter, you should really be asking for help in their issue tracker, as they're definitely going to be able to help you better.

**Comment by ghost** [comment]
Im using the latter actually, ok, I'll do that, thank you so much for your time...

**Comment by Simbul** [comment]
You're welcome :)
