### ISSUE TITLE
Dose the  page cache  work ?

### ISSUE THREAD

**Issue by magix** [Simbul/baker#49]
I have try to open the comment code   who have relation to below .
 self.prevPage;
 self.currPage;
self.nextPage;

But it seam not work well . Some thing is confused . I have try to fix it ...could you give me some tips . that i can fix this problem . 

It always crash after do :
    // *****\* DESTROY
    /*if (webView != nil&& slot != 0) {
        [webView removeFromSuperview];
        [webView release];
    } 
if destroy it . It will crash ... I don`t know why.

**Comment by folletto** [comment]
Uncommenting commented code couldn't make things work. If it's commented there's a reason: there's no page cache. ;)

See issue #27 and all the comments there.
