### ISSUE TITLE
Issues prices, bookmarks and icon changer

### ISSUE THREAD

**Issue by sevirinov** [Simbul/baker#491]
Hello, big thanks for this framework, but I have some questions:
1. How can i put prices near app instead of free (i use shelf)? And also pay for this. (In-app)
2. If user was in issue already, he continues reading from place, where he finished.
3. And when new issue appears, how can i change app icon in NewsStand.

**Comment by folletto** [comment]
Hello @sevirinov  :)

To answer your questions:
1. To sell your app you should have the Apple Developer account. You set that up on the iTunesConnect website. For in-app you need custom code that you have to add yourself to Baker.
2. Baker restores the publication at the latest reading point.
3. Baker doesn't support NewsStand yet, however that part is managed by NewsStand (will be). :)

**Comment by Simbul** [comment]
@sevirinov if you have no more questions I'll close the issue, is that alright?
