### ISSUE TITLE
3.5 and 4 inch snapshot

### ISSUE THREAD

**Issue by belgo** [Simbul/baker#495]
Hello,
I'm working on a iPhone version of my Magazine app: BCN Colina Delicooks and I have a small problem with the "snapshot".
With the release of the last iPhone I need two kind of the snapshot: 3.5 and 4 Inch.... how I can resolve this problem?
Thanks.

**Comment by folletto** [comment]
Baker unfortunately doesn't support that yet, it's the same support missing #434 and we have it scheduled right now on the 4.1.

**Comment by belgo** [comment]
Thank you.
