### ISSUE TITLE
App Rejected: "did not integrate" + "slow"

### ISSUE THREAD

**Issue by ShaunStilwell** [Simbul/baker#496]
Hi all, 

I recently had an app rejected from the app store: 

We found the following issues with the user interface of your app:
- Portions of your app loaded, refreshed, ran, and/or responded very slowly. For example, every page loaded slowly.

(Q: Is there a way to preload the pages? Alternatively I can reduce the size of the images. )
- Did not integrate with iOS features. For example, the user should be able to interact with your app content, ex: list, history, sort, etc.

(Q: Is there a way to integrate any of these features?)
- Did not include iOS features. For example, it would be appropriate to use native iOS buttons and iOS features other than just web views, Push Notifications, or sharing.

Any advice or links would be most helpful.

**Comment by folletto** [comment]
Given that's the second time in a couple of weeks (see Issue #479) I can just guess that Apple has changed or is changing its approval policies.

It seems that PhoneGap users have similar issues: https://groups.google.com/forum/?fromgroups=#!searchin/phonegap/rejected/phonegap/2dPIMUmBbAk/XibomfhLSoQJ
This thread specifically contains also some suggestions on how to try solving it... I hope it might help.

**Comment by ShaunStilwell** [comment]
Hi Folletto 

Thank you for the response. I have done research and still can't find anything on integrating IOS features with the Baker. If you have any links or tuts I could see that would be much appreciated.

**Comment by marwol** [comment]
Maybe it is time to build iOS native stuff into the framework itself to ensure that the apps will be accepted by Apple. Rigth now we have to do it ourself depending of out personally needs.

One thing most people could use, and at standard magazine function, is the ability to mark pages as favourites with a star or someting. This should be combined with some sort of section where the favourites can be seen, sorted etc. If you put alle this in objectiveC and not HTML/javascript you have a iOS native functionality.

You can show a standard navigation bar at the top with the required buttons to mark as favourite and to show the list. The navigation bar can show up along with the index.html file when you tap a page.

Another posibility is to build in support for in app purchase and newsstand support.

**Comment by folletto** [comment]
We're open for contributions, as you can see we already have all these things lined up in this issue tracker but alone we can't do everything. So if you can develop any of these things, let's have a chat in the matching Issue here on GitHub and let's proceed. :)

**Comment by nin9creative** [comment]
This is some of what we had been intending on the BakerShelf branch work...  However there are already a handful of BakerShelf magazines
approved and on the App Store.  Here are a couple of the recent ones that I know of.

http://itunes.apple.com/us/app/oscorp-magazine-vietnam./id557827480?ls=1&mt=8

http://itunes.apple.com/us/app/revista-canamix/id498066240?mt=8

**Comment by folletto** [comment]
Unfortunately as we discussed BakerShelf has broken compatibility about 1 year ago and so we aren't unable to support it or merge it. :/

**Comment by folletto** [comment]
Baker 4.0 should have solved this kind of problems, plus this discussion didn't have follow-ups in more than 4 months, so I'm closing it. Reopen at need.
