### ISSUE TITLE
Maps integration

### ISSUE THREAD

**Issue by ec8or** [Simbul/baker#497]
Hi,

Is it possible to integrate map links in a publication? So rather than opening up an external browser the standard map application would be opened (Google or Apple depending on which version of iOS is running).

I've seen in the docs that mail:// links are supported so if someone could point me in the right way this might be pretty straight-forward to add by myself.

Cheers

**Comment by folletto** [comment]
Yup. You the code to check that specific bit is inside this function:

```
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType
```

**Comment by Simbul** [comment]
Hi @ec8or, have you managed to implement your maps? :)

**Comment by ec8or** [comment]
No haven't looked at it yet as some other requirements came up that were more important. Will ask in another thread actually :)

**Comment by danielreiser** [comment]
If I got your question right, then you simply could use: `maps://` as an url scheme(It's working for me in iOS6 as well). I don't know wether this url-scheme is already deprecated, so this really won't be future-proof.

Besides my suggestion above, Apple suggest to use a simple http-link:
read this -> http://developer.apple.com/library/ios/#featuredarticles/iPhoneURLScheme_Reference/Articles/MapLinks.html

I'll fork it and implement a clean and future-proof version of this, if anyone is interested :)

cheers
