### ISSUE TITLE
Is it possible to check if another app is installed?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#498]
If you know the URL scheme info from the plist file, is it possible to do using html/javascript? For example, if you want to check if another magazine you have is installed or if an advertiser wants to know if their app is installed.

**Comment by folletto** [comment]
As far as I know it's possible, but you have to implement it yourself since it's beyond the scope of Baker.
This is a good starting point: http://stackoverflow.com/questions/5746289/determine-if-an-app-exists-and-launch-that-app-on-ios

**Comment by tstegart** [comment]
Thanks!

**Comment by tstegart** [comment]
@folletto Does Baker support a URL schemes? I can't quite figure out how they work exactly, but should it be possible to have a user click on a link on our website and a specific story opens up in our magazine? That seems like it would be useful. Maybe I need to learn more and write up a little how-to.

**Comment by folletto** [comment]
It's as any other app: you have to do that by yourself. Just define your own protocol and implement it. :)
