### ISSUE TITLE
xcode 4.5 ios6 - css, javascript not working?

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#500]
hello!
i have problems with testing my app on ios6 from xcode 4.5 in Simbul-baker-3.2-ios6 (last zip-download)
 some javascripts failed to run on ipad retina, allthough it works perfect in safari on ipad retina.
i don´t know where the problems are. has  anyone same isuues?
help would be appreciate. thanx!
h.

**Comment by hitchio** [comment]
found my problem-thanx

**Comment by bharathiit09** [comment]
may i know reason for the that problem??

**Comment by hitchio** [comment]
it´s not a baker - problem. i thought first. i work with hype and export to html5. 
meantime i wrote my example to tumultco-support.
