### ISSUE TITLE
Port to Windows 8

### ISSUE THREAD

**Issue by steelcuda** [Simbul/baker#501]
I was wondering, I'm trying to build an HTML5/JavaScript children's book for Windows 8.  It would seem that I could start to port Baker to the HTML5/JavaScript/CSS app type in Windows 8.  Where would you recommend that I start?  I saw that someone ported it to Android.

Thanks,

Scott

**Comment by folletto** [comment]
That would be great. :)

Well, just start by allowing the same interaction model to work: allow the tool to open the hpub and paginate left/right. With that, you will have the basic structure in place, and you can start adding all the other pieces, like links, download, etc. :)

On the Windows 8 side, I don't know the development environment so I can't help much. :)

**Comment by steelcuda** [comment]
Is there list anywhere of the all of the interactions for Baker?  Something
that I can use as a feature list?  And I'm not totally clear on this point,
did you create the "HPub" format?

**Comment by folletto** [comment]
There isn't a feature list, except for the Hpub specification (that yes, we created after long discussions with some experts in the field). Two things you can use if you want to build an exact replica:
1. The issues labeled as "feature" here in the issue tracker
2. The Git commits

These should give you an excellent list of features. :)

**Comment by Simbul** [comment]
I guess another, slightly more condensed list would be the [Changelog](https://github.com/Simbul/baker#changelog) in the README.

**Comment by JamesDuffield** [comment]
Hey @steelcuda , have you made any progress with a port to Windows 8? I have just finished a publication using Baker on iPad and now I'm required to create the same thing for Windows 8 Tablets.

**Comment by Simbul** [comment]
I'm doing some housekeeping. I'll close this thread soon - unless @steelcuda has got news of course.
