### ISSUE TITLE
Fixed elements don't stay in position

### ISSUE THREAD

**Issue by webperformance** [Simbul/baker#504]
With the release of iOS 6 we are facing a problem with fixed divs (position: fixed; top: 0; left: 0). If the user changes to a page and scrolls then downwards, the fixed div layers don't stay in their position, but scroll too as long as the user holds his finger down to scroll. Afterwards the fixed elements jump back in their assigned position. This happens just once. The behaviour is then as intended.

We were not able to fix this with CSS. Has anyone the same problem and an idea how to fix this? Any tipps are highly appreciated.

**Comment by Simbul** [comment]
Weird. Is this happening on Mobile Safari as well?

**Comment by webperformance** [comment]
Yes, it's really weired. I've tested it in Safari with iOS 5.1 and iOS 6 and there's no problem with fixed Elements.They stay in position all the time. My Baker project works perfect on iOS 5.1 too but iOS 6 is the Problem. I've tried al lot of things I've found via google, like: http://igstudio.blogspot.de/2012/09/positionfixed-in-ios-6.html
My first presumption was that this is a CSS problem. But obviously I was wrong.

**Comment by folletto** [comment]
Uh... Are you really sure the same problem doesn't appear in Mobile Safari? Because I tested this yesterday and it jumps in Mobile Safari as well, exactly the first time as you described...

**Comment by webperformance** [comment]
Yes I am. There's no "jumping" on Mobile Safari iOS 5.1 and iOS 6.
Try on your own:
http://sites.webperformance.eu/bakertest/Seite_03.html
The fixed elements do what they should. The stay positioned :-)

**Comment by webperformance** [comment]
Here's a short clip that describes the problem best:
http://www.youtube.com/watch?v=WyAfgd4AZmU

**Comment by folletto** [comment]
Yes, it's exactly the same problem I tested in Mobile Safari hehe. It's a CSS issue, we can't do much.

**Comment by danielszczygiel** [comment]
I spent an hour analyzing (eliminating everything from csses) the site http://sites.webperformance.eu/bakertest/Seite_03.html. And the solution is in @font-face directive.
Try to add something like this to your css:

@font-face {
    font-family: "FixFont";
    src: url();
}

and apply the font to your fixed element with 

{
  font-family: "FixFont";
}

Bravo apple, great bug:)

**Comment by folletto** [comment]
WTF!

Impressive debugging @danielszczygiel :o

**Comment by unphased** [comment]
Found a solution for this here: http://igstudio.blogspot.de/2012/09/positionfixed-in-ios-6.html

**Comment by ashconnell** [comment]
Unphased, I dont think this is the correct solution for this particular problem.

In his example that shows the broken/working fixed elements, on iOS6, the first time you scroll the page both of the elements scroll up and out of view. After the first scroll it works as intended from there on.

**Comment by unphased** [comment]
Hmm. Weird cuz it stays messed up no matter how many times I scroll around.

**Comment by ashconnell** [comment]
I managed to create a choppy fix using jQuery. I force the page to perform that "first broken scroll" before the user gets a chance to do it.

``` javascript
$(window).load(function(){
    window.scrollTo(0, 1);
});
```

Which scrolls the page up 1 pixel. This causes a mild flash (page re-render?) but is better than a confusing broken interface when the user begins using it.

IMPORTANT: The page must have scrollable content when it calls window.scrollTo(0, 1) for it to work. 

This wasn't my case as I am building an app with hash based swappable views and the page loads with no scrollable content and then checks the hash and loads the relevant view.

To fix my issue, i create scrollable dummy content, initiate window.scrollTo(0, 1); and then remove it before my hash script kicks in:

Below my body tag is: 

``` html
<div id="fixedPositionFix" style="height:2000px;"><div style="position:fixed; top:0; left:0; width:100%; height:44px;"></div></div>
```

And this javascript is fired before my hash function (ie: my page is blank)

``` javascript
$(window).load(function(){

    window.scrollTo(0, 1);
    $('#fixedPositionFix').remove();
```

**Comment by silouanwright** [comment]
@unphased that does not work for this problem

**Comment by Simbul** [comment]
Unfortunately there's not much we can do here. The solutions above are all we have at the moment. Hopefully Apple will fix this soon.
