### ISSUE TITLE
COLLADA files

### ISSUE THREAD

**Issue by ec8or** [Simbul/baker#505]
In iBook Author it is possible to use COLLADA files for embedding 3D objects, is there any way this could be made to work in baker? I've tried to find examples of plain HTML5 embedding but have had no luck, so it would be if it is possible to render some sort of native view inside the web view?

Anyone looked at this before?

**Comment by folletto** [comment]
If it's not possible in HTML5, it's not possible in Baker.
As for the HTML5 support: if it's there in Mobile Safari, it works in Baker. ;)

For 3D, given this review:
http://caniuse.com/webgl

WebGL is not yet supported. Sorry.
