### ISSUE TITLE
Loading new page shows cached/screenshot page

### ISSUE THREAD

**Issue by simondelacourt** [Simbul/baker#506]
Just started working with Baker, and Laker. But there is this strange thing that happens when I swipe to the next page, I see for a brief moment an old version of the HTML page that was there. It somehow doesn't help to clean or fully clean the build folder, nor removing Safari cache. Nothing seems to change it. 

I'm working with 3.2, XCode 4.5, and the iPad 6.0 simulator.

**Comment by folletto** [comment]
Try deleting the app from the simulator/device. It's likely the automatically-generated screenshot, that is generated only once and stored. Switch to three-cards mode in the `book.json` while you work. ;)

**Comment by folletto** [comment]
Hello, were you able to solve this? :)

**Comment by drking0211** [comment]
I have this problem also using 4.0 and the shelf.

I am getting screenshots for a brief moment from other publications which have previously rendered.

Tried altering the name structures of the HTML files so they are uniquely different but that did not work.

Any ideas?

dk

**Comment by folletto** [comment]
As commented above: did you try deleting the application from the simulator/device? Once created the old screenshot stays there until you delete the app, cleaning and compiling have nothing to do with it. :)

**Comment by drking0211** [comment]
Yes.   Deleted the app from the device and restarted the device.

First book renders okay and then subsequent books show previous caches before the Webview renders the correct page.

Am trying to debug this now.

dk

**Comment by drking0211** [comment]
Managed to get around this problem.

I had two publications with pages titled 1.html, 2.html, 3.html and so on.

I renamed the first publication pages with prefix a1.html, a2.html, a3.html etc

And now working fine. 

Hope to get this up to the App Store during this month so will report back with Apple's response.

Regards

dk

**Comment by Simbul** [comment]
@drking0211 that's weird. I've tested it now but cannot reproduce it.

I'm glad you found a workaround, but that shouldn't be needed in the first place, so I hope you won't mind a couple more questions.

First of all, when you cleaned up the app, did you follow the instructions in the [Proper cleanup](https://github.com/Simbul/baker/wiki/Proper-cleanup) page?

Second, are you sure your books have different names in your [shelf JSON](https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON)? I'm referring specifically to the `name` attribute, which is what Baker uses to create the screenshot folders.

**Comment by drking0211** [comment]
Hi there,

Yes did a proper clean-up and the names in the shelf.json are unique.

I have been working on an Android port for Baker for the past week or so and will be looking at IOS later this week and will report back.

Regards

David

**Comment by folletto** [comment]
We weren't able to replicate it without having the publications causing the issue, so we are stuck. Do you have any way for us to replicate the problem you are having?

**Comment by nin9creative** [comment]
Are you guys adding multiple publications to your shelf for testing with the same names?  I noticed this behavior when I duplicated the name of the publication on accident when testing...  As @simbul mentioned above the code uses that to create the screenshot folders...

**Comment by drking0211** [comment]
Sorry ben tied up with Android woes.  If you think IOS is a maze.... 

I will do some testing again later this week with the shelf and use a virgin install.

Thanks for the feedback so far.

Regards

David

**Comment by folletto** [comment]
Hello, did you check this? :)

**Comment by Simbul** [comment]
Closing as the issue has gone stale. Please feel free to reopen if you have new info to add.

**Comment by black-orca** [comment]
Hi, I'm having the same trouble. I'm using baker 4.0. I think it's because the in5 output which I'm using. The output for Baker format always named 0001.html - 00xx.html. Before I was using in5, I have my pages named differently. But now since in5 named it, my second issue from the in5 is having the exact trouble. I haven't try to rename all the files like drking0211 said yet. While searching for the answer, I found issue #506 

I'll get back to you if renaming the files solved the issue.

**Comment by black-orca** [comment]
Hi,

I tried to rename all the files ini the book folder, and re-upload the hpub. I tried to archive the issue and download it again, but the problem persist. I don't know what happened. I think it's a big deal. I start receiving complaints about it. Does anybody has the solution?

thx.

**Comment by sgkalyans** [comment]
Try to change the URL value in book.json 

From iPhone

**Comment by simondelacourt** [comment]
I've never been able to really fix this, and I switched to Cordova to work my way around caching problems. To me it seems that the webkit caching engine is the reason why this bug appears. I've changed any value possible before, and none led to to a solution.

**Comment by folletto** [comment]
Yes, there's a "content flashing" issue triggered by `UIWebView`. Unfortunately that's all up to Apple to solve.

But there are two things that trigger the behaviour described above: Baker does page screenshots in the screenshot mode and these screenshots get deleted only if there's a low-space warning or if the app is completely deleted from the device and then reinstalled.

Takes some skill to distinguish the two, but in general if you totally removed the app and the issue is still there it's likely it's the `UIWebView` issue.
