### ISSUE TITLE
Rendering issues in Xcode 4.5

### ISSUE THREAD

**Issue by cipnt** [Simbul/baker#508]
Hi guys,
Anybody else getting weird results running Baker with Xcode 4.5?
Things like:
- contents menu displayed in viewable area and double tapping just repositions it.
- orientation won't change
- unable to scroll the entire width of the document

I tried the provided HPub example and the book that I'm working on. 

One more thing - how do we enable the new 4" screen resolution of the iPhone 5? :)

Thanks

**Comment by folletto** [comment]
Did you already try this?
https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue

**Comment by cipnt** [comment]
Yes, I did. 
I noticed the rendering problems occur only when the app is launched in landscape orientation.
But even when launched in portrait it will not change orientation
I used a clean Baker 3.2 download with a clean HPub book provided as example
Any suggestions? Is anybody else using Xcode version 4.5.1 (4G1004)?

**Comment by folletto** [comment]
Ok. But: does the same problem appear on MASTER? :)

**Comment by cipnt** [comment]
I downloaded it from http://bakerframework.com/down/baker-framework-3.2.zip and didn't change anything at all... 
I din't get if from git

**Comment by folletto** [comment]
Ok: try MASTER then. :)
Because if it's fixed there then we just have to release it, if it's not fixed there then we will have to find the problem and fix it. ;)

**Comment by cipnt** [comment]
Fixed! It fills the 4" screen too. :) Cheers!

**Comment by folletto** [comment]
You're welcome. :)
