### ISSUE TITLE
How to chnage app icon?

### ISSUE THREAD

**Issue by rahuxx** [Simbul/baker#509]
I made an ebook with using baker framework but not able to change app icon.plz help.

Thanks in advance.

**Comment by folletto** [comment]
It's simple. :)

Just update the PNG files inside the "icon" folder: :)
https://github.com/Simbul/baker/tree/master/icon

**Comment by folletto** [comment]
Hi! Did you manage to do this? ;)

**Comment by Simbul** [comment]
Closing, as the issue's gone stale.
