### ISSUE TITLE
Swipe movement crash

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#51]
Hi everyone,

I encountered a problem that causes the "swipe" moves to stop working. I think it is related to the use of internal links.

How I can I provide more information to detect what caused the problem?

Thanks!

**Comment by folletto** [comment]
Hello and thanks! ;)
1. Baker 1.0 or 1.1?
2. In the title you say "crash", does the app crash?
3. When it happens, it's just once, or from that moment on is broken even on taps?
4. Could you provide a simple, barebones, html page that breaks it and the steps to reproduce it?
5. If not, could you film yourself doing that, explaining the problem at the same time?

This might help. ;)

**Comment by frantovar** [comment]
Hi Davide,
1. Baker 1.1
2. Sorry for my "Google English" ... simply stops working swipe movement, the app still works.
3. The taps are still running.
4. I can pass you by mail a sample of our book ;)
5. Try to spend a video, do you I can send it by email?

Keep in touch!

**Comment by Simbul** [comment]
Fix: clicking on a link and then changing page via tap caused swipe to stop working. Closed by 738754ab8d571c6d31c0743e442901b9fdb42bba

**Comment by Simbul** [comment]
Thanks for pointing this out. Let us know if this solves the issue for you and in case you bump into more of them :)

**Comment by frantovar** [comment]
Works fine! thanks a lot!
