### ISSUE TITLE
Vertical tap disabling?

### ISSUE THREAD

**Issue by Issean** [Simbul/baker#512]
Hello,

how can I disable tap  for vertical scrolling on the top and on the bottom of the page? 

If i double-tap on the bottom of the first part of my long html page  { position:absolute; top:0px; left:0px; width:768px; height:1024px;}   in order to open the index bar, it scrolls automatically to the second part  { position:absolute; top:1024px; left:0px; width:768px; height:1024px;}. So i would like to disable this one-touch-tap. Vertical swiping & arrow navigation are enough for me:)

Thx!

**Comment by folletto** [comment]
Hi @Issean! 
There's no builtin way to do that, you need to check the function `- (void)userDidTap:(UITouch *)touch` and remove the part you don't want to use. :)

**Comment by Issean** [comment]
Thanks a lot!
Removed this part from RootViewController - and everything works fine.

By the way, I am not sure if I should open a new thread for the next two questions. So I just asked here..

1). Is there a way to make a FB-Share like popup or iframe?
2). I want my magazine prove the internet connection after click on the button (to the page with embedded youtube-videos.) So I could implement a popup window with something like "there is no connection. Check you wifi". How can I do that?

Thanks in advance.

PS Baker rules. Thx to the developers of this framework. Saved me a lot of time.

**Comment by folletto** [comment]
You should open a different issue, yes. However in this case the answer is kinda quick and also... non Baker related: in both the cases the answer is: yes, as you would normally do with HTML5. So it's some custom coding you will have to do with JavaScript, we can't support much on that, but I'm sure you'll be able to find sources online. :)

You're welcome! :)
