### ISSUE TITLE
Statusbar highlight current chapter

### ISSUE THREAD

**Issue by Wolfred** [Simbul/baker#515]
Hello,

Is there a possibility to not just pop up the status bar, but have it highlighting your current page. Preferably also at the position you're in the book so, if you're at chapter 7, then the first chapter displayed in the status bar would be chapter 7. 

Thanks!

**Comment by folletto** [comment]
It's not there yet, but it's part of the feature #350, where we will provide that kind of information in javascript so you can just read that information and update the index accordingly. :)

**Comment by Wolfred** [comment]
ok. thanks!

**Comment by folletto** [comment]
You're welcome! :)
