### ISSUE TITLE
Tumult Hype support: javascript-transitions not working

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#518]
hi there!
i build html5 using hype. hype recommend on their website to use baker for itunes-store - so far.
but transitions doesn´t work, when i export to baker from hype since ios6 and xcode 4.5. 
so i wrote to support and got this answer:

"The framework you're using is not reporting itself as a WebKit-based User-Agent and, thus, Hype will not animate the scene transitions. Scene transitions are only supported on browsers that report themselves as being WebKit-based and on the latest FireFox releases. Whomever wrote the framework you're using will need to change their custom User-Agent string so that it includes something along the lines of "AppleWebKit/536.26.14".

how do i change this lines and what exactly do i have to do?? does anyone know that? thanx a lot for help.
regards
strmiska

**Comment by folletto** [comment]
Thanks, that's a very valuable information! We'll review it. :)

You should be able to implement it yourself easily, check the file `BakerAppDelegate.m` and check the `initialize` function. :)

**Comment by hitchio** [comment]
hi!
i´m no programmer, but i think i did the right thing: changed @userAgent to @AppleWebKit/536.26.14 - it works!! ;-)

```
// Set user agent (the only problem is that we can't modify the User-Agent later in the program)
+ (void)initialize {
    NSDictionary *userAgent = [[NSDictionary alloc] initWithObjectsAndKeys:@"BakerFramework", @"AppleWebKit/536.26.14", nil];
    [[NSUserDefaults standardUserDefaults] registerDefaults:userAgent];
    [userAgent release];
}
```

**Comment by folletto** [comment]
Ok, it's in Baker now! Hype should work out of the box now. :)
Thanks. :)

**Comment by hitchio** [comment]
you´re welcome!

**Comment by hitchio** [comment]
hello foiletto!
i downloaded your zip - there´s a problem with width of the index.html in the book.json. 
if i set "orientation": "both" - all works fine. but as soon as i set: "orientation": "landscape",
the index.html on double-click doesn´t appear. only on "-baker-index-height": 356, it comes up and is cutted at the end.
it seemed to be that the index.html doesn´t turn into landscape-modus.
i tried with your zip-original. the same issue there.

is there something to change?

thanx-h.

**Comment by folletto** [comment]
Yes: it just means that the HTML needs to properly set its width, something that the default book doesn't do because uses floats. Make sure that the objects inside the HTML (the window and body) have dimensions and they are correct.

However, please create a separate issue if you need support that isn't related to this one. ;)
