### ISSUE TITLE
zoom in the webview

### ISSUE THREAD

**Issue by alpertayfun** [Simbul/baker#52]
Hello,

I'm using Baker Framework. I have a question. How can i zoom and pinch current webview ?

**Comment by folletto** [comment]
Zooming and pinching is possible, see on RootViewController.m:

`#define PAGE_ZOOM_GESTURE NO`

However, please try to avoid it and use javascript instead to make zoomable only the parts you really need to, because zooming and pinching interfere with the "book" interaction model. It also makes the creation of a book way more complex.

**Comment by alpertayfun** [comment]
Just like :

[webView stringByEvaluatingJavaScriptFromString:@"document.body.style.zoom = 5.0;"];

?

**Comment by alpertayfun** [comment]
And i have an another question. How can i add toolbar ? 

Example :
- (void)viewDidLoad {
  
  // Implement viewDidLoad to do additional setup after loading the view, typically from a nib.
  
  [super viewDidLoad];
  [self loadSlot:0 withPage:currentPageNumber];
  
  // *****\* TAPPABLE AREAS
  upTapArea = CGRectMake(50, 0, 668, 50);
  downTapArea = CGRectMake(50,974,668,50);
  leftTapArea = CGRectMake(0,50,50,924);
  rightTapArea = CGRectMake(718,50,50,924);
  NSLog(@"cpo : %d",currentPageNumber);
  
  UIToolbar *mytoolbar = [UIToolbar new];
  mytoolbar.barStyle = UIBarStyleBlackOpaque;
  [mytoolbar sizeToFit];
  mytoolbar.frame = CGRectMake(0, 0, 768, 50);
  
  UIBarButtonItem *icerik = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"icerik.png"] style:UIBarButtonItemStylePlain target:self action:@selector(icerik_clicked:)];
  UIBarButtonItem *logo = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"logo.png"] style:UIBarButtonItemStylePlain target:self action:@selector(logo_clicked:)];
  
  UIBarButtonItem *flexItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:self action:nil];
  flexItem.width = 450;
  
  UIBarButtonItem *flexItem1 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:self action:nil];
  flexItem1.width = 120;
  
  UIBarButtonItem *bookmark = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"online.png"] style:UIBarButtonItemStylePlain target:self action:@selector(bookmark_clicked:)];
  [mytoolbar setItems:[NSArray arrayWithObjects:icerik,flexItem,logo,flexItem1,bookmark, nil]];
  [self.view insertSubview:mytoolbar atIndex:1];
  [icerik release];
  [logo release];
  [flexItem release];
  [flexItem1 release];
  [bookmark release];
  [mytoolbar release];
  }

But, i don't see any toolbar..

**Comment by folletto** [comment]
These are more iOS SDK questions: you'll probably find better answers on a iPhone development forum or Stackoverflow. ;)

**Comment by alpertayfun** [comment]
All right :) But there is problem for the zooming. Because i'm using only jpg file on the uiwebview. " scalesPageToFit " function resize my image. i don't want it.

**Comment by folletto** [comment]
That's exactly what I was referring before with "It also makes the creation of a book way more complex." :D

Try adding the HTML/iPhone headers with a set zoom in the header, it might help. :)

**Comment by alpertayfun** [comment]
All right I'm idiot :D

BTW, I did the navigation with thumbviews. Do you want it?

**Comment by folletto** [comment]
Send it to us (or link from Github) only if you agree to allow us to add it to the Baker codebase if it suits the plans for it, because otherwise it will just block us to use a similar implementation due to possible license violations. ;)
