### ISSUE TITLE
Releasing new issues.

### ISSUE THREAD

**Issue by benharker** [Simbul/baker#522]
Hello. I have recently came across this framework and it looks really good! I can not wait to use it.

I am wanting to create a magazine that has monthly issues. I am just wondering how would I go about releasing the new issues?

Would I just have to send out an update via the app store for people to download the latest issue? and possibly integrate a push notification system to alert readers of the latest issue. 

Or is there a way to do this via a different source for the issues to just update itself? 

Thanks for the advice!

**Comment by nin9creative** [comment]
For the new issues being released there is a .json file that you host on your own website that determines what your app will load in the shelf.  For full newsstand support there is a way to implement push notifications with background downloading for the app.  I don't think the shelf branch supports that right now - and I don't know if it's in scope for the 4.0 milestone or not.

**Comment by folletto** [comment]
Right now, Baekr 3.2.2 doesn't have support for the shelf / multi-issue yet.
Baker 4.0 will have, but it's still not complete. You can check the progress in the branch `shelf` and in the issue #100 (plus the Milestone 4.0 always here on GitHub). :)
