### ISSUE TITLE
ModalViewController - access to Storyboard or XIB file? 

### ISSUE THREAD

**Issue by CatherineEng** [Simbul/baker#523]
Hi - this pertains to the wonderful contribution from @Steiny2k: https://github.com/Simbul/baker/pull/325

Where can I find the XIB file or access to the storyboard for ModalViewController.m? I would like to remove the Safari button for a particular app I'm doing. Although I can see how it would be useful in many cases, the one popup modal is just perfect for the particular app I'm doing. I actually commented out the Safari element in the .h file and .m file, so the button doesn't click through, but then it doesn't need to be there. 

Curious also - the button does not actually appear if you open a web view in landscape mode. Only in portrait, but I'm sure you are aware of that.

Thanks in advance.

**Comment by folletto** [comment]
Hi. :)

There's no XIB, everything is built in code because we needed more flexibility and control. That button is generated in `ModalViewController.m` in the `loadView` function. Check the `*btnAction` variable.

—

If it doesn't appear in landscape mode it's a bug. Thanks for the pointer. :)

**Comment by Simbul** [comment]
Hi @CatherineEng,
I can see the button just fine with the latest version from `master`. Can you elaborate a bit on that bug?

![Safari button](http://d.pr/i/F7Ym+)

**Comment by CatherineEng** [comment]
Hi Alessandro,

The issue wasn't that I could not see the Safari button - it's that I could see it, and wanted to somehow remove it. We have since removed it based on @Folletto's instructions, so there is just the Back button (which we renamed Done) and the back / forward arrows. 

```
( Oh - you mean the landscape bug issue. Let me see if I can find a screenshot of it not appearing in landscape mode...)
```

Really enjoying working with Baker. You guys have created something amazing. Can't wait to show you our application. If you are interested, please PM me your UDID - you and @Folletto both. Thanks again.

Best,
Catherine

**Comment by folletto** [comment]
Hi @CatherineEng, do you have any update? :)
