### ISSUE TITLE
no index.html in book.json "landscape"

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#524]
hi!
i got a problem in 3.2.2, downloaded from bakers. 
please see video for better declaration before:

https://dl.dropbox.com/u/22409460/bakers_landscape-bug.mp4

if i set "orientation": "both" - all works fine. but as soon as i set: "orientation": "landscape", the index.html on double-click doesn´t appear. only on "-baker-index-height": 356, it comes up and is cutted at the end.
it seemed to be that the index.html doesn´t turn into landscape-modus.
i tried with your zip-original. the same issue there.

any help appreciated - thank you!

**Comment by bober80** [comment]
Yes, I have the same issue. But I'm using index.html created with Laker

**Comment by hitchio** [comment]
how does this work?
can you please give an example?

**Comment by hitchio** [comment]
just tried with laker - same issue! there must be something wrong in programming.

**Comment by hitchio** [comment]
any help appreciated! is there a solution to solve this problem yet?
thanx

**Comment by hitchio** [comment]
installed xcode 4.5.2 today - problem solved, but don´t know why ;_)
