### ISSUE TITLE
I just want the html app not the iphone app do I need to do step 3 ?

### ISSUE THREAD

**Issue by landed1** [Simbul/baker#526]
Is it possible to just end up with an html application without packaging up with phonegap.

So kind of like just using css html and js running within a browser. I am looking to make a magazine with images for each page. Is this something which is well made using baker. I know from experience that I dont want to do the time consuming packaging for iphone nor do I want to pay to be an apple developer.
thanks

**Comment by folletto** [comment]
No I'm sorry, it's not what Baker is for... you should probably build yourself the javascript required to emulate that, or look for an existing pure JS library.

**Comment by landed1** [comment]
But doesn't it use html and js i.e. this is not an objective C build. I see that Laker may be more what I need but it supposedly uses baker so I wanted to get as few wrappers as possible.

**Comment by folletto** [comment]
Baker is a Objective-C wrapper that allows you to use HTML/CSS to create a iOS App, while Laker is a magazine template carefully designed for Baker. 

Hpub is a HTML/CSS package, but it's designed to run inside a wrapper and Baker is the default implementation. :)
