### ISSUE TITLE
High Bandwidth Issue Hosting

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#531]
Has anyone done any good research for high volume and bandwidth hosting for issues?  I have seen a lot of the bigger outfits use AWS S3, but it can get pretty pricey....

**Comment by tstegart** [comment]
Try looking into Parse (https://www.parse.com/plans). It appears you can host your issues (if they're under 1GB) and get 1,000,000 downloads for free. Might need a little extra work to get it working though.

**Comment by nin9creative** [comment]
Hmm, will need to look into that.  Ideally I would like to find a decent host with a large bandwidth allowance for files.  I'm not sure, but I have a feeling that a lot of folks will run into a similar issue if they start publishing heavy media laden magazines with the BakerShelf.  I'll try to do some more research.

**Comment by Simbul** [comment]
Have you tried getting in touch with the authors of some of the published Baker magazine that already have a shelf?
There's at least a couple of them in our showcase, and I believe one was based on your fork.

**Comment by nin9creative** [comment]
I do know that I had a few people ask me about it before because their bandwidth was getting eaten up quickly :)

**Comment by nin9creative** [comment]
Ok, so I talked to a few different people...  It seems that some are trying to use hosts that have "unlimited" bandwidth as part of their offering.  Hostgator, Bluehost etc...  However I think it's a fine line before those types of hosts might catch on to the potential high bandwidth issues (with bundled video etc) that might occur.

Someone else turned me on to 100TB.com hosting accounts.  On the higher end they offer dedicated servers at a somewhat reasonable cost (if you are actually making money on the magazines or hosting them for someone you can charge).  I spec'ed out a pretty nice server that includes 100TB of premium bandwidth for about $250 per month. 

The nice thing is that they also have a shared server hosting plan (which is all you'd need for hosting issues and newsstand content) that starts off at $20 / node per month.  Each node gives you 10GB of disk space and 1TB of bandwidth.  You can also adjust that up over time by adding nodes if you require it for your app.

https://www.100tb.com/cloud-servers/

I think that for me I will try using something like Hostgator and see if I run into any issues.  If I do, I'll switch to 100TB.com with their cloud based offering at the lowest end and go from there.

Sounds like a plan for me at least :)

FYI - I have no affiliation whatsoever with any of these.  Just thought I'd pass along what I dug up.

**Comment by nin9creative** [comment]
Scratch the Hostgator idea.  Hosting files for serving up to an iPad is against their Terms of Service (chatted with a customer service rep).  Also, their download speeds are SLOW.  I tried downloading a 150mb hpub and was only getting around 100kbs.  Not very fast at all.

**Comment by nonuts** [comment]
I was using dropbox so far. paid accounts allow for 200 GB/day - enough for me  I guess.

**Comment by folletto** [comment]
I'm closing this since the discussion seems done. :)

The summary I get from the discussion, if someone read this thread at a later time, is that:
- Hostgator — Doing that is against their ToS and really slow.
- Dropbox — Seems working but limited to 200 Gb/day
- 100tb.com — Seems ok
- AWS — Is ok, but check the costs first for both bandwidth and storage
