### ISSUE TITLE
Idea for Shelf Layout - Newsstand

### ISSUE THREAD

**Issue by cfocoder** [Simbul/baker#532]
Hi guys,

This is a proposal of an idea of the layout. I know the idea is to keep it simple for first round, but I thought I'd share with you a layout that I like. You can check a screenshot here:

http://gurulik.com/la%20foto.JPG

I think the layout is not that complicated but I like it because it makes subscriptions very prominent at the top. I think selling a subscription is more important than selling a single issue, as it helps publishers to earn recurring revenue over time.

The layout also features a "Private" issue, which is an issue that can only be read if reader is a subscriber.

Just my 2 cents.... 

Keep up the great work!

Regards
Hector

**Comment by folletto** [comment]
Even if it doesn't seem like it, it's a huge rework from the current structure. We won't be able to do it in the next version, but we'll keep the suggestion open as a feature request. :)

**Comment by folletto** [comment]
I'm closing this since we jus released version 4.1. Please open a new issue if this is still relevant. :)
