### ISSUE TITLE
Orientation Change Issue

### ISSUE THREAD

**Issue by thejtate** [Simbul/baker#534]
Had a question over Baker when you change the orientation on the iPad (iOS6). Whenever I do, I can see a white background for a second while my page then expands to fit the screen. Does this on the Simulator as well (iOS5, iOS5.1, 6) running xCode 4.5 with Baker 3.2.2.

Wasn't sure how to fix this, tried using  "-baker-background": "#000000". I figure it might be a simple fix that i'm just not seeing?

I noticed on the Baker example Urbanic that it seems to have a more fluid 'spin' to it. Basically what I'm aiming for. 

Thanks! Hopefully that all makes sense.

**Comment by folletto** [comment]
Which version of Baker are you using?

That said, check if a different HTML page (completely different) does that as well...

**Comment by thejtate** [comment]
Using Baker 3.2.2. I loaded up the example Book it comes with and it seems that does it as well. 

Could it have anything to do with the meta information? 

 <meta name="viewport" content="width=768; initial-scale=1.0;"/>

**Comment by folletto** [comment]
Nope. But we changed the code. You might try to go back to older Baker versions and see if it does that as well: I'm not sure if it's something we changed or something Apple changed...

**Comment by thejtate** [comment]
I loaded Baker 3.1 and it still seemed to do it (don't want to go any lower than that). So odd.

I tried stripping out all the CSS and just have a simple image loading on the page using media queries to load the size depending on if it's portrait or landscape. But I can still see a lag time when the orientation changes and the images has to take a second to resize. Does the same thing if it's just a div or the body tag. 

I'm use to using a responsive grid format for site design (stuck with Skeleton) but a big question I have is:

Is it common practice to have ALL styles nested in the CSS media queries for iPad/iPhone development or just have a typical responsive CSS setup? 

Edit: I am curious if I need to just load Javascript to handle the orientation change instead of having CSS do so.

**Comment by folletto** [comment]
JavaScript shouldn't be needed at all. However, this is still weird... are you able to upload a video on YouTube so we can see what's happening on your device? :)

**Comment by thejtate** [comment]
Yeah, that's what I would figure. It acts like my CSS takes a bit to 'kick in' when it reads the current devices screen resolution. 

Here is the video: https://vimeo.com/53901289

**Comment by folletto** [comment]
Uhm... indeed, my first guess seeing that would be similar to yours: the CSS media-query kicks just after the rotation completes.

**Comment by thejtate** [comment]
Looking into possibly doing some sort of preloader that will let the entire page load before displaying anything upon orientation change. Seen a few others do this with Baker, seems like a good quick fix. 

I checked out Laker's book example and it does the same thing. Surprised not anyone else has really been bugged by this. 

Edit: Where could I grab later builds of Baker? Like to give those a shot, might as well.

**Comment by danielreiser** [comment]
Well that's the exact problem I am facing right now. And it's bothering me a lot! I think the mediaquery fires just to late so that's causing the delay.

So I'll investigate that :)

**Comment by danielreiser** [comment]
So I checked the code. Problem is that `updateBookLayout` gets called after the view did rotate. That's causing the delay. But that's not all of it. There's one problem as well that has to be investigated. I'll try to fix that and post a pull request shortly.

**Comment by thejtate** [comment]
@danielreiser Sweet, sounds good. Thanks again!

**Comment by danielreiser** [comment]
Rotation in the current branch looks pretty good. I don't think we need any further improvement here. What do you think?

**Comment by thejtate** [comment]
Great! I'll port over my changes and check it out later today. 

Edit: Seems to work a lot better. Still does a funky animation jerk but the CSS does load fast enough.

**Comment by Simbul** [comment]
Closing as this would seem to have been solved - and the discussion is quite dated anyway. Feel free to reopen if you need it.
