### ISSUE TITLE
Support Retina Issue Cover Images

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#538]
Right now the cover images only support standard non retina resolution.  Trying to use retina resolution images also doesn't work as the app seems to somehow scale and mess up the image even when sized correctly.

**Comment by folletto** [comment]
Thanks @nin9creative  :)

**Comment by nin9creative** [comment]
I did a little more digging on this.  I believe that this line is the culprit.  I have made some changes to add another cover url to the JSON file on my fork in case someone wanted to have a different cover for the retina version vs the non retina version.  But commenting out this line fixes the issue of the retina version being messed up.  It looks super sharp on my iPad 3.

Under the Setup Cover Image in `IssueViewController.m`

```
issueCover.layer.shouldRasterize = YES;
```

![Retina Covers](http://www.bakershelf.com/screenshots/ShelfScreenshot3.png)

**Comment by folletto** [comment]
And that fixes everything with no drawback? That's awesome! Great job. :D

**Comment by nin9creative** [comment]
I'm trying to test a few different scenarios...  Not sure why it was there in the first place?  There must have been a reason?

**Comment by nin9creative** [comment]
Ah, I got it.  Did some more research.  I guess since you guys were adding a layer to the issueCover image to add the shadow, you were rasterizing the image to probably speed up things.  It looks like otherwise the processor would have to do some more work to keep up with the shadow if orientation changed / items were in a scroll list or whatnot.

However adding another bit of code right after the shouldRasterize option fixes the problem as well....

```
    issueCover.layer.shouldRasterize = YES;
    issueCover.layer.rasterizationScale = [UIScreen mainScreen].scale;
```

**Comment by folletto** [comment]
You got it correctly: optimization. 
Well... very good digging indeed, keeping `shouldRasterize` and fixing that with scale is even better. :)

**Comment by nin9creative** [comment]
One thing I haven't tested is whether or not just using one cover image would work in all cases.  For example, just setting the cover image to a larger retina sized image - would that work ok on non retina screens.  I'll have to test that.  If it doesn't, I've already done some coding to allow for both a retina and non retina version of the cover to be specified by the issue list.  On the cover download, the device determines which version to pull based on a test if it's a retina device or not.

**Comment by nin9creative** [comment]
Well, it looks like if you just upload a retina version of the image as the Cover, it works ok on a non retina device, and it works on the retina device.

The simplest fix for this whole issue then would be to create some documentation around what sizes a developer should use if they want to also support retina devices and then let the device scale the image down as needed.

Unless there would ever be a need to support two different versions of the cover (the published wanted something different to show up for retina vs non retina) then the addition of the rasterizationScale line of code would work.

**Comment by Simbul** [comment]
Great job fixing this!

I think we should suggest developers always provide the hi-resolution version and Baker scales it down when needed.
This seems to be the approach that Apple is taking on their guidelines and it's much more linear.

**Comment by folletto** [comment]
I agree. 
I think that right now for simplicity reasons it's better the approach you suggested: one image, scaled. :)
We can think about the alternative in a future version, if it's required. MVP. ;)

The ideal resolution should be double the standard px size, 135x180px = 270x360px (retina). :)

**Comment by nin9creative** [comment]
Sounds good.
