### ISSUE TITLE
Confirmation popup on click of Archive button?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#539]
Since archiving is a permanent delete of the downloaded issue, perhaps we should confirm the deletion with the user via a popup message.  It's easy to mistakenly hit archive instead of read.  Since redownloading is a potential expensive task in terms of bandwidth/time it might make sense to prompt first....

**Comment by folletto** [comment]
Good point. I think it's relevant, and I agree with you. It should be in 4.0. :)

**Comment by nin9creative** [comment]
I submitted a pull request for this change.

![Screenshot](http://www.bakershelf.com/screenshots/ArchiveConfirm.png)

**Comment by Simbul** [comment]
Pull request #540 has been merged in. Thanks for the contribution @nin9creative!

**Comment by folletto** [comment]
Wonderful. :)
