### ISSUE TITLE
loading page delete

### ISSUE THREAD

**Issue by alpertayfun** [Simbul/baker#54]
i just want to delete loading page.

**Comment by folletto** [comment]
You have to dig inside the code and remove it by hand, however I advise you to not do that, since you're removing an important feedback for your readers.

**Comment by alpertayfun** [comment]
All right. I just want to users dont see scrollViewDidEndDecelerating white pages..

**Comment by folletto** [comment]
The loading is there exactly because we can't avoid it. See #27
