### ISSUE TITLE
Deployment Target?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#548]
Shouldn't the deployment target be set for a minimum of iOS 5?  None of the newsstand stuff will work on devices that aren't at least on iOS 5.

**Comment by tstegart** [comment]
Yes, it needs to be 5.0 or above. Does anyone know if it needs to be higher than that? Did you guys use any 6.0-only features? It would be nice if 5.0 was still available as that makes iPad 1 an option.

**Comment by nin9creative** [comment]
Am I wrong that the current Baker master has a target of 4.3?

**Comment by tstegart** [comment]
No, I think you're right. It should probably be changed to 5.0 otherwise it will be rejected from the app store. The Baker shelf version probably still uses 4.3, but I would argue we should set the default at 5.0 and let those that wish to support the lower OS set it on their own.

**Comment by Xm4s** [comment]
You are both right, thanks for pointing out the version mistake :)
The Baker Shelf version without newsstand should works on iOS 4.3+ devices, but since newsstand require iOS 5+ we'll raise the deployment target to that.
Those who wish to support lower version of iOS we'll be responsible to set the correct target.

**Comment by Xm4s** [comment]
Closed with 3a794f3f9abe691510b547c2aa418f93c701e6a1

**Comment by tstegart** [comment]
When I open the Baker master in Xcode it still shows up with a deployment target of 4.3.

**Comment by Xm4s** [comment]
Sorry, my fault.
I raised the deployment target in Baker project settings but not in Baker target settings :)
Re-Closed with 7224ace839ff4c5bcfac5384347fb6054390345e
