### ISSUE TITLE
Setting Up and Testing 4.0

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#549]
I need some help. I'm setting up and testing Bakershelf 4.0. When I run the app to test it is crashing on me with this error:

2012-11-26 13:22:59.221 Magazine[4872:c07] ====== Newsstand is enabled ======
2012-11-26 13:22:59.420 Magazine[4872:c07] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x95358e0
2012-11-26 13:22:59.420 Magazine[4872:c07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x95358e0'
**\* First throw call stack:
(0x1cf9012 0x16a8e7e 0x1d844bd 0x1ce8bbc 0x1ce894e 0x623e0 0x61df2 0x2852 0x2ee7b7 0x2eeda7 0x2effab 0x301315 0x30224b 0x2f3cf8 0x298bdf9 0x298bad0 0x1c6ebf5 0x1c6e962 0x1c9fbb6 0x1c9ef44 0x1c9ee1b 0x2ef7da 0x2f165c 0x2472 0x23a5)
libc++abi.dylib: terminate called throwing an exception
(lldb) 

It appears to me that it is my connection to my shelf JSON. When I remove that URL it runs fine with the filler content. I can't figure out if it is my JSON file or the connection to the server. My JSON file is set up according to the wiki.  I have no problems accessing the file putting the URL in a web browser. And our official IT guy doesn't know web stuff.
Any ideas?
Thanks.

**Comment by folletto** [comment]
Thanks, we'll check, meanwhile:

Can you access the JSON file from your browser?

**Comment by nin9creative** [comment]
Is the JSON formatted correctly?

Try checking it out here....

http://jsonlint.com/
http://jsonformatter.curiousconcept.com/

**Comment by ghost** [comment]
Yes but it immediately downloads it.

**Comment by nin9creative** [comment]
Try running it through the JSONLINT tool above to check what the output looks like.

**Comment by ghost** [comment]
@nin9creative It validates at both sites

**Comment by Simbul** [comment]
What happens if you point it to our test JSON?

http://bakerframework.com/newsstand-books/list.json

We've used that multiple times, so it could help rule out one possible issue.

**Comment by drking0211** [comment]
Not sure whether this is the same problem but using the JSON example in the WIKI documentation you will note there is an additional comma at the closing of the second publication definition followed by  "...".

I removed the "..." as this is clearly an i.e statement but missed the second comma definition and had similar problems.

Once I removed it everything worked fine. 

Also noticed that the old book.json file has changed with the new 4.0 and points to a new GFX directory which also caused XCODE to crash on my existing publications. 

So using the example json file from the Scarlett book I made changes to my existing json and added the new directory and Hey presto it all worked.

Hope that is of some help.

**Comment by Simbul** [comment]
I've removed the comma from [the example](https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON), as I agree it's a bit misleading.

The `gfx` folder is nothing new: it has always been there, as far as I can remember. In any case, that's not part of the `book.json` specification: it's simply something we decided to have in our sample book, but nothing prevents you from calling it `foo` or even storing all the files in the root folder.

What has changed with 4.0 is we went from a single `book` folder to a `books` folder containing multiple books, but the structure of the single book is still the same.

**Comment by ghost** [comment]
With your comments I got the app to run and download my magazine. 

For those who are looking back, it was my JSON file, it was missing some brackets. Pointing it to the test JSON helped thank you @Simbul 

My next issue is when I try to read the magazine I'm getting the Path to the index view is (null). Is there a change to the hpub setup for 4.0 that I am missing? One thing I did notice is the book protocol isn't supported by 4.0 you are to use 3.2.x instead. If that is the case what should I use? 

In my set I added one of the baker sample books to my list to help me with testing, so that is showing up too. It downloads and reads okay. I am unable to see how that hpub file is set up. I look at the sample book that downloads with the 4.0 framework. My set up is the same and the JSON file is the same.
Not sure what I'm missing.
any ideas?

If this should have a new issue opened, let me know. My thought is once I get this up and running to help put together instruction and/or give feedback. I am taking notes of my experience.
Thanks again everyone.

**Comment by nin9creative** [comment]
You can download the book by pasting the URL in your browser.  Rename it to .zip, unzip, and inspect the contents.

**Comment by ghost** [comment]
I checked my magazine with the downloaded Baker sample. They look the same too.

It is showing my book is downloading and unzipping to the cache. Then when I try to read/view it it says there is no directory:
...
2012-11-27 11:03:02.542 Magazine[5564:c07] Connection did finish downloading file://localhost/Users/darrenrettburg/Library/Application%20Support/iPhone%20Simulator/6.0/Applications/2F372FBF-1CEE-4992-B784-613DE701A302/Library/Caches/bgdl-5564-2c43e1137150dc8f.hpub
2012-11-27 11:03:02.543 Magazine[5564:c07] File is being unzipped to /Users/darrenrettburg/Library/Application Support/iPhone Simulator/6.0/Applications/2F372FBF-1CEE-4992-B784-613DE701A302/Library/Caches/Newsstand/EAEF95D3-019B-4E77-A4FF-855525BC0BC8
2012-11-27 11:03:03.068 Magazine[5564:c07] Refreshing 001magalog view with status downloaded
2012-11-27 11:04:00.232 Magazine[5564:c07] Refreshing 001magalog view with status opening
2012-11-27 11:04:00.233 Magazine[5564:c07] • INIT
2012-11-27 11:04:00.233 Magazine[5564:c07]     Device Width: 768.000000
2012-11-27 11:04:00.234 Magazine[5564:c07]     Device Height: 1024.000000
2012-11-27 11:04:00.247 Magazine[5564:c07] Error when loading book status: Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn’t be completed. (Cocoa error 260.)" UserInfo=0x95b8280 {NSFilePath=/Users/darrenrettburg/Library/Application Support/iPhone Simulator/6.0/Applications/2F372FBF-1CEE-4992-B784-613DE701A302/Library/Caches/statuses.json, NSUnderlyingError=0x95d9500 "The operation couldn’t be completed. No such file or directory"}
...

Could it be the way I am zipping the file? Is anyone else zipping up the file to make the hpub file doing it a certain way?

**Comment by drking0211** [comment]
I had exactly the same problem and for some reason my previous book folder was missing the gfx folder and the odd comma was wrongly referenced in the JSON file up on the server.

Anyways, I fixed it by using the book.json file from the working Scartlett download book and replacing my page definitions (is 1.html, 2.html and so on.

I then copied the gfx folder from the Scarlett download into my book folder (hitherto this was missing).

I then cleaned, deleted the app from my iPad and built again and it all worked okey dokey.

Hope that helps.

**Comment by ghost** [comment]
I have an update. I went as fare as to replace my .hpub file on my server with the downloaded sample .hpub file from Baker. it worked just fine. I then took the downloaded Baker sample .hpub file changed it to a zip file, unzipped it, zipped it back up, changed it back to a .hpub file and placed that on my server. It downloaded fine, went to read it and no go. This looks like it's the way I am zipping the files. Is there something special I should be doing to zip the file to make the .hpub file? I'm using a MAC. I've zipped them using control click and choosing compress file. I have also zipped it using the terminal.
Thanks again for everyones help

**Comment by folletto** [comment]
It seems you are zipping the folder instead of the _files_ within the folder. Try that :)

**Comment by ghost** [comment]
Do I zip them each or highlight them all an zip them together?

**Comment by Simbul** [comment]
Highlight them all and zip them together. The important bit is not to zip the folder that contains them, but the files themselves.

**Comment by ghost** [comment]
Thanks, I will give it a try and let you know.

**Comment by ghost** [comment]
Okay, I feel like an idiot on that last one. It's working.

Can any one tell me the adjustability we have on this version (4.0) I would like to adjust the titles sizes,  typeface, italics, ect. This version doesn't use the ViewController nibs. Can you point me to the class file that may contain this?

**Comment by nin9creative** [comment]
I was actually working on abstracting the font selections and sizes to the UI Constants file :)

You can change for the Issues in IssueViewController.m

Warm Regards,
Andrew

**Comment by ghost** [comment]
@nin9creative Do you have idea when you might have that done or is it done already?

**Comment by nin9creative** [comment]
I did it in a local branch of mine.  I can probably tidy it up and send a pull request in the
next day or so.  I also broke out and added another font selection so that the user can style the
issue title and info with different fonts and sizes.

Andrew

**Comment by ghost** [comment]
@nin9creative you do some fine work. Thank you very much.
