### ISSUE TITLE
Vertical dump

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#55]
Hi guys,

I designed my book to work properly in the vertical position of IPAD and I wonder if it's possible to turn the book, ipad change positions but only in the vertical positions.

Thank you very much

**Comment by folletto** [comment]
Are you referring to this issue? -> #6

However turning the page changes it size, so if you want that you are going to need a new CSS for horizontal viewing. :)

**Comment by frantovar** [comment]
Yes!! sorry ;)
