### ISSUE TITLE
Testing Baker 4.0

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#550]
I have it up and running, and everything looks great! My issues download perfectly and archive and anything else works great. The questions I have are:
1. The shelf is still called "Baker Shelf." There was talk about abstracting this so people could rename it to something other than Baker Shelf. Is this still in the works for the 4.0 release? Should I open a new issue for this? 
2. When I am inside an issue and double tap to bring up the Baker shelf menu, the name of my magazine is nicely set up at the top. Where is this set? Can I change it somehow?
3. I have set Baker to only work in portrait mode in all the places I know of, but the shelf still works in landscape mode. Why? I have checked both the plist (portrait is the only two set) and the info page in the build settings (only portrait modes are checked). Am I missing something new here?

Thats it so far. Still waiting for my IAP to be approved so I can test the free subscription.

**Comment by tstegart** [comment]
Another quirk: If you have an issue specified in the json file on the server but there isn't a file actually there to download, Baker just hangs and attempts to download it continuously (well, for a minute so far). Is there a timeout set? There should be an error message if there is no book to download.

**Comment by folletto** [comment]
Thanks for the feedback! :)

First, could you please open 1, 3 and the "other quirk" as separate issues? :)

About 2, the name is taken from the `book.json` file from the `title` parameter. :)

**Comment by tstegart** [comment]
Thanks! Will do.

**Comment by folletto** [comment]
We closed this since we released 4.0. :)
Thank you everyone! :D
