### ISSUE TITLE
Provide way to rename Baker Shelf

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#551]
There should be a way to customize the name of the Baker shelf. It appears in two places: at the top of the Baker shelf view, and when you are inside an issue and double tap, the button in the upper left is called Baker Shelf. I am not sure if they are set in the same place or not. 

Maybe this can be added to the UI constants file?

**Comment by Simbul** [comment]
There is a way to customise that, you just need to change the string corresponding to `SHELF_NAVIGATION_TITLE`.
All customisable strings have been recently moved to `Baker/Supporting Files/en.lproj/Localizable.strings`, which is probably why you couldn't find it.

In passing, this should also make it possible to localise the Baker interface in any language ;)

**Comment by tstegart** [comment]
Thanks! That makes things pretty easy.

**Comment by tstegart** [comment]
I think we can probably close this. I'll add a line to the Wiki to let people know where to change things.

**Comment by folletto** [comment]
We need this open until it's "solved" by either documenting it or finding a clearer solution. ;)

**Comment by tstegart** [comment]
I added a line to the Wiki about where to change things under optional customization. The solution mentioned above seems to be a nice way to customize all of the strings at once and I believe it is optimal.

**Comment by Simbul** [comment]
Closing, as documentation has been added to the [Newsstand tutorial](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand).
