### ISSUE TITLE
Baker 4.0 - Xcode Version 4.3.2 build issues

### ISSUE THREAD

**Issue by ShaunStilwell** [Simbul/baker#558]
Hi All

Trying the new 4.0 build using the Master https://github.com/Simbul/baker/downloads.

I have followed the following steps to run Mode 2: Bundled (without Newsstand)
https://github.com/Simbul/baker/wiki/Newsstand-vs-Bundled-publications-support-in-Baker-4.0

I am getting the following 9 issues when trying to test.
http://i671.photobucket.com/albums/vv73/shaunstylz/baker_build_issues.png

I have also tried running the in Mode 1: Newsstand (default)
http://i671.photobucket.com/albums/vv73/shaunstylz/baker_build_issues_mode1.png

Help would be much appreciated thanks

Shaun

**Comment by tstegart** [comment]
Have you tried updating Xcode to the newest version?

**Comment by ShaunStilwell** [comment]
Thanks it works with the latest version.
