### ISSUE TITLE
Testing free subscription

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#559]
Does anyone know how to test if the subscribe button is working?

**Comment by nin9creative** [comment]
Basically you need to do all the setup on the iTunes connect side of things.  Create an App ID in the provisioning portal first, setup the app / free subscription with iTunes connect etc...  Then you can test from within XCode by using a Sandbox Apple ID (also created from within iTunes connect).

**Comment by tstegart** [comment]
Thanks! Can I ask if anyone knows what the app should do when a user subscribes correctly? Is there a pop-up, a confirmation message, some kind of user notification?

**Comment by folletto** [comment]
The "Subscribe" button should turn off. :)

**Comment by tstegart** [comment]
Is there an unsubscribe button? Not that anyone would want to do such a thing with my magazine of course, but, you know, for others.. :)

**Comment by tstegart** [comment]
Nevermind, I believe subscriptions are handled from within iTunes. EDIT: We might want to tell the user this with a pop-up after subscribing. Its not commonly known.

**Comment by folletto** [comment]
That's correct.
And nobody knows... actually, do you ever found a magazine that explains that? We would like to see it, but we still have yet to find one, so far it seems that nobody does it.

**Comment by tstegart** [comment]
You're right, I don't think anybody knows. Actually, I'm not even sure what a free subscription does, and I have a magazine. Even though we have to offer it to get accepted, does it actually do anything? I mean, what is the free subscription code actually doing in the background, does anyone know? Sigh, Apple kills me sometimes.

**Comment by ghost** [comment]
I think if you are a subscriber, free or otherwise, it will automatically download a new issue in the background, when one comes out without you (the customer) having to do anything.

**Comment by folletto** [comment]
That's not correct: that's Push Notification, not Subscription. The subscription just allows you (the author) to get the data of the user subscribing. What you do with that is _usually_ the Push Notification, but it's a separate piece of code. :)

**Comment by tstegart** [comment]
Hmmm.. I thought @darren2c57's version was right. I thought push notifications was just the message you could send to users notifying them of a new issue (and having a little badge show up on the corner of your icon), but Newsstand actually did the downloading of the new issue in the background by itself without any push notification. Sigh. Apple really needs better documentation.

**Comment by nin9creative** [comment]
I'm pretty certain that background downloading of new issues is only triggered by a special type of push notification to the Newsstand enabled
app, which it must correctly handle.

Background downloads – Using Apple Push Notifications 
Service (APNS) your server can notify the application when new content 
is available. The application can detect this via a special payload key 
and automatically download content in the background (over wi-fi only).

**Comment by nin9creative** [comment]
Newsstand Push Notifications
To receive Newsstand Push Notifications, your application 
must register for them (which in turn prompts the user for permission). 
Include this statement early in your application lifecycle:

1 UIApplication.SharedApplication.RegisterForRemoteNotificationTypes (UIRemoteNotificationTypes.NewsstandContentAvailability); 
and add a new entry newsstand-content to the string array key UIBackgroundModes in your Info.plist

On your server, add this payload key to your APNS message 
to notify the Newsstand application that new content is available for 
download.

1 {'aps':{'content-available':1}} 

Handling this type of notification would normally involve 
starting a background download of the new content. The 
‘content-available’ key should not be combined with an APNS message that you intend the user to see – if this key is present in a message then 
any text included will not be shown to the user.

To prevent applications using too much bandwidth, Apple 
limits applications to sending one APNS ‘content available’ message per 
24 hour period. If your server generates additional messages they will 
be ignored (not forwarded to the device).

**Comment by tstegart** [comment]
So if we don't send push notifications, is the user notified in any way. How do they get a new issue, just by hitting refresh? What the heck does hitting the subscribe button do then?

**Comment by folletto** [comment]
Hehe yes guys, but you are missing a piece of the puzzle: Push notifications CAN trigger Background download, but they are NOT tied to it. :)

Baker today implements background download without Push. Actually, that's one of the reasons why we are asking people to submit to the store: that's the only way we'll know for sure. ;)

**Comment by folletto** [comment]
Gives your server the information a subscriber subscribed.

In other words: nothing unless you develop something that uses it.

**Comment by nin9creative** [comment]
The subscribe button has everything to do with the In App Purchasing system.  A minimum free subscription is required for a Newsstand enabled app
to get accepted.  You can take the receipt data returned from the subscription registration and store that / validate it against Apple to receive more information
regarding the subscription.  

Later on this will all be pretty important when the single issue and paid subscription work has to be done....

http://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/StoreKitGuide/VerifyingStoreReceipts/VerifyingStoreReceipts.html#//apple_ref/doc/uid/TP40008267-CH104-SW1

**Comment by nin9creative** [comment]
Although in this scenario I thought we were talking about this use case.

1)  User is subscribed to XYZ magazine
2)  Publisher releases new issue of XYZ magazine in the middle of the night
3)  Push notification is sent to User's device notifying it of new available content, device begins background download
4)  User wakes up, the Newsstand cover icon has a blue sash that says "new" on it and upon opening the XYZ magazine shelf, the content is already downloaded and available to read.

I understand that Baker kicks off a background downloading process on the Newsstand framework for the issues when a users clicks on it, but it's not the same thing
as Push notification background downloading.

**Comment by Simbul** [comment]
First of all, a couple of simple FAQs:

_Do I need to implement push notifications to get into the App Store?_
As far as we know, no. See [this](https://github.com/Simbul/baker/issues/100#issuecomment-9798521) and the following posts.

_Do I need to offer a free subscription to get into the App Store?_
Yes. Again, see above.

_So what's the point of a free subscription without push notifications?_
You could argue there's no point other than getting the app approved. If you offer your content for free anyway, subscribing (without push) won't make a difference for the user.

_So why isn't Baker supporting push notifications?_
Because we haven't got round to implementing it yet. We only have a limited time to dedicate to new features, and preparing version 4.0 required a considerable amount of time already :)

---

Now, let's **not** consider free subscriptions for a minute, as I think they're the most confusing bit.

Suppose you offer a yearly subscription for $5. When a user subscribes, it means she is buying the right to download all the issues of your magazine that are published in the following year. The way they are delivered to her is not relevant as far as subscriptions go.
The most basic form of delivering an issue is having the user download it when it is ready. That's what Baker is doing at the moment.
A more advanced option is to send push notifications to the user. This means she won't have to download the issues manually.

In both cases, your server will have to manage the subscription logic. When the user wants to download an issue, the server will have to check with Apple that her subscription is still valid. In the same vein, the server will have to check that the subscription is valid before sending a push notification.

While this makes sense for a paid subscription (users buy the right to read issues), free subscriptions break all the rules, as the user will be able to download your content for free anyway. So the main advantage of getting a free subscription, for a user, would indeed be to get push notifications.

**Comment by Simbul** [comment]
@tstegart to get back to your original question: the subscribe button will send a subscription request to the App Store (in your case it will be most likely the sandbox, which is the testing environment).
If it works, you will see a series of modal popups asking if you want to subscribe, if you agree to disclose your data and so on.
If the subscription fails, you will see an alert message with an error message.

If the value of `PRODUCT_ID_FREE_SUBSCRIPTION` is wrong, you won't see any popup but the logger will show a message saying something similar to "invalid product id".

**Comment by tstegart** [comment]
Great write-up! And thanks for writing out what is supposed to happen. Do you think this is something that should be added to the Wiki?

**Comment by tstegart** [comment]
It looks like I successfully tested a free subscription in the sandbox. There were a few unfortunate side effects/lessons learned.

I believe you need to change the bundle identifier from the Baker one to your own to successfully get testing to work. Someone may have mentioned this already.

The display name of your in-app description appears in the pop-up message that appears asking the user to confirm. You should make sure your display name is just the name of your magazine so it appears grammatically correct. The exact message, if you're wondering, is "Do you want to subscribe to [display name] for free?"

Newsstand automatically tells the user that you want their name, email address and zip code, even if you don't. There is no way to TURN THIS OFF, at least as far as I can tell. You should put up a privacy policy on your website. Even if the user clicks no, the subscription appears to work.

In the same message, it also uses your developer name. I can't figure out if this is a bug or not, because the message is grammatically incorrect. But be aware that if you use your real name instead of an LLC to publish your apps, every user will see your name.

**Comment by anjimi** [comment]
In iOS 5.1 simulator when I try to subscribe I repeatedly get this error message: "Subscription failure An unknown error has occurred" after entering my test Apple ID.

In iOS 6 I can complete the subscription process. After entering my test Apple ID I get the message which @tstegart mentions which references my developer name, the full message is: "Share your information? The publisher of [developer name] would like your name, email and postcode for use in accordance with their privacy policy."

This doesn't seem right, it doesn't make sense to reference the developer name here, it may bear no relation at all to the publication title. Is this message generated by Baker or Apple?

Whether I choose 'Allow' or 'Don't Allow' I then get a message saying I have successfully subscribed, but the 'Subscribe' button is still there.

**Comment by nin9creative** [comment]
The message is generated by Apple for the IAP...

I would assume that the same behavior below applies to the free subscription vs paid subscription. 

"The user is presented with a buy confirmation dialog when purchasing an auto-renewable in-app purchase. They then have to sign into their account, if they are not already logged in. The personal data sharing dialog is then presented. Clicking Don't Allow in the last dialog does not prevent the user from purchasing the add-on."

As far as the subscribe button, I don't think that the current codebase records whether or not a subscription has already taken place nor persists that to disable the Subscribe button.  It will always be available even if the user has already subscribed.  Better subscription management and whatnot would probably come as a subsequent release that incorporates paid subscriptions etc.

**Comment by Simbul** [comment]
Yup, Andrew nailed it :+1:

**Comment by anjimi** [comment]
Ok, re the subscribe button, it's just that @folletto mentioned earlier in this thread that it would turn off once subscribed. I wanted to check my app is behaving as it should. 

I understand that the user can subscribe whether they agree to share their personal info or not, I was just saying I had tested it both ways.

So the subscription is not recorded within the app? What is the purpose of the free subscription - other than for approval process? I have this feeling Apple will not approve it if the subscription doesn't actually do anything...

I've mentioned this before on another thread - found on Apple Newsstand FAQ: http://developer.apple.com/library/ios/#technotes/tn2280/_index.html

> Is my Newsstand app required to use Newsstand Kit's background downloading feature?
> 
> If you're delivering an issue to a user as part of a subscription, you must deliver it via background download.
> 
> In general, users will expect Newsstand apps to have content downloaded in the background, ready and available for offline viewing. If a user hasn't purchased a subscription for new issues, you may use Newsstand Kit's background downloading feature to deliver other content. Keep in mind that your Newsstand app should not deliver or manage content in a way that ends up consuming large amounts available storage space on a user's device.

This sounds to me like Apple will expect subscribed users to receive issues via background download.

Any ideas re the error subscribing in iOS 5.1? Or are we only supporting iOS 6.0 onwards?

**Comment by nin9creative** [comment]
Have you tried testing it on an iOS 5.1 device?  I don't have an actual 5.1 device handy to test on, but the simulator doesn't work "Subscription Failure - An unknown error has occurred"

However on the iOS 6 simulator and my iPad 3, it does work with no issues.

**Comment by anjimi** [comment]
I get the same error in 5.1 simulator. I have an iPad with 5.1, but it's setup with a real Apple ID user, which errors on subscribe. Is it possible to sign in with sandbox test user temporarily, without losing the other data on the iPad associated with the real user account?

**Comment by anjimi** [comment]
Ok after checking I could sign in and out of different Apple IDs I managed to get the subscribe to work successfully with my test user on iPad 3 running iOS 5.1.1.

**Comment by ghost** [comment]
I am trying test out my subscription in the sandbox also. I am having a few issues. When I hit the subscribe button I either get the wheel briefly and it goes back to the regular stat or I get the wheel just spinning with nothing else happening.

I could be putting the wrong url's in the Constants.h code.
I have three questions

1) For the  #define PRODUCT_ID_FREE_SUBSCRIPTION line does anyone know if there is info Apple gives you to fill in here once you set up your subscription? I am getting an Invalid product identifiers message in my console when I fill it in with the example using my information.

2) For the #define PURCHASE_CONFIRMATION_URL do I need to make the JSON file at this location or will it automatically be generated when the first user subscribes?

3) Are the answers hiding in some obvious place in the Wiki? If so will someone point me in the right direction?
Thanks.

**Comment by tstegart** [comment]
1 - You should use the product ID you used when you created your in-app-purchase in iTunes connect. Make sure you completed your in-app-purchase all the way through to the "ready to submit" phase.

2 - I'm not sure, I leave this blank, so you should still get a successful subscription in the sandbox without changing anything in constant.h here.

**Comment by ghost** [comment]
@tstegart yep I am using the product ID used in the in-app-purchase and it's in the ready to submit phase.

**Comment by Simbul** [comment]
@darren2c57 what @tstegart is saying is correct, as you can see in the [Newsstand tutorial](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand).

The Product ID for an In-app Purchase is something you have to provide in iTunes Connect. It's not coming from Apple: whatever you entered in the "Product ID" field in iTunes Connect is what you should set `PRODUCT_ID_FREE_SUBSCRIPTION` to.
As an aside, make sure the Bundle Identifier for your app matches the Bundle ID in the iTunes Connect interface.

The `PURCHASE_CONFIRMATION_URL` is a URL Baker will use to send the receipt to. You don't have to provide any content at that URL, and you don't have to set that constant if you don't need it. See [Subscription pingback](https://github.com/Simbul/baker/wiki/Subscription-pingback).

**Comment by tstegart** [comment]
The bundle ID! That's what I forgot. Good catch @Simbul. We should really add that to the Wiki as it is a required step. It seems odd that you can follow all the steps in the current Wiki and still fail. Any objections to adding it? I can do it.

**Comment by ghost** [comment]
Thanks everyone, I got the subscription working yesterday and now I think I understand that the JSON file will be created. 
I had to get the PURCHASE_CONFIRMATION_URL set. We are planning to eventually have paid subscriptions and the option to buy single copies. 
I would love to know how we can contribute to help different subscription options along?

**Comment by folletto** [comment]
If you want to contribute, just pick an issue that you want to work on, write here what you are doing and implement it on master. Once ready, do a pull request to us. :)
When you do this, try to keep the code changes to the issue you are working on, without any extra: every extra code makes more difficult to merge back the changes. :)

**Comment by folletto** [comment]
We closed this since we released 4.0. :)
Thank you everyone! :D
