### ISSUE TITLE
Turn off vertical swipe in the UIWebView?

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#56]
Hello,

My book  always measure 768x1024  so the vertical swipe is not necessary. Can you turn off easily?

Thanks!

**Comment by Simbul** [comment]
This sounds like a sensible request - especially after trying out your book ;)

**Comment by Simbul** [comment]
Added configuration constant PAGE_VERTICAL_BOUNCE: turns off bouncing on vertical scrolls, which is good for books that don&#39;t need any vertical scroll anyway.
Closed by b0c2396fd0b501220ca66afdcb003e1ed1cd00a6.

**Comment by frantovar** [comment]
Thanks, is good news!

**Comment by frantovar** [comment]
Works fine, thanks!
