### ISSUE TITLE
Magazine links staying in Newsstand app

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#561]
I'm not sure if this is the right place to put this. When I click on the links in my magazine on the Baker Shelf app the link opens up within the app. I want it to go out of the magazine and open on the iPad browser. Is this possible? 
Is there something I have to change in my magazine links code? 
Is anyone else experiencing this?
I was unable to find anything about that in the wiki.
Thanks.

**Comment by folletto** [comment]
From the iPad browser there's an icon in the top right corner that opens Safari. It's default behaviour for iOS apps. :)

**Comment by ghost** [comment]
I'm not finding an icon within my magazine for the link to go to Safari instead of the link opening inside my magazine. When I am on the web page that opens within my magazine and Baker Shelf, I'm not finding any icon either. When I scroll to the edge of the opened webpage that's in my magazine and go a little further it slides to the next page in my magazine. If I then swipe back it goes to the original page that had the link on it. I am using the 4.0 framework. I probably should have mentioned that in the title.

**Comment by folletto** [comment]
Ahhh ok, now it's clearer. :D

Could you paste here the link you are using, so we can check it?

**Comment by yujulio** [comment]
Did you use "?referrer=baker" on your link?

The behavior that you're telling us is exactly when you use the screenshot
rendering with no referrer.

2012/11/29 Davide Casali notifications@github.com

**Comment by ghost** [comment]
@folletto  it is doing it with all and every link that is set up in the .hpub (magazine) file. Do you want me to choose any one of them?

@yujulio  do I need to put that in the HTML href tag?

**Comment by folletto** [comment]
Yes, please. 

The more data we have the easier is to debug! :)

**Comment by ghost** [comment]
Here is what the code is looking like:
< a href="http://www.frontierboys.com/" target="_blank" alt="The Frontier Boys Movie" >

Here is the  link:
http://www.frontierboys.com/

**Comment by yujulio** [comment]
Yes, like this: <a href="http://www.frontierboys.com/
?referrer=Baker">Link</a>

You should check this too
https://github.com/Simbul/baker/wiki/Managing-links-and-urls

**Comment by ghost** [comment]
Thanks @yujulio that was the issue. 

I really am trying to get better at navigating the wiki's 
_sigh_

**Comment by folletto** [comment]
Well, the wiki isn't the most simple thing to use, but at least exists. :)

However, I think you still might have found a bug, we'll check. ;)

**Comment by Xm4s** [comment]
I've checked the links management in Baker 4.0 and all seems to work fine.
Since the specific problem of @darren2c57 was already addressed in the wiki at the address provided by @yujulio (https://github.com/Simbul/baker/wiki/Managing-links-and-urls) I'll close this issue.
