### ISSUE TITLE
Calling js functions in index.html from other pages?

### ISSUE THREAD

**Issue by ec8or** [Simbul/baker#562]
Is this possible? I thought it might be as the index.html loads first of all but can't get it to work, is this file and normal page files not displayed in the same ui view or something?

This would be a easy way to solve music changes etc. on a page-per-page basis.

**Comment by Simbul** [comment]
You're correct: the index bar is loaded in a separate uiwebview.
At the present time, there's no connection between the views showing pages and the view showing the index.

**Comment by folletto** [comment]
The feature request is already in our pipeline but thanks for the feedback @ec8or, so we can have a better idea in how to prioritize it. I'm closing this issue, if you want to follow its development check issue #198
