### ISSUE TITLE
Problems with changing of IndexViewController background.

### ISSUE THREAD

**Issue by Samback** [Simbul/baker#566]
I  tried to change the background color at this controller. When I try to implement these changes the result  was as following: I got a new view with an alpha which is placed on the top of  self.view.  I know that we replaced the web view with the self.view, but the change of the web view background doesn't give a necessary result :

```
- (void)loadView
{
    // Initialization to 1x1px is required to get sizeThatFits to work
    UIWebView *webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 1024, 1, 1)];
    webView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
    webView.delegate = self;

    [webView setOpaque:NO];

    self.view = webView;
    for (UIView *subView in webView.subviews) {
        if ([subView isKindOfClass:[UIScrollView class]]) {
            indexScrollView = [(UIScrollView *)subView retain];
            break;
        }
    }
    [webView release];
    [self loadContent];
}
```

But when I look at the stack of views there is only one view 
  "<_UIWebViewScrollView: 0x1f8b4fa0; frame = (0 0; 1 1); clipsToBounds = YES; autoresize = H; gestureRecognizers = <NSArray: 0x1f8b5270>; layer = <CALayer: 0x1f8b4ef0>; contentOffset: {0, 0}>"
Without a substrate which could add an alpha.

Also, when I try to change the background in my html file, which contains my small pages, just a part of the view's background is being changed.
SO, THE QUESTION IS: How can I  change the background without getting an alpa problem?

**Comment by folletto** [comment]
May I ask first one thing? Why are you trying to change the color of the controller - that's transparent - instead of changing the background colour of the HTML file? :)

**Comment by Samback** [comment]
I tried this as I previously mentioned. It changes just a part of the view background, but not all of it.

**Comment by folletto** [comment]
OK, but did you try extend it? If it doesn't cover everything it means that the HTML doesn't fill everything. Check the size of body. It's probably way simpler (and more upgradeable) than changing the codebase. :)

**Comment by Samback** [comment]
Ok. Thank I will try and make response.

**Comment by Samback** [comment]
Thanks it was really problem in html.

**Comment by Simbul** [comment]
Glad to see it resolved. I'm closing the thread ;)
