### ISSUE TITLE
Refresh button is grayed out when no issues.json file exists

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#567]
If your issues .json file accidentally or purposely gets deleted, Baker loads a blank page with no issues (seems legit). But, if you then put up an issues.json file on your server, there is no way for the user to refresh to load all the issues again. I'm guessing if they delete the app and reinstall it will work again (since a clean and reload in Xcode works), but if you somehow lose your issues.json file, all your users will be in the dark. It also happens when your webserver goes down, which might happen to everyone at sometime, in which case your entire user base will need to delete and reinstall. This would not be good. Opening and closing the app does not refresh the issues. Maybe it should?

**Comment by Simbul** [comment]
If you properly close the application (i.e. remove it from the list of running applications you can access by double-clicking the home button), the next time you open it, Baker will try and fetch the shelf JSON again. So you don't need to delete the app - which would indeed be terrible UX.

Anyway, I reckon this is still rather cumbersome on the user. Commit 8336eb839fdf61f463aa474e22d0de79484c901c fixes this by making sure it is still possible to click the refresh button even if the shelf JSON could not be retrieved properly. So if your server goes down the user can just keep refreshing until it comes back up ;)

@tstegart does this fix the issue for you?

**Comment by tstegart** [comment]
Yes, thanks!
