### ISSUE TITLE
Advice for Three-Cards view

### ISSUE THREAD

**Issue by robbkt** [Simbul/baker#57]
Hi everybody,
I begin to study sdk and I'm very interested in this framework. I want to use the three-cards feature but i'm not able to make it working. When i active the Three-cards code, the only loading page is the first, here a copy of debugger console:

Pages in this book: 14
 [+] Loading: book/Book Cover.html
[Switching to process 645]
 Current Page IS delaying loading --> load page
 Current page height: 1024
 (1) currPage finished first loading
- \- hidden:0 animating:1
  Scrolling
  <<<>>> Swiping to page: 2
  [Switching to process 645]
  Goto Page: book/Chapter 01.html
  [+] Loading: book/Book Cover.html .

As you can see, when i swipe to another page, it loads again the first one ( in this case the cover).
What I have to do to solve this? Thanks

P.s. sorry if i'm not so clear, i begin sdk study only 3 months ago.

**Comment by folletto** [comment]
A brief explanation: it isn't supported due to hardware and libraries limitations.

Please read issue #27 for more details. ;)

**Comment by robbkt** [comment]
ok, thanks for the rapid answer. :)
