### ISSUE TITLE
Baker downloads too much, doesn't seem to archive correctly

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#570]
So I tried a test with Baker to check the archiving feature. An empty shelf version of Baker takes up about 2.3 MB on an iOS Device, when you check its size via settings.

I then downloaded four issues, and checked the size. Baker was taking up over 600MB. But four issues should only have taken up less than 300MB, as each issue is less than 90MB (zipped or unzipped). So Baker is storing too much information somewhere. Quite a lot more, which will be a problem. The nice part about using HTML is that I can say our issues are smaller than PDF magazines, but in this case, it doesn't seem to be helping. 

Next, I archived all four issues. Baker reduced it's size to 299MB. Theoretically, it should have gone down to it's original size of 2.3MB. 299MB seems like it is still storing all four issues somewhere, and is actually in the ballpark of what four of my issues should take up. 

I'm not sure what is happening, but Im guessing an improper use of data storage will present an app store approval problem. Let me know if you need more info about this.
Tom

**Comment by nin9creative** [comment]
You can debug this if attached to the simulator via Xcode.  Figure out where the app is being saved in the simulator on disk and poke around
before and after you delete stuff.

**Comment by tstegart** [comment]
Thanks! I didn't know about that. But thanks to you I think I've narrowed down the problem. It looks like it IS archiving correctly. When I hit archive, the issue disappears. However, it appears Baker is not deleting the zipped files after it unzips them. All my .hpub files are still there, none of them get deleted. That would explain why the size of Baker is so high even after archiving. Therefore, I believe the fix will involve deleting the downloaded .hpub file after it is successfully extracted.

**Comment by nin9creative** [comment]
I kind of figured as much (but am not at my computer with xcode) :)

**Comment by Simbul** [comment]
Fixed thanks to @nin9creative in pull request #575.

Please feel free to reopen if you need more support :)

**Comment by anjimi** [comment]
Please can you tell me the best way to update baker when fixes like this are made - do I need to download the whole master branch and start fresh, or is it possible to just update the necessary files?

**Comment by folletto** [comment]
In theory you just use the new Baker and update the couple configuration lines you changed, but from the question I guess you changed more than that... in that scenario the ideal thing is to use git itself and allow it to do the work, but yes, it's something that requires git, but shouldn't be difficult if you were already working on code changes. :)
