### ISSUE TITLE
Has anyone tried out Adobe Muse?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#571]
Seems interesting for creating wysiwyg HTML.

**Comment by thejtate** [comment]
I have and it's ok, prefer to just do things by hand with Espresso or Coda. I did get around to trying out Adobe Edge. Generates a ton of fat js code but it is very easy to create quick HTML5 animations. I was impressed.

**Comment by nonuts** [comment]
likewise, I prefer handcoded, too. Also, I use middleman http://middlemanapp.com to generate all my html assets, which works well for me.

**Comment by nin9creative** [comment]
Do you have some sort of template that you created?

Warm Regards,
Andrew

**Comment by nonuts** [comment]
for now, I'm piggybacking on http://lessframework.com mostly, just for bootstrapping.

**Comment by thejtate** [comment]
@nonuts Very cool. Love how it helps handle better caching. 

@nin9creative  LessFramework is great, might also check out Skeleton, http://www.getskeleton.com. Super clean.

**Comment by nin9creative** [comment]
What else are folks using for doing their layouts?  I get a sense from some of the responses and others that I've talked to there is a lot of hand coding etc.  

Some of what I'm interested in is whether or not anyone is using a tool that speeds up development of layouts for Baker.  Adobe Muse seemed promising.  There was also a Kickstarter project a while back that is almost entering production that does exports from Indesign to HTML5.

I have been contacted by various people that are looking at creating Baker magazines and come from a publishing background where they are reliant on tools such as Indesign to create content.  Many other magazine solutions (such as Adobe DPS / MagPlus) have Indesign plugins that allow these users to easily create content...

Was just curious...

**Comment by tstegart** [comment]
We use a modified version of the Baker layout and then just do modifications by hand in Dreamweaver. I'm self taught though, so I'm sure I'm not the most efficient coder. Because of that, most of what people would consider "design" in our magazine comes from my co-founder, who does it in Photoshop. So all the good looking stuff is jpegs, and all the easy text part is your basic HTML. Not the most optimal solution, but easier than spending hours trying to figure out why something is not lining up by a pixel in CSS.

**Comment by drking0211** [comment]
We have written our own backed system in .ASP and .NET which takes input from the user in a browser with a back end MSSQL db.

Copy, images, video, sound etc are uploaded to our server via browser interface and then depending on the template that the user chooses, the system renders an HTML page automatically.

The user then selects the page order etc and then the entire book/publication  automatically updates itself within the Baker file system moving images and other assets into the correct folder, writes the index.html/TOC.html and book.json and spits out a book ready for testing in Xcode.

Takes out all the fiddly HTML work and we have been able to produce publications on a daily basis without the interference of our busy web designers,

Just adding a lot more bells and whistles now with all the fancy HTML5 stuff that's around.

We are having 4 to 5 apps approved a week at present.

Been a lot of hard work but really beginning to pay off.

dk

**Comment by mutador** [comment]
hi @drking0211 i´d like to know more about your system, can i talk whit you for email
manuel@magmagoo.com

**Comment by ghost** [comment]
Hey @drking0211,

What you're doing sounds really interesting.
Are you willing to share the code on GitHub?

I bet a lot of Baker users would love to make their own templates and have their server render the .HPub/Baker book for them.

Kind regards,
Mitchell.

**Comment by folletto** [comment]
I'm closing this issue since the discussion seems ended. :)
Reopen if needed. :)

**Comment by jhmac** [comment]
@nin9creative 
We are using Muse for our html. It's supper simple. You just have to tweak your index.html and index.css  in three of four places. Our magazine is Storied Magazine on the app store for the ipad. we did a simple version to for the first issue. The second we are working on now will have much more user interactivity. Let me know if you have any questions about it. 
I am having a problem getting the index to show on the mobile version but I hope to have that worked out soon.

**Comment by jhmac** [comment]
I think I have figured out my problems and should have everything working now. Please head over to  issue #1214
"having trouble with mobile index in adobe muse" to see more.
