### ISSUE TITLE
Cover images in Newsstand

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#576]
I'm testing with Baker 4.0, and the cover image in Newsstand is not being updated with my cover images. My cover images are displaying fine in the shelf. 

When should the cover image in Newsstand get updated? When an issue has been downloaded, or when an issue has been opened/read?

**Comment by anjimi** [comment]
I just tested with the Baker book A Study in Scarlet, and the cover image updated. I see this book has "cover": "thumb.png" specified in the book.json, which I don't have in mine.

Are the cover images for the shelf specified in the issues list .json not used for the Newsstand cover image? I will test by copying my cover images in the .hpub and specifying 'cover' in book.json.

**Comment by folletto** [comment]
The cover image used is the one of the last issue downloaded. So yes: the cover must be there in the hpub file. :)

**Comment by Simbul** [comment]
I've added this to the wiki: [Issue cover displayed in Newsstand](https://github.com/Simbul/baker/wiki/Issue-cover-displayed-in-Newsstand).

Please let me know if that is clear enough.

**Comment by anjimi** [comment]
Yes that worked for me, thanks. :)

I'm wondering if it would be possible to have a default cover image that could be used as the Newsstand cover image instead of the app icon until an issue has been downloaded, the square app icon looks kinda clunky on the Newsstand shelf. Does anyone know the convention with other Newsstand apps for this?

**Comment by ghost** [comment]
The convention with Newsstand apps is to have a specific default cover for your magazine. I believe the long edge of your icon should be at least 512px with an aspect ratio of between 1:2 and 2:1 (magazine or newspaper). You define this icon in your xxx-info.plist. Under your icon files there is an area for Newsstand Icons This is where you reference the default image that will show up on the Newsstand. Right now with 4.0 they are the usual iPhone/iPad icons.

**Comment by anjimi** [comment]
I wondered if the 'Default Cover Art' which you have to upload to iTunes Connect should be used as the default cover in Newsstand... On the Apple developer documentation it just says "If there are no issues available for your app on a given date, the default cover art is used to represent your app on the App Store."

I found other sources which say this default cover art, and not the app icon, should be used as the default cover in Newsstand, before any issues have been downloaded.

http://docs.appstudio.net/display/AppStudio/Apple+Newsstand: "Although the latest cover image is displayed automatically in the app store and on the Newsstand bookshelf, Apple requires you to provide a default image. This is only seen on the user's first install of the app before they have opened it."

https://support.oomphhq.com/entries/21739771-newsstand: "Generic cover art is used in Newsstand when the user has not yet downloaded an issue and also as the app is being downloaded from the App Store."

I don't know how this would be implemented?

**Comment by anjimi** [comment]
That's great, got it! Thanks @darren2c57 for confirming that and pointing me in the right direction. :)

**Comment by anjimi** [comment]
Ok, I saved images for default cover, changed the references for Newsstand Icon files in my info.plist, I am now getting a different image in Newsstand, but not mine, it's a generic image with a grey mountain and MAGAZINE across the top?

@darren2c57 do you know what is the correct location for the Newsstand Icon files? I tried them in the same 'icons' folder as the Baker icons, in the 'Baker' folder, and in the main root of the project, but still I get the generic mountain cover.

The Apple developer documentation says this: "When specifying icon filenames, it is best to omit any filename extensions. Omitting the filename extension lets the system automatically detect high-resolution (@2x) versions of your image files using the standard-resolution image filename. If you include filename extensions, you must specify all image files (including the high-resolution variants) explicitly. The system looks for the icon files in the main resources directory of the bundle."

So, what is the 'main resources directory of the bundle'? And also do I need to save ipad/iphone/@2x versions of the cover image as for app icons?

**Comment by ghost** [comment]
With mine I 'broke' Apples rules except putting it the in the 'main resources directory bundle.' If I am correct it should be the same place your splash screens are sitting if you just drug and dropped them into Xcode. Mine are sitting directly under the project file on the project navigator menu in Xcode not in any of the folders. I also used the extension for the cover file. My magazine is only aimed at the iPad so I just used the @2x file for the iPad.

**Comment by anjimi** [comment]
Thanks for your help, yes that seems to be the right location, in the main project root. I had not dragged my image files into Xcode which was why it wasn't working, I had just put them in the folder in the finder. Works fine now I dragged them into Xcode. :)
