### ISSUE TITLE
Index view disappears after opening modal web view

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#578]
Steps to reproduce:
1. Open a book.
2. Click on a link in the book that opens up the modal web viewer.
3. Click Back on the modal web viewer to close it.
4. Without doing anything else, double tap on the book page to bring up the index and navigation.
5. Index view does not appear (status bar does appear correctly, though).

Closing/reopening the book or even rotating it will cause the index bar to reappear.

(I noticed this while working on issue #574, which is why the steps are pretty much the same ;) )

**Comment by anjimi** [comment]
I just discovered this same issue, any news on a fix for this?

**Comment by folletto** [comment]
Nope. Any news is always posted on the issue when it happens, unfortunately if we don't write it means there are no news.

We are working on items with a higher priority right now for 4.1, this will come at a later time.

**Comment by buildc0de** [comment]
Will look into fixing this one next :-)
