### ISSUE TITLE
UIWebView and UIScrollView Backgrounds

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#58]
Hi all, I set a background image for UIScrollView and one for the UIWebView. The problem is that when passing page, the UIWebView background image shown before content as a Flash. Is there a solution to improve this?

Thanks!

**Comment by Xm4s** [comment]
I'm sorry francesc, could you be more specific?
Seems to me that you are saying that you see the UIWebView background you have set before the current page is load... which is perfectly normal I think :)
Maybe you are referring to the open bug in issue #27?

**Comment by Xm4s** [comment]
Since there's no replay I'm closing this up as "invalid"
