### ISSUE TITLE
Dossier numbers

### ISSUE THREAD

**Issue by joaogarin** [Simbul/baker#580]
Hello I have a question to make, I didn't find any answer to this on Laker or Baker webpages.

I have a magazine that I am finishing and I renamed the images folders from "Dossier-x" to "meaninfull"  names in my application. The same with the CSS files (of course in the HTML files to path was corrected etc.) It is all working but havent tested in Xcode yet.

Does this affect anything?I have the correct order in my Json file and in toc (index) but since the magazine by default is created with dossier-x and numbers of dossiers I wanted to make sure this is not a problem.

Best regards,
Joao Garin

**Comment by folletto** [comment]
I'm not sure what do you mean with "doessier"... could you explain it? Is it a Laker layout details? :)

However, we strongly advise to test always in Xcode while you're working, to be sure that in the Simulator / Device everything works as expected. :)

**Comment by joaogarin** [comment]
Hello,

I had an app in development and it was working Okay.we tested on Ipad and Iphone and everything was smooth. We then made some changes, the most significant being the actual names of the image folders (originally they where dossier-01,dossier-02,dossier-03 and so on) and  the Css files (originally they where in a dossier folder with the names 01,02,03 etc..)

Does the names of  the images and css have to follow this naming pattern so that the book can be correctly recognized?

We are having the function LoadSLot (page) coming with a page value that is 0.Normally it would be 1..

Tjhe function is in BakerViewController : 

(void)loadSlot:(int)slot withPage:(int)page

**Comment by folletto** [comment]
The content of the Hpub file is **completely up to you**, the only mandatory things are the `book.json` and index. You can find the full spec on the wiki: https://github.com/Simbul/baker/wiki/hpub-specification :)

**Comment by folletto** [comment]
I'm closing this issue due to no follow-up in more than a month. Reopen at need. :)
