### ISSUE TITLE
Cover images in shelf do not load until visible (scrolled to)

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#581]
I have a shelf of more than 6 magazines so the user has to scroll to see more issues.  One bug I have run into is the fact that the cover images for the issues that are not visible are not loaded until they are in view. This makes the interface seem slow.

I have tried to remedy the issue, but I have essentially hit a mental wall still with no results.

Has anybody else run into this issue?
If so, I would greatly appreciate it if you post your solution here.

As a feature for Baker 4.0, it would be great if users could specify if they want all the cover images in the the GridView to be loaded (whether they are currently visible or not) or specify how many rows/cells past the current view they want to load.

**Comment by ghost** [comment]
The odd thing is that the information about the issue (title & info) are loaded. It is only the cover image that waits until the cell is visible to download and display.

**Comment by Simbul** [comment]
That's how the shelf component (AQGridView) works: to save memory and processing power, it only renders the objects that are visible.
Title and info are not rendered either, but they don't have to be downloaded, which is why you see no delay.

In my tests, the delay was definitely there, but barely noticeable - though I appreciate this may depend on network speed. How big are the covers you're downloading? With [270x360px](https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON) I'm getting images that are around 100 KB.

**Comment by ghost** [comment]
Thank you for your response.
My covers are the same size and at around 100KB and I understand that AQGridView intentionally loads only the cells in view to save memory and processing power.

However, I came across this issue in the official AQGridView Repository. (https://github.com/AlanQuatermain/AQGridView)

"This is a feature suggestion: The ability to specify how many rows off the current view you would like pre-loaded. For instance, I extended AQGridView so you could specify that 2 rows of cells should be loaded above and below the visibleBounds, this helps ensure that the cells have all their content loaded by the time they become visible (in case you're loading content via threads or http)."

I messaged the person who submitted the issue but they seem to no longer use their account.
I wonder if anyone knows how to do this as it will replicate a functionality seen in many other Newsstand apps that distribute magazines.

I just think an enhancement like that would really put the fining touch on the user experience.

**Comment by Simbul** [comment]
I think the best trade off in this case would be to show a placeholder for the cover when it has not yet loaded.

This would make it less jarring to wait for the covers to load while at the same time not requiring massive changes to AQGridView.
