### ISSUE TITLE
Network Connection Warning (may be needed to receive Apple approval)

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#582]
I am about to submit my Newsstand app to iTunes Connect and have ensured that I have read every relevant piece of information Apple provides developers.

Today I came across some information on the developer member centre that stated that one of the main reasons an app is rejected is when there are no network connection warnings.

For example: I fear my app may be rejected because when I open it for a second time (this time without a network connection) all the issues have disappeared and no notification is given that this is because of a network issue.

As an enhancement for Baker 4.0 I would suggest that a HUD that states that there is "No Network Connection" is displayed when the app launches/becomes active without a network connection.
A HUD like in this image:
![full](https://f.cloud.github.com/assets/2995310/5344/d842b840-436f-11e2-86a2-e9272c8c196d.png)

As an alternative to the previous option: When the app becomes active, a trigger to refresh the grid is given. This is what makes the issues disappear when there is no network connection. Changes could be made here to check if there is a network connection and not initiate the refresh command if there is no connection. This means that any previously downloaded issues are there to be read offline and all the other issues that have not been download are still there but (because of the recent addition of the download failed alert) if a user attempts to download one of the other issues while offline they will simply receive the existing alert that "The issue could not be downloaded".

I will still submit my app today and I will post here as to whether it was accepted or rejected. However, I believe one of the above options should be included in the final Baker 4.0 release as it would completely fulfil the guidelines that Apple has set out. Additionally, it will decrease customer confusion when no issues are displayed for them to see if they launch their app for the very first time with no network connection.

**Comment by folletto** [comment]
It's a good suggestion, thank you very much. :)
Let's hope however that it's still ok for Apple. ;)

**Comment by nin9creative** [comment]
I was actually going to post about this.  I think that we do need to put a warning for no network connectivity.  Apps will get rejected.  Apple will test
the app with no connectivity and if it doesn't handle the situation gracefully they will reject the app I believe.

The other issue is that we have to better handle the situation where there is no connectivity on startup.  If the app can't get the JSON file it shouldn't
display a blank page.  I haven't looked into the code that caches the issues yet, but it should still load whatever was there the last time.  It should also
obviously allow you to read what content you already have downloaded locally.  If a you click download and are offline, a warning should appear.

This is all important for a base Newsstand 4.0 enabled release because the use case is that it is likely iPad users will not always be connected.  It defeats
the purpose of having an app that downloads content if you can't even get to it if there is no connection that the app depends on.

**Comment by ghost** [comment]
Hi Andrew,
I have also been following your version of BakerShelf for the better part of this year.

I notice that in the version of your shelf before you changed direction to better align with Baker 4.0, the previously loaded JSON data remained in the shelf when the app was loaded with no internet connection. Do you think it is possible to change the code you used previously to do that and submit it to the Baker 4.0 Milestone?

That would then only leave the network connectivity notification (on first run) to implement as I believe the current "Download Failure" alert that appears when the shelf cant connect the URL that the issue is hosted on would be enough to satisfy Apple in that aspect.

I'll see if I can use Apple's Reachability code to call a HUD like in the image above every time the device looses connection to a network. I'll try and make it unobtrusive, like a thin transparent one hovering at the bottom of the screen so the user is informed of the status of the connection but can still (if the above issue is addressed) use the currently downloaded issues and see the JSON data from the last connection. It would just appear in the shelf, not when reading am issue.

**Comment by nin9creative** [comment]
Yeah, I just noticed it was an issue here.  Will take a look and see.  I agree that if we at least detect and warn that a connection isn't available when something is attempted (refresh issues) or downloads it should be good.  The biggest issue is loosing the populated shelf view.

Andy

**Comment by nin9creative** [comment]
I am going to submit a pull request for part of this request.  The initial launch testing of the network connection with a warning message.  I think that there are a few ways to simply address this issue.  1)  Test connectivity on Launch and warn a user if there is no network available.  2) Don't refresh the IssuesList in the case and display the data that was previously stored for the issues.  3) When a user tries to download a new issue, if there is no connection, show a warning message.

The pull request I'm going to submit addresses #1

I believe Baker already addresses #3 with the change that was made recently.

#2 is outstanding, but I want to defer to the Baker guys on how they think that best should be implemented.

Here is what pops up when there is no connection on launch with the change I just made.  All three text elements are customizable in the localized strings file.

![Network Warning](http://www.bakershelf.com/screenshots/NetworkWarning.png)

**Comment by folletto** [comment]
Looks good, however I wouldn't annoy the user if at launch connection isn't presente. Just tell the user in case of update (by pressing the button). :)

**Comment by nin9creative** [comment]
Well, that's fine then.  Minimally in the launch you'd need to do the same test to figure out whether or not to refresh the Issues list, or when the user clicks on refresh.  Not sure how you want to handle this then....

**Comment by ghost** [comment]
Hey Andrew,

Is it possible to only show this alert on the very first launch if there is no connection?
I have been working with a transparent HUD that hovers at the bottom of the shelf when there is no connection but I would love to have a more abrupt alert for users who don't have any content due to it being the first launch.

Mitchell

**Comment by folletto** [comment]
When the user clicks refresh, a message in a popup is fine for now. I wouldn't do anything more on that side. :)

Good point @mit1818 about having a message when the shelf is empty on first launch. :)

**Comment by nin9creative** [comment]
What about the situation that the launching of the app requires a network  connection to load the json file and populate the shelf?

**Comment by folletto** [comment]
Yes, that's what I mean by _first launch_. If there's already a shelf populated, there's no need to disturb the user with a popup. If the shelf isn't populated, then a popup is ok (even probably a message on the screen would be better, but I wouldn't complicate it too much). :)

**Comment by nin9creative** [comment]
I'm just saying that if a user launches the app now and there is no connection, even if the list was there before the shelf is blank...  It shouldn't blank it out.

**Comment by ghost** [comment]
I agree Andrew,
If I open the app with a network it loads fine. But if I completely close the app (by exiting it in the multitasking bar), disconnect from the Internet and then open the app again the shelf is blank. This happens even if you have already download issues to the device. This is the one thing that remains on my todo list before my app is released.

Regards,
Mitchell.

**Comment by folletto** [comment]
Sure, that's the point of this issue right? ;)

**Comment by ghost** [comment]
Yes :)
Unfortunately I have still not had success with having the refresh not occur when there is no network connection.
Hopefully there is an easy solution that I am just not seeing.

**Comment by nin9creative** [comment]
I have a solution will post later tonight....

Warm Regards,
Andrew

**Comment by ghost** [comment]
Thanks Andrew.

Kind regards,
Mitchell.

**Comment by nin9creative** [comment]
I posted a couple commits on my https://github.com/nin9creative/baker/commits/master-enhancements branch.  I included versions of Apple's Reachability code samples although it's probably not totally necessary.

In the IssuesManager.m file I modified the code in the refresh method.   It basically caches the NSArray for the JSON file in the /Library/Caches folder every time it sucessfully refreshes it.  If the refresh method is called and the remote json retrieve fails, the code tries to load it from the cached file.  If it can't find a cached file, then a warning message pops up that tells the user about the internet connection problem (because at this point it can't get the issue list and there is no cached issue list).  At the point that it fails I do a reachability test in the ShelfManager on the handleRefresh.  It may not be totally necessary because at that point it most likely failed because it couldn't get the remote file.

**Comment by Simbul** [comment]
I added a commit (see c786f51 above) to address one of the issues by caching the shelf manifest.

@nin9creative I hope you won't mind that I went ahead of you on this one.
I still think a pull request from you would be massively useful to show the warning message when even loading the cached manifest fails.
As an aside, I'd leave out the Reachability code: as you said it's probably not necessary and I'd rather keep the codebase slim :)

**Comment by nin9creative** [comment]
@simbul - No worries!  Will submit the warning message part in a bit.

**Comment by Simbul** [comment]
Between commit c786f51 and pull request #591, I think we have pretty much implemented what this thread was about.

The only thing left out is managing the download of an issue when there's no connection, but that is already tracked in #593, so I'll close this issue.
