### ISSUE TITLE
Disable page turn swipe on a single page

### ISSUE THREAD

**Issue by Wolfred** [Simbul/baker#583]
Hello!

I read about the json Behaviour properties: baker-page-turn-swipe
Is it possible do disable page turn swipe or tap on a single page. Or a defined area without swipe page turn, that's cool too.
In my book I have one page that shouldn't have page turn swipe. I need the swipe gesture to do something else. I don't wan't my whole book just tap for page turn. 

Any suggestions?

Thanx

**Comment by heirenton** [comment]
You can hijack swipe function with javascript and do whatever you want. There are different javascript libraries which take control of touch functions.

**Comment by Wolfred** [comment]
Thank you for the reaction, I'll look into that

**Comment by Wolfred** [comment]
Hello again, I have been looking into hijacking swipe functions. I'm pretty new to this and I can't really figure it out. 
It's a page with drag and drop and another with .reel. I need them to work like they do outside of the baker framework.
So it's more disabling baker than anything else.  

Could you advise any of the libraries. It would be a great help.

**Comment by heirenton** [comment]
Hi.

I had used this [library](http://www.codingjack.com/playground/swipe/)... I tried to find code snippet i used but i am not the tidiest person. But it is easy. You have to define swipe events and than define callback functions for them. This way you can use them whenever you want.

**Comment by Wolfred** [comment]
Hi, thanks for the reaction. I'm still working on it. Touch punch was the solution for drag and drop. .Reel pluging still doesn't work. But I don't know if it is related to this topic. Thanks again for the help

**Comment by folletto** [comment]
I'm closing this issue because there was no follow-up in more than a month. Reopen at need.
