### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#585]
I'm a newbie to Xcode, Laker, and Baker who has had a decent amount of experience in HTML and CSS. I've been looking to design a magazine App for Apple's App store and Newsstand.

After struggling with trying to figure out how to develop a magazine App, Laker and Baker seem like a solution that I can work with. I've been successful with modifying the various files and graphics, so I'm confident that I can get it to work for me. Thanks to you all!!!

My biggest concern at this time is that I want my App to be accepted by Apple or any work that I have done/will do will be for naught. And, I know that Apple can be temperamental, so...

While my App/Magazine runs properly, I noticed that when I output my magazine App to the simulator in Xcode or to my iPad that a number of "issues" (yield signs) show up in Xcode under JSONKit.m and unzip.c. They include things like "Format String Issue," "Semantic Issue," and "Parse Issue."

So, my question is, are these normal issues and will Apple accept them, or do they need to get fixed before Apple will approve the App? If they need to be fixed, how do I fix them?

TIA

**Comment by folletto** [comment]
They are just warning, they are coming from the libraries we are using. Since the app is compiling and working, that's ok. We have addressed part of these issues in the next version (currently on Master). :)

**Comment by tstegart** [comment]
You're fine @sportyguy209, they are for the most part normal and we've been accepted already with those there.

**Comment by sportyguy209** [comment]
Awesome, thanks!
