### ISSUE TITLE
Baker/Friar on Android

### ISSUE THREAD

**Issue by mtamony** [Simbul/baker#586]
I have Baker/Friar working somewhat well on Android. I update Jquery and Jquery Touch Swipe in Friar. Improved the experience. Has anyone gotten the double tab navigation to do anything in Android?

**Comment by folletto** [comment]
I think you should contact the author of Friar, we can't give much support for that... and I've seen you already posted on the issue board there: https://github.com/hanchang/friar/issues :)

**Comment by mtamony** [comment]
Thought I would ask here since that github doesn't have much activity. I will post over there.

**Comment by folletto** [comment]
Hehe worth trying. Maybe someone will see this and answer. ;)

**Comment by folletto** [comment]
I'm closing this since there was no follow-up in more than a month. Sorry, but reopen at need.
