### ISSUE TITLE
index position for landscape orientation iOS 5.1

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#587]
When loading a book from the shelf in landscape orientation, the index loads as if it were portrait, which on the Baker test book means you can't see it as it's off the bottom of the screen. In my book I have a full-screen index, and when it loads in landscape orientation you can see it's cropped to portrait width.

If you rotate to portrait and back to landscape it corrects.

It happens in iOS 5.1 simulator and device, it seems to be ok in the simulator for iOS 6.

**Comment by Simbul** [comment]
Reproduced on iOS 5.1 with the following steps:
1. Open a book in landscape mode
2. Double tap: the status bar appears but the index bar does not

**Comment by benoitchantre** [comment]
It appears that we cannot use media queries with the index page.
The document orientation isn't recognized and we cannot use max-device-width, maybe because the device-width info isn't updated on orientation change?

My index page uses media queries like other pages from my book, but only the index page (fullscreen) has problems with it's resize on orientation change.

**Comment by folletto** [comment]
Could you please open a separate issue for that? This is about the positioning of it, and your problem seems different so we probably have to look into it separately. :)
Thanks! :D

**Comment by benoitchantre** [comment]
Ok, no problem.
It's here: #637

**Comment by folletto** [comment]
Thanks! :D

**Comment by buildc0de** [comment]
I think this one can be closed :-)

**Comment by folletto** [comment]
Just as confirmation: the fixes above fix everything noted in this issue then? :)

**Comment by buildc0de** [comment]
Yep, dc183f8 fixes the issue as described above :)
1. Open a book in landscape mode
2. Double tap: the status bar appears but the index bar does not

**Comment by Simbul** [comment]
Just verified, can't reproduce the issue anymore. Thanks @waywalker.

**Comment by anjimi** [comment]
This is great. Thank you @waywalker
