### ISSUE TITLE
Code review and refactoring

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#59]
Refactor code to clean up architecture and enhance readability.

**Comment by therabidbanana** [comment]
I'm thinking a good start for supporting multiple hpubs will be breaking out as much functionality as possible into "Book" and "Shelf" models, and moving things like extraction of downloads, manifest loading, page number counts and other stuff like that into those models. 

Can you think of any issues with this plan? Does it conflict with refactoring you're already doing?

**Comment by therabidbanana** [comment]
Some initial refactoring pushed up to my fork: https://github.com/orangesparkleball/baker/tree/data-models

**Comment by folletto** [comment]
We were waiting to land three-cards, manifest and navigation before refactoring, but yes, the approach you described is going in the right direction. ;)

**Comment by folletto** [comment]
Just a quick update. This task has started, you can see the progress on the `refactor-to-reader` branch. Please be aware that things might break in that branch until it gets merged into the main branch. :)

https://github.com/Simbul/baker/tree/refactor-to-reader

**Comment by Simbul** [comment]
The task is going along nicely. Commit 1da50360e86d3b68118c7db55354b43a2ffaacbc is the first step in the refactoring process: we have moved, renamed and reorganised methods to make initialisation more streamlined.

The refactoring process is still underway, so be aware that the code in the `refactor-to-reader` branch will break some features.

**Comment by folletto** [comment]
This evening we:
- Renamed `RootViewController` to `BakerViewController`... finally!
- "Packaged" all the Baker files inside a nice Baker subfolder
- Prepared a quick tutorial to include the Baker module, following.

**Comment by folletto** [comment]
HOWTO
1. In Xcode, Create a new iOS project, for example Application --> Empty Application.
2. In the next window make sure that "Use Automatic Reference Counting" is unchecked.
3. Select the root of the project in the project navigator, select the target in the main window, scroll down to "Linked Frameworks and Libraries" and add `MessageUI.framework`.
4. In the same frameworks panel add `libz.dylib`.
5. From the menu select File --> "Add files to <project>".
6. Locate and select the Baker subfolder inside the Baker project.
7. Select "Copy items into destination group's folder (if needed)", "Create groups for any added folders" and "Add to targets" to your desired target.
8. Open the `AppDelegate.h` file.
9. In `AppDelegate.h` at the top of the file in the `#import` part add:
   
   ```
   @class BakerViewController
   ```
10. In `AppDelegate.h` after the `@interface` block add:
    
    ```
    @property (strong, nonatomic) BakerViewController *rootViewController;
    ```
11. Open the `AppDelegate.m` file.
12. In `AppDelegate.m` at the top of the file in the `#import` part add:
    
    ```
    #import "BakerViewController.h"
    #import "InterceptorWindow.h"
    ```
13. Just below `@implementation` add the `@synthesize` command:
    
    ```
    @synthesize rootViewController;
    ```
14. Inside the function `dealloc` before the line `[super dealloc];` add:
    
    ```
    [rootViewController release];
    ```
15. Inside the function `application:didFinishLaunchingWithOptions` comment or delete the line starting with `self.window`.
16. Just below that line add: 
    
    ```
    self.window = [[[InterceptorWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]] autorelease];
    self.rootViewController = [[[BakerViewController alloc] initWithBookPath:[[NSBundle mainBundle] pathForResource:@"book" ofType:nil]] autorelease];
    [self.window addSubview:rootViewController.view];
    ```
17. Put your unzipped Hpub book files inside a folder named `book`
18. From the menu select File --> "Add files to <project>".
19. Locate your newly created `book` folder.
20. Select "Copy items into destination group's folder (if needed)", "Create folder references for any added folders" and "Add to targets" to your desired target.
21. (this tutorial misses the storage of the last page and scroll position)

**Comment by folletto** [comment]
Still open:
- We still have to check the `book://` protocol behaviour (in `AppDelegate`) 
- Book download is still not working
- Create new and clean Baker app from a new Xcode project template

**Comment by folletto** [comment]
Still with some issue pending we did the merge in `MASTER`. We are almost there. :)

**Comment by bahmet** [comment]
hi @folletto ,
is the re factored code going to support "if it is html5 then it works in Baker" motto. or it is only for Hpub publishing?
thanks....

**Comment by folletto** [comment]
Hpub **IS** HTML5. What do you think the difference is? What are you missing? :)

**Comment by bahmet** [comment]
"The HPub (HTML Publication) standard is a file format designed to release rich content books in a simple and manageable package."
book ==>magazine==>script==>html5==>application==>>zzzttt==>bzzztt
I need a holiday :))

**Comment by folletto** [comment]
Exactly. It's HTML5 zipped. As simple as that. :)

**Comment by bahmet** [comment]
guys, i sent an error message to info@bakerframework.com .
thanks

**Comment by Simbul** [comment]
Given the huge changes to the codebase in version 4.0, this issue is no longer relevant, so I'm closing it.
