### ISSUE TITLE
Menu right top doest appear 

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#590]
Hi can someone helps me with this, he laker have a menu in the top on the right part, but doesnt appear  when i look in the simulator or when i prove in the device, i read somethings and it say that it have to modifi the height? its that true?
Can you help me?

**Comment by molorago** [comment]
anyone???

**Comment by molorago** [comment]
pleaseeeee????
Why doenst appear the top bar

**Comment by molorago** [comment]
@folletto Can you help me, the laker has a bar in the top with two arrows and one menu, and i dont know what does not appear? y really need your help please

**Comment by danupoyner** [comment]
Hi Monica,

Laker has built-in support for a web layout, so what you're describing is what you'll get if you view the HTML in a straight web browser rather than on an iPhone/iPad app. In other words, it's not something that appears in Baker.

Also, just a tip for these issue forums - they are well monitored and someone will always get back you promptly - there is no need to leave four messages about the same thing in one hour. Everyone here is very friendly and helpful, so don't panic.

Hope this helps,
Danu

**Comment by Simbul** [comment]
@danupoyner thanks for stepping in on this, appreciated :)

@molorago If I understand your issue correctly, I think that Danu is right: that's not something that should show up in Baker. In addition, that's probably a Laker issue, so you may get better answers on the [LakerCompendium issue board](https://github.com/ffranke/Laker-Compendium/issues).

**Comment by molorago** [comment]
thanx!!! i understand, so how can i make it???
There is a plugin or something to make the nav bar???
thanks again

**Comment by folletto** [comment]
It's better if you ask there, even if there are many people here that use Laker, that board is the best place to ask about it. :)

**Comment by molorago** [comment]
ok... bur maybe there is a way to make that the index.html dont show horizontal... Maybe verticall... and that is be placed in the top at the right side???

Thank u

I found this in the wiki 
This means there are multiple possible configurations for an Index Bar. Some examples are:

a vertical bar sticking to the left side of the viewport
a horizontal bar on the bottom (see screenshot below)
a square in the corner
a view taking up the whole space of the viewport

How can i do it verical???

THANKS A LOT

**Comment by folletto** [comment]
Just make if of that size: height that fills the entire height of the screen (or more) and with that is less of the width of the screen. :)

**Comment by molorago** [comment]
And how i make that be placed on the right or left?

**Comment by folletto** [comment]
You can't by default, to do that you have to edit the framework.

**Comment by folletto** [comment]
I'm closing this issue since no follow-up happened in more than one month. Reopen at need. :)
