### ISSUE TITLE
Newsstand Hosting Service

### ISSUE THREAD

**Issue by f3r3nc** [Simbul/baker#592]
Hi,

I am planning to build a hosting service supporting Baker's Newsstand.
The push notification part is already in production and I am getting serious about the hosting part at the moment.
If anyone would be interested in using it, please contact me.

Ferenc

@folletto if you think this issue is not appropriate, I'll remove ASAP.

**Comment by folletto** [comment]
It's great actually. We even have a tag for that: "Contribution". ;)

Keep us updated. :)

**Comment by buniden** [comment]
HI, 

I'd be interested in using this and doing some testing if you need it.

**Comment by f3r3nc** [comment]
Great, I'll keep you posted :)

**Comment by nin9creative** [comment]
Do you mean a hosting service that you'd be charging for?

**Comment by f3r3nc** [comment]
Well, yes.
Pricing structure is an open issue.
After some calculations, it can be cheaper than urban airship or magplus, by how much depending on the usage as main cost is storage and bandwidth.
The value that is added here is that I'll do the baker related integration and the scaling out so that the ones using it can focus on creating magazines.

**Comment by digipub** [comment]
I would be interested as well.

**Comment by nfeiglin** [comment]
@f3r3nc I'm interested!

**Comment by Sror** [comment]
@f3r3nc interested too!

**Comment by Simbul** [comment]
We're closing this. @f3r3nc make sure to let us know if you have news (or a release) on this!
