### ISSUE TITLE
nvalid number of items in AQGridView Issue

### ISSUE THREAD

**Issue by qusai87** [Simbul/baker#594]
Hi,

The application crashed when I  make the server offline for the first time running the app (No Cache Shelf JSON there) and run the server and try to press refresh button on the shelf.

here is the console log 

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid number of items in AQGridView: Started with 0, added 1, deleted 0. Expected 1 items after changes, but got 5'

**Comment by folletto** [comment]
This is related to issue #582. I'll close this one. :)
