### ISSUE TITLE
App Rejected: iCloud Data Storage Guidelines

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#595]
Hi everyone,

My app review came back from Apple today with a reason for its rejection. 
They stated that:
"In particular, we found that on launch and/or content download, your app stores 11.5 MB."

That is against the iOS data storage guidelines. I believe it may be trying to backup to iCloud the latest page screenshots that have been viewed. 

Basically Apple is saying that only data the the user creates can be backed up. Not data created by the application without the user knowing.

I wonder if anyone else has run into this issue?

Kind regards,

Mitchell.

**Comment by Simbul** [comment]
This kind of rejection was discussed in #233 and the underlying issue was fixed.
It may be that Apple has changed its policy since then or that the refactoring has introduced a regression, bringing that issue back.

Are you using Baker shelf from the current `master` branch? Is Newsstand enabled or disabled?

**Comment by ghost** [comment]
I am using the latest master as of about 15 days ago when I submitted my app for review.
Newsstand is enabled and everything is working in that regard.

I'll try the code Zenz put forward in issue #233. 
I'll resubmit tomorrow and keep you posted.

Kind regards,
Mitchell.

**Comment by Simbul** [comment]
There's a method in `Utils` called `addSkipBackupAttributeToItemAtPath` that does exactly that.

Anyway what I left out of my previous answer is that we'll have to go through the code and see if anything is amiss with the calls that create files ;)

**Comment by Xm4s** [comment]
Hi,

reading through the [iOS Data Storage Guidelines](https://developer.apple.com/icloud/documentation/data-storage/) we found this particular passage that kinda rings the wrong bell:

> Use the "do not back up" attribute for specifying files that should remain on device, even in low storage situations. Use this attribute with data that can be recreated but needs to persist even in low storage situations for proper functioning of your app or because customers expect it to be available during offline use. This attribute works on marked files regardless of what directory they are in, including the Documents directory. These files will not be purged and will not be included in the user's iCloud or iTunes backup. Because these files do use on-device storage space, your app is responsible for monitoring and purging these files periodically.

All data Baker saves is put in the `Application_Home/Library/Caches`, which should be already "iCloud Safe" (see point 2 of the guidelines), but has also the "do not backup" attribute setted by the method pointed out by @Simbul.

So, while is impossible that something is backed up on iCloud, maybe the rejection comes from the fact that the data saved is flagged as necessary for the app to work and so is not deleted in low storage situation.

If you can, try asking the reviewer to be more specific the problem, and keep us informed about his feedbacks.

**Comment by folletto** [comment]
Hello, is there any news on this? :)

**Comment by ghost** [comment]
Hi, there is a small amount of news. I resubmitted with the final Baker 4.0. It was rejected again.
When the app is launched it stores nothing. However, If you download an issue that is 40MB in size the storage jumps to 7.7MB without even having to open the issue. I am at a loss with this. Does Baker pre-render screenshots or any data for issues that are downloaded but not opened?

The interesting thing is that the storage size does not increase when the issue is opened. It is all stored on the download. But it cant be the actual HPUB because 7.7MB is a fraction of the size.

**Comment by ghost** [comment]
I just tested the latest master of Baker with my shelf.json connected and it produces the same result. Is someone willing to provide a link to their shelf.json so I can check if different publications produce different results? If that is the case, maybe there is an issue with my HPUB Zip files. But I cant see how that's possible.

**Comment by ghost** [comment]
Hi, sorry to past again. Disregard me asking for a shelf.json. I uploaded the Study In Scarlett book to my server and downloaded it with the latest baker master. This time the app was storing 126KB for iCloud. Due to it being a book under 3MB and my publications being between 40MB and 90MB I would have to conclude that a percentage of the book that is downloaded is not being stored in the cache or is somehow still looking to be backed up with iCloud.

Is there a solution for this? My deadline is in 7 days and I have no clue why this is happening.

**Comment by Simbul** [comment]
So I guess you had no useful new feedback from the reviewer.
As @Xm4s stated, the iOS Storage Guidelines are very clear on what gets backed up to iCloud and it looks to me like Baker is not saving anything in the folders that will be backed up.

The only file that might be backed up is `NewsstandArtwork`, which is where Newsstand stores the cover to display for the app. But this is managed by Newsstand and besides I don't think you'd end up with a 7MB image.

How are you testing how much is stored on iCloud? Have you tried running the app in the simulator and looking into the app folder on your Mac? (If you have a look at the Baker log, the path to that folder is printed out multiple times).

**Comment by ghost** [comment]
Nope Apple just referred me to what I already knew. They would not give any additional details.
I believe it's an issue that is isolated to the publication rather than the code/app. So I would say you could close this issue as I don't believe it is actually affecting others.

**Comment by folletto** [comment]
Out of personal curiosity: how are you finding the 126KB "for iCloud"?

**Comment by ghost** [comment]
I'm finding it by enabling iCloud Backup and going to the manage storage screen which shows each app and how much it is trying to backup. Additionally, we can now close this issue in saying that it was indeed the cover image that is stored in the HPUB to update the icon in the newsstand is currently set to backup. The 126KB is the size that iCloud reports for the cover of A Study In Scarlett. It seems that Apple will accept anything under about 200KB, but not the 7+ MB I was getting.

**Comment by folletto** [comment]
Hey! That's a VERY interesting discovery! :)

Thanks for the feedback! :D

**Comment by ghost** [comment]
That's okay. I hope that this thread can help anyone else who finds themselves in a similar situation with Apple.

**Comment by buildc0de** [comment]
Sounds like this one is OK to close? :-)

**Comment by folletto** [comment]
We are keeping this issue open because while solved it will be a reminder for us to double-check this before the 4.1 release. :)
