### ISSUE TITLE
Baker Private Help

### ISSUE THREAD

**Issue by nfeiglin** [Simbul/baker#596]
Hi I'm looking for someone that can help me customize Baker for my Newsstand project and set up a back end for it. I haven't had any luck with Elance and I'm willing to pay. If this post isn't appropriate for this forum please let me know and I can remove it. Once I get assistance I'm happy to post all the steps etc to help other newbies.

Thanks :)

**Comment by nin9creative** [comment]
Email me andrew@nin9creative.com

Would be interested in chatting regarding the backend :)

**Comment by nfeiglin** [comment]
Thanks Andrew - I emailed you.

**Comment by kstew** [comment]
If you  would like as well, I can show you a portfolio of various Newsstand Apps that my company has done including Apple Push Notifications, iAd's, and general knowledge of how the whole process works from the customer downloading -> purchasing -> receipt verification -> reading and any other questions you might have. Email kevins@boldisp.com

**Comment by folletto** [comment]
I'm closing this discussion since more of a month has passed without comments. Reopen if needed. :)
