### ISSUE TITLE
Discussion request: what are the alternatives for publishing books developed with Baker?

### ISSUE THREAD

**Issue by puntofisso** [Simbul/baker#599]
Hi all, I'm just wondering if anyone can help me making an inventory of all the ways we have to get books (and, in general, publications) onto the app store.

I know that with Baker 4.0 you can do
- a single app: is this compliant with the app store requirements?
- a newsstand app: do I interpret it correctly if I say that you can only do free books with Baker through this route?

It's not really clear to me how this applies to iBooks - does Baker support developing iBooks that are sold on the App Store via the iBooks channel rather than as apps/Newsstand publications?

Also, from a legal/business point of view:
- what's the best option to actually sell publications, especially if it's more than a one-off?
- is there any guide around explaining the whole procedure, including where an ISBN is neeed?

Thanks!

**Comment by Simbul** [comment]
Woah, that's quite a lot of questions :D

First of all, I think it may prove useful to have a look at the [wiki](https://github.com/Simbul/baker/wiki). I'll summarise here.

# What can you publish with Baker?

There are essentially 2 ways (actually, three) you can publish using Baker. They all rely on getting an App in the App Store.
1. A [Newsstand App](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand): Baker will display a shelf and you can publish as many issues as you like, without having to update your App.
2. A [Standalone App](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone): this is not backed by Newsstand and does not support download, as issues are bundled with the App. To publish a new issue you'll need to create a new App or push an update through the App Store.
   - If the App has more than 1 publication, it will show a shelf
   - If the App has only 1 publication, it will open it straight away (think Baker 3.2)

# Is a single App compliant with App Store requirements?

Can't see why it shouldn't. Of course - this being Apple - there are a ton of mysterious rules stating what kind of _content_ your app should have. The main reason for rejection seems to be trying to publish an App that could be as easily published through the iBooks store.

# Can you only do free books with Baker Newsstand?

At the moment, yes. That's not a limitation of the framework: just a matter of finding enough time to implement and test paid-for In-App Purchases.

# Can I publish iBooks with Baker?

No. Baker is for publishing Apps (possibly backed by Newsstand) in the App Store.

# What's the best option for selling recurring publications?

There are many frameworks around to support paid publications, though I'm not sure what the best option is at the moment. The feature will come round to Baker eventually, but it'll take a little time.
I'm sure other users will be more helpful here.

# Are there any guides?

For Baker, you can head to the aforementioned [wiki](https://github.com/Simbul/baker/wiki) and search for relevant issues in this tracker.

# Is an ISBN needed?

I'm not 100% sure on this, but I think you need an ISBN to publish through the iBooks Store, not through Newsstand.

**Comment by puntofisso** [comment]
Hi there,
thanks! In a way, I had given the wiki a quick look but what I was ideally looking for was rather first-hand experience :) 

I'm mostly worried with the point about iBooks: "The main reason for rejection seems to be trying to publish an App that could be as easily published through the iBooks store."

Also, I'm looking at the ISBN issue - I had the same impression that you have, or at least Apple guidelines only mention ISBNs within the iBooks part of the guidelines. However they say you need a different ISBN for the iBook thank you have used for the printed version.

This prompts me a question: if I want to re-publish digitally something I previously published on a printed medium, a strict interpretation of this would suggest I can only do it through the iBooks store, not Newsstand. Although it's not particularly clear. First-hand experiences, or people who analyzed this idea before?

Do you know of anyone who had issues in this context?

**Comment by ghost** [comment]
@puntofisso to publish through Newsstand, what you are publishing needs to be a periodical of some sort. If it's a book it doesn't meet Apples requirements for Newsstand. That is why it is getting rejected.

As for the ISBN issue. Books are required to have separate ISBN numbers for different formats, printed/digital/large print/etc. That is not just an Apple requirement. I work for a publisher and all of our books are offered both in print and digital thus requiring two ISBN's for every book. You even have to have a two separate ISBNs for a book that is printed in paperback and hard cover.

If you do decide to publish to iBooks I would recommend taking that ePub file and submitting it to all the other eBook stores out there. Also converting it to the mobi format for Amazon is easy to do yourself and free. That way you get the most coverage for the extra ISBN you had to purchase for the digital version of your book.

The advantage of using the Baker framework for your book is to make it interactive. I would suggest that if your book focuses more on reading to use the ebook format through iBooks. If it is more like reading a magazine with beautiful pictures and interactivity, sort of what would be called a coffee table book, use the baker framework and make it an app.

**Comment by folletto** [comment]
Is this discussion complete? May I close the thread? :)

**Comment by rossellap** [comment]
I am happy with Baker for digital magazines but I started to get confused whether to use it for ebooks to be sold on iBOOKs and Google Play or to choose some "older" format - like epub. In all, I was trying to understand whether to make a book as an ePUB or as a hPUB/app (with Baker).
darren2c57 's answer is very clear - thank you. I think he is right - if there's no particular interactivity, we'll choose epub for books.
Do you all agree with that?

**Comment by folletto** [comment]
Well, we started Baker because we feel that no standard out there is able to support effectively properly designed books, so I can't agree with that in terms of vision. :)

However I agree that it's what Apple forces you to do, so, in the end, that's what you have to do.

**Comment by rossellap** [comment]
I agree. My ideal book is the one made with Baker. The only problem is - at the moment - I am afraid to see it rejected when submitted among the applications. You are right -. it is just Apple that forces us to do that.

**Comment by Simbul** [comment]
I'll close the thread as it looks like all questions have been answered :)
