### ISSUE TITLE
Index Feature

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#602]
Hi,

I have been investigating a couple of ways to increase the simplicity of the Baker Framework for end users and developers alike.

I would love to see if moves could be made to build the book index with Xcode in Interface Builder to have the titles and images populated by the current issue's details to reduce the size of the ZIP files uploaded by not needing to attach thumbnails for each page for the index and remove the need to customise the index for every issue to change the title of the page.

I think this would be excellent and it would also allow us to more easily have the current page centred in the index all the time to allow users to easily navigate without confusion.

Kind regards,

Mitchell.

**Comment by folletto** [comment]
Hello! :)

Thanks for posting. If you are able to do any progress on that, please update Issue #411 that is related to this suggestion. :)

Thanks! :D
