### ISSUE TITLE
Vertical pagination: more flexibility

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#607]
When we use the native vertical pagination, this works for the whole book.

It would be nice if we could have a way to disable it on some pages/articles.

**Comment by folletto** [comment]
Uhm... I probably need a clarification. From what you are saying, it seems to me that you could just make the page not higher than the screen and then you don't have pagination.

What is it doing now and what would you like it to do exactly?

**Comment by benoitchantre** [comment]
If the page is smaller than the screen height, I don't have pagination as expected.

What I would like to do is to disable the vertical pagination for the table of contents (or another page). This page is longer than the screen height, but it is better to use the standard scroll with the layout of this page.

**Comment by folletto** [comment]
Uhm... Are you talking about the `book.json` flag `-baker-vertical-pagination`?

**Comment by benoitchantre** [comment]
Yes

**Comment by danupoyner** [comment]
For example, in The New Yorker app, some of the articles scroll continuously while some are paginated. It depends on the flow of the piece. Whereas the book.json flag is an all-or-nothing proposition, it would be nice to have the granularity to toggle it per .html page. Am I correct in understanding you Benoît?

**Comment by benoitchantre** [comment]
It's exactly that.

**Comment by folletto** [comment]
Ok then, now it's clear. :)
We'll see what we can do. :)

**Comment by benoitchantre** [comment]
Thanks

**Comment by folletto** [comment]
We just received the pull request #620 from @danielreiser that implements this. :)

**Comment by folletto** [comment]
Add this line in the head of the HTML document to enable it programmatically: `<meta name="paged" content="YES">`.

**Comment by danupoyner** [comment]
Fantastic! And I see the wiki is already updated :)

**Comment by benoitchantre** [comment]
Wow! Thanks everybody

**Comment by thejtate** [comment]
@danielreiser @folletto Thanks again for adding this bit of functionality! Really needed it for a project I'm working on this month. Been so impressed with Baker, just keeps getting better and better.

**Comment by folletto** [comment]
Thanks! Given this was a community contribution, I think these compliments are twice as valuable. :+1:

**Comment by anjimi** [comment]
Hi, this is certainly a useful feature. I just need to check, should the -baker-vertical-pagination property in the book.json file still apply? I've downloaded the latest master version of Baker and am testing it with my existing book which is published in our current app using Baker 4.0. I have -baker-vertical-pagination set to true but vertical pagination is not applied on my book pages. I tried adding the new meta tag <meta name="paged" content="YES"> to a page and that page then has vertical pagination.

As I understood from the wiki the -baker-vertical-pagination setting applies to the whole book, and the meta tag is used to alter an individual page:

-baker-vertical-pagination (_boolean_, default: false):
Whether vertical page scrolling should be paginated in the whole publication. Since 4.1 this setting can be overridden on a per-page basis by adding the tag meta name="paged" content="YES" inside the head tag of the HTML file.

Have I misunderstood?

**Comment by folletto** [comment]
It might be a bug. Could you please open a separate issue? :)

**Comment by anjimi** [comment]
Ok, sure: https://github.com/Simbul/baker/issues/827
Thanks

**Comment by folletto** [comment]
Thanks! :)

**Comment by airterjun** [comment]
Hi I saw this article and I think this is a right page to asking about -baker-vertical-pagination.
So, I just newbie and I try building some APPS using baker framework 4.2, and in book.json I set -baker-vertical-pagination to TRUE and the page doing good and working like what I want, but there is one think make me not happy with that, so I try to add some navigation panel ( menu to jump to the page ) on top and social sharing button in the bottom of page on the HTML file and I set the position to fixed on CSS, now when I try to click on each menu the page not goes to the right page, example : if I try to click on top navigation or click on each link navigation then the page goes to the previous page or goes to up, also when I try to click on social button on bottom the page will scroll to the next page or goes to down not goes to right url.

Can anybody help me with this situation???

Sorry about my bad English :8ball:  :)

**Comment by folletto** [comment]
Hello there! :)

This board is closed, and kept alive for historical reasons only. You should try to ask on the new one here:
https://github.com/bakerframework/baker/issues

Please also open a new issue, don't add a comment to existing ones, it helps people helping you and keeping track of the issues. :)

**Comment by airterjun** [comment]
Ok Thanks folletto :)
