### ISSUE TITLE
InfoPlist.strings listed in red in Baker.xcodeproj v4.0

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#608]
When you open the Baker folder in Xcode and then the Supporting Files folder, there's an InfoPlist.strings listed in red (file is missing).

![Capture d e cran 2013-01-03 a 09 36 45](https://f.cloud.github.com/assets/1521015/40100/10591b70-5581-11e2-8934-9ea98d533a0d.png)

**Comment by folletto** [comment]
It shouldn't be needed, but that's odd indeed. Thanks for pointing it out. :)

**Comment by benoitchantre** [comment]
Thanks for your work on this project and for the support.
