### ISSUE TITLE
Developing for Newsstand and stand-alone in the same project?

### ISSUE THREAD

**Issue by bsjosten** [Simbul/baker#612]
I am developing a Newsstand application. However, I find that having to zip the current state of the book into an hpub, and then downloading into the Newsstand app is timeconsuming, when all I am trying to do is work on the actual book.

Therefore, I would like to simply download the book I am working on as in the stand-alone app, directly from Xcode into my iPad.

Is there a way to set up a single Xcode project so that you could easily toggle back and forth between Newsstand and stand-alone?

Or is there another way to speed up the book update/build/download to iPad cycle?

Thanks,

/Bo

**Comment by tstegart** [comment]
I use an old version of Baker for testing the newest issue because of this exact problem, so I'd like to hear what other people are doing as well to speed up development.

**Comment by folletto** [comment]
I'd advise to prepare the whole publication just by using Safari Mobile, and when all the pages are in place, working and with the right visual, push them as a Baker Hpub.

The second, incremental step would be to setup first Baker in standalone, test, verify that the Hpub works, and just after that build the Hpub and test with Newsstand.

I hope this helps. :)

**Comment by Simbul** [comment]
@bsjosten this thread is extremely old, but I'll answer anyway in case it helps someone.

Most of the steps to go from Newsstand mode to Standalone mode are required by Apple's review process. This means that the bare minimum to switch from one mode to the other is to add/remove the `BAKER_NEWSSTAND` constant declaration.

You can set up a Standalone app and work on your book inside the `books` folder. When you're ok with the book, you can package it into an HPUB and test the Newsstand integration.
When you're ready to submit to Apple, just remember to remove the `books` folder.
