### ISSUE TITLE
Back end system for Baker

### ISSUE THREAD

**Issue by nfeiglin** [Simbul/baker#613]
Hi Guys - I was just thinking that it would be great if some sort of back end code is written that will allow users to easily distribute their content, track subscribers etc. Are there any plans to do this?  Also is there any way to sell issues through in app purchases and paid subscriptions?

**Comment by nin9creative** [comment]
I may have some news on this shortly....

Andrew

**Comment by nfeiglin** [comment]
Looking forward to it @nin9creative  - If you need any help testing I'm happy to give it a shot albeit with my limited knowledge.

**Comment by nin9creative** [comment]
I think I will be looking for beta participants shortly.... :)

**Comment by tekdope** [comment]
Sounds very interesting! Can't wait to beta test :) :+1:

**Comment by nin9creative** [comment]
I&#39;m planning on posting something here by the end of this weekend with details.  Stay tuned!

**Comment by teckmonkey** [comment]
I'd be interested in some beta testing also

Tim

**Comment by nin9creative** [comment]
Cool.  Like I said - will post some more details shortly.  I'm excited about it :)

**Comment by nin9creative** [comment]
Hey guys...  I'll spill the beans a little bit here.  I've been working on a backend system for Baker based applications for a little bit now and have been making some good progress.  I was actually going to wait until it was a little further along before posting about it, but as I see many people are starting to ask or wonder about a way to manage the backend of their Baker publications I figure I might as well post this now.

I'm looking for some people to be involved in the Alpha (not enough complete yet to call it a Beta) :) of my solution that I'm calling MagRocket.

As it sits right now I have a slightly customized version of the current Baker 4.0 shelf that supports some of the integration features with the backend that I've been developing.  It's pretty much based on open source software such as PHP, Slim Framework for API, MySQL etc.  I'm using the Twitter Bootstrap framework for the administration front end and it looks pretty nice and clean.

I am planning on posting all of this as Open Source on GitHub eventually when it gets closer to a feature complete 1.0 state.  However prior to that I'm looking for some Alpha participants that can help test it out or even contribute.  I have private repositories on GitHub that I'm using now for development and will shift that over to public repos when the 1.0 release is finished.

If you'd like to take a look and sign up to participate, you can find some information over at http://www.magrocket.com

![MagRocket](http://www.magrocket.com/wp-content/uploads/2012/12/slider-image-magrocket-11.png)

I know that there has been some discussion with the main Baker guys about potentially creating an interface definition for Baker to work with different backend systems.   I certainly don't want to step on any toes with this, but I personally have the need for a solution like this and figure I might as well share it with others!

Andrew

**Comment by teckmonkey** [comment]
super excited,,, def signed up,, this is perfect as i was just looking for back end stuff,, finding the in's and outs, 

thanks

tim  aka teckmonkey

**Comment by tekdope** [comment]
Super Excited too. just signed up, Can't wait to put my hands on and see how i can help.

Thanks!

**Comment by nfeiglin** [comment]
Wow @nin9creative MagRocket looks great! I signed up :)

**Comment by ghost** [comment]
This looks excellent. I would love to help you put in the testing process. I'll sign up now. :)

Kind regards,
Mitchell.

**Comment by nonuts** [comment]
sounds great, @nin9creative ! count me in, I submitted The Nimble Magazine http://nimble.nonuts.de last week, so I would love to support where possible.

**Comment by nin9creative** [comment]
Cool.  Glad there is some interest.  I will be sending an email over to whoever signed up by Monday evening US time with information on how to take part.  

I have moved the code to private repos here on GitHub to make it easier - however that means that I will need your Github ID's to grant access (not sure if I can do it by email address or not)...  Will need to check that out.

Thanks!

**Comment by ghost** [comment]
You know I'm in

**Comment by yitweng** [comment]
just signed up :)

**Comment by anjimi** [comment]
Magrocket looks great! I signed up :)

**Comment by killer1loop** [comment]
Andrew, we would be happy to collaborate on the project. We missed the launch of your service, but we definitely look forward to be of help, let us know if we can help in some way.

**Comment by teckmonkey** [comment]
What's up Andrew? Got the cc

**Comment by teckmonkey** [comment]
Ok help me pick vps or dedicated server? Value n speed? 

Have issue set for testing need to set up back end. 

Also def want in app purchase at some point .. Or the ability to add I add framework 

Thoughts?

**Comment by nin9creative** [comment]
I have been a fan of using VPS for the past few years.  The flexibility that they allow and the managed solutions that companies offer is great.  Plus you can start out smaller and expand quite easily as needed.  I currently have a VPS with both KnownHost and WiredTree...

http://www.knownhost.com/vps_packages.html

They also have a current 15% discount for the lifetime of your account http://www.knownhost.com/specials.html

I have a VPS-2 with them.  It's been fast and very stable.

I also have a VPS with WiredTree.

https://www.wiredtree.com/managedvps/

I have their VPS1000.

**Comment by nin9creative** [comment]
Basically what I've found is that Shared Hosts are very finnicky with their Terms of Service.  VPS or Semi/Dedicated are more open to allow you do whatever you want.

**Comment by teckmonkey** [comment]
vps it is,,,, there cheap enough per month,, and i can always go up as i grow,,, 3,000 gigs bandwidth isn't to bad,, as I'm just in testing phase,, distribution will follow in feb

**Comment by TheCrucible** [comment]
RackSpace is excellent so far also.

**Comment by folletto** [comment]
I'll close this issue, keeping issue #639 open for this since it's more recent. :)
