### ISSUE TITLE
v.4.0 - demo project always starts from 10th page

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#616]
Hi, All!

I'm a newbie in Baker.
I've downloaded the sample project and played with it a little bit.

Now, I've got the strange situation - 
my project always starts from 10th page   8-\

I even set up the "-baker-start-at-page" to "3"
and it did not helped.

The solution of https://github.com/Simbul/baker/issues/405
does not look relevant, because, I was unable to find
the code of method "initBook" in Baker v.4.0

What I am doing wrong?

**Comment by folletto** [comment]
Baker stores automatically the last page you visited, when it closes normally.

Did you try a proper cleanup, removing also the app from the simulator or device? :)
https://github.com/Simbul/baker/wiki/Proper-cleanup

**Comment by divlv** [comment]
Thanks a lot!

The 1st option helps - "Remove the app from the iOS Simulator."
I really didn't removed it from simulator, as I do in real iPad - with "shaking icon" ;-)

Now - it's working as expected ("-baker-start-at-page", ect.)

**Comment by folletto** [comment]
Great! :)
