### ISSUE TITLE
Paid subscriptions

### ISSUE THREAD

**Issue by moushik** [Simbul/baker#617]
Sorry, I'm a bit confused:

I know Baker 4.0 has full Newstand support with Free subscriptions support, the question is:
will it work with Paid subscribtions?

**Comment by folletto** [comment]
You have to implement it yourself, right now the native, existing support is only for the free ones.

**Comment by moushik** [comment]
Thank you folletto!

**Comment by folletto** [comment]
You're welcome. :)

**Comment by teckmonkey** [comment]
Ill have to read about paid subscription implementation ...
