### ISSUE TITLE
360° picture

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#618]
I have searched some solutions to display a 360 picture in Baker.

jQuery Reel seems to be the better solution with many configuration options, but it doesn't work with Baker. I tried also the jQuery Sprite Spin plugin with the same result.

To test them, I have made a simple page with links to load their demos in my test page.
http://jquery.vostrel.cz/reel
http://spritespin.ginie.eu/examples.html

I can see the plugin loads the pictures successfully, but then I can't move them. What happens is that I move the page.

When I use links with baker referrer, they doesn't work either in the modal view.

My tests were made with Baker v.3.2.3 and v.4.0

I found also that the threesixty demo from Apple works in Baker if I load it into Baker using a link, but this demo doesn't work when I download the files, even with Safari (desktop version).
https://developer.apple.com/safaridemos/showcase/threesixty/

Have you an idea why those jQuery plugins doesn't work?

**Comment by benoitchantre** [comment]
This demo works: http://www.albanx.com/demo3d/index.php with the same test procedure.

**Comment by alexbar10** [comment]
Hi, i also want to include this feature in my app, do you have a solution for this?

**Comment by benoitchantre** [comment]
Not yet. I don't have the source of Viewer 3D to make a real test.

**Comment by alexbar10** [comment]
Ok I'm gonna try to deal this issue, if i find something useful i'm gonna post it.

**Comment by benoitchantre** [comment]
If you are able to understand why jQuery Reel doesn't work in Baker, it would be great, because this is a good plugin and it is open source.

**Comment by folletto** [comment]
Is there any update on jQuery Reel? :)

**Comment by benoitchantre** [comment]
I didn't found enough time to give a new try.
@alexbar10, do you have a solution?

**Comment by alexbar10** [comment]
Not yet. I've been focused on other features

**Comment by Simbul** [comment]
Closing as this has gone stale.
