### ISSUE TITLE
Disable shelf view in 4.0 for single publications

### ISSUE THREAD

**Issue by atracht** [Simbul/baker#619]
Is it possible to disable the shelf for single publications (like a book) in baker 4.0?

**Comment by folletto** [comment]
If you work in standalone mode and you put just one publication in, it should start with just that issue loaded without shelf. No need to disable anything. :)

**Comment by atracht** [comment]
Ah, you are correct. For some reason despite cleaning the app, I had to remove the baker app on the iPad Simulator home screen and do a new build and it works fine. 

I had used baker 3.2 previously. 

When it first launch it showed the included book with a cover, and a duplicate with no cover.

**Comment by folletto** [comment]
Yes, unfortunately the Xcode development stack does a pretty aggressive caching and cleaning is often required. :/

I'm glad it worked tho! :D

**Comment by thejtate** [comment]
This was driving me nuts too. I recently updated from 3.2 to 4.0 and didn't realize Xcode was so agressive with caching. Thanks for the post @atracht!
