### ISSUE TITLE
Orientation blocked in the code?

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#62]
Hey guys, 

I uploaded my application, but Apple has recommended that I support the application, at least the vertical orientation in two directions.

I'm trying to implement the method "shouldAutorotateToInterfaceOrientation" but it seems that there is something in the code that blocks their operation.

I have reviewed the pull nº6 but I can not working in 1.1

Do you have any ideas? Thanks

**Comment by folletto** [comment]
Interesting, yesterday they just approved our 5x15 app updated to 1.1... however the rotation is something we are adding in the current master, check it out. ;)

**Comment by frantovar** [comment]
Thanks Folleto!! just in time! XD
