### ISSUE TITLE
In-App Purchase for single issue (IAP)

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#621]
Baker should support buying single issues on the shelf by using In-App Purchase.
This only applies to the Newsstand version of Baker.

To enable In-App Purchase for an issue, a `product_id` parameter will have to be specified in the shelf JSON, e.g.:

``` json
[{
  "name": "a-study-in-scarlet",
  "title": "A Study in Scarlet",
  "info": "The original masterpiece by Sir Arthur Conan Doyle",
  "date": "1887-10-10 10:10:10",
  "cover": "http://localhost/baker/a-study-in-scarlet.png",
  "url": "http://localhost/baker/a-study-in-scarlet.hpub",
  "product_id": "com.example.issues.a_study_in_scarlet"
}]
```

**Comment by tablazines** [comment]
The code above.. Is that all it takes to implement a single issue purchase?

**Comment by Simbul** [comment]
No. This thread tracks the feature, but we are still working on implementing it ;)

Eventually, when the feature is completed, all it will take should be the JSON code above plus the creation of the single issue in iTunes Connect.

**Comment by Simbul** [comment]
This feature is currently being implemented in the [single_purchase](https://github.com/Simbul/baker/tree/single_purchase) branch.

**Comment by Simbul** [comment]
Commit 2f275965f4489acc15a38100207c492bc902d22f has brought In-App Purchase into the `master` branch.
This means it is possible to create an App with paid-for issues.
Also, a "Restore purchases" button has been added.

Note that auto-renewable subscriptions have **not** been implemented yet.
This means the only available subscription is the free subscription, which arguably does not make a lot of sense with paid-for issues. However, we thought it valuable to bring the code back into `master` so that people could start playing around with it.

**Comment by drking0211** [comment]
I am little confused guys with this feature and need some clarity here please.

Have been working on other projects for the past few months and have just got back up to speed with 4.0.

The Free Subscription now seems cool and the shelf works well. Good job everyone.

My question is does 4.0 handle single IAP  I see that there is an addition to the shelf.json:

"product_id": "com.example.issues.a_study_in_scarlet"

But does that mean that single issues are handled within the IAP at iTunes?

Any help or pointers greatly appreciated.

Regards

David

ps. I am a speaker at the London Publishing Expo later this month and will be featuring the integration of Baker and our Rabbit Digital publishing platform that delivers HTML to Baker.

**Comment by folletto** [comment]
Version 4.0 doesn't handle IAP right now. As you see at the beginning of the page, this is a feature still open and is targeting the 4.1 milestone. :)

Right now it's possible to test it in the `master` branch from github, but it's unlikely to be accepted by Apple without paid subscription support as well.
So to answer your question: the issues are created within iTunes Connect, and they need to match and have everything set. The ID used there is the "product_id" in the shelf. However, when you introduce the concept of subscriptions everything starts being a little more complicated...

**Comment by drking0211** [comment]
Okay, I understand.

I spent some time a while back using Urban Airship as the push and pull from iTunes is a pain with the tokens etc.

I think I will have a look at this again as a work-around.

Regards

David

**Comment by Simbul** [comment]
Closing this as auto-renewable subscriptions have been added with commit 7cc7bee5c727fe157f83787a86d74e7c033c85b2 (and previous commits).

A draft for a tutorial can be found at https://github.com/Simbul/baker/wiki/In-App-Purchase-tutorial

**Comment by trudderham** [comment]
One quick question: do we have a tutorial for standalone apps that include in-app purchases?

**Comment by folletto** [comment]
The Standalone mode have all the issues embedded, so it doesn't and can't have IAP. :)

**Comment by trudderham** [comment]
Hmm, am I getting confused? I spotted this issue where it appears to be possible:
https://github.com/Simbul/baker/issues/665

**Comment by folletto** [comment]
The problem there was in getting the Standalone mode working, not about IAP. Sorry. :)
