### ISSUE TITLE
Launch specific page within app using custom URL scheme

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#622]
We have a need to launch an app, and load a specific page, via a QR code.

This would be for a non-Newsstand app, with one book bundled with the app.

I believe this could be done using a custom URL scheme, but being a web developer and not very Xcode-savvy I'm getting stuck on the implementation.

It's a bit like https://github.com/Simbul/baker/issues/465 which was about implementing a back button, but would need to load the page from an external URL call.

**Comment by folletto** [comment]
It's pretty much all custom development, I think you could have a better luck asking on StackOverflow.

Here you can find the official Apple documentation, under "Implementing Custom URL Schemes":
http://developer.apple.com/library/ios/#documentation/iphone/conceptual/iphoneosprogrammingguide/AdvancedAppTricks/AdvancedAppTricks.html#//apple_ref/doc/uid/TP40007072-CH7-SW50

**Comment by anjimi** [comment]
Thanks @folletto. I got as far as adding a custom URL scheme to a baker Xcode project, and can launch the app from a custom URL call. I wondered if someone here might be able to point me in the right direction for the code which loads up individual pages in baker, which I could modify to work with external URL call.

**Comment by folletto** [comment]
Ok, now I got it. :)

Have a look at `AppDelegate.m`, in `application:didFinishLaunchingWithOptions:` you see around line 90 (under `NSLog(@"====== Newsstand is not enabled ======");`) the line that initializes a single book:

```
self.rootViewController = [[[BakerViewController alloc] initWithBook:[[books objectAtIndex:0] bakerBook]] autorelease];
```

You have to "create" that `BakerBook` object before passing it to the function, with the correct parameter. Have a look at the class to see how it works. :)

**Comment by anjimi** [comment]
Ok, I'll take a look there. Thanks @folletto :)

**Comment by folletto** [comment]
You're welcome. :)

**Comment by folletto** [comment]
Hi @anjimi may I close this issue? :)

**Comment by anjimi** [comment]
Yes, sorry, we decided to do this a different way in the end.
