### ISSUE TITLE
Paid Subscription support (IAP)

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#623]
As a user I want to be able to subscribe to a paid publication (In-App Purchase Paid Subscription support, Renewable and Non-Renewable.).

http://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/StoreKitGuide/APIOverview/OverviewoftheStoreKitAPI.html

**Comment by nin9creative** [comment]
:)

**Comment by Simbul** [comment]
I think we should only implement Auto-renewable subscriptions and leave out Non-renewing subscriptions, as I can't see any advantage in having a Non-renewing subscription for a Newsstand application.

**Comment by nin9creative** [comment]
True, I'd only do auto renewable.  A user can always cancel it if they want.

**Comment by Simbul** [comment]
Closing this as auto-renewable (paid) subscriptions have been added with commit 7cc7bee (and previous commits).
