### ISSUE TITLE
How to run baker on ios simulator withour internet connection

### ISSUE THREAD

**Issue by rtshittu** [Simbul/baker#626]
Hi,

I have followed all the steps to get a new magazine and bake it.  It run successfully.  it keeps bringing that i need internet connection to make it run.

i would like to view it since i have internet connection on my mac.

what should i do please?

**Comment by folletto** [comment]
Which steps did you follow, could you give us the link? The Newsstand or the Standalone tutorial in the wiki (link above)?

**Comment by rtshittu** [comment]
I followed the step by step here http://bakerframework.com/tutorials/30/basic.

When i run it and expected to see my html5 and css3 design.  It kept displaying a box saying" No Internet Connection  An Internet connection is unavailable.  some features of this application require an active connection"  with an "ok" button at the bottom.  i clicked ok and nothing happened.

I could see nothing. 

Please note that i have change the icon following Apple's standard and i have my html bundle working fine after i finished with the design.

i have equally listed all files in the book.json.

I want it to run on Newstand.

Thanks a lot for your prompt reply.

**Comment by folletto** [comment]
That tutorial is "3.0", it's for Baker up to version 3.2, not for Baker 4.0. 
Check the wiki above for the correct tutorial. :)

**Comment by rtshittu** [comment]
Ooops!

Ok let me check it.  I will get back to you pretty soon.

**Comment by inevitablerharj** [comment]
Hello everyone, I followed this steps in the wiki page but the dialog "No Internet Connection" is still popping up. Pls help me look into this, I believe am missing something

**Comment by folletto** [comment]
I have to give the same answer to you as well: please give more informations! :D
1. Which tutorial are you following? Newsstand or Standalone?
2. If you followed the tutorial, could you then follow https://github.com/Simbul/baker/wiki/Problems-and-Debugging and tell us the details you get from that?

**Comment by sportyguy209** [comment]
I'm a novice in all of this, but in hopes that this will help you move in the right direction, I'll provide you with my experience...I just had the same thing happen to me. I'm transitioning from Baker 3.0 to 4.0 and changed the app from Newsstand to Standalone. I got the "No Internet Connection" message when I renamed the folder baker-framework-4.0. When I reverted back to the original name, I no longer received that message and everything worked as expected. So, I suspect that there are other resources that need to be changed when you update the folder name so they all match.

**Comment by rtshittu** [comment]
I followed the tutorial but still no headway.  I want to re-do it and share my experience.  I just finished with my html5 parts.

I hope i get it work this time. I am using baker 4.0 framework

**Comment by rtshittu** [comment]
Now i still have same issue.  Is it not possible to test run the app on my ipad. It keeps bringing "no internet connection"

Please I need help. i have followed everything on the link above except that i have not hosted my files anywhere. just on my mac book.

please help me out.  I want to write a success story too

**Comment by folletto** [comment]
Please, please, please! Add details, otherwise it's _impossible_ for anyone to help. :D 
Add the Hpub. Code. Debug log. Did you follow the Debugging steps from the [specific page in the wiki](https://github.com/Simbul/baker/wiki/Problems-and-Debugging)? Which tutorial? Where does it stop? Can you share the `shelf.json` file? Did you check it? Is everything up to date? Did you try Standalone mode? Does it work?

**Comment by dymv** [comment]
1. Put files on your mac http://dl.dropbox.com/u/930742/Screenshots/tbn9.png
2. Navigate to this directory in Terminal.app and run `python -m SimpleHTTPServer 8080`
3. After that you should be able to access your files using address like this http://dl.dropbox.com/u/930742/Screenshots/670d.png
4. Set correct url in `shelf.json`:
   e.g. your mac have ip=192.168.1.45 in local network

```
[
  {
    "name": "a-study-in-scarlet",
    "title": "A Study in Scarlet",
    "info": "The original masterpiece by Sir A. Conan Doyle",
    "date": "1887-10-10 10:10:10",
    "cover": "http://192.168.1.45:8080/a-study-in-scarlet/a-study-in-scarlet.png",
    "url": "http://192.168.1.45:8080/a-study-in-scarlet/a-study-in-scarlet.hpub"
  }
]
```
1. In `book.json`:

```
...
    "url": "book://192.168.1.45:8080/a-study-in-scarlet",
...
```
1. In Xcode, file `Contstants.h`

```
...
        #define NEWSSTAND_MANIFEST_URL @"http://192.168.1.45:8080/shelf.json"
...
```
1. Connect your device to network your mac connected to. Results:
   https://dl.dropbox.com/u/930742/baker/result_01.PNG
   https://dl.dropbox.com/u/930742/baker/result_02.PNG
   https://dl.dropbox.com/u/930742/baker/result_03.PNG
   https://dl.dropbox.com/u/930742/baker/result_04.PNG

Hope that helps

**Comment by folletto** [comment]
Awesome! Thanks. :D

**Comment by rtshittu** [comment]
Hurray guys,

It worked!!!!!

I can see it.

I am so happy

Thanks @eugenedymov and @folletto 

I followed @eugenedymov step by step and it fixed it

**Comment by moloragom** [comment]
Hi, i have a question, always the ip is the same? for local?
Thanks

**Comment by moloragom** [comment]
:( Can anyone help me with this, i already do every steps, and still dont work

**Comment by rtshittu** [comment]
Hi moloragom,

I guess where its not working is the command line on your terminal.

Please follow every step on @ eugenedymov comment.  you will be fine.  Also use the jsonlint tool to verify your shelf.json file.

Try this it will work.

**Comment by folletto** [comment]
Ehm guys. Let's not reopen closed issue. If there's need, open a new issue. :)
