### ISSUE TITLE
Add more items to the index

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#627]
Hi the index bar that is activate with the toc, have only 4 items if i add more pages i need to add more itemsin that index, i trie but the new items appear in other line...
Can some one help me?

**Comment by aspek** [comment]
fix width in .css

**Comment by molorago** [comment]
In which one?

**Comment by stemmo** [comment]
You need to adjust the width of your index view in nav.css.
And also book.json, if you have specified the width there.

**Comment by molorago** [comment]
Thx!!!! :)
