### ISSUE TITLE
Background image behind pages instead of flat color

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#628]
When you scroll to top or bottom, you have a gray color appearing behind the page when it bounce.

Is there a way to replace the gray color by an image?

**Comment by folletto** [comment]
There's no way in Baker, however you might try to code that by yourself, but I'm not sure if it's possible since it's a default part of the iOS interface. 
I'll leave this open for a while to see if someone has some better knowledge of that. :)

**Comment by benoitchantre** [comment]
Unfortunately I have no knowledge of Objective-C.
In the case we could use and image instead of the flat color, I can contribute with the graphic part.
My idea was to have an image similar as what you see in Safari mobile (gray lined background image).

**Comment by danielreiser** [comment]
Update: Actually there's already a background-image which is defined in book.json:
    "-baker-background-image-portrait": "gfx/background-portrait.png",
    "-baker-background-image-landscape": "gfx/background-landscape.png"

To make these visible you have to comment out the line 1556 & 1557 in BakerViewController.m
    currPage.backgroundColor = webViewBackground;
    currPage.opaque = YES;

hope that helps :)

**Comment by benoitchantre** [comment]
Thanks @danielreiser. That works, but the idea was to use a different image than the one that is shown when the page is loading.

Here's a sample file
![](https://devimages.apple.com.edgekey.net/assets/elements/layout/background_linen.png)

I would like to use the same image for every book in the app. It should not be defined in the book.json file.
Is it possible?

**Comment by folletto** [comment]
Ok I'll try to clarify a bit:
1. If you want to specify the loading background, is as @danielreiser pointed out, part of the book.
2. If you want to override the native Apple scrolling behaviour (the texture you shown) you have to hack into Apple's code itself.

As a byproduct of certain `WebView` bugs we had to circumvent (white flash, delayed loading, ...), if you set the component as transparent you can see below the background specified in the book, but that means you are relying on a workaround that might not be there in the next version (and I don't mean just "Baker version" but also "iOS version").

I hope this helps. :)

**Comment by benoitchantre** [comment]
I understand. It's better to let it as a flat color.
I think we can close this issue.

Thanks.
