### ISSUE TITLE
Shelf customisation: documentation

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#629]
In the img folder of the shelf, there are some files for iPad and iPhone in landscape and portrait orientation, but also 2 images with 568h at the end of their name.

What is the purpose of the files ending by 568h?

A little document about ressources (images, strings, colors) that can be easily customised by a publisher would be welcome on the wiki.

**Comment by DrBOZ** [comment]
Hi Benoit!

They are the shelf background image (.png) files for the 4 inch retina display (iPhone 5) in portrait and landscape mode.

**Comment by benoitchantre** [comment]
Thanks for the quick response!

**Comment by folletto** [comment]
Hi @benoitchantre, thanks for the question. You already had the answer, so I will just add something on the reason why you didn't find anything about it: we tend to avoid documenting things that are directly part of the iOS SDK, and as such are documented by Apple.

The reason for this is to avoid us to re-write Apple's documentation (even if we are aware it's not a great documentation), something that would be a big, big effort both for size (there's a lot of it) and maintainability (every major version changes something).

So, we can just refer you to the Apple documentations for these topics. :)

http://pinchmultimedia.com/blog/ios-5-icon-sizes-and-names-new-ipad

Thanks! :D

**Comment by benoitchantre** [comment]
Thanks for your comment @folletto.
