### ISSUE TITLE
Support for Landscape / Rotation?

### ISSUE THREAD

**Issue by jono2010** [Simbul/baker#63]
This is a great tool, thank you.  Is there any planned support for landscape in the future?

This would relate the the app startup screen and the pages.  For example using the following format or moving the page orientations into folders (ie landscape/ and portrait/)

page_01_landscape.html
page_01_portrait.html
page_02_landscape.html
page_02_portrait.html
page_03_landscape.html
page_03_portrait.html
page_04_landscape.html
page_04_portrait.html

Thx
Jon

**Comment by folletto** [comment]
It was the issue #6, now completed and closed. It's already in the master branch and will be the next version of Baker. :)
