### ISSUE TITLE
What are our font choices in UIConstants.h?

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#631]
I've noticed the font in the shelf view is editable, for example:
   #define ISSUES_ACTION_BUTTON_FONT @"Helvetica-Bold"
Are there other possible font choices then? How do I know which ones are available?

**Comment by Simbul** [comment]
Have a look at this list: http://support.apple.com/kb/HT5484

**Comment by tstegart** [comment]
Thanks! I didn't realize iOS had built in fonts.

**Comment by tstegart** [comment]
Do we need to do anything special to use fonts on this list? I've tried using Arial Bold, but it doesn't work. Do we need to embed them? Use special characters? I've tried Arial-Bold, without the space too, still doesn't work.
