### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by antontushnov** [Simbul/baker#632]
Hi!
I've making app with Baker & Laker (http://www.lakercompendium.com/)

I don't want to pay 99$ for testing app on my iPad, cause i didn't sure - did will it works?

Can you help me? See screenshots. There are some warnings. What should I do?

Thanks! 
![1](https://f.cloud.github.com/assets/3263854/64134/b27a6e92-5e30-11e2-8a8b-637363a390c0.jpg)
![2](https://f.cloud.github.com/assets/3263854/64133/b277e866-5e30-11e2-9440-52f16768a50e.jpg)

**Comment by Simbul** [comment]
Those warnings are fine. They are due to a library we're using and will not affect the application.

You should really test on a real device before releasing an app though ;)

**Comment by antontushnov** [comment]
Thanks!
Yes, I know. But i noob of iOS developing, and don't want to pay if it will not work :)
I.E. if i pay i can test it on my iOS devices?

**Comment by folletto** [comment]
Yes. The developer account gives you access to Apple documentation, Developer forums and the ability to test on device and publish on the store. :)
