### ISSUE TITLE
Size of images

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#634]
What size of image i put, for not cut the images in landscape or portrait

**Comment by folletto** [comment]
Could you please be more descriptive? Which image? Where? :)

**Comment by molorago** [comment]
Im using baker, but the magazine that i have to do, only have images, not text.
My images are cut when i run the app, in landscape and also in portrait.
I want to know what wil be the size that i have to put the images for not to cut and show complete in both orientation.
THANKS

**Comment by folletto** [comment]
@molorago we can't really support the HTML side of Bake, I'm really sorry. What you are asking is basically how to design an HTML page for iPad, and well... you can find plenty on documentation all around the web.

I'm sorry about this, but unfortunately our time is limited. Try googling for some resources about developing on the iPad with HTML or asking on StackOverflow.
