### ISSUE TITLE
Automatic screenshots in iOS simulator

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#636]
In the aim simplify the work to build the index in html, would it be possible to extend the function that makes the screenshots with iOS simulator?

A first step could be to take screenshots of every pages you browse in the iOS simulator, not only the top part and to name them with a suffix "index".

Then, if the screenshots taken for the index could be taken at full height and resized at a given width it would be superb.

**Comment by folletto** [comment]
If it's a "support" tool to build the index thumbnails I think it should be / could be a separate tool from baker. It's likely you could even do it as a Chrome extension for example. :)

Is that a correct assumption? ;)

**Comment by benoitchantre** [comment]
Yes, I think it falls in the category "support" tool, but it was an idea to go in direction of the issue #411.
Then, the index view could be built by a jade template.

**Comment by folletto** [comment]
Yep. Is it a problem if I close this issue? I think it's well tracked by that one, and if you want you can give suppor there. :)

**Comment by benoitchantre** [comment]
No problem, you can close it.

**Comment by folletto** [comment]
Thanks. :)
