### ISSUE TITLE
MagRocket Backend

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#639]
Some of this discussion has been buried in Issue #613 

While I had initially opened up the MagRocket work that I've been doing on a Private Alpha basis I've been getting lots of inquiries and input and have decided that it might be better suited for the community as a whole to just open up the project to the general public...  Don't get me wrong, there is a way to go to get this to a solid 1.0 release, but I think that with more open access that will be better for everyone.  Plus it will ease the headache of me managing who has or doesn't have access to private repos :)

So, anyone that is interested in checking out what is already there and working, and also participating on enhancing and developing the new features to support the coming Baker 4.1 and 4.2 main workstreams, please feel free to hop over to.  

http://github.com/nin9creative/magrocket-shelf
http://github.com/nin9creative/magrocket-backend
http://github.com/nin9creative/magrocket-api

While I have a separate MagRocket Shelf fork currently, the end goal is to make the backend work as well with the Baker Shelf as with the MagRocket shelf.  In general I feel that there will be a close alignment in codebase and feature set between the two - however I am currently keeping a separate shelf as there may be some features down the road that I may want to implement that are beyond what the main Baker project is looking to implement.

That being said, MagRocket will work in it's current form to replace the Shelf.json file among a few other things.

It's my hope that folks will help grow this into a viable end to end solution.

You can also head on over to the http://www.magrocket.com site as there will be a knowledgebase for setup info / FAQ etc.

Setup info.
http://www.magrocket.com/kb/magrocketsuitesetup/

If you want to get on a mailing list for general Alpha program information you can access that here...  http://eepurl.com/t4vSX

Thanks!
Andrew

**Comment by aspek** [comment]
OMG, Thank you so mush.

**Comment by TheCrucible** [comment]
Thanks

**Comment by Simbul** [comment]
This is probably better tracked in #829. Closing this old issue ;)
