### ISSUE TITLE
Distribute issues to a restricted audience

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#640]
Is there a way to distribute issues to a restricted audience?

I think the newsstand is public only?
Maybe the solution is only to restrict the distribution of the app (ad hoc or enterprise)?

**Comment by folletto** [comment]
Could you detail more what do you mean by "restricted audience"? What should it do?

**Comment by benoitchantre** [comment]
A restricted audience could be employees/students which have to download some issues from an app that is not available on the App Store.

That way, there's no need to authenticate users, but it could be an improvement to have a way to set permissions on issues.

**Comment by folletto** [comment]
If it's not on the store, then it's a matter of distribution, you should check Apple's documentation on Enterprise releases and all the related items.

We don't have any control on that side of things, it's all Apple. :)

**Comment by benoitchantre** [comment]
There's no problem to make an enterprise build with Baker. I made already one for a test purpose.

If I'm not wrong, the newsstand is only for newspapers and magazines. You cannot use it to distribute other type of documents. You app also needs to be on the App Store.

If you cannot distribute through newsstand because your content is not a magazine or a newspaper, it would be great to have an alternative. With Baker v 3.2, you could download issues.

It would be great to have a standalone mode that could either display local issues (what we have now) or that allow to download remote issues if the book folder has no issue.

**Comment by folletto** [comment]
Yes. I agree. Individual downloads for the Standalone mode are a very interesting feature that... unfortunately is very difficult to implement and we choose to keep the codebase simple and keep just Newsstand support... because that was what most of the users are asking. 

If you want however open an issue asking for downloads for the Standalone mode, so we can see how many people are interested in that feature. :)

**Comment by benoitchantre** [comment]
Done. It's here #644.

Thanks for your follow up.
