### ISSUE TITLE
device in landscape orientation and portrait issue: crash

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#643]
If you have an app that allows both orientations and that contains a vertical issue, the app crashes when you open and close the issue twice.

**Comment by folletto** [comment]
Is this related to #642?

**Comment by benoitchantre** [comment]
Yes, because the source of the problem is when you have single orientation issue in an app that support both orientations.

**Comment by buildc0de** [comment]
Hmm, my reference didn't show up... Looks like this issue has been fixed in 3228d83.

**Comment by Simbul** [comment]
Weird, maybe Github doesn't support cross-referencing from comments on commits.

Anyway, @benoitchantre could you please check whether the commit has indeed solved the issue? All you have to do is pull the latest `master` and run the test again :)

**Comment by benoitchantre** [comment]
I have tested with iOS simulator (6.1, 6.0, 5.1) and there's no more crash of the app :-)
Thanks for the fix.
