### ISSUE TITLE
Top AND Bottom indexes?

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#645]
I apologize if I am using incorrect terminology, as I'm not that experienced in developing. I noticed in the Dobry Znak magazine which was published with Laker/Baker that when you double tap on a page that the normal index appears along the bottom of the page, but there is also a smaller one that appears at the top. I'd like to have a home and help button appear on the top of the page at the same time as the index appears on the bottom. What do I need to do to get a second index section to appear at the top?

TIA

**Comment by folletto** [comment]
Unfortunately that's custom development that was done on top of Baker, it is not a standard Baker. Sorry.

**Comment by sportyguy209** [comment]
Darn, it sure would be a nice feature to add.

**Comment by folletto** [comment]
You can create a transparent index, full-height, and use just the top part and bottom part of it... maybe... :)
