### ISSUE TITLE
Configuring Baker with Newsstand

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#647]
I'm confused as to the proper procedure in being able to develop a Newsstand app (magazines), testing one, and submitting one. I have a developer account and I'm trying to follow the 4.0 Baker tutorial. At the moment, it seems like proverbial chicken, egg question.:-) What comes first? Please understand, I have never created an App before, so I'm unfamiliar with the process and may be completely off base with my assumptions.

I'm confused by the concept of an App, Newsstand, and editions. Do I create one App and then the different editions of my magazines get "attached" to the same App or do you create a different App for each edition of the magazine?

In "C. Configure Baker with Newsstand" it says you must create a free subscription which is done in "Manage In App Purchases." You start by creating a new App.

But, if I am just developing the magazine and just want to test it, I don't want to create a new App and go through an approval process until it's done. I won't have screen shots, proper description, etc. Or, can all of this be added at a later time?

Later in the instructions under "F. Test and Publish" it says to test your publication, subscriptions, and downloads. How is this done if I haven't applied for an App?

And, finally it says, "When you're ready, submit to the App Store." I thought filling all the information in to create the App created the submission to the App Store. Is that not correct?

I understand that it is necessary to get data from Apple to configure Baker, but I am confused as to how to go about it without applying for the App.

TIA

**Comment by Simbul** [comment]
You should really read up some Apple tutorials on Newsstand and the App Store. Here's a couple of links:
- [Newsstand](developer.apple.com/devcenter/ios/newsstand/)
- [In-App Purchase](developer.apple.com/appstore/in-app-purchase/)

In short: you create a single App, which is displayed as a "magazine" in the Newsstand folder. You then publish your issues through the App.

You do need to create an App in iTunes Connect to properly test, but that won't have to go through any review/approval process. You just have to fill in a lot of fields, but that's it.
When you're ready to publish you can review the fields you entered, add some more, and send your app for review to Apple.

**Comment by sportyguy209** [comment]
@Simbul Thanks for your response. I've researched where I can, for example I went through Apple's video on creating a new App and was still confused, so I appreciate your response. I'm interested to read the links you provided, but they don't seem to work for me.

I am happy to read and learn more about the process, but in summary, are you saying that I can go through the creating an App process without actually submitting the App for approval? It's particularly confusing because when you fill out the application it asks for the date when your App goes live. Do I just put it far in the future and change it later?

And, I will be able to update all the assorted information in the application before submitting the App for approval?

Finally, I can test the App and Newsstand with my magazine before submitting the App for approval?

I just want to confirm all of this because A) I don't want to submit an App or magazine before it is ready, and B) don't want to have old, incomplete information that can't be changed as part of my App or magazine. I know how Apple can be and don't want to go down a road that I can't go back from.

TIA

**Comment by Simbul** [comment]
To browse that Apple documentation you need to log in with a Developer account (which you'll need to create and submit your App anyway).

I appreciate you concerns about Apple :D

Yes, you can create an App for testing without submitting it for approval. As far as I can tell, you can edit most fields, but I've never done it myself: you might want to google that or wait for someone else to answer here.

**Comment by folletto** [comment]
I'm closing this issue since the discussion seems ended. Reopen if needed. :)
