### ISSUE TITLE
How to disable media autoplay in "three-card" mode? If it not current page.

### ISSUE THREAD

**Issue by aspek** [Simbul/baker#648]
Hi,
Many user don't want to wait loading page  in "-baker-page-screenshots" mode.
I decided to use  "three-card". But the problem is that the video plays automatically. It's important and I need to use it.

![SampleImage](https://f.cloud.github.com/assets/2587452/73789/6ff40474-6061-11e2-8993-26276818a2f2.jpg)

**Comment by folletto** [comment]
Just create a javascript that listen to `window.focus` and `window.blur` so you can trigger the video when it gets visible. :)

**Comment by nonuts** [comment]
here's a coffescript snippet that works for me, with #html5-video being the ID of the embedded video:

window.addEventListener "blur", (->
  $("#html5-video")[0].pause()
), true

**Comment by aspek** [comment]
Oh that work. Thanks

**Comment by folletto** [comment]
You're welcome. :)
