### ISSUE TITLE
Subscription button does not disable after the user has already subscribed.

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#649]
Hi,

I am having an issue where users of my app (which was accepted by Apple and released today) are subscribing but then they can just press the button again and go through the whole process almost as if they never subscribed.

By doing this multiple times, the user just receives a default email from Apple to alert them of the subscription every time. 

I believe it is important (to not confuse customers) that the subscribe button be disabled after a successful subscription.

Kind regards,

Mitchell.

**Comment by Simbul** [comment]
That bug has been fixed in the [single_purchase](https://github.com/Simbul/baker/tree/single_purchase) branch, which hopefully we will be merging into `master` soon.

**Comment by heirenton** [comment]
I am having same problem. How can i check the fix from single_purchase to my baker code. I am about to send my app to apple...

**Comment by folletto** [comment]
It's not a "fix", it's the whole new code in single_purchase that does that. And unfortunately that code isn't ready yet, not even for testing (we merge in master when the code is ready).

Having the button not doing this isn't a blocker, you can submit as many others did already. :)

**Comment by heirenton** [comment]
Ok thanks.

**Comment by ghost** [comment]
Hi everyone,
The feature to disable the subscribe button after a subscription has been committed to the master so I will close the issue.
