### ISSUE TITLE
Grayish overlay appears when scrolling, disappears if I rotate the device

### ISSUE THREAD

**Issue by ollisulopuisto** [Simbul/baker#651]
Hey y'all, take a quick look at this video: http://www.youtube.com/watch?v=yMwZUlI6ztQ

So basically what's happening is that the moment I start scrolling, a grayish overlay appears on the page. However, if I rotate the device and then return to the original orientation, the overlay disappears.

Using bundled mode, fresh install with book.json config that partly reads

```
"-baker-page-numbers-alpha": 0.01,
"-baker-rendering": "three-cards",
"-baker-background": "#ffffff",
```

Any idea what this might be about? I tried cleaning the emulator's screenshot directory, but maybe I missed something.

**Comment by folletto** [comment]
My first guess... It looks a transparency rendering bug. How are you setting the white background of your HTML? A CSS `body` rule?

**Comment by ollisulopuisto** [comment]
I'll check that out. I should mention that the same thing doesn't happen in Safari or Mobile Safari.

**Comment by folletto** [comment]
Yes, I'm aware. But unfortunately the `UIWebView` is and isn't Mobile Safari at the same time and we had to use some tricks (including making some components transparent) in order to try work around some bugs.

**Comment by ollisulopuisto** [comment]
Tried to strip out bits of the css (no body color rule, no transparencies left anymore) but it doesn't seem to have an effect.

Here's a second video that shows 1) how the overlay only covers a portion of a long page and 2) the debug messages in xcode: http://www.youtube.com/watch?v=AcYeMIx27vc&feature=youtu.be

**Comment by folletto** [comment]
Actually, you should do the opposite: ADD body color. Because by default the page is transparent. ;)

However, I really have no clue why that happens.

**Comment by ollisulopuisto** [comment]
That's it – adding an explicit body background color rule fixed it. Thanks.

Should we add a wiki page for these kind of known peculiarities? It's not quite a FAQ, but I could imagine someone else running into a similar program.

**Comment by folletto** [comment]
You're right, we should do something like that. :)

**Comment by ollisulopuisto** [comment]
Added a page https://github.com/Simbul/baker/wiki/Known-glitches-and-solutions . Feel free to rename it or move it to a better location.

**Comment by folletto** [comment]
Thanks, that's a good starting point. :)
