### ISSUE TITLE
Book links not working in v4.0

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#654]
I tried to link one book to another book in the shelf (standalone mode), but the link doesn't work.

book://testbook/page2.html

```
2013-01-18 14:55:24.949 Baker[56728:c07] • User tap at [578.000000, 372.000000]
2013-01-18 14:55:25.303 Baker[56728:c07] • Should webView load the page ?
2013-01-18 14:55:25.304 Baker[56728:c07]     Page is current page and current page IS NOT delaying loading --> handle clicked link: book://testbook/page2.html
2013-01-18 14:55:25.304 Baker[56728:c07]     Page is a link with scheme book:// --> download new book
```

Can you reproduce that?

**Comment by yujulio** [comment]
I read in the Wiki that the book parameter doesn't work anymore on 4.0.

2013/1/18 Benoît Chantre notifications@github.com

**Comment by benoitchantre** [comment]
I don't expect that external book links are working, but internal book links should.

from @folletto 

> That actually was possible, isn't it working anymore? If it's not working, then definitely open an issue. :)

**Comment by folletto** [comment]
Thanks @yujulio for pointing that out. The part that shouldn't work is the _download_ part, but we didn't want to explicitly disable also the _opening_ part, that's an unfortunate byproduct.

**Comment by Xm4s** [comment]
With commit dd9bc700 we partially re-enabled book protocol support for books that are on the user shelf.

Now a click on a book:// link will bring the user back to the shelf, then ...
- if the book is available for download the download will begin
- if the book is already downloaded it will be opened

Deeper support for book links (the ability to target a specific page and a specific anchor) remains unavailable.
