### ISSUE TITLE
Experts at HTML Magazine Content Creation?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#655]
Have some questions offline....  Send me an email at andrew@nin9creative.com

Thanks!

**Comment by aspek** [comment]
I am looking for Carousel image  and use it with touch event.
like this  http://desandro.github.com/3dtransforms/examples/carousel-01.html

**Comment by folletto** [comment]
I'm closing this one since it fell down a bit. Maybe try asking on twitter and pointing out Baker's account so we can RT it and give it more visibility. :)
