### ISSUE TITLE
Named Anchor Question

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#656]
Do named anchors work in Baker on an IOS device? If so, what am I doing wrong? I have a html page named "glossary.html" with the following link:

``` html
<a href="glossary.html#test">Word</a>
```

When I click the link in Safari for a test, it takes me to the page "glossary.html" and then scrolls to the bottom of the page where I have the following link:

``` html
<a id="test">Word</a>
```

However, when I try this on my iPad it takes me to the "glossary.html" page, but instead of scrolling to the bottom of the page, I get a slight movement up on the page and then it stops.

TIA

**Comment by folletto** [comment]
Might be a bug. We'll check. :)

**Comment by anjimi** [comment]
I have links in my index which link to named anchors in my pages and they seem to be working fine for me. I have one page with an iframe and the named anchor doesn't work on that page oddly enough, if I remove the iframe it works.

**Comment by folletto** [comment]
Uhm. That makes me think: @sportyguy209 did you try putting just the anchor name in the a tag (`"#test"`)?

**Comment by sportyguy209** [comment]
@folletto It seems when I write the code in this post it turns into links and disappears. What is the proper way to write code in a post so it shows up as code? I tried commenting it out but that didn't seem to work.

Sorry, I'm not sure what you are asking. On one page I have the following link: `<a href="glossary.html#test">`, then on the glossary.html page I have at the bottom <a id="test">. The link works in my browser, but when I try it on my iPad, it takes me to the glossary.html page, but then the page bumps up slightly and nothing. Am I writing the tag or doing something else wrong?

**Comment by folletto** [comment]
I'm suggesting to see if `"#test"` instead of `"glossary.html#test"` works. :)

**Comment by sportyguy209** [comment]
@folletto It didn't work. Am I the only one with this problem? I'm trying to create a link from one page to a specific area of a different page. If I preview the pages in a browser the link works correctly, on my iPad the link takes me to the correct page, but not to the location on the page.:-(

**Comment by tekdope** [comment]
Hi! i Have the same problem here, Running baker 4.0 standalone, anchors are taking either to the top or bottom of the page. i tried to point to id or name tags with same result. I also tried to point inside the same page by using  "currentPage#anchor" and "#Anchor" with the same result. Something might be broken somewhere.
And of course my Anchors are not localized at the top or bottom of the page but in the art of the page.

**Comment by sportyguy209** [comment]
I just tried a few named anchors to take the reader back to the top of the page, and some work and some don't even though they are all the same. I think something is not working relating to named anchors.

**Comment by sportyguy209** [comment]
@folletto Sorry to bother you, but I don't know how this system works. Has there been any investigation into this issue yet? TIA

**Comment by folletto** [comment]
When we work on something, we update the corresponding issue to keep everyone updated. No updates means that we still didn't have time to work on it. Sorry.

**Comment by kkporter** [comment]
I have the same issue, but my case is kind of wierd cos in some pages the anchor works exactly as it should be, but in some pages, I get a slight movement down on the page and then it stops and didnt get to where the anchor is. I tested it in safari and it goes down to where it should be. I tried both the "#anchor" and "page.html#anchor", the result is the same.

**Comment by benoitchantre** [comment]
I'm able to replicate the bug described with the latest code from the master branch.

With an anchor in the same page:
The first time you click on the link (same elements as you), there's a slight movement.
**If you click again, the page scrolls to the anchor, then it to works normally** (as long as you stay on this page)

The results are the same with or without vertical pagination.

Update: I have found that there's an influence of where your anchor is in the DOM. If it's inside too much elements, it doesn't work, but at a certain level it works normally. No influence in Safari Mobile.

**Comment by folletto** [comment]
Thanks, that's a valuable feedback. :)
It seems a `UIWebView` issue there... mumble. I wonder if it works in iOS7 then.

**Comment by folletto** [comment]
I'm consolidating this issue in #483, mostly because it's likely to be a `UIWebView` issue, but also because once we start looking at the issue, if solvable, should solve both.
