### ISSUE TITLE
Prevent to show the index page when you open a book?

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#657]
When you open a book from the shelf, the index page is shown briefly and then is closed automatically.

Is there a way to disable that, in order to let the user see the cover immediately in the case we use a fullscreen index page?

**Comment by folletto** [comment]
I'm sorry but that's a behaviour there by design: it's required to tell the user, in a subtle way, that there's an index and that there's a way to go back to the shelf. 

We won't add in Baker a way to disable it.
