### ISSUE TITLE
Purchases: restore purchases function in v4.1?

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#658]
Baker 4.1 will bring us the ability to have paid issues in the shelf.

Will the user be able to restore his purchases if he reinstalls the app (remove then install) or if he wants to have it on a new device?

**Comment by Simbul** [comment]
We're still deciding whether to include that in the scope for 4.1.

Even if you don't restore purchases, however, the App Store will never take payment twice for something you already bought.

**Comment by benoitchantre** [comment]
Good news to know that it will come quite soon.
Thanks for this great framework.

**Comment by rtshittu** [comment]
Can't wait to see the paid subscription in the new version of Baker Framework

**Comment by Simbul** [comment]
Closing this as the feature has been added in 479ba8522243b73b40d62135e29d3eb08b1128e6 (and other commits).
So the answer is yes, restoring purchases will be in release 4.1.

**Comment by benoitchantre** [comment]
Thanks!
