### ISSUE TITLE
Contents Question/Bug with 4.0?

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#659]
I have just transitioned my "magazine" App from 3.0 to 4.0. Everything appears to be working as it should. When it first launches (standalone and landscape orientation) it takes me to the shelf page on my iPad. I can view all the pages, effects, contents, etc. of the magazine.

The problem is, if I click the home button on the iPad, when I go back to the magazine my contents on the page have shifted up about a quarter of an inch and so the contents on the bottom show and the top of the page is cut off. If I scroll to any other page, the layout stays shifted up. Is it something I'm doing wrong? I have tried cleaning and reinstalling my publication from Xcode, but get this consistent error each time.

If, from my home screen, I close the running magazine and relaunch it, everything works as it should.

TIA

**Comment by folletto** [comment]
This issue seems the same of issue #584. 
Am I correct?

**Comment by sportyguy209** [comment]
Yes, sorry for not noticing.

**Comment by folletto** [comment]
It's ok. :) 
We have a long list, unfortunately that's not always easy to find the right issue. :)
I'll close this one as we use that for tracking. :)
