### ISSUE TITLE
Can't figure out what's wrong with Book

### ISSUE THREAD

**Issue by Ajguy** [Simbul/baker#660]
If anyone is willing to help out with this, I would be much obliged. I've finished work on compiling a first issue (using Adobe Edge Animate), created the book.json, and attempted to load the book in the stand alone Baker shelf along with "A Study in Scarlet" just to make sure everything is working. Sadly, it's anything but.

"A Study in Scarlet" appears on the shelf just fine, but my "Issue 0" only shows a download button. The title and cover image are missing, even though they are defined in the book.json file. If I run the app preview with the scarlet folder, the app just opens to a blank screen.

Here's a link to my hpub for the curious: http://www.outlandmoto.com/Mag/issue0.hpub

I really appreciate any help and advance that can be provided. It'd be a real life saver!

**Comment by qutehoot007** [comment]
Hi Ajguy,

I unzipped the files , I found you have problem in the book.json, please use service like http://jsonlint.com/ to validate the JSON , 

this is the valid JSON : 
--------------- START -----------------
{
    "hpub": 1,
    "title": "Issue 0",
    "author": [
        "Jimaj Media LLC"
    ],
    "creator": [
        "A. Minotti, J. Vota"
    ],
    "date": "2013-01-20",
    "url": "book://www.outlandmoto.com/Mag/Issue0",
    "cover": "outlandmoto0.png",
    "orientation": "landscape",
    "zoomable": false,
    "-baker-background": "#000000",
    "-baker-vertical-bounce": false,
    "-baker-media-autoplay": false,
    "-baker-page-numbers-color": "#000000",
    "contents": [
        "FrontCover/page1.html",
        "OverlandAd/page14.html",
        "ToC/page3.html",
        "Staff/page13.html",
        "LetterFromE/page5.html",
        "HowDid/page6.html",
        "ProdWold.page7.html",
        "Rescue/page8.html",
        "TellStory/page9.html",
        "ProdAero/page11.html",
        "Photos/page10.html",
        "BackCover/page12.html"
    ]
}
----------- END --------------

BTW I'm working on Adobe Edge Magazines too :)

cheers,

**Comment by Ajguy** [comment]
An extra comma. And this is why I got out of programming in college. Thank you so very much! I hope the Edge Animate platform is going well for you. Feel free to ping me with any questions you may have on it. I've figured out a lot of its idiosyncrasies. Especially when it comes to laying out a page for iPad.

**Comment by folletto** [comment]
Does it work now? May I close this issue? :)

**Comment by Ajguy** [comment]
Yup, we're all good. Thanks again to @qusai87.
