### ISSUE TITLE
Crash app when server is unreachable... 

### ISSUE THREAD

**Issue by alexbar10** [Simbul/baker#663]
Hi. I found a problem about the connection with the server when it's looking for the JSON file. 

I run the project in my ipad, i have a local server and when they both are in the same network everything works fine, it show the issues availables, but when i connect my ipad to another network and run again the app it crashes, when it supposed that have to load the JSON file from cache.

I been looking in the code and i guess that is something about the method stringWithContentsOfURL: encoding: error:, it takes a long time looking for the server and blocks the main thread

I change that line of code for the class NSURLConnection and the method sendSynchronousRequest:returningResponse:error, also i use the NSURLRequest class and the method requestWithURL: cachePolicy: timeoutInterval: and i put a short timeout, about 3 seconds, and now works fine  

Someone can tell me if this is the best solution?

**Comment by Simbul** [comment]
I could not reproduce the crash, but you have a valid point: that code was hardly optimal.
I've implemented your suggestion in the commit listed above. Thanks :)
