### ISSUE TITLE
In-App Purchase for single issue: build failed in standalone mode

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#665]
If you download the code from the master branch, you can't run the iOS Simulator with the standalone mode because the build failed.

![Capture d e cran 2013-01-22 a 12 10 41](https://f.cloud.github.com/assets/1521015/86003/76f5a080-6484-11e2-93b4-5cb431dfd8d4.png)

**Comment by folletto** [comment]
Did you do a complete cleanup before testing? The class is there, so it should be defined...

**Comment by benoitchantre** [comment]
My test was made on a clean download from the master branch, I haven't made a proper cleanup.

If I follow steps 2 and 3 to make a proper cleanup, the build fails, but I have something different.

![Capture d e cran 2013-01-22 a 12 23 11](https://f.cloud.github.com/assets/1521015/86036/298299b4-6486-11e2-9dc0-b383f49d30d1.png)

**Comment by folletto** [comment]
I just downloaded the current master and works smoothly, I don't know what that could be if you did the same.

**Comment by benoitchantre** [comment]
I have remarked something wrong from myself: I didn't removed the reference to NewsstandKit.framework

Here's the result after a restart of the computer, a coffee and a new try from a new download of the master branch. Same result if I clone the repository. A proper cleanup was made.

![Capture d e cran 2013-01-22 a 13 10 55](https://f.cloud.github.com/assets/1521015/86168/2605e9d8-648d-11e2-9d72-88742b897eb2.png)

I'm using Xcode 4.5.2 (4G2008a) and OS X 10.8.2

**Comment by benoitchantre** [comment]
I made a new test with the same result, but with a different method.
1. Baker repository cloned to my desktop
2. new branch "standalone" from commit e07b5dc6df66c8ec30cfbd558391fce74da7b690 (just before the merge of single-purchase branch)
3. settings applied to use the standalone mode
4. tried to run iOS Simulator: success
5. app removed from iOS Simulator
6. iOS Simulator closed
7. master branch merged in the standalone branch
8. clean and clean build folder
9. tried to run iOS Simulator: build failed

![Capture d e cran 2013-01-22 a 15 10 20](https://f.cloud.github.com/assets/1521015/86468/98a2fb4c-649d-11e2-93e7-97a2254ac25b.png)

What's wrong?

**Comment by folletto** [comment]
We'll check. It might be something specific with the Standalone mode. :)
Thanks for the report :D

**Comment by benoitchantre** [comment]
Thanks for your help.

**Comment by benoitchantre** [comment]
Thanks for the quick fix!
