### ISSUE TITLE
Cannot put accent in issuelist.json

### ISSUE THREAD

**Issue by RolandMarianna** [Simbul/baker#666]
Hello,

I tried to put accent in title or info part (for a french description) of the JSON issue list file but it doesn't work.
I have the "No Internet Connexion" error.

By the way, the same error message pop when the JSON is not present or when it was wrong.

Perhaps i miss something... :)

Thanks in advance for your advices

**Comment by Simbul** [comment]
So everything works while you have a shelf JSON without accents, but then it breaks when you add the accent?

Does that mean you are adding an accented letter like àèìòù?

**Comment by RolandMarianna** [comment]
yes, it's correct.

For exemple, when I put date of issue in the info tag ("info": "") : 
"15 novembre 2012" it works,
but "15 décembre 2012" doesn't.

**Comment by folletto** [comment]
Is your file saved with UTF-8 encoding? :)

**Comment by RolandMarianna** [comment]
Ouch ! Indeed, I saved the JSON with UltraEdit without specify an encoding... :')

Now, it works perfectly.

Thanks guys !
