### ISSUE TITLE
Best practices for magazine layout

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#667]
Greetings!

My goal is to publish a magazine on iPad.
Source files: text (html) + images.

I'm interested in best practices for such projects.

Looking at similar iPad publications, I see, that the best way
is to create multi(2-) column layout for a single iPad page,
having all the text splitted into 768x1024 "pages" ("-baker-vertical-pagination").

The problem I met so far - is that I have html text with images,
and these 2 columns of text I want to create, 
must wrap on each iPad "page" ("-baker-vertical-pagination") separate,
not going down, down, down, and then - second column from the very top...

I don't know how many text I'll have in each article,
so, that's why I need at least some kind of "semi-automatic" solution for layout
generation (HTML5, CSS3, JS ... what? how?)

So... something like this...
Maybe someone has any experience in such kind of tasks.

Any advice will be greatly appreciated!

**Comment by Ajguy** [comment]
There's a few routes you can go depending on what makes you comfortable. I'm also not 100% I understand what you're shooting for, so I'll keep it general.

If you want an article to smoothly scroll vertically, you just lay it all out. I'm getting the sense you want multiple columns visible in a single page view. For that, I would suggest creating a <DIV> element with the height you want (in this case 1024 px), and using the CSS style for columns (http://www.w3schools.com/cssref/css3_pr_columns.asp). This will arrange a single block of text into multiple columns.

If you want it to hard scroll bit by page, the DIV option would still work. Alternatively, I've been using Adobe Edge Animate. It's freely available, allows you to layout out your content in a fairly WYSIWYG style, and makes sit easy to place each element into paginated "chunks" to scroll through. It also makes it pretty easy to add animation and interactivity to you magazine if that's your bag.

Let me know if this helps at all.

**Comment by divlv** [comment]
Ajguy, thanks for answer!
Actually, I knew about CSS3 columns.
But the interesting thing to me - is how (semi-automatically) to split an article(-s) into "chunks"
of 768w-1024h DIVs?
It is the main question.
How to "understand"  that this text does not fit current 768w-1024h DIV and it needs to be moved to second
"chunk", under the current?

Regarding Adobe Edge Animate - I tried to start the app, but being forwarded to Creative Cloud,
and... not sure, what I need to do next.
I can upload my HTML file..and... what now?

**Comment by benoitchantre** [comment]
For this task, the solution would be to use CSS region (with a polyfill), but it's not recommended, because it's <a href="http://html5please.com/#regions">too experimental</a> at the moment.

**Comment by Ajguy** [comment]
Adobe Edge Animate requires a free creative cloud subscription. Just sign in with an Adobe ID and you'll be set. You'll have to rebuild your pages, I'm afraid, but I think you'll like the control the program gives you.

And has benoitchantre said, CSS Regions are a possible solution down the road, but Safari iOS does not support them. Actually, no browsers do except Chrome in debug mode.

Long story short, there is no automatic way as of now.

**Comment by divlv** [comment]
I'm still searching for the "auto pagination" techniques, and see what I have found:

http://bytes.com/topic/javascript/answers/157400-spill-overflow-text-another-div

Check out the last comment from Danny@Kendal...
