### ISSUE TITLE
How to Populate Baker App with magazine issues

### ISSUE THREAD

**Issue by rtshittu** [Simbul/baker#668]
Hi Guys,

So far, I have been able to implement Baker Framework.  This is so good.

I like it.  Well done guys.

However, I have about 3 magazine issues, See image below.

These are inside my "books" folder with the default "a-study-in-scarlet".

I have my shelf.json file as shown in the image.

I have equally editted individual book.json in eash folder as well as individual .hpub file.  (it was a zipped file then I changed the extention to .hpub).

I cannot find any other thing to fix again, yet it will not load.  

Please what am I missing?
![SCREEN2](https://f.cloud.github.com/assets/3063600/89918/4e4c937c-655c-11e2-88bd-7cf1a3148070.png)
![SCREEN1](https://f.cloud.github.com/assets/3063600/89924/61b87b1a-655c-11e2-9afc-55d7e2ac018a.png)

**Comment by rtshittu** [comment]
In addition to this.  This is the output when I run it and its not loading the issues.  see image below

**Comment by Simbul** [comment]
You are mixing up standalone and newsstand modes :)
Which one are you trying to use?

**Comment by rtshittu** [comment]
I am using newsstand.

**Comment by Simbul** [comment]
Right. If you're using Newsstand, you don't need to put anything inside the `books` folder.

Have you tried following the [Newsstand tutorial](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand)?

**Comment by rtshittu** [comment]
I have followed this tutorial and i was able to view it and it worked.  the challenge am having is how to populate multiple issues.  The files are hosted on my pc. please look at the screenshot i added earlier.
Thanks alot. 
Mean
![screen3](https://f.cloud.github.com/assets/3063600/89995/1d8c9326-6562-11e2-9ce9-1d49e537d54c.png)
while, this is the output on my simulator.

**Comment by rtshittu** [comment]
I have all my files hosted on my pc andmy url looks like "http://192.168.1.1:8080/issue1/issue1.hpub"
etc

please i dont know what else am missing.  I have done practically everything.

**Comment by Ajguy** [comment]
Can you post the contents of your "shelf.json" file?

**Comment by rtshittu** [comment]
@Ajguy Here is the content of my shelf.json file.

 [
  {
  "name": "a-study-in-scarlet",
  "title": "A Study in Scarlet",
  "info": "The original masterpiece by Sir A. Conan Doyle",
  "date": "1887-10-10 10:10:10",
  "cover": "http://bakerframework.com/newsstand-books/a-study-in-scarlet.png",
  "url": "http://bakerframework.com/newsstand-books/a-study-in-scarlet.hpub"
  },
  {
  "name": "a-study-in-green",
  "title": "A Study in Green",
  "info": "An exciting remake of the original, with added mint!",
  "date": "2010-10-10 10:10:10",
  "cover": "http://192.168.1.3:8080/a-study-in-scarlet/a-study-in-scarlet.png",
  "url": "http://192.168.1.3:8080/a-study-in-scarlet/a-study-in-scarlet.hpub"
  },

  {
  "name": "issue1"
  "title": "Current Issue",
  "info": "Waje takes the stage",
  "date": "2013-1-22 10:10:10",
  "cover": "http://192.168.1.3:8080/issue1/issue1.png",
  "url": "http://192.168.1.3:8080/issue1/issue1.hpub"
  },

  {
  "name": "issue2"
  "title": "July/August Issue",
  "info": "Mavin - A Modern Family",
  "date": "2012-1-22 10:10:10",
  "cover": "http://192.168.1.3:8080/issue2/issue2.png",
  "url": "http://192.168.1.3:8080/issue2/issue2.hpub"
  },

  {
  "name": "issue3"
  "title": "May/June Issue",
  "info": "Ibidun Ighodalo, The Lady, Her Lover & Her Lord",
  "date": "2011-1-22 10:10:10",
  "cover": "http://192.168.1.3:8080/issue3/issue3.png",
  "url": "http://192.168.1.3:8080/issue3/issue3.hpub"
  }

  ]

**Comment by rtshittu** [comment]
I ran this on my terminal python -m SimpleHTTPServer 8080

so if i type http://192.168.1.3:8080  i have my files listed on the directory.

I await your reply as soon as possible.

Thanks guys

**Comment by Ajguy** [comment]
The first thing I want to eliminate is the possibility of the iOS simulator not being able to connect to your terminal. Punch in the address of your shelf.json file (which I'm guessing is at http://192.168.1.3:8080/shelf.json) into safari on the simulator and see if it comes up. You should just see the contents of the file.

**Comment by rtshittu** [comment]
@Ajguy, thanks for your help. I have done that and i can see the content on my safari. i could even see the content of my html5 too.  

i really cannot pin point what the problem is.  please can you do me a favor,

kindly tell me d steps i need to do to have more than one issues on beaker framework.

please see my screenshots for the way i arranged the issues inside the books folder.

Thanks a bunch

**Comment by Ajguy** [comment]
Ah, there it is! Missing commas. After your "name" entries in your shelf.json there are no commas. That's probably what's causing the failure. You can always run your json files through this handy site to find programming errors: http://jsonlint.com.

Give that a shot and see if it works.

**Comment by rtshittu** [comment]
Wow @Ajguy, I used the json handy site and i saw my errors.  Now everything is working fine.  I can see all my magazines issues.

Your are awesome.

Thanks a lot for your time.

Really appreciate.

**Comment by Simbul** [comment]
Thanks for solving this, @Ajguy!
