### ISSUE TITLE
Vertical pagination not paginating.

### ISSUE THREAD

**Issue by Ajguy** [Simbul/baker#669]
I've enable the -baker-vertical-pagination to true, but it's not working on my current issue. Here's my book.json.

{
"hpub": 1,
"title": "Issue 0",
"author": [
"Jimaj Media LLC"
],
"creator": [
"A. Minotti, J. Vota"
],
"date": "2013-01-20",
"url": "book://www.outlandmoto.com/Mag/Issue0",
"cover": "outlandmoto0.png",
"orientation": "landscape",
"zoomable": false,
"-baker-background": "#000000",
"-baker-vertical-bounce": false,
"-baker-media-autoplay": false,
"-baker-page-numbers-color": "#000000",
"-baker-page-turn-tap": false,
"-baker-page-turn-swipe": true,
"-baker-vertical-pagination": true,
"-baker-start-at-page": 1,
"contents": [
"FrontCover/page1.html",
"OverlandAd/page14.html",
"ToC/page3.html",
"Staff/page13.html",
"LetterFromE/page5.html",
"HowDid/page6.html",
"ProdWolf/page7.html",
"Rescue/page8.html",
"TellStory/page9.html",
"ProdAero/page11.html",
"Photos/page10.html",
"BackCover/page12.html"
]
}

Anyone else run into this problem?

**Comment by yujulio** [comment]
I ran into this too, you have to put "<meta name="paged" content="YES">"
inside the head section of each one of your HTML files.

2013/1/23 Ajguy notifications@github.com

**Comment by Ajguy** [comment]
Ah, I thought that was optional. Let me give it a go.

**Comment by folletto** [comment]
Yes, it should be optional... :o

**Comment by Ajguy** [comment]
Yeah, even with the meta tags, I've got nothing. I've even tried adding vertical pagination to the Study in Scarlett sample, but it won't work there either. I've tried in both 4.0 and the current master. Any ideas?

**Comment by yujulio** [comment]
Weird, it works perfectly for me...

2013/1/23 Ajguy notifications@github.com

**Comment by Ajguy** [comment]
I've even tried manually changing the setting to YES in the code found in BakerBook.m. Still nothing. This is really strange.

**Comment by Ajguy** [comment]
The saga continues. It's working fine in the Scarlett example. Not sure why it didn't before. However, it most definitely isn't working in my magazine still. This is leaving me to think that it's something to do with the way my magazine is laid out (done with Adobe Edge Animate). I'll continue investigating and see what I find. Until then, if any has any ideas, please feel free to share.

**Comment by Ajguy** [comment]
And there's my answer. If you set an Adobe Edge Animate project to scroll to content off the edge of the composition, this causes the scrolling to happen within your DIV, not the entire page. Since the page doesn't seem to be scrolling, Baker didn't not paginate it. Problem solved. For those using Edge Animate, mind your doc sizes!
