### ISSUE TITLE
window.onorientationchange Javascript not working?

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#67]
Hey there!

First of all thanks for the great work! I'm designing a digital magazine with HTML5 and Baker for my diploma thesis.

Everything is working fine, except the following javascript problematic.
I Implemented a javascript/css image-scroller which works great in mobile safari but not in Baker. I use a JavascriptFunction to calculate the image's width and need that value for the css animation of the image. In Baker the function setimgwidth(); isn't reexecuted on orientation change. The complete function:

---

<pre><code>
// Execute function on pageload  
setimgwidth();

// Execute function on orientationchange
window.onorientationchange =  setimgwidth;

//Function for setting IMG_WIDTH, which is needed for further functions
function setimgwidth () {

/*window.orientation returns a value that indicates whether iPhone is in portrait mode, landscape mode with the screen turned to theleft, or landscape mode with the screen turned to the right. */
var orientation = window.orientation;

//if device = iPad
if(navigator.platform == "iPad") {
    if(orientation == 0) {
    IMG_WIDTH = 768;
    } else {
    IMG_WIDTH = 1024;
    }
}

//if device = iPhone or iPod Touch
if(navigator.platform == "iPhone" || navigator.platform == "iPod") {
    if(orientation == 0) {
    IMG_WIDTH = 320;
    } else {
    IMG_WIDTH = 480;
    }
}

}
## </pre></code>

I'm already working with css-styles depending on landscape or portrait, but the image-scroller javascript function needs that value IMG_WIDTH to determine how far it should "push" the image to the left or right to display the next.
I used the script from the following site (which works great and fast!): http://labs.skinkers.com/touchSwipe/demo/image_scroll.php

Any idea? Is this something I'm able to solve with JS or is it a Baker-related thing of how it handles the viewport, orientation and size (For example, if I start the app in landspace, then IMG_WIDTH is also set to "768" (which is portrait)?

Thank you very much and best regards,
florian

**Comment by Xm4s** [comment]
It seems that UIWebView has some problems handling the orientationchange event (which on the other hand works perfectly on Safari Mobile).

Searching around and experimenting a bit I've found something that should do the job.
Try to add at the bottom of the method

<pre>
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation
</pre>

this line

<pre>
[currPage stringByEvaluatingJavaScriptFromString:@"var e = document.createEvent('Events'); e.initEvent('orientationchange', true, false); document.dispatchEvent(e);"];    
</pre>

So, when the UIWebView finish its rotation the event is dispatched correctly.
Then another problem arise: window.orientation value is always 0 (I think that's why your IMG_WIDTH is always set to 768)

How to solve this... well don't check for window.orientation :)
I think that window.innerWidth is the value you are looking for your image width, so i would go for a script like this:

<pre>
var setImgWidth = function setImgWidth() {
    IMG_WIDTH = window.innerWidth;
}
window.onorientationchange = setImgWidth;
setImgWidth();
</pre>

This seems to work like a charm on the iOS Simulator, try it on your iPad and let us know how it goes. Rember that this is only a quick fix, probably the performances aren't like the ones of a Safari Mobile page... but better off with this than nothing right?

**Comment by ffranke** [comment]
Heyho!

Thank you very much! It works like a charm! ;)
Deadline is the 15th of April. After that I'll share all the code and HTML's.

I'm using the Less-CSS-Framework, so the Magazine will also be viewable on iPhone and a normal screen... Yeah! ;D

Best regards and thanks again!
florian

**Comment by Xm4s** [comment]
Thank you very much for pointing out this little glitch and testing the solution provided.
Can't wait to see your finished magazine :D

I'm leaving this discussion up as a reminder, since I'll like to polish the solution proposed a little bit and then include it in the core of Baker :)

**Comment by k8fisher** [comment]
Hi guys I cant seem to get the code suggested above to work,  I think whats happening is window.innerHeight definitely doesnt in this instance return the correct height of the screen when the screens orientation is changed after onload event. If I change orientation to landscape and then enter the page with the code the window.innerHeight is calculated correctly.

Thanks go out to Ffranke for zuviel build. Thoughts very much welcome. Is the Less-CSS-Framework thats available here?

Kate

Have the following inside the page

```
<head>
    <title>California Wine-Contents</title>
    <link rel="stylesheet" type="text/css" href="css/book_spread.css">
<script>
    var setImgHeight=function setImgHeight(){
        IMG_HEIGHT=window.innerHeight;
        document.write('<div><img src="gfx/3.jpg" style="height:'+IMG_HEIGHT+'px;"></div>');
        alert(window.innerHeight);
    }
    window.onorientationchange=setImgHeight();
    setImgHeight();

    </script>
</head>
```

**Comment by ffranke** [comment]
I catched a cold, so I'm not quite back to normal yet but: What do you want to do? Do you want to stretch an image to the whole width of the screen? That can be done with CSS only.

img {

width:100%;
height:auto;

}

I'm using the LESS CSS Framework (http://www.lessframework.com), which targets different screen sizes and orientation. 

I know, I said that a couple of days ago, but maybe I have my documentation ready by the start of next week...

Florian

**Comment by k8fisher** [comment]
Hey Florian, sorry to bear you've not been well. Will try doing it the good olde fashioned css route cause the change of orientation malarky wasnt happy. 

Many thanks, I'll check out the LESS CSS framework thank you :) _sendz an oodle of get well vibes_ 

Kate :)

**Comment by ffranke** [comment]
Thank you! I'll send you the link to my documentation when it's ready.

**Comment by Xm4s** [comment]
A little update on this matter: I've included in the RootViewController the support for the "orientationchange" event and fixed the "window.orientation" property value (if checked now return 0 / 180 for portrait orientation normal / upside down and -90 / 90 for landscape orientation left / right, as it should be).
I hope this help, thanks ffranke to point out the UIWebView glitch :)

**Comment by ffranke** [comment]
And thank YOU for providing the solution so quick! ;)

**Comment by k8fisher** [comment]
Thank you guys for your hard work, your hard work and funky technical know how are much appreciated

**Comment by Xm4s** [comment]
Since the problem seems solved I'm closing up this issue.
In case new problems arise on the orientation matter feel free to open other more specific issues
