### ISSUE TITLE
Going back directly to the html from which a local PDF document is opened

### ISSUE THREAD

**Issue by jaimeloci** [Simbul/baker#671]
In a HTML file we can link and view PDF files that reside inside the book folder but we are unable to return to that HTML page directly. Is seems that the PDF content replaces the HTML page from where it is accessed.

For instance, given /book/article.pdf and /book/p5.html and the link to the PDF, if we activate the link then the PDF gets loaded and we can scroll up/down to any of its pages. But, how can we return to p5.html from there? The only solution I have found is to swipe to next/previous pages and return to p5.html.

Also, depending on the rendering mode:
- “screenshots”, we will have to move 1 page and then return
- “three-cards”, we will have to move 2 pages and then return

Is there a way to go back to the HTML page directly?

**Comment by folletto** [comment]
Using PDF inside Baker is not supported, sorry.

**Comment by jaimeloci** [comment]
I see, and now I'm confused because we can actually open the PDF files while Baker is running. If Baker is not opening them, what is then? Thanks!

**Comment by benoitchantre** [comment]
There's a feature request (#609) to be able to open a pdf file in the modal view. To come back to your book, the only thing you will need is to close the modal view.
If you are interested, you can vote for it.

Your PDF should be something complementary to your book, it should not be a part of its content.

@folletto, does this feature request match the way we should build a book for Baker?

**Comment by jaimeloci** [comment]
Yes, benoitchantre, that is the point. The content is written in HTML while complementary documents are stored apart. This is useful when we are writing about a topic and add bibliographic references (we link them to the PDF).

**Comment by sportyguy209** [comment]
@benoitchantre @folletto Speaking of which, I think this may be a related issue, is there a way to zoom a photo or a linked website to full size and then return directly to the original page? I've only been able to get back to the original page by moving to the next or previous page and then going back to the original page again.

**Comment by benoitchantre** [comment]
At the moment, a workaround is to put your PDFs somewhere on the web. You will then be able to open them in the modal view. Look at the wiki to see how to open a link in the modal view and remove your links from the PDFs, you will be able to close them with the button of the modal view.
That's probably the easiest solution for the moment.

**Comment by benoitchantre** [comment]
Have a look at the wiki, it's explained how to <a href="https://github.com/Simbul/baker/wiki/Managing-links-and-urls">manage URLs</a> with Baker.
To play with images, it's better to handle that directly in your pages using Javascript.

**Comment by folletto** [comment]
@benoitchantre Baker is made to support HTML5 and PDF isn't part of it. We might support - as your feature request does - PDF opening in the future, but not as book elements.

@jaimeloci The fact that right now it "opens" a PDF is just a byproduct of the components we are using.

@sportyguy209 As @benoitchantre said, just open your URL in the modal window. Check the wiki. :)

**Comment by jaimeloci** [comment]
Thanks guys!
