### ISSUE TITLE
Video Question

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#672]
First of all, please understand, I am not a programmer or developer, but I've managed to muddle my way though Baker and create a reasonable looking publication on an iPad. I have included video on some pages which can be viewed inline or clicked on to resize and fill the entire screen. When the video fills the screen, you touch the screen, video controls appear on the bottom of the screen and the top gives a choice of "Done" which returns you back to the page.

Here is my question. I'd like to swipe to a page in my magazine that displays a poster frame of the video full page/full screen. Then, when the user pushes play, the video goes to full screen, plays, and provides those touch controls including "Done".

When I try that now, the poster frame starts out full screen, the video is sized full screen on touch, the bottom controls appear, but the top "Done" is not available (and does not appear upon a touch). There is no way to quit out of the video other than scroll to the previous or next pages unless you click on resize button (bottom right) which is not very intuitive. But, if you do choose it, the video doesn't change size, but the top "Done" control will then appear on a touch.

This may have an obvious answer, but I haven't figured it out and would appreciate any guidance you can provide.

TIA

**Comment by Simbul** [comment]
@sportyguy209 sorry for not getting on top of this sooner. Have you managed to solve it in the meantime?
