### ISSUE TITLE
Newsstand question

### ISSUE THREAD

**Issue by badstorm** [Simbul/baker#674]
Hi,
can i create my app with all the characteristics of the Newsstand( download of the new issues from my server) but in an app outside the Newsstand app of apple?

My intent is to create an app like your standalone version but with the capability to download new issues from my server.

Thanks.

Marco

**Comment by Simbul** [comment]
You can indeed do that, but you'd have to write a sizeable amount of code yourself, to replace all the facilities that Newsstand provides.

In the end, Baker is open source, so you can do whatever you want with it ;)

**Comment by benoitchantre** [comment]
There's a feature request like that: #644
You can put a comment to notify your interest in that feature.

**Comment by badstorm** [comment]
I found a simple solution to get my intent: I set "NO" in the file Baker-Info.plist at the voice "Application presents content in Newsstand".

I think that I can publish it on the App Store like a normal app.

**Comment by Simbul** [comment]
I have to confess that I'd be curious to see the outcome of that, but I don't think that's going to work.

Apple is rather strict with Newsstand: if you use Newsstand Kit, your application must be in Newsstand or it will be rejected. If you don't use Newsstand Kit, you'll have to implement downloads and issue management on your own, as I mentioned before ;)

**Comment by Simbul** [comment]
Hi @badstorm, any followup on this?

**Comment by ghost** [comment]
I'm curious of the outcome too. I'm not sure of exactly what @badstorm is looking to do but other apps that are not in the Newsstand have the ability to do in app purchases.

**Comment by badstorm** [comment]
I wrote to Apple and I explained my intent. Now i'm waiting for the answer.

Il giorno 29/gen/2013, alle ore 14:23, darren2c57 notifications@github.com ha scritto:

**Comment by Simbul** [comment]
@darren2c57 you can definitely have an app with purchases that's not in newsstand. 
What you cannot have, at least at the moment, is an app based on baker that supports downloads without requiring newsstand ;)

Alessandro

**Comment by folletto** [comment]
Is there any progress on this issue?

**Comment by Simbul** [comment]
Closing as inactive.
