### ISSUE TITLE
Video Size Question

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#678]
I'm trying to get video to display full screen (edge to edge) on an iPad (landscape view), but no matter what size video I start with I'm getting the same sized black bands at the top and bottom of the screen. I started with 1024 x 768 and got black bands. I resized the video to 768 x 768 just to see what would happen and I got the same result (smaller screen with black area on the top and bottom of the screen. What am I doing wrong or what should I be doing?

TIA

**Comment by Simbul** [comment]
Are you getting the same issues on Safari on the iPad?

**Comment by sportyguy209** [comment]
@Simbul Yes, when I preview the page in Safari, I'm getting black bands on the top and bottom of the video. So, the video and black bars appear the same in Safari as when I output to my iPad.

Now, I'm hoping you can tell me how to get rid of them in both places.:-)

**Comment by Simbul** [comment]
That's not really a Baker issue then.
I'll leave this open in case someone wants to contribute, but you should really be looking for the answer somewhere in the Apple documentation/forums ;)

**Comment by sportyguy209** [comment]
@Simbul Good point, didn't realize that the same issue was happening in Safari until you mentioned it! I haven't found anything in Apple's documentation and have posted on the Apple Forums (under video) on this issue, but have been getting coding replies, when I need to solve the issue through html, css, or javascript. I'll check in the Safari group and post the answer here if I get one. Unfortunately, I've found Apple's Forums to be less than helpful.:-( In the meantime, if anyone knows the answer, please let me know. TIA

**Comment by sportyguy209** [comment]
@Simbul OK, I've done some more work on my video issue and think it's either a Baker issue or an iPad issue.

I took a video sized 1024 x 768 and placed it in a video tag in a plain html file with no css. The only markup was in the body style of 0 margin and 0 padding. It shows up full screen in Safari, but when I move it to the iPad I get the top and bottom bands and it is no longer full screen.

The first time I tried this I did not use any height or width attributes. It appeared fine in Safari, but in miniature on the iPad. The second time I included the width and height attributes in my video tag and got the black bands on the top and bottom of the video instead of it going full screen.

Other than that the video appears as it should, and plays at it should.

**Comment by Simbul** [comment]
Right. What you should check is what happens if you render the same code in Baker on the iPad and in Safari Mobile on the iPad. This could give you an idea on where the issue really lies ;)

Also, search through the archive for other issues related to "video": it may help.

**Comment by sportyguy209** [comment]
@Simbul OK, back to it's looking like an Apple question. I saved a video based on Apple's size specs and get the black bars on the top and bottom. I can't seem to get the right sizing on my video to display full screen without the fit to page button.

**Comment by folletto** [comment]
You can try then to report a bug to Apple here: https://developer.apple.com/bugreporter/

I'll close this issue since it's not something we can solve on our side. I'm sorry.
