### ISSUE TITLE
Designing for Baker

### ISSUE THREAD

**Issue by nfeiglin** [Simbul/baker#679]
Discussion:
While this isn't entirely related to Baker I came across this Indeisgn to HTML / CSS tool that I thought the Baker community could benefit from. http://ajarproductions.com/pages/products/in5/

I'm thinking of buying it and giving it a shot. Does anyone have experience with other similar tools?

**Comment by nin9creative** [comment]
I backed it on Kickstarter.  Works ok.  Outputs a lot of images with HTML wrapper.  I had sent some feedback to the developer
regarding ways he could make it easier for Baker to consume.  As I recall right now it dumps everything into a single HTML file etc...

It's interesting, but was rough when I was testing it out.

Andrew

**Comment by tablazines** [comment]
Note that seem less Baker integration is due in a future upgrade. I'd wait.

**Comment by folletto** [comment]
I had a chat with the authors and I can confirm they are working to see if it's possible to integrate a Baker export function in the tool. I can't confirm on any ETA tho. :)

**Comment by Simbul** [comment]
The plugin has been released, so I'm closing this thread. See issue #756 for more info.
