### ISSUE TITLE
Pixelated Image

### ISSUE THREAD

**Issue by nadzree** [Simbul/baker#68]
The picture is ok if being viewed on the html page using a browser. 
However when being converted using the Baker frameworks, it turn out to be pixelated and worse when I zoomed in.

**Comment by nadzree** [comment]
Image in jpg format

**Comment by folletto** [comment]
Uhm it's strange because there's _no_ conversion done by Baker, and at the same time it shouldn't zoom. Could you give us a link of an example book that has that problem?

**Comment by nadzree** [comment]
Thanks for the reply.

You can download the sample here :
http://www.nadzree.com/book.zip

But you need to enable the zoom first to see the image pixelated.
It is ok when I zoom it using a computer browser.

**Comment by albertosarullo** [comment]
What is the size of image?

Ios has several resource limits: each png, gif and tiff image has limits of 3mpixel ( http://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariWebContent/SafariWebContent.pdf ).

I have similar problem, solved by splitting big png image in 3 smaller images.

**Comment by nadzree** [comment]
The image in jpg. Does that include in the ios restriction?
Yess!! good idea in splitting the image into portions..Thanks!!

Will try that later.

**Comment by nadzree** [comment]
I can confirmed that splitting the image will solve this problem. Thanks a lot albertosarullo!!

But is there any way to bypass this?

**Comment by albertosarullo** [comment]
:) 

But what is the size of image?

**Comment by albertosarullo** [comment]
I made several test with png and jpg images

If png size is > 1024_1024_3  (example: 768x4103), safari hide the image, otherwise (example: 768*4090) safari show the image.

If jpg size is >  1024_1024_3  (example: 768x4103), safari subsamples the image, otherwise show the image

 The limit is 768x4096pixel

**Comment by nadzree** [comment]
Thanks albertosarullo.. The image size is 2474 × 3299..

**Comment by Xm4s** [comment]
Since this problem seems to be solved I'm closing this issue up.
Thanks to nadzree and albertosarullo for pointing our this problem and provide a good solution :)
