### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#681]
Hello, I am working on my first Baker app. Thank you for such a wonderful framework!

But i have a problem with video playback. Video can't be paused when user press on pause button on youtube player. Video playback pauses for a moment and then resumed. Tested with the Laker magazine. This bug is reproduced only on iPad with iOS 5.0, 5.1, 6.0

You can download .hpub file from https://dl.dropbox.com/s/dh6zbefobjcymq9/Laker-Example.hpub
You can use link https://dl.dropbox.com/s/3m5yliyztuoskbm/issues.json as NEWSSTAND_MANIFEST_URL for testing.

**Comment by Simbul** [comment]
Have you tried testing this in Safari Mobile as well?

**Comment by ghost** [comment]
Yes, I tested in Safari Mobile. I also created a test project with a single UIWebView and loaded this magazine from the resources.
In both cases, this bug is not reproduced

**Comment by yujulio** [comment]
I'm having this issue too, the only solution I found was downloading the
videos from youtube and host it myself using the html5 player.

2013/1/30 Dmitry-Gruzd notifications@github.com

**Comment by ghost** [comment]
Hmm, it seems that the problem was in the UserAgent. Thus, if we remove the UserAgent, the video will play without any problems and the video player will look like in Safari.

**Comment by brianharrington** [comment]
I am also having a similar issue. With vimeo I can embed the video it appears ok on the surface but when it comes to playback it just spins trying to load. I have also tried loading the link directly. ie: vimeo.com/video/12345678?referrer=Baker still nothing but spinning.

**Comment by yitweng** [comment]
@brianharrington. I am facing the same issue with the Vimeo files :(

**Comment by Simbul** [comment]
@Dmitry-Gruzd so did you solve it in the end? And how exactly? Your solution may be helpful to other people in the future :)

Note that possible solutions for Vimeo are discussed in issue #510.

**Comment by wwarder** [comment]
@Dmitry-Gruzd Did you delete the UserAgent from AppDelegate.m? I can't find any other files with that parameter. 
I tried to delete it but the video still can't be paused :(

UPD: Solved it! I've just clean the Xcode build

**Comment by ghost** [comment]
Simbul, yes i solved it. Just remove initialization of UserAgent from AppDelegate (or set another one). After that video player will looks like a native video player in Safari and problems with playback will be solved (tested with youtube videos)
