### ISSUE TITLE
App approved

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#683]
We just had our Baker newsstand app approved by Apple this week: 
https://itunes.apple.com/gb/app/anfield-wrap/id583362683

Big thanks to the Baker community, I wouldn't have been able to do it without you. :)

**Comment by benoitchantre** [comment]
Nice work!
One question: why didn't you used the three-cards rendering mode?

**Comment by anjimi** [comment]
Thanks!
Using screenshots mode (with prerendered solid black screenshots) because of this issue https://github.com/Simbul/baker/issues/440

**Comment by Ajguy** [comment]
Congrats! Downloading it now. The screens look great!

**Comment by Simbul** [comment]
Very happy to hear that, congratulations!

**Comment by aspek** [comment]
How you can get position of page from index.html?

**Comment by folletto** [comment]
@aspek for that follow Issue #350. :)

**Comment by aspek** [comment]
@folletto Thanks!

**Comment by folletto** [comment]
Hello! It's an excellent publication, we added it to the showcase!
http://bakerframework.com/books

Congratulations :)

**Comment by santyas** [comment]
Nice index like dps ;)
