### ISSUE TITLE
Weird problem with downloaded issues.

### ISSUE THREAD

**Issue by yujulio** [Simbul/baker#685]
Hi. 

In newstand mode, after downloading 2 issues the next one I download doesn't show correctly. It's like the issues were corrupted, the styles doesn't load correctly I believe. This only happen in the downloaded app from the App Store, with the simulator and device simulator works just fine. I've tried uninstalling and installing again, reuploading my issues to the server and the problem's still there.

My issues have an average of 50Mb per issue, it's made completely by images and I can see embed videos from youtube. So I'm guessing the HTML works fine but not the CSS.

**Comment by Simbul** [comment]
When you say "device simulator", do you mean testing it on the actual device through XCode?

Does it always happen with the same issue or the downloading order doesn't matter?
Could you post a picture of how the issue should look and how it looks when things break?

**Comment by yujulio** [comment]
Yes, when I test it through the XCode works perfectly.

It only happens from the third issue you download, I can be any issue.

Right now I can't give you the picture because I left the iPad at work,
I'll update you guys on monday.

2013/2/2 Alessandro Morandi notifications@github.com

**Comment by yujulio** [comment]
How it should look:
![Captura de pantalla de Simulador iOS 04 02 2013 16 51 36](https://f.cloud.github.com/assets/678854/125321/e4b755fa-6f10-11e2-9d29-299f9a72db01.png)

How it looks:
![IMG_20130204_164944](https://f.cloud.github.com/assets/678854/125336/6d0eb290-6f11-11e2-9ab0-253e579dde3c.jpg)

![IMG_20130204_164953](https://f.cloud.github.com/assets/678854/125335/6cfe63cc-6f11-11e2-8813-52693e2dc570.jpg)

I just realize that it doesn't even load all the dossier, more than half of it doesn't show nor the index.

**Comment by folletto** [comment]
I really have no idea what could trigger that behaviour, sorry. :|

Could you link us the app from the AppStore?

**Comment by yujulio** [comment]
Sure, this is the  iPad one https://itunes.apple.com/us/app/nos.3-magazine/id528873285?l=es&ls=1&mt=8 .

2013/2/11 Davide Casali notifications@github.com

**Comment by folletto** [comment]
I tested it and I think your problem there is memory load. You have huge pages working in three-cards mode. Have you tried using screenshot mode and using JS techniques to reduce the load?

**Comment by yujulio** [comment]
I tried the screenshot mode but my client doesn't like it, he insisted in
using the three-cards mode, and what do you mean using the JS techniques?
Something like lazyload?

2013/2/12 Davide Casali notifications@github.com

**Comment by folletto** [comment]
What didn't the client like about the screenshot mode?

Yes, something like lazyload.

**Comment by yujulio** [comment]
The flashing thing. He really hated that effect.

2013/2/13 Davide Casali notifications@github.com

**Comment by folletto** [comment]
However, the flash is a result of the page itself, by design it's completely seamless. :)

**Comment by anjimi** [comment]
It sounds like the flash @yujulio describes in screenshot mode is the same thing I get, discussed here: https://github.com/Simbul/baker/issues/440

I get around it for now by including pre-rendered screenshots which are solid color - the same color as my background color.

**Comment by yujulio** [comment]
@anjimi And how do you include pre-rendered screenshots? I could use a solid white one.

The problem with the flash is because my client doesn't like the fact that he starts to read the magazine and suddenly a flash appear, like @anjimi said, I could get around it showing a blank page until the screenshot render the page so the users have to wait to see the content.

**Comment by folletto** [comment]
Ok. The important thing in a general sense is that you work to decrease memory load, that seems likely the issue. The white flash is a WebKit bug so there's nothing we can do, only Apple can (and please, open an issue on Apple's Bug Tracker if you can). :D

**Comment by anjimi** [comment]
1. set parameter '-baker-page-screenshots' in book.json to screenshots folder, see: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters (obviously '-baker-rendering' should also be set to 'screenshots')
2. save a blank image with your background color, both portrait & landscape dimensions (if your publication uses both), and then duplicate the screenshots for as many pages as you have in your app, e.g.:
   screenshot-landscape-1.jpg
   screenshot-landscape-2.jpg
   screenshot-portrait-1.jpg
   screenshot-portrait-2.jpg

That's how I do it for now :)

**Comment by Simbul** [comment]
@yujulio are you still experiencing the issues we were discussing in this thread?

**Comment by yujulio** [comment]
Not anymore, you can close this thread. Thanks.

2013/4/8 Alessandro Morandi notifications@github.com
