### ISSUE TITLE
Outland Moto is in the App Store!

### ISSUE THREAD

**Issue by Ajguy** [Simbul/baker#686]
Our magazine, Outland Moto, was just listed in the App Store! https://itunes.apple.com/us/app/outland-moto/id595720158?mt=8

I'd like to extend a huge thank you to the Baker developers and community. There's no way any of this would have been possible without everyone's help and expertise. I'd love it if you'd all give the app a look and posted any comments or questions you have.

And of course I'll be paying it forwards. I'll always be checking the Github for Baker to help out any way I can.

**Comment by Simbul** [comment]
Great news, congratulations!

**Comment by folletto** [comment]
Congratulations. :)

**Comment by folletto** [comment]
We checked it and we decided to add it to our showcase! :)
http://bakerframework.com/books

Congratulations. :)
