### ISSUE TITLE
Configuring standalone: I miss something (it's me, I know...)

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#687]
Hi,

just a quick question: I'm developing a digital publishing project but I've also decided to use my project + Baker to create my portfolio: an app I always have on my iPad is really helpful :)
Since I want to keep my portfolio app made with Baker separate from everything else, I went with a standalone app.
But I have some problems with the CONFIGURE BAKER STANDALONE procedure.
Point 6 is ok - commented out the line - but I don't understand (it's me, I'm a graphic designer, I know...) where I have to remove NewsstandKit.framework from the list of linked libraries. I can't simply find where, sorry :(
Point 8 is ok (or I think so :)

**Comment by Simbul** [comment]
Not your fault, really: that tutorial takes quite a lot for granted :)

You need to select your project, then your target, then in the "Summary" tab remove NewsstandKit.framework. This screenshot should help you locate it.

![baker frameworks](https://f.cloud.github.com/assets/147104/125853/1afa94fe-6f27-11e2-8544-7eee9b1d2367.png)

Let me know if this helps you.

**Comment by ilpiac** [comment]
Ahhhhh :) Great and very useful screenshot!
I will try later (now I'm working on a Mac without XCode) but I think I can deploy a standalone app now.

Thanks a lot

**Comment by folletto** [comment]
Is everything ok then? May I close this issue? :)

**Comment by ilpiac** [comment]
Sorry guys, I got a very bad flu so didn't work for some days...
You can close it, for sure.

Thanks!
