### ISSUE TITLE
Ready -> Putzalarm!  :: App & eBook ->  AppStore

### ISSUE THREAD

**Issue by webschnecke** [Simbul/baker#688]
Hey guys,

have a look and feel free to download ;-) 
Putzalarm! is available at the Appstore worldwide. At this time in german language only.
The app supports you with your housework; it is a plan how to clean the flat. 

Microsite:
www.putzalarm.agenci.de

Putzalarm! - PRO
http://itunes.apple.com/de/app/putzalarm!/id537208071

Putzalarm! - GRATIS (free)
http://itunes.apple.com/de/app/putzalarm!-gratis/id590707334

Have fun.
greetz webschnecke

**Comment by folletto** [comment]
Hello! Unfortunately I checked but the code seems incomplete. I contacted you in the email to update it and evaluate the inclusion in the showcase. :)

**Comment by webschnecke** [comment]
Hi,

thanks for your Mail.

I've sent you PromoCodes at the 18.01.2013 -  and I filled out the form ;-) - hmmmmmm -> nirvana?
Maybe you find my mail? Or do you need the infos again?
