### ISSUE TITLE
Adding toolbar icons to Navigation bar

### ISSUE THREAD

**Issue by rtshittu** [Simbul/baker#690]
Hi Guys,

I have really been enjoying the baker framework.  You guys did a great job.

However, I am looking at customizing my app.

I want to add some toolbar icons such as Bookmark, facebook, twitter, help, library etc at the navigation bar at the top and also to add another navigation at the bottom on both shelf and viewer.

The question is which file will I edit.(I am new to Objective C) in the Baker Master?

**Comment by folletto** [comment]
I think the answer is... you are going to edit a lot of files to do that. :)
If you want to start editing Baker in Objective-C it's better if you start looking at it and understanding how it works in the various files and then you could start working with it.

As a rough overview, consider that there are two main components, the Baker view (the actual player showing the HTML5 pafes) and the Baker Shelf (the one that shows the list of books). These two elements are separated, they communicate just through a small call and they are placed on the screen in a navigation structure.

**Comment by rtshittu** [comment]
wow!!! I agree.  Kindly recommend some books or resource that can really help me so fast to understand Objective C on Xcode

**Comment by rtshittu** [comment]
@folletto, I must say, customizing to have the icons in place is a lot of work.  But i would like to suggest that, can the new version of Baker include some of these features?  It would really be so awesome! 

I downloaded TAW app on my iPad and i like the way the index page comes on. its really nice, how about that too.

Thanks.

**Comment by folletto** [comment]
It's a _bit_ vague. We already have issues opened here that are tracking these issues. But it's about the feature request (i.e. search) and not about the solution (i.e. put an icon on the toolbar). Check the ones that are missing in your opinion and add them. :)

I'm closing this issue then. :)

**Comment by rtshittu** [comment]
ok
