### ISSUE TITLE
The Nimble Magazine is out,  reached Issue002 today

### ISSUE THREAD

**Issue by nonuts** [Simbul/baker#691]
Hey guys,
I wanted to wait a little to see if all runs smooth, but now let me send you all a HUGE thank you:  The Nimble Magazine -- a tiny magazine about mobile art, fluffy animals and other disruptive culture stuff got approved two weeks ago, without any hassle.
https://itunes.apple.com/us/app/the-nimble-magazine/id590761909?l=de&ls=1&mt=8

Web-Touch-Points:
http://nimble.nonuts.de

In case you care, I posted some thoughts about the mag and the tech setup here.
http://www.nonuts.de/blog/2013/1/18/the-nimble-magazine-10

Many many thanks to each and all.

**Comment by nin9creative** [comment]
Cool!

Warm Regards,
Andrew

**Comment by nonuts** [comment]
andrew, thx!
I still haven't found any time to lay my hands on magrocket. soon!
