### ISSUE TITLE
External links in modal window/safari and book.json property file

### ISSUE THREAD

**Issue by calaba** [Simbul/baker#693]
Hello,

1st - good job with the baker! I would love to see working (really working) Android port :) ... anyway ... 

I have been playing with external links display. There is little bit of docu on it here - https://github.com/Simbul/baker/wiki/Managing-links-and-urls .  Well, the docu is not accurate (at least for my version 4.0 of Baker). The behavior in my context (using Laker on top of Baker) is that any link is opened as internal link in (BakerView) unless you specify the ?referrer=Baker (modal window) or ?referrer=Safari (opens link in Safari). 

What I like is the modal window for external links. Reasons:
- It gives the option to zoom in/out (which I am loosing with Laker and display of external link in BakerView to keep the formatting of the book nice)
- if link is opened in BakerView - there is no 'loading progress' visualization so the in case of external link which takes a while to load it seems for the reader that Baker app is frozen - that's not nice
- if opened in modal view - reader can decide to open the link in Safari - there is nice button for that - so anything which is integrated with Safari can be used - nice

As mentioned in Issue 255 (https://github.com/Simbul/baker/issues/255) - I also do have problem to correct every external URL link to use ?referrer=Baker - I don't want to reformat the e-book from ePub just to use this for Baker. So I ended up with modifying the 4.0 source code to ignore the referrer= tag and just open every external link in modal view.

Suggestion:

Wouldn't it be very useful to have baker specific property in book.json to decide what is the default viewer for external links (BakerView/Modal Windows/Safari ...) so any external link  (the one starting with http(s):// ...) is opened by that customized default viewer - unless overridden by ?referrer parameter of particular link ... ???

I would suggest name like: -baker-external-links-viewer defaulting to BakerView (for backward compatibility).

Ric.
 .

**Comment by folletto** [comment]
Hi @calaba,

Thanks for the feedback, you raise a lot of interesting points of discussion. :)

First of all, we updated the wiki, so now it's accurate. As you noticed there was a typo and it was misleading. :)

As for the suggestion, unfortunately we can'd add a default behaviour for normal links, the reason is that pretty much any javascript out there rely on the fact to be able to use standard URLs in page. Many people use libraries like Google Maps and adding a default behaviour "open in modal" would make all these scripts to simply stop working.

To solve your problem at hand is actually quite simple: just write a regexp and append automatically the `referrer` parameter to all your links. It's a very quick operation with common editors that support regexp. :)

**Comment by calaba** [comment]
Hi Davide - @folletto 

just quick comment with my idea -> i wasn't suggesting overriding the current behavior by default. I was suggesting to add an option to be able to override the current viewer of external links (which is now defaulted to BakerView) to another viewer (modal view/ Safari) for all links - if and only if specified in book.json file. So all (new/old) apps not specifying this new parameter would still use the current behavior (BakerView). Thanx for regexp advice however I don't see changing the links in the book source as the right solution from SW architecture standpoint. Of course it is a solution - but then I like my ad-hoc solution (changing the code) better as it is much less work :).

Best regards, ric.

**Comment by folletto** [comment]
Well, you don't have to change the source, just add a script before you prepare the Hpub package and you're done (even simpler if you have a CMS that manages your Hpub export feature). :)
