### ISSUE TITLE
Can Baker bake WordPress Pages for daily newspaper?

### ISSUE THREAD

**Issue by rtshittu** [Simbul/baker#694]
Hi guys!

I want to produce a daily newspaper and i want to use Baker framework.  so i am wondering if i have a wordpress pages can i still follow the same procedure to enable it on newsstand.

What strategy is best for me to get this done?

**Comment by folletto** [comment]
You probably have to write a plugin to automate the creation of the Hpub files and the `shelf.json` file from Wordpress. It's something that some private companies did, but so far there's nothing open source we can point you to. :)

The plugin should likely be able to select the posts you want to be part of the issue, export them as static HTML files and zip them up in HPub. At the same time it will update `shelf.json` with the new issue.

**Comment by surelynot** [comment]
Here's a plug in that does the wordpress to static html part well:
http://wordpress.org/extend/plugins/static-html-output-plugin/

**Comment by JeanetteMueller** [comment]
does anyone already started to develop such a wordpress plugin?

**Comment by Yago** [comment]
It would be so cool if such a plugin exist !

**Comment by Simbul** [comment]
It would be great if someone were developing such a plugin, and I'm sure they'll come to Github if they do. In the meantime, we're closing this.
