### ISSUE TITLE
hosting IAP content with Apple

### ISSUE THREAD

**Issue by surelynot** [Simbul/baker#696]
Hi all,

great work on implementing IAP for single issues, this has been the feature we've been needing!

We want to host the IAP content (in this case the .hpub magazine) with Apple, rather than having it downloaded from our server (which is currently working in the Sandbox environment), what changes to we need to make to the shelf.json file? 

I've tried removing the url line to the hpub in the hope it would default to the Apple server, and I've also failed to find a url to the product hosted on the Apple server in itunesconnect. (I also not that it adds a .pkg rather than .hpub extension once uploaded)

Cheers, Simon.

**Comment by Simbul** [comment]
Interesting question. We need to look a bit more into hosted content.
From what I could quickly gather, tough, it looks like subscriptions are not supported and you'll need to provide at least one subscription to get a Newsstand app approved. This means hosting content for Newsstand apps won't work.

Some more details: this is what I could understand so far (I might be wrong ;))

Content hosting is only available in iOS 6. To use it, you have to wrap the object you want to host (in our case the HPUB file) in a PKG object and upload it to iTunes Connect. I believe the wrapping can be achieved using XCode or the Application Loader app.

When you buy _non-consumable_ content (e.g. a single issue in Baker) your app gets a `SKPaymentTransaction`, which contains references to a number of `SKDownload` objects representing the content you hosted on Apple's servers. In other words, there's no way of accessing the URL of the content other than from a payment transaction.
This is what makes subscriptions impossible: you can only access hosted content for issues that were purchased individually, but subscribers have to be able to download issues that they did not individually pay for.

**Comment by surelynot** [comment]
Would it be possible to gather all the URLs to the specific issues through purchases in the Sandbox environment, and then implement those in the issues.json / shelf.json? 

If this could be made to work, along with a subscription pingback service like Beeblex.com – see issue #697 – we might get to a point where someone could utilise Baker without actually needing to have their own servers, just having a folder of .json files and some thumbnail images 'in the cloud'. This would expand the potential user base massively I think.

I'm a little fuzzy about subscriptions though and how they work, mainly we'd only be implementing them to comply with the Apple approval, so I haven't looked into them much. (In reality, and others may be thinking along the same lines (issue #644), we'd see Baker with its shelf and IAP for single items as a kind of branded book store for our one off publications, rather than a periodical as such, so Newsstand/Newskit is a means to an end rather than a natural fit.)

**Comment by Simbul** [comment]
Closing as the discussion has not been going on for quite a while.
