### ISSUE TITLE
IAP transaction confirmation

### ISSUE THREAD

**Issue by surelynot** [Simbul/baker#697]
Hi all,

with IAP now implemented (thanks!) in Baker, I've been looking into the best ways of managing the transaction confirmation, what's referred to in the wiki as Subscription Pingback.
https://github.com/Simbul/baker/wiki/Subscription-pingback

It seems that this side of things is particularly complicated, though necessary thanks to our Russian hacker friends, and could be a barrier to the less technically minded among us to using these features (at least, securely). In my searching I found this group offering a solution, which seems to be in the same spirit of Baker (ie both free and well put together):
http://www.beeblex.com

Has anyone looked into this? Is there an easy way to set up Constants.h as the subscription/purchase confirmation server in the same way a local server might be used? It would make a great addition to the wiki link above, which I'd be happy to write up if someone more adept can take a look at it!

Cheers, Simon

**Comment by Simbul** [comment]
Beeblex looks like a very interesting project, thanks for bringing it up!

Unfortunately, at a first glance it looks like integrating it with Baker would be more complicated than just editing `Constants.h`: there's a library you have to include to talk to the Beeblex server.

As an aside, while working on auto-renewable subscriptions, we're reviewing subscription pingbacks to make them less complicated ;)

**Comment by Simbul** [comment]
Closing this old issue. You may want to have a look at MagRocket ;)
