### ISSUE TITLE
Vertical index

### ISSUE THREAD

**Issue by trudderham** [Simbul/baker#698]
Is it possible to set the index file to display vertically, instead of horizontally across each page? I have a lot of pages in my book and believe it would be easier to navigate them by displaying the index on the left-side of the screen.
Any ideas or help would be really appreciated.

**Comment by Simbul** [comment]
Yes. If the HTML file for the index is not as wide as the viewport, it will snap to the left.
Also, see `-baker-index-width` in the [Baker parameters](https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters) list.

**Comment by trudderham** [comment]
Thanks so much for the quick reply, that worked brilliantly.

**Comment by Simbul** [comment]
:+1:
