### ISSUE TITLE
HTML files read alphabetically

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#7]
As a user I want to use any name for my HTML files, seeing them inside Baker alphabetically ordered.

**Comment by Xm4s** [comment]
I'll handle this

**Comment by Xm4s** [comment]
Handle custom file names and alphabetical order visualization. Tested on simulator and pushed on main branch, waiting for a test on physical device (just to be sure all is ok) before closing.

**Comment by folletto** [comment]
Note: this is going to change slightly the handling of page numbers.
Now we are using 1.html, 2.html, but with the alphabetical ordering now 1.html is followed by 10.html, so we need to state the change clearly when we are going to release this update in the downloadable package.

**Comment by svdgraaf** [comment]
I'm not sure whether alphabetic ordering is smart, also looking at what folletto notes above. I would love for the hpub standard to define how the files should be named, I personally liked the numbered pages a lot :)

**Comment by folletto** [comment]
Yes, but it's not feasible: too many kinds of book, too many needs. Even making one book with the current numbering is a pain, so alphabetically the author retains full control. :)

**Comment by svdgraaf** [comment]
Suggestion: default to numbered pages, or define a file order in the meta file?

**Comment by segundoseis** [comment]
I think it's a good choice to define the order in a configuration file as you said svdgraaf.
Have considered the possibility that it might be multi language? in that case I think that may complicate that order it just by numbers.

**Comment by folletto** [comment]
Consider that every setting we add to the standard, the less it's probable it could became a real standard.

Alphabetical ordering works already well without any kind of setting, and that's the assumed default for many systems, from how the filesystem shows you the files, to how we manage chapter numbers, allowing also numbering if you want to. No setting needed, works outside of the box intuitively. :)

**Comment by folletto** [comment]
Confirmed and tested, it works. :)

**Comment by bru** [comment]
suggestion, maybe keep it ordered numerically and add the title of the chapter to the name of the file: 1.intro.html, 2.early_days.html, 3.the_end.html ...

**Comment by folletto** [comment]
Yup, that's something that is going to happen already if they are ordered alphabetically. Just, if you have more than 10 page, it's going to be: 01.name.html, 02.name.html and so on. :)

**Comment by jeffehobbs** [comment]
Flexible and elegant!
