### ISSUE TITLE
no provisioned device connected

### ISSUE THREAD

**Issue by Contexter** [Simbul/baker#70]
since all other xcode projects do detect a connected device - maybe that's a baker plist issue?

Greetings from Berlin

Bene

**Comment by folletto** [comment]
Hello! Could you detail a little more your problem? :)

**Comment by Contexter** [comment]
after doing a fresh clone of the github repo I try compiling - which works for the simulator target, but doesn't for the device target - getting: "No provisioned iOS device is connected." But that's simply not the case. All other fresh clones, (for instance three20) do compile and run on - in my case an iPod . That's unfortunately all I can say ...

**Comment by Xm4s** [comment]
Could you please check that the value of "Target Device Family" in the active target build setting is equal to "iPhone/iPad"? 
By default Baker framworks targets only iPad, so if you try to deploy it on a device that's not an iPad you'll receive an error (the same one you are reporting).

**Comment by Contexter** [comment]
I set "Target Device Family" in the active target to "iPhone/iPad" but unfortunately still get "No provisioned IOS devices are available" ... (I'm on a fresh install of XCode 4) ... any idea?

**Comment by Xm4s** [comment]
I've also cloned a clean copy of Baker and tried to deploy it on my iPhone through a fresh install of Xcode4: after setting the right device family (and the base SDK, switched from iOS 4.2 to iOS 4.3) it just worked. 

So... another things that comes to my mind is the iOS installed on your iPod: which version it is? By defaul we target iOS 4.2 (and up on iOS 4.3 Baker seems to work like a charm :D ) so, if you have an older version, probably you'll get the same error.

**Comment by Contexter** [comment]
Sure, it's 4.2.1 (8C148) on an iPod touch ... but still the same "No provisioned ..." You may want to consider providing some test and and a test target?

**Comment by Xm4s** [comment]
Since I'm unable to reproduce this problem on my own, may I ask you if you can provide the Baker package that seems to trigger this unusual behavior?

**Comment by Contexter** [comment]
What do you mean by Baker package?

**Comment by Xm4s** [comment]
Maybe I wasn't too clear, sorry.

Since I'm unable to reproduce this behavior with a pristine clone of Baker and also no other user had this problem before, I'd like to see your clone of Baker, the code you have tried to deliver on the iPod.

Being able to see it may help me to spot the flaw that prevent you to install Baker on your device :)

**Comment by Contexter** [comment]
I've switched machines, did a fresh xcode 4 install, ran through the provisioning portal stuff, (installing .mobileprovision and .cer ) cloned baker from github, switched device family - but still the same:  please let me know where to send a copy of the whole thing - !

**Comment by Contexter** [comment]
<strong>That's what Marco found out, solving my problem:</strong>

" When I opened the project and check the Baker Target Summary I noticed that for "Deployment Target" the value it's a grayed 4.3, which means that no specific target have been selected, so Xcode assume the latest iOS to be the target.

Since your iPod runs iOS 4.2.1 try to change to set that to 4.2 and that should do the trick: I've just compiled and run the code you send me on my "iPod from the past", an old first gen iPod Touch with iOS 3.1.3... well, didn't run very well (crashed almost instantly :P) but it got installed perfectly.

So once again before running the app check in the Baker Target Build Settings that the value in the Resolved column is as follow:
- Architectures                 Standard (armv6 armv7)
- Base SDK              iOS 4.3
- Target Device Family      iPhone (or iPhone/iPad)
- iOS Deployment Target         iOS X.X 

(where X.X is the lowest version of iOS you want to target, Baker support version of iOS from 4.0 to the latest 4.3, should work well even on iOS 3.3 devices)"

<strong> so it's: find the right switch and indeed - it WORKS !</strong>

**Comment by folletto** [comment]
I mark this as closed then. ;)
