### ISSUE TITLE
Vertical index scrolling

### ISSUE THREAD

**Issue by trudderham** [Simbul/baker#700]
I've set my index overlay to snap to the left of the screen via:
"-baker-index-width": 300,
"-baker-index-height": 1024,

And in the index.html file I've added:
<meta name="viewport" content="width=300, height=1024, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

However the index is scrolling horizontally. Is there a way to tell it to scroll vertically?

Thanks!

**Comment by folletto** [comment]
Well... is your page vertical? :)
The scrolling behaviour depends on the size of your page. Make the page 300px wide and it will scroll vertically. In other words: open it in Safari: is it vertical? If not, fix the CSS to make it so. :)

**Comment by trudderham** [comment]
That did the trick, apologies if this was a really simple question - and thanks, much appreciated!

**Comment by folletto** [comment]
You're welcome! :)
