### ISSUE TITLE
Autoload the TOC

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#701]
I would like to autoload the TOC on the cover, is that possible with a simple function?

**Comment by Simbul** [comment]
What do you mean by "autoload"?

**Comment by ghost** [comment]
Sorry, on the cover I want the TOC to appear at the bottom without the user having to double click.

**Comment by folletto** [comment]
Well... Baker is HTML5. The only way I can think of in HTML5 to do that is to use an iframe that includes the other page. :)

**Comment by ghost** [comment]
Thanks, been doing just that, was thinking I was making it too complicated and that there was a JS function buried somewhere you could call. Thanks for the great work.

**Comment by folletto** [comment]
You're welcome. :)

In a general sense, we tend to avoid as much as possible by "adding" features to the browser, to have books that are 100% compatible with the standard web. :)
