### ISSUE TITLE
exit fullscreen video -> page scrolls to the top

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#703]
I have found that when you close a video that was playing fullscreen, the page scrolls immediately to the top.

Can you reproduce it?
I'm using the native video player.

Here's the code I use for the video

``` html
<video poster="video/big-buck-bunny_poster.jpg" width="320" height="180" controls="controls">
    <source src="video/big_buck_bunny.mp4" type="video/mp4"/>
</video>
```

I can't reproduce this behavior in Safari (iOS) with the same test page.

**Comment by Simbul** [comment]
@benoitchantre  is this issue still present in 4.1?

**Comment by benoitchantre** [comment]
@Simbul I'll test that next week.

**Comment by benoitchantre** [comment]
@Simbul, I can't reproduce the issue with the latest code in the master branch (tested with iOS Simulator v.5.1, 6.0, 6.1)

**Comment by benoitchantre** [comment]
@Simbul, I have remarked something strange with iOS 5.1 only.
When you close the fullscreen video, the page is moved by 20px. This doesn't happen with iOS 6.0 and 6.1

![capture decran 2013-05-21 a 09 28 13](https://f.cloud.github.com/assets/1521015/540304/43f8b3ea-c1e8-11e2-8f26-6bddae84d6d8.png)

Should I open a new issue for that?

**Comment by Simbul** [comment]
Is it the same as #828?

**Comment by benoitchantre** [comment]
Yes.
