### ISSUE TITLE
Beginning with Baker

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#708]
Hi
I'm beginning with baker. I  download the package Hpub and the framework. I put the files of the Hpub pacakage in the books folder. I open the xcode project. I click to run... and  the build failed. WHY? I don't understand. Thanks for the help. Sorry for my english.

**Comment by aspek** [comment]
https://github.com/Simbul/baker/wiki

**Comment by aredqueen22** [comment]
Thanks I've searched someone who had same problems that me and so I didn't have the good version of Xcode... Damn.
