### ISSUE TITLE
SIGABRT Error on double tap

### ISSUE THREAD

**Issue by nadzree** [Simbul/baker#71]
Below is the error log. Help me please : (

Mar 14 21:29:06 SPLUS003 Female[143] <Error>: -[RootViewController userDidTap:]: unrecognized selector sent to instance 0x1a4fb0

Mar 14 21:29:06 SPLUS003 Female[143] <Error>: **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RootViewController userDidTap:]: unrecognized selector sent to instance 0x1a4fb0'
    **\* Call stack at first throw:
    (
        0   CoreFoundation                      0x31de164f **exceptionPreprocess + 114
        1   libobjc.A.dylib                     0x36adac5d objc_exception_throw + 24
        2   CoreFoundation                      0x31de51bf -[NSObject(NSObject) doesNotRecognizeSelector:] + 102
        3   CoreFoundation                      0x31de4649 ___forwarding_** + 508
        4   CoreFoundation                      0x31d5b180 _CF_forwarding_prep_0 + 48
        5   Female                              0x0000573f -[InterceptorWindow forwardTap:] + 22
        6   CoreFoundation                      0x31d4ef03 -[NSObject(NSObject) performSelector:withObject:] + 22
        7   Female                              0x00005925 -[InterceptorWindow sendEvent:] + 308
        8   UIKit                               0x3348a313 -[UIApplication sendEvent:] + 298
        9   UIKit                               0x33489c53 _UIApplicationHandleEvent + 5090
        10  GraphicsServices                    0x32f34e77 PurpleEventCallback + 666
        11  CoreFoundation                      0x31db8a97 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 26
        12  CoreFoundation                      0x31dba83f __CFRunLoopDoSource1 + 166
        13  CoreFoundation                      0x31dbb60d __CFRunLoopRun + 520
        14  CoreFoundation                      0x31d4bec3 CFRunLoopRunSpecific + 230
        15  CoreFoundation                      0x31d4bdcb CFRunLoopRunInMode + 58
        16  GraphicsServices                    0x32f3441f GSEventRunModal + 114
        17  GraphicsServices                    0x32f344cb GSEventRun + 62
        18  UIKit                               0x334b4d69 -[UIApplication _run] + 404
        19  UIKit                               0x334b2807 UIApplicationMain + 670
        20  Female                              0x00002853 main + 50
        21  Female                              0x0000281c start + 40
    )

**Comment by nadzree** [comment]
I fixed it by renaming :
- (void)userDidSingleTap:(UITouch *)touch {

To :
- (void)userDidTap:(UITouch *)touch {

Hurm...strange

**Comment by Xm4s** [comment]
We change all the occurence of "userDidSingleTap" to "userDidTap" in the commit <a href="https://github.com/Simbul/baker/commit/b074338637fdffdc4920597ec200020cce66274d">b07433</a>, so maybe you should check your local repository :)

**Comment by nadzree** [comment]
i see..thanks : )
