### ISSUE TITLE
progress on 4.1 with in app purchase?

### ISSUE THREAD

**Issue by teckmonkey** [Simbul/baker#710]
any luck on when 4.1 might be released,, or even beta'd ? in app purchases is what im really looking for!

**Comment by folletto** [comment]
Just keep tracking the milestone (click on Milestones above, here) and you can see the progress to version 4.1. :)

We don't provide any ETA since it's an opensource project without full-time people working on it, I'm sorry. 
The beta is always the current `master` branch. :)

**Comment by teckmonkey** [comment]
Is there anyway to add iAd so I can try to make some rev? Servers aren't cheap

**Comment by folletto** [comment]
It's opensource, you can add any code you'd like to. :)
