### ISSUE TITLE
"No internet connection" error with Baker 4.0

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#712]
I downloaded Baker 4.0 as well as the sample hpub, and I ran it on the simulator straightaway without changing anything. Then I got Baker Shelf screen followed by "No internet connection" error.

I also tried building ipa out of the project, and installed it on my iPad,  then I just saw the launch (I set my custom launch image) page appear then followed by a blank baker shelf page, nothing else could I do.

I wonder do I need to modify the settings or the code?

Kind regards,
Johnny

**Comment by folletto** [comment]
You need to follow the tutorials, first. Click on the "wiki" above :)
