### ISSUE TITLE
Accessing Variables from XCode inside HTML

### ISSUE THREAD

**Issue by arihant23** [Simbul/baker#717]
Hi,

I am interested in knowing if we can define variables inside xcode & then access it in HTML or javascript.

for e.g. Define a variable in xcode like this

NSString \* abc = @"Hi there!";

and access it in Baker or phonegap like this

<script>
var xyz = xcode.abc //XCode Variable
alert(xyz);
</script>

**Comment by folletto** [comment]
Yup. You can see my answer on StackOverflow about it:
http://stackoverflow.com/questions/9473582/ios-javascript-bridge/9473941#9473941

**Comment by arihant23** [comment]
Thank You so much!!!
