### ISSUE TITLE
internet connecion HELPS

### ISSUE THREAD

**Issue by moloragom** [Simbul/baker#718]
Hi im trying the new version of baker with the standalone and the newstand.
An i have some questions, first of all, the newstand is the kiosko of app store???
Well... i follow all the instructions and the tutorials and always appears the message of no internet connection.
I also try to upload the hpub to a server and try to downloaded and it work, but when i rub the app o  my ipad, it doesnt appear anymore the warning but neather apperar the book
Can someone help me.
My app have to be like kiosko but just with the magazines of my enterprise...
Thanks
Sorry for my english...

**Comment by yujulio** [comment]
Are you sure you did everything right from the wiki? Try to start over again. It might be a problem with your shelf.json

**Comment by molorago** [comment]
yes i did everything.
In the newstand u up your hpub in to server.
And in the standalone u place it in the folder books.
Which one is for the kiosko of the app store??? the newstand??
And if i want an app with just my magazines i do the tutorial for standalone
Im so confuse :(

**Comment by folletto** [comment]
Let's start from the basics, yes? This is what you find if you google for Newsstand: https://developer.apple.com/newsstand/

You should be able to login with your developer account and read about it. There are also nice video tutorials. :)

When it's clear what you are trying to achieve, you can start the tutorial over and, if you still have problems, please link here your `shelf.json` file. :)

**Comment by molorago** [comment]
Ok now it works
My magazine appears in the kiosko... and its ok...
But what i really need is that just my magazines appear in there.
SOmething like my one kiosko.... That is the standalone???
And if i want to add more hpub, i add the code in shelf.json and book.json?

**Comment by molorago** [comment]
thanks...

**Comment by molorago** [comment]
when u say this You don't have to periodically publish new issues (as required by Newsstand)
What it means??? i have to publish a magazine every month?? or one magazine in 3 months??
How it works??

**Comment by yujulio** [comment]
It means that you can publish any issue, anytime and everytime you want it.

2013/2/18 monica notifications@github.com

**Comment by molorago** [comment]
But doesnt have to publish like every month??? nothing happens if i just upp one magazine between 3 months=???

**Comment by yujulio** [comment]
That is up to you. As long as the app is aproved by Apple you can publish
new issue evetime you want.

**Comment by Simbul** [comment]
Closing as the discussion seems to be over. Feel free to reopen if you need to.
