### ISSUE TITLE
Image in page number

### ISSUE THREAD

**Issue by nadzree** [Simbul/baker#72]
How to put a watermarked image replacing the page number?

**Comment by nadzree** [comment]
what i meant is the loading with the spinner and the page number..want to replace the number with a watermarked picture..

**Comment by Xm4s** [comment]
Well, you can change the "initPageNumbersForPages" method in the RootViewController and, instead of creating and attaching UILabels with page numbers, you can attach your own images.

**Comment by nadzree** [comment]
i'm still new in the oc programming.

NSString\* labelImg = [[NSBundle mainBundle] pathForResource:@"logo" ofType:@"png"];
[labelImg release];

I've tried to do it this way but the image still did not appear.

**Comment by Xm4s** [comment]
Well, maybe you should user an UIImage object instead of a NSString.
Check the <a href="http://developer.apple.com/library/ios/#documentation/uikit/reference/UIImage_Class/Reference/Reference.html">UIImage Class Reference</a> from Apple iOS Dev Library :)

**Comment by nadzree** [comment]
Thank you sir!!
It worked.

```
    // ************Logo
    UIImageView *logo = [[UIImageView alloc] initWithFrame:CGRectMake(PAGE_WIDTH * i + (PAGE_WIDTH) / 2, PAGE_HEIGHT / 2 - 6, 100, 50)];
    [logo setImage:[UIImage imageNamed:@"logo.png"]];
    logo.opaque = YES; // explicitly opaque for performance
    [self.view addSubview:logo];
    [logo release];
```

Takes some time because the image doesn't load. Realize that i have not added the image into the project..bummer..

But now..the image did not disappear after the page transition..finding a way..

**Comment by nadzree** [comment]
Updated the code to :

CGRect frame;

```
    // ************Logo
    UIImageView *logo = [[UIImageView alloc] initWithFrame:CGRectMake(PAGE_WIDTH * i + (PAGE_WIDTH + frame.size.width) / 2 - 40, (PAGE_HEIGHT + frame.size.height) / 2, 100, 31)];
    [logo setImage:[UIImage imageNamed:@"logo.png"]];
    [[self scrollView] addSubview:logo];
    [logo release];
```

And the logo disappear after the page load just as what I wanted : ) thanks a lot Xm4s

**Comment by Xm4s** [comment]
You're welcome :D
