### ISSUE TITLE
How can i prove the button of subcribe

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#721]
I already thit all the itunes connect process and everything.. but how i know that its working??? There is some way to prove it??
Thanks!

**Comment by aspek** [comment]
I have same problem. But in my case the problem can solved if you add new an app and upload it to your itune connect.

**Comment by molorago** [comment]
dont undesrtand, can u be please more specific

**Comment by aspek** [comment]
Upload your app to itune connect.

**Comment by Simbul** [comment]
@molorago is this issue still valid, or have you managed to solve it in the meantime?

**Comment by Simbul** [comment]
Closing as inactive.
