### ISSUE TITLE
changes for 4.0 tutorial for standalone

### ISSUE THREAD

**Issue by philippgeuder** [Simbul/baker#722]
as far as i can tell, the guide in the wiki is a little confusing. at least i struggled with it, so i suggest some changes:

> ### REQUIREMENTS
> 1. A Mac with Xcode
> 2. An [Apple iOS Developer account](https://developer.apple.com/programs/ios/)  (required to test Newsstand and publish to the store).

get rid of the newsstand part in the parentheses, since this is the guide for standalone ;) 

> ### CREATE YOUR PUBLICATIONS
> 1. **Create** your issues using the [HPub tutorial](How to package an HPub).
> 2. **Zip** the publication and rename from _zip_ to [Hpubs](hpub specification) (remember to select all the files and zip them, do not zip the folder)
> 3. **Upload** the Hpubs to your web server. Test and make sure that you can download them from a browser. (e.g. `http://example.com/publication/issue1.hpub`).

**step 2.** is not needed for the standalone app, since folders work inside `books` folder too. might clarify that more :)
**step 3.** is wrong/confusing because in step 9 guide tells you to copy the hpub to the `books` folder before compiling. so uploading the hpub is needless.

cheers

**Comment by folletto** [comment]
You're right, these aren't correct. I guess they were updated wrongly in the last version.
Could you update them yourself? :)

**Comment by folletto** [comment]
Thanks @schlompf! :)
