### ISSUE TITLE
Flashing screen issue

### ISSUE THREAD

**Issue by trudderham** [Simbul/baker#723]
I've finished my first app, and it looks brilliant thanks to the Baker framework, but I'm seeing a flash as every page loads.

It seems to be linked to the background color in my style.css sheet, because if I change it from white to orange the screen flashes orange briefly. I've also tried using an image for my background, and that flashes too.

If I take the background color out, then the flash goes away, but now all of my pages have a grey background (see the lower half of the screenshot attached
![344uwdc](https://f.cloud.github.com/assets/3518136/176810/3c4a747a-7b80-11e2-9a30-a2b95fe3abb3.jpg)
). I've searched through all the code in my book for the hex of the grey but haven't had any luck finding it.

So, I skimmed through the RootViewController, but being relatively new to Xcode I couldn't find anything. I've left it as-is.

Is there anything I can do to remove the flash and replace the grey background? I tried editing the "-baker-background": "#000000", property in the JSON file but that seems to only control what the app displays when I pull the first screen to the right - and it makes the first screen flash white.

Any help would be really appreciated, I've had many sleepless nights trying to fix this, and it's the last persistant bug! Hopefully it's something really simple that I've missed.

Thanks

**Comment by folletto** [comment]
It's unfortunately an Apple Bug, we spent loads of time to try workaround that, but unfortunately it's not something in our control. You can try opening a bug in the Apple bug tracker: https://developer.apple.com/bugreporter/

At this time, you can just minimize the issue, not remove it (unless you're able to have a page so light that doesn't trigger it.

**Comment by trudderham** [comment]
Thanks. I've managed to minimise the flash by stripping out lots of Java features. It's still there, but only for a split second, some pages don't even show it. If I strip out all of the Java code there's no flash at all - so Java is most likely the culprit.
