### ISSUE TITLE
Problem with more than one magazine

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#724]
Hi im working with baker4.0 with the newstand.
Y upload 1 magazine and tried and it works perfect.
But then i upload other magazine and that is my problem, if i delete one of theme, boot are deleted, if i download one, boot are download,
How can i solve it???
thanks

**Comment by aspek** [comment]
I think this problem has been from the same  "name":  in shelf.json

https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON
name ( string ):
A unique identifier for the issue. Note that both Newsstand and Baker rely on this ID, which should be unique and should never change. This property is used internally and it won't be shown to the user.

**Comment by molorago** [comment]
Thanks!!!
now it works
