### ISSUE TITLE
Content loading into index view

### ISSUE THREAD

**Issue by winmhtun** [Simbul/baker#725]
Hi,

When I click one of the indexes from the index view, the content of that page is still loaded into index view. Please guide me on how to solve this. 

I saw that issue was marked as a rare bug before but it is still happening to me.

**Comment by folletto** [comment]
Please, please, please: we need details. There's no way we can help if no detail about it is provided.
1. How is the `index.html`? Could you link it here? Or paste the relevant part of the code with the a tag and the link?
2. What's in the debug log?
3. What do you mean by "one of the indexes"?
4. Are you trying to open an internal or an external page?

...and pretty much every other detail you could add. :)

**Comment by folletto** [comment]
Is there any update?

**Comment by winmhtun** [comment]
Sorry for my late response.

Your framework is nice and clean. 

There was one condition I messed up with. 

this is the part.
<code> if (![self changePage:page] && ![webView isEqual:customViewController.view] )
                    {
                        if (anchorFromURL == nil) {
                            return YES;
                        }
                            [self handleAnchor:YES];
                    } 
</code>

And I was able to solve it.

Thanks for your support !

**Comment by folletto** [comment]
That's great! :)
Thanks for sharing. :)
