### ISSUE TITLE
Cover magazine newstand

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#726]
Hi everyone, in the documentation i found that the cover of the newstand will be replace it every time we upload a ner magazine.... that right???
So i try but always appear the icon, my question is this only work when the app is in the app store???
or how can i try it??
Thanks

**Comment by folletto** [comment]
The cover icon updates when the user downloads a new hpub from the server, not when you upload it. :)

**Comment by molorago** [comment]
But i cant try it locally?

**Comment by folletto** [comment]
If you're using Newsstand, Newsstand can't work locally. :)

**Comment by molorago** [comment]
But i using newstand and i download a magazine and the cover doesnt change, what im doing wrong?

**Comment by folletto** [comment]
I have no idea if you don't provide more informations, I'm sorry. I can just say to check the cover is present in the Hpub and on the server and everything is in place. :)

**Comment by molorago** [comment]
The thumbnails its working when i click the icon in the newstand....
Are placed in the server.... but the icon in the newstand always is the same...

**Comment by folletto** [comment]
There are TWO locations for the thumbnails: _inside_ the Hpub and _on the server_. Check both.

Otherwise please, try adding more details about your setup, error logs, etc. :)

**Comment by molorago** [comment]
maybe it is because i dont place them in the hpub???
i will try that

**Comment by molorago** [comment]
The icon that is visible in the newstand is not the one that is placed in the icon folder???

**Comment by folletto** [comment]
I have again to refer back to Apple's Newsstand documentation. I'm sorry but we can't really support Apple's side of things. You can find all you need to know on their documentation. :)
