### ISSUE TITLE
Sen my app to the app store

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#727]
Hi guys, i know that maybe for u this is a really stupid question
But this is my first app, and i allready setup my app in the itunes connect.
But im confused, i have to create a .IPA, or i send my folder of baker ????
I dont know how to send it to the newstand.
ICan someone send me a tutrorial or a web page so i can sen my app to aproval

**Comment by folletto** [comment]
I'm afraid that the only answer I can give you is: login in the Apple Developer account and look for that. There are instructions, tutorial and even videos that explain it. Even if you just google it you can find that kind of information, like the tutorial in two parts:
http://www.raywenderlich.com/8003/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-1

Please, we can't really support Baker and also the Apple side of it, it will take too much time, as much as we'd love to support everyone to have their app published. Look on Apple's forums for support on that and try to use this space just for Baker related questions and issues. Thanks. :)
