### ISSUE TITLE
modal browser breaks navigation popup

### ISSUE THREAD

**Issue by winklebleck** [Simbul/baker#728]
After closing an external link that opened in the model browser (?referrer=Baker) double tapping does not bring up the navigation. The top bar comes down, but the index does not come up. If you load the link without ?referrer=Baker and swipe away from the webpage, the navigation does not break. 

Ideas?

**Comment by folletto** [comment]
The issue has already been fixed here #578, currently on `master` and will be out in the next release of Baker. :)
