### ISSUE TITLE
Book build succeed but I saw just Baker Icon

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#729]
Hi. I wanted to work with the Hpub example on Baker. The app build with success but I saw just Baker icon.
![Capture d e cran 2013-02-22 a 09 20 26](https://f.cloud.github.com/assets/3580334/185116/57168c18-7cfb-11e2-805c-7d3b2eb8374c.png)

![Capture d e cran 2013-02-22 a 09 20 11](https://f.cloud.github.com/assets/3580334/185114/4b786d40-7cfb-11e2-8d65-ee8b699670eb.png)

I followed the Standalone tutorial and I removed specifics parameters on NewsStand because it told me that I need active web connection.

Can you help me?

thnks

**Comment by folletto** [comment]
You have to add a _folder_ inside `books/` not the files themselves. The `books/` folder can hold multiple publications, so you have to put each individual publication in a single folder. :)

**Comment by aredqueen22** [comment]
ok thnks I'll try it

**Comment by aredqueen22** [comment]
WOW THANKS :D :+1:  You make my day because it takes 2 weeks to understand to work Baker. thanks for everything. I can to begin my project. :)
