### ISSUE TITLE
DoupleTap for displaying navigation bar instead of single tab

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#73]
Hey there,

I implemented a navigation bar at the bottom of the screen (loosely based on svdgraafs code), which fades in, if tapped once on the screen. But because thats interfering with hyperlinks in the main content, I want to trigger my navigation bar with a double tap. 

Does anybody have a tip how to do it?

Thanks a lot and best regards,
florian

**Comment by nadzree** [comment]
Hi ffranke,

in the RootViewController.m inside the function of userDidSingleTap:(UITouch *)touch :
in the else statement include :

....
else { 
  if (touch.tapCount > 2)
  {
    //function here
  }
....

Is this what you are looking for?

**Comment by ffranke** [comment]
Hey nadzree!

Thanks a lot! Works like a charm. I changed the ">" to an "==", so the function is triggered by a double tap (and not triple tap and so on..)

Wishin' you a good day!
Florian

**Comment by nadzree** [comment]
Glad to know : )
