### ISSUE TITLE
Problems with referrer=Baker and internal browser

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#730]
Solved a problem, here we are with another one: but Baker is marvellous so I keep on working on my portfolio app :)
This time some problems with the ?referrer=Baker and internal browser.
I want to keep users inside the app/Baker so I use internal modal browser.
But using the internal browser <code>?referrer=Baker</code> is passed with the url and no trimmed away.
It never minds a lot of times, but if the website the user is going to visit uses URL rewriting or something like that problems arise.
An example: http://www.letterpressisbetter.com?referrer=Baker becomes  http://www.letterpressisbetter.com/?referrer=Baker/
And this gives an 404 error because that page doesn't exist. Letterpress is better is a project of mine so I know for sure that it uses url rewriting.
Is it possibile to have <code>?referrer=Baker</code> cut also for internal browser and not only when you load a link in Safari?

Second problem with internal browser: when you load a webpage that has a video inside (YouTube, for instance) and then you use the Back button to get back to Baker app, the internal browser is not erased but simply put aside (or something like this, I suppose).
If the video is playing and you don't stop it before going back you can hear the audio "in background" while using your app. And there's no way to go back to that internal browser window to stop the video :(
Using the link again opens a different browser window but the old one still keeps on playing...

**Comment by folletto** [comment]
Could you please open two separate issues for the two problems? (Actually, just another one for the second problem). 
They are quite distinct. :)

**Comment by ilpiac** [comment]
Sorry, you're right!
Just created a new issue (#731) for the internal browser Back button not erasing the window.

**Comment by folletto** [comment]
Thanks! :D

**Comment by ilpiac** [comment]
Thanks schlompf, now I'm sure I found the right solution :)
Unable to be online for 3 days with my Macbook but I was working on my portfolio, so I tried to find the line of code to change and found it inside BakerViewController.m
I'm not a dev so I tried some stupid things before, for instance newURL instead of url but then a warning said me that loadModalWebView can't directly use a string!
Then I copied the right piece of code from line 1173: saved the new version of BakerViewController.m and now everything is working fine!
Just a stupid question, I'm curious: why did I find <code>[self loadModalWebView:url];</code> on line 1189 and on your fix I read 1198 as line number?
Anyway, thanks a lot.

**Comment by philippgeuder** [comment]
well, i'm just starting to learn obj-c and git&github is new for me ... so maybe a mistake on my side. but keep in mind that the fix and line numbers are for "master"/lastet code on github. if you use the code bundled as baker 4.0 then line numbers might be different.

**Comment by ilpiac** [comment]
It really makes sense: in fact I'm using Baker 4.0. Thanks again.
I think this issue is solved and it could be closed, but I really don't know how to (and if I can) do it :)

**Comment by folletto** [comment]
Thanks guys! :)

We keep this open until we check it and it's merged and tested in `master`. :)

**Comment by ilpiac** [comment]
Perfect. Another little thing I've just learned about how "developers' things" work ;)

**Comment by Simbul** [comment]
Thanks for the contribution @schlompf! I'm closing this issue as we've now merged your commit into master.
