### ISSUE TITLE
Modal internal browser: back button doesn't erase/delete the window

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#731]
I opened an issue with two separate problems (#730) so I open another one to keep it separated.

I have a problem with the modal internal browser: when I load a webpage that has a video inside (YouTube, for instance) and then you I the Back button to get back to Baker app, the internal browser is not erased but simply put aside (or something like this, I suppose).
If the video is playing and you don't stop it before going back you can hear the audio "in background" while using your app. And there's no way to go back to that internal browser window to stop the video :(
Using the link again opens a different browser window but the old one still keeps on playing...
An unwanted audio in background is a little bit noisy, but I think it's also a performance problem because every modal internal browser you "put aside" with the Back button plays in background.

**Comment by ilpiac** [comment]
Just tested this fix with my portfolio and it works like a charm.
The only positive aspect about the bug was that it was a kind of cache.
When you loaded the same URL again in a second modal view it was already running in the first hidden one, so loading was lightning :)

**Comment by philippgeuder** [comment]
... let's say it seems to work :smiley:  someone with a little more knowledge of how memory management and dealloc and stuff works, should look into this.

until it is in `master`, be careful :smirk:

**Comment by ilpiac** [comment]
You're right. But it works enough to let me keep on working on my app.
And this is what I need now :)

**Comment by Simbul** [comment]
Thanks for the contribution @schlompf! I'm closing this issue as we've now merged your commit into `master`.
