### ISSUE TITLE
Right to left book  

### ISSUE THREAD

**Issue by Danash** [Simbul/baker#733]
Hi guys!
I want to use Baker framework to produce a magazine in Arabic language, is it possible to start from page1 then go to right  (contrary to what it is now) ?
Thanks

**Comment by folletto** [comment]
It's simple.
Just use the variable `-baker-start-at-page: -1`, and it's done. :)

Read here for the full details. :)
https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

**Comment by Danash** [comment]
Works great...You can’t see me but I’m totally doing a happy dance :)..Thank you !

**Comment by folletto** [comment]
Great! You're welcome! :D
