### ISSUE TITLE
Magazine not downloading on iPhone

### ISSUE THREAD

**Issue by benjamincano** [Simbul/baker#734]
I created my magazine and decided to make it universal it worked fine but I couldn't download any issues of the magazine on the iPhone. I thought it was me but also saw that the Jon Low app on the Showcase doesn't let you download any issue either. This works correctly on the iPad though.

**Comment by folletto** [comment]
Thanks, we'll look into it. :)

Could you please add more details about the problem? At least copy-pasting the console log you're getting? :)

**Comment by yujulio** [comment]
Could it be this same issue? https://github.com/Simbul/baker/issues/630

**Comment by benjamincano** [comment]
Thank you Julio, this was exactly the problem... sorry I couldn't find it before posting it. It may be based on the fact that we were both running it on Latin American phones.
