### ISSUE TITLE
UIWebView link popup

### ISSUE THREAD

**Issue by vlondon** [Simbul/baker#735]
When you hold finger on link at Navigation it showing popup with link to page. But i don't wont that my customers to see some different link. How to disable this popups for UIWebView? Thank you.
![IMG_0124](https://f.cloud.github.com/assets/2144180/192921/d703d9fe-7f70-11e2-85c8-5edd71e37508.png)

**Comment by philippgeuder** [comment]
add `-webkit-touch-callout:none;` to elements in your css where the popup should not appear. `* { -webkit-touch-callout:none;}` hides it on all elements. and you might want to disable user selection with `-webkit-user-select: none;`

**Comment by vlondon** [comment]
Thank you! Magic works!
