### ISSUE TITLE
I cannot see my mag in the simulator but I see always Laker example

### ISSUE THREAD

**Issue by rossellap** [Simbul/baker#736]
I followed the standalone tutorial.
In the folder books/ I have another folder with files and assets for a digital magazine. There is no other folder.
When I build the app and open the simulator, I see the laker example magazine. I used it to make my files but I deleted all the lakers one. The magazine is fine if tested in a browser.
Why cannot I see my magazine and I see something I don't have in books/ ?

**Comment by folletto** [comment]
Could you please add more details? Screenshots of the folder and files, debug log, and in general following the instructions here: https://github.com/Simbul/baker/wiki/Problems-and-Debugging :)

**Comment by aredqueen22** [comment]
I have the same problem but with baker :P 
http://www.flickr.com/photos/redqueen22/8531427234/in/photostream
I delete the url in my book,json.

And run ... I have a blank page with these errors...
http://www.flickr.com/photos/redqueen22/8531427214/in/photostream.

Thanks a lot to help me.

**Comment by folletto** [comment]
It's difficult to tell from these screens, I'm sorry.
Could you please follow the link above and the instructions there? Thanks. :)

**Comment by aredqueen22** [comment]
I forgot my bundle id in Xcode. I did a search and I found it. I wrote it but my app didn't open.

**Comment by rossellap** [comment]
I am still at a loss. I cannot even set it. It gives me many errors - I am using your example not my book/  now -  and when I run the simulator it says the internet connection is missing. Where can I find a tutorial or somebody to help me out - also by paying them

**Comment by Simbul** [comment]
@rossellap I think we're already following this up via email, is that correct?

@aredqueen22 I'm sorry but that's not enough information to understand what's going on. Please follow the instructions in https://github.com/Simbul/baker/wiki/Problems-and-Debugging and we may be able to help you.

**Comment by rossellap** [comment]
Yes, we are. Thank you, Simbul. I was able to set it up and I am almost ready to deploy the app to the store.

**Comment by Simbul** [comment]
Great :)
