### ISSUE TITLE
Automatic Content Download config in Settings

### ISSUE THREAD

**Issue by fcontreras** [Simbul/baker#737]
Greetings guys
First of all thanks for the great project.

I have a question for you, Im currently trying to launch a magazine app with baker but before sending it to apple I wanted the app to be able show the background downloading on the settings for enable/disable.

Is there any code you can point at me, so I can ge this done.
Thank u!

**Comment by Simbul** [comment]
I'm sorry, what do you mean by "on the settings for enable/disable"?

**Comment by fcontreras** [comment]
Greetings...

Sorry I was not that clear, if you go to Settings on the iPad and look on the Newsletters there is not option to enable disable background downloading for the user to change.

**Comment by Simbul** [comment]
I think that button will disable Newsstand push notifications rather than background downloads (though they look the same for the user).
We've just merged push notifications into `master`, so you may want to check with the latest version of the code.

**Comment by fcontreras** [comment]
Hmm.. I have seen two options on different locations on Settings

Settings->Notifications (for the notification styles, and others)
and Settings->Newstands (for automatic content download)

I have seen baker ask the user at first use if wants to allow Notifications, which is the global one. If the user press no. Then there is no option for him/her to turn them on later.

**Comment by Xm4s** [comment]
From what I've seen it seems that, unless you have an app ID
• with a bundle identifier that match the one of your app
• configured to handle push notification (with a valid push SSL certificate)
your app won't show in the settings, neither in notification center nor under the newsstand tab
Try to configure your app on the provisioning portal :)

**Comment by fcontreras** [comment]
hmm.. by now I have configured the app into the provisional portal.. still no luck.
I may think is more like something is missing in the code, Im still learning Objetive-C :P so I dont think I can find an answer soon.. but according to what the apple learning center videos says there is a way to set those settings on the code.

**Comment by Xm4s** [comment]
I'm pretty sure that all the code necessary is in the latest master branch, I can see my Baker app in the notification center and under the newsstand tab and the only thing I've done is to set the correct name of the app target and the bundle identifier to match the app ID I've previously set up in the provisioning portal.

It's actually very difficult to tail your problem, since those settings are not created by Baker itself but are generated by iOS if the app is configured properly.

We'll provide a tutorial on how to configure the push notification as soon as possible to help solving problems like this, in the meantime you can help us by keeping us up to date with everything new you discover about your configuration.

**Comment by fcontreras** [comment]
Rechecking .. I think Im missing the SSL configuration as you say.. 
To be honest.. the process of publishing an app is not quite well documented and there are various steps I may be missing.

:-1:  not cool.. will keep checking and keep u posted.. thanks for the interest

**Comment by folletto** [comment]
Unfortunately Apple has one of the worst documentations out there, we are aware of that. On the other side, we can't be the editorial team for them... ;)

**Comment by fcontreras** [comment]
I understand your point, but since we are working with a product that is aimed to their plataform a better guide for publishing will make it one of the tops knowing that the rest of the docs is not good.

It will be cool to get the push notifications tutorial above mentioned, and I will try to also get the rest of the process documented so we can create a for dummies tutorial. Im sure it will help a lot.

**Comment by folletto** [comment]
For sure. It would be better. But the time we spend writing a documentation (something that often is changed by Apple at every release) must be balanced with the time we use to actually write an publish features to Baker. And the time we have isn't that much. :)

On the other side, it's an opensource project, so you can write the tutorial so we can add it to the wiki for everyone else. :)

**Comment by bobbytung** [comment]
Just found an old Newsstand App tutorial, don't if that may help or not:
http://www.viggiosoft.com/blog/blog/2011/10/17/ios-newsstand-tutorial/
I'd like to contribute but I'm an editor and designer.

Push-notification is ok, somebody use charged service as Urban Airship, somebody try Java/PHPish APNS package for that. Several ways togo.

**Comment by Simbul** [comment]
That is an excellent tutorial, we used it quite a bit while implementing Newsstand in Baker :)

**Comment by Simbul** [comment]
@fcontreras have you managed to sort this out in the end?

**Comment by fcontreras** [comment]
Well, we didnt solve it.. I guess as@Xm4s said there wasnt any issue.. we dont have a SSL cert yet. So I think thats the part missing.

:)

**Comment by fcontreras** [comment]
As soon as we implement that part I surely will place some extra comments here so everyone knows :)

**Comment by Simbul** [comment]
Ok, we'll keep this open while we wait for you to comment back then :)

**Comment by Simbul** [comment]
@fcontreras I'm about to close this issue. Any update? ;)

**Comment by fcontreras** [comment]
Hi we are about to setup the SSL.. 
please hold on..

**Comment by fcontreras** [comment]
Greetings guys.. sorry for the late response.
Well .. as said before.. I was missing the SSL config on the server side.. and activate push notifications on the App.. (dumb but yes) I was missing those configs. :tongue: 

So after enabling push notification in the provisional portal, I had to recreate the provisional profiles .. (other way It was giving me an error trying to find the apn key) and it was it.. I re added those to my project and it works like a charm.

Thanks!

**Comment by folletto** [comment]
That's great news, and thanks for taking the time in giving your feedback. I'm sure it will be useful to others as well. :)

I'm closing this issue then. Thanks. :)
