### ISSUE TITLE
Prerendered screenshots not working for first 11 pages

### ISSUE THREAD

**Issue by blowback** [Simbul/baker#738]
I'm using pre-rendered screenshots. When I start the app, it's as if it doesn't see the cached screenshots, ie I see my background image; that is until I get to page 12, this page and pages above 12 render the screenshots fine, but as soon as I go back to 11 I see the background image again.

However, if I rotate by 90 degrees to the other orientation, screenshots work fine for all pages. If I rotate back again, they now work fine in the original orientation too!

I put some debug in checkScreeshotForPage and it's looking for the right image and returning TRUE every time, even in the cases where it isn't displaying it.

You see this behaviour regardless of whether you start in portrait or landscape.

**Comment by Simbul** [comment]
This is weird, sorry you didn't get a reply sooner, @blowback. Have you managed to solve the issue in the meantime, or do you have any more information?

**Comment by blowback** [comment]
Still seeing it, 100% repeatably. I'm about to roll a new issue so I'll let you know if I see the same problem.

**Comment by Simbul** [comment]
@blowback did you get anywhere with this?

**Comment by blowback** [comment]
I've been focused on content generation, but I shall look at it again in the next few days!

**Comment by blowback** [comment]
I can't reproduce this in 4.1, so I think it has gone away!

**Comment by folletto** [comment]
Excellent! Thanks for the feedback! :)
