### ISSUE TITLE
Icons required for every app

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#739]
Just a stupid question: going through this document (http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/mobilehig/IconsImages/IconsImages.html) I've seen that - apart from icons I've already found in Baker/icon folder - also "App icon for the App Store" and "Launch image" are required. And "Small icon for Spotlight search results and Settings" is recommended.
Apple splits info about required graphic assets across multiple docs and this is really uncomfortable especially id it's the first time your try to submit an app :)
This is not a Baker issue, obviously! But I have to change/add something inside Baker-info-plist file, so I need some support...

I can use any name as long as I add it inside the Info.plist (Baker-Info.plist for Baker) and add @2x for Retina versions. 
The question is: if I deploy an iPad only app without Newsstand support, is it right to add the string for Spotlight support like I did in this code (the bold one)?
<sample>
&lt;key&gt;CFBundleIconFiles&lt;/key&gt;
      &lt;array&gt;
        &lt;string&gt;ios-icon-iphone&lt;/string&gt;
        &lt;string&gt;ios-icon-ipad&lt;/string&gt;
        <b>&lt;string&gt;ios-small-ipad&lt;/string&gt;</b>
      &lt;/array&gt;
&lt;/sample&gt;

Where can I add UILaunchImageFile key (plus array and string tags) in Baker-Info.plist for launch images (portrait and landscape) support?
Or is it better not adding any key, just adding <sample>Default-Landscape.png</sample>, <sample>Default-Portrait.png</sample>, <sample>Default-Landscape@2x.png</sample> and <sample>Default-Portrait@2x.png</sample> inside Baker/icon folder?

Thanks!

**Comment by philippgeuder** [comment]
concerning app icons and launch icons: you can add them through xcode. go to the summary tab for your project's target, there you can drag-and-drop the appropriate images.

for the rest: try searching the dev forums from apple or stackoverflow. i bet, someone already asked that ;)

**Comment by ilpiac** [comment]
Thanks Schlomps. Eventually I added ios-small-ipad adding the string inside CFBundleIconFiles key and putting these files in Baker/info folder and added Default-Landscape and Portrait through xcode.

**Comment by Simbul** [comment]
Hi @ilpiac, do you think the issue can be closed then?

**Comment by ilpiac** [comment]
For sure @Simbul, thanks.
