### ISSUE TITLE
I cant add a tab bar

### ISSUE THREAD

**Issue by nadzree** [Simbul/baker#74]
Hi All,

Cant create any tab bar since there is no xib. Is there any way to include this tab bar natively?
Really appreciate any help from you guys as guidance.

**Comment by Xm4s** [comment]
Hi!

Every component you can add in a .xib file it's also manageable programmatically.
If you want a tab bar there's the <a href="http://developer.apple.com/library/ios/#DOCUMENTATION/UIKit/Reference/UITabBar_Class/Reference/Reference.html">UITabBar class</a>

**Comment by nadzree** [comment]
Hi Xm4s,

Oops I forgot to close this. Manage to do it the way you pointed : )

Thanks
