### ISSUE TITLE
App with no-Newsstand: some interesting info

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#741]
I wanted and app with no-newsstand, so:
1) removed <code>NewsstandKit.framework</code>
2) removed line <code>#define BAKER_NEWSSTAND</code> in <code>Constants.h</code>
3) removed <code>UIBackgroundModes</code> and <code>UINewsstandApp</code> entries from my ilpiac-Info.plist (project was renamed)
But while I tried to verify my archive against iTunes Connect, the procedure said that there were two errors:
1) I can use only "non negative" numbers inside <code>CFBundleVersion</code> key;
2) the key UINewsstandApp has to be "true" to use newsstand.

Error n.1: Actually the value in Baker-info.plist is <code>Baker-4.0</code> and so it is in mine .plist file too. I changed the value to <code>4.0</code> and everything is now fine.

Error n.2: Why? Since I deleted the framework, removed the line in Constants.h and removed the two entries in .plist file, I was sure that everything was ok...
I decided to open the .plist file in TextEdit and found that there was a <code>UINewsstandIcon</code> key. I removed it and now everything is fine: my archive validates against iTunes Connect.
It was probably better to open the .plist file in Xcode, I know, but I didn't know what I had to look for :)
Now that I know what to I have to look for, I've opened the .plist file in Xcode: you can find a <code>Newsstand icon</code> entry inside <code>Icon files</code>, delete it to remove all references to Newsstand.
I hope this is useful for other people too.

Now I'm going to upload my app to the Apple Store. It's just my portfolio, so I don't know if they will approve it... Obviously I hope that they do!
I'll let you know, I've obviously mentioned Baker in credits inside the app :)

**Comment by aspek** [comment]
Find this line in your .plist 
![Screen Shot 2556-02-28 at 1 49 13 AM](https://f.cloud.github.com/assets/2587452/202318/8c086060-810e-11e2-8381-e26f7e5bcc50.png)

and set to NO.

**Comment by ilpiac** [comment]
Thanks Aspek!
I've already solved the problem :)
As per this tutorial - https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone - I had removed <code>UINewsstandApp</code> ("Application presents content in Newsstand") but <code>UINewsstandIcon</code> key was there, in my .plist file, anyway.
I realized it while validating against iTunes Connect, the procedure still threw and error.
Now that I've removed also <code>UINewsstandIcon</code> key in .plist (or <code>Newsstand icon</code> entry inside <code>Icon files</code> entry if you open .plist inside Xcode) everything is fine.

**Comment by Simbul** [comment]
Thanks for the report @ilpiac. We definitely missed the icons entry in the plist.
I've updated the tutorial with the new information you provided.

We'll also look into the Bundle Version.

Cheers!
