### ISSUE TITLE
Baker Shelf title

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#742]
Hi ,
i am using stand alone mode and did follow to modify required parameters (like removing newsstand stuff). i searched the issues here but could not find how to remove Baker Shelf title and back to shelf button title . below ones.

thanks

![Screen Shot 2013-02-28 at 16 39 14](https://f.cloud.github.com/assets/1453020/205691/de458960-81b4-11e2-8a4f-940e0998617d.png)
![Screen Shot 2013-02-28 at 16 40 17](https://f.cloud.github.com/assets/1453020/205692/de481f72-81b4-11e2-9405-4a2ecadbe935.png)

**Comment by folletto** [comment]
You can't remove it, standalone is still a shelf, just managing the issues in... a standalone mode. :)

You can change the title in `Baker/en.lproj/Localizable.strings`

**Comment by bahmet** [comment]
Thanks @folletto
