### ISSUE TITLE
Link to a page from ios

### ISSUE THREAD

**Issue by andersonchagas** [Simbul/baker#744]
I`ve created a new viewController with some buttons I wanna link to some specific pages of the book (like a menu), and load it above the bakerView.

How can I make an action to "goToPage"?

thanks.

**Comment by Simbul** [comment]
Try having a look at the code for the `webView shouldStartLoadWithRequest` method inside `BakerViewController.m`, especially when `[self changePage:page]` is called.

**Comment by andersonchagas** [comment]
Yes.. changePage:page is what I was searching..

I put a view with menu above the scrollview and used notification center to call changePage:page..

Exist a better way to do that?

Thanks?

**Comment by Simbul** [comment]
That sounds like the right approach. I'm not sure you can call `changePage` straight from the notification center, though. Has that worked?

**Comment by andersonchagas** [comment]
I called a function that treat what button was pressed and call the changePage.

In viewDidLoad{

   [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(rollPage:) name:@"button1" object:nil];

}

``` objc
- (void)rollPage:(NSNotification *) notification{   
    if([[notification name] isEqualToString:@"button1"]){   
        [self changePage:5];      
    }  
}
```

this works, but I know I can improve.

**Comment by Simbul** [comment]
I did not dive into the code, but it looks like a reasonable solution.

I'm going to close this issue, feel free to reopen if you need more support on this specific topic ;)
