### ISSUE TITLE
Apple store refused

### ISSUE THREAD

**Issue by wflaugh** [Simbul/baker#745]
2.2

We found that your app exhibited one or more bugs, when reviewed on iPad running iOS 6.1.2, on both Wi-Fi and cellular networks, which is not in compliance with the App Store Review Guidelines.

We found your app has newsstand content background mode enabled. However, no relevant feature found in your binary.

2.21 

We found that your app is primarily a book and is therefore not appropriate for the App Store, as noted in the App Store Review Guidelines. 

Books should be submitted to the iBookstore when it becomes available in your country. To work with Apple on iBookstore distribution, first verify that your content meets the following requirements: - ISBNs for all titles you intend to distribute - Is in EPUB format, passing EpubCheck 1.0.5 To obtain an ISBN for your content and learn more about ISBNs, please see US ISBN Agency. Then complete the iTunes Connect Online Application. Visit iBookstore Aggregators for information on working with the iBookstore aggregators.For discrete code-level questions, you may wish to consult with Apple Developer Technical Support. Please be sure to:
- include the complete details of your rejection issues
- prepare any symbolicated crash logs, screenshots, and steps to reproduce the issues for when the DTS engineer follows up. 

For information on how to symbolicate and read a crash log, please see Tech Note TN2151 Understanding and Analyzing iPhone OS Application Crash Reports.

If you have difficulty reproducing this issue, please try testing the workflow as described in https://developer.apple.com/library/ios/qa/qa1764/Testing Workflow with Xcode's Archive feature".

How to solve this problem?

**Comment by Simbul** [comment]
Are you building a Standalone app or a Newsstand app?
Assuming it's the former, have you followed the instructions in https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone?

**Comment by wflaugh** [comment]
I have submitted the  Newsstand app to the Apple store.(My program  is no problem when I debug it. HPub is also normal when it is  downloaded from the server)
How to solve it.Thanks!

**Comment by folletto** [comment]
Reading the second issue, 2.21, it looks like you didn't submit a magazine but a static book. Unfortunately there isn't much we can suggest, apart from what Apple is already telling you to do: either comply that, or change your content in such a way that you are able to not fall in these issues (i.e. people added interactive features to their books in order to avoid the 2.21 rule).

I would still try to ask clarification for 2.2, because well, that's not clear to me, even less without knowing what you developed. There are already a few submission to the store with Baker in Newsstand mode.

**Comment by Simbul** [comment]
@wflaugh any news on this?

**Comment by thejtate** [comment]
I had issues with trying to publish a digital pub for a university we were producing. The easy fix I did was add a few embedded videos and minor animations using Zepto javascript (http://zeptojs.com/) into the publication. 

Took only four days for Apple to approve of it finally.

**Comment by folletto** [comment]
Excellent news! Thanks. :)
