### ISSUE TITLE
Loading times

### ISSUE THREAD

**Issue by benjamincano** [Simbul/baker#746]
I am becoming a little obsessive with loading times, I saw the Portfolio by [Jon Low](https://itunes.apple.com/app/jon-low-studios/id568827957) and you never get to see the loading screens but also the pages load crazy fast.

I was wondering if anyone has done anything similar? I wish he could share his source code :)

**Comment by aspek** [comment]
"Jon Low" use `-baker-page-screenshots` see on wiki. And this mag just have one image per page.
If you observed "baker" will still show screenshot image before the content loaded. But some time you can see flashing screen like this #723

**Comment by benjamincano** [comment]
Thanks a lot, I was able to see the difference on the implementation using the iPhone version.
