### ISSUE TITLE
"No Internet Connection" error when testing

### ISSUE THREAD

**Issue by blacksheeptattoo** [Simbul/baker#747]
Hi,
Firstly I want to make it clear that I am a total noob. I am trying to set up a free magazine for a small local business and am finding Apple and xcode a tad tricky.

I have followed the tutorial for the newsstand app and found it very easy and helpful. The problem is when it comes the the Apple side of things, namely this part:

"CONFIGURE NEWSSTAND ON ITUNES CONNECT

To meet the App Store requirements for a Newsstand app, you must provide a free subscription. You can create one on iTunes Connect. Follow Apple instructions to do that, we can't unfortunately provide support for the Apple side of things.

You need to have your application already created in iTunes Connect (don't worry, it's not submitting anything yet).
From the iTunes Connect page for your application, select Manage In App Purchases.
Click the Create New button.
Select Free Subscription.
Fill in all the required form fields. Baker will need a reference to the Product ID, which will be something similar to com.example.Baker.subscriptions.free."

I know you say you cannot provide apple support (of course), but I have been trying to create a itunes connect account and it only seems possible for ibooks or music/movie apps, not magazine apps. I would be hugely grateful if someone could point me in the right direction. 

As I said, eveything else is coming along nicely thanks to your brilliant work, but I am unable to test my product (No Internet Connection error, which I am presuming is due to the lact of iTunes Connect account...)

Thanks!

**Comment by folletto** [comment]
1. From what you're saying, it seems that you don't have a Developer Account, it's a prerequisite. Once you have that, the iTunes Connect login is enabled and you can create apps... any kind of app.
2. However, the shelf should be visible when `shelf.json` is ready, regardless of iTunes Connect. You are likely to have a problem there. Check the Problems and Debugging page on the wiki first.

**Comment by blacksheeptattoo** [comment]
Thank you so much! I had another trawl through everything related to the
shelf.json and realised I had done something really dumb. Problem solved -
thanks!

**Comment by folletto** [comment]
Excellent! :D
