### ISSUE TITLE
Change index.html orientation from horizontal to vertical on double tap

### ISSUE THREAD

**Issue by rtshittu** [Simbul/baker#749]
Hi Guys,

I am wondering how i can change the way the index.html file appear at the bottom.  i would like to make it vertical upon a double tap.  how do i get this done.

**Comment by folletto** [comment]
By reading the wiki above. :)
https://github.com/Simbul/baker/wiki/Adding-an-Index-Bar-to-your-publication

**Comment by rtshittu** [comment]
thanks
