### ISSUE TITLE
Just wanted to share my version of baker (iphone-support, navigationbar)

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#75]
Hey everyone,

just wanted to share my version of the baker framework. This version includes (based upon code of svdgraaf and others):
- iphone support
- Navigation Bar (The file navigation.htm is loaded with a double tap on the bottom of the screen. When clicked on a link baker jumps to that page and automatically hides the navigation bar. The navigation.htm can be placed in the /book folder, because Baker reads just .html files as "main pages" and not .htm files.

http://dl.dropbox.com/u/2858901/baker-withnavigationbar.zip

I'm not a code-guy, so its maybe a little "rough", but it works!

Hope this helps some people.

best regards,
florian

**Comment by jameskatt** [comment]
This link is dead.

**Comment by ffranke** [comment]
I share the new version this evening. 

Best regards,
florian

**Comment by ffranke** [comment]
Here's the correct link:

http://dl.dropbox.com/u/2858901/baker_with_navigation_bar_title_tag.zip

I added also a function which reads the <title> Tag of the HTML and displays it on the loading screen.

Have fun and show what you do with it ;)

**Comment by jameskatt** [comment]
Thank you very much.. Is this part of the Autorotate branch?  If it does allow rotation, that would be so cool.

**Comment by jameskatt** [comment]
I would love these additional features to fold into the main branch

**Comment by ffranke** [comment]
Sure it does. 

I'm about to do a website with a set of files and explanations for building digital websites. Hope to have it ready by the end of the week. I'll post it here.

**Comment by ffranke** [comment]
Note: if the navigation bar is visible and you rotate the device, the bar closes, so that could be improved.

**Comment by k8fisher** [comment]
Hey just wondered if the files above can be loaded elsewhere as the second link is also dead.

Many thanks

K

**Comment by k8fisher** [comment]
Heck ignore me it was just the link was broken above. thanks FFranke!

**Comment by ffranke** [comment]
;) cool.

**Comment by ffranke** [comment]
;) cool.

**Comment by k8fisher** [comment]
How did you thesis (with rotationy goodness go btw?) I recall reading about that on another of your threads.

k

**Comment by ffranke** [comment]
I think I can finalize my scripts and the documentation website this week. I'll post the link here ;)

**Comment by ffranke** [comment]
I think I can finalize my scripts and the documentation website this week. I'll post the link here ;)

**Comment by ffranke** [comment]
argh, always pushin' the wrong button (comment & close)

**Comment by k8fisher** [comment]
Cool :) thanks ffranke

K :)

**Comment by folletto** [comment]
I'll say that this is closed, the issue #83 updates this one. ;)
