### ISSUE TITLE
Newsstand application rejected

### ISSUE THREAD

**Issue by bryanrpi** [Simbul/baker#751]
Just received rejection notice on my newsstand application from the iTunes team which said in part:
"Specifically, your application loads to an empty storefront. Please refer to the attached screen shot for more information" (Default-568h@2x.png - the Baker icon)

Note: Newsstand is activated in iTunes.

I understood that the application would get its files from shelf.json which is loaded on my server as: http://dancinginthemirror.com/ebooks/shelf.json as are my hpub files.

What am i missing?

**Comment by folletto** [comment]
Did you test it first? Does it work? From the link you gave us, it doesn't look like that... I'm sorry to be so blunt. :/

Plus, that file you linked isn't a JSON file. It's full with error. You have to test first locally on your Mac and your device, and only when everything works, then submit.

You can find all the instructions in the Wiki linked above. To fix the `shelf.json` read the Newsstand shelf JSON and validate it with the information in Problems and Debugging page.
