### ISSUE TITLE
Not an issue, on the contrary... thanks everybody for help and support :)

### ISSUE THREAD

**Issue by ilpiac** [Simbul/baker#754]
My portfolio is finally on App Store: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=609748728

No Baker no party, so thanks a lot for Baker framework and for everybody who answered my stupid questions :)

Just a small tweak on Baker, I disabled the Tap Down area commenting one/two lines because of the structure of my portfolio, I have a menu button with fixed position at the bottom of the page and I didn't want the page scrolling down every time the reader  push the button. To scroll they can swipe, even if my portfolio pages I really short and you have to scroll just two/three times.

Now I must remember to also tweak version 4.1 of Baker - when available - if I will use it to upgrade my app :)

Thanks, again.

**Comment by aspek** [comment]
That great. What is framework(scroll snap)  did you use in app?

**Comment by ilpiac** [comment]
Sorry aspek, probably I haven't completely understood your question, but I try to answer anyway, let me know if the answer is ok or I missed the point :)
I used Baker with just a little tweak: I commented the lines that made the page scrolling when you tapped on the bottom of the page (last 50 pixel or something like this). The tap bottom area is still active: I'm not a coder so no way for me to easily disable it and, anyway, I wanted a somewhat "back-compatibility" with the official Baker.
But when you tap on the bottom area in my app nothing happens, because the code is commented. Really simple.
This is why I use a footer with a fixed position (with CSS): inside the footer there is a small button that you use to open the TOC menu.  If I hadn't disabled the bottom area the page would have scrolled down every time you touched that button. Disabling the bottom area you can sroll down the page swiping it, but when you tap on the menu button nothing strange happens.
I didn't use the index.html file and double tap for the TOC menu: every time I used it there was some problem. Sometimes everything was fine, sometimes not. Sometimes I opened the app and the index was ok, sometimes it was too small or not visible. Probably it's me and my code :)
But I decided to put the menu directly inside every page, using CSS + Javascript to moving it in and out: it works fine and it adds some animation.
There are two other changes too, but they are simply two bugs I found and other people solved.
These two bugs will be solved in the next official version of Baker, but I needed the new code immediately so I changed it by myself, using the code committed to the master.

That's all. If this is not what you asked for of if you need other info, please let me know.

**Comment by aredqueen22** [comment]
Congrulations :)

**Comment by aspek** [comment]
Sorry for my question is shortness.
I mean. What did you use images slide with snap to the page on landscape mode?
And so Thanks!! for shared your idea.

**Comment by ilpiac** [comment]
Don't worry :)
I used Swipe 1.0: https://github.com/bradbirdsall/Swipe
The footer - in landscape mode - is useful not only for fig caption (on/off using the balloon button) but also because all the screen is used for swiping images, so you need a "free area" to go back an forth through projects.
