### ISSUE TITLE
Determining Retina and downloading related hpub file

### ISSUE THREAD

**Issue by ulasbilgen** [Simbul/baker#755]
Hello,

I'm very new to Baker, and maybe what I'm trying to achieve is already implemented. If that so sorry for taking time :)

I'm preparing a newsstand magazine and I'd like to have 2 hpub files. I for Retina devices and the other is for non-Retina, like magazine.hpub and magazine2x.hpub. 

I did a quick check in baker source and though that if I replace self.url assignment in BakerIssue.m file to;

```
    if ([UIScreen instancesRespondToSelector:@selector(scale)]) {
        CGFloat scale = [[UIScreen mainScreen] scale];
        if (scale > 1.0) {
           self.url = [NSURL URLWithString:[issueData objectForKey:@"urlret"]];
        } else {
           self.url = [NSURL URLWithString:[issueData objectForKey:@"url"]];
        }
    }
```

we can download hpub files depending on resolution. This also requires a change in shelf.json file, I'm planning to add one more line under url in the shelf.json, like this;

"url": "http://example.com/magazine.hpub"
"urlret": "http://example.com/magazine2x.hpub"

Now my question is, will this be enough to download different files in different devices?

Cheers,

Ulas

**Comment by folletto** [comment]
My advice is to avoid doing that. If you google around there are _loads_ of instructions on the web on how websites deal with Retina and how to present the right resolution. I would build a single Hpub that does that.

For the question you are asking... I think the only way you have is trying. People usually do as I just said, and well since you're doing a custom solution, the way to go ahead is to test it properly yourself. :)

**Comment by ulasbilgen** [comment]
Thanks for the advice, but I'd like to keep the hpub size smaller, cause I have quite a lot of images. That's why I want to separate the Retina and normal editions.

I'll try the solution that I wrote and share my experience :) Maybe it could be implemented later on in Baker also ;)

Cheers,

Ulas

**Comment by Simbul** [comment]
A slightly more clunky solution would be to publish 2 HPUBs for each issue in the shelf and let the users pick the right one (similar to what happens with apps on the App Store, where you usually have app "xyz" for iPhone and "xyz HD" for iPad).

**Comment by Simbul** [comment]
Hi @ulasbilgen, do you have any update on this? ;)

**Comment by ulasbilgen** [comment]
Hi @Simbul, I edited the code and did some test. Works perfect :) Although didn't submit anything to Apple yet, don't know if there will be a problem in the submission.

**Comment by folletto** [comment]
Ok we are closing this issue then. Come back anytime if you have a follow-up. :)
