### ISSUE TITLE
animations in baker framework

### ISSUE THREAD

**Issue by ask91** [Simbul/baker#757]
what's best solution to play animated object in baker framework besides using javascript, flash, and gif ? and if it's html5, how far the html5 could work out the animations like gif flash and javascript?

**Comment by fcontreras** [comment]
For my curren experience.. it does not depend on Baker but on the device, if you write complex animation might consume too much memory and will not look correctly.

If you are trying to use basic animations I would recommend use CSS ones.. otherwise you may need to be careful on the target device.

**Comment by stemmo** [comment]
fcontreras is right, CSS animations and transitions work best. Javascript is fine if the animation is not too complex or bulky. As for GIFs or Flash bundled inside Edge, forget it.

I'm having good results with HTML5 animations created in Hype then loaded into Baker. But even that struggles if the animation is too large and ambitious.

**Comment by ask91** [comment]
thank you :D of course the CSS3 animations and transitions in html5 are awesome for animating object,.
i agree that the other 3rd parties're would still needed to build animation in html if we want to present a complex ones.

i've seen how the result of Adobe-Edge being used in html and it doesn't have content to show besides a div to wrap the object, because the result is generated inside Edge's code itself, so it'll be hard to modified animation outside the Adobe-Edge & their tools,.

**Comment by folletto** [comment]
This discussion seems ended, so I'm closing the issue. Reopen if needed. ;)
