### ISSUE TITLE
toc-index to the background

### ISSUE THREAD

**Issue by armenjo** [Simbul/baker#758]
I have the following question: is it possible to bring the toc-index-menu to the background if a image-lightbox in fullscreen is displayed? I have tried it in the css with “z-index“, but without success. Can someone please help?

**Comment by philippgeuder** [comment]
currently this is not possible. the toc-menu is a seperate webview/html document, so z-index doesn't work ;) and i'd say it is discouraged to hide the toc menu from the user. toc is sort of a global nav, thus should always be accessible to your user/reader ;)

though, if you absolutely need it, you have to add functionality directly into baker to change toc display behavior, but there is no easy solution to communicate from js/html to obj-c. most if not all involve making a request to a special, custom "url" and capturing those requests in obj-c.

**Comment by armenjo** [comment]
thanks for your answer. where can i add it directly in baker? and what i have to do in obj-c?

**Comment by philippgeuder** [comment]
with "directly into baker" i meant you have to change the source-code (obj-c) of baker framework. the functionality you are looking for is tracked under issue #350 but even the developers behind baker said they don't know how to properly implement this. so you have to figure it out yourself.

if you know your way around javascript, you could add the toc content to every page and invoke that on double tap or not. ilpiac described replacing the normal toc with one inside each page in #754.

but anyways, i highly discourage you to do it ... from a usability stand-point i'd say it's bad to change behavior like you want to.

**Comment by folletto** [comment]
Hello, this discussion seems ended, so I'm closing the issue. Reopen if needed. ;)
