### ISSUE TITLE
Book viewer

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#76]
Hi, folks!
Congratulations for that amazing Baker Framework! I', currently studying the tool to create an iPad version of my Amazon Kindle short stories book! 

So, I got a doubt about Baker: is it possible to use Baker to create something like a "book viewer", with book cover thumbs, like these one we see a lot when it comes to iPad magazines?

Thanks!
Alex

**Comment by folletto** [comment]
You can use Baker as the reader part of an app that does exactly that, but at this time it's not available "out of the box". :)

**Comment by ghost** [comment]
I think I got it... So, that's the "downloadable book", isn't it?

**Comment by folletto** [comment]
Well, the download works from one book to another, but it doesn't store the book itself. :)

**Comment by ghost** [comment]
Yeah, that's what I thought! Thanks!
