### ISSUE TITLE
Moving through pages

### ISSUE THREAD

**Issue by yujulio** [Simbul/baker#760]
Is posible to make Baker do something like this?

http://www.youtube.com/watch?v=GXodwlAPZiQ

**Comment by stemmo** [comment]
If you're referring to the animated car driving across the pages, then not really. The different webviews in Baker would make that just about impossible.

However you could certainly create an animation that simulates the effect. Just use image grabs of your Baker pages as the animated background, and Tumult Hype or a similar keyframe animator to put it all together.
