### ISSUE TITLE
App store has rejected my app for second time [guideline 2.21]

### ISSUE THREAD

**Issue by naveed8575** [Simbul/baker#765]

**Comment by folletto** [comment]
Ehm... could you add something? :)

**Comment by ghost** [comment]
My app got rejected this morning as well.

Here you go the statement from Apple:

We found that your app is primarily a book and is therefore not appropriate for the App Store, as noted in the App Store Review Guidelines. 

Books should be submitted to the iBookstore when it becomes available in your country. To work with Apple on iBookstore distribution, first verify that your content meets the following requirements: - ISBNs for all titles you intend to distribute - Is in EPUB format, passing EpubCheck 1.0.5 To obtain an ISBN for your content and learn more about ISBNs, please see US ISBN Agency. Then complete the iTunes Connect Online Application. Visit iBookstore Aggregators for information on working with the iBookstore aggregators.

# 

Actually my app is more than a book, it has 20 pages cartoon, plus a cartoon related game in HTML5, can anyone help?

**Comment by stemmo** [comment]
Wouldn't a "20 page cartoon" (comic?) still be a considered a book? You really need some interactive content for it to pass as an app.

My apps are 90% books but have quizzes and crosswords towards the end. A couple of times I've had to post on the resolution centre forum, reminding reviewers that the app in question actually does have non-book interactive features. I suspect some reviewers just get halfway through, decide it's a book and reject it.

**Comment by ghost** [comment]
Hi stemmo,

As I mentioned, I do have a HTML5 game at the end, and it is relevant to the book's character, I also stated this in my reply to the Apple store review.

http://socialreading.cxware.net/books/apps/drawing/draw.htm

**Comment by stemmo** [comment]
Fair enough. But that in itself mightn't be enough if the rest of your book is just images and text. They've tightened up on this in the last couple of years and now expect developers to produce more than static webview pages. Even stuff like lightboxing and inline video/audio don't seem to impress them. Apple wants the App Store to contain interactive native-feel apps; everything else is pushed to iBookstore.

Is there any way you could add a couple more interactive tasks, like quizzes or tap and drag activities?

**Comment by ghost** [comment]
Thanks heaps stemmo for your advice, it is much appreciated.

I think you are right, and I'm trying to put more interactive elements into the book. I hope I don't have to change the Baker framework itself, but just add another HTML5 game, and a video. I'm still not quite sure if it is enough.

Are your quizze and other interactive elements HTML5 or built on top of Baker framework?

Thanks and regards,

**Comment by stemmo** [comment]
No, just Javascript and Tumult Hype animations embedded into Baker pages. You shouldn't have to change the framework. If you need Javascript libraries for quizzes, etc. then there are a few on Code Canyon and various other places. Good luck with it all.

**Comment by ghost** [comment]
Hi stemmo, thank you again for your helpful guide, I will give it a go. Looks like we are both in Australia, I'm in Sydney, how about you? Look forward to talking to you about ebook via email, my email is johnny.jiang(at)yahoo.com.au

**Comment by folletto** [comment]
We are closing this issue as I don't think much more could be done from what has been suggested, and it's really something in the hands of Apple.
