### ISSUE TITLE
Change Page even when vertical scrolling is in progress?

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#77]
Hey there,

I nearly finished my digital magazine. A little testing with some endusers revealed, that they wanted to change a page by swiping horizontally WHILE the current page was scrolling vertical. It seems that thats not possible. The vertical scrolling has to stop completely before a horizontal swipe can be recognized.

Is there a way to enable a page change by horizontal swiping, even when the page is scrolling vertically?

Thanks a lot!
Florian

**Comment by folletto** [comment]
I think it's going to be quite a trouble: that's all manager by native iOS controls, UIScrollView and UIWebView and it doesn't seem if you can override these behaviours.

That said, we even never tried... so there might be a way. We'll look into it... and if you can please try checking it out yourself. ;)

Thanks!

**Comment by ffranke** [comment]
Thanks for the quick reply! I'll see what I can do and ask around a little bit! ;)

**Comment by folletto** [comment]
I'll close this since it seems unsolvable right now, we'll see in the future if Apple will update the components what happens. :)

**Comment by ghost** [comment]
Hi,
we also need a solution of this issue. Have you found anything suitable in Apple API since the last comment?

**Comment by folletto** [comment]
As was, still is. I'm sorry.
