### ISSUE TITLE
Error in main.m when runs Baker

### ISSUE THREAD

**Issue by ask91** [Simbul/baker#771]
Hi,

I'm still learning how to develop using baker. I have an error in the main.m file when I try to read the book after downloaded it from the shelf. I use the Baker-master from github and didn't change a thing, except for the Constant.h in the Baker Shelf to point the shelf.json file to my web server (checked the shelf.json, and it is valid). So far I develop the book using Baker 3 and it is running smooth.

![Baker Run Error](https://f.cloud.github.com/assets/3522957/274037/f57fcb90-9046-11e2-8b46-20e5f083283c.png)

I tried the what dhart23746 said in the <a href="https://github.com/Simbul/baker/issues/226">#226 issue</a> but, my xcode keep crashing when I delete my old Baker projects.

I'm using iMac with Mountain Lion, and xcode 4.5.1 (installed using a .dmg file, not using app store)

Does anybody know what happened?

Thx.

**Comment by Simbul** [comment]
Looks like your HPUB file is not quite right. Make sure you are zipping _files_, not the enclosing _folder_. Also, you may want to validate your `book.json`.
You can find more info on the wiki page on [How to package an HPub](https://github.com/Simbul/baker/wiki/How-to-package-an-HPub).

**Comment by ask91** [comment]
Geez! All this long I zipped the folder, now I know.

Thx!
