### ISSUE TITLE
Always hide the iPad status-bar and book title

### ISSUE THREAD

**Issue by aldidas** [Simbul/baker#772]
I'm currently working on my first digital publication using Baker 4.0 in standalone mode. Is there any setting that can make the iPad status-bar and book title always hidden, even when user double-tap the page? Thanks in advance...

**Comment by folletto** [comment]
It's not possible, it's a custom development you have to do yourself. :)

**Comment by aldidas** [comment]
Just to confirm : So I have to check and modify the 'Obj-C side' of Baker right?

**Comment by folletto** [comment]
Yep, exactly. :)

**Comment by aldidas** [comment]
OK thanks :)
