### ISSUE TITLE
Invalid product identifiers

### ISSUE THREAD

**Issue by zakkiman** [Simbul/baker#776]
Hi,
I have created newsstand using baker, the list of the books in the shelf came out alright. but i try to click subscibe, an error says "Invalid product identifiers". I have created free subscription in itunes connect with product id com.mynews.subscription.free and put it in file Contant.h on section 
# define PRODUCT_ID_FREE_SUBSCRIPTION @"com.mynews.subscription.free"

can you tell me what can be wrong ?

**Comment by Simbul** [comment]
Have you followed the instructions in the [Newsstand tutorial](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand)?

It sounds like the Bundle ID for your application may not be the correct one.

**Comment by zakkiman** [comment]
Hi,

I have followed the instruction, and working fine for subscription. It
seems that the bundle ID in xcode is different from itunes.
But apparently I cannot download the issue. I have followed on how-to from
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand section
CREATE YOUR PUBLICATIONS.
I have set book.json in hpub file with this :

{

  "hpub"_:_ 1_,_

  "title"_:_ "Rossier Outlook"_,_

  "author"_:_ _[_"The Jakarta Globe"_]__,_

  "creator"_:_ _[_"Jakarta Globe"_]__,_

  "publisher"_:_ "BeritaSatu Media Holdings"_,_

  "date"_:_ "2013-03-15"_,_

  "url"_:_ "http://api.beritasatumedia.com/hpub/15.hpub"*,*

  "cover"_:_ "images/page0001_i1.jpg"_,_

  "orientation"_:_ "both"_,_

  "zoomable"_:_ false_,_

  "-baker-background"_:_ "#000000"_,_

  "-baker-vertical-bounce"_:_ true_,_

  "-baker-index-bounce"_:_ true_,_

  "-baker-index-height"_:_ 150_,_

  "-baker-media-autoplay"_:_ true_,_

  "-treesaver-loopArticles"_:_ "true"_,_

  "contents"_:_ _[_

```
"index.html",

"page01.html",

"page02.html",

"page03.html",

"page04.html",

"page05.html",

"page06.html",

"page07.html",

"page08.html",

"page09.html",

"page10.html",

"page11.html",

"page12.html",

"page13.html",

"page14.html",

"page15.html",

"page16.html",

"page17.html",

"page18.html",

"page19.html",

"page20.html",

"page21.html",

"page22.html",

"page23.html",

"page24.html",

"page25.html",

"page26.html",

"page27.html",

"page28.html",

"page29.html",

"page30.html",

"page31.html",

"page32.html",

"page33.html",

"page34.html",

"page35.html",

"page36.html",

"page37.html",

"page38.html",

"page39.html",

"page40.html",
```

  _]_

}

Can you tell me where did I go wrong ?

thx

On Tue, Mar 26, 2013 at 5:00 AM, Alessandro Morandi <
notifications@github.com> wrote:

> Have you followed the instructions in the Newsstand tutorialhttps://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand
> ?
> 
> It sounds like the Bundle ID for your application may not be the correct
> one.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/776#issuecomment-15428426
> .

## 

Best Regards,
Ahmad Zakki

**Comment by Simbul** [comment]
If you cannot download, the issue is more likely to be in the `shelf.json`, not in the `book.json`.
What kind of error are you getting exactly?

As an aside, the line `"page40.html",` in the JSON you posted should _not_ have a comma at the end. Use http://jsonlint.com/ to validate.

**Comment by zakkiman** [comment]
In simulator i can see the list of newspaper the include in shelf.json.
below is my shelf.json file content :

[
  {
    "name": "thejakartaglobe-24-mar-2013",
    "title": "Jakarta Globe 24 Mar 2013",
    "info": "Prison Ambush",
    "date": "2013-3-24 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130324.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130324mobile.hpub"
  },
  {
    "name": "thejakartaglobe-25-mar-2013",
    "title": "Jakarta Globe 25 Mar 2013",
    "info": "Subsidy Suicide",
    "date": "2013-3-25 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130325.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130325/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-23-mar-2013",
    "title": "Jakarta Globe 23 Mar 2013",
    "info": "New Priok Port",
    "date": "2013-3-23 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130323.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130323/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-22-mar-2013",
    "title": "Jakarta Globe 22 Mar 2013",
    "info": "Where There's Smoke",
    "date": "2013-3-22 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130322.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130322/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-21-mar-2013",
    "title": "Jakarta Globe 21 Mar 2013",
    "info": "Build Trust, SBY Says",
    "date": "2013-3-21 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130321.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130321/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-20-mar-2013",
    "title": "Jakarta Globe 20 Mar 2013",
    "info": "Opportunity Amid Challenges",
    "date": "2013-3-20 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130320.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130320/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-19-mar-2013",
    "title": "Jakarta Globe 19 Mar 2013",
    "info": "King of the Skies",
    "date": "2013-3-19 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130319.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130319/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-18-mar-2013",
    "title": "Jakarta Globe 18 Mar 2013",
    "info": "Stolen Innocence",
    "date": "2013-3-18 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130318.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130318/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-17-mar-2013",
    "title": "Jakarta Globe 17 Mar 2013",
    "info": "Room to Grow",
    "date": "2013-3-17 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130317.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130317/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-16-mar-2013",
    "title": "Jakarta Globe 16 Mar 2013",
    "info": "Time to Bite The Bullet",
    "date": "2013-3-16 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130316.jpg",
    "url": "http://www.thejakartaglobe.com/media/epaper/jg/20130316/mobile.hpub"
  },
  {
    "name": "thejakartaglobe-15-mar-2013",
    "title": "Jakarta Globe 15 Mar 2013",
    "info": "Rossier Outlook",
    "date": "2013-3-15 00:00:01",
    "cover": "http://www.thejakartaglobe.com/pages/downloads/cover-pdf/images/thumb20130315.jpg",
    "url": "http://api.beritasatumedia.com/hpub/15.hpub"
  }
]

as you can see from http://api.beritasatumedia.com/shelf.json

I tried to download on the last one ("name": "thejakartaglobe-15-mar-2013")

There's no error on simulator, on debug output panel only shows :

_2013-03-26 14:32:27.008 BeritaSatu Newsstand[903:c07] Refreshing
thejakartaglobe-15-mar-2013 view with status connecting_

that's it, no more progress after that. If I scroll down/up, the download
button re-appear.

On Tue, Mar 26, 2013 at 3:19 PM, Alessandro Morandi <
notifications@github.com> wrote:

> If you cannot download, the issue is more likely to be in the shelf.json,
> not in the book.json.
> What kind of error are you getting exactly?
> 
> As an aside, the line "page40.html", in the JSON you posted should _not_have a comma at the end. Use
> http://jsonlint.com/ to validate.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/776#issuecomment-15446153
> .

## 

Best Regards,
Ahmad Zakki

**Comment by folletto** [comment]
I tried downloading http://api.beritasatumedia.com/hpub/15.hpub, and it's incredibly slow. I tried to add that `shelf.json` in Baker (from a clean setup) and the download actually starts and progresses, but as said, incredibly slowly.

Once downloaded however the issue have problems, that are likely due to what @Simbul told you above.

If you still have problems, please describe step by step what happens – really really step by step? As detailed as possible, with screenshots if you can.

**Comment by zakkiman** [comment]
Hi,

Apparently after I set Application presents content in Newsstand to NO on
iOS target properties the application cannot download the hpub file.
After I reset Application presents content in Newsstand to YES, now it can
download the file.
If I have the issue that user need to buy (not subscription), can I use
baker framework ? Can you show me the tutorial todo this ?

thx

On Wed, Mar 27, 2013 at 6:43 AM, Davide Casali notifications@github.comwrote:

> I tried downloading http://api.beritasatumedia.com/hpub/15.hpub, and it's
> incredibly slow. I tried to add that shelf.json in Baker (from a clean
> setup) and the download actually starts and progresses, but as said,
> incredibly slowly.
> 
> Once downloaded however the issue have problems, that are likely due to
> what @Simbul https://github.com/Simbul told you above.
> 
> If you still have problems, please describe step by step what happens –
> really really step by step? As detailed as possible, with screenshots if
> you can.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/776#issuecomment-15496058
> .

## 

Best Regards,
Ahmad Zakki

**Comment by folletto** [comment]
The Standalone mode doesn't support downloads. That's why you can't download anything anymore once you set Newsstand to "NO". 

The next version of Baker Framework will support In-App Purchases. :)

**Comment by zakkiman** [comment]
Thx David.

How about if I have the issue that user need to buy (not subscription), can
I use baker framework ? Can you show me the tutorial todo this ?

On Wed, Mar 27, 2013 at 5:37 PM, Davide Casali notifications@github.comwrote:

> The Standalone mode doesn't support downloads. That's why you can't
> download anything anymore once you set Newsstand to "NO".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/776#issuecomment-15516232
> .

## 

Best Regards,
Ahmad Zakki

**Comment by folletto** [comment]
That's what In-App Purchases are for. And that will be the next version of Baker, however you need to have a server to do that.
