### ISSUE TITLE
Icon and orientation

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#777]
HI! THis is working now my book! I want to know for this last time maybe where in Xcode I could change the icon of my book. And when I run my book, the Ipad simulator put it in portrait. Where I could change that? I want it in lanscape.

**Comment by Simbul** [comment]
There's plenty of documentation in the [wiki](https://github.com/Simbul/baker/wiki) for the Baker specific stuff, and you can have a look at Apple's documentation for generic information such as how to replace the icon.
