### ISSUE TITLE
Tool for automating book/issue production

### ISSUE THREAD

**Issue by surelynot** [Simbul/baker#779]
Hi all,

I've been taking a look at incorporating Hammer For Mac into a potential workflow for magazine production, and it's pretty amazing (I'm in no way affiliated with them). It's an html/css compiler that produces static (optimised) html files. 
http://hammerformac.com

Authoring the pages is so straightforward with this, just have your written copy as markdown files, and with one line in the html: 
    
It'll grab the file and write out the static page with all the html markup required. If you name everything sequentially, and code your templates to match, you won't even have to open a template at all, just include the right number of pages for each article (so setup 1.html using 1.md as the copy), then just drag the image and md files into the folder and press go. Done.

Genius. Thought there may be people out there that would find this interesting. It does heaps of other amazing stuff too to help speed up the design process. 
Best $25 I've spent all year.

Cheers Simon.

**Comment by nin9creative** [comment]
I've been impressed with the in5 plugin for Indesign.  However the output is heavy on images, it does work for more "traditional" looking magazine output.

**Comment by surelynot** [comment]
Hi Andrew,

I agree, the IN5 plug-in is impressive but, despite having used indesign (and quark before that) for years I found the workflow required really time consuming. It's really very fiddly, so many pages to edit each time, interactive layers to reinsert, having to do each article and then create new journal bundles. I think it would probably be ok for one off books but the idea of having to go through that with every issues I think would drive me mad...

There's a lot of potential to make mistakes in the indesign process I think. I remember one participant in the baker discussions describing a system he developed for his clients were they entered their text and uploaded images via a web interface and this information was placed into the correct parts of the HTML template and written out as a baker-ready book. With some robust templates I can imagine the Hammer workflow being used by people with no design background or where speed is crucial in the production process.

I suppose the in5 plugin may even have a role for some in designing those templates, which then could be tweaked to utilise the Hammer approach too.

Cheers!

**Comment by folletto** [comment]
It's because you're not the target user of that. The people that use InDesign probably will have the same hard time you have in using it in following the solution you're using. :)

For them, In5 is really the only solution. :)

**Comment by Simbul** [comment]
Closing this. See #756 for more info on in5.
