### ISSUE TITLE
I wanna put my book just on my Ipad

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#783]
Hello I wanna put my book just on my Ipad it's just a school's project. But I don't know to do with xcode. thnks a lot.

**Comment by coosir** [comment]
put hpub files in a local server

**Comment by aredqueen22** [comment]
even if it's a book with Standalone mode?

**Comment by ghost** [comment]
Do you mean, you want to put it just on your iPad rather than submit it to the App Store for everyone to see? You can just put it on your iPad if you have a developer license. All you have to do when running the app in xcode is select your ipad's name rather than simulator to install it.

**Comment by aredqueen22** [comment]
Yes I have a developer license with my college. And Yes I wanna to put my book in my Ipad. Where I select my Ipad name when I running the app in Xcode?

**Comment by ghost** [comment]
Just click on the top-left where it will say something like iPad Simulator 6.1. It's a drop down menu. When your iPad is plugged into the computer it will be at the top of this menu.

**Comment by jukialla** [comment]
Xcode > View > Show Toolbar > select device

**Comment by Simbul** [comment]
Hey @aredqueen22, have you solved this in the end? :)

**Comment by aredqueen22** [comment]
Nope. I didn't work because Xcode didn't see my device. I have an apple developper licence with the college's Ipad. I don't know why Xcode didn't see the device. Did I forget something?

Because I must to do the same thing for my conference. Or I run my application on simulator :S

**Comment by folletto** [comment]
Have you tried asking on the Apple Development Forums?

**Comment by aredqueen22** [comment]
Nope. I will ask on this forum. Thanks.

**Comment by divlv** [comment]
Any updates on this problem?
Did you find a solution?

**Comment by aredqueen22** [comment]
Nope and I don't have time for this. You can close this post because my book application was a school project and I don't have a Mac except at school. Thanks anyway. Maybe, I'll check this for an other project.
