### ISSUE TITLE
Build Failed in xCode

### ISSUE THREAD

**Issue by Rhom** [Simbul/baker#784]
Hello,
When I try to build and run the Baker project (+ Laker) with xCode, the program shows me a lot of errors when I did not touch anything. Should make a special handling for this work?
Sorry for my english, I'm french.
Thank you!

**Comment by philippgeuder** [comment]
which version of baker do you use? baker framework 4.0 from bakerframework.com or latest source from github?

**Comment by Rhom** [comment]
Baker Framework 4.0 and i just follow the step on the tutorial from bakerframework.com...

**Comment by folletto** [comment]
Then, please follow also the other tutorial, in case of problems: https://github.com/Simbul/baker/wiki/Problems-and-Debugging :)

**Comment by aredqueen22** [comment]
Which version you have with Xcode because I have the same problem in the past?
