### ISSUE TITLE
UI is blocked during book.json refresh

### ISSUE THREAD

**Issue by andrask** [Simbul/baker#787]
Currently book.json is updated every time the `ShelfViewController` appears. Since the updating of the book.json happens synchronously, this blocks the UI thread. This operation needs to be moved to a background scheduler.

**Comment by folletto** [comment]
Do you mean the `shelf.json`?

We accept pull requests ;)

**Comment by andrask** [comment]
Yes, `shelf.json`. Sorry. I looked into this issue but the problem is that the UI management is too tightly coupled into the operations. This makes it really complex to break the code up into GCD calls. Generally, it would be a great improvement if the view management and business logic was better separated.

I'll see what I can do. For now, I simply throttled this back by allowing the update only 30 seconds after the previous one.

**Comment by benoitchantre** [comment]
The pull request #817 has been merged, I think this issue can be closed.

**Comment by folletto** [comment]
Yep you're right. :)
