### ISSUE TITLE
Can't download issue from Newstand using latest version of Baker

### ISSUE THREAD

**Issue by lumierephoto** [Simbul/baker#788]
I followed instructions for setting up the app: 4.0 tutorial for Newsstand (free subscription) here on Github. I'm using the latest build of Baker from Github as well.

I can't seem to get the issue to download. I've tried as well with the Baker 4.0 on the official website as well, however I had different issues. 

The app does load and I do see the cover and the name of the magazine. 

The only thing I'm not sure about is the books.hpub file. Only because of the hidden extension of .zip so it is actually books.hpub.zip on the server. Im not sure if this is the way it's supposed to be. 

I did validate the book.json and shelf.json files. 

This is what is spewing out of the console:  

<pre>
2013-03-30 23:00:32.084 Baker[523:907] application didFinishLaunchingWithOptions
2013-03-30 23:00:32.088 Baker[523:907] ====== Newsstand is enabled ====== 2013-03-30 23:00:32.161 Baker[523:907] Successfully added skip backup attribute to      item /var/mobile/Applications/B70419D7-A7A2-492F-AF4C-   9A4AA81C2050/Library/Caches/shelf-status.json (iOS >= 5.1)
2013-03-30 23:00:32.442 Baker[523:3a03] ADDRESPONSE - ADDING TO MEMORY ONLY: http://syntheticmedia.net/shelf.json?app_id=com.syntheticmedia.laker&user_id=D3A0D0B3-7C74-4C71-8515-88EBF4DEDE2E
2013-03-30 23:00:32.464 Baker[523:907] Successfully added skip backup attribute to item /var/mobile/Applications/B70419D7-A7A2-492F-AF4C-9A4AA81C2050/Library/Caches/shelf.json (iOS >= 5.1)
2013-03-30 23:00:32.472 Baker[523:907] alloc a new date formatter
2013-03-30 23:00:32.505 Baker[523:907] EXCEPTION the name argument cannot be nil
2013-03-30 23:00:32.533 Baker[523:907] Refreshing (null) view with status (null) -> remote
2013-03-30 23:00:32.631 Baker[523:907] Failed to get token, error: Error Domain=NSCocoaErrorDomain Code=3000 "no valid 'aps-environment' entitlement string found for application" UserInfo=0x2082bd00 {NSLocalizedDescription=no valid 'aps-environment' entitlement string found for application}
2013-03-30 23:00:33.422 Baker[523:907] ############ REQUEST RECEIVED RESPONSE (
    "<SKProduct: 0x2082da20>"
</pre>

When I press download I receive this in the console:

```
 2013-03-30 23:01:15.325 Baker[523:907] Refreshing (null) view with status remote -> remote
```

I did create a test user account in iTunes Connect and I am able to subscribe successfully.

Mac OS X 10.7.5, iOS 6.1.3, Xcode 4.6

**Comment by Simbul** [comment]
You're missing a `name` property in your `shelf.json`. See [Newsstand shelf JSON](https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON#shelf-manifest-properties).

**Comment by folletto** [comment]
Furthermore:

> Only because of the hidden extension of .zip so it is actually books.hpub.zip on the server. Im not sure if this is the way it's supposed to be.

The extension must be "hpub", not "zip", so you have to remove the "zip" part of the filename. :)
Be sure to have the correct file in the `shelf.json` file as well. ;)

**Comment by lumierephoto** [comment]
@Simbul I added a name and title property to the name of the app. You can see in the link:

```
http://syntheticmedia.net/shelf.json
```

It is being pointed to in the Constants.h 

@folletto The extension is .hpub, however the hidden extension (you can only view this if you have hidden files enabled on your Mac)  is hpub.zip. As far as I know, I'm doing it correctly following these steps. I'm using the Laker book as an example:

1) Open the books folder
2) Select all files (Command + A) 
3) Right click and then compress all items
4) Change file name to  "books.hpub"
5) Put on server
6) Point to it in shelf.json file 

Here is where my file is:

```
http://syntheticmedia.net/books.hpub
```

It does not download for some reason. 

Here a link to the file itself:

```
 https://www.dropbox.com/s/pqb2s01z57q3nhk/books.hpubs.zip
```

I'm still getting error when clicking download:

```
 2013-03-31 18:16:08.446 Baker[885:1a303] Refreshing laker view with status remote -> remote
```

**Comment by folletto** [comment]
As I said, ".hpub.zip" means that the extension is ".zip", not ".hpub". The extension is only and uniquely the last part after the last dot. :)

"Hidden extension" means just that OSX isn't showing you the extension. That is in your case, ".zip".

Fix that. :)

**Comment by lumierephoto** [comment]
@folletto  The problem is that when I change my books.zip file to books.hpub, OSX automatically adds the .zip as the last extension which ends up as books.hpub.zip

The ONLY way I can take off the .zip extension is editing the file on the server directly. Then I do have a books.hpub file, however, the file is not downloadable like yours is. 

Links for comparison:

http://bakerframework.com/demo/a-study-in-scarlet.hpub

http://syntheticmedia.net/books.hpub

May I ask which archive software you are using to zip the "books" content? I've tried using the Archive Utility native to OSX, Keka and Stuffit. 

I attached an image of what the file looks like on the server
![Screen Shot 2013-03-31 at 9 10 23 PM](https://f.cloud.github.com/assets/981541/322736/aa0b7ca0-9a72-11e2-8f72-668f3cf45b87.png)

**Comment by lumierephoto** [comment]
@folletto OK, I sorted it out. There were a few issues.

First, the date wasn't formatted correctly in the shelf.json file. 

I had: "YYYY-MM-DD"  instead of "YYYY-MM-DD HH:MM:SS"

I searched for this in the docs because I was getting this log in the console:

```
 2013-03-31 23:17:50.676 Baker[6261:1a303] alloc a new date formatter
```

In fact, I changed the date format to this in all json files i.e book.json

Second, for my issue with zipping I solved it by: creating the zip, dragging the zip onto the server and then changing the extension to .hpub directly on the server i.e my FTP client instead of trying to do it on my computer. This stopped OSX from then making the books.hpub.zip file as I said before since I have hidden files enabled on my computer. What a weird quirk! 

After I did this I'm now able to download the issue on my iPad!

**Comment by Simbul** [comment]
As an aside, you can change the extension in OS X by using Terminal or by editing "Name & extension" after you do "Get Info" on a file in Finder ;)

**Comment by lumierephoto** [comment]
Yes, I can confirm it does work if you "Get Info" and edit the "Name & Extension". I was trying this before as well, but I was first changing the extension to .hpub directly on the file and then after that editing in the "Get Info". 

I haven't fully tested, but I believe the real issue was the "date" string in the SHELF.JSON, because after I corrected it after I received this log: 

```
Baker[11159:1a303] alloc a new date formatter
```

I then received this log with the date string, which I hadn't before:

```
Baker[11159:1a303] added laker 2013-03-30 12:01:30 +0000
```

It seems to me that this date format is imperative for the compiler to then move on to the next process. I don't know why I was formatting it that way before?
