### ISSUE TITLE
Semantic issues with Xcode Version 4.6.1 (4H512)

### ISSUE THREAD

**Issue by jukialla** [Simbul/baker#789]
Hi, I just upgraded to Xcode Version 4.6.1 (4H512). Now i get three new semantic issues popping up as in the image below. Any clues on these?
![Screen Shot 2013-04-01 at 1 27 04 AM](https://f.cloud.github.com/assets/3812260/322530/f613726e-9a5a-11e2-9a86-d52caad95f50.png)

**Comment by folletto** [comment]
Semantic issues aren't usually a problem. If it's running, it's ok.

What version of Baker are you using? :)

**Comment by lumierephoto** [comment]
I agree. These issues usually are for deprecations, but provide backwards compatibility

**Comment by jukialla** [comment]
4.0.5 - Yes they are not causing any problems with the running of the app. No need to worry about them then?

**Comment by Simbul** [comment]
You can generally ignore those issues.

As an aside, we usually fix them in the `master` branch.
