### ISSUE TITLE
Push Notification through baker server

### ISSUE THREAD

**Issue by tekdope** [Simbul/baker#792]
Hi guys, this must be a dumb question but how do do you send push notification?
I mean i installed everything : Baker Server API is running and got token devices in database etc...
But how do you send the json file containing  "content-available": 1 ?

I'm missing something here but tutorial isn't clear  about this, thanks for helping me.

**Comment by nin9creative** [comment]
You'll need something such as Easy APNS, Parse, or Urban Airship etc...

**Comment by tekdope** [comment]
Hey Andrew, thanks for your answer. I was wondering if you knew a good tutorial or already developed php to retrieve datas from baker-server database and plug them with Parse?

**Comment by folletto** [comment]
Which server are you using? I'm asking just to point out that the server you find published on GitHub isn't a production server, is just useful for you to develop your server as a guideline and nothing more. Nobody should use it as is or develop over it. :)

**Comment by tekdope** [comment]
@folletto thanks for pointing out this. Well i'm going to use easyapn then, unless you guys have a better recommandation :))

Any tutorial on how to plug easyapn with baker ?

**Comment by tekdope** [comment]
Ok, i downloaded EasyApns but i think i would prefer to go with something like Parse.com. Is someone aorund here already plugged the latest master version of Baker with Parse.com notification center. If yes i wouldn't ming to get some help on this :) Thx

**Comment by yujulio** [comment]
I followed this guide:
https://www.parse.com/apps/quickstart_push#ios/existing

2013/4/3 Cedman notifications@github.com

**Comment by tekdope** [comment]
@yujulio Thank you so much, Exactly what i needed. I'm going to give it a try. I let you know if i have troubles to implement in latest version of Baker.

**Comment by tekdope** [comment]
Ok, i added Parse and commented some lines of code to make it work. It fully functional.
@folletto i'm closing this since my problem is solved. Thank you all for your help.

**Comment by folletto** [comment]
Great! :)
If you want to write something here on on your blog on how to do that it would be very helpful for others. ;)

**Comment by tekdope** [comment]
Sure, i'll write a couple of lines in the wiki when i have a chance.
