### ISSUE TITLE
Infos on Baker

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#796]
Hi! I will give a conference in a few weeks about Baker but it miss some informations that I need. I want infos about Baker, BakerShelf and BakerView folders. please. Where I will find these informations?

**Comment by folletto** [comment]
Hello!

What kind of informations do you need? :)

**Comment by aredqueen22** [comment]
What is their utility these folders on Bakerframework :)

**Comment by folletto** [comment]
Well... they _are_ Baker Framework, which for development reasons is split into a number of logical units.

If you open each of these folders you see the code that drives Baker and how it works. Loosely:
1. `Baker` if you open it you see that it contains just the application initialization files
2. `BakerView` is the viewer itself, basically what was there before version 4.0. It's the part that actually shows the Hpub format.
3. `BakerShelf` is... the shelf. Manages the various issues, Newsstand and calls the BakerView when a publication is opened.

**Comment by aredqueen22** [comment]
Thanks a lot :+1:

**Comment by folletto** [comment]
You're welcome. :)
