### ISSUE TITLE
Build failed with standalone mode (undeclared identifiers)

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#797]
I found an issue if you use the latest code available from the master branch and the standalone mode: undeclared identifiers in BakerAPI.m
- `NEWSSTAND_MANIFEST_URL`
- `PURCHASES_URL`
- `PURCHASE_CONFIRMATION_URL`
- `POST_APNS_TOKEN_URL`

**Comment by folletto** [comment]
Thanks! We'll look into it. :)
