### ISSUE TITLE
Disappearing Shelf

### ISSUE THREAD

**Issue by janakmshah** [Simbul/baker#798]
Hi, I hope I'm not being really stupid here, but when I point to a shelf.json file with all the elements except 'Product_id' everything works fine. As soon as I add the 'Product_id' line all the issues disappear. Do I have to do anything more to have paid issues show up other than just change the shelf.json?

Thanks,
Janak

**Comment by folletto** [comment]
Did you follow the tutorial? :)
https://github.com/Simbul/baker/wiki/In-App-Purchase-tutorial

**Comment by janakmshah** [comment]
Nevermind, I was missing a comma in the JSON! Sorry :s

**Comment by kvirella** [comment]
Hmm. Trying to find the in-app-purchase tutorial. The link above no longer works. I'm guessing GitHub's redesign ate it. Anyone have another URL for it?

**Comment by kvirella** [comment]
Found it: https://github.com/Simbul/baker/wiki/Tutorial-for-Newsstand-with-In-App-Purchase
