### ISSUE TITLE
Status bar on center tap

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#8]
_As a user I want to see the status bar when I tap in the middle of the pages_

(this is the first step for future "center taps" admin controls)

**Comment by Simbul** [comment]
Implemented in commit c2136c50c07ccd44ff70dee05c73819554edec62.
A minor feature is missing: make the status bar automatically disappear when the page is scrolled vertically with a swipe motion.
I will close the issue when the feature is added.

**Comment by Simbul** [comment]
Completed in commit 013a8d219a295f4fb108a7e705460eb1b1b29a92.

**Comment by jeffehobbs** [comment]
In the iPad simulator, the status bar now toggles during internal link-based navigation. The status bar works as expected during swipe-based navigation.

**Comment by folletto** [comment]
I'll re-open this. :)

**Comment by folletto** [comment]
Just to keep track of everything, we tried to ask on StackOverflow:
http://stackoverflow.com/questions/4597118/intercept-unused-tap-events-in-a-uiwebview

**Comment by jeffehobbs** [comment]
For a short term production fix, I wound up commenting out the toggle status bar function call in the source code, so the status bar always shows.

**Comment by folletto** [comment]
I'd go for the "never shows", most of the things we see are going to take it off (and forcing it on changes the page size). However, that's a _critical_ function to evolve this app, so either we are able to solve it, or to find another way to show "additional features". :(

**Comment by MacBoy** [comment]
Please do not show the Status Bar on a tap. The content is meant to be immersive, any distraction of that kind is not needed.

Thank you  :-)

**Comment by folletto** [comment]
To remove that feature it means that basically we can't evolve the platform more than it is now. The trigger at the touch is _critical_ to allow the evolution of the platform, to perform more actions. If you don't like it, just disable it if your books, but this is critical for us. :)

**Comment by MacBoy** [comment]
I think I understand your intentions.

You want to capture the tap for other reasons.  Such as showing a drop-down menu, navigation bar, etc.

Was the tap-to-show the status bar just a way of demonstrating that taps can be caught and processed?

**Comment by folletto** [comment]
Exactly. For now it's something still useful, but simple and non-intrusive. Until we are able to perfect it it's pointless to try moving forward. :)

**Comment by Simbul** [comment]
Ok, we need to back down on this, as it's not possible to associate the single tap to the statusbar toggle and at the same time keep all the other single-tap actions.
From now on, the statusbar toggle will be associated to a single-finger double-tap in the center area of the screen and will be implemented accordingly.

**Comment by Changilainen** [comment]
Following silently your progress on this. Keep up the good work!

**Comment by Simbul** [comment]
The gesture to open and close the statusbar is now a single-finger double-tap in the center area of the screen.
Minor code refactoring in InterceptorWindow.
Closed by b074338637fdffdc4920597ec200020cce66274d.
