### ISSUE TITLE
Free Subscription mechanism implementation

### ISSUE THREAD

**Issue by ask91** [Simbul/baker#800]
i wish you guys to give me a hint about the mechanism of FREE SUBSCRIPTION part. because i've once tried submitting an application to Apple store and got rejected because of that issue.

'Additionally, we found that your app has an associated free subscription, however, it does not include a mechanism for the user to sign up for the free subscription.
It is required to revise the app to include the mechanism to allow user to sign up for the free subscription. For more information, please see Newsstand for Developers for information on Newsstand Kit.For discrete code-level questions, you may wish to consult with Apple Developer Technical Support. Please be sure to:
- include the complete details of your rejection issues
- prepare any symbolicated crash logs, screenshots, and steps to reproduce the issues for when the DTS engineer follows up. '

they also sent a screenshot of an image, that i think probably, they tried to access the application for subscription but the URL i've described, directs to where it should provide a page for user input their information to free subscribe the application.

i'm not sure how to start building the free subscription implementation,.
wish anyone could give me a hint to do that

**Comment by folletto** [comment]
When the Free Subscription is setup, you'll notice the button in the top-left corner "Subscribe", just on the side of the refresh icon. Is it there?

Could you also attach the screenshot?

**Comment by ask91** [comment]
the problem is i'm blind with how to create the free subscription mechanism.
i mean, what should i do first to make it?
is it like making a page for signing up in the same URL that i put in my book.json for my application<book application like scarlet sample> or what?

**Comment by folletto** [comment]
Nop, nothing like that. If you follow these instructions that's it: https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

The "mechanism" is builtin. Once setup, a button "Subscribe" will appear in the top-left corner of Baker in the shelf screen.

**Comment by ask91** [comment]
The 8 point Set PURCHASE_CONFIRMATION_URL to the URL where i want to receive the ping.
1. if i have an individual web, it could be anywhere.  willl it matter if its just a page that contain nothing?
2. does the free subscription mechanism has something to di with the baker server API? if yes, then i should make a form page of html as interface that connect to _baker-server-example_ like php files, aren't i?
   with web services php sql server etc, dont know what i have to do to the baker-server files

i found this source,and i think i missed those steps too :(
http://troybrant.net/blog/2010/01/in-app-purchases-a-full-walkthrough/
http://blog.mugunthkumar.com/coding/iphone-tutorial-–-in-app-purchases/

i'm sorry for the inconvenience of my complicated question
the steps in apple documentation out from the baker project confusing me too

**Comment by folletto** [comment]
Point 8 is _optional_. :)
As said, the tutorial is all you need to do to setup the publication.

Are you setting up Free or In-App Purchases? There's a difference. :D
With In-App Purchases of course it's kinda of a problem to offer a Free Subscription (plus, you need to develop a server). The tutorial for In-App Purchases is [this one](https://github.com/Simbul/baker/wiki/In-App-Purchase-tutorial) but I don't think it's what you're looking for.

**Comment by ask91** [comment]
I read the following guide of Apple documentation and stuck on setting up server to maintain the in app purchase processes.

as said in the Apple documentation about Server Product Model :

In the server product model, you provide a separate server that delivers products to your application. Server delivery is appropriate for subscriptions, services and content, because these products can be delivered as data without altering your application bundle. For example, a game might deliver new play environments (puzzles or levels) to the application. Store Kit does not define the design of your server or its interactions with your application. You are responsible for designing all interactions between your application and your server. Further, Store Kit does not provide a mechanism to identify a particular user. Your design may require you to provide a mechanism to identify a user. If your application requires these (for example, to track which subscriptions are associated with a particular user), you need to design and implement this yourself.

i know that the baker server API example is a model sample for a server i should build.
but where to do with the php?
i dont understand how to start a Baker API -like server model.

does it uploading such folder db,issue,lib,log &php files to my web host?

**Comment by ask91** [comment]
I've managed to show the Subscribe button on the top left of my shelf :) 
When I tap it, the message window contains button to "Subscription for free"  appear as an option. But when I tap it, it shows a message "Subscription failure" and a "Close" button. Is it normal? Is it enough to be approved by Apple App Store?

**Comment by ask91** [comment]
By the way, I'm setting up for free subscription. But in the future, I will try to sell the magazine. Not in the short term. Maybe in the next year.

**Comment by Simbul** [comment]
You should not get a failure message if everything works as it should. I don't think the app would be approved, as is.

Look in the log inside XCode to see if you get any more info on the error that prevents the subscription.

Also, make sure you have set your bundle ID correctly and that the product ID for the free subscription corresponds to a free subscription set up in iTunes Connect.
In addition, to test anything that has to do with iTunes Connect, you should create and use a test user.

**Comment by ask91** [comment]
thanks,.
yes, i've set bundleID &productID correctly & created test account,.

so, instead of getting "subscription failure" what is the very simple workflow should appear?

if it has something to do with baker-server like things, what should i do next, after putting the sample php implementations in a directory of my web,.? 

i haven't tried working out to the backend things,.hope you help give steps to lead me there

**Comment by folletto** [comment]
There's no backend if you are doing Free subscriptions. If you follow this tutorial that's all you need. Really. We don't lie :D
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone

So, if by following that tutorial till the end it's still not working, please check this page:
https://github.com/Simbul/baker/wiki/Problems-and-Debugging
And report back. ;)

**Comment by ask91** [comment]
Okay
i'll help clear it with myself,
I can see the different steps of NewsstandFreeSubscription mode VS paid issues/subscriptions IAP is at the 'CONFIGURE SUBSCRIPTION MANAGEMENT SERVER' for IAP setting. 

I'll start over following the 'Baker in Newsstand mode with free issues/subscriptions' from the documentation https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand.

Do you think with free subscription mode, 
we could still get the report of how many downloads occurs [like analytics], and push notification for our app?

Lot thanks for all your helps & reccommendations  :)

**Comment by folletto** [comment]
Given the situation, I'd suggest to do one thing at time. First setup everything and make it work. :)

Analytics and Push notifications aren't part of Baker right now, so you need to develop these features by yourself. :)

**Comment by ask91** [comment]
Thanks @folletto , i'll report back the progress ASAP :D

**Comment by ask91** [comment]
I got the flow of free-subscription process work :)
- [ ] When tapping the subscribe button at the top left of the newsstand,
  a dialog window Subscription Option with 'Subscribe for free' button appeared.
- [ ] Then 'Confirm Subscription'  dialog (from sandbox environment) appeared with option: 
  CANCEL and CONFIRM. 
- [ ] by confirm it, 
  a dialog window then prompted me to Sign In with apple ID.
  i used existing test user appleID from iTunesConnect account. 
  i've create the Test User Account by following this basic documentation:
  http://developer.apple.com/library/ios/#documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/7_ManagingYourTeam/ManagingYourTeam.html  
- [ ] Dialog window then asked 'Show Your Information' to be allowed. 
- [ ] by Allowing it, a successful message of the free subscription issue came up. 

guess, that's what Apple asks to be done for a 'free subscription', am i correct or should there be more process within the FreeSubscription beside the process i said above ?

**Comment by folletto** [comment]
That's it. :)
