### ISSUE TITLE
delete old issues automatically

### ISSUE THREAD

**Issue by coosir** [Simbul/baker#803]
hi guys,

if old issues were downloaded but not in new shelf.json, they will not be displayed but still exist in the device.

would it possible to auto-delete these issues? (after shelf.json refreshed)

and...if a device always display Baker (single-app mode), would it auto-refresh shelf.json?(like every hour)

**Comment by folletto** [comment]
It's not currently possible. But I add this as a feature request. :)

**Comment by benoitchantre** [comment]
It now integrated in the master branch, see issue #957.

**Comment by Simbul** [comment]
Thanks for pointing this out. I'm closing it ;)
