### ISSUE TITLE
7 Errors on Baker.xcodeproj with xcode 4.6.1 and baker-framework-4.0

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#804]
Hello world ;)

when I open the Baker.xcodeproj with xcode 4.6.1 and baker-framework-4.0 
just for trying i have 7 errors :
![Capture d e cran 2013-04-07 a 23 59 08](https://f.cloud.github.com/assets/4087173/349548/fc4e20ce-9fce-11e2-8061-b5a6be94b2e0.png)

why ?
Hope you will help me ;)

**Comment by folletto** [comment]
In general terms, Warnings aren't errors. If the application runs, it's ok. :)

Just follow the tutorial however, the only warning you should fix is the one in Constants.h, but that's explained in the tutorial.

**Comment by kodjoe** [comment]
hello folletto ;)
thanks for your help and hope to find you if I've some problems ;) 

i start the tuto ;)

**Comment by kodjoe** [comment]
Hello arfff I've an other problem i just read that :
NOTE: Baker 4.0 does not support the book protocol for downloads. Use version 3.2.x instead.

But my goal is to create a Newsstand app with free download issues and subscription (18 at this time)

1) so can I continue with backer 4.0 if not where can i find baker 3.2.x and which version of xcode i've to use for it ?

2) i want to put an url of my first issue on the book.json, at this time this is the location of my issue's folder :
baker-framework-4.0/books/fm17/"all my html files and the folder for images"
What is the following...

"url": "book://facticemagazine.com/book/fm17/...",

thank you

**Comment by Simbul** [comment]
1. Yes, Baker 4.0 supports book downloads via Newsstand. What you cannot do with 4.0 is download books _without_ Newsstand.
2. Not sure what you mean exactly. If you're wondering about the URL in `book.json`, it can be whatever string you like, as long as it's unique.

**Comment by kodjoe** [comment]
Okay for the two sentences and thanks for your quick reply ;)
so for each magazine we have a book.json file with the link of the magazine

but in this link, which file should I aim for ?
an .hpub
An html file 
or ?

**Comment by Simbul** [comment]
Inside `book.json`, it doesn't matter, as long as the URL is unique. It can be _whatever string you like_. See [hpub specification](https://github.com/Simbul/baker/wiki/hpub%20specification).

On the other hand, the URL in `shelf.json` has to point to your HPUB file, but that's a wholly different file with a different purpose ;)

**Comment by kodjoe** [comment]
okay so i'll put this link in the book.json
"url": "book://mywebsite.com/book/fm17/",

but for the  shelf.json, I read anything yet on it so i think that it's a futur step ;)

**Comment by Simbul** [comment]
Cool. I'm closing the issue if that's ok with you then ;)

**Comment by kodjoe** [comment]
yepp thank you ;)

**Comment by kodjoe** [comment]
Just to be sure
you know when book.json is finished and valid
we just have : a folder (books) with insides each folders for each issues and insides these folders only a zip file called for example mag.hpub ???

so if you understand me, we have : 
baker-framework-4.0/books/17/mag.hpub
baker-framework-4.0/books/16/mag.hpub
....
or 
baker-framework-4.0/books/17/mag and mag.hpub
baker-framework-4.0/books/16/mag and mag.hpub
....
