### ISSUE TITLE
Page scrolls up when opening index (double tap)

### ISSUE THREAD

**Issue by aspek** [Simbul/baker#805]
If user double tap on page for show index bar. The page will move up.That right?
This feature work smoothie with original index form.

-So I have customize an index.html is height= 700px. If double tap on page.  The page will move up. It look not good. I just want to fix the position of page.

**Comment by Simbul** [comment]
We were able to reproduce the issue. It looks like it has nothing to do with the size of the index bar, as disabling the index bar entirely does not solve it.

What it comes down to is actually a UIWebView feature: you can see the same behaviour in Safari on iOS: if you double tap on an empty area of a page, the web view will scroll until the position you tapped on is at the center of the viewport.

We're currently looking into a fix.

**Comment by aspek** [comment]
Thanks you so much.

**Comment by Xm4s** [comment]
With commit 5064ddac we disabled the doubletap-to-focus behaviour on the UIWebView,  but **only if the zoomable property in the book.json is set to false**, otherwise it remains active to help the user to reset the zoom level

**Comment by aspek** [comment]
@Xm4s Thanks.
 I  try to set 

```
 [self removeWebViewDoubleTapGestureRecognizer:webView];

//    if (!webView.scalesPageToFit) {
//        [self removeWebViewDoubleTapGestureRecognizer:webView];
//    }
```

it work fine on iOS 5.1 - 6.1. I do not know what effect it will have.But it can work on `zoomable : true  and false`

**Comment by folletto** [comment]
@Aspek why are you changing it? It should work straight out of the box if you try the latest version. Are you still having problems?

**Comment by aspek** [comment]
Because. If I config `zoomable:true` the problem not solved. From Xm4s said "only if the zoomable property in the book.json is set to false"

**Comment by folletto** [comment]
If `zoomable: true` that's what the user expects to happen. Try in Safari. Otherwise you are removing the zoom functionality as well. ;)

**Comment by aspek** [comment]
Yes, I agree. But I can enable and disable zoom function and work  as well on iOS 5.1 -6.1. Did you try it?

**Comment by folletto** [comment]
I don't understand the question, sorry. What do you mean? :)

**Comment by aspek** [comment]
I mean. If user double tap on page for show index bar. The page will move up.

And Xm4s  disabled the doubletap-to-focus behaviour on the UIWebView, but only if the zoomable property in the book.json is set to false.

I will try to config the code from Xm4s just put out `[self removeWebViewDoubleTapGestureRecognizer:webView];` form the box. And it work on `zoomable :true` too  and now page not moved up if user double tap  for show index bar.

**Comment by aspek** [comment]
I use zoom with finger pinch.

**Comment by folletto** [comment]
Ah ok, now I get it. Well, that's not the expected behaviour, so you're going to annoy a everyone that zooms with double-tap.  :)
