### ISSUE TITLE
book.json & Newsstand shelf JSON

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#807]
Hello friends ;)
I just have 2 questions for you ;)

Book.json :
Just to be sure !!!! you know when book.json is finished and valid
we just have : a folder (books) with insides each folders for each issues and insides these folders only a zip file called for example mag.hpub ???

so if you understand me, we have : 
baker-framework-4.0/books/17/mag.hpub
baker-framework-4.0/books/16/mag.hpub
....
or 
baker-framework-4.0/books/17/mag and mag.hpub
baker-framework-4.0/books/16/mag and mag.hpub
....

---

shelf.json :
Where & how do I copy this bloc in constant.h ?

```
[
  {
    "name": "a-study-in-scarlet",
    "title": "A Study in Scarlet",
    "info": "The original masterpiece by Sir A. Conan Doyle",
    "date": "1887-10-10 10:10:10",
    "cover": "http://bakerframework.com/newsstand-books/a-study-in-scarlet.png",
    "url": "http://bakerframework.com/newsstand-books/a-study-in-scarlet.hpub",
    "product_id": "com.example.Baker.issues.january2013"
  },
  {
    "name": "a-study-in-green",
    "title": "A Study in Green",
    "info": "An exciting remake of the original, with added mint!",
    "date": "2010-10-10 10:10:10",
    "cover": "http://bakerframework.com/newsstand-books/a-study-in-green.png",
    "url": "http://bakerframework.com/newsstand-books/a-study-in-green.hpub"
  }

  ...

]
```

Here in constant.h ?

```
// ----------------------------------------------------------------------------------------------------
// Mandatory - This constant defines where the JSON file containing all the publications is located.
// For more information on this file, see: https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON
// E.g. @"http://example.com/books.json"
#define NEWSSTAND_MANIFEST_URL @""
```

**Comment by folletto** [comment]
So, you're doing Newsstand. :)
As such, you need just the Hpub uploaded to the server.

One thing that you could do and could also help you through, is to follow really really step by step the tutorial, and tell us where you get confused on what to do:
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

For example, Step 3 of "Create Your Publication" states to upload just the Hpub to the server. That's it. Where is the confusing coming from on what to upload? Is how we wrote the sentence?

–

On the second question, you don't have to copy that. Following the tutorial you see the "Create a shelf.json file" and it states that the block there must be inside the `shelf.json` file on the server. Then, in a later step, you configure that constant in Xcode with the `shelf.json` file URL location.

**Comment by folletto** [comment]
1. Yes. Zip and rename. :)
2. Yes. Just the Hpub file must be on your server. That's the "issue" Newsstand will download.
3. Which folder are you referring to? You just need the Hpub and the cover. Where they are located doesn't matter, as long as you write the correct URL in `shelf.json`. :)

If you're getting that error I'm afraid to say this... but you're missing some step from the tutorial. Follow it _to the letter_. 

For example: where is your shelf file?

**Comment by folletto** [comment]
These aren't errors, these are warnings. If the application runs, there's no problem. 

However... man, as much as I want to help you, it seems you're not following through the tutorial. I really don't want to repeat that but...  The shelf file should be on a server, and that's step 3 of "Create a shelf.json file". :)
Please, follow through it literally, and then see if it works.

And if I test the URLs above, the image don't load, so you have some problem on your server: http://facticemagazine.com/apps/17/images/0.png

**Comment by folletto** [comment]
@kodjoe, really. FOLLOW THE TUTORIAL. It will answer the questions above. :)

**Comment by folletto** [comment]
Excellent. :)

So, is `NEWSSTAND_MANIFEST_URL` set? 
Could you link here the `shelf.json` file?

Could you paste also the debug log from Xcode? :)

**Comment by folletto** [comment]
1. You set it... opening `constant.h` and adding that. See the tutorial (LOL) under "CONFIGURE BAKER WITH NEWSSTAND AND SUBSCRIPTION". :)
2. Ok. Works. :)
3. See this image to [open the log](http://beginning-mac-programming.timisted.net/images/posts/generalOverview/04-Xcode4DebuggerConsole.png)

**Comment by folletto** [comment]
> Can I work on "configure baker in newsstand and subscription" before "configur newwstand on itunes connect"

So you're telling me you're testing the app again before having completed the tutorial? Man, really. I don't know what to say again. Complete. The. Tutorial _FIRST_. :(

"Test and publish" is the FINAL thing after you do _all_ the steps there. :(

**Comment by kodjoe** [comment]
Hello Folletto now i finished all the tutorial and i just have some problems of finalization
I just wanna say thank you for all your help and patience : 
- I don't have background color for my thumbnails (books.json file perhaps ?)
- When I launch my app in simulator iphone for example i've a probleme with height of images, they're to tall (height of images on html files of my microsite perhaps ?)
- In magazine background, I've my title with the number of the pages behind my images, how can I delete it (books,json file ?)
- When i try to go and back with images, my background become grey and not white. 
  How to put it only white ?
- Probleme with subscribe. check the images : 
  ![Capture d e cran 2013-04-11 a 19 11 21](https://f.cloud.github.com/assets/4087173/368883/feebf30c-a2ca-11e2-9d85-54845b5fb21d.png)
  ![Capture d e cran 2013-04-11 a 19 12 08](https://f.cloud.github.com/assets/4087173/368884/0174a236-a2cb-11e2-8c29-0cf6397f0c78.png)
- and finally probleme with in apps purchases, i don't understand this message : 
  ![Capture d e cran 2013-04-11 a 18 41 10](https://f.cloud.github.com/assets/4087173/368886/10faa30e-a2cb-11e2-9b13-97f55ba0455a.png)

**Comment by ask91** [comment]
1) In your point 7,
-   i think the first image is a normal flow of Free Subscription process
-   second image,
  you need to create a Test User Account in your genuine itunes connect account in Manage User section,
  just put your test email, password, no need verification like real account registration because it'll just be used as fake account for debuging your app in Sandbox Environment, not the real appstore server. And you shouldnt use that Test Account to purchase a real apps in iTunes Connect/AppStore.

2) last point,
the problem comes from the Apple-side process,. you should walkthrough the Apple Developer/Store guide :)
