### ISSUE TITLE
Creating Magazine with full-page JPEGs...same image appearing for every page.

### ISSUE THREAD

**Issue by millr88** [Simbul/baker#81]
I have used the Baker Framework to run a JPEG based magazine, inside of the HTML5 tables. I plan to rebuild future magazines using HTML 5 pages instead of linking to full JPEGS.

The files are all linked properly, just like a functioning website, with the JPEGs inside of the gfx folder.

However, when running the test on the iOS 4.3 iPad simulator, the same image is being called for all 24 pages, even though the HTML on each page calls for the image that corresponds with that page.

Is this an issue only in the simulator?

Can I expect the same thing to happen if I have an HTML 5 layout instead for my headers and footers?

**Comment by folletto** [comment]
Hello! 

It's really hard to understand what's happening, is it possible for you to send us a ZIP with the book you are making, changing the images with dummy ones so we can see it? :)

**Comment by millr88** [comment]
Sure, where should I send the .zip?

I can send it over later tonight.

**Comment by folletto** [comment]
Thanks! Send it to: info AT bakerframework DOT com :)

**Comment by millr88** [comment]
Thank you so much!
I'll definitely give you guys a shout out in the mag for your assistance.

**Comment by folletto** [comment]
This was resolved through email. It was a problem solved by removing the "build/" folder (or a Clean all targets equivalent).
