### ISSUE TITLE
testing newsstand on ipad doesn´t load issue

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#811]
hi!
comming back to bakers after a long time i tried newsstand 4.0 with your tutorial. all ok,
setting up all shelf.json and other stuff i want to test on my ipad from xcode.
all updated. i see my cover in newsstand, i can download into the shelf. as soon as i click "read" i get my splash-screen and the spinner from page 1, then ist stoppes. and i cannot get back but have to force quit the app.
is it not possible to load the issue and test it?
do i have to wait for apples review first??
i also cannot test free subscription - it alerts "can´t connect to itunes store"
attached a screenshot, where xcode is changing when i click the "read"-button.

![xcode_problem](https://f.cloud.github.com/assets/1135467/368205/6f1a79de-a2ba-11e2-8e25-b3438bb267c9.jpg)

thanx for help
regards
strmiska

**Comment by folletto** [comment]
You should be able to test it before submission, so if it doesn't work it means there's something missing.

Could you follow: https://github.com/Simbul/baker/wiki/Problems-and-Debugging
And report back?

**Comment by hitchio** [comment]
hi foiletto!
testing with success!! my issue on my server was damaged or had the wrong book.json content, i don´t know.
what i did, i exported all htm5-files again, cleaned all builds, wrote .json again new - zip, upload to my server, rename to .hpub ---> ´s working now!! thanx-h.

**Comment by folletto** [comment]
That's great! :)
