### ISSUE TITLE
Help with setting up Baker Server and API

### ISSUE THREAD

**Issue by ImkeTee** [Simbul/baker#812]
Hey guys. 
Who would be able to help me with setting up the Baker Server API? I am currently trying to set up a paid supscription for  Newsstand and I am stuck on "CONFIGURE YOUR SUPSCRIPTION MANAGEMENT SERVER". I have the link to https://github.com/Simbul/baker/wiki/Baker-Server-API on github, but here it says that the server example implementation is not meant to be used for setup. I am not technical enough to set up a server... Who would be able to help, or lead on the matter? 

Many thanks

**Comment by ImkeTee** [comment]
Hi again. Would anyone be able to help on this? I have everything set up and am using baker master for testing and compiling, but need help with houw to set up the Server please. Many thanks. Imke

**Comment by folletto** [comment]
Did you try contacting one of the developers on our page? :)
http://bakerframework.com/developers

**Comment by ImkeTee** [comment]
Thanks I will do that now.
