### ISSUE TITLE
standalone build failed SystemConfiguration.h file not found

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#813]
I've just downloaded the latest master files and have set baker up as standalone version for testing. 

Build failed - issue is in Reachability.h:
# import <SystemConfiguration/SystemConfiguration.h>

issue: 'SystemConfiguration/SystemConfiguration.h' file not found

I tried commenting out the line which imports the file but then get other errors.

**Comment by folletto** [comment]
The answer I found on StackOverflow is unfortunately Xcode related:
http://stackoverflow.com/questions/9685101/systemconfiguration-systemconfiguration-h-file-not-found

> Re-installing Xcode removed the error.

We'll check to see if we can find any other cause. :)

**Comment by anjimi** [comment]
Thank you @folletto reinstalling Xcode did indeed resolve that issue.

**Comment by folletto** [comment]
Good! Annoying, but at least it worked. :)
