### ISSUE TITLE
CFBundleVersion [Baker40]: Validation/Publishing Issue

### ISSUE THREAD

**Issue by thejtate** [Simbul/baker#815]
Finally finished up my first project with Baker and now on the step of publishing this sucker to the App Store. Pretty excited!

Looks like I'm running into one last roadblock. When I go to validate and publish it through the Organizer/Archives, the signing works but it's giving me an error:

<code>This bundle is invalid. The value for the key CFBundleVersion [Baker40] in the Info.plist file must be a period-separated list of non-negative integers. </code>

Probably a stupid question, but just all new to this. Is there a step I skipped with setting up Baker or is this just a question I need to shoot over to Apple's forums? 

Thanks.

**Comment by folletto** [comment]
Uhm... good point... it should be part of one of the steps of the tutorial (together with Bundle ID) but we probably left out part of it by error, we have to check.

Just follow the message there: 

> period-separated list of non-negative integers

And you should be fine. :)

**Comment by thejtate** [comment]
Changed [Baker40] to just 4.0 and it passed validation. Feel dumb not thinking that through at what exactly the error was trying to tell me. But this thread might be good for anyone who might have hit this as well. 

Thanks @folletto!

**Comment by folletto** [comment]
Precisely! :)
Good to know it's solved. :)
