### ISSUE TITLE
Native Twitter integration into HTML5 page

### ISSUE THREAD

**Issue by simantics** [Simbul/baker#816]
Hi All,

Firstly thanks to everyone who's worked on the Baker Framework, it's incredibly awesome for someone like myself who isn't well versed in Objective-C (or even much HTML/JS really). 

I'd like to know if there's anyway to integrate iOS' native Twitter and Facebook sharing framework into an HTML page. Example: I have a normal html page with words and pics, I've placed a button inside which if tapped opens up the native Twitter prompt.

At the moment I'm using Twitter's share?url= which opens up the referrer=Baker browser inside of the app. This is ok, but not ideal. Also for some reason the referrer=Baker browser doesn't seem to work with Facebook's sharer URL protocol.

Any help would be much appreciated. Sorry if I'm not following the proper etiquette, very new to Github. 

Cheers for your time,
Sim.

**Comment by Simbul** [comment]
You should be able to use a `twitter://` link. If the Twitter app is installed on the device, it will be called automatically.

An example would be:

``` html
<a href="twitter://post?message=hello%20world">Share On Twitter</a>
```

**Comment by folletto** [comment]
We completed this as we went ahead on issue #862 and implemented an additional support feature to call any kind of third-party app. :)
