### ISSUE TITLE
Missing Push Notification Entitlement 

### ISSUE THREAD

**Issue by drking0211** [Simbul/baker#819]
Just uploaded binary to Apple foe a Free Subscription magazine called Knitsy and got his message back.

Doesn't seem that onerous.  Anyone else seen this and any idea where the API call is emanating from?

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

If you would like to update your binary for this app, you can reject this binary from the Binary Details page in iTunes Connect. Note that rejecting your binary will remove your app from the review queue and the review process will start over from the beginning when you resubmit your binary.

Regards

dk

**Comment by marcheluis** [comment]
i think this is the same error I'm having, i am still testing but i get the following message in the output on Xcode:

2013-05-03 17:24:47.995 Lo+in[11043:907] [AppDelegate] Push Notification - Device Token, review: Error Domain=NSCocoaErrorDomain Code=3000 "no valid 'aps-environment' entitlement string found for application" UserInfo=0x1fd715b0 {NSLocalizedDescription=no valid 'aps-environment' entitlement string found for application}

I haven´t configured anything to do with push notifications, and i configured baker to work on newsstand mode.

**Comment by marcheluis** [comment]
Just found the source of this error. On AppDelegate.m from line 73 to 94 is the part of the didFinishLaunchingWithOptions method that checks if the app is running in response to a notification. Because i don't have push notifications configured there should be a constant to define if baker should execute this section or not, because otherwise this error pops out when not having push notifications configured.

In Constants.h inside the `#ifdef BAKER_NEWSSTAND` i added the following line:

```
#define APNS_ENABLED
```

Then in AppDelegate.m i added `#ifdef APNS_ENABLED` before line 73 and `#endif` after line 94.

This way, if you are not using push notifications, you just need to comment `#define APNS_ENABLED`.

**Comment by folletto** [comment]
Thanks! That's a wonderful feedback. We'll look into it. :)

**Comment by marcheluis** [comment]
Ok, so after adding my condition to get rid of the error i mentioned before, i have finally sent my app for review and i got an email with the same message @drking0211 got. So my question is, do i have to remove a library? which one?

**Comment by folletto** [comment]
I report the feedback we received on Issue #879: 

> @simantics: "If you aren't using push notifications in the app, then it will be fine. I recieved the same alert after I uploaded my binary and it was approved without a hitch.
> The alert is only if you intend to use push notifications – but most likely if you are using push, you would know which bits to edit."

**Comment by marcheluis** [comment]
thanks @folletto i hadn't seen that issue

**Comment by folletto** [comment]
You're welcome. :)
