### ISSUE TITLE
HTML5 / CSS3/Baker Framework classes etc.

### ISSUE THREAD

**Issue by k8fisher** [Simbul/baker#82]
Hi Im new to the group and would like to ask for an overview of how  these entities relate to one another. Im from a programmatic background, but unix based. Not familiar with macs or xcode. I can see there are different entities going on in this funky shabang but Im finding it hard to understand the crossover between the html5 documents I create to sit within the baker framework object and the classes etc / bits within the directory structure. I need to log up on css3 as Im more familiar with css2.  Could someone give me a quick run down on how the classes and programmatic bits fit together. E.g. if I want my book to add navigation to the object Im creating (which holds the HTML5 book) where would I make alterations. Would there be a library of functions I can work with?

Im just not feeling the relationship between the entities, html5 code, classes of baker, webkit etc.

Any assistance would be most welcome as I have programmatic experience Im just in a whole new environment. Is there a book which might help me get up and running with this thing as Im trying to find my bearings atm.

Much appreciated.

K

**Comment by folletto** [comment]
Hi k8fisher,

To use Baker Framework you don't have to learn anything more than HTML and CSS, so, you just need to put your HTML files in the book/ folder as explained in the readme.

Really, there isn't anything else to do. :)

To create a menu like you asked you can borrow ideas from other Baker books that has been published, from in-page sliders (you tap on a corner and you get the menu) to a simple link to one of the first pages. All HTML.

You can develop everything inside your browser (check the test book from the website) and then put the files in the book/ folder an compile. :)

**Comment by k8fisher** [comment]
Hi Folletto, might I ask if theres an area where sample books are available? So far Ive seen the Tokyo 5x15 example which looks great , but Ive not found the examples you mention though Ive been working with Florians version of the code (to try to utilise the rotate functionality he's built into the baker framework).

Would love to see more examples, which use menus etc. Love the work you guys are doing because most every other way of putting a publication via things like indesign is insanely expensive for a small organisaiton putting free magazines out.

Kate

**Comment by folletto** [comment]
I think that Florian's work just posted here with more details on his website should be able to answer a lot of your questions. ;)
It's the issue #83.

For the sample books we are updating the website soon with some of them. :)

**Comment by folletto** [comment]
We added a page on the website with all the published books we are aware of: http://bakerframework.com/books
Also, there is a more detailed tutorial: http://bakerframework.com/tutorials/basic

If you need more help, just ping back. :)
