### ISSUE TITLE
Cant Find iWeb support I need

### ISSUE THREAD

**Issue by methodradio** [Simbul/baker#823]
Ok, Posted here before, but had to scrap and start over.

I am using iWeb to make my HTML.  I export it and open in safari, all is well.  I then try and zip it with a JSON and it falls apart.  The photo below, is how the files come out from iWeb, dropped JSON in there just to store.

![Screen Shot 2013-04-17 at 12 36 06 AM](https://f.cloud.github.com/assets/2636088/389674/63020358-a718-11e2-9d78-989e127a6de1.png)

now, when i organize the files, according to the baker tutorial, the css/html is all lost and the thing falls apart.

![Screen Shot 2013-04-17 at 12 38 42 AM](https://f.cloud.github.com/assets/2636088/389677/c760df90-a718-11e2-84c2-cf3f324ec3df.png)

Now I have a less than 10 page, mainly text, document I am trying to get into newsstand.  I have been struggling for months.  I feel I am pretty comfortable with all the lingo and the steps on the web, but I cannot get my websites to load correctly once the user hits download on the shelf.  

![Screen Shot 2013-04-17 at 12 50 23 AM](https://f.cloud.github.com/assets/2636088/389712/5b13817e-a71a-11e2-93c7-2b8a4c77462a.png)

now I feel this could be due to iWeb's default file management, but then how do I maintain my site's integrity when reordering like the baker tutorial.  Does the index.html file and the .plist files have anything to do with it.  

fishing for any solution at this point, even if I have to scrap the code again.  Can work in PDF or HTML but trying to keep it Open Source.  And baker appears simple enough when reading.

Anyone use iWeb as their main tool?

PLEASE HELP MEEE!

**Comment by folletto** [comment]
Hello! :)

I think the idea would be that you shouldn't move the files when you finish with iWeb. In other terms: keep the files as they are, otherwise it will break.
The difference is all inside `book.json`, in the `content` section just add the path, folder included, to your files. For example:

```

   "contents": [
        "Aspects_of_tsomething_Newsstand/index.html",
        "Aspects_of_tsomething_Newsstand/Part1-01.html",
        "Aspects_of_tsomething_Newsstand/Part1-02.html",
        "Aspects_of_tsomething_Newsstand/Part1-03.html",
        "Aspects_of_tsomething_Newsstand/Part1-04.html"
    ]

```

In this way, you keep everything as iWeb prepared, but you reference the pages as needed. :)

**Comment by methodradio** [comment]
I am currently loading up alright.  Didnt have to touch json – it looks like my file was showing still .zip and never fully became .hpub – novice.  Thanks again — ill have more very soon !
