### ISSUE TITLE
Kerning.js

### ISSUE THREAD

**Issue by lostinjapan** [Simbul/baker#824]
Has anyone been able to use kerning.js with this framework? I tried including the file so we'd have more control over word wrap in some instances, but none of the styles would work. I assumed there was some kind of conflict.

http://kerningjs.com/

**Comment by folletto** [comment]
Does kerning.js work on Mobile Safari?

**Comment by lostinjapan** [comment]
Sorry, I spoke too soon. It appeared to not be working, but I hadn't tried very extreme examples I guess. 

So yes, kerning.js works for fine-tuning your typography.
