### ISSUE TITLE
Sandbox or real mode for submission ?

### ISSUE THREAD

**Issue by RolandMarianna** [Simbul/baker#825]
Hello,

I just put my Baker App for review. It is the newstand version with in-app purchases.
When I made test with my server scripts, I put de receipt checking in sandbox mode.

For Appstore review, do I need to put it on the normal mode or let it on the sandbox mode until the app will be approuved ?

Thanks

**Comment by folletto** [comment]
The submission is always the final version, the one that gets uploaded on the store, as such it should use the release codes.

I guess however that you might get better feedback on Apple's Developer Forums or Stacktrace, since it's an Apple-related question. :)

**Comment by RolandMarianna** [comment]
I think you are right about the feedback :)

Thanks a lot.

**Comment by folletto** [comment]
Great! :)
