### ISSUE TITLE
Baker server api

### ISSUE THREAD

**Issue by belle101** [Simbul/baker#826]
Hello,

I want to ask a question about the baker server api because i'm not familiar with back end,

what do i need it for?

if i want just a free subscription magazines and i want to add an issue do i need a php files or i just edit the shelf.json file and add a new issue?

thank you :)

**Comment by folletto** [comment]
Hello!

If you deal with just free magazines then you don't need a backend. Just following the [Newsstand tutorial](https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand) is enough. :)

**Comment by belle101** [comment]
What if i want to add a new issue? 

And if i want to create a purchased subscriptions is there any tutorial that i can follow? (like i said before i'm not familiar with backend and the baker server api and the example aren't frank enough :( ) 

Thanks again Davide, your answers always help :)

**Comment by folletto** [comment]
To add a new Issue you just add it in `shelf.json`, that lists all your issues and then publish it. :)

Purchases mean payments, and payments will be in the next version. However given the additional security, management and so on, to work they require a server you have to build.

So in short:
- Free = **no** server, just Baker and iTunes Connect
- Pay = server, Baker and iTunes Connect

**Comment by belle101** [comment]
Aaa i see,

How about adding new issue in standalone type? Since there is no shelf.json 

Sorry i ask so many questions i am a bit confused :s

**Comment by folletto** [comment]
If you follow the tutorial you'll see that it tells you to add the issues in the `books/` folder. When you have a new issue just add it there and upload the app to the Store. :)

**Comment by belle101** [comment]
Ok Davide, thank you! 

You can close this :)

**Comment by folletto** [comment]
You're welcome. :)
