### ISSUE TITLE
-baker-vertical-pagination property in book.json

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#827]
Should the -baker-vertical-pagination property in the book.json file still apply? I've downloaded the latest master version of Baker and am testing it with my existing book which is published in our current app using Baker 4.0. I have -baker-vertical-pagination set to true but vertical pagination is not applied on my book pages. I tried adding the new meta tag (https://github.com/Simbul/baker/issues/607) to a page and that page then has vertical pagination.

As I understood from the wiki the -baker-vertical-pagination setting applies to the whole book, and the meta tag is used to alter an individual page:

-baker-vertical-pagination (_boolean_, default: false):
Whether vertical page scrolling should be paginated in the whole publication. Since 4.1 this setting can be overridden on a per-page basis by adding the tag `<meta name="paged" content="YES">` inside the `<head>` tag of the HTML file.

**Comment by folletto** [comment]
That should still apply, yes. We have to look into that...
