### ISSUE TITLE
bug on exiting fullscreen video in iOS 5

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#828]
After testing the latest master version for the previous bug on exiting fullscreen video https://github.com/Simbul/baker/issues/611 which is fixed...

There is a new/lesser bug in iOS 5.0/5.1 only:

When exiting fullscreen video the app screen moves up by 20px (the same effect as was happening in #584 which is now fixed). Oddly, if the device has been rotated before playing fullscreen video it doesn't happen.

It works fine in iOS 6.1.

**Comment by folletto** [comment]
Is this bug still present in Baker 4.1? :)

**Comment by anjimi** [comment]
I haven't tested with Baker 4.1 release code yet, will do soon.

**Comment by benoitchantre** [comment]
The bug is still present in Baker 4.1.

**Comment by folletto** [comment]
We are evaluating to remove support of iOS5 from the next version of Baker, what do you think? :)

**Comment by benoitchantre** [comment]
iOS 5 support has been removed, this issue can be closed.

**Comment by folletto** [comment]
Right. ;)
