### ISSUE TITLE
Laker - a compendium of files, frameworks, styles and tips for designing digital publications in HTML5.

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#83]
Hey everybody,

I'm glad to announce, that I finished my diploma thesis! One part of it was the development of a digital magazine with HTML5 and Baker. I collected all the changes I made to Baker, all my files and all scripts and produced a little compendium called "Laker".

http://www.lakercompendium.com

With the combination of Baker and the CSS Framework Less, I designed a digital publication. The layout resizes automatically, depending on screen size and orientation. Furthermore "Laker" includes HTML code snippets for a variety of content-types, such as slideshows, text, video, audio and so on.

Please use "Laker" as a starting point for your own project and let me know if something is wrong or can be improved!
Thanks again to the Baker-Developers. They done a great job and I hope with "Laker" I can give something back to the project.

Does it help, when I upload the "Laker"-Version of Baker to gitHUB?

Best regards and happy experimenting,
florian

**Comment by folletto** [comment]
Wow Florian, that's amazing! :D
You did an impressive job! :D

Which version of Baker did you use?
Did you make any change, or did you build just over the current Baker framework? (i.e. is it going to be easy to upgrade to the upcoming 2.0?). :)

Please ping us back when the app is approved, too. :)

**Comment by ffranke** [comment]
Hey Foletto,

Thanks!
I started with the public 1.1 Master Version and added some code of simbul Baker concerning the table of contents. But it was not functioning properbly, so a friend helped me making some modifications.

If you have any suggestions or tipps, please let me know!

Florian

**Comment by folletto** [comment]
Ok, I think it's too late for the 2.0 but it's something we can look into for the next version. :)

I'll test it out asap and we'll get back in contact. For now... well, it's an amazing work.
Do you mind if we add a link back from our site when we update it? :)

**Comment by ffranke** [comment]
Sure, go along! I would be really happy! ;)
cool! 

It's a pity, that i can't release the magazine I did for my thesis ("zuviel", see "about"). It's got 17 dossiers and a lot of cool stuff... But the content is not entirely mine...

**Comment by ffranke** [comment]
Oh and bear with me, if the files are not 100% cleanly written. I'm a designer, not a coder ;)

**Comment by Simbul** [comment]
Terrific work Florian! This is really the stuff Baker was built for :)

When you talk of uploading to Github I assume you're referring to bringing some of your modifications to the core of the Baker project. The best way of doing that would be to fork the project and later submit a pull request (both operations are explained in detail in the Github help pages). Failing that, I presume it'd nonetheless possible to include changes from a totally separated repo, it would just be more complicated.

**Comment by folletto** [comment]
Florian, just a quick update: we added your project in our brand new tutorial page for the 2.0: http://bakerframework.com/tutorials

And when your app is released by Apple I think it's a great entry for our showcase page. ;)

**Comment by ffranke** [comment]
Hey Folletto,

cool, thanks! Ouuuh 2.0! 
I'll take a look how to include it into Laker (or if its even necessary to include it).

best regards
florian

**Comment by ffranke** [comment]
Hey everybody!

Laker is now updated with the 2.0 Version of Baker. We added the Laker-Features and updated the Starter Pack.
http://www.lakercompendium.com/2011/04/28/laker-now-includes-the-new-baker-version-2-0/

If you find some errors, please let me know!
Florian

**Comment by laswell** [comment]
I've been using Laker all day now it it is AMAZING. I seriously created a great mag/app and it was great fun as well as looking fantastic. So much potential here, I hope you guys keep in touch or team up because together you have a killer product.
Cheers
Laurence

**Comment by ffranke** [comment]
Hey Laurence,

great to hear that! Wow! Do you submitted it to the App-Store?

Cheeeerio,
florian

**Comment by laswell** [comment]
Hey Florian, no, early days yet, I work for a TV Network here in Australia and have been searching for a way to bring some of our content to the iOS world with out bogging down in dev time. We were blown away today, so I'll be putting in the dev time as as soon as I have something I'll be sure to let you know. I sincerely hope you keep going, maybe in the template for iOS mag / app style because I think that would be huge. 

Regards
Your beta tester
Laurence

**Comment by ffranke** [comment]
;D Cool. Ah "Laurence from australia". Just got back to you via Email ;D

cheerio

**Comment by laswell** [comment]
hehe :)

**Comment by folletto** [comment]
Well, on our side we are looking forward to integrate give the same features on the Cocoa side, and I think it's fine to have Laker as a framework on top of it. But of course Florian, if you have other ideas let's discuss them. ;)

**Comment by laswell** [comment]
Hey Davide, ooops , sorry I should have said how amazed I am at the baker framework as well, after all it's the platform Laker is sitting on , so my hat is off to you guys as well. I'm sure there are some big names taking note of what you guys are up to , it's a fantastic way to bring content to iOS. I can't wait to see what comes next
cheers
Laurence

**Comment by folletto** [comment]
No worries! Florence really did an amazing work! 
Thanks for the support! :)

**Comment by laswell** [comment]
:)

**Comment by ffranke** [comment]
Hey folletto,

here are some of the things I like to see (besides the changes already made in Laker):
- Preloading of Pages for faster Page swiping
- Support for <iFrame> (currently the app quits and opens safari with the content of the iframe ;D)

When I'm discovering something else, I let you know.

Florian

**Comment by therabidbanana** [comment]
Hey guys, I've broken out Florian's awesome navigation bar enhancement from Laker into a separate topic branch that can be merged into the Baker core - Issue #85 has the changes.

I made some modifications to allow disabling the feature completely by setting a constant, updating the navigation when opening a downloaded .hpub, and handle resizing a little better.

**Comment by therabidbanana** [comment]
Also based on Florian's work - a Sinatra based hpub generator.

https://github.com/orangesparkleball/bakers-oven

**Comment by folletto** [comment]
Very nice. I just tweeted about it! ;)

**Comment by tablazines** [comment]
Hey, when is that sample publication that you have on the Laker site going to finally make the appstore?

**Comment by ffranke** [comment]
I didn't have time to work on it, but if you want to check it out, just install the starter-package and run the code on an iPad. It's the same app.

cheers
florian

**Comment by tablazines** [comment]
GREAT... thanks...

**Comment by ffranke** [comment]
I hope that's not meant ironically ;D

**Comment by tablazines** [comment]
lol..no....

**Comment by tstegart** [comment]
Just wanted to add my thanks to both the Laker and Baker folks, this is all awesome.

**Comment by folletto** [comment]
Thank you! These comments helps a lot in keeping the morale up! :)

**Comment by Paul-B** [comment]
I want to say thank you to the Baker project and Florian for the Laker files. It's awesome. I finally managed to self-publish my study book in the app-store. I already converted it to epub via smashwords but sales are low and version control is not good enough. An app allows so much more functions.

**Comment by folletto** [comment]
I'll close this one to follow Issue #196, and waiting for the update to Laker there. :)

**Comment by ffranke** [comment]
Hey Paul-B!

Wanna share the link to that publication?

cheers
florian
