### ISSUE TITLE
fastclick.js

### ISSUE THREAD

**Issue by hdml** [Simbul/baker#830]
I'm trying to implement [fastclick.js](https://github.com/ftlabs/fastclick) with baker to get rid of the 300 ms delay between the tap and the actual `click` event. I'm running into the problem where the double-tap event doesn't register and can't show the index bar.

Fastclick attaches to everything inside the body and fires a synthetic `click` when `touchend` fires, it is initialized like so:

```
window.addEventListener('load', function() {
    new FastClick(document.body);
}, false);
```

The problem is that it suppresses the additional `click` event that the browser generates after 300 ms. I'm not sure how Baker knows when there's a double-tap, if it needs the non-synthetic `click` event for it to determine the double-tap, then I'm at a loss.

Does anybody here can hint a solution for this problem I'm having?

Thanks!

**Comment by espilber** [comment]
Hi, fastclick.js is a fantastic script for webapps but doesn't work well in Baker. Try energize.js instead, only captures the "a href" events and the double tap works perfect!
https://github.com/davidcalhoun/energize.js

**Comment by folletto** [comment]
That's an excellent feedback, thanks! :D

**Comment by Simbul** [comment]
@rowbells have you managed to fix this (by using energize.js or otherwise)?

**Comment by hdml** [comment]
@Simbul yes, I ended up using energize.js. There's a workaround for those who _must_ use fastclick.js, you can add the `needsclick` class to every item that's not clickable with a simple jQuery line like

```
$('div:not(button-class)').addClass('needsclick');
```

But I don't like this approach, as it adds too much complexity to a simple process, I'll leave the solution here for future documentation.

**Comment by folletto** [comment]
Thanks for taking time to give feedback here. :)
