### ISSUE TITLE
About push

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#831]
Hello, I work on a free Newsstand application with baker and I would like to add a new downloadable magazine every two months with its Push notification, I've to follow these two paragraphs here : https://github.com/Simbul/baker/wiki/Push-notifications-tutorial
->
1) APNS device token
2) Push notification for the latest issue

Or

1) follow this tutorial ->
http://www.raywenderlich.com/3443/apple-push-notification-services-tutorial-part-12

2) implemente APNS device token
https://github.com/Simbul/baker/wiki/Baker-Server-API#apns-device-token

3) and finaly create a json file or add on shelf.json/book.json these lines ->
{
    "aps": {
        "content-available": 1
    },
    "content-name": "a-study-in-scarlet"
}

Thanks

**Comment by folletto** [comment]
If you want to use Baker, I'd suggest to use our wiki, but as you can see, that page you link is more informative, it isn't a tutorial, and points to the [server implementation](https://github.com/Simbul/baker/wiki/Baker-Server-API). You need to develop a server to use Push. Or use the just released MagRocket, see Issue #829. ;)

However yes, we should clear out better how to use Push in the upcoming 4.1 release.

**Comment by kodjoe** [comment]
Okay that's cool, this  is an interesting point for the new upcoming 4.1 release. hope to find that in 4.1 -> "send automatycly push notifications when a new downloadable magazine is available"

meanwhile the upcoming release of Baker 4.1,  
- I'll deepen reading of MagRocket, I've seen that Andrew purposed this tutorial Parse via this link too : 
  https://github.com/nin9creative/baker/issues/89
- If I've some complications, can I follow these tutorials ?
  server side : http://blog.serverdensity.com/how-to-build-an-apple-push-notification-provider-server-tutorial/
  client side : http://mobiforge.com/developing/story/programming-apple-push-notification-services
- Or If you have a better/nice tutorial (Step by step) that looks like yours to suggest me, I'll take it with smile ;)

Thanks Folletto ;) and congratulation for all your work really ;)

**Comment by nin9creative** [comment]
With Magrocket, the intention is to put in a easy to use push notification hook that can be triggered from the MagRocket Administration Console.  

The issue with Push Notifications is that you really need a third party solution for sending them (in a reliable manner). 

I'm targeting to integrate with the Parse.com Push Service as they have a pretty healthy FREE plan as well as an easy to use API that I can consume from the MagRocket side.

Still trying to figure out the best approach.  I may end up supporting a few of the top tier providers (Parse, Urban Airship, Stackmob) etc...

Warm Regards,
Andrew

**Comment by kodjoe** [comment]
Thanks mister Andrew, I think I understood :

Magrocket, Parse,Urban Airship, Stackmob, pushwizard... have the same goal, if we pass by them we just have to configure our apps from each tuto that each platform purpose to us, right ? 

I want the most reliable platform who send "an automatic push notifications when a new magazine is available for download". If no one can do that, I can send it manually from the administration Console. According to you,which platform will be most appropriate to my request.

Thank you

**Comment by nin9creative** [comment]
If you can wait a bit I will be integrating a push notification ability and server directly into MagRocket based on the EasyAPNS code base - so there will be a complete solution using MagRocket.

Warm Regards,
Andrew

**Comment by kodjoe** [comment]
Oki doki maestro ;) sure I'll wait, it looks pretty cool !!!
- How to know when it'll be available ? (via newsletter ?)
- Where can I read how "Free subscriptions support on the top-left" works when a reader subscribe for example ?
  (in other words "the operation process")

I will submit my Apps without push notification in these days and try to add an update with push notification when all is available 

Hope  I can ;)
Thank you very much ;)

**Comment by festaans** [comment]
Wow, this is really, really awesome

**Comment by kodjoe** [comment]
About Subscribe button : 

I found that interresting discussion : https://github.com/Simbul/baker/issues/559

1) "The subscription just allows you (the author) to get the data of the user subscribing. What you do with that is usually the Push Notification, but it's a separate piece of code. :)"
->how to use data of the user after subscrition ? via newsletter when a new issue is available ?

2) "Baker today implements background download without Push. Actually, that's one of the reasons why we are asking people to submit to the store: that's the only way we'll know for sure. ;)"
->Actually I offer only free subscription, a background downloading will start via wifi  when a new issue is available?

**Comment by folletto** [comment]
Briefly: push notification to work require a server. If you don't have a server, you can't do that. The reason is that the user must be subscribed, the subscription must be stored in a server and when you publish the server goes through the list of subscribers and sends a push notification to them.

So, to answer:
1. As we were saying above, you need a server. Either develop your own, or wait for MagRocket's implementation.
2. No. Since background download requires an activation and that without push notifications (so, without a server) the download will just start when the user opens the application. Then it goes on downloading in background, but the user has to open the app first and open the magazine.

**Comment by nin9creative** [comment]
Good summary :)

Andrew

**Comment by kodjoe** [comment]
Ok, about push notification, I understand it perfectly now and it's for that reason that'll wait for the new release ;)

1) And I finally understand the problem, you also "need a server" to use data of subscriber after a subscription!!! it's that I don't understand since the begining !!! So before magrocket's implementation, subscribe button is useless if you don't develope a server !!!!

2) And that' cool for me if any new issue is downloaded when the user open the apps ;) meanwhile the magrocket's implementaion

Thank you very much guys, that's what I call precision ;D

**Comment by folletto** [comment]
You're welcome. Do you think we may close this issue now? :)

**Comment by kodjoe** [comment]
;) yes we can close this issue you rock guys !!!

i'll follow you an Andrew on github for the 4.1 release ;)
