### ISSUE TITLE
Index / TOC does not hide

### ISSUE THREAD

**Issue by yujulio** [Simbul/baker#837]
Hi, I'm using the last master and just found this is happening:

Opening the book the index shows automatically:
![Captura de pantalla de Simulador iOS 23 04 2013 14 26 15](https://f.cloud.github.com/assets/678854/416203/80c2f562-ac47-11e2-804e-d90b4f0dfd79.png)

If you double click the screen the index goes up 200px more.
![Captura de pantalla de Simulador iOS 23 04 2013 14 26 18](https://f.cloud.github.com/assets/678854/416204/80d66ee4-ac47-11e2-9f06-729663057719.png)

**Comment by jaehanley** [comment]
Noticed this as well. Occurs when the user exits the application, and then re-opens the application. Was able to return to normal functionality by ending the background process.

**Comment by folletto** [comment]
Thanks for discovering the bug! We'll check it. :)
