### ISSUE TITLE
Icon Newsstand 

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#838]
Hello everybody ;) about icon apps Newsstand

I organized my icons like that and everything works : 

![Capture d e cran 2013-04-24 a 02 33 38](https://f.cloud.github.com/assets/4087173/417711/a7c56904-ac76-11e2-9c76-f6a98f021278.png)

ios-icon-iphone -> 41x57
ios-icon-iphone@2x.png -> 81x114
ios-icon-ipad -> 51x72
ios-icon-ipad@2x.png -> 101x144

Actualy these images are in a folder inside backer 4.0 folder.
Just to knoww, can I upload these images on my server and put the link for each images on info.plist ?

Because when my apps will be in Appstore, how can I add a new icon for the new issues if there are not on my server ?

Perhaps there is an automatic way to change icons ?
or I've to change them, re-archive the xcode project and resend it whenever ?

Thank you

**Comment by folletto** [comment]
The 'cover' parameter of `shelf.json` is the one specifying the icon visualized on the Newsstand shelf. :)

Check it here: https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON

**Comment by kodjoe** [comment]
Extract of my shel.json ->
 {
        "name": "Factice Magazine #18 - Dazzling Lights HD",
        "title": "Dazzling Lights HD",
        "info": "Issue 18 / April 2013 / 103pages / 86 Mo",
        "date": "2013-10-04 20:05:53",
        "cover": "http://facticemagazine.com/apps/18.png",
        "url": "http://facticemagazine.com/apps/issue18.hpub",
        "product_id": "com.facticemagazine.issues.April2013"
    },

If you speak about these cover icons, it's okay I ever put the link in front of cover line, it works great for each issue ;) ->

![Capture d e cran 2013-04-24 a 02 55 10](https://f.cloud.github.com/assets/4087173/417772/b27a2512-ac79-11e2-8167-7b8faa0623f6.png)

But for these icons ->

![Capture d e cran 2013-04-24 a 00 16 59](https://f.cloud.github.com/assets/4087173/417328/9c0e3e6e-ac63-11e2-98a3-c94ddc72176d.png)

I found two different elements of answer  here : https://github.com/Simbul/baker/issues/576

1) "The convention with Newsstand apps is to have a specific default cover for your magazine. I believe the long edge of your icon should be at least 512px with an aspect ratio of between 1:2 and 2:1 (magazine or newspaper). You define this icon in your xxx-info.plist. Under your icon files there is an area for Newsstand Icons This is where you reference the default image that will show up on the Newsstand. Right now with 4.0 they are the usual iPhone/iPad icons. "

If I have to modify the info.plist, what should I write into the info.plist to have the icon of the latest issue whenever automatically ? 
At this time I've the images from here : baker-framework-4.0/baker/icon/... ->

![Capture d e cran 2013-04-24 a 02 33 38](https://f.cloud.github.com/assets/4087173/417791/8cd29000-ac7a-11e2-835d-496a634cda62.png)

2) https://github.com/Simbul/baker/wiki/Issue-cover-displayed-in-Newsstand
Answer -> I just have to put this line : "cover": "http://facticemagazine.com/apps/....png"
for each new issue on shel.json  and the most recent cover link icon will appear automatically on each update on the shel.json file ?

**Comment by aspek** [comment]
If you use newsstand app.The icon from supporting file it will show only in Storage list
setting  --> General -->  Usage -->  Storage.

So if you want update your default cover. 
1. You just go manage it on iTuneconnect / Manage Newsstand --> Add issue . 
2. go to App details --> look at the bottom page --> Change Default Cover Art.

**Comment by kodjoe** [comment]
The picture that we can see here :  setting --> General --> Usage --> Storage.
Is the same image from :  App details --> look at the bottom page --> Change Default Cover Art.

I though that this cover was managed with the info.plis ->
![9c0e3e6e-ac63-11e2-98a3-c94ddc72176d](https://f.cloud.github.com/assets/4087173/420927/a50dab98-acfa-11e2-95cf-f169abd04830.png)

**Comment by folletto** [comment]
Ok, to summarize:
1. The icon you specify in the plist is the default one that you get when no issue has been downloaded. :)
2. Instead, as said, the icon you specify in `shelf.json` is the same of the one shown on the Newsstand shelf when you download an issue. :)

**Comment by kodjoe** [comment]
Hello,Is it normal to have the same icon  (the little one in background) even after downloading the issue 15 ->

![Capture d e cran 2013-04-24 a 20 21 06](https://f.cloud.github.com/assets/4087173/421611/c6c5cfd8-ad0c-11e2-97de-c0184c58985b.png)

![Capture d e cran 2013-04-24 a 20 32 07](https://f.cloud.github.com/assets/4087173/421626/5413deb6-ad0d-11e2-9465-191f3859a173.png)
