### ISSUE TITLE
blur javascript event

### ISSUE THREAD

**Issue by nms666** [Simbul/baker#839]
The blur event is not called if the rendering mode is not "three cards"
I have changed the gotoPage function in BakerViewController.m and moved the call to blur event above the check for rendering mode.
It's working fine.

Is the change I have made correct ? 

thanks

**Comment by folletto** [comment]
You mean the `window.blur` event?
Well... It's hard to tell without checking it. If it works for you, then I guess that's it. :D

**Comment by nms666** [comment]
Yes, I mean the window.blur event.
If you check it let me now if it's ok.

thanks

**Comment by folletto** [comment]
Err... I need to see the code, test it, and verify it works in all the conditions and all. I think the best thing is for you to test it (verify that, and also that doesn't trigger "double" events for example when you re-enable three-cards) then it's fine. :)

I can't help much. :D

**Comment by Simbul** [comment]
Closing due to lack of followup.
