### ISSUE TITLE
chapter / section

### ISSUE THREAD

**Issue by comfused** [Simbul/baker#84]
Hi,

I was wondering if the following is possible - or will be in the future:

I'd like that each folder inside the 'book' folder is considered as a chapter / section.
The swiping between pages is only possible inside a chapter / section.
To go to another chapter / section you need to click on a link, that links to a page in another folder.

Also, it would be nice to have a setting (inside RootViewController.m for example) to disable the swiping between pages - so you can only go to another page by clicking on a link.

**Comment by ffranke** [comment]
"Also, it would be nice to have a setting (inside RootViewController.m for example) to disable the swiping between pages - so you can only go to another page by clicking on a link."

But then you wouldn't need Baker. You could build it as a normal website and ask users to "save it to homescreen". 

florian

**Comment by comfused** [comment]
Time has already learned us that people want an app to download/install
I wonder how many people know the 'save to homescreen' functionality

Thing is, I'm building a 'conference schedule app'
and you don't want the user to be able to swipe on all pages - cause that is not what the user is expecting
the swiping is good, for certain parts of the app
so if I could work with subfolders inside the 'book' folder - and have only swiping able inside each folder - that would be also good

example structure:
- book folder
  --- index.html
  --- saturday folder
  ------ speaker001.html
  ------ speaker002.html
  ------ speaker003.html
  --- sunday folder
  ------ speaker001.html
  ------ speaker002.html
  ------ speaker003.html

this way:
- I can link from the index page to the 2 days
- people can swipe between pages inside a certain folder ('sunday folder' for example)
- but you won't swipe from a page from folder A to a page in folder B

hope I make myself clear :)

**Comment by Xm4s** [comment]
Hi comfused!

With the actual version of Baker you can do something like that with the aid of the "downloadable books" feature.

You can bundle inside your Baker app a book with just one page, which contains all the link to the other books.
A tap on one of those link will start the download of the "new" book and at the end will open it; the book then will be navigable like a normal Baker book.
In each book a link to book://local must be provided, which, when clicked, will return the user back to the main bundle book.

That would be a simple solution for you case, the only drawback is that now Baker doesn't store more than one book at a time: when you return to the bundle book the last downloaded book is deleted, so every time you switch from a book to another you'll have to download it.

**Comment by Javier-G-Lainez** [comment]
I think you don't need any folder. Reading the Baker documentation, the application will browse alphabetically all the pages. Well, you can "recreate" a folder tree without folders, simply by using a combination of letters and numbers. For example:

a001.html
a002.html
...
a999.html

b001.html
b002.html
...
b999.html

If you sort them alphabetically, you'll end up with the same functionality as the use of folders.

And for a way to restrict the navigation to just one folder, maybe the app can trigger a javascript in the last page of the series. For example, an onLoad event that redirects to the first page of the chapter.

**Comment by comfused** [comment]
the sorting I understand
but I don't want the user to be able to swipe from a999.html to b001.html
and I'm afraid javascript isn't going to solve this

**Comment by Javier-G-Lainez** [comment]
Try this code: http://davidwalsh.name/detect-iphone

**Comment by Javier-G-Lainez** [comment]
Works like a charm!!!

Paste this simple line inside an script label (in the head section of an empty html page) and it will redirect to the first page of the stack:

document.location = "a001.html";

(I can't put the entire head code because this blog parses the content and I don't know how to avoid this).

**Comment by folletto** [comment]
Ok, to summarize:
- It's outside the scope of Baker as it's intended.
- It seems doable in javascript.
- Still, it's going to be managed well with the multi-hpub support, once ready.

I think that's all, I close this issue. If there's something else, please comment. ;)
