### ISSUE TITLE
unwanted book in standalone app

### ISSUE THREAD

**Issue by belle101** [Simbul/baker#843]
Hi again,

I try my standalone app when suddenly there's a study in scarlet book in my application, i didn't include that book in my books folder. 

what's wrong?
thanks
![Screen Shot 2013-04-25 at 11 54 24 PM](https://f.cloud.github.com/assets/4170188/426431/e9d8ac7c-adc8-11e2-816c-29468a0e014b.png)

**Comment by folletto** [comment]
Please check the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page, it's likely a problem related to cleanup or removal of the app from the simulator before re-building it. :)

**Comment by Simbul** [comment]
As an aside, your folder hierarchy looks a bit weird. Why do you have a `books` folder inside the main `books` folder?

**Comment by belle101** [comment]
okay thanks, i already changed it and i think the problem is like what @folletto have said,
thanks

**Comment by folletto** [comment]
Good to hear that. :)
I'm closing this then, reopen if needed. ;)
