### ISSUE TITLE
correcting bundle ID mismatch

### ISSUE THREAD

**Issue by kvirella** [Simbul/baker#844]
Hi! I have kind of a dumb question. Sorry!

Is there a way to remove the word Baker that auto-populates my bundle ID field in Xcode? I'm asking because -- after testing my app on the simulator and making sure that everything worked like a charm -- I just realized that there's a mismatch between my bundle ID in Xcode and my bundle ID on iTunes Connect. The former contains the word auto-populated word Baker and the latter does not.  

Thanks!

**Comment by Simbul** [comment]
That word is the name of your target. You could change it by changing the target name in XCode (although I don't think you can remove it altogether).

**Comment by kvirella** [comment]
Oh, I see. Well, I've run into this dilemma. XCode registers my bundle ID as including the auto-populated word Baker. So it's telling me that I can't use my provisioning profile on this application because my provisioning profile is applied to my actual bundle ID, which excludes the word Baker. Guess it's time to create a new bundle ID that does include the word Baker?

**Comment by nin9creative** [comment]
You can change the bundle id in XCode and delete the baker part...  Just go to the Info tab after clicking on target.  Double click in the box and change it to whatever you want.   

By default it uses the Product Name as the trailing part of the bundle id...  com.yourcompany.${PRODUCT_NAME:rfc1034identifier}

So either that or just change the target name like @Simbul mentioned.

![Xcode](https://f.cloud.github.com/assets/449883/428139/c6d41508-adfb-11e2-9d7f-2709d98b98fe.png)

**Comment by folletto** [comment]
To be more clear: _don't_ use Baker in the Bundle ID. At all. That's just a default we put, you have to user your own. ;)

**Comment by nin9creative** [comment]
Or that :)

**Comment by kvirella** [comment]
Thanks, all! @nin9creative solved the problem. I was trying to change the bundle ID in the summary tab. Not the info tab. When I switched to the info tab and bundle ID field, I realized that the word Baker was auto-populating through a variable that was appended to the end of the bundle ID. Hope this helps all other Xcode newbies.

**Comment by folletto** [comment]
Great! :)
