### ISSUE TITLE
Need help renaming the Nav Bar from "BAKER SHELF"

### ISSUE THREAD

**Issue by jervenstar** [Simbul/baker#845]
Does anyone know what part in XCODE I need to edit to replace this? I cannot seem to find it. As well as resizing the COVER IMAGE. It is stretching my publication icon to fit a standard size

**Comment by folletto** [comment]
All the text is inside `Baker/en.lproj/Localizable.strings`, the title is the very first one of that file. :)

**Comment by jervenstar** [comment]
Thanks Folletto. I saw it was already resolved. 
Does anyone know how to make the Issue Cover fit the image size instead of stretching it to conform to a portrait size cover?

**Comment by folletto** [comment]
That's currently unsupported, sorry. :)

I'm closing this issue since it's solved. Thanks! :D
