### ISSUE TITLE
Pb with videos in HTML5 and scripts in the app view

### ISSUE THREAD

**Issue by jmminy** [Simbul/baker#847]
Hi, as per my previous requests, i went trough a massive debug and testing before writting. I also followed the steps in the wiki pages and double-checked all the options in my book.json which is fine, working, valid and passed the lint test.

Here is my problem, I'm using Baker + Laker framework in standalone mode (using the master version you asked me to download about three weeks ago) everything is perfect except a little point i try to figure out:

Embedding videos in html5 using the video tag works, either for local or external videos in the app generated and in the browser of course. 

My issue is when I try to insert a video using an iframe. I tried different options like inserting the video in a page with no js at all or using the referrer=Baker or Safari links-->like that, it works perfectly but it's not what i try to achieve. Trying to load the video right inside the book just display a black box saying : 

media_err_src_not_supported The video could not be loaded , either network failed or because the format is not supported

Of course i'm connected to the internet (tried wifi and 3G) and the file is correctly encoded as opening the book page in Safari from the iPad works. Opening the book normally in the app using the Simulator works too. After seeing that i also formatted my iPad to make sure there is no cache somewhere. same behavior. Searching on Github, i did not find similar issues but few other video problems recommending to disable the user-agent in the appdelegate (actually this allowed me to get the video being read in the simulator as it was not working before) this did not fix the issue on the iPad.

I'm using the latest version of Xcode and i'm exporting for 5.0 or 6.1 (same). Here is my iframe code for the video so you can test it within your app or from an iOS browser: 

``` html
<iframe width='512' height='288' frameborder='0' marginheight ='0' marginwidth='0' scrolling ='no' src='http://player.ina.fr/player/embed/CAB8401384401/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/512/288/0/148db8'></iframe>
```

I also tried it like that:

``` html
<iframe width='512' height='288' frameborder='0' marginheight ='0' marginwidth='0' scrolling ='no' src="http://player.ina.fr/player/embed/CAB8401384401/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/512/288/0/148db8"></iframe>
```

Here is a piece of the debug log, not sure it helps:

```
2013-04-26 18:40:21.346 mand2604-16[539:907] • Page did start load
dlsym(0x1f89c341, BP_CreatePluginMIMETypesPreferences)
2013-04-26 18:40:21.528 mand2604-16[539:907] • Should webView load the page ?
2013-04-26 18:40:21.530 mand2604-16[539:907]     Page is current page and current page IS NOT delaying loading --> handle clicked link: http://player.ina.fr/player/embed/CCAB8401384401/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/512/288/0/148db8
2013-04-26 18:40:21.532 mand2604-16[539:907]     Opening absolute URL: http://player.ina.fr/player/embed/CAB8401384401/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/512/288/0/148db8
2013-04-26 18:40:21.534 mand2604-16[539:907]     Link doesn't contain param "referrer=Safari" --> open link in page
2013-04-26 18:40:21.538 mand2604-16[539:907] • Page did start load
dlsym(0x1f89c341, BP_CreatePluginMIMETypesPreferences)
2013-04-26 18:40:23.973 mand2604-16[539:907] • Page did finish load
2013-04-26 18:40:23.976 mand2604-16[539:907] • Setting current page height from 4652 to 934.000000
2013-04-26 18:40:23.980 mand2604-16[539:907] • Taking screenshot of page 6
```

I did try to switch to three-cards mode but had the same behavior. I really need your help as as soon as this is fixed, i'll be able to add my video intro and submit my app :)

Thanks in advance for your help. I can send you a private zip of my book folder if required and easier.
Cheers,

**Comment by folletto** [comment]
Could you please try downloading the latest version of Baker from master, the most recent one first? It might not solve anything, but you know... maybe... ;)

**Comment by jmminy** [comment]
Hi Foletto, I did a try with the latest version, downloaded 5 seconds ago. Same story the only difference is that I only have 2 issues after exporting with Xcode but my problem is still there unfortunately :)

**Comment by folletto** [comment]
My guess would be that the player used there does some kind of user-agent sniffing to provide the video and Baker has its own. You might try to change the user-agent to the one of some browser and see what happens.

**Comment by jmminy** [comment]
Thanks.
Can you tell me how to modify this to meet our needs and test (i'm lost):

// Set user agent (the only problem is that we can't modify the User-Agent later in the program)
    // We use a more browser-like User-Agent in order to allow browser detection scripts to run (like Tumult Hype).
   NSDictionary *userAgent = [[NSDictionary alloc] initWithObjectsAndKeys:@"Mozilla/5.0 (compatible; BakerFramework) AppleWebKit/533.00+ (KHTML, like Gecko) Mobile", @"UserAgent", nil];
    [[NSUserDefaults standardUserDefaults] registerDefaults:userAgent];
    [userAgent release];

**Comment by folletto** [comment]
Just change it with another user-agent string (the part inside `@""` that starts with "Mozilla..." and ends with "...Mobile"). I don't know what could work to meet your needs, you just have to try another string.

**Comment by Simbul** [comment]
@jmminy did that work as a solution?

**Comment by jmminy** [comment]
Nope but i solved my pb using standard html5 video tag. There is definitely something with user-agent detection on the remote video or within the app as trying the same page (even on the emulator) on a mobile safari, works
