### ISSUE TITLE
Set to launch Baker Framework Magazine... Only confusion is - Can BakerFramework offer In-App Purchases and Subscriptions through newsstand? 

### ISSUE THREAD

**Issue by jervenstar** [Simbul/baker#849]
Has anyone done this? We've set up the in-app per issue purchase on iTunes Connect and also the yearly subscriptions - Implementing this within baker is where I am lost. I cannot find any documentation to walk us through. Please advise.

PS I do not want to handle the server for the purchases - I want AppStore / iTunesConnect to do that. I do not care that they take 30% of the purchases.

**Comment by folletto** [comment]
The next version, 4.1, will do that, it's currently in development in the master branch, but almost ready for release. :)

However, you must have a server to handle the issues, you can't do that just through iTunes Connect.

**Comment by jervenstar** [comment]
Great. One follow up question... Can we implement a free one for now and switch to this after it is released? I am excited about this and cannot wait to pay you guys for your hard work.

**Comment by nin9creative** [comment]
If you want to implement paid now, you could use MagRocket as the server component...

**Comment by folletto** [comment]
Yes of course. :)

And as @nin9creative, there's MagRocket if you want to support paid issues. ;)

**Comment by Simbul** [comment]
@jervenstar you can also have a sneak peek at the [In-App Purchase tutorial](https://github.com/Simbul/baker/wiki/In-App-Purchase-tutorial) ;)

**Comment by nin9creative** [comment]
There is a screencast that I uploaded related to MagRocket setup if you want to check it out.  Not saying it's the best ever but gives you a good front to end picture of how it all works....  :)

http://www.youtube.com/watch?v=DKpaJ486Zyo
