### ISSUE TITLE
Looking to chat with amazing HTML5/CSS Magazine developers...

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#850]
I have a few things that I would like to chat with (offline) regarding HTML5/CSS...  Have some ideas I want to go over with a few folks that have great design skills, HTML5/CSS wizardry and vision...

andrew@magrocket.com or andrew@nin9creative.com

Baker team, please feel free to categorize this issue as you see fit.  I didn't know how else to post something like this to have people see it :)

**Comment by Simbul** [comment]
Hopefully you were able to find someone. If you want more reach, post a tweet and we'll retweet it ;)

**Comment by thejoepeach** [comment]
Find me at thejoepeach@gmail.com
