### ISSUE TITLE
Free Subscription

### ISSUE THREAD

**Issue by nayanseth** [Simbul/baker#851]
I added an Free subscription in my iTunes Connect. Then in the Constants.h in Baker Shelf folder, I added the Free Subscription Product ID as com.example.ProjectName, ProductID

Where example is company name, Project Name refers to the XCODE Project Name and ProductId refers to the free subscription Product ID.

I also created a test user. I then Signed Out of my personal Apple ID on my iPad.

Then i ran the build on my iPad. I got the subscribe button but when i clicked on it, it asked for confirmation which i accepted but then it gave Subscription Failure.

How do i overcome this issue?

![photo](https://f.cloud.github.com/assets/3462785/435180/22c426da-afac-11e2-8acc-0185b87942e5.PNG)

**Comment by ask91** [comment]
issue #800

**Comment by folletto** [comment]
Check the thread as @ask91 told you. :)
In general, please read through the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page and report back. :)

**Comment by nayanseth** [comment]
@ask91 Can you explain me how did you overcome the "Subscription Failure" issue. Please tell the step by step process.

**Comment by ask91** [comment]
I re-do all the instruction in https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

make sure you follow CONFIGURE NEWSSTAND ON ITUNES CONNECT 
and CONFIGURE BAKER WITH NEWSSTAND AND SUBSCRIPTION :)

**Comment by Simbul** [comment]
@nayanseth have you solved this?
