### ISSUE TITLE
Page scroll like Adobe DPS

### ISSUE THREAD

**Issue by badstorm** [Simbul/baker#852]
Hi,
I used Baker to create my magazine newsstand app. Now I want to add a new feature. For some pages when I scroll down, I want that it scroll page for page like Adobe DPS.

I use iscroll for this and all works fine except the double tap and left/right scroll. 

I  think iscroll overlaps the default touch functions.

How I can restore the original touch function and leave only the up/down scroll iscroll function?

Thanks in advance.

Marco

**Comment by folletto** [comment]
May I ask why you aren't using the `-baker-vertical-pagination` (in the current version, 4.0) property or the `<meta>` property `paged` (in the upcoming version, 4.1)? There should be no need of extra libraries. :)

**Comment by badstorm** [comment]
Thanks a lot! You save me from a lot of time in writing code!!! I didn't read about this features!! :P

One thing: there is any simple way to hide the scrollbar?

Thanks 

Marco

**Comment by folletto** [comment]
What do you mean by scrollbar? :)

**Comment by badstorm** [comment]
When I scroll down the page I see on the right side of the ipad the scroll bar. I want to know if there is a way to hide it.

Thanks

**Comment by folletto** [comment]
While there might be a way to disable it, we don't provide any way to disable it as it will be a problem for the users: they expect it.
