### ISSUE TITLE
How To Get From InDesign To Free Newsstand Subscription?

### ISSUE THREAD

**Issue by nicholasmartin** [Simbul/baker#853]
Hey all,

Sorry for bringing this up as I might be missing a clear part of the puzzle....

I would like to just get a magazine on my iPad to see it actually on there. I think this Baker framework sounds perfect for that, but I have no clue on how to get my hpub build through Baker and onto my iPad :(

What I want to achieve:
A test magazine onto my iPad in the newsstand.

What I got so far:
1) a Mac
2) Xcode installed
3) iOS developer account
4) Adobe InDesign
5) in5 addon
6) a packaged hpub (zip)
7) no idea what to do next for newsstand (not standalone)

I was thinking I had to build the hpub in xcode via Baker so I could submit it to my iOS developer account? I have used my dev account to push a Unity3D game onto my iPhone which worked great. I just don't know how to create a new app for the magazine now?

Really sorry if this is too far out of context and would appreciate links or pointers in the right direction - thanks!

**Comment by folletto** [comment]
I guess you can start from the tutorials: https://github.com/Simbul/baker/wiki/Newsstand-vs-Standalone-publications-in-Baker-4.0 :)

**Comment by nicholasmartin** [comment]
Yeah I've been going over these tutorials all day long :)

I think I get stuck because I don't have access to iTunes Connect (I'm a developer on another agents developer account). I just signed up for my own account and once I get access, I should be able to setup everything following that guide.

Sorry for the rushed support request and I'll follow up here and close the submission when I get further :)

Thanks for the SWIFT reply tho!

**Comment by folletto** [comment]
You're welcome. :)

**Comment by nicholasmartin** [comment]
Okay the tutorial is good!!!! There is a lof of setup to do on the apple side, but I guess once we've done it a couple of times it becomes a lot easier :)
