### ISSUE TITLE
Changing pages by sliding up and down

### ISSUE THREAD

**Issue by JosephMacReady** [Simbul/baker#855]
Hey guys, great job, thanks!  
Any ideas on how could I make the HPub scheme change pages when the user is sliding up and down too, like; 

```
(Item A) <-> (Item B) 
   A           A
   I           I
   V           V
(Item C)     (Item C)    
```

"A
 I
 V "    being an arrow, such as <->, sorry I can't draw in here 

?

Thank You!

**Comment by aspek** [comment]
``` html
<div class ="column1">
    <div class="scroll"> 
         <div class="itema">What ever </div>
         <div class="itemb">What ever </div>
    </div> 
</div> 
<div class ="column2">
       <div class="itemc">What ever </div>
</div> 
```

Something like this?

**Comment by JosephMacReady** [comment]
Thanks for the idea but what I meant was that 
up and down should change between specific HTML pages too, just like left and right do, any ideas?

**Comment by aspek** [comment]
I think this is impossible. But you can adapt such as duplicate itemC on itemA and itemB
and use this.
`-baker-vertical-pagination : true,`
 `<meta name="paged" content="YES">` inside the `<head>`

**Comment by JosephMacReady** [comment]
Hmm 
The way I see it, the left-right sliding concept is defined somewhere in the code and so it could be copied and adapted for up-down too, right?

**Comment by aspek** [comment]
Oh, Did you mean new feature or adapt "baker" for this operation?
So sorry, I saw "Support" on the header. I can't help.

**Comment by folletto** [comment]
@ValKalinic unfortunately the left-right behaviour and the page behaviours are managed by native iOS components (`UIWebView` and `UIScrollView`) so there's no explicit code that does that. The change you are asking is actually quite massive.

You might try to replicate the left-right logic also for up-down scrolling using again another `UIScrollView` or some listener, but I wouldn't really know where to start.

May I ask why are you trying to do that?

**Comment by JosephMacReady** [comment]
@aspek sorry, not able to find a way to change that tag :/ 
@folletto thank you! 

well I had an idea for a publication that is in more subjects, so if you slide left-right, you change the pages as usual, but sliding up-down would change the dossier/chapter/article 
maybe I should do the up-down sliding through html itself, any ideas on that?

**Comment by folletto** [comment]
@aspek It's tagged Support because it's a thread to support him, not a feature request. :)

@ValKalinic that's what was suggested above by @aspek, you can use one of these two commands and then build the individual HTML files in vertical paged chunks. :)

**Comment by JosephMacReady** [comment]
Thank you! I'll try and post results!

**Comment by Simbul** [comment]
@ValKalinic any results? ;)

**Comment by JosephMacReady** [comment]
So; 
-Vertical scrolling can be enabled in the Baker definition list file, replacing the horizontal way so we could change the first aspect easily, but the horizontal in-story page changes are here still unsolved; 
they could be done by modding the WebView and Baker scrolling but the easiest would be modifying a slideshow-like element (as the one available the Laker Compendium), but that way it isn't as fluid as the native WebView scrolling 
I personally moved away from this approach as even though it partly resembles analog book paging, it feels like a slideshow and very unfamiliar

**Comment by Simbul** [comment]
Sounds sensible. I'm closing the thread then.
