### ISSUE TITLE
Binary Cannot Be Uploaded

### ISSUE THREAD

**Issue by schamas** [Simbul/baker#858]
Hi there, 
my newsstand app works fine. i tested on iPad. It's all okay 
But, 
while i try to upload binary it's fail and message;
Binary Cannot Be Uploaded
To submit a Newsstand app, you must offer at least one auto-renewable or free In-App Purchase subscription. To set one up, click Manage In-App Purchases on the App Summary page. 

But i made it newsstand app and my in application purchases shown as Free subscription 
And i add issue as free too. 
I stuck there. 
Do somebody know why?

**Comment by schamas** [comment]
Problem Solved and my newsstand app waiting for review.. Thanks

**Comment by folletto** [comment]
Hello!

Could you please detail how you solved the problem? Might turn useful to others as well. :)

**Comment by schamas** [comment]
I created the free subscription from In application purchase page, after that i missed the thick the radio button which indicates the free subscription. 
It was Application details page. You can see it below 
Now i solved the problem and Uploaded the binary... 

:) Thanks you all David, You are THE KING 

![ekran resmi 2013-04-30 14 31 20](https://f.cloud.github.com/assets/1557807/443735/320d38c2-b18a-11e2-80c1-4ed64d964c8e.png)

**Comment by folletto** [comment]
That's great, thank you. :)
