### ISSUE TITLE
No response to gestures zoomify HTML

### ISSUE THREAD

**Issue by fobetor** [Simbul/baker#859]
Hello,
 Im a begginer, and i cant find why i cant make the zoomify.com html viewer work in a page inside baker . I've tested it in ipad/ iphone with safari and it works. 
 I tested it with ADVNewsstandtemplate which uses bakers and it works.
 Any idea that can help me implement this javascript html inside baker?
Thank you 
Fernando

**Comment by fobetor** [comment]
Ah, my scuses.. What happens is that the page inside baker does not recognize touch or gestures events for the DIV that uses the javacript
Thank you

**Comment by fobetor** [comment]
One more detail about testing.. I have tested with phonegap too and it works correctly...

**Comment by fobetor** [comment]
Well... hard investigating for a novice like me... BUT here is the solution for the problem with gestures & other javascript libraries...
in the `appDelegate.m` file, the line 

```
NSDictionary *userAgent = [[NSDictionary alloc] initWithObjectsAndKeys:@"Mozilla/5.0 (compatible; BakerFramework) AppleWebKit/533.00+ (KHTML, like Gecko) Mobile", @"UserAgent", nil];
```

Makes that some javascript dont work...¿Why? I dont know... but if you "remove/comment" it, everyhthing works fine...
 Any help about the implications this may have?
Thank You
Fernando

**Comment by folletto** [comment]
The reason for that is unfortunately simple: there are javascript libraries doing a really bad thing: they check the user-agent to choose if enable themselves or not. And since Baker uses that user-agent to identify itself as it should, the library mismatches and doesn't run, even if it should.

**Comment by fobetor** [comment]
Yes, I undestand what you say... but... in my case... its the inverse reason ... bufs... Or... my javascript is checking for a user agent not in the list?... this may be the reason? 
How to make a useragent list that covers all possibilities?

**Comment by folletto** [comment]
That user agent is "different" from either Safari, Mobile Safari, WebKit, Firefox, Opera, Chrome, Exporer and so on. For that reason, certain libraries don't "get" the user-agent because Baker defines that, its own.
When you take away the string as you did before, the user-agent reverts to the WebKit default one. And certain libraries start working again. :)

Unfortunately it's not possible to do a general user-agent.

**Comment by fobetor** [comment]
Thank you folleto. 
I'll look for a complete list or... A wild card for this?

**Comment by folletto** [comment]
As I said it's not a matter of lists. They usually use regexps or things like that. They should _not_ use user-agent, but they do.

**Comment by Simbul** [comment]
@fobetor have you solved this in the end?

**Comment by fobetor** [comment]
Yes alessandro. I just commented out the lines  I mentioned in appdelegate.
Everithing works now correctly. I use other javascripts and they work fine too. 
Thank you
