### ISSUE TITLE
Index Navigation Bar

### ISSUE THREAD

**Issue by therabidbanana** [Simbul/baker#86]
Hey Baker Team, 

The index bar is looking great - I'm having a couple of issues with it though:
1. Doesn't take into account downloaded books. I don't know if this is by accident or design. I think it makes sense for the downloaded book to be able to update the index view as well, but I can see an argument for keeping the same index bar for "magazine issues" or something like that.
2. Every now and then rotating to landscape causes the navigation bar to get "stuck" on one side. Seems like it only happens on heavier pages where lots of content is reflowing. I've also had the navigation bar appear without any tap actions when rotating, on occasion - probably a related issue.

I'd be happy to look into these and fix them, if nobody else is working on it right now. :D

**Comment by Simbul** [comment]
No one is working on those issues yet, feel free to code away ;)

More specifically:
1. It's not been implemented or discussed yet, but it makes sense. Downloaded books should definitely be able to initialize a new index view.
2. It would be nice if you could post the steps to reproduce the issue.

Looking forward to your pull request :)

**Comment by therabidbanana** [comment]
The rotation issue actually looks like it originates from Baker's core - every now and then the resetScrollView function gets called before pageHeight and pageWidth are set to the correct values for the orientation, resulting in a landscape frame for portrait mode and a portrait frame for landscape mode. To get it to happen I had to keep rotating back and forth a lot. Hard to reproduce in a predictable manner, but since it's not directly related to the navigation bar I can open it as a separate issue. Fix for 1 in the pull request queue shortly.
