### ISSUE TITLE
How to change 'Baker Shelf' text

### ISSUE THREAD

**Issue by DrCrypt** [Simbul/baker#860]
Hi guys, I'm VERY new at Baker, and iOS development as a whole, but I've managed to get a prototype together for a Baker pub. One of my questions right now, though, is how to change the 'Baker Shelf' text that appears both at the top of the app next to the Subscribe button on the 'Shelf' screen, as well as how to change that text in the 'Baker Shelf' back button when you're actually in an issue. Can anyone walk me through it? Thanks so much in advance.

**Comment by folletto** [comment]
All the text that's easily editable is inside `Baker/en.lproj/Localizable.strings`, including the title you're looking for. It will change the back string as well. :)

**Comment by DrCrypt** [comment]
Thank you! That worked a charm.
