### ISSUE TITLE
Swipe between pages doesn't works over canvas 

### ISSUE THREAD

**Issue by albertora** [Simbul/baker#863]
Hi, 
I'm making an ebook with your framework and everything works fine, but I've a problem with swipe between pages when the page has a canvas. If I do swipe over the canvas the page doesn't change to the next or previous. 

Can someone help me?

Thank you

**Comment by qutehoot007** [comment]
Try this css property on your canvas:

```
pointer-events: none
```

**Comment by albertora** [comment]
Thank you so much this works!!

**Comment by folletto** [comment]
That's great! Thanks. :)
