### ISSUE TITLE
Three-cards affecting interactivity on pages

### ISSUE THREAD

**Issue by simantics** [Simbul/baker#864]
Hi there,

I have six pages with Hype HTML5 animations (CSS and Javascript based).  I have three-cards set as my rendering method.

I find that the animations do not start sometimes when using three-cards. There's a repeating pattern:

If cover (start page) is animated it works. The next two pages do not. The fourth page will work. 

If I start on page 2, that page will work, the next two pages do not, and the fifth page will work. Etc.

When the rendering mode left blank all the animations work.

Does anyone know how I might be able to solve this? I prefer the three-cards effect to loading between each page.

Thanks.

**Comment by folletto** [comment]
Have you tried to start the Hype animation when the window.focus event is fired? :)

**Comment by simantics** [comment]
I'm not sure how I would go about doing this. Any tips?

**Comment by folletto** [comment]
Just add an event listener on `window.focus` and start Hype when that event is fired. More info on the [wiki](https://github.com/Simbul/baker/wiki/Use-baker-javascript-events). :)

**Comment by simantics** [comment]
Hi, I'm incredibly new to JS but would it look something like this:

 <script>

window.addEventListener("focus", function() { "type" : "HypeDocumentLoad" }, true);

</script>

I've read the wiki you've linked to, and here is Hype's Events tutorial. Could you let me know if I'm on the right track?
http://tumult.com/hype/documentation/javascript/

**Comment by thejoepeach** [comment]
Hi there, i run into the same issue with baker, three card rendering and a library for touch events called Zepto.... 

on normal mode it work without any incident but after add that render mode, the animations dont run or run very slow... also one script that works with the acelerometers stop responding son maybe its something more deep...

Also all the afected pages feature the focus event so no idea how we can fix this...

**Comment by folletto** [comment]
I can just advise to go back to the standard screenshot mode, maybe tweaking the loading page. It's very difficult to work out these bugs because they are likely internal to the `UIWebView`, and that's full in Apple's control and a real black box for us.
