### ISSUE TITLE
Issue not appearing on the Newsstand app

### ISSUE THREAD

**Issue by pattypatpat** [Simbul/baker#865]
Hi there,

I'm quite new to coding especially with xcode so Baker was a great tool to use - I followed the Standard App guide and everything worked perfectly. I am now attempting the Newsstand Free Issues guide and after following everything (several times), I run the simulator and while the app appears on the Newstand shelves, when I open it I get the blank screen with Baker logo. There are no glaring errors I can see on Xcode so I'm not sure what I'm doing wrong. I've got the correct hpub file (no zip extension) along with the cover and shelf.json on the webserver but I've obviously missed/overlooked something as no issues appear on the app. 

Here are the three uploads to the server:
http://sportreadr.com/wp-admin/shelf.json
http://sportreadr.com/wp-admin/issue.hpub
http://sportreadr.com/wp-admin/cover.png

What else can I provide you with to help you see where I might have made a mistake?

Thanks so much!

Ps. This is the tutorial I've followed: https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand
I noticed that quite a few people having problems were using old guides so I made sure I was at least on the right track.

**Comment by folletto** [comment]
The simplest advice would be start entirely from scratch. Re-do the tutorial from the very beginning assuming you don't have anything ready.

(for example, if you do that now, you'll probably notice when you reach the validation of your `shelf.json` that it doesn't validate...).

Also, check the page [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging).

**Comment by pattypatpat** [comment]
Thanks for the quick response! I started from scratch each of the 3 times, happy to give it a go again. The Json issue must have happened when I took away the Product ID. Let you know how I go after a full try.

**Comment by pattypatpat** [comment]
Before I do start from scratch, just a quick note - the first two times this was the code that stopped the simulation:

@autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }

I don't quite know what to do here.

**Comment by folletto** [comment]
It stopped likely to some other reason. Always check the console log. :)

**Comment by pattypatpat** [comment]
Thanks - I definitely I wish I was more knowledgable in this area. I'll get into it again tomorrow, thanks for your help so far :)

**Comment by nin9creative** [comment]
If those are the actual files you are trying to use, they don't load when I click the links you have above.  Baker probably can't load them either...  Unless you already moved them somewhere else?

**Comment by pattypatpat** [comment]
That's odd as I haven't moved them. I can open them from the links, they don't load on Baker though (probably a mistake on my part as stated above). I haven't tried it all from scratch again.

**Comment by pattypatpat** [comment]
I tried the process from start to finish, as best as I could. The simulator loads then stops at an empty page with no issues showing within the newsstand app. These are the errors that come up - any advice here - I'm sorry I'm so bad at this.
![screen shot 2013-05-05 at 9 27 08 pm](https://f.cloud.github.com/assets/4339703/463556/1574bffa-b577-11e2-83e9-7888502c58c6.png)

**Comment by pattypatpat** [comment]
OMG got it!

I was missing the "[" and "]" in the shelf.json file, used your test files to find the issue. Thanks for all the help so far, you guys are champions. So relieved that it's working.
