### ISSUE TITLE
Magazine can't be downloaded

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#867]
Hello, my application was rejected at this time because Apple told me that
any magazine can't be downloaded , when you click on one, you only have the circle and no progress !!!
There is a way, something to check or that I've forgotten to solve this problem ? 

In simulator everything works in any device, on my Iphone it works too but you've to wait more time before the download starts, each magazine weighs on average 200Mo !!!

Thanks ;)

**Comment by Simbul** [comment]
When you're downloading on the real device, do you see the progress bar during download or is it just shown for a split second at the end?

To display the bar, Baker needs the server to provide the total size of the file that's being downloaded. Most servers return that information, but some don't, which results in the progress bar not being displayed.

**Comment by kodjoe** [comment]
I can see the progressbar, all works when you click on download with the simulator and on my devices (iphone or ipad) and with each version, so that's why honnestly I don't understand why they rejected my app.

According to them "when you click on download nothing happens" but not for me. I've any idea so before to resend it I just reinitialized my application on the simulator and reinstalled it on my devices. At this time all is working for me and hope for them too lol

**Comment by Chrissmen** [comment]
i have the same issue, how we can get the file size from the server? permissions? Plataform? in the simulator run ok but in device just show the progress bar and never have download progress

**Comment by Simbul** [comment]
Based on my tests, your server should return a `Content-Length:` header containing the size of the HPUB file in bytes.

**Comment by folletto** [comment]
Hello! Were you able to solve this? :)

**Comment by mensch** [comment]
I have the same problem. Tried it on three servers, two just showed the download progress track without the progress bar as per the first reply to this issue. On one server everything worked as expected, unfortunately this machine can only be used a test server.

The `Content-Length` seems to be returned by the faulty servers. Is there a way to circumvent or solve this problem?

The `curl -sv` result of from the faulty one:

```
> GET /magazine-04.hpub HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
> Host: testserver01.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 05 Jun 2013 08:56:05 GMT
< Server: Apache/2
< Last-Modified: Wed, 05 Jun 2013 08:55:07 GMT
< ETag: "b800ad-2166b23-4de645ab8d0c0"
< Accept-Ranges: bytes
< Content-Length: 35023651
< Vary: Accept-Encoding,User-Agent
< Content-Type: text/plain
```

And the one that worked:

```
> GET /magazine-04.hpub HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
> Host: testserver02.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 05 Jun 2013 08:26:22 GMT
< Server: Apache/2.2.0 (Fedora)
< Last-Modified: Wed, 05 Jun 2013 08:24:32 GMT
< ETag: "1077841d-2166b23-4de63ed58f000"
< Accept-Ranges: bytes
< Content-Length: 35023651
< X-Powered-By: PleskLin
< Content-Type: text/plain
```

I also tried a fresh, bleeding edge copy of the framework from Git, but the problem persists.

**Comment by fcontreras** [comment]
If you are not using the latest version, might be related to the data parsing.
It causes the download never to start but it shows the waiting icon.

See https://github.com/Simbul/baker/issues/630?source=cc

**Comment by folletto** [comment]
I'm closing this issue since it's a bit tool old.
