### ISSUE TITLE
Subscription failure

### ISSUE THREAD

**Issue by simantics** [Simbul/baker#868]
Hi All,

Very close to having a real working app in the store. Just got a message back from Apple that my first submission was rejected because the subscription button wasn't working.

My app is called Aucklandia and has a free subscription – the product ID I've created is called 'freesub1'. In the Constants.h file I've put  'com.aucklandia.Aucklandia.freesub1'. Is this the correct syntax? In the example wiki it says it should be 'com.aucklandia.Aucklandia.subscriptions.freesub1' but this doesn't work either.

Cheers for your help!

**Comment by damenvaz31** [comment]
Same here. The subscription appears to work on scode demo but when I test it on iPad i have a subsctiption error. Also rejected from apple. Any help would be appreciated.

**Comment by simantics** [comment]
Ok I've fixed it on my end – the name I used for the product ID for Free Subscription was incorrect. I put in 'freesub1' in iTunes connect , when it really should have been written out fully 'com.aucklandia.Aucklandia.freesub1.freesub1'. 

You should also create a test user in iTunes Connect -> User Management

Make sure you clear the settings in your simulator after all this before you test again. To do this go to iOS Simulator --> Clear all settings (or something like this) . Then build your simulation again.

**Comment by Simbul** [comment]
@damenvaz31 I am about to close the issue. Have you solved your problem as well?

**Comment by damenvaz31** [comment]
Hi @Simbul sadly I´m still with the problem. My test on the ipad simulator works great but when i try to test the same issue on my real iPad it gives me the suscription error. Any suggestios? I follow the instructions on the tutorial so i don´t know wher i¨m wrong.

Thanks!

**Comment by Simbul** [comment]
Can you follow the instructions in https://github.com/Simbul/baker/wiki/Problems-and-Debugging ?

**Comment by damenvaz31** [comment]
Ok. I will do it and let you know. Thanks!

**Comment by damenvaz31** [comment]
i just made all the recommendations but i´m having still the problem. On the simulator suscription works great!! But unfortunately on the iPad doesn´t work and send me a Suscription Error. Any ideas? Thanks a lot.

**Comment by Simbul** [comment]
The page I linked to has a list of what you need to provide to submit a report (mainly version, steps and log). Without that information, there's not much we can do ;)

**Comment by DrCrypt** [comment]
damenvas31, I'm no technical expert at all, but a few days ago, I had an issue where something ran great on simulator and then didn't on iPad. It turned out that the iPad is case sensitive where the simulator is not. Maybe check your Product ID and make absolutely sure the cases are correct?

**Comment by Simbul** [comment]
I'm closing this as there's been no feedback. Please reopen if needed.

**Comment by jbavington** [comment]
I am also having this issue.  I've compared the Subscription Product ID in iTunes with what I have in the Xcode Constants.h and they are both the same.  ( Product ID ca.rb.aboutcanada.baker.subscriptions.1year )

![subscription product id -- itunes](https://f.cloud.github.com/assets/4700969/750601/c8a74cc0-e4d2-11e2-92b5-05d0b7411e57.png)

![subscription product id -- xcode](https://f.cloud.github.com/assets/4700969/750603/ccfcbb02-e4d2-11e2-823c-3c2f645b9813.png)

I still see the "Subscription Failure" popup, both in the simulator and when testing on my device.

Xcode log is saying:

2013-07-04 13:57:32.209 Baker[2942:15b03] Trying to buy unavailable product ca.rb.aboutcanada.baker.subscriptions.1year
2013-07-04 13:57:32.211 Baker[2942:15b03] ############ UPDATED TRANSACTIONS (
    "SKPaymentTransaction: 0x86988e0"
)
2013-07-04 13:58:07.288 Baker[2942:15b03] ############ UPDATED TRANSACTIONS (
    "SKPaymentTransaction: 0x86988e0"
)
2013-07-04 13:58:07.289 Baker[2942:15b03] Payment transaction failure: Error Domain=SSServerErrorDomain Code=5002 "An unknown error has occurred" UserInfo=0x81a8de0 {NSLocalizedDescription=An unknown error has occurred}

Please let me know what I missed, thanks.

**Comment by nin9creative** [comment]
Needs to match whatever you setup in iTunes connect....
