### ISSUE TITLE
transition pages and title bar css

### ISSUE THREAD

**Issue by petesavva** [Simbul/baker#869]
hi guys,
first of all, excellent job on baker!
i'm trying to change the css for the title bar (after double tap) and also the css for the transition pages (page title)
can anyone point me in the right direction please?
thanks

**Comment by folletto** [comment]
I'm not sure what you're asking... Trying to guess:
1. The title bar is the only thing native, there's no CSS. It's standard iOS. You can just change the name from the `Localizable.strings` file.
2. What do you mean by transition pages?

**Comment by petesavva** [comment]
I managed to change the font color for the transition pages thru:
bakerviewcontroller.m and pagetitlelabel.m

all i need is to change the font and color of the title bar. could you point me to the .m file that builds the navbar or toolbar please? thanks

**Comment by folletto** [comment]
Actually, you could have done that just by using a proper `book.json`, without having need to touch the code. Read more here: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters

Plus, there are additional parameters you can find in `UIConstants.h`.

For the toolbar, just change the images: `navigation-bar-bg.png` and its retina counterpart.

For the font of the navigation bar instead we don't provide a way to change it, you have to do it manually (check `AppDelegate.m`).

**Comment by petesavva** [comment]
You know what?i like this better!
