### ISSUE TITLE
JQuery content in Baker Framework doesn't work in iPAD 2 

### ISSUE THREAD

**Issue by ask91** [Simbul/baker#870]
i've produced Baker book for iPAD,
my app using Baker 4.0, under iOS 6
test the book with iOS simulator,
test the book in real device iPAD 3 as standalone app,

everything works smooth, [not perfect but acceptable],.

So, i delivered the hpub as a Newsstand app, and download it from AppStore using iPAD 3,
most of JQuery interactivities inside it worked.

But when the app is downloaded to iPAD 2
Most of interactivity using JQuery inside of the book misbehave. None of them works.
 Only interactivity using css3 that works fine.

Where is the incompatibility of my Book app?
is it because the JQuery with iPAD 2 and its iOS SDK?  or something to do with Baker and iPAD 2?

i'm sorry if here is wrong place to discussed it, 
but at least, i need Baker feedback from admin or anyone else that know  where i should head for this issue

thank you

**Comment by folletto** [comment]
Is it the very same version of iOS? Because Baker uses Apple's WebKit (UIWebView) and that behaviour difference is likely due to a version difference. Also: you tried the same page in the same device / iOS version in Mobile Safari?

**Comment by ask91** [comment]
yes, the iPAD 2 and iPAD 3 using the same version of iOS 6.0.1.

i haven't test the page in Mobile Safari though,
so i'll report for further information while clean checking and test the app again.

i wonder if it's normal for app to act differently when in simulator, in standalone, and in real store,.?

**Comment by ask91** [comment]
anyway, Baker becomes more and more awesome with the 4.1 release :) thanks to the teams n contributors

**Comment by yujulio** [comment]
Could it be the screen resolution? iPad2 has a 1024x768 screen resolution
and the iPad3 has 2048x1536.

2013/5/8 ask91 notifications@github.com

**Comment by Simbul** [comment]
@ask91 any news on this?
