### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by JosephMacReady** [Simbul/baker#871]
Hey, 
Do you have some ideas on how I could add the ability for the readers to leave comments on hpub/html magazine articles? 
Thanks! :)

**Comment by petesavva** [comment]
http://coding.smashingmagazine.com/2012/05/09/building-real-time-commenting-system/

**Comment by folletto** [comment]
Hello I'm closing this since the discussion seems stopped. Reopen this if needed. :)
