### ISSUE TITLE
Can the standalone version be updated the same way a newsstand app is?

### ISSUE THREAD

**Issue by benjamincano** [Simbul/baker#872]
My app got rejected by the AppStore because they say it's a a catalog not a magazine, my solution is to create a standalone version but I was wondering if it can be updated with hpub files the same way a newsstand version works?

**Comment by folletto** [comment]
If you mean by downloading new issues, unfortunately the answer is no. The download system currently in Baker uses heavily Newsstand (to support validation and background downloads) and as such can't be used in Standalone mode.
To update, you have to update the app through iTunes Connect as you would do by updating a normal app.

**Comment by benjamincano** [comment]
I imagined, it's upsetting that Apple its not that helpful. 

I might not be the only one who encounter the problem, and the answer is built and app that emulated the newsstand but its outside the newsstand. Maybe I am not the only one that encounter this and can think of something for the magazines that dont get approved.

**Comment by folletto** [comment]
The ideal scenario would be to make an alternative system that download issues but isn't tied in Newsstand. Unfortunately right now it would be a massive rewrite, but actually it was one of the most difficult decisions we had to make... I hear you.

**Comment by benoitchantre** [comment]
This feature is tracked here #644

**Comment by folletto** [comment]
Good post. ;)
Closing this. :)
