### ISSUE TITLE
popover images

### ISSUE THREAD

**Issue by petesavva** [Simbul/baker#873]
can someone point me in the right direction please?
i'd like to add popover images in my book and need to be pointed the right way....

**Comment by folletto** [comment]
Just do it as you would do on the web. You can write your own javascript to do it, or use some library, like Lightbox-like ones. :)

**Comment by petesavva** [comment]
i've tried multiple examples but they don't work.......

**Comment by thejoepeach** [comment]
Hi there, if you check my magazzine here, i did something like that....

https://itunes.apple.com/us/app/udf-geekcast-magazzine-vol.0/id636810457

I use one simple library called lightbox, if needed i can post here the code that make it work....

**Comment by folletto** [comment]
As a reference, this is what you could use (should be tested first):
http://lokeshdhakar.com/projects/lightbox2/
http://fancybox.net/
http://leandrovieira.com/projects/jquery/lightbox/

I'm closing this. :)
