### ISSUE TITLE
Stupid Question - Will I only need 1 App ID for my magazine?

### ISSUE THREAD

**Issue by nicholasmartin** [Simbul/baker#875]
Hey all,

A little embarrassed to ask this but ..... will I need to setup a new app id everytime I create a new issue for my magazine, or can Itunes Connect manage this via the issues function?

It's a little unclear for me, and I would like to have it 100% clear for various naming conventions etc :) 

I'm hoping it's 1 App ID for every magazine and not issue :)

**Comment by Simbul** [comment]
The app ID (also called bundle ID) will only need to be setup once, when you create your app in iTunes Connect.
Each issue will have to have its own product ID, but the app ID stays the same.

**Comment by nicholasmartin** [comment]
Awesome thanks!
