### ISSUE TITLE
Missing Push Notification Entitlement - free subscription

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#879]
hi!
today i uploaded my free subscription magazine to itunes connect. i got this message and don´t know, if i can change anything there?

Dear developer,

We have discovered one or more issues with your recent delivery for "Kinderkrebshilfe". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

If you would like to update your binary for this app, you can reject this binary from the Binary Details page in iTunes Connect. Note that rejecting your binary will remove your app from the review queue and the review process will start over from the beginning when you resubmit your binary.

Regards,

The App Store team

**Comment by simantics** [comment]
Hi there,

If you aren't using push notifications in the app, then it will be fine. I recieved the same alert after  I uploaded my binary and it was approved without a hitch. 

The alert is only if you intend to use push notifications  – but most likely if you are using push, you would know which bits to edit.

Hope this helps.

Sim.

**Comment by hitchio** [comment]
ok-i see. thank you for informations.
str.
