### ISSUE TITLE
Help me !

### ISSUE THREAD

**Issue by sgkalyans** [Simbul/baker#880]
Hi there,

Please note that i'm not reporting any issue here.

I need a sample HTML file for iPhone book. Currently baker framework's HTML sample book is for iPad, so user have to scroll here and there to see the full content of the page. so can any one give me a sample HTML file for iPhone, that means HTML file that having correct width setting of iPhone.

Please help kindly help !

Thank you

**Comment by yujulio** [comment]
Take a look at this: http://www.lakercompendium.com/

2013/5/10 sgkalyans notifications@github.com

**Comment by sgkalyans** [comment]
Thank you :+1:
