### ISSUE TITLE
Screenshots and page caching

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#881]
Hello!

I'm going to release a magazine and using the screenshots,
when "turning" pages is the great option for me.
But it seems, that Baker in screenshot rendering mode _always shows the screenshots_
before the  actual page.
(my pages are just rendered PDFs in PNG files)

In "non-screenshots", default mode, I noticed, that after visiting a page,
next time it shows at once. (for example swipe forward and then backward).

Now, in screenshot rendering mode it looks like no pages was cached for me.

Where's my fault?

**Comment by folletto** [comment]
I'm not sure what you mean. Just to clarify to see if I got it correctly:
1. In screenshot mode, always shows the screenshot first and then swaps the page once it's ready: the result is usually that the user don't see any change and feels like a unique magazine
2. In three-cards mode pre-loads just the next and previous pages, creates a heavy load on the iPad and requires more time to actually load the adjacent pages, so if you skim or swipe too fast you see the page loading

**Comment by divlv** [comment]
Yes. This is correct and I understand this.
So I'll try to ask my question in the other way:

Is it possible, being on screenshot mode and visiting the page, say, second time
(load page, swipe forward and then swipe backward)
to see already cached (fully loaded) page?
Now I always see screenshot first, and then - page itself.

Or the described behavior is restricted for screenshot mode?
(quick show of previously loaded pages available only in three-cards mode)

**Comment by folletto** [comment]
I still see some confusion, maybe it's just in the terms... you say "already cached (fully loaded)" - if it's "cached" it's a "screenshot", and screenshots are all preloaded all the time after the first (and even the first if you pre-create them).

Instead, "cached" doesn't exist on three-cards mode, because three-cards always loads three pages and that's it. So you either get the page loaded or wait it to be loaded. No caching. Nothing.

If you see the "screenshot first and the page then"... there's something strange, because in the ideal scenarion you shouldn't be able, as a user, to tell the difference from the screenshot and the real page (given you don't scroll, of course).

**Comment by Simbul** [comment]
@Dinamitrij do you mean "caching" as in "load a page in a UIWebView so the screenshot is not needed anymore"?
If that's the case, it doesn't work that way: to keep memory usage to a sensible amount we are reusing the same UIWebView for multiple pages, so there's no "caching" at that level.

**Comment by divlv** [comment]
@folletto - regarding your last sentence: so, did you mean, that when we swipe pages and see the auto-generated screenshots (three-cards mode) these screenshots are hi resolution ones and that's why I unable _as a user, to tell the difference from the screenshot and the real page_ ?
Actually - my own pre-rendered screenshots are super-blurred ultra-compressed JPEGs, just to show matte preview of the page and then it changes to HiRes page itself. Maybe that's why I **can** see the difference...?

@Simbul - No. Actually, I'm not digging into source ObjectiveC code so deep ;-)

**Comment by folletto** [comment]
Precisely. If you use a low-res image, then the difference appears. :)

A clarification: _"see the auto-generated screenshots (three-cards mode)"_: three-cards mode **does not** use screenshots. It's just the HTML page, loaded, or not.

**Comment by divlv** [comment]
OK! Thank you! I got it, finally :-)

But, does it mean, that when we download our magazine on the device and swipe through the content,
occupied place by the application on the device grows up to 2 times, due to auto-generated screenshots?

In this case - less download amount, but it grows in future...
In screenshot mode - already download "increased" amount?

**Comment by folletto** [comment]
If you are running in `screenshots` mode, a screenshot for each page is generated and yes, it makes the application grow. If you provide these screenshots yourself however, nothing changes.
The screenshots are however stored in a way that's managed by the operating system and will be removed automatically if space is required.
