### ISSUE TITLE
iOS 5 compatibility?

### ISSUE THREAD

**Issue by surelynot** [Simbul/baker#882]
Hello all,

I'm having problems getting Baker 4.1 IAP to work in the sandbox under iOS 5 – I've attempted it using the 5.1 Simulator and on a real device running 5.1.1 (iPad 1). It fails everytime after Signing In (Use Existing Apple ID), giving an 'Unknown Error'.

Runs fine on the iOS 6.0 and 6.1 Simulators. I've also tested with both a simple shelf.json file and the dynamic Rocketmag setup, both setups work fine (purchases & subscriptions) in the iOS 6 simulators, neither works with the iOS 5 simulator or device.

Is anyone else having this issue? I am assuming Baker 4.1 is intended to be iOS 5 compatible – I double checked by searching the wiki and the Issues but didn't see anything contrary to this.

Cheers, Simon.

**Comment by bober80** [comment]
Yes I have the same issue with simulator it is not Baker issue it's apple's restrictions.

The quote from storekit docs:

Note: Store Kit does not operate in iOS Simulator. When running your application in iOS Simulator, Store Kit logs a warning if your application attempts to retrieve the payment queue. Testing the store must be done on actual devices.

http://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/StoreKitGuide/DevelopingwithStoreKit/DevelopingwithStoreKit.html

So you have to use the latest iOS simulator (6.1). I test Beker on iOS 6.1 iPad simulator and it works.

**Comment by surelynot** [comment]
Hi bober80,

thanks for the clarification – I assume that's also why it doesn't work on the iPad running iOS 5.1.1 – a bit stupid really given you can't actually update the first gen iPad to iOS 6, meaning you can't test the hardware in the sandbox!

Appreciate the input, cheers.
