### ISSUE TITLE
Application Approved by AppStore

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#883]
Thank you so much to all the team of baker project ;D Am so happy to tell you that my app is in Appstore ;)

Thank you to Folletto / Andrew / Allesandro for all your answers and Patience lol
https://itunes.apple.com/us/app/factice-magazine/id634867246?l=fr&ls=1&mt=8

**Comment by folletto** [comment]
That's great! You're welcome! :)

**Comment by kodjoe** [comment]
;D you're the best !!!!
I submitted my App on your website ;)
