### ISSUE TITLE
Ability to provide access to Issues via "Access Code" or subscriptions/purchases made outside Newsstand.

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#886]
With MagRocket I'm getting a lot of questions regarding a bunch of really good topics.  One of which is providing the ability to provide a method for users that have purchased subscriptions outside of Newsstand to "activate" those subscriptions within the Baker Application.  The other is to provide a method to give out promotional codes for single issues and or subscriptions.  The example given to me was giving a promo code to a publicist for an issue of a magazine that their client was in etc...

First, does anyone know if you can use iTunes Connect to generate a promo code for a Newsstand subscription?

**Comment by folletto** [comment]
I need to check with @Simbul, but I think it's already possible: the server just have to match the subscription or voucher with the user account and enable it when the shelf asks for the list of purchased products.

I think iTunes Connect doesn't manage subscription promo codes because the server will do that itself.

**Comment by nin9creative** [comment]
I was thinking about that.  The question is how to match the subscription/voucher with the user account.  Since the user account is basically the
generated device ID...

**Comment by Simbul** [comment]
The main issue is how to match the Baker user ID with the person that entered the voucher code.

A solution that requires some coding would be to have a "redeem code" form in Baker, which would then send both the code and the user ID to the server.
At this point, the server could check the validity of the code and unlock the relevant content for the given user.

A potential pitfall is persisting the information across reinstalls of an app, as the Baker user ID will change in that case.
Usually this is not an issue, because we can rely on the App Store to match a Baker user ID with the content purchased by the user (through the "restore purchases" function), but I can't think of an easy way of persisting voucher codes (unless of course they are somehow handled by the App Store, which I doubt).

**Comment by freney** [comment]
Just to clarify a point above: there is no way to create iTunes Connect promo codes for in-app purchases of any kind, including subscriptions.

**Comment by yujulio** [comment]
It could be using a external website where you can create a account and buy
issue in that page. When you use the baker you have to log in using the
account where you bought a issue so it can be downloaded and viewed.
Something like the kindle app.

2013/5/15 freney notifications@github.com

**Comment by MaverickWar** [comment]
so what is the status with this? Is this something which is being looked into this?

**Comment by nin9creative** [comment]
I haven't looked into it much yet.  Unfortunately I don't have as much time as I would like to spend on this as I have bills to pay :)

If people wanted to donate I could work faster...  LOL

**Comment by folletto** [comment]
I think we could use a very flexible solution that I actually used elsewhere with good success: if we add a button on the right-hand side of the toolbar that opens a dropdown with a UIWebView we can pass to that view the ID as a get string, and from there the server can decide what to do: register, authenticate or else.

The only detail one should pay attention is to avoid completely any kind of store inside that space, as Apple would surely deny approval.

This will solve also #913.

**Comment by nin9creative** [comment]
That actually sounds like a great idea.  Simple to implement on the Baker end.  With MagRocket, I could easily take the USER_ID passed and then write a small
PHP page to prompt for Access Code or whatever else and then make the connection.

It would also give others a hook for doing things that they might want to do.

Sounds like a good idea to me :)

**Comment by macsolving** [comment]
Assuming my client doesn't have a problem with it, I'll gladly contribute my baker login interface and the magrocket api modifications -- although you will _definitely_ want to clean them up - hope to have something functioning soon

**Comment by folletto** [comment]
That would be great. :)

If you want to contribute let's discuss it as early as possible so we can avoid double work on both sides. ;)

**Comment by macsolving** [comment]
Absolutely - I'll get back to you later tonight or tomorrow

**Comment by macsolving** [comment]
Hi guys -- my client wants me to finish up what I've got first, but she's willing to pass it on to you after she gets her hands on it.  As the modification is being commissioned it's pretty much her call - but when the time comes I'll be happy to explain its implementation if there is any question (but it will be pretty self explanatory I'm sure...)

**Comment by folletto** [comment]
Ok, let's see then after you made your client happy. ;)

**Comment by fturner19** [comment]
Has there been any other feedback regarding this topic???

**Comment by MaverickWar** [comment]
I would like to know this also please.

**Comment by Simbul** [comment]
We've implemented a minimum viable solution for this issue in b618d3e.

We've added an `init` [JS event](https://github.com/Simbul/baker/wiki/Use-baker-javascript-events) that passes in `user_id` and `app_id` every time the Info Box HTML page is loaded.

This means it's possible to implement a form inside the Info Box (e.g. for the user to provide a redeeming code) and then use Javascript to push the content of the form along with `user_id` and `app_id` to the server (e.g. MagRocket).

It is not a fancy implementation (and it needs the server to support it), but it allows for a barebones implementation of what was requested in this issue.

**Comment by Simbul** [comment]
Closing as this satisfies the requirements on the Baker side. Please open new issues for any further improvements.

**Comment by folletto** [comment]
Documentation on the wiki: https://github.com/Simbul/baker/wiki/Use-baker-javascript-events

**Comment by JamesMowatt** [comment]
Can I just confirm what happens when a user uninstalls and re-installs the app with regards this this function?

EDIT
Scratch that, I see how to use it. Thanks

**Comment by JamesMowatt** [comment]
How would I set a HTML form hidden field using the JS Event?

Thanks

**Comment by folletto** [comment]
As you would do on a HTML page. Check jQuery, CSS triggers and DOM manipulation in google. :)
