### ISSUE TITLE
Height of scrollable baker shelf area

### ISSUE THREAD

**Issue by codypallo** [Simbul/baker#887]
How high is the scrollable baker shelf area? I'm wondering how big to make my banner logo on the top of the shelf. I dont want the issues to scroll over it.

**Comment by freney** [comment]
The banner height between the menu bad and the top of the scrollable area is approx. 250px for the iPad, approx. 110px for iPhone (both 3.5 & 4.0 inch). Same height in landscape as in portrait mode.

**Comment by codypallo** [comment]
Great Thanks!
