### ISSUE TITLE
Changing orientation sometimes shows white strip?

### ISSUE THREAD

**Issue by johndryan** [Simbul/baker#89]
We've just finished creating a first version of a book with Baker 2.0. There seems to be a bug occurring intermittently when changing orientation - not constantly, but every now and again. It creates a white strip down the right hand side which remains until the orientation is changed again.

We changed the colour of `scrollView.backgroundColor` and this changed the colour of the strip - so I assume it's this that's showing up - if that helps!

I've uploaded a [screengrab](http://cl.ly/0a3d3H1d2v0g3A0l0k2D).

**Comment by therabidbanana** [comment]
I have encountered this issue as well - it seems to occur most frequently on pages with lots of content to resize (we use a lot of @media queries to handle rotation - and those a slow). It looks like `@selector(setPageSize:)` is getting called too early on occasion - setting the boundaries of  the screen to portrait boundaries when you've just rotated to landscape (and vice versa).

**Comment by therabidbanana** [comment]
I think I found and fixed the issue. I'm submitting a patch, but you can try the fix immediately by changing [[UIDevice currentDevice] orientation] to [self interfaceOrientation] in RootViewController.m on two lines.

orangesparkleball/baker@05377c2d92aa93911b912fb391b2f083d9029f6c

**Comment by jvmeding** [comment]
hey @therabidbanana I'm working on the project with @johndryan above, and I tested it with the change you suggested. Unfortunately, the problem is still there fyi

**Comment by therabidbanana** [comment]
Are you using javascript to handle orientation change resizing? I'm using CSS media queries, which the patch seems to fix for my test cases, but javascript events get called earlier and might still be getting the wrong size.

**Comment by johndryan** [comment]
Nope, we're using CSS Media Queries too - and on the page above there's only one image - so it's not like there's a lot of content involved?

Is there many people experiencing the same problems?

**Comment by therabidbanana** [comment]
Hmm... do you have a test hpub/book directory you can share? I'd be willing to take a look.

**Comment by Simbul** [comment]
I've merged the patch from therabidbanana and thus closed the issue.
Please let us know if you still get the problem. In that case, it would be good to have a list of detailed steps to reproduce the bug (a book that triggers it consistently, as suggested above, would be great).

**Comment by jvmeding** [comment]
therabidbanana- It must have been a weird test, because I re-tried the patch you suggested and now the bug is gone! You're a legend

**Comment by johndryan** [comment]
Thanks guys!

**Comment by k8fisher** [comment]
Can I ask what the changes were to the code? Apologies for asking cause Im using Baker 2 implementation of Laker and need to correct the problem in my own publication without switching to Baker 3.

Ive tried changing:

Change [[UIDevice currentDevice] orientation] to [self interfaceOrientation] in RootViewController.m on two lines
