### ISSUE TITLE
newsstand cover image size

### ISSUE THREAD

**Issue by lostinjapan** [Simbul/baker#890]
Sorry, I searched (honestly!) but I wasn't able to find an answer for this. What is the recommended size for issue cover images in newsstand?

Thanks in advance

**Comment by nfeiglin** [comment]
I think it's 512 x 1024 or 1024 x 512 depending on if your publication 
is a magazine or newspaper

**Comment by lostinjapan** [comment]
Thank you very much. I will try it  :+1:
