### ISSUE TITLE
reachability on standalone app

### ISSUE THREAD

**Issue by petesavva** [Simbul/baker#892]
i'd like to know how to setup a reachability alert on a standalone book that loads a url
thank you

**Comment by folletto** [comment]
Could you please describe better what are you trying to do?

**Comment by petesavva** [comment]
i have a chapter that loads (body onload) a url
i'd like to alert the user if there is no internet connection

**Comment by folletto** [comment]
Ok, that's clear now. It's not something possible now with reachability, but you should be able to do that directly in JavaScript. Check Stackoverflow, you'll find threads like this:
http://stackoverflow.com/questions/4373266/how-to-check-for-connectivity-with-server-using-javascript-from-native-android-2

**Comment by petesavva** [comment]
Success! I did it in the BakerViewController.m file

```
 (void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error {
    // Sent if a web view failed to load content.
    if ([webView isEqual:currPage]) {
        NSLog(@"[BakerView] ERROR: CurrPage failed to load content with error: %@", error);
    } else if ([webView isEqual:prevPage]) {
        NSLog(@"[BakerView] ERROR: PrevPage failed to load content with error: %@", error);
    } else if ([webView isEqual:nextPage]) {
        NSLog(@"[BakerView] ERROR: NextPage failed to load content with error: %@", error);
    }

//added this alert for internet connection!

    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Connectivity Issue" message:@"Message Boards will not be available until connectivity is restored." delegate:self cancelButtonTitle:@"Close" otherButtonTitles:nil, nil];
    [alert show];
}
```

**Comment by folletto** [comment]
Nice! :)
And thanks for reporting the code back. :)
