### ISSUE TITLE
How to rename app from "Baker" to my custom?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#893]
When I try to delete app from simulator or device,
I see the following confirmation dialog:

> **Delete "Baker"**
> Deleting "Baker" will also delete all
> of its data
> [Delete] [Cancel]

How can I change the name of my magazine from "Baker" to my own "Super Magazine"?

**Comment by folletto** [comment]
Just change it from the project settings in Xcode. :)

**Comment by divlv** [comment]
Oh, thanks a lot! :-)
