### ISSUE TITLE
Old issue page shown while loading the new issue page of the magazine.

### ISSUE THREAD

**Issue by sgkalyans** [Simbul/baker#895]
I have a magazine app and I created issues#1 and #2.

I'm able to download issue#1 and read, then I downloaded issue#2 then issue#1's page is showing for sometime while issue#2's page loading.

Why there is a delay loading or refreshing ?

not sure whether I missed any settings.

Please help me..

**Comment by folletto** [comment]
Could you please follow the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page on the wiki above and report back? :)

**Comment by marcheluis** [comment]
i seem to remember i had a similar problem some time ago, and i think it might be related to the screenshot render mode, as i just changed to 3-page render mode and that problem disappeared.

**Comment by sgkalyans** [comment]
Thank you guys. 

I manage to solve it by downloading the latest baker framework.
