### ISSUE TITLE
Understanding Newsstand with IAP and subscription

### ISSUE THREAD

**Issue by lostinjapan** [Simbul/baker#898]
I apologize in advance for asking such a basic question.

I'd like to create a Newsstand app with one sample half issue that is free and all paid issues after that. I am having trouble understanding the mandatory subscription option. 

If users subscribe, will they be able to download all available issues or is there a way to distinguish between things included and not included in a subscription?

**Comment by folletto** [comment]
It's really all up to you: using anything but free issues/subscriptions requires you to implement (or use, see [MagRocket and Newsstand DIY](http://bakerframework.com/tutorials)) a server. The server is the one that validates paid issues and paid subscriptions and unlocks them.

So, depending on what you need, just implement the server following that and you'll be fine. :)

**Comment by lostinjapan** [comment]
Thank you for the reply! I used MagRocket so I will post in their forums asking what the typical behavior of a subscription is.

**Comment by folletto** [comment]
Great. :)
