### ISSUE TITLE
Updating the app... Issues with signing certs?

### ISSUE THREAD

**Issue by fcontreras** [Simbul/baker#899]
Greetings all

I wanted to share this issue Im having with you, maybe some comments and experiences may help clarify.

My App was published on version 1.0, all good but an issue with the Locale and dateformating that was preventing some users to download the issues.

I found an applied the fix 86785e1, then updated the bundle build number and the version to 1.0.1 all good.. created a assembly, created the version on itunes connect and then submitted the new binary, all good all test pased and the apple guys after couple of days started to check the app.

To make this short, I got the app aproved and there comes the issue.
Trying to download the update it shows 

Unable to Download Application
"AppName" could not be downloaded at this time.

From the log of the iPad i got 

May 21 00:31:55  SpringBoard[66] <Warning>: Killing <appbundle> for app installation
May 21 00:31:55  installd[53] <Error>: 0x2ffc4000 handle_install: Install of "/var/mobile/Media/Downloads/535049042357234212343/-8193871302343084732" requested by itunesstored
May 21 00:31:56  installd[53] <Error>: 0x2ffc4000 MobileInstallationInstall_Server: Installing app <appbundle>
May 21 00:31:56  installd[53] <Error>: 0x2ffc4000 install_application: Attempting patch update of <appbundle>
May 21 00:31:56  installd[53] <Error>: 0x2ffc4000 verify_signer_identity: MISValidateSignatureAndCopyInfo failed for /var/tmp/install_staging.nO9DaY/foo_extracted/Payload/<appname>.app/<appname>: 0xe8008019
May 21 00:31:56  installd[53] <Error>: 0x2ffc4000 do_preflight_verification: Could not verify executable at /var/tmp/install_staging.nO9DaY/foo_extracted/Payload/<appname>.app
May 21 00:31:56  installd[53] <Error>: 0x2ffc4000 install_application: Preflight validation failed after patch.
May 21 00:31:56  itunesstored[75] <Error>: 0x1682000 MobileInstallationInstall: failed with -1

From some research it seems like the cert failed.. wondering why? and why the apple guys didnt notice.

Also one last note, the app fails to update but installs ok if is removed.

Hoping we can add some comments on this.. I know this may not be totally baker related but may help getting an update guide and creating a check list before submitting.

Thanks for your comments

Kind Regards

**Comment by folletto** [comment]
This looks like more a iTunes Connect / Xcode issue. I would advise to try on Apple's developer forums or Stackoverflow. We can't do support on these issues unfortunately. I'll leave this thread open for a couple of days just in case someone has a ready answer.

**Comment by fcontreras** [comment]
Hi @folletto, yeah I agree with you, that this is not a baker issue, just wanted to post this out, in case i found the answer i will post it here to let the rest know, and as you said learn from anyone that have a previous idea of it.

Thanks for letting this open for couple of days. :)

**Comment by fcontreras** [comment]
What I finally ended doing was removing all certs from my XCode and having it re download them, that fixed the issue.

**Comment by folletto** [comment]
Ahh... I see. :)
Thanks for coming back with the answer. :)
