### ISSUE TITLE
Ebooks can be zipped

### ISSUE THREAD

**Issue by folletto** [Simbul/baker#9]
_As an author I want to put the book inside Baker as a zip file._

This is required to create a "proper" hpub format.

**Comment by svdgraaf** [comment]
I agree :)

**Comment by folletto** [comment]
Upvote then! ;)

**Comment by svdgraaf** [comment]
done ;)

**Comment by alpertayfun** [comment]
Well.

How can i get zipped file from the ftp / http server ? Then zipped file content extract the any book name directory ?

Thak you.
AT

**Comment by Simbul** [comment]
The feature you're mentioning has not been implemented yet, though we are working on it and it shouldn't be long before you can use it ;)

**Comment by folletto** [comment]
The feature is almost there, we are putting the finishing touches to make it work correctly. :)

**Comment by folletto** [comment]
We developed this thing a little differently. So:
1. It handles downloaded zip books.
2. It can handle book:// links from inside a book (see protocol issue #14) and download a book.
3. The special book://local URL brings back to the internal book.
4. The downloaded book stays in memory until a links goes back to book://local.

**Comment by folletto** [comment]
Released.

**Comment by MacBoy** [comment]
When we restart the iPad, does the downloaded book get erased from memory?

**Comment by folletto** [comment]
No, it stays there until a new book is loaded. :)
