### ISSUE TITLE
iframe for dynamic content

### ISSUE THREAD

**Issue by apontillo** [Simbul/baker#903]
I would like to use an iframe to insert dynamic content, but does not seem to work. Is there a way to make it work or another system to achieve the same result?

**Comment by folletto** [comment]
Well... it should work. What are you trying to do?

Otherwise, you could just use javascript to dynamically load data. :)

**Comment by apontillo** [comment]
I would like to prepare a php page that resides on a server and read from mysql, and insert them in barker with < iframe src="http://mioserver.it/page.php" >< /iframe >

Thank you very much to the interest

**Comment by folletto** [comment]
As said, it should work. What's the problem? :)

**Comment by apontillo** [comment]
I tried putting in src = "http://www.google.it/" and does not work. I get empty space occupied by iframe

**Comment by folletto** [comment]
Well... Google doesn't allow iframing its website. Maybe you should try with a site of yours. ;)

**Comment by apontillo** [comment]
I'm a real stupid, now it works.
Another question: does the apple problems if you try to publish an app built with baker that contains iframe?

**Comment by folletto** [comment]
It actually should improve the odds since adds a dynamic element to the page (unless it's a system to workaround Apple's in-app purchases), but Apple's approval process is opaque, so it's impossible to tell with certainty.

Good to hear it's solved. I'm closing the issue then. :)

**Comment by apontillo** [comment]
thank you very much.

by

**Comment by jukialla** [comment]
Google "iframe, ios bug" all will be revealed. :-(
