### ISSUE TITLE
Error parameter 'title' in book.json with iPad One

### ISSUE THREAD

**Issue by Rexios** [Simbul/baker#904]
I published a Newsstand App who work fine on iPad Three Retina (iOS 6) but on iPad One (iOS 5.1) I have this issue:  [BakerBook] ERROR: param 'title' is missing. Add it to 'book.json'. When download magazine on iPad One I recive this message: There was an error opening this issue. Try downloading it again or contact the publisher.
Thanks
Emanuele

**Comment by Simbul** [comment]
What does your `book.json` look like?

**Comment by Rexios** [comment]
``` json
{
    "hpub": 1,
    "title": "Numero 01_2013",
    "author": ["ASL"],
    "creator": ["la Cittadina"],
    "date": "2013-04-30",
    "url": "http://www.lacittadina.com/Xcode/",
    "cover": "http://www.lacittadina.com/Xcode/Marzo2013.png",
    "date": "2013-04-13",
    "orientation": "portrait",
    "zoomable": true,
    "-baker-background": "#000000",
    "-baker-vertical-bounce": false,
    "-baker-media-autoplay": false,
    "-baker-page-numbers-color": "#000000",
    "-baker-rendering": "three-cards",
    "-baker-index-width": 6500,
    "-baker-index-height": 250,
    "contents": [
        "0001.html",
        "0002.html",
        "0003.html",
        "0004.html",
        "0005.html",
        "0006.html",
        "0007.html",
        "0008.html",
        "0009.html",
        "0010.html",
        "0011.html",
        "0012.html",
        "0013.html",
        "0014.html",
        "0015.html",
        "0016.html",
        "0017.html",
        "0018.html",
        "0019.html",
        "0020.html",
        "0021.html",
        "0022.html",
        "0023.html",
        "0024.html",
        "0025.html",
        "0026.html",
        "0027.html",
        "0028.html",
        "0029.html",
        "0030.html",
        "0031.html",
        "0032.html",
        "0033.html",
        "0034.html",
        "0035.html",
        "0036.html",
        "0037.html"
    ]
 }
```

**Comment by Simbul** [comment]
I've reverse-engineered your `shelf.json` URL from the `url` you posted above and downloaded the HPUB.

It looks to me like the `book.json` you have in the HPUB doesn't match the one you posted above: in the HPUB, your `title` is declared as an array, while it should be a string (it is correct in the version you posted above).

**Comment by Simbul** [comment]
Btw, made the error message a bit more helpful in 21d5210.

**Comment by Rexios** [comment]
That book.json is a test who I make after, thanks for your answer. I will exclude iPad One and iOS 5.1 from my app.

**Comment by Simbul** [comment]
Ok, I tested it on an actual iPad 1. The `book.json` you posted above works fine, but you have to remove the duplicated `date` parameter.

**Comment by Rexios** [comment]
Thank you. It's work fine.
