### ISSUE TITLE
how can i make the sample book disappear?

### ISSUE THREAD

**Issue by Philipice** [Simbul/baker#906]
This my first time to use baker.I wanted to make a Standalone app.  I added my book folder in the books folder. But when I ran the simulator, my story appeared in the baker shelf, and the sample story "A Study in Scarlet" was also there.How can I make the sample book disappear?  
![snip20130523_1](https://f.cloud.github.com/assets/4500688/552082/53a5a660-c33f-11e2-940e-2d2fcd89d69f.png)

**Comment by ask91** [comment]
You have to make sure what you are running to. Standalone or Newsstand/Shelf mode?
At picture above, you might still use a Shelf mode. because if you running on standalone mode, the app will appear like apps in device, not inside a shelf like that.
Find out more in
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

for now,
i think you can make it disappear from the shelf by remove/delete the 'A Study in Scarlet' folder [inside the 'book' folder in BakerFramework bundle].

and make sure in the book.json file [inside your 'Laker Example' folder]   you put hpub specification of your 'Laker Example' book bundle only. 
Do not input hpub specification for other book you don't want to show.

**Comment by Philipice** [comment]
Wow, you reply to me so fast. I am impressed. You are so kind. Genius!!!!!    

Philip

At 2013-05-23 13:58:59,ask91 notifications@github.com wrote:

You have to make sure what you are running to. Standalone or Newsstand/Shelf mode?
At picture above, you might still use a Shelf mode. because if you running on standalone mode, the app will appear like apps in device, not inside a shelf like that.
Find out more in
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

for now,
i think you can make it disappear from the shelf by remove/delete the 'A Study in Scarlet' folder [inside the 'book' folder in BakerFramework bundle].

and make sure in the book.json file [inside your 'Laker Example' folder] you put hpub specification of your 'Laker Example' book bundle only.
Do not input hpub specification for other book you don't want to show.

¡ª

**Comment by ask91** [comment]
i'd love to hear the progress,. 

as i ever had same situation like you, i think i should help here as i could.
 Just like the Baker team supported me at past days :)

**Comment by Philipice** [comment]
Hi, I am using framework 4.1 and the books folder is empty.
But the story "A study of the Scarlet" still comes out  although the books folder is empty.  
When I put my story folder into books folder, "A study of the Scarlet" and my story come out together just as the attached picture shows.
I removed something as the tutorial says, but I have not conquered it.    "A study of the Scarlet" is becoming a nightmare , a monster to me.  OMG,please help me.
Philip

At 2013-05-23 14:11:01,ask91 notifications@github.com wrote:

i'd love to hear the progress,.

as i ever had same situation like you, i think i should help here as i could.
Just like the Baker team supported me at past days :)

¡ª

**Comment by Philipice** [comment]
I want to use Standalone mode. I followed the tutorial. if I don't put my story into the empty books folder, it is running to Standalone mode and showing the "A study of the Scarlet" story. (where does the "Scarlet"story hide? ) When I put my story into the empty books folder, the shelf shows up. :) How can fix it ? Please...

**Comment by Philipice** [comment]
I want to use Standalone mode. I followed the tutorial. if I don't put my story into the empty books folder, it is running to Standalone mode and showing the "A study of the Scarlet" story. (where does the "Scarlet"story hide? ) When I put my story into the empty books folder, the shelf shows up. :) How can fix it ? Please...
Philip

At 2013-05-23 14:11:01,ask91 notifications@github.com wrote:

i'd love to hear the progress,.

as i ever had same situation like you, i think i should help here as i could.
Just like the Baker team supported me at past days :)

¡ª

**Comment by Simbul** [comment]
Wow, that's a lot of messages for a single issue. No need to panic :)

In Standalone mode, your books are stored inside the `books` folder. If you download Baker from Github, the `books` folder comes with our sample book, A Study in Scarlet. If you download the release from bakerframework.com, the folder will be empty.

You can still see the shelf in Standalone mode (that's how we support multiple books). The difference with Newsstand mode is, the user won't be able to download them. Books will show up in the shelf if if put them in the `books` folder.

So I would say:
- Make sure your `books` folder only contains a single folder: your book
- Follow the instructions to do a [Proper cleanup](https://github.com/Simbul/baker/wiki/Proper-cleanup)

**Comment by Philipice** [comment]
wow. I fix it. Thanks a lot. I am so excited .  It is clean up problem.
Philip 

At 2013-05-23 15:25:24,"Alessandro Morandi" notifications@github.com wrote:

Wow, that's a lot of messages for a single issue. No need to panic :)

In Standalone mode, your books are stored inside the books folder. If you download Baker from Github, the books folder comes with our sample book, A Study in Scarlet. If you download the release from bakerframework.com, the folder will be empty.

You can still see the shelf in Standalone mode (that's how we support multiple books). The difference with Newsstand mode is, the user won't be able to download them. Books will show up in the shelf if if put them in the books folder.

So I would say:

Make sure your books folder only contains a single folder: your book
Follow the instructions to do a Proper cleanup

¡ª

**Comment by Philipice** [comment]
hi, I have fixed it . it is cleanup problem. Thank you very much.  :)  
Philip 

At 2013-05-23 14:11:01,ask91 notifications@github.com wrote:

i'd love to hear the progress,.

as i ever had same situation like you, i think i should help here as i could.
Just like the Baker team supported me at past days :)

¡ª
