### ISSUE TITLE
JPEG 2000 support?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#907]
Can I use JPEG2000 pictures in my html pages for Baker publications?

(I'm thinking about it due to better quality / compression ratio)

**Comment by Simbul** [comment]
If they work in Mobile Safari, chances are good they will work in Baker as well.

**Comment by divlv** [comment]
I have just tested it.
Yes, Jpeg2000 format is supported by Baker, at least on my iPad-1, iOS 5+.
