### ISSUE TITLE
Help with error Please!!!

### ISSUE THREAD

**Issue by fobetor** [Simbul/baker#908]
Hello,
 I have added two books to my newsstand. The firs one load correctly once downloaded, but the next issue, gives me the following error in Xcode debugger:

```
2013-05-23 16:30:19.547 CartoGrafia[44073:c07] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 2]'
*** First throw call stack:
(0x1e66012 0x1bd9e7e 0x1e080b4 0xab6e 0xaaf3 0xa59a 0x5cb9 0x4a03 0x902103 0x9024df 0x915288 0x902103 0x9024df 0x90
```

What does this refer to? My ebook has just 3 pages, and the index... nothing more...
Thanks in advance

**Comment by fobetor** [comment]
The reason, is there is a bug somewhere, because I've discovered that since BAKER memorizes the last page that has been read to recover it later when opened again, if we switch between magazines / books and one has less pages than the other so the last page viewed was ie: 12 and the new magazine has 3 pages, when switched, Baker tries to open page 12 !!! so... we have an error ....

**Comment by folletto** [comment]
Are you sure your `shelf.json` is following the specifications? That shoudn't happen... unless you have for example the same title for two different issues. Could you please paste or link your `shelf.json` file? :)

**Comment by fobetor** [comment]
Ah, Ok , that was it... I didnt see that in the wiki documentation. Both has the same title since I'm just testing and copy/pasted the json...
Thank you
