### ISSUE TITLE
Bakerframework on PC??

### ISSUE THREAD

**Issue by aredqueen22** [Simbul/baker#909]
Good evening. So I don't have a computer Mac OS at home except at school... Can I to use Bakerframework on an other software on PC. Maybe not coz baker.xcodeproj. I will make a virtual machine on my computer soon to work at my project.

**Comment by folletto** [comment]
Hello!
Unfortunately Baker is for Xcode (and iOS) and it works only on Mac OSX. I'm sorry. A proper virtual machine with the latest version on Xcode can work (remember that you still need the Developer License tho).
