### ISSUE TITLE
Navigation Bar on Rotate

### ISSUE THREAD

**Issue by therabidbanana** [Simbul/baker#91]
If you have the navigation bar open and you rotate the device, when the navigation bar reappears, the bottom 20 pixels will be trimmed off. This is most likely related to the conditional in "resetScrollView" that checks if the status bar is hidden:

https://github.com/Simbul/baker/blob/master/Classes/RootViewController.m#L227

The index view isn't alerted that it should also be bumped up -20 pixels if the status bar is showing. This -20 jump is kind of jarring - maybe there's a way we could avoid it (hide status bar before rotating) or make it smoother?

**Comment by mimetic** [comment]
Extra height seems to appear when the nav bar is open upon rotate. A non-scrollable screen will become scrollable, the height will INCREASE by 20 pixels.

In line 807 of RootViewController.m,
            NSLog(@"Current page height: %d", currentPageHeight);
it seems that currentPageHeight shows the width. In Landscape, the height is reported to be  768 (unless nav is open and the iPad rotated, in which case it reads 788).

**Comment by Simbul** [comment]
In addition, we made the background for the UIWebView containing the index bar transparent. So if you don't specify any background color for index.html, you'll be able to see the pages below the elements in the index bar ;)
See c2426e4e20724e1f1a451a609bec73a11a5d2999.
