### ISSUE TITLE
Newsstand App crash. Walking through pages, changing issues.

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#911]
Hello!

So, I'm very close to submit my Newsstand application to App Store for review,
but today, performing some last tests I met the very unpleasant problem.
(iPad 1, iOS 5.1.1)

My App is a magazine, with 1536x2048 PNGs (rendered from PDFs) as pages.
I have 2 issues, downloaded from my server (Baker Server API).

**Steps to reproduce:**
1. Download both issues to the device
2. Open any issue and go through, say, 10 pages forward.
3. Return to Shelf page
4. Open the other issue and...
5. ... try to zoom page, or go some pages forward (variable behavior here)

**Expected result:** read the magazine without a problem
**Actual result:** App crashes - black iPad screen for 1-2 seconds and returning back to Newsstand folder (not Shelf page, but 1 step "up").

I didn't have any similar problem with standalone version.
My magazine(s) are 48 pages large, and each PNG for page is 700kb-1000kb.
On standalone version (on device!) I was able to swipe all the pages till the end, zoom, jump by TOC, ec.t.
( _There should be memory problems too, if any, but - it worked like a charm!_ )

In newsstand version... crash :-(

So, I tried to change the rendering type - add the empty screenshots to take off this job from Baker, but... no luck. The behavior didn't changed. Crashes.

Please, help me, - what I am doing wrong?

**Comment by folletto** [comment]
It looks like a memory problem, so there might be nothing we can do. But, let's see if it's true. :)

Proceed with the usual basics: follow the instructions in [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back. :)

**Comment by divlv** [comment]
OK, here's my update:

I've tried everything from section _"Problems and Debugging"_ - updated XCode, downloaded latest Baker version from GitHub, cleared everything, but - **no luck**  :-(

Then, I searched this place for memory related issues, and found the #358  (Screen shots and large books).
There we have almost the same situation.
It looks like endless screenshots generation performs bad in my case.
So... I have changed the `-baker-rendering` option to `three-cards` and...
it seems like working OK! :-)

@folletto you wrote in #358 

> What version of Baker are you using? 
> I'm asking because we released yesterday version 3.2 that had a fix for that problem.

I'm using Baker 4.1 and I can confirm, that ( _in some cases_ ) this problem **is still actual**.
I have changed the rendering mode, as suggested by @pixelrevision and this problem seems like disappeared.

**Comment by folletto** [comment]
I was going to ask you one missing piece from the Problem and Debugging page, the debug log, but if switching to three-cards solved it, then we are almost certain it's a memory problem. 
The problem is clearly more evident in older hardware and iOS versions.

We can't do much about that: it's all handled by the `UIWebView` and we have no control over it.
