### ISSUE TITLE
Baker Server API: shared_secret.txt

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#914]
Hello!

I'm implementing Baker Server API, using PHP/MySQL
and just to be sure, want to clarify - 
in **functions.php** function `function verifyReceipt($base64_receipt)` : 
what is **shared_secret.txt** ?
What should I put there and where should I get the information?

iTunes Connect, I suppose, but... where exactly?

Thanks in advance.

**Comment by Simbul** [comment]
As it says in the server README

> To verify receipt with the App Store you need to put your app shared secret in the shared_secret.txt file. See shared_secret.txt.example for instructions. You can generate/retrieve your app shared secret in iTunes Connect.

You can find all the guidance you need in the [iTunes Connect Developer Guide](http://developer.apple.com/library/ios/#documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/13_ManagingIn-AppPurchases/ManagingIn-AppPurchases.html#//apple_ref/doc/uid/TP40011225-CH4-SW1).

**Comment by divlv** [comment]
Thank you!

**Comment by divlv** [comment]
Just in case, somebody don't see the link " _View or generate a shared secret_ " 
To see this, we must go into the 'Contracts' section of iTunes connect 
then request and accept " _iOS Paid Applications_ " contract.

After that, link will be accessible.

See - http://stackoverflow.com/questions/5022296/generate-shared-secret-key-in-itunes-connect
