### ISSUE TITLE
When to test Subscriptions/In-App Purchases

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#915]
The question is:
can I test Subscriptions and/or In-App Purchases for my app without submitting it to iTunes?

I have implemented the Server API functions, but have not submitted my App to iTunes yet, 
and trying to test "Subscription" Baker's button in the top left corner of the iPads screen,
I've got **"This is not a test user account"** error message...

**Comment by folletto** [comment]
Sure. Just create... a Test User Account. ;)
http://developer.apple.com/library/ios/#documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/7_ManagingYourTeam/ManagingYourTeam.html

**Comment by divlv** [comment]
Thank you!
