### ISSUE TITLE
initPageNumbersForPages causes crash

### ISSUE THREAD

**Issue by mimetic** [Simbul/baker#92]
Since adding a new page, the app crashes in the iPad simulator, as follows. 
UPDATE: I discovered the last page, the one which causes the crash, caused an error when opening in BBEdit, something like the UTF-8 is damaged. I have recreated the page, and the error went away.

GNU gdb 6.3.50-20050815 (Apple version gdb-1518) (Sat Feb 12 02:52:12 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin".Attaching to process 44350.
2011-05-25 16:05:17.483 Fire Season[44350:207] Device Width: 768.000000
2011-05-25 16:05:17.485 Fire Season[44350:207] Device Height: 1024.000000
2011-05-25 16:05:17.485 Fire Season[44350:207] Set size for orientation: Portrait
2011-05-25 16:05:17.486 Fire Season[44350:207] HIDE status bar 
2011-05-25 16:05:17.518 Fire Season[44350:207] Pages in this book: 8
2011-05-25 16:05:17.528 Fire Season[44350:207] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
**\* Call stack at first throw:
(
    0   CoreFoundation                      0x00f5c5a9 **exceptionPreprocess + 185
    1   libobjc.A.dylib                     0x010b0313 objc_exception_throw + 44
    2   CoreFoundation                      0x00f14ef8 +[NSException raise:format:arguments:] + 136
    3   CoreFoundation                      0x00f14e6a +[NSException raise:format:] + 58
    4   Foundation                          0x001601f9 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 224
    5   Foundation                          0x0015dbf4 -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 169
    6   Fire Season                         0x000046a5 -[RootViewController initPageNumbersForPages:] + 1657
    7   Fire Season                         0x00003558 -[RootViewController resetScrollView] + 865
    8   Fire Season                         0x00003e56 -[RootViewController initBook:] + 1206
    9   Fire Season                         0x00002f76 -[RootViewController init] + 2488
    10  Fire Season                         0x00001dce -[BakerAppDelegate application:didFinishLaunchingWithOptions:] + 97
    11  UIKit                               0x002d6c89 -[UIApplication _callInitializationDelegatesForURL:payload:suspended:] + 1163
    12  UIKit                               0x002d8d88 -[UIApplication _runWithURL:payload:launchOrientation:statusBarStyle:statusBarHidden:] + 439
    13  UIKit                               0x002e3617 -[UIApplication handleEvent:withNewEvent:] + 1533
    14  UIKit                               0x002dbabf -[UIApplication sendEvent:] + 71
    15  UIKit                               0x002e0f2e _UIApplicationHandleEvent + 7576
    16  GraphicsServices                    0x018a1992 PurpleEventCallback + 1550
    17  CoreFoundation                      0x00f3d944 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION** + 52
    18  CoreFoundation                      0x00e9dcf7 __CFRunLoopDoSource1 + 215
    19  CoreFoundation                      0x00e9af83 __CFRunLoopRun + 979
    20  CoreFoundation                      0x00e9a840 CFRunLoopRunSpecific + 208
    21  CoreFoundation                      0x00e9a761 CFRunLoopRunInMode + 97
    22  UIKit                               0x002d87d2 -[UIApplication _run] + 623
    23  UIKit                               0x002e4c93 UIApplicationMain + 1160
    24  Fire Season                         0x00001d4a main + 104
    25  Fire Season                         0x00001cd9 start + 53
)
terminate called after throwing an instance of 'NSException'
sharedlibrary apply-load-rules all
Current language:  auto; currently objective-c
(gdb)

**Comment by folletto** [comment]
Do you still have the page that crashed Baker so we can check it out? :)
