### ISSUE TITLE
scrollbar invisible

### ISSUE THREAD

**Issue by apontillo** [Simbul/baker#925]
I would like to eliminate the scroll bar but not the scrolling.
In practice I would like to make the scroll bar invisible.

thank you very much

Alfredo

**Comment by folletto** [comment]
Baker doesn't have anything like that - I'm not actually sure why you would want to do that, it will just make the users more confused. 

However if you're really sure you want to do that, you can probably modify the source code.
You can find answers around, like on StackOverflow:
http://stackoverflow.com/questions/849225/iphone-is-it-possible-to-hide-native-scrollbar-in-uiwebview
