### ISSUE TITLE
Changing displayed subscription names in Baker?

### ISSUE THREAD

**Issue by DrCrypt** [Simbul/baker#926]
Hi guys --

This might be a stupid question, but is there a way to change the available subscription names within Baker? For example, I have a paid subscription with the Product ID com.3months. That subscription is entered in constants.h, like so:
# define AUTO_RENEWABLE_SUBSCRIPTION_PRODUCT_IDS [NSArray arrayWithObjects: \

```
        @"com.3months", \
        nil]
```

It shows up in the app under the "Subscribe" dropdown, but the name of the subscription is displayed as "com.3months." I can't figure out how to change the displayed subscription name from the Product ID to something more user friendly. I can't see anything in iTunes Connect, so I'm guessing it's with Baker. Any ideas?

**Comment by nfeiglin** [comment]
Hi @DrCrypt - In your Localizable.strings file add the product ID's and make them equal to whatever you want displayed. For example;

**"com.3months" = "3 Months Subscription";**

If you have additional subscriptions just repeat the process ie

"com.6month" = "6 Month Subscription"

**Comment by DrCrypt** [comment]
That did it! I knew it had to be easy. You guys are rockstars! Thanks.

On Thu, May 30, 2013 at 8:30 AM, nfeiglin notifications@github.com wrote:

> Hi @DrCrypt https://github.com/DrCrypt - In your Localizable.strings
> file add the product ID's and make them equal to whatever you want
> displayed. For example;
> 
> "com.3months" = "3 Months Subscription";
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/926#issuecomment-18676977
> .

## 

John Brownlee
writer, blogger, journowhatsit
ph: +1 212 464 7719
em: john.brownlee@gmail.com

**Comment by nfeiglin** [comment]
Glad to help!
