### ISSUE TITLE
Baker Server API: "latest_receipt_info" is missing in response

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#929]
Following the @Simbul 's guidelines from #920 , I'm editing the Server API php code...
Got one question so far:

 In **verifyReceipt** function ( _from functions.php_ ) we call **curl_exec** to verify
base64-encoded receipt with the App Store.

Later in the same file _functions.php_  there is a function called **markIssuesAsPurchased** 
where we trying to find the _start_ and _stop_ time boundaries:

```
    $start = intval($receipt->purchase_date_ms) / 1000;
    if ($app_store_data->status == 0) {
      $finish = intval($data->latest_receipt_info->expires_date) / 1000;
    } else if ($app_store_data->status == 21006) {
      $finish = intval($data->latest_expired_receipt_info->expires_date) / 1000;
    }
```

The problem is in **latest_receipt_info** parameter (as well as _latest_expired_receipt_info_ ).
See my response below,
there is no any **latest_receipt_info** parameter returned from App Store:

```
Store response: stdClass::__set_state(array(
   'receipt' => 
  stdClass::__set_state(array(
     'original_purchase_date_pst' => '2013-05-30 16:53:36 America/Los_Angeles',
     'unique_identifier' => 'd59e8fd41ef07096842fef5f113a94958f494624',
     'original_transaction_id' => '1000000075806590',
     'bvrs' => 'Baker40',
     'transaction_id' => '1000000075806590',
     'quantity' => '1',
     'product_id' => 'my.super.magazine',
     'item_id' => '651677212',
     'purchase_date_ms' => '1369958016815',
     'purchase_date' => '2013-05-30 23:53:36 Etc/GMT',
     'original_purchase_date' => '2013-05-30 23:53:36 Etc/GMT',
     'purchase_date_pst' => '2013-05-30 16:53:36 America/Los_Angeles',
     'bid' => 'my.super.magazine',
     'original_purchase_date_ms' => '1369958016815',
  )),
   'status' => 0,
))
```

So, why the **latest_receipt_info** is missing?
And how to get this or... how to substitute this variable?

**Comment by folletto** [comment]
Hello, I've seen you closed it. Did you solve it? Care to share how? :)

**Comment by divlv** [comment]
Actually, **latest_receipt_info** parameter will be returned only if paid subscription is created in iTunes Connect. (auto-renewable-subscription in my case).
I had only free subscription created for my app.

**Comment by folletto** [comment]
Ok, thanks for the update. It might be helpful also to others. :)
