### ISSUE TITLE
iAds support

### ISSUE THREAD

**Issue by Tarik21** [Simbul/baker#93]
I was just wondering, does the baker framework support iAds banners?

**Comment by folletto** [comment]
We don't want to promote any specific ad platform, so we didn't include any library in Baker, but it's quite simple to modify the code to allow that following one of the many tutorials around. :)

**Comment by Tarik21** [comment]
Could you point me in the right direction?

**Comment by folletto** [comment]
Well there's plenty of content around, it depends a lot on your skills and needs:
http://www.raywenderlich.com/1371/how-to-integrate-iad-into-your-iphone-app

From this simple query:
http://www.google.com/search?q=how+to+add+iad+to+my+app

**Comment by Tarik21** [comment]
I was thinking that I needed something special since the Baker framework
uses HTML 5. But thanks for the tip!

**Comment by folletto** [comment]
Oh, sorry I misunderstood. :)

While Baker uses HTML5 for the book itself, iAd is a component in Cocoa that interacts with the app itself, not with the book. :)

**Comment by Tarik21** [comment]
Hi Folletto,

I'm trying to use the above mentioned tutorial, but I seem to bump into some
trouble. The tutorial describes some steps that i need to do in the xib
file, but the baker framework doesn't have one..

This might sound like a real newb question, but if you could help me out
with this it would be very much appreciated.

**Comment by folletto** [comment]
Did you try reading the Apple doc?
http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/iAd_Guide/BannerAdvertisements/BannerAdvertisements.html#//apple_ref/doc/uid/TP40009881-CH3-SW2

Or googling around:
http://bees4honey.com/blog/tutorial/how-to-add-iad-banner-in-iphoneipad-app/

If you aren't able to solve the problem with these, I might suggest to try using StackOverflow or directly on Apple's dev forums. :)
