### ISSUE TITLE
How to add admob to my application built by bakerframework?

### ISSUE THREAD

**Issue by chempanvee** [Simbul/baker#931]
I tried to add iad on bakerviewcontroller first and it works. But when i tried to add admob to bakerviewcontroller in the same way, the iphone simulator built the application successfully but couldn't show the banner on the screen.Is there anyone successfully did the same thing? If so, how to make it works? Thank you very much!

**Comment by tychau21** [comment]
I had the some problem and get the issue solved.  The error from admob is "no ad to show".  AdMob and bakerframework are both using webview.  And in app delegate, baker changed the user agent.  And you need to comment out this for the admob ads to display properly.

**Comment by folletto** [comment]
Thanks for getting back in touch with this feedback. Seems a weird thing to do, but well, if it works for them... it's ok I guess. :)

I'll close the issue than. :)

**Comment by ozyab** [comment]
@folletto tell us correct way to make AdSense work please.

**Comment by folletto** [comment]
Hello!

This board is available for historical reasons only. Please refer to the active issue board at https://github.com/BakerFramework/baker/issues and ask your question as clearly as possible in a new thread. :)
