### ISSUE TITLE
AppStore: free and/or paid subscriptions is needed for approve?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#933]
The question, may be more AppStore-experience related...
Do Apple require, developing Newsstand aplication (i.e. weekly magazine), to have free subscription anyway, to be approved in AppStore?
Or, it is enough simply to have several free issues available at once, and paid subscription available for future purchases?

So, if I plan to sell the issues of my magazine, am I forced to have and handle 2 types of subscriptions - 1st Free Subscription (for AppStore approvement??) and the 2nd - for actual selling periodical issues?

Please, share some experience...

**Comment by folletto** [comment]
As far as we know, it's mandatory to have at least a _Subscription_, which one and how to handle that is up to you. This means that at the very minimum you need to have a free one, but if you have a paid one it's good as well. :)

**Comment by divlv** [comment]
Thanks, @folletto !
Any more experience anyone? ;-)

**Comment by divlv** [comment]
@folletto 's opinion is enough for me :-)
