### ISSUE TITLE
22 Warnings

### ISSUE THREAD

**Issue by codypallo** [Simbul/baker#934]
Im using Baker 4.1. I haven't touched the code, only the settings. I need my magazine to not be downloadable in iOS 5. However, when I switch the Xcode deployment target to 6.0 there are 22 warnings, mostly depreciations. The build still succeeds though. Will this be a potential cause for rejection when I attempt to get the app approved?

**Comment by Simbul** [comment]
As far as we know, warnings have never been a reason for rejection.

The latest version on `master` is targeted to iOS 6.0 and has no issues, by the way ;)

**Comment by codypallo** [comment]
Great thanks!
