### ISSUE TITLE
Advice needed: Magrocket - cannot download issues

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#937]
Hi All!
Sorry for posting possible resolved, or offtopic here but I cannot download issues, when using Magrocket as Baker backend :-(

So, I even use the proxy/sniffer to check the HTTP requests and responses, but this gave me no clue...

In my _MagRocket Administration Console_ I have only 1 free issue and I cannot download that issue anyway.
I have read everything in #42 and noticed I did all the same: downloaded the
latest **magrocket-api-master** package (not magrocket-backend-MagRocket1.0)
and switched _Issue Security_ parameter ON and OFF...
No luck.

I even edited the _index.php_ file to do
`header('Location: '.$issue['URL']); die();`
No luck as well.

So, my sniffer tells me, that on issue download we have 2 requests, HEAD and GET.
HEAD has its response like this:

```
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Accept-Ranges: bytes
ETag: "2618703717"
Last-Modified: Tue, 04 Jun 2013 12:33:16 GMT
Content-Length: 54407181
Date: Tue, 04 Jun 2013 21:47:13 GMT
Server: lighttpd/1.4.28
```

So, it means, file **is available** and ready for download.
But the following GET request has no response at all :-(
I'm really struck with this problem.
As you may notice, I'm using the **Server: lighttpd/1.4.28** but it not seems to be a problem, all my _mod rewrites_ looks like works well.

And the main thing: when I copy the URL from my HTTP sniffer, which Baker tries to use to download an issue, and paste this URL into the browser - it works like expected - download file dialog is appeared.

Please, help me, what I am doing wrong... ?
Is it a Baker problem (my Baker configuration), or Magrocket or... ??

**Comment by nin9creative** [comment]
Wait, you are using the master api?  Are you using the master backend as well? 

I not, you should be using the 1.0.1 API, you can find that tagged release.

Regards,
Andrew

**Comment by divlv** [comment]
_After several hours of debugging_ I use API - latest from GitHub (https://github.com/nin9creative/magrocket-api),
Backend - downloaded link from the website 
(http://github.com/nin9creative/magrocket-backend/archive/MagRocket1.0.zip).

**Comment by nin9creative** [comment]
If you are using the MagRocket 1.0 zip file as listed below for the backend

You need to use the API 1.0.1 (NOT the master)  The Master has some hooks into new
fields with the backend master and if you are using the released 1.0 backend, the api
needs to "be in sync"

https://github.com/nin9creative/magrocket-api/archive/MagRocket1.0.1.zip

Andrew

**Comment by divlv** [comment]
Guys, actually this is a record for _Knowledge base_ ;-)
So, as I told you before, I use Proxy/Sniffer for debug purposes.
Actually, the problem was in this Proxy-Interceptor, I think its waited till issue fully downloaded in the cache and then... I don't know.
When I disabled this debug proxy, issue downloaded well.

This particular issue may be closed, however I've got another related problem - #939

**Comment by folletto** [comment]
Wonderful, thanks for the feedback! :)
