### ISSUE TITLE
download issue get interrupted during the downloading process

### ISSUE THREAD

**Issue by kkporter** [Simbul/baker#938]
Hi, has anyone experience this:
during the downloading process of one issue, the internet access get interrupted, The app exit and back to the home screen without any error message, when I reopen the baker app, the issue looks like as if it has been successfully downloaded,however by openning the issue, the html looks like got something missing, such as css or images. I would expected the issue would be re-downloaded/ ask the user to tap download again/restart to download from the point where got interrupted. is there a way to fix this? Thx

**Comment by folletto** [comment]
It's likely interrupted after the download and while it was unzipping. What happens if you delete the issue and download again?

**Comment by kkporter** [comment]
if delete the issue and redownload again, the issue looks fine, but the unzipping promblem seems happen quite frequently on my side especially when i was using ipad2 ios6.0 for the testing, our file size is around 30M(dont think the file size is that big that would cause the issue), please shed some lights.

**Comment by folletto** [comment]
The problem was already notified on this issue #766 but at the moment we don't have any solution, also because we weren't able to reproduce the issue. :/

**Comment by kkporter** [comment]
then probably we shall leave it like that, thanks @folletto
