### ISSUE TITLE
template for library?

### ISSUE THREAD

**Issue by nickeykhem** [Simbul/baker#94]
hi there, you guys have created an amazing framework!! im almost done publishing my first catalog for a client soon. :)
im rather new to ipad development - so i sincerely apologize if this is an ill researched question

just had a quick question - your published issues show MagGames which has a library style ability to download, i just wanted to ask if this is based on html5 internal page links? - http://torqueo.net/files/html5-tabs/
or are these tabs built in via the xcode interface builder?

is there a template that i can download for something like this (just like your inital "book" issue where i can modify, as im a bit confused how MagGames got their content being updated on launch...

thank you guys so much !
nick

**Comment by folletto** [comment]
The library part - or shelf, how sometimes we call it - is something we are working on but it's still missing from the engine itselft. MagGames built its own on top of the download book feature we created, the same it's working for the book:// links. :)

At this time you have three choices:
1. Build the shelf in HTML5 as the "initial" book, with the rest downloaded (remember to put a back link to the downloaded issues)
2. Find a Objective-C developer to add that feature for you
3. Wait for us to implement it

:)
