### ISSUE TITLE
Endless "Updating price..."

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#940]
I've got similar problem as in #822

I see the magazine's cover, and just like in #822 - _There is no download button. Only flash indicates and writes: UPDATING PRICE..._

Following the #822 discussion, I've tried everything:
1. Rolled back all my localizations, and I'm using the original English messages;
2. Log doesn't say anything about _invalid product id_.
3. This is paid subscription created with **MagRocket** and _product id_ in MagRocket's "Shelf" exactly matches _product id_ in iTunes Connect...

So... any suggestions, please...

**Comment by folletto** [comment]
That issue however was solved: there was problem (the date) in the `shelf.json`, check it out. 

Also, as you should already know by now... you should add the log. What's in the log? ;)

**Comment by divlv** [comment]
Date in my `shelf.json` looks like this:

_"date":"2013-05-07 23:02:47"_

**Comment by Simbul** [comment]
Please post your full XCode debug log (and possibly your `shelf.json` as well). There's no way we can understand otherwise.

**Comment by divlv** [comment]
XCode debug log for the simulator:

```
2013-06-06 16:15:21.329 Zh Lulblu[2339:c07] ====== Baker Newsstand Mode enabled ======
2013-06-06 16:15:21.528 Zh Lulblu[2339:c07] [BakerShelf] Newsstand - Added Lublu792 2013-06-06 00:00:00 +0000
2013-06-06 16:15:22.191 Zh Lulblu[2339:c07] [AppDelegate] Push Notification - Device Token, review: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo=0x815d1c0 {NSLocalizedDescription=remote notifications are not supported in the simulator}
2013-06-06 16:15:23.517 Zh Lulblu[2339:c07] ############ REQUEST RECEIVED RESPONSE (
    "<SKProduct: 0x81a7ea0>"
)
2013-06-06 16:15:23.555 Zh Lulblu[2339:c07] ############ REQUEST RECEIVED RESPONSE (
    "<SKProduct: 0x81c3e90>"
)
```

I searched this issue tracker a bit and found some references to "date" parameter in _shelf.json_ file.

My _shelf.json_ file:

```
[{"name":"Issue788",
"title":"Issue 788",
"info":"blah blah blah blah blah blah ",
"date":"2013-05-07 00:00:00",
"cover":"http://ipublish.div.lv/issues/lublu/lublu788.png",
"url":"http://api.ipublish.div.lv/issue/lv.div.lublu/68CD17C0-C702-421C-8409-CD58DC031705/Issue788"},
{"name":"Issue792",
"title":"Issue 792",
"info":"blah blah blah blah blah blah ",
"date":"2013-06-06 00:00:00",
"cover":"http://ipublish.div.lv/issues/lublu/lublu792.png",
"product_id":"lv.div.lublu.weekly.pay.issue",
"url":"http://api.ipublish.div.lv/issue/lv.div.lublu/68CD17C0-C702-421C-8409-CD58DC031705/Lublu792"}]
```

**Issue788** is the free issue;
**Issue792** is the paid one.

I noticed the following, when I change the date format for paid issue to, say, US - 
"date":"06/06/2013 00:00:00",
then in the log I see the following:

`_ERROR: Exception the date argument cannot be nil._`
Means that my current date format is valid for Baker.

So... where's my mistake?
"product_id"?
When I remove "product_id" from the paid issue section in JSON, I see no "Updating price...",
FREE price but cannot download the issue itself. (It's OK, it is paid, indeed!)

Maybe, some settings in iTunes Connect?

Please, give at least a way to dig to...

**Comment by Simbul** [comment]
The `REQUEST RECEIVED RESPONSE` lines in the log point to the fact that the App Store is returning 2 products (one should be the paid issue, one should be the subscription).

However, this line looks suspicious: `Newsstand - Added Lublu792 2013-06-06 00:00:00 +0000`. First of all, you should see _two_ such lines, one for each issue. In addition, the debug line should show the `name` of the issue as it is specified in `shelf.json`, but I can't see `Lublu792` anywhere. Is the one you posted the same JSON your app is using?

**Comment by divlv** [comment]
@Simbul , actually, I have only 1 subscription - paid one. Free issues are added simply, without a subscription.
Is it clarifies anything?
And, btw, this `Lublu792` should be in place of `Issue792`.
Sorry for the inconvenience 
Here's my 100% original, raw shelf.json file (comes from MagRocket URL)

```

[
{"name":"Issue788",
"title":"Issue 788",
"info":"issue 788 issue 788 issue 788 ",
"date":"2013-05-07 00:00:00",
"cover":"http:\/\/ipublish.div.lv\/issues\/lublu\/lublu788.png",
"url":"http:\/\/api.ipublish.div.lv\/issue\/lv.div.lublu\/68CD17C0-C702-421C-8409-CD58DC031705\/Issue788"},
{"name":"Lublu792",
"title":"Lublu 792",
"info":"Lublu792 Lublu792 Lublu792 Lublu792",
"date":"2013-06-06 00:00:00",
"cover":"http:\/\/ipublish.div.lv\/issues\/lublu\/lublu792.png",
"url":"http:\/\/api.ipublish.div.lv\/issue\/lv.div.lublu\/68CD17C0-C702-421C-8409-CD58DC031705\/Lublu792",
"product_id":"lv.div.lublu.weekly.pay.issue"}
]
```

Here's my 2 issues in MagRocket:
![MagRocket](http://is.gd/9cjx5E)

Here's my iTunes page for 1 paid subscription. (no free subscription at all)
![iTunes paid subscription](http://is.gd/SgaCil)

**Comment by nin9creative** [comment]
@Simbul  In this case I've tested that this does work...  The FREE issue (with no product id) does show up as free and the
ones with Product ID's do get a price.

At least in my test cases.  A few others are doing the same thing and it works for them as well.

Andrew

**Comment by nin9creative** [comment]
Dinamitrij

Where's the screenshot of the Non-Consumable In App Purchase definition for the paid issue?

Andrew

**Comment by divlv** [comment]
Oh... hmmm... actually, I have no any "Non-Consumable" In-App Purchases for my application.
According to iTunes description:

_**Auto-Renewable Subscriptions**_
_Auto-renewable Subscriptions allow the user to purchase updating and dynamic content for a set duration of time. Subscriptions renew automatically unless the user opts out, **such as magazine subscriptions**_.

Looks like this one is for me! I plan to periodically publish and sell magazine issues.

But what about _Non-Consumable_ ?
Let's read iTunes description: 

_**Non-Consumable**_
_Non-consumable In-App Purchases only need to be purchased once by users. Services that do not expire or decrease with use are usually implemented as non-consumables, such as new race tracks for a game app_.

Hmmm... are you sure, I need to have this ?...

**Comment by nin9creative** [comment]
You have to have one defined for each of the issues that have a product id.

Regards,
Andrew

**Comment by Simbul** [comment]
It's all in our [In-App Purchase tutorial](https://github.com/Simbul/baker/wiki/Tutorial-for-Newsstand-with-In-App-Purchase#create-issues-on-itunes-connect): 
- A paid _subscription_ in Baker needs an **Auto-Renewable Subscription** in iTunes Connect
- A paid _issue_ in Baker needs a **Non-Consumable** in iTunes Connect

So assuming your magazine has 3 paid issues and it offers a subscription, you'll have to create 3 Non-Consumable product IDs and 1 Auto-Renewable Subscription product ID.

**Comment by divlv** [comment]
Guys, thank you **very much** for support!
Finally, I see the price near the issue.
