### ISSUE TITLE
animating background-image using CSS

### ISSUE THREAD

**Issue by maxhungry** [Simbul/baker#941]
Hello dear baker friends, I'm trying to animate the background-image in a div using css animation, since there's no way to directly select background-image to animate, I did a little research and found out that we can have background-image under a 'before' or 'after' pseudo element, and this works perfectly in a testing browser but when I test it in the simulator it failed to work. 

Here's how I did it:

```
@-webkit-keyframes animation {
    0% {-webkit-transform: translate(0,0);}
    50% {-webkit-transform: translate(0,-100px);}
    100% {-webkit-transform: translate(0,0);}
}
.div{
    height: 600px;
    position:relative;
}
.div:before{
    background-image:url('image/image.jpg');
    -webkit-animation: animation 2s infinite;
    content:"";
    width:200%;
    height:200%;
    position:absolute;
}
```

Maybe it has something to do with the :before pseudo? I can't seem to figure it out, any ideas?
*note: normal transformation works, only animation isn't working with this method =( 

(I'm under Laker framework)

**Comment by folletto** [comment]
If by browser you mean Safari on desktop, it's likely because the engine is different. You have to target Safari Mobile.

**Comment by maxhungry** [comment]
Hey folletto thanks for the quick reply, but I'm a bit confused.
I thought -webkit-animation is targeting Mobile Safari, if I would use the same code on a div it would animate on desktop browser/simulator/ipad.

**Comment by folletto** [comment]
What I mean is that you didn't specify what browser were you testing it in the first message. :)

Could you list precisely where it works and where it doesn't? This is the first thing to try to understand.

**Comment by maxhungry** [comment]
Sorry, I tested in Safari and Chrome on desktop they both worked. However in iOS simulator and ipad this doesn't work.

Maybe iOS does not support puesdo element animation? if that's the case I guess I'll need to use z-index instead of background-image.

**Comment by folletto** [comment]
Ok then that's it: Safari and Safari Mobile are two different browsers (usually Safari is more advanced than Safari Mobile). So you can't work on one and hope that the other works, expecially with edge features like `@-webkit-keyframes`.

Work directly on Safari Mobile, once it works there you should be 99% sure it will work on Baker – since it uses the same engine as Safari Mobile. :)

**Comment by maxhungry** [comment]
Thank you so much for your help sir, but I still cannot get it to work on Safari Mobile.
I'll just stay with the z-indexing for now.
Cheers.

**Comment by aspek** [comment]
If it's not work you should be expand it. Something like this

``` css
     -webkit-animation-name:animation;
     -webkit-animation-duration:.2s;
     -webkit-animation-iteration-count: infinite;
```
