### ISSUE TITLE
Info text in standalone mode

### ISSUE THREAD

**Issue by antoinemoussy** [Simbul/baker#943]
Hi,

How to add text between the title of the book and the read button ?
I know "info" when I use Newsstand mode but how to do the same in Standalone mode ?

Thx

**Comment by folletto** [comment]
I'm sorry it's not possible in Standalone mode.

**Comment by benoitchantre** [comment]
Maybe it will be possible with v4.2 (feature #615) ?

**Comment by folletto** [comment]
Yep that's the feature tracking it, thanks. I'm closing this one. ;)
