### ISSUE TITLE
Crashes on iOS5, works on iOS6?

### ISSUE THREAD

**Issue by ollisulopuisto** [Simbul/baker#946]
I cloned the repo two days ago to give this new subscription thing a test drive. It worked beautifully after a few tries.

However it looks like my project is only working when I run it in the iOS6.1 emulator. Both the iOS5.0 emulator and my 1st gen iPad (iOS5.1.1) crash Baker at the same point, ie. after loading the launch image:

2013-06-07 19:39:39.607 Kinotin[23950:c07] ====== Baker Newsstand Mode enabled ======
2013-06-07 19:39:39.701 Kinotin[23950:c07] [BakerShelf] Newsstand - Added kinotin-01 2013-07-01 09:00:00 +0000
2013-06-07 19:39:39.708 Kinotin[23950:c07] [BakerShelf] Newsstand - Added kinotin-02 2013-10-01 09:00:00 +0000
2013-06-07 19:39:39.710 Kinotin[23950:c07] [BakerShelf] Newsstand - Added baker-framework-tutorial 2013-01-25 13:01:25 +0000
2013-06-07 19:39:39.714 Kinotin[23950:c07] +[NSIndexPath indexPathForItem:inSection:]: unrecognized selector sent to class 0xe03f20
2013-06-07 19:39:39.717 Kinotin[23950:c07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSIndexPath indexPathForItem:inSection:]: unrecognized selector sent to class 0xe03f20'
**\* First throw call stack:
(0x15e0052 0x13cfd0a 0x15e1add 0x1546f00 0x1546ce2 0x2a235 0x15434d5 0x1543056 0x1542f65 0x2a047 0x29d2f 0x27a7a 0x324a 0x2b49d6 0x2b58a6 0x2c4743 0x2c51f8 0x2b8aa9 0x2fb7fa9 0x15b41c5 0x1519022 0x151790a 0x1516db4 0x1516ccb 0x2b52a7 0x2b6a9b 0x2dc2 0x2cf5)
terminate called throwing an exception(lldb) 

I've tried cleaning the build, but that didn't seem to affect it at all. Could still easily be a newbie mistake, so don't discount the obvious solutions. So where should I look next?

**Comment by folletto** [comment]
iOS5 is not supported anymore in the latest master.

**Comment by ollisulopuisto** [comment]
Okay, thanks–that would pretty much explain it, then. (Maybe add a notice to the web page?)

**Comment by folletto** [comment]
The master version isn't yet released, the currently released version is 4.1, and that works. :)

**Comment by ollisulopuisto** [comment]
Sure, but if the next version of Baker excludes iPad 1 owners, I'd rather start out that way (haven't yet published my app) than drop the support after the first few issues.

**Comment by folletto** [comment]
Sure, but don't make the decision based on an unreleased version of Baker. :)
Version obsolescence will happen, and we just follow the market for that. You can stay with 4.1 as long as you want, or switch immediately. But if you decide to switch, you can use even the 4.1 today and exclude iOS 5.0 immediately. Your choice. :)

This is a nice link: http://iossupportmatrix.com/ ;)

**Comment by ollisulopuisto** [comment]
Hmm, maybe  I was too rash with this line of reasoning. I'm just guessing that the next major version of Baker will include some essential feature that I cannot live without and then I'll have to /dev/null the iPad 1 customers. Must… stay… logical…

**Comment by folletto** [comment]
Well, you can check the 4.2 milestone here on GitHub and see by yourself if that's going to be the case in your perspective. :)
Also: next week there's the WWDC, and iOS7 is likely to be announced. :)
