### ISSUE TITLE
Refresh in baker?

### ISSUE THREAD

**Issue by MaverickWar** [Simbul/baker#947]
Maybe this has been asked before, if it has then i apologise, is it possible to make the refresh work in more of an obvious way, like a loading option, at the moment when clicking the refresh button, it doesnt appear to do anything.

Or perhaps an option to pull down to refresh would be nice....?

**Comment by folletto** [comment]
It has already been asked a few times, and it's surely something that has to be fixed.

The fix will require however some rework on the button, as such it's not that straightforward. But definitely doable. :)

Pull to refresh isn't a good choice in this case because a shelf isn't a stream. :)

**Comment by folletto** [comment]
I just noticed - or I can't find it - we don't have an open issue to track this. There was another one but it has been closed by the author #833.

So, I marked this one as bug for the next release. :)

**Comment by MaverickWar** [comment]
Brilliant, thanks for the response, this would be a welcome fix for sure.

**Comment by JosephMacReady** [comment]
Just wanted to say that when I add other buttons to the Navigation Bar, (they work but) the effect is the same - no button down animation. Any ideas?

**Comment by folletto** [comment]
I think it's the same issue as above: fixable but not with a straightforward solution. The issue seems raising by the combination of colors/transparency of the bar/button, and should be fixable if you manually control the button status.

**Comment by nfeiglin** [comment]
What about just adding a UIActivityIndicatorView on the navigation bar
while it refreshes?

**Comment by folletto** [comment]
That's one of the possible workaround solutions I mentioned before. :)

**Comment by nfeiglin** [comment]
Sorry - I didn't see it :)

**Comment by folletto** [comment]
Haha no I mean I mentioned "workarounds", nothing specific. Yes, that's one possibility. I'm still not sure. :)

**Comment by fcontreras** [comment]
Actually the issue seems to be related to the colors... I tried a version with the standard colors (gray/black) and the button actually shows the press and release statuses.

**Comment by folletto** [comment]
Yep. :)
