### ISSUE TITLE
What if you have a bunch of other magazines?

### ISSUE THREAD

**Issue by MaverickWar** [Simbul/baker#949]
Just a quick question, i have a client who has a few different magazines from different areas, how would they use baker for this, 

They wanted to know if there is a multi magazine option?

The other thing is to do with a library, i.e. if a user downloads a magazine, could these show up in a library area or be archived into a library rather than all on main screen?

**Comment by MaverickWar** [comment]
Dont worry if there isnt anything for this, i can always point them towards commecial options for this, i just id check here first.

**Comment by folletto** [comment]
I'm not sure how much sense would have one app for multiple magazines. Do you have any evidence of any company that publishes multiple magazines inside the same app? Or the commercial options you're aware of?

What do you mean about the "library area"? How is that different from the "main screen"? Just to explain: Baker has a shelf view and a book view: which one are you referring to?

**Comment by MaverickWar** [comment]
As an example, custompc magazine has this option at present.

This is how they lay theirs out, The company that handles the subscriptions and app is pixelmags.

![library](https://f.cloud.github.com/assets/4552051/628318/4962b9ba-d099-11e2-92b4-e4fdd3f160c8.png)
![downloads](https://f.cloud.github.com/assets/4552051/628319/49b43a88-d099-11e2-9073-1877941a05df.png)

**Comment by folletto** [comment]
Seems like a more complex way to do it. Baker des everything through a single shelf. What does that solution that is a benefit compared to Baker's shelf?

**Comment by MaverickWar** [comment]
well for one, with their setup/layout, you could list and view more issues on smaller devices. also if an author has a mixture of subscription and premium magazines, having a downloads area will take you to magazine you actually own without having to scroll down through app.

**Comment by MaverickWar** [comment]
Also the other benefit of their setup is that you can upload and use pdf instead of having to redesign everything into HTML5.

Custom PC magazines are interactive PDFs, although the files are large, usually around 100mb+ each.

**Comment by folletto** [comment]
The first point is just a matter of visualization choice. Baker uses a banner and a wider view, that I agree could be more optimised on iPhone.
I see the second point, however magazines are usually read on a specific month, so it should be a marginal case.

The third point however is final, and for Baker is actually a negative point not a benefit: don't use Baker if you don't want to convert to HTML: the HTML format is a direct benefit for the user, as is the fact that adapts to the screen. PDFs are a real pain to be read, that's why we created Baker. If the plan is to use PDF or repurpose it, I would suggest to go for another route. :)

**Comment by nin9creative** [comment]
Or if he/they are already using Indesign to create the PDF layout, just use in5 to convert to Baker .hpub!

:)

Andrew

**Comment by MaverickWar** [comment]
I agree with your last point, its most likely the best option, but from the point of view of most people who have pdfs already made and little knowledge of html5, its a steep learning curve to convert. IN5 is the best option so far but its expensive. But as you say, thats the setup so no real issue there. No offense to you guys because youve provided a great solution, i just wonder if it could be better optimised out of the box for mobile phones.

both visually and things like the refresh which has been listed for fix.

**Comment by nin9creative** [comment]
I actually wonder what the real demographics are on popular digital magazines - honestly as a user I can't get a good experience reading on on a phone....

Andrew

**Comment by MaverickWar** [comment]
As in your not sure there is a need for it? Not everyone has a tablet but there a lot of people that have iPhones, I know that out of the clients i have dealt with for example, in houses that cannot afford a tablet and iphones, they tend to pick the iphone for practical reasons (phone calls)

obviously magazines are easier to read on a tablet, but shouldnt that be a good reason to come up with a better solution for the mobile market?

Another example is the commuter, maybe they dont want to carry a tablet, but they wont go without their phone...

Just my 2 pennies worth.

**Comment by nin9creative** [comment]
Just saying that from a users point of view it is not an optimal platform for an interactive magazine format.  My .02

Andrew

**Comment by MaverickWar** [comment]
Possibly not and in an ideal world where everyone is able to afford multiple devices then it maybe the best way to read publications, but for those that dont have that luxury or are on the move alot and want quick access to files, the option to read on a mobile device is essential, there are plenty of options out there for tablets, it would be nice to see a solution that nails the mobile option also.

**Comment by folletto** [comment]
Well, I could say that Baker already _"nails the mobile option"_. Depends what you need. The current Baker implementation is a solution that covers both the need of a good visualization of the magazine (hence the top space and the background picture) united with the flow of available magazines. It's a balanced design that came out from our experience and the great feedback of the community. :)

And even better, when you open the magazine, an HTML publication can be adapted with responsive and `media-queries` to every possible screen, as such, you can already produce the perfect magazine. For iPhones and iPads alike. :)

Now, I see that you might prefer a simpler, more streamlined shelf with no background image and such, but as one solution Baker can't accomodate perfectly everyone's needs out of the box. You can customize it yourself, tho (see for example the [Find a Developer](http://bakerframework.com/developers) page on the website). :)

**Comment by folletto** [comment]
I'm closing this one since the discussion seem ended. :)
