### ISSUE TITLE
Suggestion: Add a Wiki?

### ISSUE THREAD

**Issue by therabidbanana** [Simbul/baker#95]
Might be nice to compile info we've all gathered into a single place - especially extra tools/css/other bits of code people are using to create their own books and any Baker tutorials. I think a Github Wiki would be a useful for that kind of thing.

**Comment by folletto** [comment]
I was thinking to link other's people content from the website, in order to valorize the community work, but yeah, I'm fine also with a wiki. :)

I'll assign this to Simbul since this is his space. :)

**Comment by therabidbanana** [comment]
Well, I don't mind the idea of linking directly to other sites if they do post the content, but generally I'm more likely to post to a project wiki than post directly on my own site because I know other people can come along and help clean it up and keep it up to date - I don't know if others are the same way.

**Comment by Simbul** [comment]
I enabled the wiki: https://github.com/Simbul/baker/wiki
Currently, editing is open to everyone on Github. Let's see where this goes ;)
