### ISSUE TITLE
IOS 7 compatibility?

### ISSUE THREAD

**Issue by MaverickWar** [Simbul/baker#952]
What's going to happen to baker with regards to IOS 7? Will it still be compatible?

**Comment by nonuts** [comment]
tested my baker-instance in ios7 beta today: works fine for now.

**Comment by folletto** [comment]
In other terms: of course it will be compatible. Why shouldn't we not make it so? :)

**Comment by nin9creative** [comment]
lol

**Comment by MaverickWar** [comment]
Absolutely, I had doubt it would be supported but with a new operating system coming out, I wondered if there was going to be compatibility issues.

I doubt I'm the only one that wondered that.

**Comment by folletto** [comment]
No worries. That's clear. It was just that the way you asked it looked like you were worried about Baker not supporting it in the future at all. :)

**Comment by MaverickWar** [comment]
Sorry, that's me being rushed, work is busy today and I popped on to ask a question between meetings so it was a bit rushed. lol 

No, I've no doubt you will look to support it. Just wondered if anyone had started testing and run up against any issues. I've no idea yet what impact 7.0 will have on newsstand and future publishing.

**Comment by folletto** [comment]
From the change log for iOS7, at the moment, I read: **NewsstandKit: No changes**

**Comment by freney** [comment]
The custom navigation bar will need a bit of work: not a huge fix, but a small one to make the subscribe & back buttons visible. Aside from that, there's no issues as far as I can see.

**Comment by folletto** [comment]
Thanks. :)

**Comment by benoitchantre** [comment]
@folletto can we report issue about iOS7 or is it too early?
I have noticed that pages are moved up by 20px.

**Comment by folletto** [comment]
Thanks for asking. :)

Not yet, unless you are aware that there's an iOS7 branch on GitHub and we are working on it. ;)
Once we merge that branch back in master then we'll open the feedbacks for iOS7. :)

**Comment by benoitchantre** [comment]
I now there's an iOS7 branch, I have merged it with on a local test branch (a copy of the master branch).
When launch a test project from this branch, I can see the page is moved up by 20px (the height of the status bar). The info of the status bar (network, clock, etc.) are displayed on the page. When I switch the simulator to iOS 6.1, pages are displayed properly. Maybe it would be a good idea to use `autolayout` to position the pages and the index?

**Comment by folletto** [comment]
Yup, iOS7 changed how the status bar is managed and given Baker handled it by hand to adapt to all the various situations it's misbehaving – quite badly actually. That's the next thing we are working on in that branch, keep an eye on it. :)

**Comment by benoitchantre** [comment]
Thanks, I'll keep an eye on this branch.

**Comment by benoitchantre** [comment]
I find that the text displayed in the shelf view is a bit big, but that's probably something that will be improved at the end?

**Comment by folletto** [comment]
I noticed the same, it's now using the new rendering engine on iOS7... it's now possible for the user to change it from the control panel. Yeah, we should review that. :)

**Comment by benoitchantre** [comment]
The setting to change the font size works well, it's only the base font size that is too big.
To have a font size similar to iOS6 in the shelf, you need to move the slider two steps on the left.

**Comment by folletto** [comment]
I'm not entirely sure, but I _think_ that's the iOS mandated "default". But I'm not entirely sure, we'll check. :)

**Comment by benoitchantre** [comment]
The answer should be in the session 223 _Using Fonts with Text Kit_.
Update: text styles are probably the solution: `[UIFont preferredFontForTextStyle:]` styles are described in UIFontDescriptor documentation

**Comment by Simbul** [comment]
We're already using styles for all UI components under iOS 7. We should probably review them and make sure we're using the appropriate one for each component.

**Comment by benoitchantre** [comment]
Ok. I can't help much, my understanding of Objective-C is quite limited.

**Comment by benoitchantre** [comment]
Here's the [text styles list](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIFontDescriptor_Class/Reference/Reference.html#//apple_ref/doc/constant_group/Text_Styles) from Apple documentation.

Here's the result of what I changed (with default text size).
@Simbul, do you want a pull request?

**Before**
![capture decran 2013-09-10 a 18 17 31](https://f.cloud.github.com/assets/1521015/1116049/901b5e36-1a34-11e3-920e-2bb8db850c94.png)

**After**
![capture decran 2013-09-10 a 18 15 52](https://f.cloud.github.com/assets/1521015/1116036/61b2be40-1a34-11e3-92ee-a465d0319598.png)

**Comment by benoitchantre** [comment]
iOS7 golden master is available in iOS Dev Center

**Comment by MaverickWar** [comment]
Is the shelf design getting an upgrade for iOS 7 or maybe a kiosk option?

I saw this from another provider upgrading to iOS7

https://www.dropbox.com/s/u0detkrm63zqv89/2013-09-15%2016.59.08.png

https://www.dropbox.com/s/kxezm2f546ul2gz/2013-09-15%2017.28.55.png

https://www.dropbox.com/s/4hzwqdquufoe9y7/2013-09-15%2017.29.14.png
