### ISSUE TITLE
Deleting Issue on shelf.json does not update the shelf list.

### ISSUE THREAD

**Issue by yalexyu-1stdibs** [Simbul/baker#957]
Hi there,

This is my first time doing iOS development. I'm using Baker for a Newsstand app. I was fiddling with the Shelf.json and noticed the following:

1) If I add a magazine issue to Shelf.json and the application is open, it will show up on Baker's shelf. This is good.
2) If I remove aforementioned magazine issue from Shelf.json, the magazine issue remains on Baker's shelf. Tapping the refresh button in the top-left of the application window does not remove the deleted magazine issue from view. I had to do a hard reset on my device before it registered.

To ensure that the refresh was working, I included a NSLog line in BakerAPI -getShelfJSON, which displayed just fine. I also navigated to Shelf.json and the changes were reflected. I tried changing the cachePolicy to NSURLRequestReloadIgnoringLocalAndRemoteCacheData, but that also didn't update the shelf list.

Is there no way around this? Is anyone else experiencing this?

Edit: Restarting the application also worked. However, I'd rather not resort to this method!

**Comment by Simbul** [comment]
It should work now. Have a look at the latest `master`.

**Comment by yalexyu-1stdibs** [comment]
Thanks!
