### ISSUE TITLE
Rejected: Metadata, Application Description. Any idea why?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#958]
Hello all!

Today I've got second(!) rejected conclusion from App Store review team.
The "diagnostic" both times is the following:

```
We found that your Application Description did not fully meet the terms and conditions for auto-renewing subscriptions, as specified in Schedule 2, Section 3.8(b). Meeting the terms of this agreement is required by the App Store Review Guidelines. 

Specifically, we found that your Application Description did not include:

the length of the subscription
the price of the subscription
information about the auto-renewable nature of the subscription
```

I think, I have edited the description properly. 
I agree 1st time it wasn't correct.

And the subscription items was yellow-marked (as incorrect), **not the main application description(!)**:

![Subscription items](http://is.gd/5rfeNo)

Sorry for blur. (anti-boss protection ;-)) )

All the mentioned information was included: See the screenshot (http://is.gd/zKarNf) or:

![Auto Renewable subscription description](http://is.gd/zKarNf)

**the length of the subscription** - "subscription for 7 days" (in russian)
**the price of the subscription** - "price - 0.89 €;" (in russian)
**information about the auto-renewable nature of the subscription** - Auto-renewing, until cancelled by user (in russian)

So, please, any idea anyone, what's wrong with this description?
(or, some misunderstanding were took place...?)

**Comment by nfeiglin** [comment]
I don't think the price should be in the description because it would be
different in each region. I actually had this same issue so I'll take a
look later at what I did to rectify it.

Nathan

**Comment by divlv** [comment]
Nathan, please, I'll be waiting for your update so bad...

**Comment by nfeiglin** [comment]
Do did you submit an app binary with this IAP? Apple kept on rejecting mine
until I submitted the actual app binary.

**Comment by divlv** [comment]
As far as I know, I cannot send my app to review by Apple, unless my binary is not submitted...
I followed the standard procedure for uploading app
(actually, seen here: http://youtu.be/VxMSLzwHeCk _"Xcode 4 - Uploading an app to the AppStore"_)

Validated my App from XCode with Apple "Pre-Reviewing" procedure and sent to Review.
Am I missed something Newsstand specific?!
Not sure, because Apple quite directly points me to the "wrong places"...

Any more ideas?

P.S.
what's IAP stands for...?

**Comment by nfeiglin** [comment]
Hi, 

IAP stand for In App Purchase. I just re-read what Apple sent to you and it mentioned that the issues were in the application description. Not the IAP description.

**Comment by folletto** [comment]
Hello. Could you give us your feedback? :)

**Comment by divlv** [comment]
The issue was solved.
I needed to add the mentioned data to Main Application's Description.
I mean:

> the length of the subscription - "subscription for 7 days" (in russian)
> the price of the subscription - "price - 0.89 €;" (in russian)
> information about the auto-renewable nature of the subscription - Auto-renewing, until cancelled by user (in russian)

I even left these lines in IAP description. No problem.
Actually, the main complaint from Apple side was the lack of this information in the **Main Application's Description** (not IPA description!)

**Comment by folletto** [comment]
Great, thanks. :)
