### ISSUE TITLE
Selection Disabled

### ISSUE THREAD

**Issue by usaps** [Simbul/baker#96]
Hi All,

I'm just wondering if you came by this issue: the selection "box" & the magnifier over the images (please see images below)

![screen shot 1](http://www.eggmotion.es/images/ss1.jpg)

![screen shot 2](http://www.eggmotion.es/images/ss2.jpg)

Would be great to be able to disable it, if possible of course,

best regards

jero

**Comment by folletto** [comment]
It should be this CSS command:
-webkit-user-select: none;

Source:
http://stackoverflow.com/questions/923782/disable-the-text-highlighting-magnifier-on-touch-hold-on-mobile-safari-webkit

Tell us if it works. :)

**Comment by usaps** [comment]
Hey... as always it needed to be mixed.. .this is the answer:

on the _styles.css_ file find the **body** and my code looked like this:

```
body {
    margin: auto;
    -webkit-tap-highlight-color: #d3f9f2

    /* Disable selection/Copy of UIWebView */
    -webkit-touch-callout: none;
    -webkit-user-select: none;
}

```

that's cool for me,

thank you!

**Comment by folletto** [comment]
Great! 

Thank you. :)
