### ISSUE TITLE
Auto renewable subscription does not unlock the magazine 

### ISSUE THREAD

**Issue by codypallo** [Simbul/baker#960]
My app has been approved and is in the app store. Ive got a complaint that the auto renewable subscription was purchased but does not unlock the magazine for download at all. Instead they are prompted to buy the magazine. Any suggestions?

**Comment by folletto** [comment]
It's all about your server. How are you managing the subscription server-side? :)

**Comment by codypallo** [comment]
OK That helps. I put a request in to MagRocket. He's on US time though.

**Comment by folletto** [comment]
I'll close this issue then, it's likely on that side. :)

Thanks! :)

**Comment by nin9creative** [comment]
Were there any errors logged on the MagRocket backend system log?  Are you using the 1.0.1 version?

Regards,
Andrew

**Comment by codypallo** [comment]
Yes Im using 1.0.1 of the API

Undefined property: stdClass::$latest_receipt_info

2013-06-19 07:59:44 <-- This time stamp is must be GMT. I dont really know when this occurred today.
