### ISSUE TITLE
Navigation bar: wrong positioning

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#961]
Hello!
I've got some strange behavior from my navigation bar (with thumbnails)

So, I'm holding my iPad horizontally.
There's a bookshelf:
![Shelf](http://is.gd/Fx7KTq)

**All** my magazines are **portrait oriented** (magazine content rotating disabled!).

When I open an issue, I see the navigation bar at once:
(it is visible and positioned slightly upper, than needed)
![Bar](http://is.gd/l1DwQb)

When I perform **"doubleTap"** to see the upper buttons and navigation bar,
the bar itself moves to the midd;e of the screen:
![Bar in the middle](http://is.gd/ZeQEEQ)

And right after that, when I returning to the book shelf page (in portrait mode), 
I see the following (white space under the shelf content, - why??):
![shelf bottom cut](http://is.gd/evdlrD);

To fix the current state, we should several times change orientation of the book shelf - portrait/landscape.

So, what's wrong with all this?
Am I doing something wrong?

P.S.
Maybe the easiest solution will be - to disable rotating for the whole (Baker binaries?) app?

Or...???

**Comment by benoitchantre** [comment]
Which version of Baker do you use?
Did you have a look at the wiki about the index?

With a simple horizontal index at the bottom, you shouldn't have any issue.
You have probably used a wrong parameter in your index.
Did you use `meta-viewport` with a width of `device-width`?
If yes, use a value in pixels.

You can also have a look at the one provided with "A Study in Scarlet"'.
Issues #948 and #637 are related.

If you set the app in one orientation only, it should solve your issue too.

**Comment by divlv** [comment]
Sorry, didn't find in wiki, how to force bookshelf be in portrait orientation only...
(How to do it with magazine itself, I know, but for bookshelf...?)

**Comment by benoitchantre** [comment]
Make sure you are using Baker v. 4.1. It corrects some issues with the index bar.
In the [troubleshouting section about Index Bar](https://github.com/Simbul/baker/wiki/Adding-an-Index-Bar-to-your-publication#troubleshooting), its explained how to set `width` and `height`. That should help.
You need to check also [Baker extension parameters](https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters#book-extended-properties), at the end of the page you have some properties concerning the index.

**Comment by divlv** [comment]
> @benoitchantre:
> If you set the app in one orientation only, it should solve your issue too.

Hmm... I have looked through the _Baker extension parameters_, and didn't find any parameter,
which can restrict the _whole application_ (including BookShelf, not only magazine issue itself !), say, **only in portrait** mode.

Perhaps, @folletto knows... ;-)

**Comment by folletto** [comment]
To force the bookshelf in only one direction... it's done from Xcode itself. It's a standard app configuration. :)

For the issue you raised above, I don't know unfortunately. :)

**Comment by divlv** [comment]
Thanks, guys!
I've forced my App to operate only in portrait mode and it solves this problem.
