### ISSUE TITLE
Undesirable bookshelf behaviour when submitting a new issue/new in-app 

### ISSUE THREAD

**Issue by gdg87** [Simbul/baker#962]
Hi,
I release an app based on Baker 4.1, with some modification and a custom made backend, 
to deliver a bimonthly magazine.

When the app was accepted for the app store, it had some non consumable in-app and a paid subscrition.
All went well until the submission of a new issue, which is both a stand alone paid non consumable in-app, and one item of the annual paid subscrition.
I submitted the in-app for review and at the same time I added it to the bookshelf, to let it show in the app, allowing Apple to review it.

Being the single in-app still waiting for review, if the application is not launched on a develop device, the issue is showed, but with the spinner claiming it is waiting to retrieve the price, except for users that have already subscribed (because for those I automatically set the issue purchased in the backend server).

Maybe we lack a method to show the new published issue only to regular subscribers, hiding it to all the others until it's approved by Apple as a non consumable in-app?

Moreover, I wonder: how long does it tipically take for Apple to review and approve a single 
in-app issue? (my current issue has been in "wating for review" staus for more than a couple of days now... it could be a real pain if it were a daily or even a weekly publication... But Newsstand is indeed plenty of daily newspaper...)

**Comment by divlv** [comment]
+1
The same problem.
Need a solution so bad...

**Comment by Simbul** [comment]
This is really weird. It's hard to believe Apple will need you to include content in a live app _before_ they have approved it.
Are you sure you need to add your new issue to the shelf before Apple can review your new In-App Purchase? Wouldn't the screenshot and a description be enough?

**Comment by divlv** [comment]
Actually, it's a good option to test.
But as we can see in _In-App Purchase Details_, adding a **Non-Consumable** IAP, 

![In-App Purchase Details](http://is.gd/AB10sU)

In (an optional...) _Review Notes_ there's a place for information like **test accounts**, ect.
Does this mean - they want to see/download the content already...?

_Screenshot_ option - tells us, - we already should have at least a _Screenshot_ for our new issue...
" _Something stupid_... " (c) popular song

**Comment by folletto** [comment]
From what we found, the creation of In-App Purchases can (and likely, should) be done ahead of time.

From [here](http://forums.adobe.com/message/5226440):

> you would need to plan in advance and create advance in-app purchases so that they are approved before the publication date. 

So, create the In-App Purchases before you have to publish them, so they get approved first. Then, publish. :)

**Comment by divlv** [comment]
Ok, but what about information itself from these future issues?
Should the information itself be available for Apple to review? (to listen my magazine)

**Comment by folletto** [comment]
Read the thread linked above, it will probably give you a better idea. :)
Otherwise, please ask on Apple's Dev forums, it's a general iTunes question this one. :)

**Comment by alanfeng99** [comment]
Hello Dinamitrij,

Have you solved this problem?

I'm the project manager of a digital publishing company, we publish issues for our client, usually monthly magazine, and what we do is to submit an app binary with pre-defined local sqlite database so only reviewer can see the latest issue and test it's IAP functionality.

It currently works but sure takes us a lot of time preparing for all new issues every month.
Please share if you've found a better solution, thanks!
