### ISSUE TITLE
Disable the cache for development

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#964]
Some ressources (css, js, book.json, ...) are cached by the app.

That's great when ready to publish, but when you are working on the content you often make changes to your files. You can't be sure you see all your lastest changes unless you quit the app or you reset the simulator.

To avoid that, it would be a nice feature to have a setting to disable the cache. A warning associated with this setting would be needed to remember to change it before the final build).

**Comment by folletto** [comment]
I don't think it's possible: Baker doesn't do any caching, except for the `screenshot` mode, but there it's as simple as switching to `three-cards`. Any "caching" you see is done by Xcode or the Simulator itself, as far as I'm aware of.

**Comment by benoitchantre** [comment]
One solution is to add a timestamp or a version number after the file name.
For example `main.css?v2`.

This can be added automatically during the build process with grunt or another build tool.

@folleto, is there a similar cache for an app on a real device? If yes, is there any difference between an update of the app coming from Xcode (build for device) and an update coming from the AppStore?

**Comment by folletto** [comment]
The update mechanism for the App Store is a complete app replacement, while Xcode does just incremental updates of the files that have been changed. 

Also as said above, there's no other inherent caching, other than what the various API do (i.e. if you store data, that data is stored and persisted, but it's not "caching").

**Comment by benoitchantre** [comment]
Thanks for this information.

**Comment by folletto** [comment]
You're welcome! :)
