### ISSUE TITLE
Weekly magazine: Paid issues and Atom feed. Any experience?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#966]
Recently I have met 1 problem with paid issues on AppStore / iTunes Connect:
following all the notes and suggestions I have created In-App Purchase paid subscription,
Non-Consumable issue and everything looks OK on my device:
I see the paid issue for the particular price.
So... I'm trying to publish weekly paid magazine, so, when the new issue comes out, I have created another Non-Consumable issue in iTunes Connect, uploaded all the stuff and
I see my new issues in **Waiting for Review** status :-(
_(my first initial paid subscription and first paid issue were approved at once with Application itself)_

![Newly added paid issue](http://is.gd/bc48NU)

But, having weekly or even daily issues, we definitely need the faster processing from Apple side.
Some people from Apple Developers forum point to **Newsstand Atom feed**.
It's OK, but I can't found any information in their DOC regarding how to mark that this particular issue is **paid** one. 

Maybe anyone here got some experience in selling daily/weekly issues using _Newsstand Atom feed_ for faster processing?

Please, share some experience and/or "best practices".

Thanks in advance!

**Comment by folletto** [comment]
I don't have any, I'll let others answer. 
I'd suggest however given the kind of question to ask on Apple's Dev forums or Stackoverflow. :)

**Comment by gdg87** [comment]
I used atom feed for my app.
It isn't possible specify if a issue is paid or not. The available atom entry are the same as the table issue in newsstand section on itunes connect.
So in your atom must be the lastet issue and in 24 hours the change will be visible on itunes connect and in newstand section on the appstore.

**Comment by divlv** [comment]
So, you published **only free** issues that way?!
Or we can publish paid issues as well?

**Comment by gdg87** [comment]
You can publish paid issue, this information in the atom doesn't have any influence on the issue price.

**Comment by nin9creative** [comment]
The ATOM feed only feeds the information displayed in iTunes.  It doesn't have any affect on what you've submitted as paid issues to iTunes Connect for your application.  

From the Atom Feed .PDF Document

Overview
Newsstand is feature of iOS 5 that allows your readers to access the latest issue of your newspaper or magazine. You host your content on your web server and provide the App Store with an Atom feed that provides updated metadata and cover art for each issue as it becomes available. The Newsstand Atom Feed XML (described in this document) is used to enable the App Store to display your app with the cover art and metadata that is relevant to the latest issue.
This document specifies the Newsstand Atom Feed XML format for managing Newsstand issue metadata. Newsstand issue metadata is displayed on your Newsstand app’s product page in the App Store. The metadata provided should accurately reflect the issues and content that are available within your app.
Newsstand issue metadata can be managed via the Newsstand Atom Feed or directly in iTunes Connect. The Newsstand Atom Feed allows you to create new issues and update existing issues. The Newsstand Atom Feed is processed daily.

**Comment by divlv** [comment]
OK, guys, I think I need to clarify my question itself:

According to Baker's information, to publish a paid issue, and to **display its price** in the Baker's Book Shelf,
I need to create **Non-Consumable** In-App Purchase record in iTunes Connect.
Otherwise, I'll see endless "Updating price..." message (it was discussed here - #940) in the place of price, near the issue cover.

So, to sell the issues I need _Non-Consumable In-App Purchase_ record.
I do have one already - see the screenshot above.
But it is in _Waiting for Review status_.
It means it is _inactive_ yet.
That's why I see "Updating price..." message instead of price (0,89 Eur).
I understand why.
OK.

@gdg87 said - 

> this information in the atom doesn't have any influence on the issue price. 

So...
If it "have no influence", does it helps me to get my _Non-Consumable In-App Purchase_ record enabled in 1 day??

I think, we could have at least the same **ID**s for my paid issue in _Non-Consumable In-App Purchase_ record
and in Atom feed (to match these 2 records).

And the question may sounds like this: 
Does the Atom feed "forces" Apple to "enable" this _Non-Consumable In-App Purchase_ in 1 day?!

**Comment by gdg87** [comment]
This is the same problem that i have with my application and explained in issue #962. 
I had to wait 2 days (after chage atom and have the app in waiting for review status) to see my new in-app approved and see the price of the issue so the response to your question is no the Atom feed doesn't forces Apple to enable the In-App. The atom feed avoid only you to go on newsstand section in itunes connect end manually change the latest issue.

I think that atom content and issue approval are two sepatare things.

From apple description of Atom Feed:
"Feed information is processed once a day. After adding or updating your feed you may need to wait 24 hours before the change will be visible in iTunes Connect and/or on the App Stor"e.

I'm doing same test to avoid this trouble with price label of the issue but still i have not figured out how to avoid this problem.

**Comment by folletto** [comment]
I'll close this then since we already have #962 to track the issue. :)
