### ISSUE TITLE
Placing an ADS

### ISSUE THREAD

**Issue by Amboy16** [Simbul/baker#968]
Is it possible to put ads or hyperlink inside the page? any alternatives you can recommend?

**Comment by folletto** [comment]
It's HTML. Use any solution you'd like. :)

**Comment by Amboy16** [comment]
ive  tried using <a href cannot? im trying to put an ad that will redirect to my website..

**Comment by folletto** [comment]
As said, a Hpub is just HTML. You can do anything you can do in HTML. :)

**Comment by Amboy16** [comment]
tried but got no luck tried using js <a href doese work at all or is it because im using the simulator? havent tested it in ipad though...

**Comment by folletto** [comment]
As said, it's HTML. So, goes without saying: every HTML tag is supported, including `<a>`. 
If you need a reference, you can see that in the default book.

If something doesn't work, you really have to describe more about the problem, what you did, what you expected to happen and what happens instead. And ideally, go through the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page. :)

**Comment by Amboy16** [comment]
thanks for the very quick response and sorry for im being a newbie.. nweiz.. here it goes..

im creating an ipad app where in a certain page i want to put an ad that once you click it will redirect to external website or page like yahoo or google... <a href="http://www.yahoo.com">click here</a> in simulator yeah it is there but once you clicked nothing happens.... but if i used web browse it works :) and again sorry for being a newbie thanks

**Comment by folletto** [comment]
Then follow Problems and Debugging page... mostly at the part when it tells you to paste here the log and the file or code that has problems. :)

**Comment by marcheluis** [comment]
Maybe [THIS](https://github.com/Simbul/baker/wiki/Managing-links-and-urls#external-links) might be useful.

Using `?referrer=Baker` or `?referrer=Safari` to choose where the link will open, either inside Baker using a modal webview or using Safari.

**Comment by Amboy16** [comment]
oohh.... that works thaks guys....
