### ISSUE TITLE
Getting Started Here....

### ISSUE THREAD

**Issue by anelephantintheroom** [Simbul/baker#97]
Hi:

I looked at the book example provided, but was having a hard time understanding the full process even after reading the tutorial. I was hoping someone could help me get a better understanding of how this works? I have working knowledge of html 5 and CSS.

+How do I add sound/animation to the piece? Is it possible to program zoom in or interactivity via the touchscreen?
+If I was making a 12 page book, should each html file be a singular page? Would the scroll/page turn happen between each individual html file?
+Is it possible to add page turn transitions, or is the horizontal scroll the automatic default for each html page?
+How long does it take to publish to the iPad store? If I just want to make the files available for one or two other people to view, would they only be able to access it from my machine?

Thanks for your assistance.

**Comment by folletto** [comment]
1. In the same way you'd do in HTML5. Google for the various techniques, for example: http://html5doctor.com/native-audio-in-the-browser/
2. Yes: each HTML will be one page, and the turning is between each HTML page.
3. The transition is default, but you could change it modifying the Objective-C source code.
4. To make it available to one of two people it depends on who they are: you could show the HTML page itself on the web before including it in Baker, you could build with Baker and give them the developer versions or you could roll them out using the Ad-Hoc profile (the latter are all managed by Apple, check their documentation for that).

You're welcome. :)

**Comment by anelephantintheroom** [comment]
I am so sorry to ask you this annoying question. Can you just clarify for me, if I build it in Baker and give them the developer version, will that someone be able to read it on their iPad or see the page transition and hear any audio I add if they only had the developer version built in Baker? Does it take a long time (a few hours vs. several days) to build in Baker once the HTML 5 files are complete? 

Sorry for my confusion.

**Comment by folletto** [comment]
Well, I think that you could try doing it, experimenting is a great way to learn it. :)
Most of you questions are on the Apple side: Xcode, distribution and such, so there's a lot of documentation and tutorials out there to help you with it. :)

However:
1. The developer beta could be something like this: https://testflightapp.com/ or this: http://stackoverflow.com/questions/40154/how-do-you-beta-test-an-iphone-app
2. Once the HTML5 files are complete it's a matter of minutes: drop the book inside the book/ folder, compile and the only thing that remains to do is to distribute it (with one of the options above: dev, ad-hoc or store).

**Comment by therabidbanana** [comment]
We've been using testflightapp to distribute our internal books - I highly recommend it. You still have to go to Apple's provisioning center and add devices individually to your "distribution certificate", which is pretty complicated if you've never done something like that before (I spent several hours fighting with the code signing nonsense before I got my app deployed on somebody else's iPad)

**Comment by folletto** [comment]
Uhm I think I can mark this discussion as closed. :)
