### ISSUE TITLE
Tech U is live on the App Store

### ISSUE THREAD

**Issue by nfeiglin** [Simbul/baker#970]
My magazine based off Baker, Tech U, is live. Download it: http://bit.ly/getTechU
![ipad-lifestyle3](https://f.cloud.github.com/assets/3063367/691816/f3e0e5b6-dbc9-11e2-93ab-d56d24af2244.jpg)

**Comment by nin9creative** [comment]
Cool!  Congrats :)

Regards,
Andrew

**Comment by nfeiglin** [comment]
Thanks Andrew :)

Closed #970
