### ISSUE TITLE
Languages mismatch in AppStore and iTunesConnect

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#971]
I've got the strange situation:

I see that my _language_ flags does not match in AppStore and iTunesConnect...

![Languages mismatch](http://is.gd/cu9M8O)

"Russian" option (on the right side) is correct one,
but in AppStore I see **Language: English**
What's wrong?
Why _Language: English_ ?
Xcode settings, or... what?

**Comment by Simbul** [comment]
You should really ask this one in the Apple forums, as it looks like an App Store / iTunes Connect issue ;)
