### ISSUE TITLE
"Invalid product identifier" and "param 'product_id' type is wrong"

### ISSUE THREAD

**Issue by JosephMacReady** [Simbul/baker#972]
Hey, 
Thanks to all again for the amazing support and development in the Baker community. 
I'm editing a magazine and after setting iTunes Connect and my server storage by the instructions for "Newsstand and Free Issues" I have errors with two things - 
- the free subscription and 
- issue product IDs. 

Considering the subscription problem, what Xcode lets me know is: 
- Invalid product identifier: com.valkalinic.enactmentmag.subscriptions.free
- Trying to buy unavailable product com.valkalinic.enactmentmag.subscriptions.free 
  which lead to "Subscription failure"  

while the identifier is identical to the one in iTunes Connect (as is the bundle ID, com.valkalinic.enactmentmag) 

And the product ID for the issue; 
- it gets downloaded and unzipped correctly 
- reports "ERROR: param 'product_id' type is wrong. Check it in 'book.json'"
  which leads to "Book Enactment could not be initialized (There was an error opening this issue. Try downloading it again)"  

while the issue's book.json's product ID is set to "product_id": "com.valkalinic.enactmentmag.products.july13" which is the same as the Non-Consumable In-App Purchase for the issue. 

What am I missing? Please say if you need any more info to know, many thanks

**Comment by nin9creative** [comment]
If its a free subscription, your issues will not have product ids.

Regards,
Andrew

**Comment by JosephMacReady** [comment]
Hi Andrew @nin9creative  , thank you for your kind reply, 
removed the ID from the book.json and the issue from iTunes Connect, it can now be opened and read normally! The subscription in sandbox works too! :) 
Will thank you all in there and let you know when it's out
