### ISSUE TITLE
Refresh and subscription button disappeared in navigationBar

### ISSUE THREAD

**Issue by Regolo-Design** [Simbul/baker#973]
Hi,
i changed the background image in the navigation bar with fireworks .png and rewrite it. 

The refresh and the subscription button are disappeared in the navigationBar. How i can restore them? 
Sorry for my english

**Comment by Regolo-Design** [comment]
Resolved downloading a new version of Baker.

Thank you for this software.

**Comment by Regolo-Design** [comment]
Now i can't view the "Back" button

**Comment by folletto** [comment]
It's really hard to tell without any more detail. You need to add as much information as you can for other to help you. :)

Check the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page on the wiki. :)

**Comment by folletto** [comment]
Hello. Did you solve the issue? May I ask you what was the cause and how did you solve it? :)

**Comment by Regolo-Design** [comment]
Yes i was modified the navigationBar accidentally, sorry for the open issue.

**Comment by folletto** [comment]
Oh, I see. :)

Thanks for the follow-up. :)
