### ISSUE TITLE
Customizing the back button

### ISSUE THREAD

**Issue by JosephMacReady** [Simbul/baker#975]
Hey, 
I can't find the code resulting in the Back button on the html view's navigation bar that takes the view back to the issues shelf
(
![ios simulator screen shot jun 25 2013 8 39 18 pm](https://f.cloud.github.com/assets/830461/704722/e19e1bd6-ddc6-11e2-980a-d561df22c929.png)
)
Where can I find it and customize? 
Thanks!

**Comment by folletto** [comment]
If I remember correctly we don't do anything with it, it's natively provided by the `UINavigationBar`. If you want to customize it, you have to add the code to do it yourself.

Check around threads like this one on Stackoverflow:
http://stackoverflow.com/questions/6003082/custom-uinavigationbars-backbutton

**Comment by JosephMacReady** [comment]
Thanks! I'll look into it and post what I found out :)

**Comment by JosephMacReady** [comment]
update: exactly! and also note that it may be more adequate to create a custom button and make it replace the default back button. Thank you @folletto ! :)

**Comment by folletto** [comment]
Great! :)
