### ISSUE TITLE
Are people interested in a hosted baker backend?

### ISSUE THREAD

**Issue by bingimar** [Simbul/baker#978]
Been working on a backend for baker for a couple of magazines, are people in general interested in a hosted service?

**Comment by tekdope** [comment]
Depends on the Backend and what it does. I guess a lot of people around here are using their own server and in house solutions. On my side i'm using Magrocket, which i like a lot since it's open source i can add functions and having it on my own servers. But if you have a killer backend all-in one solution it could be interesting.
My two cents.

**Comment by bingimar** [comment]
what's a killer backend with all-in one solution?

**Comment by tekdope** [comment]
I guess it will be different for each people. We don't have all the same needs. :)
Do you plan to launch something similar to MagRocket ?

**Comment by nin9creative** [comment]
I've been asking the same questions :)

**Comment by bingimar** [comment]
Well I guess a nice feature to have would be in-app sales figures. It would be similar to MagRocket but different, without saying anything about Andrews good work, it's just I really dislike php :)

**Comment by folletto** [comment]
Why don't you join up contributing to MagRocket instead? :)
Yes, you might dislike PHP, but... ;)

**Comment by nin9creative** [comment]
I would tend to think that if you are talking about Paid subscriptions that iTunes Connect provides much of the sales type data...  

The reason I chose PHP is generally because it's something easy for folks to get setup.  PHP/MySQL are supported on pretty much every commodity Linux hosting account out there.  Easy to deploy, easy to manage.

**Comment by nin9creative** [comment]
I'm with @folletto on that :)  I could use some help... LOL

**Comment by tekdope** [comment]
That was my next comment :) :+1:

**Comment by nin9creative** [comment]
Also I'm a bit biased as the MagRocket Cloud Console will hopefully be here sometime soon for those that don't want to install their own MagRocket instances... :)

**Comment by folletto** [comment]
OH YEAH! :D

**Comment by bingimar** [comment]
Yeah don't get me wrong, I'm not questioning your work. 

iTunes Connect does provide much of that data but presents them in a very poor way. There are some services that gather comments, sales etc in a nice dashboard, I'm sure that wouldn't be terrible difficult to make.

Maybe I'll pitch in for MagRocket.

**Comment by nin9creative** [comment]
Well, a dashboard of sorts has always been in the cards for MagRocket...  At least from the perspective of the stats and data that MagRocket knows about.  

If @folletto and team expose a nice Analytics API within Baker - there are lots more things that we could tap into as well related to actual end user activity within the Publications.

:)  hint hint lol

**Comment by folletto** [comment]
;)

**Comment by JamesMowatt** [comment]
For stats and monitoring I have tied in a self hosted version of countly, it provides huge amounts of information. You just need to have a setting to turn off certain monitoring at the users request.

**Comment by Teklink** [comment]
It should be pretty easy to add in Google Analytics right? I'm no iOS coder but it doesn't seem too difficult (famous last words!)

Either way, i'm interested in a hosted backend :)

**Comment by nin9creative** [comment]
Google Analytics is pretty easy to add in...

Regards,
Andrew

**Comment by nin9creative** [comment]
I tried installing it before and ran into issues with the setup.  Did you have any problems?  Like their end user UI.

Regards,
Andrew
