### ISSUE TITLE
Loading text

### ISSUE THREAD

**Issue by mimetic** [Simbul/baker#98]
Currently, a loading chapter displays a number. It's the number of that file in the list of files. 
However, if I have a forward or a table of contents, then the loader shows "3" when I'm loading chapter 1.

I've modified my class to show "Loading...", but it would be niftier if the text to be shown came from the HTML file, no? I think this was working before.

**Comment by folletto** [comment]
It's one of the modifications made in Laker, that we are considering adding... Thanks for opening the ticket so we can track it. :)

**Comment by jonniejoejonson** [comment]
Is there a way on the laker framework to change the color of the loading background from black to white?... 
regards J

**Comment by folletto** [comment]
On Baker, yes, open the file RootViewController (https://github.com/Simbul/baker/blob/master/Classes/RootViewController.m) and you'll see a few configuration constants at the top of the file, two of them control the background: SCROLLVIEW_BGCOLOR and PAGE_NUMBERS_COLOR. :)

**Comment by jonniejoejonson** [comment]
Thanks Folletto, i will take a look at that. I'm actually trying to get the laker one to go from black to white, so there would be no need to change your one... im assuming that there is no way to get rid of the loading pages altogether?... kind regards J

**Comment by folletto** [comment]
It's the same thing on the two, since Laker is still Baker at the core.

You can try downloading the master branch from GitHub, we are working trying to optimize page loading. It's hard, but we have something. ;)
See Issue #27 for more infos.

**Comment by jonniejoejonson** [comment]
Thanks Folletto, i wish i understood the coding involved to help this project, but sadly im a web developer and new to xcode... thanks for your help... it would be really cool to preload all the pages and remove the need for the loading page.. so that you can see one page slide out as the new page slides in...
I will take a look at the master branch... thanks for your help... regards J

**Comment by folletto** [comment]
It isn't easy, but that's exactly what we are working on. :)

**Comment by jonniejoejonson** [comment]
Im sure it is difficult, my brain hurts just trying to understand the first thing to do with xcode... You have a really nice product already, but i think this improvement would be the icing on the cake... i wish you the best of luck.... kind regards J

**Comment by usaps** [comment]
hi, I will love to have a loading image for each chapter, even if it has to be hard coded :)

**Comment by folletto** [comment]
...well, er... you have to code it yourself. ;)

**Comment by usaps** [comment]
yeah I know ;)

**Comment by laswell** [comment]
Haha, the "coding it yourself" that the bit that always trips me up!

**Comment by Xm4s** [comment]
I've just added the page titles in the loading screens, just below the page numbers, as in Laker Compendium by @ffranke.
Some feedbacks before closing this up are appreciated as usual :)

**Comment by folletto** [comment]
Ok I'll check asap. ;)

**Comment by Simbul** [comment]
Implemented in 352093f0056090f3be8d6cfe69ebfa4b13e2ed24.

**Comment by folletto** [comment]
Worth considering: on the actual beta of iOS5 the spinner doesn't show up on back background, they changed the grey sprite. We'll check again before the final iOS5 release.

**Comment by lostinjapan** [comment]
I just wanted to say that I can't find the constant SCROLLVIEW_BGCOLOR or PAGE_NUMBERS_COLOR in the link that was in this thread. Am I missing something? The page numbers don't match up with the pages I'm loading, so I want to change the page number color to hide them. 

https://github.com/Simbul/baker/blob/master/Classes/RootViewController.m

Can someone tell me the line number in that file to change? Thanks in advance.

**Comment by lostinjapan** [comment]
nevermind! I found it! It's a constant now. My bad :)

"-baker-page-numbers-color": "#FFFFFF",
