### ISSUE TITLE
What is Default-568h@2x.png used for?

### ISSUE THREAD

**Issue by Teklink** [Simbul/baker#980]
I've been looking through the code and can't see any reference to the graphic Default-568h@2x.png.

Can you tell me where this image is used and what it is used for?

**Comment by benoitchantre** [comment]
It's the default launch image for iPhone5.
I think it's here because it's the only way to define it. For other devices, you can set launch images with Xcode.

**Comment by Teklink** [comment]
ah, thanks for that. I'm just focusing on the iPad to start with so i've no need to worry about it then.
