### ISSUE TITLE
Chapter numbers while page is loading

### ISSUE THREAD

**Issue by bsjosten** [Simbul/baker#982]
When flipping from page to page, the background shows the chapter number and title while the new page is loading.

How do I modify the numbers shown to reflect my chapter true number? My publication starts with a cover and an index, so my first chapter is shown as "3" instead of "1".

In other words, I would like to skip the first two numbers and go directly to 3. Alternatively, just delete the chapter numbers and only show the title.

Thanks,

/Bo

**Comment by folletto** [comment]
Hello! :)

That code is automatic, so you have to modify Baker in order to do that. See the `buildPageDetails` function.

As an alternative, you could include pre-rendered screenshots that replace the numbering.

**Comment by folletto** [comment]
Hello! 
Were you able to make it work? :)

**Comment by bsjosten** [comment]
Davide,

Yes, I modified the code successfully.

Thanks!

/Bo

**Comment by folletto** [comment]
Great! :D
