### ISSUE TITLE
How do I open a http hyperlink in Safari on iPad instead of the modal webview

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#985]
When I create a hyperlink, such as www.google.com, it opens in a modal view within the baker app.

I'd like the link to open Safari on the iPad.  Is this possible?

**Comment by Simbul** [comment]
Yes, see the wiki page on [Managing links and urls](https://github.com/Simbul/baker/wiki/Managing-links-and-urls#external-links).

**Comment by callaght** [comment]
Thank you!  Adding the param ?referrer=Safari solved my problem
