### ISSUE TITLE
My Index Bar won't scroll

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#986]
I have an index bar in my magazine, but it does not scroll.  It's static and no amount of swiping will make it move.  The pages that are displayed can be tapped on though and they do take me to the correct page.

I've read through https://github.com/Simbul/baker/wiki/Adding-an-Index-Bar-to-your-publication and my index.html does not have: - 

<meta name="viewport" content="width=2000; height=200" /> 

But, my json file does contain: - 

"-baker-index-width": 768,
"-baker-index-height": 400,

So everything looks right to me as according to the documentation the json params override the index.html.

Its probably something obvious but I cannot work out why it can't get it to scroll - can anybody point me in the right direction?

**Comment by folletto** [comment]
It's difficult to say... let's see, could you post a screenshot and the `index.html` code? :)

**Comment by callaght** [comment]
Thanks for offering to take a look.  This is my index.html: -

```
{
    "hpub": 1,
    "title": "Slapshot Magazine Issue 1",
    "author": [
        "Tom Callaghan"
    ],
    "creator": [
        "Tom Callaghan"
    ],
    "date": "2013-06-30",
    "url": "book://tomcallaghan-slapshotmagazineissue1",
    "orientation": "both",
    "zoomable": false,
    "-baker-background": "#ededed",
    "-baker-vertical-bounce": true,
    "-baker-media-autoplay": false,
    "-baker-page-numbers-color": "#000000",
    "-baker-rendering": "three-cards",
    "-baker-index-width": 768,
    "-baker-index-height": 400,
    "cover": "tomcallaghan-slapshotmagazineissue1.png",
    "contents": [
        "0001.html",
        "0002.html",

..and so on..

        "0063.html",
        "0064.html"
    ]
 }
```

**Comment by folletto** [comment]
That might help, but it's the `book.json` not the `index.html` (and screenshot). :D

**Comment by callaght** [comment]
oops sorry.  Here's index.hml: -

```
<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8">
<title>Slapshot Magazine Issue 1</title>
<meta name="generator" content="In5 v1.4.20">
<meta name="description" content="Slapshot is a magazine about all things Ice Hockey and will be published monthly on Apple Newsstand.">
<meta name="author" content="Tom Callaghan">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script type="text/javascript">window.jQuery || document.write('<script src="assets/js/jquery.min.js"><\/script>')</script>
<script type="text/javascript" src="assets/js/vmouse.min.js"></script>
<script type="text/javascript" src="assets/js/swfobject.js"></script>
<script type="text/javascript" src="assets/js/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="assets/js/jquery.touchSwipe.min.js"></script>
<script type="text/javascript" src="assets/js/in5.config.js"></script>
<link rel="stylesheet" href="assets/css/pages.css">




</head>

<body>
<div id="container">
<ul class="thumbs">
  <li>
    <a href="0001.html">
      <img width="150" src="assets/images/pagethumb_0001.jpg"/>
    </a>
  </li>
  <li>
    <a href="0002.html">
      <img width="150" src="assets/images/pagethumb_0002.jpg"/>
    </a>
  </li>

..and so on..

  <li>
    <a href="0063.html">
      <img width="150" src="assets/images/pagethumb_0063.jpg"/>
    </a>
  </li>
  <li>
    <a href="0064.html">
      <img width="150" src="assets/images/pagethumb_0064.jpg"/>
    </a>
  </li>
</ul>
<nav>
<button id="nextBtn" name="nextBtn">&nbsp;</button>
<button id="backBtn" name="backBtn">&nbsp;</button>
</nav>
<div id="prefooter" style="float:left;height:1px;">&nbsp;</div>
</div>
<div id="in5footer">Built with <a href="http://ajarproductions.com/pages/products/in5/?ref=footer" target="_blank" >In5</a>.</div>
</body>

</html>
```

![img_0041](https://f.cloud.github.com/assets/4885291/727930/db082432-e1cd-11e2-94ac-73077f38df75.jpg)

**Comment by folletto** [comment]
The problem might be all that JavaScript included, that seems handling the swipe. Baker index doesn't need anything to handle the swipe, since a page that's already wide will automatically scroll if swiped with nothing else needed.

I would suggest to try building the index by hand, or maybe just trying to remove these items... it might work.

_P.S. check the link "GitHub Flavored Markdown" just above the comment box: you'll find there the syntax to include code (using the "`" character)._

**Comment by nin9creative** [comment]
It looks like you are doing this with in5 right?

I have had the same issue recently when playing around with it.  Once exported, the horizontal swiping doesn't work for the index bar.  I think this might be an export bug with in5 or something related to what they are doing...

Are you exporting / building a retina compliant magazine?  That's another issue I had with in5 - issues with the viewport and scaling the retina size image to work correctly - another bug I think.

**Comment by justinputney** [comment]
Hi,
That does appear to be an issue with in5. You can uncheck Use Swipe and re-export from ID, or simply edit the following line in assets/js/in5.config.js:
FROM:
var container = $('#container');
TO:
var container = $('#slider');

We will update this code internally so that it does not create this issue going forward.

**Comment by callaght** [comment]
Cheers for your suggestion folletto.  I tried removing all javascript and different combinations but still no scrolling unfortunately.

nin9creative, yeah using in in5, great piece of software!

I'll post screenshots shortly.

justinputney, saw your post appear while typing this - I'll try your suggestion...

**Comment by callaght** [comment]
![screen shot 2013-07-05 at 17 00 36](https://f.cloud.github.com/assets/4885291/754540/0191621e-e58c-11e2-927e-b0d970ad41b3.png)

**Comment by callaght** [comment]
![screen shot 2013-07-05 at 17 00 48](https://f.cloud.github.com/assets/4885291/754544/148c7b10-e58c-11e2-9ddf-18de3d923148.png)

**Comment by callaght** [comment]
![screen shot 2013-07-05 at 17 00 57](https://f.cloud.github.com/assets/4885291/754546/1dc0b89a-e58c-11e2-81b0-8c1d25dbe7fa.png)

**Comment by callaght** [comment]
these are my current in5 export settings

**Comment by justinputney** [comment]
You can uncheck Enable Swipe and that should do it.

I would remove the screencap containing your serial # if I were you. ;)

**Comment by justinputney** [comment]
P.S. You can also set useSwipe at the top of assets/js/in5.config.js to false if you don't want to re-export.

**Comment by nin9creative** [comment]
Justin, what are the optimum settings for export when using a Portrait Retina Indesign document.  I have nothing but trouble to get it to fit on the retina ipad.  It's ways zoomed in.  I've played with all combinations of viewport settings and setting the hpub property for zoom able etc.

Regards,
Andrew

**Comment by justinputney** [comment]
I would imagine that matching the pixels values for that size would be optimal.

When you change the viewport settings--does it have any effect?

**Comment by callaght** [comment]
Just tried: -

useSwipe = true;
var container = $('#container');
..
useSwipe = true;
var container = $('#slider');
..
useSwipe = false;
var container = $('#slider');
..
useSwipe = false;
var container = $('#container');
..

But still no index bar scroll

**Comment by justinputney** [comment]
Then it may not be in the in5 javascript. Since setting useSwipe to false, should effectively shut off any page swipe by in5.

That doesn't rule out CSS changes, though. But I'm not sure what they'd be...

**Comment by tonyrh** [comment]
I'm not an expert but maybe changing the width here

```
"-baker-index-width": 768,
```

to something bigger should make the index scroll.

**Comment by folletto** [comment]
Check the demo book: there's no js, nothing at all. And it scrolls. It works because the page is simply larger than the screen. :)

@tonyrh That's the size of the visible part on screen. I'm quite sure it won't work if you try to make it larger than the screen. ;)

**Comment by callaght** [comment]
tonyrh, worth a go!, I'll try: -

--in5.config.js--

```
useSwipe = false;
var container = $('#container');
```

--book.json--

```
"-baker-index-width": 7680,
```

**Comment by callaght** [comment]
yes that worked!!!

Thank you!

**Comment by rlarrett** [comment]
I had this problem. When IN5 creates a Baker HPUB it assigns a default width and height for the index.html in the JSON file:

```
    "-baker-index-width": 768,
    "-baker-index-height": 400,
```

Which can be deleted.

**Comment by justinputney** [comment]
When I did my initial testing with Baker, I needed those values for the thumbnails to work properly. However, if it would be better to remove those in the output, I can easily make that update.

Anyone feel free to chime in if you've also had experience with the index height/width. Thanks!

**Comment by callaght** [comment]
Yep, removing those 2 lines from book.json also made the index bar scroll.

So, in summary, to resolve the issue, I have: -

--in5.config.js--
useSwipe = true; -->CHANGED TO--> useSwipe = false;

--book.json--
DELETED --> "-baker-index-width": 768,
DELETED --> "-baker-index-height": 400,

**Comment by justinputney** [comment]
The predefined values for index width/height have be removed within in5 1.5.1 (which actually looks better than before). There should be no need to remove these settings from the JSON file going forward.

Additionally, swiping will be disabled on the index page by default.

**Comment by folletto** [comment]
That's good news. I'll mark this issue as closed then. :)
