### ISSUE TITLE
Contents Menu Dissapeared

### ISSUE THREAD

**Issue by Bonet83** [Simbul/baker#987]
I accidentally dragged upward the bottom menu and disappeared. Can i lock the menu in this direction?

**Comment by folletto** [comment]
If you mean the index, the solution is simple: make the `index.html` page as high as the height of the index height. Might require some CSS rework, I guess...

**Comment by Bonet83** [comment]
If i set a "min-height"? Can this solve the problem?

**Comment by folletto** [comment]
All depends on your CSS, you just have to try and fix the layout of the page until it works.

**Comment by Bonet83** [comment]
Thanks i´m trying. You know "trial and error method"

**Comment by Bonet83** [comment]
I can´t fix the "index bar" issue. Everytime i launched the app it appears with an vertical scroll bar at the right side. I´ve tried all the possible solutions published on this forum but doesn´t works.

Please it´s a client project and i had to fix it.

**Comment by folletto** [comment]
Please note that even if I think the explanation is just in crafting a different CSS, you are not providing anything here that might give others clues on how to help you. :)

**Comment by Bonet83** [comment]
Here is my book.json

```
{
    "title": "Title",
    "author": ["Jorge Bonet"],
    "creator": ["Jorge Bonet"],
    "date": "2013-08-01",
    "url": "book://lakercompendium.com/book/",

    "orientation": "portrait",
    "zoomable": false,

    "-baker-background": "#fff",
    "-baker-vertical-bounce": true,
    "-baker-media-autoplay": true,
    "-baker-index-height":204,
    "-baker-background-image-portrait": "images/background-portrait.png",
    "-baker-background-image-landscape": "images/background-landscape.png",
    "-baker-page-numbers-color": "#333",


    "contents": [
                 "Cover.html",
                 "UsoyNavegacion.html",
                 "Introduction.html",
                 "Publicidad001.html",
                 "Interactivity.html",
                 "Structure_and_Columns.html",
                 "Maps.html"
                 ]
```
