### ISSUE TITLE
Rejected Binary (Issue 1):  No In App Purchase API

### ISSUE THREAD

**Issue by jbavington** [Simbul/baker#989]
Hey crew,

I submitted a Binary and got it rejected for a few reasons.
#1:

We found that while you have submitted In App Purchase products for your app, the In App Purchase functionality is not present in your binary.

If you would like to utilize In App Purchase in your app, you will need to upload a new binary that incorporates the In App Purchase API to enable users to make a purchase

Once you revise and resubmit your binary, you will also need to resubmit your In App Purchases for review since they are in the state Developer Action Required. For each IAP product submitted, please be sure to edit the detail information or cancel the request to change the detail information for the In App Purchases using iTunes Connect.

For more information on how to implement In App Purchase in your application, please refer to the In App Purchase Programming Guide.

---

I have tested the subscribe ($4.99) and issue download ($1.99) in Xcode using a test account in the Sandbox and it successfully purchases.  This is the 2nd time Apple has rejected for this reason.  The 1st time around, I told them this function was BUILT IN to the Binary.   However, they came back with the above.

Any ideas appreciated.

Here is a screenshot of my IAP setup in iTunes:

![iap list](https://f.cloud.github.com/assets/4700969/734237/f5423e38-e2bc-11e2-8442-3e0c0cca01ef.png)

In the `Constants.h` file in the project, I have this:

```
#define AUTO_RENEWABLE_SUBSCRIPTION_PRODUCT_IDS [NSArray arrayWithObjects: \
                @"ca.rb.aboutcanada.baker.subscriptions.1year", \
            nil]
```

I don't have anything for Free Subscriptions.  Originally I had both free and paid in the Project, but Apple came back about not handling Free subscriptions properly so I removed it and just have the above paid.

The JSON file on my server is as follows:

```
[
  {
    "name": "about-canada-2013-07",
    "title": "About Canada -- July 2013",
    "info": "Canada Day, Moving to Canada, Focus on the North",
    "date": "2013-06-24 12:01:01",
    "cover": "http://www.mi.ca/clients/rbrown/issues/2013-07.png",
    "url": "http://www.mi.ca/clients/rbrown/issues/2013-07.hpub",
    "product_id": "ca.rb.aboutcanada.baker.issues.2013.07"
  }
]
```

Thanks in advance for any assistance.

Jason

**Comment by jbavington** [comment]
Additional error log notes on this one.  When I run the project through Xcode, I see the following:

_2013-07-02 19:17:43.913 Baker[2149:1a303] ERROR: Could not parse response from purchases API call. Received: 3c627220 2f3e0a3c 623e5761 726e696e 673c2f62 3e3a2020 666f7065 6e286c6f 672f6c6f 675f3230 31332d30 372d3032 2e747874 29205b3c 61206872 65663d27 66756e63 74696f6e 2e666f70 656e273e 66756e63 74696f6e 2e666f70 656e3c2f 613e5d3a 20666169 6c656420 746f206f 70656e20 73747265 616d3a20 5065726d 69737369 6f6e2064 656e6965 6420696e 203c623e 2f736d61 7274686f 7374696e 672f636f 6e74656e 742f6d2f 6d692f2e 77656273 69746531 37352f63 6c69656e 74732f72 62726f77 6e2f6170 702f6c69 622f4b4c 6f676765 722e7068 703c2f62 3e206f6e 206c696e 65203c62 3e313834 3c2f623e 3c627220 2f3e0a3c 6272202f 3e0a3c62 3e466174 616c2065 72726f72 3c2f623e 3a202055 6e636175 67687420 65786365 7074696f 6e202750 444f4578 63657074 696f6e27 20776974 68206d65 73736167 65202753 514c5354 4154455b 48593030 305d3a20 47656e65 72616c20 6572726f 723a2031 3420756e 61626c65 20746f20 6f70656e 20646174 61626173 65206669 6c652720 696e202f 736d6172 74686f73 74696e67 2f636f6e 74656e74 2f6d2f6d 692f2e77 65627369 74653137 352f636c 69656e74 732f7262 726f776e 2f617070 2f746162 6c65732e 7068703a 32320a53 7461636b 20747261 63653a0a 2330202f 736d6172 74686f73 74696e67 2f636f6e 74656e74 2f6d2f6d 692f2e77 65627369 74653137 352f636c 69656e74 732f7262 726f776e 2f617070 2f746162 6c65732e 70687028 3232293a 2050444f 2d266774 3b657865 63282743 52454154 45205441 424c4520 49462e2e 2e27290a 2331202f 736d6172 74686f73 74696e67 2f636f6e 74656e74 2f6d2f6d 692f2e77 65627369 74653137 352f636c 69656e74 732f7262 726f776e 2f617070 2f686561 6465722e 70687028 3137293a 20726571 75697265 5f6f6e63 6528272f 736d6172 74686f73 74696e67 2f632e2e 2e27290a 2332202f 736d6172 74686f73 74696e67 2f636f6e 74656e74 2f6d2f6d 692f2e77 65627369 74653137 352f636c 69656e74 732f7262 726f776e 2f617070 2f707572 63686173 65732e70 68702838 293a2072 65717569 72655f6f 6e636528 272f736d 61727468 6f737469 6e672f63 2e2e2e27 290a2333 207b6d61 696e7d0a 20207468 726f776e 20696e20 3c623e2f 736d6172 74686f73 74696e67 2f636f6e 74656e74 2f6d2f6d 692f2e77 65627369 74653137 352f636c 69656e74 732f7262 726f776e 2f617070 2f746162 6c65732e 7068703c 2f623e20 6f6e206c 696e6520 3c623e32 323c2f62 3e3c6272 202f3e0a_

Thanks.

**Comment by folletto** [comment]
What's in your `PURCHASES_URL` in `Constants.h`?

**Comment by jbavington** [comment]
Hi there,

I have this:

#define PURCHASES_URL @"http://www.mi.ca/clients/rbrown/app/purchases.php"

When I run that PHP file directly, I see this:

```
Warning: fopen(log/log_2013-07-03.txt) [function.fopen]: failed to open stream: Permission denied in /smarthosting/content/m/mi/.website175/clients/rbrown/app/lib/KLogger.php on line 184

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 14 unable to open database file' in /smarthosting/content/m/mi/.website175/clients/rbrown/app/tables.php:22 Stack trace: #0 /smarthosting/content/m/mi/.website175/clients/rbrown/app/tables.php(22): PDO->exec('CREATE TABLE IF...') #1 /smarthosting/content/m/mi/.website175/clients/rbrown/app/header.php(17): require_once('/smarthosting/c...') #2 /smarthosting/content/m/mi/.website175/clients/rbrown/app/purchases.php(8): require_once('/smarthosting/c...') #3 {main} thrown in /smarthosting/content/m/mi/.website175/clients/rbrown/app/tables.php on line 22
```

I have the database file sitting here:

http://www.mi.ca/clients/rbrown/app/db/baker.sqlite3  and it has a filesize of 0

The database file has permissions "776"

Thanks.

**Comment by folletto** [comment]
Then I guess you have some problem on the server side of things. It's strange tho if it worked before you submitted to Apple. Was anything changed?

Did you try asking on MagRocket's issue tracker? :)

**Comment by jbavington** [comment]
Hi,

I think it didn't wok before I submitted to Apple, either.

Not sure why it can't open the database file.

I haven't checked out MagRocket.  Is the server software from them?  

Thanks.

**Comment by folletto** [comment]
Uhm. What server software are you using? :)

**Comment by jbavington** [comment]
https://github.com/Simbul/baker-server-example

Thanks.

**Comment by folletto** [comment]
You mean the example server that says in big letters: **"Disclaimer: This server is provided as an example and it should never be used in production."**? ;)

So, well. Don't use it in production. Check [MagRocket](http://www.magrocket.com/) or [Newsstand DIY](https://newsstanddiy.herokuapp.com/). :)

**Comment by jbavington** [comment]
Yes, that's the one exactly!  :)

Sooooo much self-inflicted digital misery....

I'll check out MagRocket, thanks!

**Comment by jbavington** [comment]
MagRocket worked beautifully (after figuring out some .htaccess hiccups).  Thank you!  Very cool admin/api server software.

Your support is awesome!

**Comment by nin9creative** [comment]
So you got the .htaccess issue resolved?  Good.  If you don't mind chiming in on the Issue you logged for MagRocket with your fix/or the issue you ended up having that'd be good (in case others run into the same).

**Comment by jbavington** [comment]
I installed MagRocket admin and api, carefully working through the docs.  Updated Constants.h with the new URL's.  Then updated the MagRocket api .htaccess file, as it wasn't redirecting properly (for our setup).

See logged issue here:  https://github.com/nin9creative/magrocket-backend/issues/76

Thanks again.

**Comment by folletto** [comment]
Ok, I'm closing this then. :)
