### ISSUE TITLE
Memory problems?

### ISSUE THREAD

**Issue by mimetic** [Simbul/baker#99]
Well, I'm in the field and cannot investigate, but it seems I am still getting memory problems. On occasions, I was getting memory warnings 1 and 2. Now, as I try to show the book, it often loads incorrectly. That is, images in my code don't load, especially after running other large apps. 

If anyone has testing to discover whether the browser simply won't load images at times? How to test? 

Sorry to be so vague. Maybe when I am home I can figure out how to test. Meanwhile it means the book is unstable and I cannot publish. 

Note, I do have a form of memory management in my JavaScript. I unload large images when not shown.

**Comment by folletto** [comment]
What version are you using? The latest master?

However yes, if you could provide more informations at home it would be valuable. :)

**Comment by folletto** [comment]
Were you able to test it? Is it the same thing you were discussing in the topic three-cards? :)

**Comment by folletto** [comment]
Ok, I'll close. I'll reopen if you can confirm it. ;)
