### ISSUE TITLE
Before submit to the AppStore

### ISSUE THREAD

**Issue by jamesBar** [Simbul/baker#995]
Hi, I been working with Baker & MagRocket for my magazine and it's great, I'm gonna submit my app for review in the next days but I am new in this proccess, this is my first time submitting an app to the appStore, so before to do that i want to know:

First, how many issues of my magazine do I need in my server? I have just one in this moment, is it enough for the review?  And second, i'm using MagRocket for the server side, the Apple reviewers need to have access to my server and see how I manage all the data? 

Any help will be appreciated, Thanks.

**Comment by nin9creative** [comment]
They don't need access to the server end.  Just make sure to leave it in
development mode while they are reviewing it....

**Comment by jamesBar** [comment]
Ok but how do they test the notifications part? or they don't test that? I mean, you need to enter to the server if you want to send a notifications for the users

**Comment by nin9creative** [comment]
Pretty sure they just test that the issues work and any purchase functions.

**Comment by jamesBar** [comment]
Ok thanks, i'm gonna submit my app the next week and wait for the approval
